### ISSUE TITLE
0002042:
saving of product with linked lead does not work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1103]
**Reported by pschuele on 5 Jan 2010 16:19**

saving of product with linked lead does not work

**Additional information:** Fatal error: Uncaught exception &#039;ErrorException&#039; with message &#039;Argument 1 passed to Zend_Json_Server_Request::setOptions() must be an array, null given, called in /opt/local/tine/2009-11-2/htdocs/Tinebase/Server/Json.php on line 59 and defined&#039; in /opt/local/tine/2009-11-2/htdocs/library/Zend/Json/Server/Request.php:74 Stack trace: #0 /opt/local/tine/2009-11-2/htdocs/library/Zend/Json/Server/Request.php(74): Tinebase_Core::errorHandler(NULL) #1 /opt/local/tine/2009-11-2/htdocs/Tinebase/Server/Json.php(59): Zend_Json_Server_Request-&gt;setOptions() #2 /opt/local/tine/2009-11-2/htdocs/Tinebase/Core.php(192): Tinebase_Server_Json-&gt;handle() #3 /opt/local/tine/2009-11-2/htdocs/index.php(51): Tinebase_Core::dispatchRequest() #4 {main} thrown in /opt/local/tine/2009-11-2/htdocs/library/Zend/Json/Server/Request.php on line 74

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jan 2010 16:41**

json encoding/decoding goes wrong (it seems that it happens already in the client). the Tinebase_Server_Json can&#039;t decode the json data when saving a product that is linked to lots of leads.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Jan 2010 13:16**

seems to be a problem with php fcgi and big json post data (~ +250kb)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Jan 2010 16:45**

this is not a tine problem. we did some tests with transmitting json with post requests and had issues on a system with mod-fgcid. we switched to standard libapache2-mod-php5 and the problems were gone.
