### ISSUE TITLE
0002464:
Error: add new contact (IE 8)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1312]
**Reported by unknown user on 23 Mar 2010 13:50**

**Version:** git master

Errormessage (IE 8): &quot;Ihre Sitzung ist ausgelaufen. Bitte melden Sie sich erneut an.&quot;  in POPUP Window

**Additional information:** 2010-03-23T13:45:34+00:00 INFO (6): exception &#039;Zend_Session_Exception&#039; with message &#039;This session is not valid according to Zend_Session_Validator_HttpUserAgent.&#039; in /var/www/2010-03-ms2/library/Zend/Session.php:782
Stack trace:
#0 /var/www/2010-03-ms2/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /var/www/2010-03-ms2/Tinebase/Core.php(506): Zend_Session::start()
#2 /var/www/2010-03-ms2/Tinebase/Server/Abstract.php(44): Tinebase_Core::setupSession()
#3 /var/www/2010-03-ms2/Tinebase/Server/Http.php(31): Tinebase_Server_Abstract-&gt;_initFramework()
#4 /var/www/2010-03-ms2/Tinebase/Core.php(184): Tinebase_Server_Http-&gt;handle()
#5 /var/www/2010-03-ms2/index.php(56): Tinebase_Core::dispatchRequest()
#6 {main}

**Comment by Gloirin** [comment]
Related to #1310

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Mar 2010 15:53**

somehow (perhaps with installed Developertoolbar) the IE changes his User Agent string. we should add a config option to disable the exception and log this in all cases.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Mar 2010 16:12**

added config option sessionUserAgentValidation to disable exception and increase logging
