### ISSUE TITLE
0002494:
Active Sync: Email sync fails with invalid number in response on Android

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1327]
**Reported by Canny on 27 Mar 2010 15:28**

**Version:** Mialena (2010-03) Milestone 2

The sync of Emails on Android fails with a NumberFormat exception. The exception was also present in the August release of Tine 2.0.

Tine 2.0 reponse:

2010-03-09T23:48:58+00:00 DEBUG (7): ActiveSync_Command_Wbxml::getResponse::129 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot;&gt;&lt;Status&gt;1&lt;/Status&gt;&lt;SyncKey&gt;1&lt;/SyncKey&gt;&lt;Changes&gt;&lt;Count&gt;3&lt;/Count&gt;&lt;Add&gt;&lt;ServerId&gt;addressbook-root&lt;/ServerId&gt;&lt;ParentId&gt;0&lt;/ParentId&gt;&lt;DisplayName&gt;Addressbook&lt;/DisplayName&gt;&lt;Type&gt;9&lt;/Type&gt;&lt;/Add&gt;&lt;Add&gt;&lt;ServerId&gt;tasks-root&lt;/ServerId&gt;&lt;ParentId&gt;0&lt;/ParentId&gt;&lt;DisplayName&gt;Tasks&lt;/DisplayName&gt;&lt;Type&gt;7&lt;/Type&gt;&lt;/Add&gt;&lt;Add&gt;&lt;ServerId&gt;calendar-root&lt;/ServerId&gt;&lt;ParentId&gt;0&lt;/ParentId&gt;&lt;DisplayName&gt;Calendar&lt;/DisplayName&gt;&lt;Type&gt;8&lt;/Type&gt;&lt;/Add&gt;&lt;/Changes&gt;&lt;/FolderSync&gt;

Android Exception:

D/EAS_SyncEngine(  415): 06021143 syncMailFolderAndUpdAccount(): mFolderSyncKey equals initial sync key, update account
D/MailSyncSource(  415): 06021143 &gt; updAccount()
D/MyWidgetViewWL(  189): message widget observer onChange, isDelete false
D/MailSyncSource(  415): 06021143 &lt; updAccount(): true
D/EAS_SyncEngine(  415): 06021143 &lt; syncMailFolderAndUpdAccount(), return: true
W/System.err(  415): java.lang.NumberFormatException:
W/System.err(  415):    at org.apache.harmony.luni.util.FloatingPointParser.parseDblImpl(Native Method)
W/System.err(  415):    at org.apache.harmony.luni.util.FloatingPointParser.parseDouble(FloatingPointParser.java:283)
W/System.err(  415):    at java.lang.Double.parseDouble(Double.java:285)
W/System.err(  415):    at java.lang.Double.valueOf(Double.java:324)
W/System.err(  415):    at com.htc.android.mail.eassvc.core.SyncManager.createAccount(SyncManager.java:7742)
W/System.err(  415):    at com.htc.android.mail.eassvc.EASAppSvc$MailBlockCommandHandler.createAccount(EASAppSvc.java:5837)
W/System.err(  415):    at com.htc.android.mail.eassvc.EASAppSvc.createAccount(EASAppSvc.java:6144)
W/System.err(  415):    at com.htc.android.mail.eassvc.EASAppSvc$EasAuthenticator.addAccount(EASAppSvc.java:444)
W/System.err(  415):    at android.accounts.AbstractAccountAuthenticator$Transport.addAccount(AbstractAccountAuthenticator.java:118)
W/System.err(  415):    at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:67)
W/System.err(  415):    at android.os.Binder.execTransact(Binder.java:287)
W/System.err(  415):    at dalvik.system.NativeStart.run(Native Method)
D/EAS_AppSvc(  415): 06021143 initSyncOption()
D/EAS_AppSvc(  415): 06021143 getSyncOptionFromCustomization
D/EAS_AppSvc(  415): 06021143 customize mail truncation size: 4
D/EAS_AppSvc(  415): 06021143 syncSchedule: 4

**Additional information:** see for more information: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=3028

**Comment by Gloirin** [comment]
**Comment posted by Canny on 25 Apr 2010 16:56**

Now I can describe the problem more in detail:

I dumped the traffic with Tine and an MS Exchange Server syncing with my Android device.

The exception occurs when the phone process the follwoing response, that telling that there are no new mails to sync with tine::

&lt;FolderSync&gt;
    &lt;Error&gt;
        &#039;1&#039;
    &lt;/Error&gt;
    &lt;SyncKey&gt;
        &#039;1&#039;
    &lt;/SyncKey&gt;
    &lt;Changes&gt;
        &lt;Count&gt;
            &#039;0&#039;
        &lt;/Count&gt;
    &lt;/Changes&gt;
&lt;/FolderSync&gt;

**Comment by Gloirin** [comment]
**Comment posted by Canny on 27 Apr 2010 05:10**

Here is the complete traffic of Tine compared with Exchange. What I recognized ist that Exchange does not respond on the first Android request, so the device fires 2 requests before the response.

:: Tine ::

Request:

&lt;FolderSync&gt;
    &lt;SyncKey&gt;
        &#039;1&#039;
    &lt;/SyncKey&gt;
&lt;/FolderSync&gt;

Response:

&lt;FolderSync&gt;
    &lt;Error&gt;
        &#039;1&#039;
    &lt;/Error&gt;
    &lt;SyncKey&gt;
        &#039;1&#039;
    &lt;/SyncKey&gt;
    &lt;Changes&gt;
        &lt;Count&gt;
            &#039;0&#039;
        &lt;/Count&gt;
    &lt;/Changes&gt;
&lt;/FolderSync&gt;

:: Exchnage ::

Request:

&lt;FolderSync&gt;
    &lt;SyncKey&gt;
        &#039;{A7DD87D2-985B-4599-98D2-DE1679A92218}1&#039;
    &lt;/SyncKey&gt;
&lt;/FolderSync&gt;

Request:

&lt;GetItemEstimate&gt;
    &lt;Folders&gt;
        &lt;Folder&gt;
            &lt;FolderType&gt;
                &#039;Email&#039;
            &lt;/FolderType&gt;
            &lt;FolderId&gt;
                &#039;34b8d4b61c185647b6b24c1908944187-8004b5d&#039;
            &lt;/FolderId&gt;

            &lt;FilterType&gt;
                &#039;2&#039;
            &lt;/FilterType&gt;
            &lt;SyncKey&gt;
                &#039;{39B06346-F5B1-4D6C-9288-422A4DD5C981}3&#039;
            &lt;/SyncKey&gt;
        &lt;/Folder&gt;
    &lt;/Folders&gt;
&lt;/GetItemEsitmate&gt;

Response:

&lt;GetItemEstimate&gt;
    &lt;Response&gt;
        &lt;Error&gt;
            &#039;1&#039;
        &lt;/Error&gt;
        &lt;Folder&gt;
            &lt;FolderType&gt;
                &#039;Email&#039;
            &lt;/FolderType&gt;
            &lt;FolderId&gt;
                &#039;34b8d4b61c185647b6b24c1908944187-8004b5d&#039;
            &lt;/FolderId&gt;
            &lt;Estimate&gt;
                &#039;0&#039;
            &lt;/Estimate&gt;
        &lt;/Folder&gt;
    &lt;/Response&gt;
&lt;/GetItemEsitmate&gt;

Request:

&lt;Synchronize&gt;
    &lt;Folders&gt;
        &lt;Folder&gt;
            &lt;FolderType&gt;
                &#039;Email&#039;
            &lt;/FolderType&gt;
            &lt;SyncKey&gt;
                &#039;{39B06346-F5B1-4D6C-9288-422A4DD5C981}3&#039;
            &lt;/SyncKey&gt;
            &lt;FolderId&gt;
                &#039;34b8d4b61c185647b6b24c1908944187-8004b5d&#039;
            &lt;/FolderId&gt;
            &lt;DeletesAsMoves /&gt;
            &lt;GetChanges /&gt;
            &lt;MaxItems&gt;
                &#039;100&#039;
            &lt;/MaxItems&gt;
            &lt;Options&gt;
                &lt;FilterType&gt;
                    &#039;2&#039;
                &lt;/FilterType&gt;
                &lt;Truncation&gt;
                    &#039;4&#039;
                &lt;/Truncation&gt;
                &lt;Conflict&gt;
                    &#039;1&#039;
                &lt;/Confilt&gt;
            &lt;/Options&gt;
        &lt;/Folder&gt;
    &lt;/Folders&gt;
&lt;/Synchronize&gt;

Response:

&lt;Synchronize&gt;
    &lt;Folders&gt;
        &lt;Folder&gt;
            &lt;FolderType&gt;
                &#039;Email&#039;
            &lt;/FolderType&gt;
            &lt;SyncKey&gt;
                &#039;{39B06346-F5B1-4D6C-9288-422A4DD5C981}3&#039;
            &lt;/SyncKey&gt;
            &lt;FolderId&gt;
                &#039;34b8d4b61c185647b6b24c1908944187-8004b5d&#039;
            &lt;/FolderId&gt;
            &lt;Error&gt;
                &#039;1&#039;
            &lt;/Error&gt;
        &lt;/Folder&gt;
    &lt;/Folders&gt;
&lt;/Synchronize&gt;

**Comment by Gloirin** [comment]
**Comment posted by Canny on 30 Apr 2010 05:50**

The problem can be also reproduced on the HTC Desire

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Apr 2010 06:10**

Very good! That should help me solving the problem. I try to modify the code over the day.

**Comment by Gloirin** [comment]
**Comment posted by Canny on 30 Apr 2010 11:21**

That sounds great. Please let me know, when you modified the code. I will test it and give you some feedback.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Apr 2010 12:02**

I changed to code to return nothing, when no new folders are availble.

Can you please try if this helps?

**Comment by Gloirin** [comment]
**Comment posted by Canny on 30 Apr 2010 12:46**

Unfortunately I could not really try it. For now I used Mialena M2. Today I upgraded the first time to the SVN head revision. Now I get a general sync error independant of the mail sync problem. Maybe there are some other changes in ActiveSync after M2 that cause that.

I try to found out more at the weekend and keep you up to date.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Apr 2010 12:51**

If you can switch back to M2 just have a look at ActiveSync/Command/FolderSync.php line 161. Just add the new return line. That&#039;s all I changed.

            if($count &gt; 0) {
                $newSyncKey = $this-&gt;_syncKey + 1;
            } else {
                // test: don&#039;t return anything if $count = 0
                return;
                $newSyncKey = $this-&gt;_syncKey;
            }

**Comment by Gloirin** [comment]
**Comment posted by Canny on 30 Apr 2010 13:07**

I switched back to M2 and can sync my calendar and contacts as before the update, but the mail sync doesn&#039;t work, but with another exception than the NumberFormatException. It just said that there are generel sync errors on mail sync. Unfortunately your (test) fix doesn&#039;t work. :-( You can test it yourself with your HTC Tattoo.

I will try to give you a detailed log about the generel sync errors with the current head revision.

**Comment by Gloirin** [comment]
**Comment posted by Canny on 30 Apr 2010 14:14**

The problem with the head revision calendar and contact sync was a problem with the Android device. If you active mail sync in your exchange account settings it is activated all the time, also if it is deselected. So calendar and contact sync failed in every further tries. Dumb HTC implementation!!!

I think you have to respond the Tine request with the exchange responds, otherwise it will not work. Sorry, that I can&#039;t support you with the implementation, because of my not present PHP skills.

That is the current debug output during mail sync on Android:

/System.err(  260): org.xmlpull.v1.XmlPullParserException: Illegal input format (position:START_DOCUMENT null) 
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.WbxmlParser.exception(WbxmlParser.java:631)
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.WbxmlParser.setInput(WbxmlParser.java:476)
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.SyncManager.getFolderHierarchy(SyncManager.java:700)
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.SyncManager.syncMailFolderAndUpdAccount(SyncManager.java:6395)
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.SyncManager.doSync(SyncManager.java:613)
W/System.err(  260): 	at com.htc.android.mail.eassvc.core.SyncManager.doSync(SyncManager.java:473)
W/System.err(  260): 	at com.htc.android.mail.eassvc.EASAppSvc$ContactsCommandHandler.handleMessage(EASAppSvc.java:4307)
W/System.err(  260): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(  260): 	at android.os.Looper.loop(Looper.java:123)
W/System.err(  260): 	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 6 May 2010 17:03**

Status update: I was able to get synchronisation working between the HTC Tattoo and another ActiveSync server. I need to debug the difference yet, but we are on a good way.

**Comment by Gloirin** [comment]
**Comment posted by Canny on 6 May 2010 18:49**

Was your tested Server and Mircroft Exchange Server? Does the response differ from the response I posted in the note above? Isn&#039;t it enough to use my posted response as reference? Thanks for your effort.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 May 2010 09:44**

No. It was not enough, as the response was mostly equal to ones generated by Tine 2.0.

In the end it was one space character in the OPTIONS response.

-header(&quot;MS-ASProtocolVersions: 2.5, 12.0&quot;);
+header(&quot;MS-ASProtocolVersions: 2.5,12.0&quot;);

After removing the space character the HTC Tattoo is working without any problems.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 May 2010 09:47**

The problem should be solved now. Please update from svn and reopen this ticket if the problem still exists.
