### ISSUE TITLE
0002712:
add keyboard shortcuts for tabs in edit dlgs

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1435]
**Reported by cweiss on 2 Jun 2010 10:23**

**Version:** Mialena (2010-03) Beta 1

i.e. to speed up customfields in timetracker

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 4 Jan 2012 12:32**

in editdialog ctrl + n-number switches to the nth tab

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2012 12:48**

this is not working for me. i get this error:

Tine.widgets.dialog.KeyShortcutsEditDialogPlugin::onRender
KeyShortcutsEditDialogPlugin.js:55TypeError: Cannot call method &#039;on&#039; of null
    at Object.enable (http://localhost/tine20/library/ExtJS/ext-all-debug.js:13943:15)
    at Object.&lt;anonymous&gt; (http://localhost/tine20/library/ExtJS/ext-all-debug.js:13783:10)
    at Object.onRender (http://localhost/tine20/Tinebase/js/widgets/dialog/KeyShortcutsEditDialogPlugin.js?1325759574:49:33)
    at [object Object].onRender (http://localhost/tine20/library/ExtJS/adapter/ext/ext-base-debug.js:1595:25)
    at [object Object].render (http://localhost/tine20/library/ExtJS/ext-all-debug.js:15381:18)
    at [object Object].renderItem (http://localhost/tine20/library/ExtJS/ext-all-debug.js:19211:19)
    at [object Object].&lt;anonymous&gt; (http://localhost/tine20/library/ExtJS/ext-all-debug.js:19202:22)
    at [object Object].renderAll (http://localhost/tine20/library/ExtJS/ext-all-debug.js:19588:56)
    at [object Object].&lt;anonymous&gt; (http://localhost/tine20/library/ExtJS/ext-all-debug.js:19188:14)
    at [object Object].onLayout (http://localhost/tine20/library/ExtJS/ext-all-debug.js:19438:50)

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 6 Jan 2012 14:12**

new Plugin: Tinebase/js/ux/TabPanelKeyPlugin.js
ux.tabpanelkeyplugin
