### ISSUE TITLE
0002736:
Courier IMAP server now seems to be unsupported

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1447]
**Reported by jleg on 8 Jun 2010 14:21**

**Version:** Mialena (2010-03) Beta 1

whereas Courier worked quite well with older versions of tine (2009), in current versions there seem to be lots of problems, which renders current felamimail quite unusable.
Perhaps i&#039;ve missed some config options - at least those accessable through tine i all tried (did not find addtional related config.inc docs)
(The following is done with &quot;caching  &#039;active&#039; =&gt; 0&quot; in config.inc...)

1) folder hierarchies are only displayed &quot;sometimes&quot;
- click on folder yields in
2010-06-08T13:29:43+00:00 INFO (6): Tinebase_Server_Json::_handle::87 is JSON request. method: Felamimail.updateFolderStatus
2010-06-08T13:29:43+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::44 Connecting to server xxxt:993 (SSL) with username xxx@xxx.net
2010-06-08T13:29:44+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Kunden not found ... Error: cannot change folder, maybe it does not exist

- updating &quot;folder cache&quot; manually then seems to work
2010-06-08T13:31:24+00:00 INFO (6): Felamimail_Controller_Cache_Folder::update::112 trying to get subfolders of INBOX.Kunden.
2010-06-08T13:31:24+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::350 Adding new folder INBOX.Kunden.Anfragen to cache.

- only page reload finally makes the fold/unfold handles visible

- after that, the sub folders are visible and accessable

2) Inbox email list does not update, or updates incorrectly
- looks like as if new mails are only shown when internal intervall shoots - &quot;Aktualisieren&quot;-button does not have any visible effect
- old mails - deleted by another client - are not removed; if selected, a message is logged, but list still is not updated:
2010-06-08T13:41:38+00:00 DEBUG (7): Tinebase_Server_Json::_handleException::165 exception &#039;Felamimail_Exception&#039; with message &#039;Message not found. Maybe it was deleted by another client.&#039; in /home/www/sites/xxx/csl/tine/Felamimail/Controller/Message.php:235

deleted entries remain visible, even if the list is updated with new mails

3) Namespace &quot;INBOX&quot;
 it looks like as if the &quot;default namespace&quot; of Courier is not handled correctly.
Clients like Thunderbird, Horde, Roundcube all can be either configured to use the general namespace prefix &quot;INBOX.&quot; - or they detect it automatically, since Courier &quot;tells&quot; it to the client.
In both cases, the &quot;INBOX&quot; layer is hidden, and the standard hierarchy is shown, including a nice &quot;Posteingang&quot; instead of &quot;INBOX&quot;.
Also, all system folders like &quot;Trash&quot; or &quot;Sent&quot; are &quot;found&quot; without having to configure the prefix for each addtionally.
 

**Additional information:** additional log excerpts showing some errors during normal operation:
lots of this one:
2010-06-08T12:48:43+00:00 INFO (6): Felamimail_Controller_Cache_Message::update::151 Try to get message uids from 6628 to 1 from imap server.
2010-06-08T12:48:44+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_addMessages::535 Failed to create cache entry for msg 6629 | Re: Protokollfragen.... Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;6629-965c74408518e7de8c090b6057103abd98cb395c&#039; for key 2

sometimes:
2010-06-08T12:49:09+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_updateFolderStatus::247 Getting status and values for folder INBOX.Staff.Aldem
2010-06-08T12:49:09+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::261 Non-standard IMAP server. Trying to guess uidnext by getting all Uids. Maybe it does not work.
2010-06-08T12:49:09+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_updateFolderStatus::272 Cache of folder INBOX.Staff.Aldem is incomplete.

(folder *is* accessible after making the folder hierarchy &quot;visible&quot; (s.a.))

lots of this while felamimail seems to read and cache another folder - seems to be the 1st level below &quot;INBOX&quot; which do have subfolders:
2010-06-08T14:12:33+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::44 Connecting to server xxx:993 (SSL) with username xxx@xxx.net
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Staff not found ... Error: cannot change folder, maybe it does not exist
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Lieferanten not found ... Error: cannot change folder, maybe it does not exist
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Listen not found ... Error: cannot change folder, maybe it does not exist
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Privat not found ... Error: cannot change folder, maybe it does not exist
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Kunden not found ... Error: cannot change folder, maybe it does not exist
2010-06-08T14:12:33+00:00 NOTICE (5): Felamimail_Controller_Cache_Folder::_updateFolderStatus::242 Folder INBOX.Z-Archive not found ... Error: cannot change folder, maybe it does not exist

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 9 Jun 2010 22:26**

That&#039;s bad! I will have a look at this problem next week.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 17 Jun 2010 04:18**

Just a short status update. 

We have fixed multiple problems in the email application. There still some problems left open. When have fixed all major problems, we will release a new stable release.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 Jul 2010 17:49**

Seems like we have fixed all major problems. We will release new packages tomorrow. 

Please try them and report back any problems.

**Comment by Gloirin** [comment]
**Comment posted by jleg on 13 Jul 2010 12:03**

yes, this looks *much* more better now. However, there are still some issues...
tested environment was
- Courier-IMAP 4.5.1
* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION STARTTLS XMAGICTRASH] Courier-IMAP ready. Copyright 1998-2008 Double Precision, Inc.  See COPYING for distribution information.
- emptied all felamimail_cache-tables (MySQL)
- enabled memcached in config.php.inc
- deleted imap account entries in felamimail table (MySQL)
- re-created imap account with tine
- did a &quot;Reload Folder List&quot; (=&gt; translation missing)

1) Inbox works now - external changes are reflected, &quot;Reload&quot;-Action shows results, deleted messages are &quot;hidden&quot; - great!
Though i think it is more common to have a &quot;flat&quot; hierarchy for &quot;Inbox&quot;, showing it in the same level like other folders (making &quot;subfolders&quot; to real &quot;folders&quot;)

2) Problem - only the first subfolder has a handle to unfold its subsubfolders - i did not manage to access subfolders (containing folders) or to make the fold/unfold handle visible; selecting one of these result in displaying that little retrieval pie chart, but with no progress (and no activity in tine log).

3) unfold the first subfolder, selected one subsubfolder: tine began to retrieve messages, but: the selected sort order was &quot;date&quot;, &quot;descending&quot; - however, the first page shown was a sequence of messages &quot;in the middle&quot; of that folder. To view the most recent messages i had to wait until the complete folder was read from imap server - that&#039;s not really practical, though full retrieval might not happen that often...

4) minor: nice little &quot;pie chart&quot; showing the progress of retrieval - but it seems to show wrong numbers (half amount -  &#039;25%&#039; when in fact msg &#039;5000 of 10000&#039; is retrieved; instead of &#039;0%&#039;, &#039;NaN%&#039; is shown in tooltip; well, and &quot;Hohle Nachricht&quot; is a &#039;defamation&#039; ;-) - messages which get &quot;geholt&quot; are *not* &quot;hohl&quot;...

5) even more minor: though &quot;Trash&quot; now is refreshingly named &quot;Mülleimer&quot; :) - &quot;sent-mail&quot; got its special icon, but no name; and perhaps also &quot;Drafts&quot; could have some special handling. Would probably cover most meta folders, and enables full localisation.

6) probably normal behaviour (?) - when in &quot;idle mode&quot;, e.g. having selected inbox view, the tine apache is constantly &quot;hammered&quot; with 4-5 POST requests per second with some memcached &#039;Felamimail.updateMessageCache&#039; requests. They seem not to be related to the current view; though they might be ready a some point (?), they could become critical in case more than one user is working with tine...
In case felamimail simply uses memcached to mirror the complete mysql cache tables (??), i&#039;d fear that this would render the memcached unusable - at least for lots of people having lots of mails...
(though memcached memory footprint does not indicate this &#039;full mirroring&#039; - seems to be too small?) 

That&#039;s it for now; i&#039;d say the only bigger issue is the &quot;subfolder detection&quot; - cool work otherwise!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Nov 2010 14:59**

@jleg please test this when beta packages are available (or with trunk if you like)

**Comment by Gloirin** [comment]
**Comment posted by jleg on 12 Nov 2010 14:22**

which beta packages? i&#039;m not aware of any currently... (?)
i&#039;m running version 2010-03-7 - which still behaves as described.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Nov 2010 14:40**

we plan to release a beta of the next release at the end of november.

i&#039;ll let you know.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Dec 2010 17:28**

please test the new beta1 packages and report back if they support the courier imap server!

-&gt; http://www.tine20.org/index.php?id=54

**Comment by Gloirin** [comment]
**Comment posted by jleg on 14 Dec 2010 08:21**

well, according to your roadmap ticket #2736 is scheduled for &quot;beta 2&quot; - so do you expect any changes also for &quot;beta 1&quot;?

Nevertheless i gave it a try - and it looks quite similar to what i found last time.
Still main issue: Folder hierarchy is incomplete, first layer/level of folders is only shown partially (complete on first access, mostly missing after &quot;ordnerliste aktualisieren&quot;), second layer of folders (sub and sub-sub folders) is missing completely.


From the log:
ce6a2 xxx - 2010-12-13T12:06:32+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::274 Do not add folder INBOX.Kunden. It is not selectable.
ce6a2 xxx - 2010-12-13T12:06:32+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::274 Do not add folder INBOX.Lieferanten. It is not selectable.
ce6a2 xxx - 2010-12-13T12:06:32+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::274 Do not add folder INBOX.Listen. It is not selectable.
ce6a2 xxx - 2010-12-13T12:06:32+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::274 Do not add folder INBOX.Privat. It is not selectable.
ce6a2 xxx - 2010-12-13T12:06:32+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.Spam
ce6a2 xxx - 2010-12-13T12:06:32+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.Temp
ce6a2 xxx - 2010-12-13T12:06:32+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.Templates
ce6a2 xxx - 2010-12-13T12:06:32+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.Trash
ce6a2 xxx - 2010-12-13T12:06:32+00:00 INFO (6): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::274 Do not add folder INBOX.Z-Archive. It is not selectable.
ce6a2 xxx - 2010-12-13T12:06:32+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.sent-mail


Incomplete folders list (first layer) probably related to exceptions like this:

89da3 xxx - 2010-12-13T12:04:00+00:00 INFO (6): Felamimail_Controller_Cache_Message::_expungeCacheFolder::179 Removing no longer existing folder INBOX.Kunden from cache. cann
ot change folder, maybe it does not exist
89da3 xxx - 2010-12-13T12:04:00+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::167 exception &#039;Felamimail_Exception_IMAPFolderNotFound&#039; with message &#039;IMAP folder no
t found.&#039; in /home/www/sites/xxx/csl/tine/Felamimail/Controller/Cache/Message.php:181
Stack trace:
#0 /home/www/sites/xxx/csl/tine/Felamimail/Controller/Cache/Message.php(134): Felamimail_Controller_Cache_Message-&gt;_expungeCacheFolder(Object(Felamimail_Model_Folder), Object(F
elamimail_Backend_ImapProxy))
#1 /home/www/sites/xxx/csl/tine/Felamimail/Frontend/Json.php(157): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;5de5f4ae9a0a238...&#039;, 120)
#2 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;5de5f4ae9a0a238...&#039;, 120)
#3 /home/www/sites/xxx/csl/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 /home/www/sites/xxx/csl/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 /home/www/sites/xxx/csl/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 /home/www/sites/xxx/csl/tine/Tinebase/Server/Json.php(133): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 /home/www/sites/xxx/csl/tine/Tinebase/Server/Json.php(73): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#8 /home/www/sites/xxx/csl/tine/Tinebase/Core.php(209): Tinebase_Server_Json-&gt;handle()
#9 /home/www/sites/xxx/csl/tine/index.php(56): Tinebase_Core::dispatchRequest()
#10 {main}

**Comment by Gloirin** [comment]
**Comment posted by jleg on 14 Dec 2010 08:26**

addendum: it looks like as if &quot;Do not add folder INBOX.XY. It is not selectable.&quot; now always shows up in log for folders which do contain subfolders...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Dec 2010 10:25**

ah, that makes sense, somehow courier does not mark folders as selectable. perhaps we should remove this and maybe it will work then.

could you just remove the &quot;continue;&quot; in line 276 in Felamimail_Controller_Cache_Folder and try again?

**Comment by Gloirin** [comment]
**Comment posted by jleg on 14 Dec 2010 10:59**

with commenting out this line, folders now are displayed again - and with unfold-handles, that&#039;s a progress!

However, usage still is quite limited:
- item 3) from #2266 (above) is still a problem - opening a folder with &quot;some more mails&quot; just to access the most recent ones takes *ages* until something is shown, and that what *is* shown then is not from recent mails, but from some period &quot;in between&quot;...

- lots of errors/stack traces in the log (simply when clicking on a folder):

tine claims &quot;removed folders&quot; (though they are not removed of course):
c0707 xxx - 2010-12-14T10:41:11+00:00 INFO (6): Felamimail_Controller_Cache_Message::_expungeCacheFolder::179 Removing no longer existing folder INBOX.CSL-Staff from cache. cannot change folder, maybe it does not exist
c0707 xxx - 2010-12-14T10:41:11+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::167 exception &#039;Felamimail_Exception_IMAPFolderNotFound&#039; with message &#039;IMAP folder not found.&#039; in /home/www/sites/XXX/csl/tine/Felamimail/Controller/Cache/Message.php:181
Stack trace:
#0 /home/www/sites/XXX/csl/tine/Felamimail/Controller/Cache/Message.php(134): Felamimail_Controller_Cache_Message-&gt;_expungeCacheFolder(Object(Felamimail_Model_Folder), Object(Felamimail_Backend_ImapProxy))
#1 /home/www/sites/XXX/csl/tine/Felamimail/Frontend/Json.php(157): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;65d9a80330c8159...&#039;, 120)
#2 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;65d9a80330c8159...&#039;, 120)
#3 /home/www/sites/XXX/csl/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 /home/www/sites/XXX/csl/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 /home/www/sites/XXX/csl/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 /home/www/sites/XXX/csl/tine/Tinebase/Server/Json.php(133): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 /home/www/sites/XXX/csl/tine/Tinebase/Server/Json.php(73): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#8 /home/www/sites/XXX/csl/tine/Tinebase/Core.php(209): Tinebase_Server_Json-&gt;handle()
#9 /home/www/sites/XXX/csl/tine/index.php(56): Tinebase_Core::dispatchRequest()
#10 {main}


lots of errors regarding not-found-messages (of a just cached folder?)

9939c xxx - 2010-12-14T10:43:16+00:00 INFO (6): Tinebase_Server_Json::_handle::89 is JSON request. method: Felamimail.updateMessageCache
9939c xxx - 2010-12-14T10:43:16+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::167 exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Felamimail_Model_Folder record with id 65d9a80330c8159a0137e9e70dfddf77374621aa not found!&#039; in /home/www/sites/XXX/csl/tine/Tinebase/Backend/Sql/Abstract.php:179
Stack trace:
#0 /home/www/sites/XXX/csl/tine/Tinebase/Backend/Sql/Abstract.php(154): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;65d9a80330c8159...&#039;, &#039;id&#039;, false)
#1 /home/www/sites/XXX/csl/tine/Felamimail/Controller/Folder.php(166): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;65d9a80330c8159...&#039;)
#2 /home/www/sites/XXX/csl/tine/Felamimail/Controller/Cache/Message.php(124): Felamimail_Controller_Folder-&gt;get(&#039;65d9a80330c8159...&#039;)
#3 /home/www/sites/XXX/csl/tine/Felamimail/Frontend/Json.php(157): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;65d9a80330c8159...&#039;, 120)
#4 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;65d9a80330c8159...&#039;, 120)
#5 /home/www/sites/XXX/csl/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 /home/www/sites/XXX/csl/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 /home/www/sites/XXX/csl/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 /home/www/sites/XXX/csl/tine/Tinebase/Server/Json.php(133): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 /home/www/sites/XXX/csl/tine/Tinebase/Server/Json.php(73): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#10 /home/www/sites/XXX/csl/tine/Tinebase/Core.php(209): Tinebase_Server_Json-&gt;handle()
#11 /home/www/sites/XXX/csl/tine/index.php(56): Tinebase_Core::dispatchRequest()
#12 {main}
9939c xxx - 2010-12-14T10:43:16+00:00 WARN (4): Tinebase_Core::errorHandler::329 json_encode() [&lt;a href=&#039;function.json-encode&#039;&gt;function.json-encode&lt;/a&gt;]: recursion detected in /home/www/sites/XXX/csl/tine/library/Zend/Json.php::122 (2)

Additionally, the frontend shows a yellow exclamation-mark-icon with the imap account line, which probably is related to the errors from log:

&quot;Ihre Anfrage konnte aufgrund von fehlenden Daten nicht beantwortet werden. In den meisten Fällen wurden diese Daten von einem anderen Benutzer gelöscht. Bitte aktualisieren Sie Ihre momentane Ansicht.&quot;

or

&quot;Ein Ordner wurde von einem anderen Klienten gelöscht. Bitte aktualisieren Sie Ihren Browser.&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Dec 2010 11:21**

perhaps you need to clear the database again (at least the felamimail_folder table) to make sure that your cached folders are consistent.

maybe the &#039;INBOX.CSL-Staff&#039; folder name is problematic (because of the &#039;-&#039;).

the exclamation mark in the client shows that there have been exceptions on the server like folder/message not found.

to 3): the cache is filled from the bottom up. that is much easier than to go top-down. after the initial import, just the recent mails are fetched.

**Comment by Gloirin** [comment]
**Comment posted by jleg on 14 Dec 2010 12:45**

&gt; perhaps you need to clear the database again
i&#039;ll try that (but i have to re-check how i did this last time - perhaps some hints in docu would help others as well... :)

&gt; maybe the &#039;INBOX.CSL-Staff&#039; folder name is problematic (because of the &#039;-&#039;)
highly unlikely - since there are *several* other folders containing a hyphen as well without this message (not to mention &quot;sent-mail&quot; ;-). And since &#039;-&#039; is a totally legal char for IMAP folders, it still would remain a client&#039;s code problem...

&gt; the exclamation mark in the client shows that there have been exceptions on the server like folder/message not found

that&#039;s what i reported - perhaps i didn&#039;t made clear enough that there have not been any &quot;folder removements&quot; during that test, which means my point was that those messages are &quot;irritating&quot; at best, or simply &quot;wrong&quot; at the end...

&gt; the cache is filled from the bottom up. that is much easier than to go top-down

well, definitely not &quot;easier&quot;  for the user, i&#039;d say... - and it does not match my experience 100%; the first view shown is neither &quot;top&quot; nor &quot;bottom&quot;, but &quot;something in between&quot;...
You are of course right pointing out that this is only true for the initial fetch - though this also  makes tine quite a &quot;resource-hogger&quot; for people with notoriously huge imap folders...
(have never checked db/cache usage though...)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Dec 2010 14:27**

&gt; &gt; perhaps you need to clear the database again
&gt; i&#039;ll try that (but i have to re-check how i did this last time - perhaps some hints in docu would help others as well... :)

just truncate your [tine20_]felamimail_folder table and relogin or refresh the browser. all mails/folders will be fetched again.

&gt; erhaps i didn&#039;t made clear enough that there have not been any &quot;folder removements&quot; during that test, which means my point was that those messages are &quot;irritating&quot; at best, or simply &quot;wrong&quot; at the end...

the problem about the error messages is that we have to guess what went wrong because Zend_Mail does not give any hints about it. if we want to know what exactly the IMAP server responded, we need to analyse the traffic with (for example) wireshark (or create our own IMAP-protocol backend class).

&gt; well, definitely not &quot;easier&quot; for the user, i&#039;d say... - and it does not match my experience 100%

perhaps your cache had been half-way filled some time ago. if it is an initial import, to oldest messages (with the lowest uid) are fetched first (at least that would be the behaviour on the IMAP servers i know).

**Comment by Gloirin** [comment]
**Comment posted by jleg on 14 Dec 2010 14:52**

&gt;the problem about the error messages is that we have to guess what went wrong &gt;because Zend_Mail does not give any hints about it. if we want to know what exactly &gt;the IMAP server responded, we need to analyse the traffic with (for example) wireshark &gt;(or create our own IMAP-protocol backend class).

Ok, but - how do all the other pets from the &quot;zoo of imap clients&quot; running here against the same IMAP server work then? And from what i can tell, our instances of Horde, roundcube, Thunderbird, Outlook, iPhone and even Windows mobile do work without any hassle regarding *these* issues...
After all, IMAP is designed to allow for concurrent access. Sometimes there&#039;s for instance a special imap client running only to detect and sort out SPAM, or to apply some rules on folders. Which has not been of any problem so far.

And concerning tine&#039;s mailclient: I doubt that you really intend to design it as *primary* mail client for anybody, or? Imo it is a &quot;convenience&quot; to have mail access &quot;nearby&quot; the tine groupware stuff, and probably some really useful interactions with other parts of tine are possible that way. But imo it is not very likely that &#039;felamimail&#039; will have *exclusive* access to user&#039;s box all the time, nor that anybody does not have it&#039;s primary mailclient open in parallel (and being it an iPhone - &quot;always on&quot;).
This means - concurrent, regular IMAP access is likely (normal?) to happen - currently this means for felamimal being in a permanent error state...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Dec 2010 09:07**

yes, you are right. felamimail is not meant to be the one and only mailclient.

and i think there was a misunderstanding: i just wanted to make clear that the error messages we get are not very precise. perhaps we should catch some more exceptions and don&#039;t bother the user with them.

but we are drifting off ... perhaps we should move this discussion to the forum. ;)

just let me know: did you empty the cache and was it helpful?

**Comment by Gloirin** [comment]
**Comment posted by jleg on 15 Dec 2010 10:11**

i emptied the cache, but behaviour did not change - still random folders are visible at first, and get &quot;lost&quot; after; still lots of exceptions in log:

74f31 xxx - 2010-12-15T10:02:42+00:00 INFO (6): Felamimail_Controller_Cache_Message::_expungeCacheFolder::179 Removing no longer existing folder INBOX.Kunden from cache. cannot change folder, maybe it does not exist

(of course it exists, and it is even still displayed in felamimail - it even remains accessible until &quot;Orderliste aktualisieren&quot; is used, then it is either hidden, or an error message pops up telling that the folder vanished, and the &quot;busy&quot; sign before the folder rotates for ever...)

New example here is folder &quot;INBOX.Kunden&quot; (note: no hyphen ;-) - old example was &quot;CSL-Staff&quot;; interestingly - though vanished from Felamimail-frontend - this folder still seems to be operated on according to log:

c0f11 xxx - 2010-12-15T10:01:09+00:00 TRACE (8): Felamimail_Controller_Cache_Message::_addMessagesToCacheAndIncreaseCounters::528 Add message 11851 to cache
c0f11 xxx - 2010-12-15T10:01:09+00:00 TRACE (8): Felamimail_Controller_Cache_Message::_addMessagesToCacheAndIncreaseCounters::528 Add message 11858 to cache
1cf15 xxx - 2010-12-15T10:01:09+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.CSL-Staff.Aldem
1cf15 xxx - 2010-12-15T10:01:09+00:00 DEBUG (7): Felamimail_Controller_Cache_Folder::_getOrCreateFolders::291 Update cached folder INBOX.CSL-Staff.Wolfgang
c0f11 xxx - 2010-12-15T10:01:09+00:00 TRACE (8): Felamimail_Controller_Cache_Message::_addMessagesToCacheAndIncreaseCounters::528 Add message 11909 to cache

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Dec 2010 11:41**

it seems that the expunge on courier works a little different than on other imap servers.

we are going to install a system with courier and will test and fix it before the release.

assigning this to lars.

**Comment by pschuele** [comment]
@jleg is this still a problem for you (and are you still using courier :wink: )?
