### ISSUE TITLE
0002882:
Global Adress List (GAL) search via ActiveSync produces php exception

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1519]
**Reported by Olodin on 2 Aug 2010 15:59**

**Version:** Mialena (2010-03-4)

Global Adress List (GAL) searching/access via ActiveSync seems to be not supported, as there is no global adressbook in tine20. But the search command initiated by a ActiveSync client produces a php error in the httpd-error.log (see below).

Is there a fix to tell the client that this search is not supported or just tell it that nothing was found instead of throwing that exception?

**Additional information:** [Mon Aug 02 14:49:00 2010] [error] [client 1.1.1.1] PHP Fatal error:  Uncaught exception &#039;Exception&#039; with message &#039;unsupported command Search&#039; in /tine20/ActiveSync/Frontend/Http.php:112\nStack trace:\n#0 /tine20/ActiveSync/Server/Http.php(97): ActiveSync_Frontend_Http-&gt;handlePost(&#039;unsers&#039;, &#039;PALM431fd884007...&#039;, &#039;Palm&#039;, &#039;Search&#039;, &#039;12.0&#039;)\n#1 /tine20/Tinebase/Core.php(194): ActiveSync_Server_Http-&gt;handle()\n#2 /tine20/index.php(56): Tinebase_Core::dispatchRequest()\n#3 {main}\n  thrown in /tine20/ActiveSync/Frontend/Http.php on line 112

**Comment by Gloirin** [comment]
**Comment posted by chrismaster on 2 Aug 2010 16:50**

Global Adress List would be a nice feature

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 22 Aug 2010 15:42**

Just came across the error that tine20 logs (level warning):
01751 xx, yy - 2010-08-22T15:00:31+00:00 WARN (4): Tinebase_Core::errorHandler::274 include(ActiveSync/Command/Search.php) [&lt;a href=&#039;function.                *include&#039;&gt;function.include&lt;/a&gt;]: failed to open stream: No such file or directory in /usr/local/www/apache22/data/tine20/library/Zend/Loader.php::83         *(2) 

01751xx, yy - 2010-08-22T15:00:31+00:00 WARN (4): Tinebase_Core::errorHandler::274 include() [&lt;a href=&#039;function.include&#039;&gt;function.include&lt;/a&gt;]:              *Failed opening &#039;ActiveSync/Command/Search.php&#039; for inclusion (include_path=&#039;/usr/local/www/apache22/data/tine20:/usr/local/www/apache22/data/tine20/        *library:.:/usr/local/share/pear&#039;) in /usr/local/www/apache22/data/tine20/library/Zend/Loader.php::83 (2)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Sep 2010 08:20**

I just implemented the missing class. It does not create an error anymore, but also does not return anything.

Access to Global Address List is already provided via synchronisation of contacts from the addressbook. All user accounts are available via the addressbook.

When I have tested the class, I will mark this ticket as resolved.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 26 Nov 2010 17:13**

Search command creates no PHP error message anymore.
