### ISSUE TITLE
0002908:
add cyrus imap backend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1532]
**Reported by pschuele on 10 Aug 2010 11:44**

add cyrus imap backend

- add to setup
- add to admin / user dialog
- implement backend

**Comment by Gloirin** [comment]
Depends on #1792

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Aug 2010 12:03**

added
- cyrus backend to setup
- cyrus backend stub (Tinebase_EmailUser_Imap_Cyrus)
- cyrus backend to email user factory

@lars please implement Tinebase_EmailUser_Imap_Cyrus ;)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 13 Aug 2010 07:53**

The backend is implemented. Now we just need to test it a little bit and then we can mark this ticket as resolved.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2010 13:24**

need to fix this error:

PHP Fatal error:  Uncaught exception &#039;ErrorException&#039; with message &#039;Argument 1 passed to Tinebase_User_Abstract::registerPlugin() must be an instance of Tinebase_User_Plugin_Interface, instance of Tinebase_EmailUser_Imap_Cyrus given, called in /srv/www/htdocs/mail/Tinebase/User/Abstract.php on line 99 and defined&#039; in /srv/www/htdocs/mail/Tinebase/User/Abstract.php:365
Stack trace:
#0 /srv/www/htdocs/mail/Tinebase/User/Abstract.php(365): Tinebase_Core::errorHandler(Object(Tinebase_EmailUser_Imap_Cyrus))
#1 /srv/www/htdocs/mail/Tinebase/User/Abstract.php(99): Tinebase_User_Abstract-&gt;registerPlugin(Array)
#2 /srv/www/htdocs/mail/Tinebase/User/Sql.php(65): Tinebase_User_Abstract-&gt;__construct(Array)
#3 /srv/www/htdocs/mail/Tinebase/User/Ldap.php(121): Tinebase_User_Sql-&gt;__construct(Array)
#4 /srv/www/htdocs/mail/Tinebase/User.php(161): Tinebase_User_Ldap-&gt;__construct(&#039;Ldap&#039;)
#5 /srv/www/htdocs/mail/Tinebase/User.php(126): Tinebase_User::factory()
#6 /srv/www/htdocs/mail/Tinebase/User.php(446): Tinebase_User::getInstance(true)
#7 /s in /srv/www/htdocs/mail/Tinebase/User/Abstract.php on line 365

see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=4632&amp;start=30#p19158

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 8 Dec 2010 06:45**

Implemented Cyrus backend and unittests.
