### ISSUE TITLE
0003010:
Android: ActiveSync crash when syncing email

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1583]
**Reported by Gurney on 10 Sep 2010 19:09**

**Version:** git master

The debug log from Tine shows no error but:
- I get an error on Android: &quot;Fails to analyse the file from the server&quot; (translated from French)
- my error.log in apache shows the following:

[Fri Sep 10 21:01:40 2010] [error] [client 192.168.0.1] PHP Fatal error:  Uncaught exception &#039;ErrorException&#039; with message 

Argument 1 passed to Tinebase_Controller_Record_Abstract::update() must implement interface Tinebase_Record_Interface, string given, called in /media/server/www/tine20/ActiveSync/Controller/Email.php on line 607 and defined&#039; in /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php:355
Stack trace:
#0 /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php(355): Tinebase_Core::errorHandler(&#039;86111a509caa934...&#039;, 5)
#1 /media/server/www/tine20/ActiveSync/Controller/Email.php(607): Tinebase_Controller_Record_Abstract-&gt;update(&#039;86111a509caa934...&#039;)
#2 /media/server/www/tine20/ActiveSync/Command/GetItemEstimate.php(198): ActiveSync_Controller_Email-&gt;updateCache(Object(ActiveSync_Controller_Email), Array, Object(Zend_Date))
#3 /media/server/www/tine20/ActiveSync/Command/GetItemEstimate.php(135): ActiveSync_Command_GetItemEstimate-&gt;_getItemEstimate()
#4 /media/server/www/tine20/ActiveSync/Frontend/Http.php(123): ActiveSync_Command_GetItemEstimate-&gt;g

in /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php on line 355

**Additional information:** Here&#039;s the original line (not formatted as above) from the error.log

[Fri Sep 10 21:01:40 2010] [error] [client 192.168.0.1] PHP Fatal error:  Uncaught exception &#039;ErrorException&#039; with message &#039;Argument 1 passed to Tinebase_Controller_Record_Abstract::update() must implement interface Tinebase_Record_Interface, string given, called in /media/server/www/tine20/ActiveSync/Controller/Email.php on line 607 and defined&#039; in /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php:355\nStack trace:\n#0 /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php(355): Tinebase_Core::errorHandler(&#039;86111a509caa934...&#039;, 5)\n#1 /media/server/www/tine20/ActiveSync/Controller/Email.php(607): Tinebase_Controller_Record_Abstract-&gt;update(&#039;86111a509caa934...&#039;)\n#2 /media/server/www/tine20/ActiveSync/Command/GetItemEstimate.php(198): ActiveSync_Controller_Email-&gt;updateCache(Object(ActiveSync_Controller_Email), Array, Object(Zend_Date))\n#3 /media/server/www/tine20/ActiveSync/Command/GetItemEstimate.php(135): ActiveSync_Command_GetItemEstimate-&gt;_getItemEstimate()\n#4 /media/server/www/tine20/ActiveSync/Frontend/Http.php(123): ActiveSync_Command_GetItemEstimate-&gt;g in /media/server/www/tine20/Tinebase/Controller/Record/Abstract.php on line 355

**Comment by Gloirin** [comment]
Related to #1518

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 13 Sep 2010 07:41**

By the way I am using a HTC Desire.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Sep 2010 07:52**

i just commit a fix. please try again and report back if it works now ...

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 14 Sep 2010 16:47**

I confirm that the message doesn&#039;t show up in error.log now.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 15 Sep 2010 07:37**

I don&#039;t get the error in the phone either but no mails show up in the Mail application.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Sep 2010 08:54**

see http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=4340

**Comment by Gloirin** [comment]
**Comment posted by lautermann on 15 Sep 2010 18:08**

Having the same problem here with a Samsung Galaxy S.

Folder structure is shown but no mails neither old nor new one.

I&#039;m using the latest trunk.

**Comment by Gloirin** [comment]
**Comment posted by lautermann on 15 Sep 2010 18:39**

For the sake of completeness: Sending mails works great. The problem is only receiving mails using ActiveSync.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 28 Sep 2010 08:31**

Issue should be linked to #2880

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 29 Sep 2010 10:11**

I&#039;ll have a look at this today.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 29 Sep 2010 13:14**

The problem should be fixed in SVN now. 

Please test and report back.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 29 Sep 2010 16:14**

It seems to work correctly indeed.

Though the ping command still doesn&#039;t trigger the update of the cache ;)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Sep 2010 05:36**

:-) I&#039;ll have a look at the ping problem too.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Sep 2010 05:37**

Problem is solved now.
