### ISSUE TITLE
0003128:
SVN 16880: can't login with LDAP auth & backend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1642]
**Reported by Gurney on 17 Oct 2010 04:47**

**Version:** git master

Since I updated to latest SVN this morning (from yesterday&#039;s SVN version) I cannot login any more to Tine, be it through the web interface or through Activesync.

I think it is the update to Tinebase 3.19 which causes the issue.

When I login I get the &quot;login/password error&quot;. The debug log doesn&#039;t show much. Basically everything goes fine, I get authentified and then the login process just stops when getting the account info from the LDAP server (I think), without issuing an error.

**Additional information:** 3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 DEBUG (7): Tinebase_Server_Json::handle::61 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase.login
            [params] =&gt; Array
                (
                    [username] =&gt; gurney
                    [password] =&gt; *******
                )

            [id] =&gt; 2
        )

)

3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 INFO (6): Tinebase_Server_Json::_handle::87 is JSON request. method: Tinebase.login
3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 DEBUG (7): Tinebase_Auth::__construct::138 authentication backend: Ldap
3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 DEBUG (7): Tinebase_Auth_Ldap::authenticate::62 Trying to authenticate gurney
3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 INFO (6): Tinebase_Auth_Ldap::authenticate::68 Authentication of gurney succeeded
3e0e8 -- none -- - 2010-10-17T04:30:01+00:00 DEBUG (7): Tinebase_User::getInstance::124 accounts backend: Ldap

**Comment by Gloirin** [comment]
**Comment posted by lautermann on 18 Oct 2010 21:37**

Bei mir existiert dasselbe Problem auch.

Hier noch der Auszug aus dem Apache-Logs:

[Mon Oct 18 05:13:34 2010] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error: Class Tinebase_User_Ldap contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Tinebase_User_Interface_SyncAble::updateContactInSyncBackend) in /var/www/tine20/Tinebase/User/Ldap.php on line 850, referer: https://myserver/tine20/

**Comment by Gloirin** [comment]
**Comment posted by lautermann on 20 Oct 2010 20:22**

Mit dem neuesten Trunk scheinen wir einen Schritt weiter zu sein.

Er sagt jetzt &quot;Anmeldung erfolgreich&quot;, aber man kriegt direkt die nächste Fehlermeldung und kommt nicht weiter.

Hier die neue Fehlermeldung:

Eigenes Fenster mit Titel &quot;Dienst nicht verfügbar&quot; und folgemdem Text:
Der Server kann Ihre Anfrage momentan nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.

**Comment by Gloirin** [comment]
**Comment posted by lautermann on 20 Oct 2010 20:26**

Hier noch der passende Log aus der tine20.log:
9e89f Lautermann, Martin - 2010-10-20T20:18:35+00:00 WARN (4): Felamimail_Frontend_Json::getRegistryData::463 Could not get accounts: Contact with user id 6b558854-030d-102f-8e3d-21253cf2b395 not found.
9e89f Lautermann, Martin - 2010-10-20T20:18:35+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::165 exception &#039;Addressbook_Exception_NotFound&#039; with message &#039;Contact with user id 6b558854-030d-102f-8e3d-21253cf2b395 not found.&#039; in /var/www/tine20/Addressbook/Backend/Sql.php:60
Stack trace:
#0 /var/www/tine20/Addressbook/Controller/Contact.php(127): Addressbook_Backend_Sql-&gt;getByUserId(&#039;6b558854-030d-1...&#039;)
#1 /var/www/tine20/Tinebase/Frontend/Json.php(472): Addressbook_Controller_Contact-&gt;getContactByUserId(&#039;6b558854-030d-1...&#039;, true)
#2 /var/www/tine20/Tinebase/Frontend/Json.php(511): Tinebase_Frontend_Json-&gt;getRegistryData()
#3 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#4 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 /var/www/tine20/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 /var/www/tine20/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 /var/www/tine20/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
#10 /var/www/tine20/index.php(56): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 21 Oct 2010 06:33**

Yes, one problem is fixed, another one is yet open.

I can reproduce the second problem and will try to fix it today.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 21 Oct 2010 17:52**

The problem is fixed now.

Unfortunately we lost the connection between the account you tried to login with and the contact stored in the addressbook.

To solve the problem you must select the contact of the affected user from addresbook.

select id,n_family from tine20_addressbook where n_family=&#039;Kneschke&#039;;
+----+----------+
| id | n_family |
+----+----------+
|  6 | Kneschke |
+----+----------+

And then update the accounts table.

update tine20_accounts set  contact_id=6 where login_name=&#039;lkneschke&#039;;

Then you can login again.
