### ISSUE TITLE
0003258:
LDAP Backend: cannot update user details

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1707]
**Reported by Gurney on 2 Nov 2010 08:41**

**Version:** git master

Each time I try to update the user details, I get the following errors:

0x41 (Object class violation; attribute &#039;member&#039; not allowed): adding: cn=Admins,ou=Groups,dc=domain,dc=net
/media/server/www/tine/Tinebase/Group/Ldap.php(330): Tinebase_Ldap-&gt;addProperty(cn=Admins,ou=Groups,dc=domain,dc=net)
/media/server/www/tine/Tinebase/Group/Sql.php(243): Tinebase_Group_Ldap-&gt;addGroupMemberInSyncBackend(2)
/media/server/www/tine/Admin/Controller/User.php(243): Tinebase_Group_Sql-&gt;addGroupMember(2)
/media/server/www/tine/Admin/Frontend/Json.php(356): Admin_Controller_User-&gt;update([object Object])
[internal function]: Admin_Frontend_Json-&gt;saveUser([object Object])
/media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array([object Object],saveUser)
/media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch([object Object])
/media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
/media/server/www/tine/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle([object Object])
/media/server/www/tine/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle([object Object])
/media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
/media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 2 Nov 2010 10:38**

I&#039;ll provide a more detailed log tonight, that&#039;s the debug info from the Tine web interface itself.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 28 Nov 2010 15:13**

OK I&#039;ve made some progress.

I think in Tinebase_Groups_LDAP, line 281, we need to replace:

        if (in_array($userId, $memberships)) {
by
        if (in_array($groupId, $memberships)) {

Otherwise we&#039;re looking for a userID in memberships, which contains only groupIDs.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 28 Nov 2010 15:26**

And now I get the following error when trying to update my user details (trying to add an openID attribute in my case)

41a10 Halleck, Gurney - 2010-11-28T15:08:04+00:00 DEBUG (7): Tinebase_Group_Ldap::addGroupMemberInSyncBackend::282 skip adding group member, as 1000 is already in group 2
41a10 Halleck, Gurney - 2010-11-28T15:08:04+00:00 DEBUG (7): Tinebase_TransactionManager::commitTransaction::112  commitTransaction request for e8cc0438c81425eca699af1a41071ddb618c9203
41a10 Halleck, Gurney - 2010-11-28T15:08:04+00:00 DEBUG (7): Tinebase_TransactionManager::commitTransaction::120  no more open transactions in queue commiting all transactionables
41a10 Halleck, Gurney - 2010-11-28T15:08:04+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::167 exception &#039;Tinebase_Exception_NotImplemented&#039; with message &#039;Not yet implemented&#039; in /media/server/www/tine/Tinebase/Group/Ldap.php:264
Stack trace:
#0 /media/server/www/tine/Tinebase/Group/Sql.php(193): Tinebase_Group_Ldap-&gt;setGroupMembershipsInSyncBackend(&#039;1000&#039;, Array)
#1 /media/server/www/tine/Admin/Frontend/Json.php(363): Tinebase_Group_Sql-&gt;setGroupMemberships(&#039;1000&#039;, Array)
#2 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#3 /media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 /media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 /media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 /media/server/www/tine/Tinebase/Server/Json.php(133): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 /media/server/www/tine/Tinebase/Server/Json.php(73): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#8 /media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
#9 /media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()
#10 {main}

I guess this is simply not yet implemented !! ;)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Dec 2010 18:20**

That was really a mistake. $userId must be $groupId.

And now I implement the missing function.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Dec 2010 19:03**

All problems should be solved now.

Please make sure that you have useRfc2307bis enabled in setup only, when your LDAP directory does support the Rfc2307bis schema.
