### ISSUE TITLE
0003296:
SVN 16981: illegal json data in response / login with ldap auth / DateTime problem with php 5.2.x

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1726]
**Reported by Gurney on 9 Nov 2010 06:55**

**Version:** git master

 DateTime problem with php 5.2.x in Felamimail_Controller_Cache_Folder::updateAllowed()

old text:

login with ldap auth fails.

Since the upgrade to 16981 I receive the following error:

illegal json data in response

Fatal error: Call to a member function getTimezone() on a non-object in /media/server/www/tine/Tinebase/DateTime.php on line 182

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 9 Nov 2010 06:56**

Maybe related to #3256 or http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=4536

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Nov 2010 11:16**

cornelius just finished the datetime stuff. does the problem still exist?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 10 Nov 2010 12:13**

Well... Now I cannot login anymore.

Here&#039;s the debug log:
d5f2e -- none -- - 2010-11-10T12:03:08+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::165 exception &#039;Exception&#039; with message &#039;invalid user object&#039; in /media/server/www/tine/Tinebase/User/Sql.php:463 

Stack trace:                                                                    
#0 /media/server/www/tine/Tinebase/User.php(377): Tinebase_User_Sql-&gt;updateUserInSqlBackend(Object(Tinebase_Model_FullUser))                                    
#1 /media/server/www/tine/Tinebase/Controller.php(86): Tinebase_User::syncUser(&#039;gurney&#039;)                                                                    
#2 /media/server/www/tine/Tinebase/Frontend/Json.php(373): Tinebase_Controller-&gt;login(&#039;gurney&#039;, &#039;****&#039;&#039;, &#039;***.**.**.***&#039;, &#039;TineJson&#039;)                  
#3 [internal function]: Tinebase_Frontend_Json-&gt;login(&#039;gurney&#039;, &#039;****&#039;&#039;)                                                                               
#4 /media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)                                                             
#5 /media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)                              
#6 /media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 /media/server/www/tine/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))                                             
#8 /media/server/www/tine/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))               
#9 /media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
#10 /media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()      
#11 {main}                                                                      
d5f2e -- none -- - 2010-11-10T12:03:08+00:00 INFO (6): index.php (68) TIME: 0.82
1501970291 seconds 9 MBytes

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 10 Nov 2010 12:17**

That&#039;s SVN 16992.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Nov 2010 12:27**

you are using ldap as auth backend, right?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 10 Nov 2010 12:30**

Yes, indeed.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Nov 2010 12:33**

passing this one to lars ...

as a workaround, you can disable the sync user in Tinebase_Controller (line 86 i think).

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Nov 2010 12:55**

The workaround doesn&#039;t work :(.

And there&#039;s no output in the logs...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2010 13:45**

we&#039;ll check this on our ldap test system asap

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2010 13:50**

you can help debugging, if you like:
- please add the removed line again in Tinebase_Controller
- add the following to the beginning of the function updateUserInSqlBackend() in Tinebase_User_Sql -&gt;

Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; &#039; . print_r($_user-&gt;toArray(), true));

- post the log here

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2010 14:01**

... and just added validation errors to the exception message

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Nov 2010 14:13**

I&#039;ve added the line as mentionned but it seems nothing is logged anymore from that aspect (I don&#039;t see the errors stated anymore).

Here&#039;s what the logs show:

f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Core::setupLogger::402 logger initialized
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Core::setupCache::452 cache disabled
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Core::setupUserLocale::692 given localeString &#039;auto&#039;
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Translation::getLocale::179 given localeString &#039;fr&#039;
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 selected locale: &#039;fr&#039;
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Server_Json::handle::61 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase.login
            [params] =&gt; Array
                (
                    [username] =&gt; gurney
                    [password] =&gt; *******
                )

            [id] =&gt; 3
        )

)

f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Server_Json::_handle::87 is JSON request. method: Tinebase.login
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::801 setting execution life time to: 0
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Auth::__construct::138 authentication backend: Ldap
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Auth_Ldap::authenticate::62 Trying to authenticate gurney
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 INFO (6): Tinebase_Auth_Ldap::authenticate::68 Authentication of gurney succeeded
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_User::getInstance::124 accounts backend: Ldap
f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_EmailUser::getConfiguredBackend::192 Array
(
    [active] =&gt; 1
    [backend] =&gt; ldapSmtp
    [hostname] =&gt; localhost
    [port] =&gt; 25
    [ssl] =&gt; tls
    [auth] =&gt; none
    [primarydomain] =&gt; 
    [secondarydomains] =&gt; 
    [from] =&gt; 
    [username] =&gt; 
    [password] =&gt; 
    [postfix] =&gt; Array
        (
            [port] =&gt; 3306
        )

)

f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_EmailUser_Ldap::__construct::55 Array
(
    [active] =&gt; 1
    [backend] =&gt; ldapSmtp
    [hostname] =&gt; localhost
    [port] =&gt; 25
    [ssl] =&gt; tls
    [auth] =&gt; none
    [primarydomain] =&gt; 
    [secondarydomains] =&gt; 
    [from] =&gt; 
    [username] =&gt; 
    [password] =&gt; 
    [postfix] =&gt; Array
        (
            [port] =&gt; 3306
        )

)

f4a19 -- none -- - 2010-11-11T14:11:48+00:00 DEBUG (7): Tinebase_Group::getInstance::58 groups backend: Ldap

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2010 15:07**

did you add the syncUser line again to Tinebase_Controller (line ~86)? -&gt;

if ($accountsController instanceof Tinebase_User_Interface_SyncAble) {
                    Tinebase_User::syncUser($accountName);
                }

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2010 15:07**

+ please update from svn first

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Nov 2010 17:04**

Ok, I updated to latest SVN, added the debug line, but no luck.

Log output is still the exact same.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Nov 2010 17:05**

here it is, just in case:

92ede -- none -- - 2010-11-11T17:03:26+00:00 INFO (6): Tinebase_Core::setupLogger::402 logger initialized
92ede -- none -- - 2010-11-11T17:03:26+00:00 INFO (6): Tinebase_Core::setupCache::452 cache disabled
92ede -- none -- - 2010-11-11T17:03:26+00:00 INFO (6): Tinebase_Core::setupUserLocale::692 given localeString &#039;auto&#039;
92ede -- none -- - 2010-11-11T17:03:26+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::705 session value &#039;fr&#039;
92ede -- none -- - 2010-11-11T17:03:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::179 given localeString &#039;fr&#039;
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 selected locale: &#039;fr&#039;
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_Server_Json::handle::61 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase.login
            [params] =&gt; Array
                (
                    [username] =&gt; gurney
                    [password] =&gt; *******
                )

            [id] =&gt; 4
        )

)

92ede -- none -- - 2010-11-11T17:03:27+00:00 INFO (6): Tinebase_Server_Json::_handle::87 is JSON request. method: Tinebase.login
92ede -- none -- - 2010-11-11T17:03:27+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::801 setting execution life time to: 0
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_Auth::__construct::138 authentication backend: Ldap
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_Auth_Ldap::authenticate::62 Trying to authenticate gurney
92ede -- none -- - 2010-11-11T17:03:27+00:00 INFO (6): Tinebase_Auth_Ldap::authenticate::68 Authentication of gurney succeeded
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_User::getInstance::124 accounts backend: Ldap
92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_EmailUser::getConfiguredBackend::192 Array
(
    [active] =&gt; 1
    [backend] =&gt; ldapSmtp
    [hostname] =&gt; localhost
    [port] =&gt; 25
    [ssl] =&gt; tls
    [auth] =&gt; none
    [primarydomain] =&gt; 
    [secondarydomains] =&gt; 
    [from] =&gt; 
    [username] =&gt; 
    [password] =&gt; 
    [postfix] =&gt; Array
        (
            [port] =&gt; 3306
        )

)

92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_EmailUser_Ldap::__construct::55 Array
(
    [active] =&gt; 1
    [backend] =&gt; ldapSmtp
    [hostname] =&gt; localhost
    [port] =&gt; 25
    [ssl] =&gt; tls
    [auth] =&gt; none
    [primarydomain] =&gt; 
    [secondarydomains] =&gt; 
    [from] =&gt; 
    [username] =&gt; 
    [password] =&gt; 
    [postfix] =&gt; Array
        (
            [port] =&gt; 3306
        )

)

92ede -- none -- - 2010-11-11T17:03:27+00:00 DEBUG (7): Tinebase_Group::getInstance::58 groups backend: Ldap

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Nov 2010 08:31**

could you have a look in your webserver error.log, too? there appears to be an error that is not logged in the tine logfile.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 12 Nov 2010 08:51**

Indeed :
[Fri Nov 12 09:50:08 2010] [error] [client 217.31.74.118] PHP Fatal error:  Declaration of Tinebase_Group_Ldap::getGroupMembershipsFromSyncBackend() must be compatible with that of Tinebase_Group_Interface_SyncAble::getGroupMembershipsFromSyncBackend() in /media/server/www/tine/Tinebase/Group/Ldap.php on line 19, referer: https://arrakeen.net/****/

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Nov 2010 08:59**

ah, ok :)

passing this one to lars again.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 13 Nov 2010 15:53**

Ok I found out:

in Tinebase_Group_Interface_SyncAble, line 55, I replaced:

public function getGroupMembershipsFromSyncBackend($_userId);

by

public function getGroupMembershipsFromSyncBackend(Tinebase_Model_User $_user);

And I am now able to log in. But I still get the following error:
illegal json data in response

Fatal error: Call to a member function getTimezone() on a non-object in /media/server/www/tine/Tinebase/DateTime.php on line 182

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 13 Nov 2010 17:12**

I added the following line to Tinebase_DateTime, just before the line 182:

if (! $_date instanceof DateTime) throw new Exception(&#039;&#039;);

And here&#039;s what I now get:

/media/server/www/tine/Felamimail/Controller/Cache/Folder.php(364): Tinebase_DateTime-&gt;compare()
/media/server/www/tine/Felamimail/Controller/Cache/Message.php(157): Felamimail_Controller_Cache_Folder-&gt;updateAllowed([object Object])
/media/server/www/tine/Felamimail/Controller/Cache/Message.php(126): Felamimail_Controller_Cache_Message-&gt;_doNotUpdateCache([object Object])
/media/server/www/tine/Felamimail/Frontend/Json.php(154): Felamimail_Controller_Cache_Message-&gt;updateCache(f83b04980f580176a38fdf2fb407a5b81563c32f)
[internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(f83b04980f580176a38fdf2fb407a5b81563c32f)
/media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array([object Object],updateMessageCache)
/media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch([object Object])
/media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
/media/server/www/tine/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle([object Object])
/media/server/www/tine/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle([object Object])
/media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
/media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2010 14:13**

committed fixes for the two problems.

please try again :)

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 16 Nov 2010 14:43**

Ok, LDAP issue is fixed in SVN :)

But I am still getting this error (small exclamation mark in near the account in Felamimail):

given $_date is not an instance of DateTime
/media/server/www/tine/Felamimail/Controller/Cache/Folder.php(367): Tinebase_DateTime-&gt;compare()
/media/server/www/tine/Felamimail/Controller/Cache/Message.php(157): Felamimail_Controller_Cache_Folder-&gt;updateAllowed([object Object])
/media/server/www/tine/Felamimail/Controller/Cache/Message.php(126): Felamimail_Controller_Cache_Message-&gt;_doNotUpdateCache([object Object])
/media/server/www/tine/Felamimail/Frontend/Json.php(154): Felamimail_Controller_Cache_Message-&gt;updateCache(f83b04980f580176a38fdf2fb407a5b81563c32f)
[internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(f83b04980f580176a38fdf2fb407a5b81563c32f)
/media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array([object Object],updateMessageCache)
/media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch([object Object])
/media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
/media/server/www/tine/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle([object Object])
/media/server/www/tine/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle([object Object])
/media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
/media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()

Here&#039;s the stacktrace:
cfcb5 gurney - 2010-11-16T14:41:00+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::165 exception &#039;Tinebase_Exception_Date&#039; with message &#039;given $_date is not an instance of DateTime&#039; in /media/server/www/tine/Tinebase/DateTime.php:181
Stack trace:
#0 /media/server/www/tine/Felamimail/Controller/Cache/Folder.php(367): Tinebase_DateTime-&gt;compare(NULL)
#1 /media/server/www/tine/Felamimail/Controller/Cache/Message.php(157): Felamimail_Controller_Cache_Folder-&gt;updateAllowed(Object(Felamimail_Model_Folder))
#2 /media/server/www/tine/Felamimail/Controller/Cache/Message.php(126): Felamimail_Controller_Cache_Message-&gt;_doNotUpdateCache(Object(Felamimail_Model_Folder))
#3 /media/server/www/tine/Felamimail/Frontend/Json.php(154): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;f83b04980f58017...&#039;, 120)
#4 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;f83b04980f58017...&#039;, 120)
#5 /media/server/www/tine/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 /media/server/www/tine/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 /media/server/www/tine/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 /media/server/www/tine/Tinebase/Server/Json.php(131): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 /media/server/www/tine/Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#10 /media/server/www/tine/Tinebase/Core.php(203): Tinebase_Server_Json-&gt;handle()
#11 /media/server/www/tine/index.php(56): Tinebase_Core::dispatchRequest()
#12 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2010 15:09**

this is a php 5.2 problem that we have atm. passing this one to cornelius ...

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 17 Nov 2010 19:40**

Indeed that&#039;s a PHP5.2 problem. I just upgraded to PHP 5.3 and the cache updates correctly.

Do you want me to give you a hand to solve it on 5.2?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 24 Nov 2010 11:33**

thanks for the offer. I think it&#039;s more easy if I setup a virtual machine for this

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 25 Nov 2010 13:21**

I just commited php 5.2 compatibility patch to trunk, can you verify if it works now?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 25 Nov 2010 14:28**

I close this bug now, as a test system with php 5.2.4 is running our testsuite successfully
