### ISSUE TITLE
0000170:
Contact image

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#179]
**Reported by martinhalle on 5 Aug 2008 04:18**

**Version:** 2008-summer-ms1-2

When trying to apply a new contact picture, the &quot;Loading&quot; message stays forever. And I click ok, while this message appears, I get a stack trace: SQLSTATE: [HY000] General Error 2053:

/var/www/crm/Zend/Db/Adapter/Abstract.php(637): Zend_Db_Statement_Pdo-&gt;fetch(2)
/var/www/crm/Tinebase/ImageHelper.php(178): Zend_Db_Adapter_Abstract-&gt;fetchRow([object Object])
/var/www/crm/Addressbook/Model/Contact.php(205): Tinebase_ImageHelper::getImageData([object Object])

/var/www/crm/Addressbook/Json.php(108): Addressbook_Model_Contact-&gt;setFromJson(
{&quot;adr_one_countryname&quot;:&quot;CA&quot;,&quot;adr_one_locality&quot;:&quot;Sainte-Foy&quot;,&quot;adr_one_postalcode&quot;:&quot;&quot;,&quot;adr_one_region&quot;:&quot;Quebec&quot;,&quot;adr_one_street&quot;:&quot;99999 Boul Laurier &quot;,&quot;adr_one_street2&quot;:&quot;&quot;,&quot;adr_two_countryname&quot;:&quot;CA&quot;,&quot;adr_two_locality&quot;:&quot;Quebec&quot;,&quot;adr_two_postalcode&quot;:&quot;g6v7g6&quot;,&quot;adr_two_region&quot;:&quot;Quebec&quot;,&quot;adr_two_street&quot;:&quot;525 de la Girouille&quot;,&quot;adr_two_street2&quot;:&quot;&quot;,&quot;assistent&quot;:null,&quot;bday&quot;:&quot;1974-03-08T00:00:00&quot;,&quot;calendar_uri&quot;:null,&quot;email&quot;:&quot;xxxxxxx@gmail.com&quot;,&quot;email_home&quot;:&quot;&quot;,&quot;jpegphoto&quot;:&quot;index.php?method=Tinebase.getImage&amp;application=Tinebase&amp;location=tempFile&amp;id=621d2df91a5960dd815b4d14b7152e8c5193a1db&amp;width=90&amp;height=78&amp;ratiomode=0&quot;,&quot;freebusy_uri&quot;:null,&quot;id&quot;:&quot;2&quot;,&quot;account_id&quot;:&quot;2&quot;,&quot;note&quot;:&quot;&quot;,&quot;owner&quot;:&quot;1&quot;,&quot;role&quot;:&quot;&quot;,&quot;title&quot;:&quot;&quot;,&quot;url&quot;:&quot;&quot;,&quot;url_home&quot;:&quot;&quot;,&quot;n_family&quot;:&quot;Family_name&quot;,&quot;n_fileas&quot;:&quot;Family_name, Martin&quot;,&quot;n_fn&quot;:&quot;Martin Family_name&quot;,&quot;n_given&quot;:&quot;Martin&quot;,&quot;n_middle&quot;:&quot;&quot;,&quot;n_prefix&quot;:&quot;&quot;,&quot;n_suffix&quot;:&quot;&quot;,&quot;org_name&quot;:&quot;DMR Conseil&quot;,&quot;org_unit&quot;:&quot;&quot;,&quot;pubkey&quot;:null,&quot;room&quot;:&quot;&quot;,&quot;tel_assistent&quot;:null,&quot;tel_car&quot;:null,&quot;tel_cell&quot;:&quot;999-999-9999&quot;,&quot;tel_cell_private&quot;:&quot;&quot;,&quot;tel_fax&quot;:&quot;&quot;,&quot;tel_fax_home&quot;:&quot;&quot;,&quot;tel_home&quot;:&quot;999-999-9999&quot;,&quot;tel_pager&quot;:null,&quot;tel_work&quot;:&quot;999-999-9999&quot;,&quot;tags&quot;:&quot;[]&quot;,&quot;tz&quot;:null,&quot;adr_one_countrydisplayname&quot;:&quot;Canada&quot;,&quot;adr_two_countrydisplayname&quot;:&quot;Canada&quot;}
)

Addressbook_Json-&gt;saveContact(
{&quot;adr_one_countryname&quot;:&quot;CA&quot;,&quot;adr_one_locality&quot;:&quot;Sainte-Foy&quot;,&quot;adr_one_postalcode&quot;:&quot;&quot;,&quot;adr_one_region&quot;:&quot;Quebec&quot;,&quot;adr_one_street&quot;:&quot;99999 Boul Laurier &quot;,&quot;adr_one_street2&quot;:&quot;&quot;,&quot;adr_two_countryname&quot;:&quot;CA&quot;,&quot;adr_two_locality&quot;:&quot;Quebec&quot;,&quot;adr_two_postalcode&quot;:&quot;g6v7g6&quot;,&quot;adr_two_region&quot;:&quot;Quebec&quot;,&quot;adr_two_street&quot;:&quot;525 de la Girouille&quot;,&quot;adr_two_street2&quot;:&quot;&quot;,&quot;assistent&quot;:null,&quot;bday&quot;:&quot;1974-03-08T00:00:00&quot;,&quot;calendar_uri&quot;:null,&quot;email&quot;:&quot;xxxxxxx@gmail.com&quot;,&quot;email_home&quot;:&quot;&quot;,&quot;jpegphoto&quot;:&quot;index.php?method=Tinebase.getImage&amp;application=Tinebase&amp;location=tempFile&amp;id=621d2df91a5960dd815b4d14b7152e8c5193a1db&amp;width=90&amp;height=78&amp;ratiomode=0&quot;,&quot;freebusy_uri&quot;:null,&quot;id&quot;:&quot;2&quot;,&quot;account_id&quot;:&quot;2&quot;,&quot;note&quot;:&quot;&quot;,&quot;owner&quot;:&quot;1&quot;,&quot;role&quot;:&quot;&quot;,&quot;title&quot;:&quot;&quot;,&quot;url&quot;:&quot;&quot;,&quot;url_home&quot;:&quot;&quot;,&quot;n_family&quot;:&quot;Family_name&quot;,&quot;n_fileas&quot;:&quot;Family_name, Martin&quot;,&quot;n_fn&quot;:&quot;Martin Family_name&quot;,&quot;n_given&quot;:&quot;Martin&quot;,&quot;n_middle&quot;:&quot;&quot;,&quot;n_prefix&quot;:&quot;&quot;,&quot;n_suffix&quot;:&quot;&quot;,&quot;org_name&quot;:&quot;DMR Conseil&quot;,&quot;org_unit&quot;:&quot;&quot;,&quot;pubkey&quot;:null,&quot;room&quot;:&quot;&quot;,&quot;tel_assistent&quot;:null,&quot;tel_car&quot;:null,&quot;tel_cell&quot;:&quot;999-999-9999&quot;,&quot;tel_cell_private&quot;:&quot;&quot;,&quot;tel_fax&quot;:&quot;&quot;,&quot;tel_fax_home&quot;:&quot;&quot;,&quot;tel_home&quot;:&quot;999-999-9999&quot;,&quot;tel_pager&quot;:null,&quot;tel_work&quot;:&quot;999-9999-9999&quot;,&quot;tags&quot;:&quot;[]&quot;,&quot;tz&quot;:null,&quot;adr_one_countrydisplayname&quot;:&quot;Canada&quot;,&quot;adr_two_countrydisplayname&quot;:&quot;Canada&quot;}
)

[internal function]: ReflectionMethod-&gt;invokeArgs([object Object])
/var/www/crm/Zend/Server/Reflection/Function/Abstract.php(366): call_user_func_array([object Object],invokeArgs)

[internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(invokeArgs)

/var/www/crm/Zend/Json/Server.php(144): Zend_Server_Reflection_Method-&gt;invokeArgs([object Object])
/var/www/crm/Tinebase/Controller.php(213): Zend_Json_Server-&gt;handle([object Object])
/var/www/crm/index.php(29): Tinebase_Controller-&gt;handle()

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2008 14:03**

from http://dev.mysql.com/doc/refman/5.0/en/error-messages-client.html -&gt;

Error: 2053 (CR_NO_RESULT_SET)

Message: Attempt to read a row while there is no result set associated with the statement

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 6 Aug 2008 08:38**

very interesting trace

- why does the loading message do not disapear -&gt; the jpegimage property ist set in the record and it&#039;s clearly a tmpFile
- but while the property is set, the corresponding entry is not in the db

conclusion:
the row isn&#039;t inserted properly in Tinebase_Http::uploadTempFile, but no exception got thrown?
maybe the session_id() is not working?

As I can&#039;t reproduce the problem I need more info to solve this.
In the meantime we fetch the exception

If possible please give me access to the system to analise the problem

**Comment by Gloirin** [comment]
**Comment posted by martinhalle on 6 Aug 2008 14:18**

Hi, thank you for your quick support

here is a link to the system.

http://crm.dmr-synergia.com

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 6 Aug 2008 19:32**

If i see it right, the tempfile record gets inserted into the db, but reading the entry is not possible.

Please provide the following:
- tine debug log the open/imageuplod/save reuest (to be enabled in config.ini)
- the contents of your &lt;tableprefix&gt;temp_files table

**Comment by Gloirin** [comment]
**Comment posted by martinhalle on 6 Aug 2008 20:16**

Debug Log:

***********************************************************************************************************************************
2008-08-06T15:51:29+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:51:29+00:00 DEBUG (7): is http request. method: Tinebase.uploadTempFile
2008-08-06T15:51:29+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:51:29+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:51:29+00:00 DEBUG (7): is http request. method: Tinebase.getImage
2008-08-06T15:51:29+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:51:43+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:51:43+00:00 DEBUG (7): is json request. method: Addressbook.saveContact
2008-08-06T15:51:43+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:51:43+00:00 DEBUG (7): method=Tinebase.getImage&amp;application=Tinebase&amp;location=tempFile&amp;id=f8b9c0b1fc215d3f8e8b248d5ea5acf83d659e92&amp;width=90&amp;height=78&amp;ratiomode=0
2008-08-06T15:51:43+00:00 DEBUG (7): Zend_Json_Server:
exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 2053 &#039; in /var/www/crm/Zend/Db/Statement/Pdo.php:260
Stack trace:
#0 /var/www/crm/Zend/Db/Adapter/Abstract.php(637): Zend_Db_Statement_Pdo-&gt;fetch(2)
#1 /var/www/crm/Tinebase/ImageHelper.php(178): Zend_Db_Adapter_Abstract-&gt;fetchRow(Object(Zend_Db_Select), &#039;&#039;, 2)
#2 /var/www/crm/Addressbook/Model/Contact.php(205): Tinebase_ImageHelper::getImageData(Array)
#3 /var/www/crm/Addressbook/Json.php(108): Addressbook_Model_Contact-&gt;setFromJson(&#039;{&quot;adr_one_count...&#039;)
#4 [internal function]: Addressbook_Json-&gt;saveContact(&#039;{&quot;adr_one_count...&#039;)
#5 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Addressbook_Json), Array)
#6 /var/www/crm/Zend/Server/Reflection/Function/Abstract.php(366): call_user_func_array(Array, Array)
#7 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#8 /var/www/crm/Zend/Json/Server.php(144): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Addressbook_Json), Array)
#9 /var/www/crm/Tinebase/Controller.php(213): Zend_Json_Server-&gt;handle(Array)
#10 /var/www/crm/index.php(29): Tinebase_Controller-&gt;handle()
#11 {main}
2008-08-06T15:52:35+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:52:35+00:00 DEBUG (7): is http request. method: Addressbook.editContact
2008-08-06T15:52:35+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:52:35+00:00 DEBUG (7): index.php (41) TIME: 0.105269908905 seconds 3 MBytes
2008-08-06T15:52:41+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:52:41+00:00 DEBUG (7): is json request. method: Addressbook.saveContact
2008-08-06T15:52:41+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:52:41+00:00 DEBUG (7):
2008-08-06T15:52:41+00:00 DEBUG (7): index.php (41) TIME: 0.150244951248 seconds 3.75 MBytes
2008-08-06T15:52:41+00:00 DEBUG (7): Tinebase_Controller::setupLogger::276 logger initialized
2008-08-06T15:52:41+00:00 DEBUG (7): is json request. method: Addressbook.searchContacts
2008-08-06T15:52:41+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2008-08-06T15:52:41+00:00 DEBUG (7): index.php (41) TIME: 0.087308883667 seconds 3.5 MBytes
***********************************************************************************************************************************

Table crm_temp_files_table (XML format)
***********************************************************************************************************************************
&lt;crm_tine20&gt;
  &lt;!-- Table tine20_temp_files --&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;070667d2386ba1325676e7937e1f8a589286c4b8&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:32:16&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_rREU7k&lt;/path&gt;
        &lt;name&gt;contact.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;0fc4ba4a1f3914a77f932bc6794c8bc2fe8f0c59&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:31:45&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_ojvIDS&lt;/path&gt;
        &lt;name&gt;contact.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;1107e0c71cd1165d8c59ac051d60f091300a0dec&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 03:07:15&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_oZR3sv&lt;/path&gt;
        &lt;name&gt;001.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;47656&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;1722fa6271dbaf37d079ec40c9ac652e4090d97b&lt;/id&gt;
        &lt;session_id&gt;fff800662e662f1fb996b7574af9b65c&lt;/session_id&gt;
        &lt;time&gt;2008-08-06 20:08:52&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_SIKXzN&lt;/path&gt;
        &lt;name&gt;DCP_1500.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;408973&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;1b475102faa179bd02d54e17eff2463fc73686e0&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:20:15&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_9kTdc6&lt;/path&gt;
        &lt;name&gt;00001-ce68457578.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;29ff8b7ec0f874c7f58e25d057766c032f4cc8cc&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 03:47:02&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_09a30b&lt;/path&gt;
        &lt;name&gt;001.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;47656&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;3d6f97971dc1eb8b22c7e648ae1942e8261cb519&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:31:14&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_PZYTrM&lt;/path&gt;
        &lt;name&gt;00001-ce68457578.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;4b1208f65b3252672b0819cd27df1a711b84d049&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:52:40&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_rzgiq6&lt;/path&gt;
        &lt;name&gt;001.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;47656&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;621d2df91a5960dd815b4d14b7152e8c5193a1db&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 04:11:40&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_S68itv&lt;/path&gt;
        &lt;name&gt;001.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;47656&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;63ac2bbbef64797b76e9e88cb59052ac5b3f34e5&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:35:16&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_S0NjOm&lt;/path&gt;
        &lt;name&gt;contact.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;793179c54029edac6594358c1946a65fa171631d&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:49:16&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_AkrEIA&lt;/path&gt;
        &lt;name&gt;contact.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;799be5e57fac9d4c727d2a36df71a093e96e2d92&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 04:09:25&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_GaSfT2&lt;/path&gt;
        &lt;name&gt;001.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;47656&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;ad972401dc2f1cf628adeb97cb904df88f14708f&lt;/id&gt;
        &lt;session_id&gt;e4f511ff62fc13a52a466b8f351122a7&lt;/session_id&gt;
        &lt;time&gt;2008-08-06 14:16:41&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_PpEjEJ&lt;/path&gt;
        &lt;name&gt;PIC000242.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;16050&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;b1ba6a29519f1cb9f75ebdf4102564c9004488ed&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:50:41&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_xXJNkb&lt;/path&gt;
        &lt;name&gt;contact.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;d2c14a9ec82678f109bd47814e328d37a309ad5b&lt;/id&gt;
        &lt;session_id&gt;ea446b71a41bf86a231dc05f03a52ca4&lt;/session_id&gt;
        &lt;time&gt;2008-08-05 02:30:28&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_7Foksk&lt;/path&gt;
        &lt;name&gt;00001-ce68457578.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;f7cce5a4aa343534f3f6185ef6eb02510aa7ef2b&lt;/id&gt;
        &lt;session_id&gt;fff800662e662f1fb996b7574af9b65c&lt;/session_id&gt;
        &lt;time&gt;2008-08-06 20:09:35&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_Y9jOOy&lt;/path&gt;
        &lt;name&gt;00001-ce68457578.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;35722&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;f8b9c0b1fc215d3f8e8b248d5ea5acf83d659e92&lt;/id&gt;
        &lt;session_id&gt;ba0be3ec5d443a4e214cac1e5368c5c4&lt;/session_id&gt;
        &lt;time&gt;2008-08-06 15:51:29&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_e6uDd2&lt;/path&gt;
        &lt;name&gt;Utah.png&lt;/name&gt;
        &lt;type&gt;image/png&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;8681&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
    &lt;tine20_temp_files&gt;
        &lt;id&gt;fc706eea9e9b5d868bdeb89999b4ee09e6f3079d&lt;/id&gt;
        &lt;session_id&gt;ba0be3ec5d443a4e214cac1e5368c5c4&lt;/session_id&gt;
        &lt;time&gt;2008-08-06 15:44:08&lt;/time&gt;
        &lt;path&gt;/var/lib/php5/tine_tempfile_Cl5BNT&lt;/path&gt;
        &lt;name&gt;Pond.jpg&lt;/name&gt;
        &lt;type&gt;image/jpeg&lt;/type&gt;
        &lt;error&gt;0&lt;/error&gt;
        &lt;size&gt;20701&lt;/size&gt;
    &lt;/tine20_temp_files&gt;
&lt;/crm_tine20&gt;
***********************************************************************************************************************************

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 6 Aug 2008 21:53**

realy interesting.

It looks like Zend_Db_Adapter_Abstract works different on your system than on mine.
- what is your php version?
- what is your ZF version?

could you provide a sql-query-log snipped from coresponding the db-query?

**Comment by Gloirin** [comment]
**Comment posted by martinhalle on 8 Aug 2008 10:15**

Hello, tell me if you need further information

PHP -&gt; PHP Version 5.2.0-8+etch11
ZF -&gt; 1.5.2

 mysql-bin.000514   	 121977   	 Query   	 1   	 303   	 use `crm_tine20`; INSERT INTO `tine20_access_log` (`sessionid`, `login_name`, `ip`, `li`, `result`, `account_id`) VALUES (&#039;ba0be3ec5d443a4e214cac1e5368c5c4&#039;, &#039;tine20admin&#039;, &#039;10.75.1.1&#039;, &#039;2008-08-06T15:43:22+00:00&#039;, &#039;1&#039;, &#039;1&#039;) 
 mysql-bin.000514  	 122252  	 Xid  	 1  	 122279  	 COMMIT /* xid=2617430 */ 
 mysql-bin.000514  	 122651  	 Query  	 1  	 365  	 use `crm_tine20`; INSERT INTO `tine20_temp_files` (`id`, `session_id`, `time`, `path`, `name`, `type`, `error`, `size`) VALUES (&#039;fc706eea9e9b5d868bdeb89999b4ee09e6f3079d&#039;, &#039;ba0be3ec5d443a4e214cac1e5368c5c4&#039;, &#039;2008-08-06T15:44:08+00:00&#039;, &#039;/var/lib/php5/tine_tempfile_Cl5BNT&#039;, &#039;Pond.jpg&#039;, &#039;image/jpeg&#039;, &#039;0&#039;, &#039;20701&#039;) 
 mysql-bin.000514  	 123016  	 Xid  	 1  	 123043  	 COMMIT /* xid=2617732 */ 
 mysql-bin.000514   	 125647   	 Query   	 1   	 363   	 use `crm_tine20`; INSERT INTO `tine20_temp_files` (`id`, `session_id`, `time`, `path`, `name`, `type`, `error`, `size`) VALUES (&#039;f8b9c0b1fc215d3f8e8b248d5ea5acf83d659e92&#039;, &#039;ba0be3ec5d443a4e214cac1e5368c5c4&#039;, &#039;2008-08-06T15:51:29+00:00&#039;, &#039;/var/lib/php5/tine_tempfile_e6uDd2&#039;, &#039;Utah.png&#039;, &#039;image/png&#039;, &#039;0&#039;, &#039;8681&#039;) 
 mysql-bin.000514  	 126010  	 Xid  	 1  	 126037  	 COMMIT /* xid=2617984 */ 
 mysql-bin.000514   	 126409   	 Query   	 1   	 1211   	 use `crm_tine20`; UPDATE `tine20_addressbook` SET `adr_one_countryname` = &#039;CA&#039;, `adr_one_locality` = &#039;Sainte-Foy&#039;, `adr_one_postalcode` = &#039;&#039;, `adr_one_region` = &#039;Quebec&#039;, `adr_one_street` = &#039;2960 Boul Laurier suite 400&#039;, `adr_one_street2` = &#039;&#039;, `adr_two_countryname` = &#039;CA&#039;, `adr_two_locality` = &#039;Quebec&#039;, `adr_two_postalcode` = &#039;G1C8K4&#039;, `adr_two_region` = &#039;Quebec&#039;, `adr_two_street` = &#039;525 de la Girouille&#039;, `adr_two_street2` = &#039;&#039;, `assistent` = NULL, `bday` = &#039;1974-03-09T00:00:00+00:00&#039;, `calendar_uri` = NULL, `email` = &#039;martinhalle@gmail.com&#039;, `email_home` = &#039;&#039;, `freebusy_uri` = NULL, `account_id` = &#039;2&#039;, `note` = &#039;&#039;, `owner` = &#039;1&#039;, `role` = &#039;&#039;, `title` = &#039;&#039;, `url` = &#039;&#039;, `url_home` = &#039;&#039;, `n_family` = &#039;Halle&#039;, `n_fileas` = &#039;Halle, Martin&#039;, `n_fn` = &#039;Martin Halle&#039;, `n_given` = &#039;Martin&#039;, `n_middle` = &#039;&#039;, `n_prefix` = &#039;&#039;, `n_suffix` = &#039;&#039;, `org_name` = &#039;DMR Conseil&#039;, `org_unit` = &#039;&#039;, `pubkey` = NULL, `room` = &#039;&#039;, `tel_assistent` = NULL, `tel_car` = NULL, `tel_cell` = &#039;418-455-4701&#039;, `tel_cell_private` = &#039;&#039;, `tel_fax` = &#039;&#039;, `tel_fax_home` = &#039;&#039;, `tel_home` = &#039;418-204-1779&#039;, `tel_pager` = NULL, `tel_work` = &#039;418-653-6881&#039;, `tz` = NULL WHERE (id = &#039;2&#039;) 
 mysql-bin.000514  	 127620  	 Xid  	 1  	 127647  	 COMMIT /* xid=2618178 */ 

thank you very much for this good support

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 11 Aug 2008 09:30**

mhh, this is interesting.

There should be two more SQL statements in the log. The statements which crash :-)

The crashing statement should be execuded twice:

Once directly after the INSERT INTO `tine20_temp_files` when the picture is send to the client. (cause this crashes, the load mask doesn&#039;t disappear)

Secondly, directly before the UPDATE  `tine20_addressbook` when the image data get read from the tmp table to copy data into contact


Could you try to fid theese statements in the logs?
cu
conny

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 25 Aug 2008 09:29**

Hi Martin, 

is this solved wiht milestone 2?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 29 Aug 2008 07:35**

Topic seems to be outdated or resolved. As I can&#039;t reproduce I&#039;m closeing it now.
Please reopen in case its active
