### ISSUE TITLE
0003522:
SIEVE-Filtermöglichkeit mit 1und1 kompatibel machen

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1838]
**Reported by splinter03 on 16 Dec 2010 17:33**

**Version:** Neele (2010-11) Beta 2

Anscheinend unterstützt 1und1 nicht alle Funktionen, die Tine für SIEVE braucht.
Bitte Tine kompatibel zu 1und1 und damit im allg. kompatibler zu Mail-Servern machen.

Forum-Eintrag zum Thema: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=5030

**Steps to reproduce:** Dialog: Filterregeln definieren öffnen
Filter anlegen
Bestätigen und schließen
Dialog: Filterregeln definieren erneut öffnen
--&gt; Keine Einträge

**Additional information:** error message:

aebb0 *******, Michael - 2010-12-15T17:44:59+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::167 exception &#039;Zend_Mail_Protocol_Exception&#039; with message &#039;line 2: Capability reject unknown&#039; in /var/www/tine20/Zend/Mail/Protocol/Sieve.php:342
Stack trace:
#0 /var/www/tine20/Zend/Mail/Protocol/Sieve.php(365): Zend_Mail_Protocol_Sieve-&gt;readResponse(false)
#1 /var/www/tine20/Zend/Mail/Protocol/Sieve.php(489): Zend_Mail_Protocol_Sieve-&gt;requestAndResponse(&#039;PUTSCRIPT&#039;, Array)
#2 /var/www/tine20/Felamimail/Controller/Sieve.php(243): Zend_Mail_Protocol_Sieve-&gt;putScript(&#039;felamimail2.0&#039;, &#039;#Generated by F...&#039;)
#3 /var/www/tine20/Felamimail/Controller/Sieve.php(358): Felamimail_Controller_Sieve-&gt;_putScript(&#039;17d372f3e324b9e...&#039;, Object(Felamimail_Sieve_Script))
#4 /var/www/tine20/Felamimail/Frontend/Json.php(474): Felamimail_Controller_Sieve-&gt;setRules(&#039;17d372f3e324b9e...&#039;, Object(Tinebase_Record_RecordSet))
#5 [internal function]: Felamimail_Frontend_Json-&gt;saveRules(&#039;17d372f3e324b9e...&#039;, Array)
#6 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 /var/www/tine20/Tinebase/Server/Json.php(133): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 /var/www/tine20/Tinebase/Server/Json.php(73): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 /var/www/tine20/Tinebase/Core.php(209): Tinebase_Server_Json-&gt;handle()
#12 /var/www/tine20/index.php(56): Tinebase_Core::dispatchRequest()
#13 {main}

capabilities:
(
    [IMPLEMENTATION] =&gt; NEMESIS ManageSieved v83991
    [SASL] =&gt; Array
        (
            [0] =&gt; PLAIN
        )

    [RENAME] =&gt; 
    [NOOP] =&gt; 
    [SIEVE] =&gt; Array
        (
            [0] =&gt; body
            [1] =&gt; comparator-i;ascii-casemap
            [2] =&gt; comparator-i;ascii-numeric
            [3] =&gt; comparator-i;octet
            [4] =&gt; date
            [5] =&gt; encoded-character
            [6] =&gt; envelope
            [7] =&gt; fileinto
            [8] =&gt; imap4flags
            [9] =&gt; index
            [10] =&gt; relational
            [11] =&gt; variables
        )

    [STARTTLS] =&gt; 
)

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 9 Jul 2012 16:15**

Ich habe (für mich) eine Lösung gefunden:

Und zwar liegt der Fehler in folgender Datei: tine20/Felamimail/Sieve/Backend/Abstract.php

...in folgender Funktion:
protected function _getRequirements()
    {
        $require = array();
        
        if (! empty($this-&gt;_rules)) {
            $require[] = &#039;&quot;fileinto&quot;&#039;;
            ---&gt; $require[] = &#039;&quot;reject&quot;&#039;; &lt;---
...
Es wird automatisch immer &quot;reject&quot; als requirement hinzugefügt.
So wie es aussieht, unterstützt der 1und1-Mail-Server das aber nicht.
Kommentiere ich die Zeile aus, funktioniert die Sieve-Filterung.
Es müsste erst geprüft werden, ob die Funktion vorhanden ist, und erst dann dürfte die Funktion im Frontend (Ablehnen mit...) und hier im Backend verwendet werden.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jul 2012 18:41**

das klingt doch nach einem plan. danke fürs nachforschen :)
