### ISSUE TITLE
0003622:
Sichtbarkeit im Adressbuch erzeugt Fehler mit LDAP als Userbackend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1887]
**Reported by GWI on 31 Dec 2010 09:24**

**Version:** git master

Das einstellen der Sichtbarkeit im Adressbuch erzeugt einen Fehler wenn man unter Sichtbarkeit
 zwischen &quot;Zeige im Adressbuch&quot; und  &quot;Nicht im Adressbuch anzeigen&quot; umschaltet.

Es wird dan folgender Fehler ausgeworfen:
26dec Röllig, Sven - 2010-12-30T12:33:14+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::171 exception &#039;ErrorException&#039; with message &#039;Argument 2 passed to Tinebase_User_Plugin_Abstract::inspectUpdateUser() must be an instance of Tinebase_Model_FullUser, array given, called in /srv/www/htdocs/mail/Tinebase/User/Ldap.php on line 383 and defined&#039; in /srv/www/htdocs/mail/Tinebase/User/Plugin/Abstract.php:38
Stack trace:
#0 /srv/www/htdocs/mail/Tinebase/User/Plugin/Abstract.php(38): Tinebase_Core::errorHandler(Object(Tinebase_Model_FullUser), Array, Array)
#1 /srv/www/htdocs/mail/Tinebase/User/Ldap.php(383): Tinebase_User_Plugin_Abstract-&gt;inspectUpdateUser(Object(Tinebase_Model_FullUser))
#2 /srv/www/htdocs/mail/Tinebase/User/Sql.php(507): Tinebase_User_Ldap-&gt;updateUserInSyncBackend(Object(Tinebase_Model_FullUser))
#3 /srv/www/htdocs/mail/Admin/Controller/User.php(218): Tinebase_User_Sql-&gt;updateUser(Object(Tinebase_Model_FullUser), &#039;&#039;, &#039;&#039;)
#4 /srv/www/htdocs/mail/Admin/Frontend/Json.php(363): Admin_Controller_User-&gt;update(Array)
#5 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array, Array)
#6 /srv/www/htdocs/mail/library/Zend/Server/Abstract.php(232): call_user_func_array(Object(Zend_Server_Method_Definition), Array)
#7 /srv/www/htdocs/mail/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
#8 /srv/www/htdocs/mail/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle(Object(Zend_Json_Server_Request))
#9 /srv/www/htdocs/mail/Tinebase/Server/Json.php(137): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#10 /srv/www/htdocs/mail/Tinebase/Server/Json.php(74): Tinebase_Server_Json-&gt;_handle()
#11 /srv/www/htdocs/mail/Tinebase/Core.php(212): Tinebase_Server_Json-&gt;handle()
#12 /srv/www/htdocs/mail/index.php(56): Tinebase_Core::dispatchRequest()
#13 {main}
26dec Röllig, Sven - 2010-12-30T12:33:14+00:00 WARN (4): Tinebase_Core::errorHandler::334 json_encode() [&lt;a href=&#039;function.json-encode&#039;&gt;function.json-encode&lt;/a&gt;]: recursion detected in /srv/www/htdocs/mail/library/Zend/Json.php::122 (2)

http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=5100&amp;p=20326

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 4 Jan 2011 16:19**

The problem is fixed now in svn.
