### ISSUE TITLE
0003794:
Calender crashes reproducable when creating a parallel event via drag'n'drop

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1971]
**Reported by mmuehlfeld on 17 Jan 2011 10:49**

**Version:** Neele (2011-01) RC 2

See the steps below to make tine crashing with the following message:

Nicht gefunden.
Ihre Anfrage konnte aufgrund von fehlenden Daten nicht beantwortet werden. In den meisten Fällen wurden diese Daten von einem anderen Benutzer gelöscht. Bitte aktualisieren Sie Ihre momentane Ansicht.

This is 100% reproducable with all accounts.

**Steps to reproduce:** - Create an event e. g. today 10-12:00 via drag n drop.
- Create an second event today from 10-13:00 via drag n drop.
- Double-click on the name &quot;Neuer Termin&quot; to edit the details and give it a name
- Click &quot;OK&quot;.

Tine crashes.

**Additional information:** 82a7f Muehlfeld, Marc - 2011-01-17T10:47:48+00:00 INFO (6): Tinebase_Server_Json::_handle::93 is JSON request. method: Calendar.saveEvent
82a7f Muehlfeld, Marc - 2011-01-17T11:47:48+01:00 DEBUG (7): Tinebase_Config::getConfig::103 Config setting &quot;mapPanel&quot; not found, using default (1).
82a7f Muehlfeld, Marc - 2011-01-17T11:47:48+01:00 DEBUG (7): Tinebase_Config::getConfig::114 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
82a7f Muehlfeld, Marc - 2011-01-17T10:47:48+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::171 exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Calendar_Model_Event record with id cal-daysviewpanel-new-ext-gen543 not found!&#039; in /srv/www/htdocs/...../Calendar/Backend/Sql.php:130
Stack trace:
#0 /srv/www/htdocs/...../Tinebase/Backend/Sql/Abstract.php(154): Calendar_Backend_Sql-&gt;getByProperty(&#039;cal-daysviewpan...&#039;, &#039;id&#039;, false)
#1 /srv/www/htdocs/...../Tinebase/Controller/Record/Abstract.php(212): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;cal-daysviewpan...&#039;)
#2 /srv/www/htdocs/...../Calendar/Controller/Event.php(412): Tinebase_Controller_Record_Abstract-&gt;get(&#039;cal-daysviewpan...&#039;)
#3 [internal function]: Calendar_Controller_Event-&gt;update(Object(Calendar_Model_Event), 1)
#4 /srv/www/htdocs/...../Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#5 /srv/www/htdocs/...../Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#6 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#7 /srv/www/htdocs/...../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#8 /srv/www/htdocs/...../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#9 /srv/www/htdocs/...../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#10 /srv/www/htdocs/...../Tinebase/Server/Json.php(137): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#11 /srv/www/htdocs/...../Tinebase/Server/Json.php(74): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#12 /srv/www/htdocs/...../Tinebase/Core.php(219): Tinebase_Server_Json-&gt;handle()
#13 /srv/www/htdocs/...../index.php(57): Tinebase_Core::dispatchRequest()
#14 {main}
82a7f Muehlfeld, Marc - 2011-01-17T10:47:48+00:00 INFO (6): index.php (75) TIME: 0.14571619033813 seconds  MEMORY: 15.25 MBytes  REALPATHCACHESIZE: unknown

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 17 Jan 2011 15:24**

nice bug, thanx for reporting
