### ISSUE TITLE
0003840:
import von ldap Usern bricht bei zu langen email adressen ab.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#1994]
**Reported by GWI on 25 Jan 2011 19:40**

**Version:** git master

PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;email&#039; at row 1&#039; in /srv/www/htdocs/mail/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /srv/www/htdocs/mail/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /srv/www/htdocs/mail/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /srv/www/htdocs/mail/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /srv/www/htdocs/mail/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /srv/www/htdocs/mail/Tinebase/Backend/Sql/Abstract.php(386): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_addressb...&#039;, Array)
#5 /srv/www/htdocs/mail/Addressbook/Backend/Sql.php(85): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#6 /srv/www/htdocs/mail/Tinebase/User.php(415): Addressbook_Backend_Sql in /srv/www/htdocs/mail/library/Zend/Db/Statement/Pdo.php on line 238

**Steps to reproduce:** beim import der LDAP User mittels

php /setup.php --sync_accounts_from_ldap

aber auch beim normalen setup

**Additional information:** habe in der db gesehen das die mails und login namen teilweise
auf max 64 zeichen beschränkt sind.

habe in meinem system ein paar pseudo- und kundenverteiler adressen die
teilweise mehr als 80 zeichen lang sind.

wäre schön wenn in zukunft da ausreichend platz für vorhanden wäre

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 26 Jan 2011 15:14**

I extended the size of the columns to 255.
