### ISSUE TITLE
0003872:
Abgelaufe Session Kill Client Interface

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2010]
**Reported by GWI on 29 Jan 2011 12:24**

**Version:** git master

Wenn die Session in Tine unbemerkt abläuft, bekommt 
man beim weiterarbeiten, beim Reload oder neu öffnen 
des browsers/tab eine weisse seite von tine geliefert.

dies lässt sich nur ändern in dem man im session ordner die session
datei löscht. da man aber nicht weiss welche session wem gehört 
muss man den ganzen ordner löschen.

die entprechende fehlermeldung im tine log sagt die auch aus:

910e6 -- none -- - 2011-01-29T12:08:53+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::171 exception &#039;Tinebase_Exception_AccessDenied&#039; with message &#039;Not Authorised&#039; in /srv/www/htdocs/mail/Tinebase/Server/Json.php:37
Stack trace:
#0 /srv/www/htdocs/mail/Tinebase/Core.php(219): Tinebase_Server_Json-&gt;handle()
#1 /srv/www/htdocs/mail/index.php(57): Tinebase_Core::dispatchRequest()
#2 {main}
910e6 -- none -- - 2011-01-29T12:08:53+00:00 INFO (6): index.php (75) TIME: 0.284562826157 seconds  MEMORY: 6.75 MBytes  REALPATHCACHESIZE: unknown
38030 -- none -- - 2011-01-29T12:09:02+00:00 INFO (6): Tinebase_Core::setupLogger::459 logger initialized
38030 -- none -- - 2011-01-29T12:09:02+00:00 INFO (6): Tinebase_Core::setupCache::521 cache of backend type &#039;File&#039; enabled
38030 -- none -- - 2011-01-29T12:09:02+00:00 INFO (6): Tinebase_Core::setSessionOptionsAndBackend::723 Session of backend type &#039;File&#039; configured.
38030 -- none -- - 2011-01-29T12:09:02+00:00 WARN (4): Tinebase_Core::startSession::628 Session error: This session is not valid according to Zend_Session_Validator_IpAddress.
38030 -- none -- - 2011-01-29T12:09:02+00:00 DEBUG (7): Tinebase_Core::startSession::629 #0 /srv/www/htdocs/mail/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /srv/www/htdocs/mail/Tinebase/Core.php(626): Zend_Session::start()
#2 /srv/www/htdocs/mail/Tinebase/Core.php(587): Tinebase_Core::startSession(Array)
#3 /srv/www/htdocs/mail/Tinebase/Core.php(289): Tinebase_Core::setupSession()
#4 /srv/www/htdocs/mail/Tinebase/Server/Json.php(30): Tinebase_Core::initFramework()
#5 /srv/www/htdocs/mail/Tinebase/Core.php(219): Tinebase_Server_Json-&gt;handle()
#6 /srv/www/htdocs/mail/index.php(57): Tinebase_Core::dispatchRequest()
#7 {main}
38030 -- none -- - 2011-01-29T12:09:02+00:00 DEBUG (7): Tinebase_Server_Json::handle::33 initFramework exception: exception &#039;Zend_Session_Exception&#039; with message &#039;This session is not valid according to Zend_Session_Validator_IpAddress.&#039; in /srv/www/htdocs/mail/library/Zend/Session.php:782
Stack trace:
#0 /srv/www/htdocs/mail/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /srv/www/htdocs/mail/Tinebase/Core.php(626): Zend_Session::start()
#2 /srv/www/htdocs/mail/Tinebase/Core.php(587): Tinebase_Core::startSession(Array)
#3 /srv/www/htdocs/mail/Tinebase/Core.php(289): Tinebase_Core::setupSession()
#4 /srv/www/htdocs/mail/Tinebase/Server/Json.php(30): Tinebase_Core::initFramework()
#5 /srv/www/htdocs/mail/Tinebase/Core.php(219): Tinebase_Server_Json-&gt;handle()
#6 /srv/www/htdocs/mail/index.php(57): Tinebase_Core::dispatchRequest()
#7 {main}
38030 -- none -- - 2011-01-29T12:09:02+00:00 DEBUG (7): Tinebase_Server_Json::handle::63 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase.logout
            [params] =&gt; Array
                (
                )

            [id] =&gt; 356
        )

)

ein erneutes aufrufen der index.php bringt folgende fehlermeldung und
eine weisse seite:

f8bb7 -- none -- - 2011-01-29T12:20:16+00:00 INFO (6): Tinebase_Core::setupLogger::459 logger initialized
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 INFO (6): Tinebase_Core::setupCache::521 cache of backend type &#039;File&#039; enabled
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 INFO (6): Tinebase_Core::setSessionOptionsAndBackend::723 Session of backend type &#039;File&#039; configured.
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 WARN (4): Tinebase_Core::startSession::628 Session error: This session is not valid according to Zend_Session_Validator_IpAddress.
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 DEBUG (7): Tinebase_Core::startSession::629 #0 /srv/www/htdocs/mail/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /srv/www/htdocs/mail/Tinebase/Core.php(626): Zend_Session::start()
#2 /srv/www/htdocs/mail/Tinebase/Core.php(587): Tinebase_Core::startSession(Array)
#3 /srv/www/htdocs/mail/Tinebase/Core.php(289): Tinebase_Core::setupSession()
#4 /srv/www/htdocs/mail/Tinebase/Server/Http.php(31): Tinebase_Core::initFramework()
#5 /srv/www/htdocs/mail/Tinebase/Core.php(219): Tinebase_Server_Http-&gt;handle()
#6 /srv/www/htdocs/mail/index.php(57): Tinebase_Core::dispatchRequest()
#7 {main}
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 INFO (6): exception &#039;Zend_Session_Exception&#039; with message &#039;This session is not valid according to Zend_Session_Validator_IpAddress.&#039; in /srv/www/htdocs/mail/library/Zend/Session.php:782
Stack trace:
#0 /srv/www/htdocs/mail/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /srv/www/htdocs/mail/Tinebase/Core.php(626): Zend_Session::start()
#2 /srv/www/htdocs/mail/Tinebase/Core.php(587): Tinebase_Core::startSession(Array)
#3 /srv/www/htdocs/mail/Tinebase/Core.php(289): Tinebase_Core::setupSession()
#4 /srv/www/htdocs/mail/Tinebase/Server/Http.php(31): Tinebase_Core::initFramework()
#5 /srv/www/htdocs/mail/Tinebase/Core.php(219): Tinebase_Server_Http-&gt;handle()
#6 /srv/www/htdocs/mail/index.php(57): Tinebase_Core::dispatchRequest()
#7 {main}
f8bb7 -- none -- - 2011-01-29T12:20:17+00:00 INFO (6): Tinebase_Server_Http::handle::69 Attempt to request a privileged Http-API method without valid session from &quot;10.10.10.100

nach dem löschen der session dateien bekommt man wie gewohnt den login zu sehen

**Comment by Gloirin** [comment]
**Comment posted by GWI on 10 May 2011 17:12**

wäre vielleicht besser dann gleich die alte session zu killen und ne 
neue zu starten, der fehler tritt im übrigen auch auf wenn ich mit
dem notebook von ap zu ap unterwegs bin (jedenfalls in verschiedenen netzen)
lässt sich aber bisher nicht wirklich gezielt reproduzieren!!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2012 13:20**

ich glaube, ich habe das problem gelöst:
es wurde an der stelle nur eine bestimmte exception (Zend_Session_Exception) gefangen, alle anderen (z.b. Tinebase_Exception_AccessDenied) sind durchgeschlagen und die session wurde nicht zurückgesetzt.

bitte mal prüfen, ob der fehler nun noch auftritt!

**Comment by Gloirin** [comment]
**Comment posted by GWI on 3 Jan 2012 15:02**

haha, allein das lies sich ja schon kaum gezielt reproduzieren.

aber bisher hab ich damit keinerlei probleme mehr gehabt.
weder bei mir zu hause, mit dsl, noch auf dem laptop mit wlan und
hsdpa.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2012 15:18**

:)

ich schliesse den task mal, da ich denke, dass es nun funktionieren sollte.

falls der fehler doch wieder auftritt, einfach wieder aufmachen!
