### ISSUE TITLE
0004290:
Update von Neele auf Maischa Beta 1 nicht möglich

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2214]
**Reported by splinter03 on 11 May 2011 08:42**

**Version:** Maischa (2011-05) Beta 1

Ich möchte meine Neele-Version gerne Testweise auf Maischa Beta 1 aktualisieren. Alle Anwendungen konnten erfolgreich aktualisiert werden, bis auf Felamimail.

**Additional information:** Auszug aus dem Log:

c0b5b -- none -- - 2011-05-10T12:41:09+00:00 ERR (3): Setup_Controller::updateApplication::355 SQLSTATE[42000]: Syntax error or access violation: 1091 Can&#039;t DROP &#039;imap_uidnext&#039;; check that column/key exists
c0b5b -- none -- - 2011-05-10T12:41:09+00:00 ERR (3): Setup_Controller::updateApplication::356 #0 /var/www/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/www/tine20/Setup/Backend/Abstract.php(202): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/tine20/Setup/Backend/Abstract.php(293): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 /var/www/tine20/Felamimail/Setup/Update/Release4.php(136): Setup_Backend_Abstract-&gt;dropCol(&#039;felamimail_fold...&#039;, &#039;imap_uidnext&#039;)
#6 /var/www/tine20/Setup/Controller.php(349): Felamimail_Setup_Update_Release4-&gt;update_3()
#7 /var/www/tine20/Setup/Controller.php(251): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#8 /var/www/tine20/Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /var/www/tine20/Setup/Server/Json.php(75): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 /var/www/tine20/Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#15 /var/www/tine20/setup.php(53): Setup_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 May 2011 18:22**

habe dir die gefixte Felamimail/Setup/Release4.php angehängt.

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 13 May 2011 21:08**

Leider klappt es bei mir immer noch nicht...nun erhalte ich folgenden Fehler:

09062 -- none -- - 2011-05-13T21:06:13+00:00 ERR (3): Setup_Controller::updateApplication::355 SQLSTATE[42000]: Syntax error or access violation: 1091 Can&#039;t DROP &#039;user_id&#039;; check that column/key exists
09062 -- none -- - 2011-05-13T21:06:13+00:00 ERR (3): Setup_Controller::updateApplication::356 #0 /var/www/tine20ut/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20ut/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20ut/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/www/tine20ut/tine20/Setup/Backend/Abstract.php(202): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/tine20ut/tine20/Setup/Backend/Abstract.php(293): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 /var/www/tine20ut/tine20/Tinebase/Setup/Update/Release4.php(155): Setup_Backend_Abstract-&gt;dropCol(&#039;felamimail_fold...&#039;, &#039;user_id&#039;)
#6 /var/www/tine20ut/tine20/Setup/Controller.php(349): Felamimail_Setup_Update_Release4-&gt;update_4()
#7 /var/www/tine20ut/tine20/Setup/Controller.php(251): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#8 /var/www/tine20ut/tine20/Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 /var/www/tine20ut/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /var/www/tine20ut/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /var/www/tine20ut/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /var/www/tine20ut/tine20/Setup/Server/Json.php(75): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 /var/www/tine20ut/tine20/Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#15 /var/www/tine20ut/tine20/setup.php(53): Setup_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 May 2011 18:46**

nun sollte es klappen.

hier gibts die Release4.php: http://git.tine20.org/git?p=tine20;a=blob_plain;f=tine20/Felamimail/Setup/Update/Release4.php;hb=1c51f3fa107ced97b3d7becd03083d961c06b25e
