### ISSUE TITLE
0004378:
Sometimes tine20 generates white-pages only

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2257]
**Reported by weberho on 24 May 2011 06:04**

**Version:** Neele (2011-01-5)

NOTICE (5): Tinebase_Core::errorHandler::356 Undefined index: HTTP_IF_MODIFIED_SINCE in /var/lib/tine20/webroot/Tinebase/Frontend/Http.php::664 (8)
INFO (6): exception &#039;Zend_Cache_Exception&#039; with message &#039;Invalid id or tag : must be a string&#039; in /var/lib/tine20/webroot/library/Zend/Cache.php:208
Stack trace:
#0 /var/lib/tine20/webroot/library/Zend/Cache/Core.php(572): Zend_Cache::throwException(&#039;Invalid id or t...&#039;)
#1 /var/lib/tine20/webroot/library/Zend/Cache/Core.php(296): Zend_Cache_Core::_validateIdOrTag(NULL)
#2 /var/lib/tine20/webroot/library/Zend/Cache/Frontend/File.php(181): Zend_Cache_Core-&gt;test(NULL)
#3 /var/lib/tine20/webroot/Tinebase/Frontend/Http.php(699): Zend_Cache_Frontend_File-&gt;test(NULL)
#4 /var/lib/tine20/webroot/Tinebase/Frontend/Http.php(627): Tinebase_Frontend_Http-&gt;_deliverChangedFiles(&#039;js&#039;)
#5 [internal function]: Tinebase_Frontend_Http-&gt;getJsFiles()
#6 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#7 /var/lib/tine20/webroot/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#8 /var/lib/tine20/webroot/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#9 /var/lib/tine20/webroot/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 /var/lib/tine20/webroot/Tinebase/Server/Http.php(62): Tinebase_Http_Server-&gt;handle(Array)
#11 /var/lib/tine20/webroot/Tinebase/Core.php(223): Tinebase_Server_Http-&gt;handle()
#12 /var/lib/tine20/webroot/index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}

**Additional information:** There seem to be situations, where HTTP_IF_NONE_MATCH is set and HTTP_IF_MODIFIED_SINCE is not set. Should be checked, too.

Are there really situation where the mixed-case variables If_None_Match and If_Modified_Since exists? I have never seen this situation and can not find them documented in PHP.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 May 2011 11:56**

thanks for reporting!

just added the check for HTTP_IF_MODIFIED_SINCE.
