### ISSUE TITLE
0004380:
Deleting an E-Mail account fails if a message cache update process is running atm

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2258]
**Reported by weberho on 24 May 2011 06:45**

**Version:** Neele (2011-01-5)

Deleting an E-Mail account fails if a message cache update process is running atm

possible solution: just mark the account as deleted and leave everything in the db (that means: add modlog fields to accounts)

---
While testing, I have added the exactly same Mail-Accout two times. Now I get an exception when I delete it.

ERR (3): Tinebase_Controller_Record_Abstract::delete::583 SQLSTATE[HY000]: General error: 1030 Got error -1 from storage engine
ERR (3): Tinebase_Controller_Record_Abstract::delete::584 #0 /var/lib/tine20/webroot/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;, Array)
#3 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Abstract.php(633): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;)
#4 /var/lib/tine20/webroot/Tinebase/Backend/Sql/Abstract.php(511): Zend_Db_Adapter_Abstract-&gt;delete(&#039;tine20_felamima...&#039;, Array)
#5 /var/lib/tine20/webroot/Tinebase/Controller/Record/Abstract.php(692): Tinebase_Backend_Sql_Abstract-&gt;delete(Object(Felamimail_Model_Account))
#6 /var/lib/tine20/webroot/Tinebase/Controller/Record/Abstract.php(568): Tinebase_Controller_Record_Abstract-&gt;_deleteRecord(Object(Felamimail_Model_Account))
#7 /var/lib/tine20/webroot/Felamimail/Controller/Account.php(217): Tinebase_Controller_Record_Abstract-&gt;delete(Array)
#8 /var/lib/tine20/webroot/Tinebase/Frontend/Json/Abstract.php(224): Felamimail_Controller_Account-&gt;delete(Array)
#9 /var/lib/tine20/webroot/Felamimail/Frontend/Json.php(400): Tinebase_Frontend_Json_Abstract-&gt;_delete(Array, Object(Felamimail_Controller_Account))
#10 [internal function]: Felamimail_Frontend_Json-&gt;deleteAccounts(Array)
#11 /var/lib/tine20/webroot/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /var/lib/tine20/webroot/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /var/lib/tine20/webroot/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /var/lib/tine20/webroot/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 /var/lib/tine20/webroot/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#16 /var/lib/tine20/webroot/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#17 /var/lib/tine20/webroot/index.php(57): Tinebase_Core::dispatchRequest()
#18 {main}
f2a9f Weberhofer, Johannes - 2011-05-24T06:35:39+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 SQLSTATE[HY000]: General error: 1030 Got error -1 from storage engine
f2a9f Weberhofer, Johannes - 2011-05-24T06:35:39+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::229 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(633): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;)
#4 .../Tinebase/Backend/Sql/Abstract.php(511): Zend_Db_Adapter_Abstract-&gt;delete(&#039;tine20_felamima...&#039;, Array)
#5 .../Tinebase/Controller/Record/Abstract.php(692): Tinebase_Backend_Sql_Abstract-&gt;delete(Object(Felamimail_Model_Account))
#6 .../Tinebase/Controller/Record/Abstract.php(568): Tinebase_Controller_Record_Abstract-&gt;_deleteRecord(Object(Felamimail_Model_Account))
#7 .../Felamimail/Controller/Account.php(217): Tinebase_Controller_Record_Abstract-&gt;delete(Array)
#8 .../Tinebase/Frontend/Json/Abstract.php(224): Felamimail_Controller_Account-&gt;delete(Array)
#9 .../Felamimail/Frontend/Json.php(400): Tinebase_Frontend_Json_Abstract-&gt;_delete(Array, Object(Felamimail_Controller_Account))
#10 [internal function]: Felamimail_Frontend_Json-&gt;deleteAccounts(Array)
#11 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#16 .../Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#17 .../index.php(57): Tinebase_Core::dispatchRequest()
#18 {main}

**Additional information:** The bad thing is, that I can not login until I delete all my tine20-related cookies

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 May 2011 12:55**

did you clone the email account (with sql commands) and they both have the same id in the database?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 24 May 2011 13:51**

no, I didn&#039;t; but I played around and added it twice.

the id in tine20_felamimail_account differs, too.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 May 2011 10:16**

so you added both accounts in tine? i just did that and could delete the second account without any problems.

the strange sql error message &quot;General error: 1030 Got error -1 from storage engine&quot; looks more like a general problem with your database.

i could not find much useful information about this error in the net. except for this: http://forums.innodb.com/read.php?4,1367,1367#msg-1367 (and the blog post in chinaunix.net)

**Comment by Gloirin** [comment]
**Comment posted by weberho on 25 May 2011 11:48**

The account I&#039;ve added is very huge. I&#039;ve recognized, that since hours the account refreshes.

I suspect the refresh process to block the deletion of the account; if it ever stops refreshing, I&#039;ll try to delete again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 May 2011 11:58**

ah, that makes sense ... when folders are updated and the cache is filled, we lock the folder row in the database. that could prevent the deletion.

i&#039;ll change the description / title of this issue ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 May 2011 12:59**

accounts are now only marked as deleted and no longer completely removed from db.
