### ISSUE TITLE
0004382:
Sometimes tine20 generates white-pages only II

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2259]
**Reported by weberho on 24 May 2011 06:50**

**Version:** Neele (2011-01-5)

Sometimes I get white pages only, until I delete all tine-related cookies. IP-changed between last successful login and next try; last thing on the old IP was, that  I have got an invalid session, because the E-Mail Address could not be deleted).

Shouldn&#039;t the session been destroyed and re-created when invalid?

**Additional information:** WARN (4): Tinebase_Core::startSession::636 Session error: This session is not valid according to Zend_Session_Validator_IpAddress.
INFO (6): exception &#039;Zend_Session_Exception&#039; with message &#039;This session is not valid according to Zend_Session_Validator_IpAddress.&#039; in /var/lib/tine20/webroot/library/Zend/Session.php:782
Stack trace:
#0 /var/lib/tine20/webroot/library/Zend/Session.php(506): Zend_Session::_processValidators()
#1 /var/lib/tine20/webroot/Tinebase/Core.php(634): Zend_Session::start()
#2 /var/lib/tine20/webroot/Tinebase/Core.php(595): Tinebase_Core::startSession(Array)
#3 /var/lib/tine20/webroot/Tinebase/Core.php(293): Tinebase_Core::setupSession()
#4 /var/lib/tine20/webroot/Tinebase/Server/Http.php(31): Tinebase_Core::initFramework()
#5 /var/lib/tine20/webroot/Tinebase/Core.php(223): Tinebase_Server_Http-&gt;handle()
#6 /var/lib/tine20/webroot/index.php(57): Tinebase_Core::dispatchRequest()
#7 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 May 2011 12:08**

the session is now destroyed if starting fails.
