### ISSUE TITLE
0004468:
Kein Trash bei Freenet.de bzw. ungewöhnliche ordner struktur

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2302]
**Reported by GWI on 5 Jun 2011 20:44**

**Version:** git master

Bei Freenet.de mailaccounts besteht das problem das offenbar
alle weitenren ordner unterhalb von INBOS liegen.

daher ist es auch nicht möglich das tine eine gelöschte mail in den trash
verschieben kann.

tine erzeugt im interface die lapidare meldung das die mail 
nicht gelöscht werden konnte.

das log dazu sieht wie folgt aus:

INFO (6): Tinebase_Core::setupUserLocale::861 user locale: de
INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Felamimail.moveMessages
INFO (6): Tinebase_Core::setExecutionLifeTime::953 setting execution life time to: 0
INFO (6): Felamimail_Controller_Account::updateCapabilities::510 Updating capabilities for account: g******@freenet.de
NOTICE (5): Felamimail_Controller_Account::_createSystemFolder::667 Folder not found: Trash. Trying to add it.
INFO (6): Felamimail_Controller_Folder::create::246 Could not create new folder: Trash (cannot create folder Trash)
INFO (6): Felamimail_Controller_Cache_Folder::_getRootFolders::133 Get subfolders of root for account 34fd16e0864e2f1d1fa255e4d7b09c6d599386ea
NOTICE (5): Tinebase_Server_Json::_handleException::161 Felamimail_Exception_IMAPServiceUnavailable -&gt; cannot create folder Trash
NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Felamimail/Controller/Account.php(671): Felamimail_Controller_Folder-&gt;create(Object(Felamimail_Model_Account), &#039;Trash&#039;, &#039;&#039;)
#1 .../Felamimail/Controller/Account.php(638): Felamimail_Controller_Account-&gt;_createSystemFolder(Object(Felamimail_Model_Account), &#039;Trash&#039;)
#2 .../Felamimail/Controller/Message/Move.php(87): Felamimail_Controller_Account-&gt;getSystemFolder(&#039;34fd16e0864e2f1...&#039;, &#039;_trash_&#039;)
#3 .../Felamimail/Frontend/Json.php(199): Felamimail_Controller_Message_Move-&gt;moveMessages(Object(Felamimail_Model_MessageFilter), &#039;_trash_&#039;)
#4 [internal function]: Felamimail_Frontend_Json-&gt;moveMessages(Array, &#039;_trash_&#039;)
#5 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#10 .../Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#11 .../index.php(57): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jun 2011 09:05**

vermutlich ein namespace problem. schaue ich mir an.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jun 2011 12:23**

bitte mal mit aktuellen checkout aus dem git ausprobieren. habe den namespace nun beim anlegen eines neuen Trash ordners mit angegeben.

falls es nicht tut, müsstest du evtl. ein wenig beim debuggen helfen ... ;)

**Comment by Gloirin** [comment]
**Comment posted by GWI on 7 Jun 2011 16:59**

NÖ läuft nicht!!!

fehler meldung:
cannot create folder Trash

tine log die selbe meldung wie oben

im übrigen der trash ordner existiert und muss nicht angelegt werden, 
der trash liegt halt nur unter INBOX.Trash

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Jun 2011 21:01**

ah, es gibt schon nen trash. interessant. dann funktioniert das einlesen der capabilities / namespaces wohl nicht richtig.

kannst du mal ein logfile schicken / anhängen, in dem der erste connect zum freenet server (nach dem login des users in tine) protokolliert wird? am besten den logger auf TRACE (8) stellen.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 8 Jun 2011 17:48**

kann ich dir den trace mal per mail schicken??

sonst müsste ich das erst bereinigen!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Jun 2011 20:17**

klaro, gerne per mail!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Jun 2011 16:59**

ah, bei dem freenet wird der benutzte namespace nicht zurückgegeben (mit den capabilities). habe nun einen fallback eingebaut, der einfach INBOX als parent annimmt, wenn das anlegen des systemordners nicht klappt.

bitte nochmal ausprobieren :)

**Comment by Gloirin** [comment]
**Comment posted by GWI on 15 Jun 2011 21:58**

einwandfrei, klappt SUPER

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Jun 2011 06:43**

freut mich, dann schliesse ich das ticket :)
