### ISSUE TITLE
0004544:
Creating/Deleting event in calender throws exception

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2334]
**Reported by Olodin on 20 Jun 2011 18:26**

**Version:** Neele (2011-01-6)

I have created a user to have a shared calender for ActiveSync devices, separated from their own user accounts.

Creating or deleting a calendar inside tine20 seems to work, the entry is shown. But in the logs I get an exception (see Additional Information).

Since I see some messages about permissions/grants in the log I&#039;ve checked permissions of the user: he is member of the default Users group and has all rights to the calendar.

Is something wrong with my installation?

**Additional information:** Debug Log:

bd13c -- none -- - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Core::setupLogger::463 logger initialized
bd13c -- none -- - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Core::setupCache::528 cache of backend type &#039;File&#039; enabled
bd13c -- none -- - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Core::setSessionOptionsAndBackend::731 Session of backend type &#039;File&#039; configured.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::955 setting execution life time to: 0
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Group::getInstance::58 groups backend: Sql
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Core::setupUserLocale::843 given localeString &#039;auto&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Translation::getLocale::179 given localeString &#039;auto&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Translation::getLocale::191 &#039;de_DE&#039; is not supported, checking fallback
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 selected locale: &#039;de&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Calendar.saveEvent
            [params] =&gt; Array
                (
                    [recordData] =&gt; Array
                        (
                            [summary] =&gt; Neuer Termin
                            [dtstart] =&gt; 2011-06-22 11:30:00
                            [dtend] =&gt; 2011-06-22 12:30:00
                            [container_id] =&gt; Array
                                (
                                    [creation_time] =&gt; 2011-06-19 20:17:05
                                    [created_by] =&gt; cf68c4ea193f8f4ba512c21fa9ff0634560a9be8
                                    [last_modified_time] =&gt; 
                                    [last_modified_by] =&gt; 
                                    [is_deleted] =&gt; 0
                                    [deleted_time] =&gt; 
                                    [deleted_by] =&gt; 
                                    [id] =&gt; 67
                                    [name] =&gt; name
                                    [type] =&gt; personal
                                    [color] =&gt; 
                                    [path] =&gt; /personal/cf68c4ea193f8f4ba512c21fa9ff0634560a9be8/67
                                    [backend] =&gt; Sql
                                    [application_id] =&gt; e8c9c6f4db6740b828b93f9f7a88bcdc37dcf836
                                    [account_grants] =&gt; Array
                                        (
                                            [readGrant] =&gt; 1
                                            [addGrant] =&gt; 1
                                            [editGrant] =&gt; 1
                                            [deleteGrant] =&gt; 1
                                            [privateGrant] =&gt; 1
                                            [exportGrant] =&gt; 1
                                            [syncGrant] =&gt; 1
                                            [adminGrant] =&gt; 1
                                            [freebusyGrant] =&gt; 1
                                            [account_id] =&gt; cf68c4ea193f8f4ba512c21fa9ff0634560a9be8
                                            [account_type] =&gt; account
                                        )

                                    [capabilites_private] =&gt; 1
                                )

                            [transp] =&gt; OPAQUE
                            [editGrant] =&gt; 1
                            [organizer] =&gt; Array
                                (
                                    [id] =&gt; 46fef667c02ca1e256f6cf9ae917f8fdc065ed8e
                                    [adr_one_countryname] =&gt; 
                                    [adr_one_locality] =&gt; 
                                    [adr_one_postalcode] =&gt; 
                                    [adr_one_region] =&gt; 
                                    [adr_one_street] =&gt; 
                                    [adr_one_street2] =&gt; 
                                    [adr_two_countryname] =&gt; 
                                    [adr_two_locality] =&gt; 
                                    [adr_two_postalcode] =&gt; 
                                    [adr_two_region] =&gt; 
                                    [adr_two_street] =&gt; 
                                    [adr_two_street2] =&gt; 
                                    [assistent] =&gt; 
                                    [bday] =&gt; 
                                    [calendar_uri] =&gt; 
                                    [email] =&gt; name@test.local
                                    [email_home] =&gt; 
                                    [freebusy_uri] =&gt; 
                                    [jpegphoto] =&gt; 0
                                    [note] =&gt; 
                                    [container_id] =&gt; 
                                    [pubkey] =&gt; 
                                    [role] =&gt; 
                                    [room] =&gt; 
                                    [salutation_id] =&gt; 
                                    [title] =&gt; 
                                    [tz] =&gt; 
                                    [url] =&gt; 
                                    [url_home] =&gt; 
                                    [n_family] =&gt; Name
                                    [n_fileas] =&gt; Name, Vorname
                                    [n_fn] =&gt; Familie Name
                                    [n_given] =&gt; Familie
                                    [n_middle] =&gt; 
                                    [n_prefix] =&gt; 
                                    [n_suffix] =&gt; 
                                    [org_name] =&gt; 
                                    [org_unit] =&gt; 
                                    [tel_assistent] =&gt; 
                                    [tel_car] =&gt; 
                                    [tel_cell] =&gt; 
                                    [tel_cell_private] =&gt; 
                                    [tel_fax] =&gt; 
                                    [tel_fax_home] =&gt; 
                                    [tel_home] =&gt; 
                                    [tel_pager] =&gt; 
                                    [tel_work] =&gt; 
                                    [created_by] =&gt; 
                                    [creation_time] =&gt; 
                                    [last_modified_by] =&gt; 9aa24383ebda3ffc0e50fce3331fa4f20d26c55a
                                    [last_modified_time] =&gt; 2011-06-20 18:09:52
                                    [is_deleted] =&gt; 0
                                    [deleted_by] =&gt; 
                                    [deleted_time] =&gt; 
                                    [lon] =&gt; 
                                    [lat] =&gt; 
                                    [type] =&gt; user
                                    [account_id] =&gt; cf68c4ea193f8f4ba512c21fa9ff0634560a9be8
                                )

                            [attendee] =&gt; Array
                                (
                                    [0] =&gt; Array
                                        (
                                            [user_type] =&gt; user
                                            [role] =&gt; REQ
                                            [quantity] =&gt; 1
                                            [status] =&gt; ACCEPTED
                                            [user_id] =&gt; Array
                                                (
                                                    [accountId] =&gt; cf68c4ea193f8f4ba512c21fa9ff0634560a9be8
                                                    [accountLoginName] =&gt; name
                                                    [accountLastLogin] =&gt; 2011-06-20 17:03:34
                                                    [accountLastLoginfrom] =&gt; 192.168.97.31
                                                    [accountLastPasswordChange] =&gt; 2011-06-19 19:38:20
                                                    [accountStatus] =&gt; enabled
                                                    [accountExpires] =&gt; 
                                                    [accountPrimaryGroup] =&gt; 2
                                                    [accountHomeDirectory] =&gt; 
                                                    [accountLoginShell] =&gt; 
                                                    [accountDisplayName] =&gt; Name, Vorname
                                                    [accountFullName] =&gt; Familie Name
                                                    [accountFirstName] =&gt; Familie
                                                    [accountLastName] =&gt; Name
                                                    [accountEmailAddress] =&gt; name@test.local
                                                    [lastLoginFailure] =&gt; 
                                                    [loginFailures] =&gt; 0
                                                    [contact_id] =&gt; 46fef667c02ca1e256f6cf9ae917f8fdc065ed8e
                                                    [openid] =&gt; 
                                                    [visibility] =&gt; hidden
                                                    [container_id] =&gt; 
                                                )

                                        )

                                )

                            [id] =&gt; 
                            [is_all_day_event] =&gt; 
                        )

                    [checkBusyConficts] =&gt; 1
                )

            [id] =&gt; 13
        )

)

bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Calendar.saveEvent
bd13c Name, Vorname - 2011-06-20T20:18:02+02:00 DEBUG (7): Tinebase_Config::getConfig::103 Config setting &quot;mapPanel&quot; not found, using default (1).
bd13c Name, Vorname - 2011-06-20T20:18:02+02:00 DEBUG (7): Tinebase_Config::getConfig::114 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
bd13c Name, Vorname - 2011-06-20T20:18:02+02:00 DEBUG (7): Addressbook_Controller_Contact::__construct::44 Mappanel/geoext/nominatim disabled with config option.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::521 filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::521 filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::521 filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::521 filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::521 filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Translation::getTranslation::245 locale used: de
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_User::getInstance::129 accounts backend: Sql
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Controller_Record_Abstract::getAlarms::930 Resolving alarms and add them to record.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Calendar_Controller_Event::_saveAttendee::1121 About to save attendee for event 9123b515b3cf13eb03ee53f7fb8f88fd83efb3eb 
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Controller_Record_Abstract::getAlarms::930 Resolving alarms and add them to record.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Backend_Sql_Abstract::delete::500 No records deleted.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /usr/local/www/apache22/data/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /usr/local/www/apache22/data/tine20/Tinebase/Model/User.php(294): Tinebase_Container-&gt;hasGrant(&#039;cf68c4ea193f8f4...&#039;, NULL, &#039;adminGrant&#039;)
#2 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(746): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;adminGrant&#039;)
#3 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(214): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_Contact), &#039;get&#039;)
#4 /usr/local/www/apache22/data/tine20/Calendar/Model/Attender.php(122): Tinebase_Controller_Record_Abstract-&gt;get(&#039;46fef667c02ca1e...&#039;)
#5 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1157): Calendar_Model_Attender-&gt;getUserAccountId()
#6 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1140): Calendar_Controller_Event-&gt;_createAttender(Object(Calendar_Model_Attender), Object(Tinebase_Model_Container))
#7 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(186): Calendar_Controller_Event-&gt;_saveAttendee(Object(Calendar_Model_Event))
#8 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#9 /usr/local/www/apache22/data/tine20/Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#10 /usr/local/www/apache22/data/tine20/Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#11 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#12 /usr/local/www/apache22/data/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#17 /usr/local/www/apache22/data/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#18 /usr/local/www/apache22/data/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#19 {main}
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /usr/local/www/apache22/data/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /usr/local/www/apache22/data/tine20/Tinebase/Model/User.php(294): Tinebase_Container-&gt;hasGrant(&#039;cf68c4ea193f8f4...&#039;, NULL, &#039;readGrant&#039;)
#2 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(754): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;readGrant&#039;)
#3 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(214): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_Contact), &#039;get&#039;)
#4 /usr/local/www/apache22/data/tine20/Calendar/Model/Attender.php(122): Tinebase_Controller_Record_Abstract-&gt;get(&#039;46fef667c02ca1e...&#039;)
#5 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1157): Calendar_Model_Attender-&gt;getUserAccountId()
#6 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1140): Calendar_Controller_Event-&gt;_createAttender(Object(Calendar_Model_Attender), Object(Tinebase_Model_Container))
#7 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(186): Calendar_Controller_Event-&gt;_saveAttendee(Object(Calendar_Model_Event))
#8 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#9 /usr/local/www/apache22/data/tine20/Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#10 /usr/local/www/apache22/data/tine20/Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#11 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#12 /usr/local/www/apache22/data/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#17 /usr/local/www/apache22/data/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#18 /usr/local/www/apache22/data/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#19 {main}
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_Controller_Record_Abstract::getAlarms::930 Resolving alarms and add them to record.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_ActionQueue::queueAction::138 queuing action: &#039;Calendar.sendEventNotifications&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 NOTICE (5): Tinebase_ActionQueue::queueAction::152 no queue configured -&gt; directly execute action: &#039;Calendar.sendEventNotifications&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): Tinebase_ActionQueue::_executeAction::192 executing action: &#039;Calendar.sendEventNotifications&#039;
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /usr/local/www/apache22/data/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /usr/local/www/apache22/data/tine20/Tinebase/Model/User.php(294): Tinebase_Container-&gt;hasGrant(&#039;cf68c4ea193f8f4...&#039;, NULL, &#039;adminGrant&#039;)
#2 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(746): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;adminGrant&#039;)
#3 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(214): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_Contact), &#039;get&#039;)
#4 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(224): Tinebase_Controller_Record_Abstract-&gt;get(&#039;46fef667c02ca1e...&#039;)
#5 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(148): Calendar_Controller_EventNotifications-&gt;sendNotificationToAttender(Object(Calendar_Model_Attender), Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, 10)
#6 /usr/local/www/apache22/data/tine20/Calendar/Controller.php(181): Calendar_Controller_EventNotifications-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#7 [internal function]: Calendar_Controller-&gt;sendEventNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#8 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(213): call_user_func_array(Array, Array)
#9 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(194): Tinebase_ActionQueue-&gt;_executeDecodedAction(Array)
#10 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(153): Tinebase_ActionQueue-&gt;_executeAction(&#039;a:2:{s:6:&quot;actio...&#039;)
#11 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1306): Tinebase_ActionQueue-&gt;queueAction(&#039;Calendar.sendEv...&#039;, Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#12 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(200): Calendar_Controller_Event-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;)
#13 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#14 /usr/local/www/apache22/data/tine20/Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#15 /usr/local/www/apache22/data/tine20/Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#16 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#17 /usr/local/www/apache22/data/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#18 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#19 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#20 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#21 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#22 /usr/local/www/apache22/data/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#23 /usr/local/www/apache22/data/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#24 {main}
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0.
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /usr/local/www/apache22/data/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /usr/local/www/apache22/data/tine20/Tinebase/Model/User.php(294): Tinebase_Container-&gt;hasGrant(&#039;cf68c4ea193f8f4...&#039;, NULL, &#039;readGrant&#039;)
#2 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(754): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;readGrant&#039;)
#3 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(214): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_Contact), &#039;get&#039;)
#4 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(224): Tinebase_Controller_Record_Abstract-&gt;get(&#039;46fef667c02ca1e...&#039;)
#5 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(148): Calendar_Controller_EventNotifications-&gt;sendNotificationToAttender(Object(Calendar_Model_Attender), Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, 10)
#6 /usr/local/www/apache22/data/tine20/Calendar/Controller.php(181): Calendar_Controller_EventNotifications-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#7 [internal function]: Calendar_Controller-&gt;sendEventNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#8 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(213): call_user_func_array(Array, Array)
#9 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(194): Tinebase_ActionQueue-&gt;_executeDecodedAction(Array)
#10 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(153): Tinebase_ActionQueue-&gt;_executeAction(&#039;a:2:{s:6:&quot;actio...&#039;)
#11 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1306): Tinebase_ActionQueue-&gt;queueAction(&#039;Calendar.sendEv...&#039;, Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#12 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(200): Calendar_Controller_Event-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;)
#13 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#14 /usr/local/www/apache22/data/tine20/Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#15 /usr/local/www/apache22/data/tine20/Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#16 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#17 /usr/local/www/apache22/data/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#18 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#19 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#20 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#21 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#22 /usr/local/www/apache22/data/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#23 /usr/local/www/apache22/data/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#24 {main}
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 ERR (3): Tinebase_ActionQueue::_executeDecodedAction::216 could not execute action :exception &#039;Tinebase_Exception_AccessDenied&#039; with message &#039;No Permission.&#039; in /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php:770
Stack trace:
#0 /usr/local/www/apache22/data/tine20/Tinebase/Controller/Record/Abstract.php(214): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_Contact), &#039;get&#039;)
#1 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(224): Tinebase_Controller_Record_Abstract-&gt;get(&#039;46fef667c02ca1e...&#039;)
#2 /usr/local/www/apache22/data/tine20/Calendar/Controller/EventNotifications.php(148): Calendar_Controller_EventNotifications-&gt;sendNotificationToAttender(Object(Calendar_Model_Attender), Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, 10)
#3 /usr/local/www/apache22/data/tine20/Calendar/Controller.php(181): Calendar_Controller_EventNotifications-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#4 [internal function]: Calendar_Controller-&gt;sendEventNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#5 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(213): call_user_func_array(Array, Array)
#6 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(194): Tinebase_ActionQueue-&gt;_executeDecodedAction(Array)
#7 /usr/local/www/apache22/data/tine20/Tinebase/ActionQueue.php(153): Tinebase_ActionQueue-&gt;_executeAction(&#039;a:2:{s:6:&quot;actio...&#039;)
#8 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(1306): Tinebase_ActionQueue-&gt;queueAction(&#039;Calendar.sendEv...&#039;, Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;, NULL)
#9 /usr/local/www/apache22/data/tine20/Calendar/Controller/Event.php(200): Calendar_Controller_Event-&gt;doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_FullUser), &#039;created&#039;)
#10 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#11 /usr/local/www/apache22/data/tine20/Tinebase/Frontend/Json/Abstract.php(164): call_user_func_array(Array, Array)
#12 /usr/local/www/apache22/data/tine20/Calendar/Frontend/Json.php(190): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#13 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#14 /usr/local/www/apache22/data/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#15 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#16 /usr/local/www/apache22/data/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#17 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#18 /usr/local/www/apache22/data/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#19 /usr/local/www/apache22/data/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#20 /usr/local/www/apache22/data/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#21 {main}
bd13c Name, Vorname - 2011-06-20T18:18:02+00:00 INFO (6): index.php (75) TIME: 0.40962696075439 seconds  MEMORY: 10.25 MBytes  REALPATHCACHESIZE: -54729

**Comment by Gloirin** [comment]
Related to #2222

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 20 Jun 2011 18:33**

I&#039;ve also deleted and created the user with same name but the exception is thrown anyway.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jun 2011 16:20**

is the (attender-)user contact visible in the addressbook and does your user have the grants to read the addressbook-container the user is in?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 22 Jun 2011 20:10**

The user which shares its calendar is set to invisible in addressbooks in the user setup.

I&#039;ve set my user to have all rights in the users calendar.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 22 Jun 2011 20:19**

What I&#039;ve just found in relation to this:

In account user1 I can see two deleted addressbooks from this other user2. In the Addressbook search I choose calendar is one from and in the drop-down-list I can select two calendars which are not there when I am logged in with user2.

Hm, in tine20_container those calendars containers are not shown as deleted.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jun 2011 12:21**

i think this problem is already resolved in Maischa as we only send notifications to user accounts that are visible in the addressbook now.

could you please update to Maischa (2011/05) and try again?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 27 Jun 2011 15:08**

Did a test with 2011-05-1 and there is no &quot;ERR Tinebase_ActionQueue::_executeDecodedAction::216 could not execute action&quot; anymore when adding/deleting events.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jun 2011 20:41**

ok, closing the issue.
