### ISSUE TITLE
0004558:
Syncing of contacts doesn't work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2341]
**Reported by chrisa50 on 27 Jun 2011 18:33**

**Version:** Maischa (2011-05-1)

My Tine has problems to sync the contacts with any activesync-client like android mobile phone. The calendar sync works perfect. There are errors like:

atal error: Uncaught exception &#039;ErrorException&#039; with message &#039;Argument 1 passed to ActiveSync_Controller_Abstract::_getContentFilter() must be an instance of Tinebase_Model_Filter_FilterGroup, null given, called in /var/www/webmail/ActiveSync/Controller/Abstract.php on line 425 and defined&#039; in /var/www/webmail/ActiveSync/Controller/Abstract.php:448
Stack trace:
#0 /var/www/webmail/ActiveSync/Controller/Abstract.php(448): Tinebase_Core::errorHandler(4096, &#039;Argument 1 pass...&#039;, &#039;/var/www/webmai...&#039;, 448, Array)
#1 /var/www/webmail/ActiveSync/Controller/Abstract.php(425): ActiveSync_Controller_Abstract-&gt;_getContentFilter(NULL, 0)
#2 /var/www/webmail/ActiveSync/Command/Sync.php(444): ActiveSync_Controller_Abstract-&gt;getServerEntries(&#039;10&#039;, 0)
#3 /var/www/webmail/ActiveSync/Frontend/Http.php(123): ActiveSync_Command_Sync-&gt;getResponse()
#4 /var/www/webmail/ActiveSync/Server/Http.php(97): ActiveSync_Frontend_Http-&gt;handlePost(&#039;adm-cbabsek&#039;, &#039;ThunderTine1303...&#039;, &#039;ThunderTine&#039;, &#039;Sync&#039;, &#039;2.5&#039;)
#5 /var/www/webmail/Tinebase/Core.php(2 in /var/www/webmail/ActiveSync/Controller/Abstract.php on line 448

**Steps to reproduce:** Just sync with the HTC Desire. It works perfect with the calendar, but shows an error with the contacts.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jun 2011 09:55**

which version of tine 2.0 are you using?

**Comment by Gloirin** [comment]
**Comment posted by chrisa50 on 28 Jun 2011 10:40**

The latest (from about Mai 2011), Maischa.
I often reinstalled it, but that all doesn&#039;t work.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jun 2011 20:37**

please try the following:

replace the line (must be around line number 420)

$filter = Tinebase_PersistentFilter::getFilterById($persistentFilterId);

in 

ActiveSync/Controller/Abstract.php

with 

$persistentFilter = Tinebase_PersistentFilter::getFilterById($persistentFilterId);
            if ($persistentFilter) {
                $filter = $persistentFilter;
                if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; filter class: &quot; . get_class($filter));
            }

**Comment by Gloirin** [comment]
**Comment posted by chrisa50 on 29 Jun 2011 15:39**

Hello.
This answer:

Fehler: Syntax-Fehler
Quelldatei: http://xyz.de/Microsoft-Server-ActiveSync?Cmd=FolderSync&amp;User=adm-chris&amp;DeviceId=ThunderTine1303418340721&amp;DeviceType=ThunderTine
Zeile: 2, Spalte: 1
Quelltext:
Fatal error: Class &#039;ActiveSync_Controller_Abstract&#039; not found in /var/www/mail/ActiveSync/Controller/Contacts.php on line 23

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Jul 2011 10:06**

hmm, now you might have broken your tine ... ;)

please check if the file /var/www/mail/ActiveSync/Controller/Abstract.php exists or if it has a syntax error.

**Comment by Gloirin** [comment]
**Comment posted by chrisa50 on 12 Jul 2011 16:04**

I don&#039;t see any error,

here&#039;s the full file:


 * @license     http://www.tine20.org/licenses/agpl-nonus.txt AGPL Version 1 (Non-US)
 *              NOTE: According to sec. 8 of the AFFERO GENERAL PUBLIC LICENSE (AGPL), 
 *              Version 1, the distribution of the Tine 2.0 ActiveSync module in or to the 
 *              United States of America is excluded from the scope of this license.
 * @copyright   Copyright (c) 2008-2009 Metaways Infosystems GmbH (http://www.metaways.de)
 * @author      Lars Kneschke &lt;l.kneschke@metaways.de&gt;
 */

/**
 * class documentation
 *
 * @package     ActiveSync
 * @subpackage  ActiveSync
 */
 
abstract class ActiveSync_Controller_Abstract implements ActiveSync_Controller_Interface
{
    /**
     * information about the current device
     *
     * @var ActiveSync_Model_Device
     */
    protected $_device;
    
    /**
     * timestamp to use for all sync requests
     *
     * @var Tinebase_DateTime
     */
    protected $_syncTimeStamp;
    
    /**
     * class to use for search entries
     *
     * @var Tinebase_Model_Filter_FilterGroup
     */
    protected $_contentFilterClass;
    
    /**
     * instance of the content specific controller
     *
     * @var Tinebase_Controller_Record_Abstract
     */
    protected $_contentController;
    
    /**
     * name of Tine 2.0 backend application
     * 
     * gets set by the instance of this abstract class
     *
     * @var string
     */
    protected $_applicationName;
    
    /**
     * name of Tine 2.0 model to use
     * 
     * strip of the applicationnamel and &quot;model&quot;
     * for example &quot;Addressbook_Model_Contacts&quot; becomes &quot;Contacts&quot;
     *
     * @var string
     */
    protected $_modelName;
    
    /**
     * type of the default folder
     *
     * @var int
     */
    protected $_defaultFolderType;
    
    /**
     * default container for new entries
     * 
     * @var string
     */
    protected $_defaultFolder;
    
    /**
     * type of user created folders
     *
     * @var int
     */
    protected $_folderType;
    
    /**
     * name of special folder
     * 
     * get used when the client does not support more that one folder
     *
     * @var string
     */
    protected $_specialFolderName;
    
    /**
     * name of property which defines the filterid for different content classes
     * 
     * @var string
     */
    protected $_filterProperty;
    
    /**
     * field to sort search results by
     * 
     * @var string
     */
    protected $_sortField;
    
    /**
     * name of the contentcontoller class
     * Defaults to $this-&gt;_applicationName . &#039;_Controller_&#039; . $this-&gt;_modelName
     * 
     * @var string
     */
    protected $_contentControllerName;
    
    /**
     * the constructor
     *
     * @param Tinebase_DateTime $_syncTimeStamp
     */
    public function __construct(ActiveSync_Model_Device $_device, DateTime $_syncTimeStamp)
    {
        if(empty($this-&gt;_applicationName)) {
            throw new Tinebase_Exception_UnexpectedValue(&#039;$this-&gt;_applicationName can not be empty&#039;);
        }
        
        if(empty($this-&gt;_modelName)) {
            throw new Tinebase_Exception_UnexpectedValue(&#039;$this-&gt;_modelName can not be empty&#039;);
        }
        
        if(empty($this-&gt;_defaultFolderType)) {
            throw new Tinebase_Exception_UnexpectedValue(&#039;$this-&gt;_defaultFolderType can not be empty&#039;);
        }
        
        if(empty($this-&gt;_folderType)) {
            throw new Tinebase_Exception_UnexpectedValue(&#039;$this-&gt;_folderType can not be empty&#039;);
        }
                
        if(empty($this-&gt;_specialFolderName)) {
            $this-&gt;_specialFolderName = strtolower($this-&gt;_applicationName) . &#039;-root&#039;;
        }
        
        $this-&gt;_device              = $_device;
        $this-&gt;_syncTimeStamp       = $_syncTimeStamp;
        
        $this-&gt;_contentFilterClass  = $this-&gt;_applicationName . &#039;_Model_&#039; . $this-&gt;_modelName . &#039;Filter&#039;;
        if (empty($this-&gt;_contentControllerName)) {
            $this-&gt;_contentControllerName = $this-&gt;_applicationName . &#039;_Controller_&#039; . $this-&gt;_modelName;
        }
        $this-&gt;_contentController   = call_user_func(array($this-&gt;_contentControllerName, &#039;getInstance&#039;)); 
    }
    
    /**
     * return list of supported folders for this backend
     *
     * @return array
     */
    abstract public function getSupportedFolders();
    
    /**
     * returns multiple records and resolves tags
     * 
     * @param  array $_ids array of record identifiers
     * @return Tinebase_Record_RecordSet
     */
    public function getMultipleAndResolveTags($_ids)
    {
        $records = $this-&gt;_contentController-&gt;getMultiple($_ids);
        
        if (count($records) &gt; 0 &amp;&amp; $records-&gt;getFirstRecord()-&gt;has(&#039;tags&#039;)) {
            Tinebase_Tags::getInstance()-&gt;getMultipleTagsOfRecords($records);
        }
        
        return $records;
    }
    
    /**
     * (non-PHPdoc)
     * @see ActiveSync/Controller/ActiveSync_Controller_Interface#moveItem()
     */
    public function moveItem($_srcFolder, $_srcItem, $_dstFolder)
    {
        $item = $this-&gt;_contentController-&gt;get($_srcItem);
        
        $item-&gt;container_id = $_dstFolder;
        
        $item = $this-&gt;_contentController-&gt;update($item);
        
        return $item-&gt;getId();
    }
    
    /**
     * get folder identified by $_folderId
     *
     * @param string $_folderId
     * @return string
     */
    public function getFolder($_folderId)
    {
        $folder = array();
        
        if($_folderId == $this-&gt;_specialFolderName) {
            $folder[$this-&gt;_specialFolderName] = array(
                &#039;folderId&#039;      =&gt; $this-&gt;_specialFolderName,
                &#039;parentId&#039;      =&gt; 0,
                &#039;displayName&#039;   =&gt; $this-&gt;_applicationName,
                &#039;type&#039;          =&gt; $this-&gt;_defaultFolderType
            );
            
        } else {
            try {
                $container = Tinebase_Container::getInstance()-&gt;getContainerById($_folderId);
            } catch (Tinebase_Exception_NotFound $e) {
                throw new ActiveSync_Exception_FolderNotFound(&#039;folder not found. &#039; . $_folderId);
            } catch (Tinebase_Exception_InvalidArgument $e) {
                throw new ActiveSync_Exception_FolderNotFound(&#039;folder not found. &#039; . $_folderId);
            }
            
            if(!Tinebase_Core::getUser()-&gt;hasGrant($_folderId, Tinebase_Model_Grants::GRANT_SYNC)) {
            	throw new ActiveSync_Exception_FolderNotFound(&#039;No sync right for folder: &#039; . $_folderId);
            }
            
            $folder[$container-&gt;id] = array(
                &#039;folderId&#039;      =&gt; $container-&gt;id,
                &#039;parentId&#039;      =&gt; 0,
                &#039;displayName&#039;   =&gt; $container-&gt;name,
                &#039;type&#039;          =&gt; $this-&gt;_folderType
            );
        }

        return $folder;
    }
    
    
    /**
     * add entry from xml data
     *
     * @param unknown_type $_collectionId
     * @param SimpleXMLElement $_data
     * @return Tinebase_Record_Abstract
     */
    public function add($_folderId, SimpleXMLElement $_data)
    {
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; add entry&quot;);
        
        $entry = $this-&gt;toTineModel($_data);
        $entry-&gt;creation_time = $this-&gt;_syncTimeStamp;
        $entry-&gt;created_by = Tinebase_Core::getUser()-&gt;getId();
        
        // container_id gets set to personal folder in application specific controller if missing
        if($_folderId != $this-&gt;_specialFolderName) {
            $entry-&gt;container_id = $_folderId;
        } else {
            $containerId = Tinebase_Core::getPreference(&#039;ActiveSync&#039;)-&gt;{$this-&gt;_defaultFolder};
            
            if (Tinebase_Core::getUser()-&gt;hasGrant($containerId, Tinebase_Model_Grants::GRANT_ADD) === true) {
                $entry-&gt;container_id = $containerId;
            }
        }
            
        $entry = $this-&gt;_contentController-&gt;create($entry);
        
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; added entry id &quot; . $entry-&gt;getId());

        return $entry;
    }
        
    /**
     * update existing entry
     *
     * @param unknown_type $_collectionId
     * @param string $_id
     * @param SimpleXMLElement $_data
     * @return Tinebase_Record_Abstract
     */
    public function change($_folderId, $_id, SimpleXMLElement $_data)
    {
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; CollectionId: $_folderId Id: $_id&quot;);
        
        $oldEntry = $this-&gt;_contentController-&gt;get($_id); 
        
        $entry = $this-&gt;toTineModel($_data, $oldEntry);
        $entry-&gt;last_modified_time = $this-&gt;_syncTimeStamp;
        
        $entry = $this-&gt;_contentController-&gt;update($entry);
        
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; updated entry id &quot; . $entry-&gt;getId());

        return $entry;
    }
        
    /**
     * delete entry
     *
     * @param  string  $_collectionId
     * @param  string  $_id
     * @param  array   $_options
     */
    public function delete($_folderId, $_id, $_options)
    {
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; ColectionId: $_folderId Id: $_id&quot;);
        
        $this-&gt;_contentController-&gt;delete($_id);
        
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; deleted entry id &quot; . $_id);
    }
    
    /**
     * search for existing entry in all syncable folders
     *
     * @param string            $_forlderId
     * @param SimpleXMLElement  $_data
     * @return Tinebase_Record_Abstract
     */
    public function search($_folderId, SimpleXMLElement $_data)
    {
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; CollectionId: $_folderId&quot;);
        
        $filterArray  = $this-&gt;_toTineFilterArray($_data);
        $filter       = new $this-&gt;_contentFilterClass($filterArray);
        
        $this-&gt;_getContainerFilter($filter, $_folderId);
        
        $foundEmtries = $this-&gt;_contentController-&gt;search($filter);

        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; found &quot; . count($foundEmtries));
            
        return $foundEmtries;
    }
    
    /**
     * used by the mail backend only. Used to update the folder cache
     * 
     * @param  string  $_folderId
     */
    public function updateCache($_folderId)
    {
        // does nothing by default
    }
    
    protected function _getContainerFilter(Tinebase_Model_Filter_FilterGroup $_filter, $_containerId)
    {
        $syncableContainers = $this-&gt;_getSyncableFolders();
        
        $containerIds = array();
        
        if($_containerId == $this-&gt;_specialFolderName) {
            $containerIds = array_keys($syncableContainers);
        } elseif(array_key_exists($_containerId, $syncableContainers)) {
            $containerIds = array($_containerId);        
        }

        $_filter-&gt;addFilter($_filter-&gt;createFilter(&#039;container_id&#039;, &#039;in&#039;, $containerIds));
    }
    
    /**
     * get all entries changed between to dates
     *
     * @param unknown_type $_field
     * @param unknown_type $_startTimeStamp
     * @param unknown_type $_endTimeStamp
     * @return array
     */
    public function getChanged($_folderId, $_startTimeStamp, $_endTimeStamp = NULL)
    {
        $filter = new $this-&gt;_contentFilterClass();
        
        try {
            $persistentFilterId = $this-&gt;_device-&gt;{$this-&gt;_filterProperty} ? 
                $this-&gt;_device-&gt;{$this-&gt;_filterProperty} : 
                Tinebase_Core::getPreference($this-&gt;_applicationName)-&gt;defaultpersistentfilter;
                
            $filter = Tinebase_PersistentFilter::getFilterById($persistentFilterId);
        } catch (Tinebase_Exception_NotFound $tenf) {
            // filter got deleted already
        }
        
        $this-&gt;_getContentFilter($filter, 0);
        $this-&gt;_getContainerFilter($filter, $_folderId);

        $startTimeStamp = ($_startTimeStamp instanceof DateTime) ? $_startTimeStamp-&gt;get(Tinebase_Record_Abstract::ISO8601LONG) : $_startTimeStamp;
        $endTimeStamp = ($_endTimeStamp instanceof DateTime) ? $_endTimeStamp-&gt;get(Tinebase_Record_Abstract::ISO8601LONG) : $_endTimeStamp;
        
        $filter-&gt;addFilter(new Tinebase_Model_Filter_DateTime(
            &#039;last_modified_time&#039;,
            &#039;after&#039;,
            $startTimeStamp
        ));
        
        if($endTimeStamp !== NULL) {
            $filter-&gt;addFilter(new Tinebase_Model_Filter_DateTime(
                &#039;last_modified_time&#039;,
                &#039;before&#039;,
                $endTimeStamp
            ));
        }
        
        $result = $this-&gt;_contentController-&gt;search($filter, NULL, false, true, &#039;sync&#039;);
        
        return $result;
    }    
    
    /**
     * get id&#039;s of all entries available on the server
     *
     * @param string $_folderId
     * @param int $_filterType
     * @return array
     */
    public function getServerEntries($_folderId, $_filterType)
    {
        $filter = new $this-&gt;_contentFilterClass();
        
        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; filter class: &quot; . get_class($filter));
                
        try {
            $persistentFilterId = $this-&gt;_device-&gt;{$this-&gt;_filterProperty} ? 
                $this-&gt;_device-&gt;{$this-&gt;_filterProperty} : 
                Tinebase_Core::getPreference($this-&gt;_applicationName)-&gt;defaultpersistentfilter;
                
            if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; defaultpersistentfilter: &quot; . Tinebase_Core::getPreference($this-&gt;_applicationName)-&gt;defaultpersistentfilter);
            if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; filter id: &quot; . $persistentFilterId);
            




            // $filter = Tinebase_PersistentFilter::getFilterById($persistentFilterId);
	$persistentFilter = Tinebase_PersistentFilter::getFilterById($persistentFilterId);
            if ($persistentFilter) {
                $filter = $persistentFilter;
                if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; filter class: &quot; . get_class($filter));
            }
            








            if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; filter class: &quot; . get_class($filter));
        } catch (Tinebase_Exception_NotFound $tenf) {
            // filter got deleted already
        }
        
        $this-&gt;_getContentFilter($filter, $_filterType);
        $this-&gt;_getContainerFilter($filter, $_folderId);
        
        if(!empty($this-&gt;_sortField)) {
            $pagination = new Tinebase_Model_Pagination(array(
                &#039;sort&#039; =&gt; $this-&gt;_sortField
            ));
        } else {
            $pagination = null;
        }
        
        //if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; assembled {$this-&gt;_contentFilterClass}: &quot; . print_r($filter-&gt;toArray(), TRUE));
        $result = $this-&gt;_contentController-&gt;search($filter, $pagination, false, true, &#039;sync&#039;);
        
        return $result;
    }

    /**
     * return contentfilter array
     * 
     * @param int $_filterType
     * @return array
     */
    protected function _getContentFilter(Tinebase_Model_Filter_FilterGroup $_filter, $_filterType)
    {
        return array();
    }
            
    abstract public function toTineModel(SimpleXMLElement $_data, $_entry = null);
    
    abstract protected function _toTineFilterArray(SimpleXMLElement $_data);
    
    /**
     * append entry data to xml element
     *
     * @param DOMElement  $_xmlNode   the parrent xml node
     * @param string      $_folderId  the local folder id
     * @param string      $_serverId  the local entry id
     * @param boolean     $_withBody  retrieve body of entry
     */
    abstract public function appendXML(DOMElement $_xmlNode, $_folderId, $_serverId, array $_options, $_neverTruncate = false);
    
    /**
     * removed control chars from string which are not allowd in ActiveSync
     * 
     * @param  string|array $_dirty
     * @return string
     */
    public function removeControlChars($_dirty)
    {
        return preg_replace(&#039;/[\x00-\x08\x0B\x0C\x0E-\x1F]/&#039;, null, $_dirty);
    }
}




I hope it helps you to find the error.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Jul 2011 19:35**

please upload the file and attach it to this issue. if you just copy&amp;paste it into a note, there might be some (html-)entities that are not shown.

**Comment by Gloirin** [comment]
**Comment posted by nfocking on 4 Aug 2011 16:13**

I also have trouble syncing my contacts (HTC Desire, Android 2.2). Interestingly this used to work with a Tine version around Sept. 2010. I think the reporter of this bug pasted the wrong lines of log because his log entry mentions ThunderTine as the client. I am getting this error, having set logging to priority 5.

[B82cb3 Focking, N** - 2011-08-04T15:58:24+00:00 WARN (4): ActiveSync_Command_Sync::handle::203 invalid synckey 0 provided

I see in the code of Sync.php that Synckey of 0 is handled as an error. This is not the correct behavior; Synckey of 0 is a discovery command asking the server for a list of available folders: 
http://blogs.msdn.com/b/openspecification/archive/2010/04/24/activesync-iii.aspx.

If this is not related to this bug, I will open a new one. Please feedback.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Aug 2011 16:27**

@nfocking: yes, please open a new bugreport. i&#039;m not sure about synckey 0 ... but when lars is back in the office, he will answer to this, i hope.

**Comment by Gloirin** [comment]
**Comment posted by nfocking on 4 Aug 2011 16:38**

Ok, my bad. The Blog I linked to refers to the command &quot;FolderSync&quot; and the error occurs on a &quot;Sync&quot; command. Please ignore my previous Note.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Aug 2011 08:19**

@chrisa50: are you still there? perhaps you should just install the upcoming service release and give it a try.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Sep 2011 11:48**

got no more feedback on this. closing it.

please reopen the task if the problem is still there.
