### ISSUE TITLE
0004656:
cli TineTrigger erzeugt erneut sporadisch Fehler

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2387]
**Reported by GWI on 26 Jul 2011 19:28**

**Version:** git master

der TineTrigger erzeug erneut einen sporadischen fehler, mit aktuellem git
abzug.

Fatal error: Uncaught exception &#039;Exception&#039; with message &#039;Controller Tinebase_TempFile does not implement Tinebase_Controller_Interface.&#039; in .../mail/Tinebase/Controller/Abstract.php:171
Stack trace:
#0 ..../mail/Tinebase/Scheduler/Task.php(195): Tinebase_Controller_Abstract::getController(&#039;Tinebase_TempFi...&#039;)
#1 ..../mail/Zend/Scheduler.php(280): Tinebase_Scheduler_Task-&gt;run()
#2 ..../mail/Tinebase/Frontend/Cli.php(113): Zend_Scheduler-&gt;run()
#3 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#4 ..../mail/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#5 ..../mail/Tinebase/Server/Cli.php(76): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#6 ..../mail/Tinebase/Core.php(239): Tinebase_Server_Cli-&gt;handle()
#7 ..../mail/tine20.php(86): Tinebase_Core::dispatchRequest()
#8 {main}
  thrown in ..../mail/Tinebase/Controller/Abstract.php on line 171

**Comment by Gloirin** [comment]
Related to #2375

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jul 2011 10:55**

auch da fehlte ein &quot;implements Tinebase_Controller_Interface&quot;.
