### ISSUE TITLE
0004670:
Wieder sporadisch Fehler vom cli TineTrigger

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2394]
**Reported by GWI on 31 Jul 2011 12:12**

**Version:** Maischa (2011-05-1)

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;DBtine.temp_files&#039; doesn&#039;t exist&#039; in ..../mail/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 .../mail/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../mail/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 ..../mail/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DELETE FROM `te...&#039;, Array)
#3 .../mail/library/Zend/Db/Adapter/Abstract.php(633): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DELETE FROM `te...&#039;)
#4 ..../mail/Tinebase/TempFile.php(186): Zend_Db_Adapter_Abstract-&gt;delete(&#039;temp_files&#039;, &#039;time &lt; &#039;2011-07...&#039;)
#5 [internal function]: Tinebase_TempFile-&gt;clearTable()
#6 ...../mail/Tinebase/Scheduler/Task.php(198): call_user_func_array(Array, Array)
#7 ..../mail/ in .../mail/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Aug 2011 08:48**

tatsache! da hat der table prefix gefehlt ... sollte nun funktionieren.
