### ISSUE TITLE
0004690:
emails are displayed as text instead of html

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2404]
**Reported by Olodin on 4 Aug 2011 11:10**

**Version:** Maischa (2011-05-1)

I am just testing ActiveSync with a new device (HP Veer, webOS 2.1.1) and found that HTML emails are displayed as text when synced via EAS and tine20.

The same email is shown correctly, when synced via IMAP. See screenshots.

In felamimail and even a Palm Pre (webOS 1.4.5) client via EAS the mail is shown correctly.

I hope that this is not a problem with the client and like to debug this. Some debug logs will follow.

**Comment by Gloirin** [comment]
Related to #2709

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 4 Aug 2011 11:27**

I digged around a bit and found out that since EAS v12.0 HTML emails should be supported (see *1).

Since tine20 reports itself as v.12.1 in ActiveSync/Server/Http.php line 157 this should be supported. 

Hmm, maybe there is sth. missing in the conversation.

I&#039;ve also attached this email in textform.

*1: http://social.technet.microsoft.com/wiki/contents/articles/exchange-activesync-overview.aspx

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 20 Sep 2011 21:08**

I hoped that this issues had something to do with issue #0004564. But in my testinstallation of 2011-05-3 I still have this problem.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 29 Sep 2011 20:18**

I&#039;ve uploaded a sync from setting up a new MS Exchange account on the device as &quot; tine20_email_initial_sync.log&quot;. It was only setup to sync email.

How can I change the Active Sync version tine20 announces itself as? Maybe that makes a difference?

**Comment by Gloirin** [comment]
**Comment posted by Nichtwirklich on 10 Jul 2012 16:01**

Can I (we) still hope for a fix?

**Comment by Gloirin** [comment]
**Comment posted by ey on 27 Jul 2012 20:46**

The client does a Sync with body type 1 (text) with truncation to get a snippet, and then does an ItemOperations with body type 2 (html) with no truncation. The logs show the server returning text/plain for both.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 Sep 2012 15:24**

The ItemOperations command was not working correctly. The fix is included in the next beta release of Joey.

Can please test when the next beta release of Joey is available and report success or failure?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 7 Sep 2012 19:08**

I&#039;ll test when the beta is available. Thx for the info.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 16 Sep 2012 18:51**

Just tested with Joey 2012.10.1~beta1:
the formating problem is gone! Mails are display just like when I connect via IMAP :)

But I noticed that I only get mails from inbox. When I change folders on my phone, no mails appear.

This is the debug log:
53a7f user - 2012-09-16T19:58:09+00:00 WARN (4): ActiveSync_Controller_Email::updateCache::820 catched exception Tinebase_Exception_NotFound
53a7f user - 2012-09-16T19:58:09+00:00 WARN (4): ActiveSync_Controller_Email::updateCache::822 Felamimail_Model_Folder record with id = 6f16ef42f433620d49c09758f73bc039ed19df8e not found!
53a7f user - 2012-09-16T19:58:09+00:00 DEBUG (7): ActiveSync_Controller_Email::updateCache::824 #0 /usr/local/www/tine20migrationstest/Tinebase/Backend/Sql/Abstract.php(202): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;6f16ef42f433620...&#039;, &#039;id&#039;, false)
#1 /usr/local/www/tine20migrationstest/Felamimail/Controller/Folder.php(163): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;6f16ef42f433620...&#039;)
#2 /usr/local/www/tine20migrationstest/Felamimail/Controller/Cache/Message.php(247): Felamimail_Controller_Folder-&gt;get(&#039;6f16ef42f433620...&#039;)
#3 /usr/local/www/tine20migrationstest/ActiveSync/Controller/Email.php(817): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;6f16ef42f433620...&#039;, 5)
#4 /usr/local/www/tine20migrationstest/ActiveSync/Controller/Abstract.php(503): ActiveSync_Controller_Email-&gt;updateCache(&#039;6f16ef42f433620...&#039;)
#5 /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Ping.php(109): ActiveSync_Controller_Abstract-&gt;getCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#6 /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Server.php(128): Syncroton_Command_Ping-&gt;handle()
#7 /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
#8 /usr/local/www/tine20migrationstest/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
#9 /usr/local/www/tine20migrationstest/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#10 /usr/local/www/tine20migrationstest/index.php(17): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 17 Sep 2012 18:50**

Addition to my last post: it just started working. Mails sync, I can get older mails.
I&#039;ve done an upgrade to an existing installation (a copy of my productive instance), anything to consider while upgrading?

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 18 Sep 2012 12:45**

It should work out of the box.

Got the problem solved by itself? In the log file above we can see that the Ping command had problems. Maybe there was a FolderSync command afterwards which snychronized the folders again and solved the problem.

As this is a copy of your productive instance, can you try to reproduce this problem?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 18 Sep 2012 19:33**

&gt; Got the problem solved by itself?
Yes. Looks like it was a client problem.

I&#039;ve tried to reproduce this problem but failed: with another installation this worked.
Only thing I changed was clearing old sessions, which worked again after I read about #7104.
