### ISSUE TITLE
0004696:
aktueller git vom 4.8.2011 nicht lauffähig

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2407]
**Reported by GWI on 4 Aug 2011 21:32**

**Version:** git master

NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_AccessDenied -&gt; Permission to add shared container denied.
NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Sales/Controller/Contract.php(107): Tinebase_Container-&gt;addContainer(Object(Tinebase_Model_Container))
#1 .../Sales/Frontend/Json.php(61): Sales_Controller_Contract::getSharedContractsContainer()
#2 .../Tinebase/Frontend/Json.php(557): Sales_Frontend_Json-&gt;getRegistryData()
#3 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(239): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(57): Tinebase_Core::dispatchRequest()
#11 {main}

**Steps to reproduce:** passiert bei jedem login mit dem fehler das der server die anfrage nicht
bearbeiten konnte!!!!

**Comment by Gloirin** [comment]
Related to #2355

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2011 09:57**

fixe das gleich.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2011 10:16**

bitte mal testen. sollte nach einem update wieder gehen.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 5 Aug 2011 13:50**

BINGO, funzt zuverlässig!!!!! :-))

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Aug 2011 10:01**

:)
