### ISSUE TITLE
0004774:
after update to 2011-05-2 from 2011-05-1 user-login impossible; setup-login still possible; failure in sales-plugin update;

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2445]
**Reported by silver on 26 Aug 2011 20:41**

**Version:** Maischa (2011-05-3)

9f4a0 -- none -- - 2011-08-24T18:22:35+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
9f4a0 -- none -- - 2011-08-24T18:22:35+00:00 CRIT (2): Tinebase_Core::setupStreamWrapper::602 filesdir config value not set. tine20:// streamwrapper not registered.
9f4a0 -- none -- - 2011-08-24T18:22:35+00:00 INFO (6): Tinebase_Core::setupCache::524 cache of backend type &#039;File&#039; enabled
9f4a0 -- none -- - 2011-08-24T18:22:35+00:00 INFO (6): Tinebase_Core::setSessionBackend::724 Session of backend type &#039;File&#039; configured.
9f4a0 XY, User - 2011-08-24T18:22:35+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
9f4a0 XY, User - 2011-08-24T18:22:35+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::836 given localeString &#039;auto&#039;
9f4a0 XY, User - 2011-08-24T18:22:35+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::841 session value: de
9f4a0 XY, User - 2011-08-24T18:22:35+00:00 INFO (6): Tinebase_Core::setupUserLocale::865 user locale: de
9f4a0 XY, User - 2011-08-24T18:22:35+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
[0] =&gt; Array
(
[jsonrpc] =&gt; 2.0
[method] =&gt; Tinebase.login
[params] =&gt; Array
(
[username] =&gt; userxy
[password] =&gt; *******
)

[id] =&gt; 7
)

)

9f4a0 XY, User - 2011-08-24T18:22:35+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Tinebase.login
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::957 setting execution life time to: 0
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Group::getInstance::57 groups backend: Sql
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Auth::setBackend::253 authentication backend: Sql
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Auth::authenticate::192 Trying to authenticate userxy
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Auth::authenticate::200 Authentication of userxy succeeded
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_User::getInstance::128 accounts backend: Sql
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Config::getConfig::121 Config setting &quot;sessionUserAgentValidation&quot; not found, using default (1).
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Config::getConfig::121 Config setting &quot;sessionIpValidation&quot; not found, using default (1).
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Auth_CredentialCache_Adapter_Cookie::setCache::36 Set credential cache cookie.
9f4a0 XY, User - 2011-08-24T18:22:36+00:00 INFO (6): index.php (75) TIME: 0.200946092606 seconds MEMORY: 9.75 MBytes REALPATHCACHESIZE: 8912
7926f -- none -- - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
7926f -- none -- - 2011-08-24T18:22:36+00:00 CRIT (2): Tinebase_Core::setupStreamWrapper::602 filesdir config value not set. tine20:// streamwrapper not registered.
7926f -- none -- - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setupCache::524 cache of backend type &#039;File&#039; enabled
7926f -- none -- - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setSessionBackend::724 Session of backend type &#039;File&#039; configured.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::836 given localeString &#039;auto&#039;
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::841 session value: de
7926f XY, User - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setupUserLocale::865 user locale: de
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
[0] =&gt; Array
(
[jsonrpc] =&gt; 2.0
[method] =&gt; Tinebase.getAllRegistryData
[params] =&gt; Array
(
)

[id] =&gt; 8
)

)

7926f XY, User - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Tinebase.getAllRegistryData
7926f XY, User - 2011-08-24T18:22:36+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::957 setting execution life time to: 0
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Group::getInstance::57 groups backend: Sql
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Addressbook
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Config::getConfig::121 Config setting &quot;mapPanel&quot; not found, using default (1).
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Config::getConfig::132 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_PersistentFilter.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::520 filtering field &#039;name&#039; of &#039;Tinebase_Model_PersistentFilter&#039; without indices, expecting slow results
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Calendar
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_PersistentFilter.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::520 filtering field &#039;name&#039; of &#039;Tinebase_Model_PersistentFilter&#039; without indices, expecting slow results
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Crm
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_PersistentFilter.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::520 filtering field &#039;name&#039; of &#039;Tinebase_Model_PersistentFilter&#039; without indices, expecting slow results
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Tasks
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_PersistentFilter.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::520 filtering field &#039;name&#039; of &#039;Tinebase_Model_PersistentFilter&#039; without indices, expecting slow results
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Felamimail
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Config::getConfig::121 Config setting &quot;sieve&quot; not found, using default (Array).
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_User::getInstance::128 accounts backend: Sql
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::826 Container ACL disabled for Tinebase_Model_ImportExportDefinition.
7926f XY, User - 2011-08-24T18:22:36+00:00 DEBUG (7): Tinebase_Frontend_Json::getAllRegistryData::553 Getting registry data for app Sales
7926f XY, User - 2011-08-24T18:22:36+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_AccessDenied -&gt; Permission to add shared container denied.
7926f XY, User - 2011-08-24T18:22:36+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Sales/Controller/Contract.php(107): Tinebase_Container-&gt;addContainer(Object(Tinebase_Model_Container))
#1 .../Sales/Frontend/Json.php(61): Sales_Controller_Contract::getSharedContractsContainer()
#2 .../Tinebase/Frontend/Json.php(557): Sales_Frontend_Json-&gt;getRegistryData()
#3 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(57): Tinebase_Core::dispatchRequest()
#11 {main}
7926f XY, User - 2011-08-24T18:22:36+00:00 INFO (6): index.php (75) TIME: 0.341705083847 seconds MEMORY: 13.5 MBytes REALPATHCACHESIZE: 16354

**Additional information:** after uninstallation of sales-plugin user-login again possible

**Comment by Gloirin** [comment]
**Comment posted by silver on 26 Aug 2011 20:47**

failure-message when trying to log in:
Der Server kann Ihre Anfrage momentan nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator..
