### ISSUE TITLE
0004882:
Deadlock while working with Felamimail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2498]
**Reported by mr_claus on 27 Sep 2011 07:53**

**Version:** Maischa (2011-05-3)

While working with filters and moving mails Tine will not respond anymore.

**Additional information:** [Mon Sep 26 13:49:36 2011] [error] [client x.x.x.x] PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction&#039; in /opt/tine/tine20-2011-05-3/library/Zend/Db/Statement/Pdo.php:238\nStack trace:\n#0 /opt/tine/tine20-2011-05-3/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)\n#1 /opt/tine/tine20-2011-05-3/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)\n#2 /opt/tine/tine20-2011-05-3/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;, Array)\n#3 /opt/tine/tine20-2011-05-3/library/Zend/Db/Adapter/Abstract.php(633): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DELETE FROM `ti...&#039;)\n#4 /opt/tine/tine20-2011-05-3/ActiveSync/Backend/ContentState.php(52): Zend_Db_Adapter_Abstract-&gt;delete(&#039;tine20_acsync_c...&#039;, Array)\n#5 /opt/tine/tine20-2011-05-3/ActiveSync/Command/Sync.php(361): ActiveSync_Backend_ContentState-&gt;resetState(Object(ActiveSync_Model_Device), &#039;Contacts&#039;,  in /opt/tine/tine20-2011-05-3/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
Related to #2601

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Sep 2011 10:29**

are you sure you attached the matching section of the logfile?
it is an error of ActiveSync. looks like the server tries to reset the client state and this does not work.
do you get a javascript error in Felamimail?
are there other errors in the logfile / webserver log?

**Comment by Gloirin** [comment]
**Comment posted by mr_claus on 27 Sep 2011 10:54**

I didn&#039;t get other errors in the log file. After working with Felamimail it was not possible to refresh the screens, any time i got the message that it is not possible to connect, after restarting the browser it worked again. I will try to get more informations.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2011 09:29**

i think this is related to the massive amount of updateMessageCache requests and should no longer be an issue when #5088 is resolved.
