### ISSUE TITLE
0005134:
Benutzer zu einer Gruppe zuweisen schlägt fehl

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2624]
**Reported by splinter03 on 24 Nov 2011 20:00**

**Version:** Maischa (2011-05-4)

1. Neue Gruppe erstellen
2. Der Gruppe einer Rolle zuweisen
3. Die Gruppe editieren und einen Benutzer hinzufügen --&gt; geht nicht da mir keine User außer mein eigener angezeigt wird
ODER
3. Ein Benutzer öffnen, und hier versuchen die Gruppe hinzuzufügen --&gt; Fehler im Frontend: &quot;Sie sind nicht berechtigt diese Aktion auszuführen&quot; (Ich bin mit Admin-User angemeldet und habe ALLE Rechte), Fehler im Log --&gt; siehe unten :)

**Additional information:** faf9d -- none -- - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
faf9d -- none -- - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Core::setupCache::524 cache of backend type &#039;File&#039; enabled
faf9d -- none -- - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Core::setSessionBackend::724 Session of backend type &#039;File&#039; configured.
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::836 given localeString &#039;auto&#039;
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::841 session value: de
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Core::setupUserLocale::865 user locale: de
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Felamimail.updateMessageCache
            [params] =&gt; Array
                (
                    [folderId] =&gt; 3d89d7a20a0630a7e6eaa1d343fc636db9746b95
                    [time] =&gt; 120
                )

            [id] =&gt; 31
        )

)

faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Felamimail.updateMessageCache
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::957 setting execution life time to: 0
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Tinebase_Group::getInstance::57 groups backend: Sql
faf9d ********, Philipp - 2011-11-24T19:41:27+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::42 Connecting to server imap.********.de:993 (SSL) with username ********@********.de
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::497 Getting capabilities of account c ********
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::510 Updating capabilities for account: c ********
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_initUpdate::203 status of folder Trash: complete
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_getLatestMessageUid::332 got last message uid: Array
(
    [c2ddac6f3f3e23ab7b670a3a5ff2ae74c54e19f6] =&gt; 10
)

faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_updateMessageSequence::255 c2ddac6f3f3e23ab7b670a3a5ff2ae74c54e19f6  10
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_updateMessageSequence::261 Check messageUid 10 in folder Trash
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_updateMessageSequence::300 Cache status cache total count: 9 imap total count: 9 cache sequence: 9 imap sequence: 9
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_deleteMessagesInCache::417 Cache status cache total count: 9 imap total count: 9 cache sequence: 9 imap sequence: 9
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_deleteMessagesInCache::419 Folder cache status: updating
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_deleteMessagesInCache::420 Folder cache actions to be done yet: 0
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_addMessagesToCache::507 cache sequence: 9 / imap count: 9
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_addMessagesToCache::559 Cache status cache total count: 9 imap total count: 9 cache sequence: 9 imap sequence: 9
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_checkForMissingMessages::656 Cache status cache total count: 9 imap total count: 9 cache sequence: 9 imap sequence: 9
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 DEBUG (7): Felamimail_Controller_Cache_Message::_checkForMissingMessages::658 Folder cache status: updating
faf9d ********, Philipp - 2011-11-24T19:41:28+00:00 INFO (6): index.php (75) TIME: 0.376824855804 seconds  MEMORY: 3.25 MBytes  REALPATHCACHESIZE: unknown
c7dc6 -- none -- - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
c7dc6 -- none -- - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Core::setupCache::524 cache of backend type &#039;File&#039; enabled
c7dc6 -- none -- - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Core::setSessionBackend::724 Session of backend type &#039;File&#039; configured.
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::836 given localeString &#039;auto&#039;
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::841 session value: de
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Core::setupUserLocale::865 user locale: de
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Admin.searchGroups
            [params] =&gt; Array
                (
                    [filter] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [field] =&gt; query
                                    [operator] =&gt; contains
                                    [value] =&gt; 
                                )

                        )

                    [paging] =&gt; Array
                        (
                            [start] =&gt; 0
                            [limit] =&gt; 10
                        )

                )

            [id] =&gt; 33
        )

)

c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Admin.searchGroups
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::957 setting execution life time to: 0
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 DEBUG (7): Tinebase_Group::getInstance::57 groups backend: Sql
c7dc6 ********, Michael - 2011-11-24T19:41:32+00:00 INFO (6): index.php (75) TIME: 0.12819314003 seconds  MEMORY: 2.75 MBytes  REALPATHCACHESIZE: unknown
0d13d -- none -- - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
0d13d -- none -- - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Core::setupCache::524 cache of backend type &#039;File&#039; enabled
0d13d -- none -- - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Core::setSessionBackend::724 Session of backend type &#039;File&#039; configured.
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::836 given localeString &#039;auto&#039;
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::841 session value: de
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Core::setupUserLocale::865 user locale: de
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Admin.saveUser
            [params] =&gt; Array
                (
                    [recordData] =&gt; Array
                        (
                            [accountId] =&gt; 03ebbc97a7641fb42f20b0d40e23356493472030
                            [accountFirstName] =&gt; Philipp
                            [accountLastName] =&gt; ********
                            [accountLoginName] =&gt; p.********
                            [accountPassword] =&gt; 
                            [accountDisplayName] =&gt; ********, Philipp
                            [accountFullName] =&gt; Philipp ********
                            [accountStatus] =&gt; enabled
                            [groups] =&gt; Array
                                (
                                    [0] =&gt; dbe5dd9967ed1de2e047a3da3524b92be1282996
                                    [1] =&gt; 1554f7c6c2a5329760803ceddd52bbf0be9c707c
                                )

                            [accountRoles] =&gt; Array
                                (
                                    [0] =&gt; 2
                                )

                            [accountPrimaryGroup] =&gt; dbe5dd9967ed1de2e047a3da3524b92be1282996
                            [accountExpires] =&gt; 
                            [accountLastLogin] =&gt; 
                            [accountLastPasswordChange] =&gt; 
                            [accountLastLoginfrom] =&gt; *************
                            [accountEmailAddress] =&gt; p.********@********.de
                            [accountHomeDirectory] =&gt; 
                            [accountLoginShell] =&gt; 
                            [openid] =&gt; 
                            [visibility] =&gt; hidden
                            [sambaSAM] =&gt; Array
                                (
                                    [sid] =&gt; 
                                    [primaryGroupSID] =&gt; 
                                    [acctFlags] =&gt; 
                                    [homeDrive] =&gt; 
                                    [homePath] =&gt; 
                                    [profilePath] =&gt; 
                                    [logonScript] =&gt; 
                                    [logonTime] =&gt; 
                                    [logoffTime] =&gt; 
                                    [kickoffTime] =&gt; 
                                    [pwdLastSet] =&gt; 
                                    [pwdCanChange] =&gt; 
                                    [pwdMustChange] =&gt; 
                                )

                            [emailUser] =&gt; Array
                                (
                                    [emailUID] =&gt; 
                                    [emailGID] =&gt; 
                                    [emailMailQuota] =&gt; 
                                    [emailMailSize] =&gt; 
                                    [emailSieveQuota] =&gt; 
                                    [emailSieveSize] =&gt; 
                                    [emailLastLogin] =&gt; 
                                    [emailUserId] =&gt; 
                                    [emailAliases] =&gt; 
                                    [emailForwards] =&gt; 
                                    [emailForwardOnly] =&gt; 
                                    [emailAddress] =&gt; 
                                    [emailUsername] =&gt; 
                                )

                            [contact_id] =&gt; 3
                            [container_id] =&gt; 1
                        )

                )

            [id] =&gt; 34
        )

)

0d13d ********, Michael - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Admin.saveUser
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::957 setting execution life time to: 0
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Group::getInstance::57 groups backend: Sql
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_User::getInstance::128 accounts backend: Sql
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_CustomField::saveRecordCustomFields::263 Updating custom fields for record of class Addressbook_Model_Contact
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Core::errorHandler::356 Only variables should be passed by reference in /var/www/tine20/library/Zend/Db/Select.php::246 (2048)
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0 ().
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /var/www/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /var/www/tine20/Tinebase/Model/User.php(311): Tinebase_Container-&gt;hasGrant(&#039;9425a02f1af08fa...&#039;, NULL, &#039;adminGrant&#039;)
#2 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(772): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;adminGrant&#039;)
#3 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(273): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;get&#039;)
#4 /var/www/tine20/Addressbook/Controller/List.php(90): Tinebase_Controller_Record_Abstract-&gt;get(&#039;d93d1db54cefc9d...&#039;)
#5 /var/www/tine20/Admin/Controller/Group.php(265): Addressbook_Controller_List-&gt;addListMember(&#039;d93d1db54cefc9d...&#039;, &#039;3&#039;)
#6 /var/www/tine20/Admin/Controller/Group.php(135): Admin_Controller_Group-&gt;addGroupMember(&#039;1554f7c6c2a5329...&#039;, &#039;03ebbc97a7641fb...&#039;)
#7 /var/www/tine20/Admin/Controller/User.php(215): Admin_Controller_Group-&gt;setGroupMemberships(Object(Tinebase_Model_FullUser), Array)
#8 /var/www/tine20/Admin/Frontend/Json.php(378): Admin_Controller_User-&gt;update(Object(Tinebase_Model_FullUser), &#039;&#039;, &#039;&#039;)
#9 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#10 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /var/www/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#14 /var/www/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#15 /var/www/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#16 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#17 {main}
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Container::hasGrant::785 Container id can not be 0 ().
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 DEBUG (7): Tinebase_Container::hasGrant::786 #0 /var/www/tine20/Tinebase/Container.php(783): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /var/www/tine20/Tinebase/Model/User.php(311): Tinebase_Container-&gt;hasGrant(&#039;9425a02f1af08fa...&#039;, NULL, &#039;readGrant&#039;)
#2 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(780): Tinebase_Model_User-&gt;hasGrant(NULL, &#039;readGrant&#039;)
#3 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(273): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;get&#039;)
#4 /var/www/tine20/Addressbook/Controller/List.php(90): Tinebase_Controller_Record_Abstract-&gt;get(&#039;d93d1db54cefc9d...&#039;)
#5 /var/www/tine20/Admin/Controller/Group.php(265): Addressbook_Controller_List-&gt;addListMember(&#039;d93d1db54cefc9d...&#039;, &#039;3&#039;)
#6 /var/www/tine20/Admin/Controller/Group.php(135): Admin_Controller_Group-&gt;addGroupMember(&#039;1554f7c6c2a5329...&#039;, &#039;03ebbc97a7641fb...&#039;)
#7 /var/www/tine20/Admin/Controller/User.php(215): Admin_Controller_Group-&gt;setGroupMemberships(Object(Tinebase_Model_FullUser), Array)
#8 /var/www/tine20/Admin/Frontend/Json.php(378): Admin_Controller_User-&gt;update(Object(Tinebase_Model_FullUser), &#039;&#039;, &#039;&#039;)
#9 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#10 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /var/www/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#14 /var/www/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#15 /var/www/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#16 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#17 {main}
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_AccessDenied -&gt; No Permission.
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Controller/Record/Abstract.php(273): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;get&#039;)
#1 .../Addressbook/Controller/List.php(90): Tinebase_Controller_Record_Abstract-&gt;get(&#039;d93d1db54cefc9d...&#039;)
#2 .../Admin/Controller/Group.php(265): Addressbook_Controller_List-&gt;addListMember(&#039;d93d1db54cefc9d...&#039;, &#039;3&#039;)
#3 .../Admin/Controller/Group.php(135): Admin_Controller_Group-&gt;addGroupMember(&#039;1554f7c6c2a5329...&#039;, &#039;03ebbc97a7641fb...&#039;)
#4 .../Admin/Controller/User.php(215): Admin_Controller_Group-&gt;setGroupMemberships(Object(Tinebase_Model_FullUser), Array)
#5 .../Admin/Frontend/Json.php(378): Admin_Controller_User-&gt;update(Object(Tinebase_Model_FullUser), &#039;&#039;, &#039;&#039;)
#6 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#7 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#8 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#9 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#10 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#11 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#12 .../Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#13 .../index.php(57): Tinebase_Core::dispatchRequest()
#14 {main}
0d13d ********, Michael - 2011-11-24T19:41:36+00:00 INFO (6): index.php (75) TIME: 0.414530038834 seconds  MEMORY: 4 MBytes  REALPATHCACHESIZE: unknown

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 26 Nov 2011 11:46**

Folgendes habe ich herausgefunden: Das mir die Benutzer beim Zuordnen von Benutzern zu einer Gruppe nicht angezeigt werden, liegt daran, dass ich die Sichtbarbeit (der Benutzer) auf &quot;Nicht im Adressbuch anzeigen&quot; gesetzt habe. Hier scheint es irgendeinen Bug zu geben...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Nov 2011 15:59**

problem ist wohl, dass wir vor einiger zeit mal den bug hatten, dass listen keine container id hatten. das ist mittlerweile behoben.

ich habe aber trotzdem noch einen workaround eingebaut, der nachträglich die container id setzt.

bitte im kommenden service release (2011-05-5) testen und den bug wieder aufmachen, falls es dann immer noch nicht tut ....

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 30 Nov 2011 21:48**

Mir werden immer noch keine User angezeigt, wenn ich welche zu einer Gruppe hinzufügen möchte. Ich habe einige Nutzer, die nicht im Adressbuch angezeigt werden. Deshalb stelle ich den Filter im &quot;Gruppen-Editor&quot; entsprechend ein, mir wird jedoch kein Nutzer angezeigt.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Dec 2011 11:17**

das hinzufügen über den user-dialog sollte nun aber klappen. hast du das auch getestet?

für die usersuche für versteckte user lege ich einen neuen bugreport an.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Dec 2011 21:29**

im nächsten release können auch versteckte user über die account suche zu gruppen/rollen/... hinzugefügt werden (siehe #5164).
