### ISSUE TITLE
0005246:
Überschreiben Blockiert das ganze System

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2678]
**Reported by GWI on 23 Dec 2011 16:40**

**Version:** git master

Beim Überschreiben von Dateien bleibt das ganze System Hängen, 
und wirft folgenden Error ins Log:

3abb3 Röllig, Sven - 2011-12-23T16:25:19+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Filemanager_Exception_NodeExists -&gt; file exists
3abb3 Röllig, Sven - 2011-12-23T16:25:19+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Filemanager/Controller/Node.php(309): Filemanager_Controller_Node-&gt;_handleNodeExistsException(Object(Filemanager_Exception_NodeExists), NULL)
#1 .../Filemanager/Frontend/Json.php(104): Filemanager_Controller_Node-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#2 [internal function]: Filemanager_Frontend_Json-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#3 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#8 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#9 .../index.php(57): Tinebase_Core::dispatchRequest()
#10 {main}

Danach wars das, das System bleibt endlos hängen. Nur ein kompletter 
Reload der Seite hilft. Beim Hochladen von mehreren Dateien, wobei nur 
eine schon vorhanden ist, lässt alle anderen Dateien als 0 Byte erscheinen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Dec 2011 19:14**

es sollte eigentlich im client ein confirm-dialog kommen (&quot;wollen sie wirklich überschreiben&quot;). ist denn da ein fehler in der js console?

**Comment by Gloirin** [comment]
**Comment posted by GWI on 23 Dec 2011 19:22**

ja das wird auch gemacht, der dialog erscheint, aber das wars dann auch

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Jan 2012 12:46**

konnte ich nicht reproduzieren.

beim klick auf &#039;ja&#039; in dem confirm-dialog lädt er die dateien hoch. beim klick auf nein verschwindet der dialog auch und es passiert nichts. wie erwartet.

und bei dir passiert nichts, wenn man auf &#039;ja&#039; klickt?
die exception im log ist ja gewollt.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 2 Jan 2012 23:05**

ach so jetzt versehe ich das erst!!! :-|

ich dachte beim dialog &quot;nicht überschrieben&quot; wird der Rest trotzdem hochgeladen,
das passiert aber nicht!!!

ist das nicht ein bisschen blöd? 
wäre es nicht besser wenn man trotzdem den rest hochläd
und nur die vorhandenen dateien ignoriert?

EDIT:
hab aber trotzdem gerade noch festgestellt das wenn man den dialog
&quot;nicht überschreiben&quot; folgt legt er trotzdem die dateien dann, aber mit
0 Byte

**Comment by Gloirin** [comment]
**Comment posted by GWI on 2 Jan 2012 23:50**

hab mal nen paar pic gemacht.

wie man sieht in 

pic 1 der anfang
pic 2 Filemanager öffnet sich Bild &quot;4Cisco11.jpg und adressbook.png&quot; ausgewählt.
      bild &quot;4Cisco11.jpg&quot; soll NICHT überschieben werden!!!

pic 3 der Dialog so wie er ist!!  =&gt; Klick auf &quot;Nein&quot; 
      Bild soll ja NICHT überschrieben werden!!!

pic 4 Ersetzen Dialog verschwindet, &quot;progressloader&quot; dreht sich nen Wolf

pic 5 adressbook.png erscheint obwohl nicht hochgeladen, wie man sieht 
      auch 0 Bytes

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2012 08:34**

ah, jetzt wird das klarer :)

danke für die ausführliche beschreibung. ich gucks mir an!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2012 10:16**

so, nun passiert auch wirklich was, wenn man auf &#039;nein&#039; klickt ...

bitte probiere es mal mit dem aktuellen git, obs nun so funktioniert, wie man denkt.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 3 Jan 2012 15:37**

AHHH, sehr schön!!!!

Geht wunderbar, ich sollte mir angewöhnen öffter Bilder zu machen

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2012 20:14**

stimmt, die bildchen sonst oft hilfreicher als text ...

schliesse das ticket.
