### ISSUE TITLE
0005352:
allow to show users even if their adb container is deleted

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2731]
**Reported by pschuele on 13 Jan 2012 12:40**

**Version:** Maischa (2011-05-6)

allow to show users even if (their / internal contacts) adb container is deleted

and allow to create new users.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Jan 2012 22:39**

- fixed user display
- TODO: allow to save user

Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Backend/Sql/Abstract.php(195): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(158, &#039;id&#039;, false)
#1 .../Tinebase/Container.php(359): Tinebase_Backend_Sql_Abstract-&gt;get(158, false)
#2 .../Admin/Frontend/Json.php(410): Tinebase_Container-&gt;getContainerById(&#039;158&#039;)
#3 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(57): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jan 2012 11:44**

needs to be backported to Maischa.
