### ISSUE TITLE
0005378:
Can't upgrade from 2011-05-5 to 2011-05-6

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2744]
**Reported by weberho on 16 Jan 2012 16:27**

**Version:** Maischa (2011-05-6)

The following failure pop&#039;s up during setup: &quot;Setup Admin undefined&quot;.

**Additional information:** 5dd5c -- none -- - 2012-01-16T16:22:37+00:00 ERR (3): Setup_Controller::updateApplication::373 SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;web_tine20.tine20_async_job&#039; doesn&#039;t exist
5dd5c -- none -- - 2012-01-16T16:22:37+00:00 ERR (3): Setup_Controller::updateApplication::374 #0 /var/lib/tine20/webroot/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/lib/tine20/webroot/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/lib/tine20/webroot/Setup/Backend/Mysql.php(206): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 /var/lib/tine20/webroot/Tinebase/Setup/Update/Release4.php(348): Setup_Backend_Mysql-&gt;alterCol(&#039;async_job&#039;, Object(Setup_Backend_Schema_Field_Xml))
#6 /var/lib/tine20/webroot/Setup/Controller.php(367): Tinebase_Setup_Update_Release4-&gt;update_9()
#7 /var/lib/tine20/webroot/Setup/Controller.php(258): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#8 /var/lib/tine20/webroot/Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 /var/lib/tine20/webroot/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /var/lib/tine20/webroot/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /var/lib/tine20/webroot/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /var/lib/tine20/webroot/Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 /var/lib/tine20/webroot/Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#15 /var/lib/tine20/webroot/setup.php(53): Setup_Core::dispatchRequest()
#16 {main}
5dd5c -- none -- - 2012-01-16T16:22:37+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;web_tine20.tine20_async_job&#039; doesn&#039;t exist
5dd5c -- none -- - 2012-01-16T16:22:37+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 .../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 .../Setup/Backend/Mysql.php(206): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 .../Tinebase/Setup/Update/Release4.php(348): Setup_Backend_Mysql-&gt;alterCol(&#039;async_job&#039;, Object(Setup_Backend_Schema_Field_Xml))
#6 .../Setup/Controller.php(367): Tinebase_Setup_Update_Release4-&gt;update_9()
#7 .../Setup/Controller.php(258): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#8 .../Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 .../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 .../Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#15 .../setup.php(53): Setup_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Jan 2012 20:51**

please try the update again with this file (replaces Tinebase/Setup/Update/Release4.php):

http://git.tine20.org/git?p=tine20;a=blob_plain;f=tine20/Tinebase/Setup/Update/Release4.php;hb=446b6886579be28cfecd937418cb7790664f17a4

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Jan 2012 10:26**

The failure has changed. Nos I see the following message:

42a76 -- none -- - 2012-01-18T10:24:37+00:00 INFO (6): Tinebase_Core::setupLogger::460 logger initialized
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Tinebase_Core::setupCache::528 cache disabled
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Tinebase_Core::setSessionBackend::729 Session of backend type &#039;File&#039; configured.
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Tinebase_Core::setupUserLocale::875 user locale: de
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Setup_Server_Json::handle::41 is JSON request. method: Setup.updateApplications
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::968 setting execution life time to: 0
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Setup_Controller::updateApplications::255 Updating Tinebase to version 4.10
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Setup_Controller::updateApplication::339 Executing updates for Tinebase (starting at 4.9)
42a76 -- none -- - 2012-01-18T10:24:38+00:00 INFO (6): Setup_Controller::updateApplication::363 Updating Tinebase - update_9
42a76 -- none -- - 2012-01-18T10:24:38+00:00 ERR (3): Setup_Controller::updateApplication::373 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;bf0e1fff6e2bea6bebfd2ac1afa9b0acb1b6d8f4-async_job&#039; for key &#039;PRIMARY&#039;
42a76 -- none -- - 2012-01-18T10:24:38+00:00 ERR (3): Setup_Controller::updateApplication::374 #0 /var/lib/tine20/webroot/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/lib/tine20/webroot/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/lib/tine20/webroot/Tinebase/Application.php(465): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_applicat...&#039;, Array)
#5 /var/lib/tine20/webroot/Setup/Update/Abstract.php(181): Tinebase_Application-&gt;addApplicationTable(Object(Tinebase_Model_Application), &#039;async_job&#039;, 1)
#6 /var/lib/tine20/webroot/Tinebase/Setup/Update/Release4.php(426): Setup_Update_Abstract-&gt;createTable(&#039;async_job&#039;, Object(Setup_Backend_Schema_Table_Xml))
#7 /var/lib/tine20/webroot/Setup/Controller.php(367): Tinebase_Setup_Update_Release4-&gt;update_9()
#8 /var/lib/tine20/webroot/Setup/Controller.php(258): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#9 /var/lib/tine20/webroot/Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#10 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#11 /var/lib/tine20/webroot/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /var/lib/tine20/webroot/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /var/lib/tine20/webroot/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /var/lib/tine20/webroot/Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#15 /var/lib/tine20/webroot/Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#16 /var/lib/tine20/webroot/setup.php(53): Setup_Core::dispatchRequest()
#17 {main}
42a76 -- none -- - 2012-01-18T10:24:38+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Zend_Db_Statement_Exception -&gt; SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;bf0e1fff6e2bea6bebfd2ac1afa9b0acb1b6d8f4-async_job&#039; for key &#039;PRIMARY&#039;
42a76 -- none -- - 2012-01-18T10:24:38+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Tinebase/Application.php(465): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_applicat...&#039;, Array)
#5 .../Setup/Update/Abstract.php(181): Tinebase_Application-&gt;addApplicationTable(Object(Tinebase_Model_Application), &#039;async_job&#039;, 1)
#6 .../Tinebase/Setup/Update/Release4.php(426): Setup_Update_Abstract-&gt;createTable(&#039;async_job&#039;, Object(Setup_Backend_Schema_Table_Xml))
#7 .../Setup/Controller.php(367): Tinebase_Setup_Update_Release4-&gt;update_9()
#8 .../Setup/Controller.php(258): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;4&#039;)
#9 .../Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#10 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#11 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 .../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#15 .../Setup/Core.php(103): Setup_Server_Json-&gt;handle()
#16 .../setup.php(53): Setup_Core::dispatchRequest()
#17 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Jan 2012 11:14**

i see.

i fixed it in Setup/Update/Abstract.php:

https://gerrit.tine20.org/gitweb?p=tine20.git;a=blob_plain;f=tine20/Setup/Update/Abstract.php;hb=c77344f97445079031780efc0567ad34a0cbf90d

please use this file.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Jan 2012 11:36**

Thank you! It&#039;s working perfectly now.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Jan 2012 15:26**

that&#039;s great :)

resolving this.
