### ISSUE TITLE
0005426:
give meaningful error message on unsupported client write attempt

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2768]
**Reported by GWI on 24 Jan 2012 00:45**

**Version:** git master

war: Keine Schreiben von Terminen über Webdav

Wenn ich Versuche einen Termin von Horde/Kronolith nach Tine
per Webdav zu schreiben geht das immer schief.

Im Tine Log findet sich dazu folgendes:
CRIT (2): Sabre_DAV_Server::exec::205 webdav exception The METHOD property is not allowed in calendar objects
CRIT (2): Sabre_DAV_Server::exec::207 webdav exception stacktrace 
#0 ****/mail/Calendar/Frontend/WebDAV/Event.php(76): Sabre_CalDAV_ICalendarUtil::validateICalendarObject(&#039;BEGIN:VCALENDAR...&#039;, Array)
#1 ****/mail/Tinebase/WebDav/Container/Abstract.php(66): Calendar_Frontend_WebDAV_Event::create(Object(Tinebase_Model_Container), &#039;4f1dfbeb-083c-4...&#039;, Resource id #395)
#2 ****/mail/library/Sabre/DAV/Server.php(1430): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;4f1dfbeb-083c-4...&#039;, Resource id #395)
#3 ****/mail/library/Sabre/DAV/Server.php(833): Sabre_DAV_Server-&gt;createFile(&#039;calendars/99e7d...&#039;, Resource id #395)
#4 [internal function]: Sabre_DAV_Server-&gt;httpPut(&#039;calendars/99e7d...&#039;)
#5 ****/mail/library/Sabre/DAV/Server.php(454): call_user_func(Array, &#039;calendars/99e7d...&#039;)
#6 ****/mail/library/Sabre/DAV/Server.php(201): Sabre_DAV_Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;calendars/99e7d...&#039;)
#7 ****/mail/Tinebase/Server/WebDAV.php(85): Sabre_DAV_Server-&gt;exec()
#8 ****/mail/Tinebase/Core.php(235): Tinebase_Server_WebDAV-&gt;handle()
#9 ****/mail/index.php(57): Tinebase_Core::dispatchRequest()
#10 {main}

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 2 Feb 2012 11:54**

writing is only allowed with &quot;supported&quot; clients. 
We need a better failure message there!

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 Feb 2012 13:45**

Das Problem ist jetzt gelöst.
