### ISSUE TITLE
0005534:
Programm Abbruch wegen SQLState

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2822]
**Reported by GWI on 4 Feb 2012 12:09**

**Version:** git master

Fast jede Aktion erzeugt den Fehler:

NOTICE (5): Tinebase_Server_Json::_handleException::161 Zend_Db_Statement_Exception -&gt; SQLSTATE[21000]: Cardinality violation: 1241 Operand sollte 1 Spalte(n) enthalten
NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(590): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(424): Tinebase_Backend_Sql_Abstract-&gt;_fetch(Object(Zend_Db_Select))
#5 .../Tinebase/Controller/Record/Abstract.php(149): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), NULL, true)
#6 .../Tinebase/Model/Filter/Relation.php(107): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), NULL, false, true)
#7 .../Tinebase/Model/Filter/Relation.php(90): Tinebase_Model_Filter_Relation-&gt;_resolveForeignIds()
#8 .../Tinebase/Backend/Sql/Filter/FilterGroup.php(45): Tinebase_Model_Filter_Relation-&gt;appendFilterSql(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Projects_Backend_Project))
#9 .../Tinebase/Backend/Sql/Filter/FilterGroup.php(47): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Projects_Model_ProjectFilter), Object(Projects_Backend_Project))
#10 .../Tinebase/Backend/Sql/Filter/FilterGroup.php(47): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Projects_Model_ProjectFilter), Object(Projects_Backend_Project))
#11 .../Tinebase/Backend/Sql/Abstract.php(454): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Zend_Db_Select), Object(Projects_Model_ProjectFilter), Object(Projects_Backend_Project))
#12 .../Tinebase/Backend/Sql/Abstract.php(416): Tinebase_Backend_Sql_Abstract-&gt;_addFilter(Object(Zend_Db_Select), Object(Projects_Model_ProjectFilter))
#13 .../Tinebase/Controller/Record/Abstract.php(149): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Projects_Model_ProjectFilter), Object(Tinebase_Model_Pagination), false)
#14 .../Tinebase/Frontend/Json/Abstract.php(127): Tinebase_Controller_Record_Abstract-&gt;search(Object(Projects_Model_ProjectFilter), Object(Tinebase_Model_Pagination), true)
#15 .../Projects/Frontend/Json.php(56): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Projects_Controller_Project), &#039;Projects_Model_...&#039;, true)
#16 [internal function]: Projects_Frontend_Json-&gt;searchProjects(Array, Array)
#17 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#18 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#19 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#20 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#21 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#22 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#23 .../index.php(57): Tinebase_Core::dispatchRequest()
#24 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Feb 2012 17:39**

konnte das leider nicht reproduzieren. kannst du mir mal den filter schicken, der gesendet wird? steht im logfile (DEBUG).

also diesen sermon:


3ecc5 schüle, phil - 2012-02-08T17:39:11+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Projects.searchProjects
            [params] =&gt; Array
                (
                    [filter] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [condition] =&gt; OR
                                    [filters] =&gt; Array
                                        (
                                            [0] =&gt; Array
                                                (
                                                    [condition] =&gt; AND
                                                    [filters] =&gt; Array
                                                        (
                                                            [0] =&gt; Array
                                                                (
                                                                    [field] =&gt; query
                                                                    [operator] =&gt; contains
                                                                    [value] =&gt; 
                                                                    [id] =&gt; ext-record-55
                                                                )

                                                            [1] =&gt; Array
                                                                (
                                                                    [field] =&gt; foreignRecord
                                                                    [operator] =&gt; AND
                                                                    [value] =&gt; Array
                                                                        (
                                                                            [appName] =&gt; Addressbook
                                                                            [modelName] =&gt; Contact
                                                                            [linkType] =&gt; relation
                                                                            [filters] =&gt; Array
                                                                                (
                                                                                    [0] =&gt; Array
                                                                                        (
                                                                                            [field] =&gt; query
                                                                                            [operator] =&gt; contains
                                                                                            [value] =&gt; 
                                                                                            [id] =&gt; ext-record-107
                                                                                        )

                                                                                )

                                                                        )

                                                                    [id] =&gt; ext-record-91
                                                                )

                                                        )

                                                    [id] =&gt; ext-comp-1290
                                                    [label] =&gt; Projects
                                                )

                                        )

                                )

                        )

                    [paging] =&gt; Array
                        (
                            [sort] =&gt; creation_time
                            [dir] =&gt; DESC
                            [start] =&gt; 0
                            [limit] =&gt; 50
                        )

                )

            [id] =&gt; 12
        )

)

**Comment by Gloirin** [comment]
**Comment posted by GWI on 8 Feb 2012 20:20**

upload log

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Feb 2012 11:01**

hm, this one looks very strange:


 [0] =&gt; Array
                                                                                (
                                                                                    [field] =&gt; :id
                                                                                    [operator] =&gt; equals
                                                                                    [value] =&gt; Array
                                                                                        (
                                                                                            [n_fn] =&gt; 
                                                                                            [n_fileas] =&gt; 
                                                                                            [org_name] =&gt; 
                                                                                            [container_id] =&gt; 5
                                                                                        )

                                                                                )


kannst mal einen screenshot von deinem filter (bzw. der filter-toolbar) anhängen? ich bekomme das so wie bei dir nicht zusammengeklickt.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 5 Mar 2012 19:54**

Upload Screenshop

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Mar 2012 09:43**

hm, vermutlich ist der &quot;Meine Projekte&quot; filter bei dir kaputt, bzw. der eigene user im teilnehmerfilter. du könntest mal die projekte-applikation neu installieren (dann werden die filter neu angelegt) und dann nochmal testen.

konnte es jedenfalls mit ner frischen installation nicht nachvollziehen.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 12 Mar 2012 21:16**

Ready to Close!!

Das Problem hat sich wohl von allein gelöst. Ist bisher nich mehr aufgetreten.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Mar 2012 09:03**

alles klar :)
