### ISSUE TITLE
0005618:
Editing a recurring event doesn't work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#2864]
**Reported by BoehserWolf on 9 Feb 2012 22:16**

**Version:** Milan (2012-03) Beta 2

Debug-level was set to 5.

--- snip ---
5c217 Doe, John - 2012-02-09T22:09:31+00:00 WARN (4): Syncope_Command_Sync::handle::276 failed to update entry exception &#039;Tinebase_Exception_Date&#039; with message &#039;given $_date is not an instance of DateTime&#039; in /var/www/tine20/Tinebase/DateTime.php:244
Stack trace:
#0 /var/www/tine20/Tinebase/DateTime.php(327): Tinebase_DateTime-&gt;compare(NULL, &#039;c&#039;)
#1 /var/www/tine20/Calendar/Controller/Event.php(947): Tinebase_DateTime-&gt;equals(NULL)
#2 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(583): Calendar_Controller_Event-&gt;_inspectBeforeUpdate(Object(Calendar_Model_Event), Object(Calendar_Model_Event))
#3 /var/www/tine20/Calendar/Controller/Event.php(451): Tinebase_Controller_Record_Abstract-&gt;update(Object(Calendar_Model_Event))
#4 /var/www/tine20/Calendar/Controller/MSEventFacade.php(289): Calendar_Controller_Event-&gt;update(Object(Calendar_Model_Event), false)
#5 /var/www/tine20/ActiveSync/Controller/Abstract.php(332): Calendar_Controller_MSEventFacade-&gt;update(Object(Calendar_Model_Event))
#6 /var/www/tine20/library/Syncope/lib/Syncope/Command/Sync.php(266): ActiveSync_Controller_Abstract-&gt;updateEntry(&#039;calendar-root&#039;, &#039;0e73171be7fdf02...&#039;, Object(SimpleXMLElement))
#7 /var/www/tine20/library/Syncope/lib/Syncope/Server.php(125): Syncope_Command_Sync-&gt;handle()
#8 /var/www/tine20/library/Syncope/lib/Syncope/Server.php(57): Syncope_Server-&gt;_handlePost()
#9 /var/www/tine20/ActiveSync/Server/Http.php(97): Syncope_Server-&gt;handle()
#10 /var/www/tine20/Tinebase/Core.php(235): ActiveSync_Server_Http-&gt;handle()
#11 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#12 {main}
--- snip ---

**Steps to reproduce:** - create monthly recurring event in webgui
- edit event on phone (all events)
- change headline

**Comment by Gloirin** [comment]
**Comment posted by BoehserWolf on 9 Feb 2012 22:25**

Forgot: Phones are Samsung Galaxy S running Android 2.3.3 and 2.3.5.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 11 Feb 2012 07:50**

The problem is fixed in 2012/03 beta 3.
