### ISSUE TITLE
0005926:
Update from maischa 2011-05-6 to 2011-05-7 breaks felamimail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3017]
**Reported by Olodin on 1 Mar 2012 15:31**

**Version:** Maischa (2011-05-7)

After update to from maischa 2011-05-6 to 2011-05-7 opening felamimail hangs and throws this exception:

exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;some fields imap_status have invalid content&#039; in /usr/local/www/tine20/Tinebase/Record/Abstract.php:457
Stack trace:
#0 /usr/local/www/tine20/Tinebase/Record/Abstract.php(299): Tinebase_Record_Abstract-&gt;isValid(true)
#1 /usr/local/www/tine20/Tinebase/Record/Abstract.php(173): Tinebase_Record_Abstract-&gt;setFromArray(Array)
#2 /usr/local/www/tine20/Felamimail/Controller/Cache/Folder.php(369): Tinebase_Record_Abstract-&gt;__construct(Array)
#3 /usr/local/www/tine20/Felamimail/Controller/Cache/Folder.php(93): Felamimail_Controller_Cache_Folder-&gt;_getOrCreateFolders(Array, Object(Felamimail_Model_Account), &#039;&#039;)
#4 /usr/local/www/tine20/Felamimail/Controller/Folder.php(131): Felamimail_Controller_Cache_Folder-&gt;update(&#039;48a10b828090387...&#039;, &#039;&#039;)
#5 /usr/local/www/tine20/Tinebase/Frontend/Json/Abstract.php(106): Felamimail_Controller_Folder-&gt;search(Object(Felamimail_Model_FolderFilter), Object(Tinebase_Model_Pagination), false)
#6 /usr/local/www/tine20/Felamimail/Frontend/Json.php(36): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, &#039;&#039;, Object(Felamimail_Controller_Folder), &#039;Felamimail_Mode...&#039;)
#7 [internal function]: Felamimail_Frontend_Json-&gt;searchFolders(Array)
#8 /usr/local/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#9 /usr/local/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 /usr/local/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#11 /usr/local/www/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#12 /usr/local/www/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#13 /usr/local/www/tine20/Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#14 /usr/local/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#15 {main}

**Comment by Gloirin** [comment]
Related to #2734

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 1 Mar 2012 15:32**

Huch, da war ich viel zu langsam. Siehe #0005924

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Mar 2012 21:38**

still some problems with the now working InArray validator in felamimail (some fields ssl,smtp_ssl have invalid content, ...). should be fixed in 2011-05-9.
