### ISSUE TITLE
0005940:
nach dem Update funktioniert einloggen nicht mehr

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3024]
**Reported by asom on 2 Mar 2012 14:09**

**Version:** Maischa (2011-05-8)

Als Fehlermeldung:

&#039;Der Server kann Ihre Anfrage momentan nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator&#039;

**Additional information:** fafc1 Müller, Hans - 2012-03-02T14:27:54+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_NotFound -&gt; User with accountId =  SimpleFAQ not found.
fafc1 Müller, Hans - 2012-03-02T14:27:54+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/User/Sql.php(151): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountId&#039;, &#039;SimpleFAQ&#039;, &#039;Tinebase_Model_...&#039;)
#1 .../Tinebase/User/Abstract.php(490): Tinebase_User_Sql-&gt;getUserByProperty(&#039;accountId&#039;, &#039;SimpleFAQ&#039;, &#039;Tinebase_Model_...&#039;)
#2 .../Tinebase/Container.php(510): Tinebase_User_Abstract-&gt;getUserById(&#039;SimpleFAQ&#039;)
#3 .../SimpleFAQ/Frontend/Json.php(120): Tinebase_Container-&gt;getDefaultContainer(&#039;e73d854314eee99...&#039;, &#039;SimpleFAQ&#039;)
#4 .../Tinebase/Frontend/Json.php(557): SimpleFAQ_Frontend_Json-&gt;getRegistryData()
#5 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#6 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 .../Tinebase/Core.php(223): Tinebase_Server_Json-&gt;handle()
#12 .../index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by asom on 2 Mar 2012 14:11**

wo kann ich die Version 2011-05-05 runterladen?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Mar 2012 14:21**

kannst du den fehler im log bitte auch posten?

download: http://www.tine20.org/downloads/2011-05-5/tine20-allinone_2011-05-5.tar.bz2

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Mar 2012 15:14**

komischer fehler. von welcher version kommst du denn?

**Comment by Gloirin** [comment]
**Comment posted by asom on 2 Mar 2012 15:16**

wieso Version 2011-05-5!

Was muss ich machen, damit es funktioniert?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Mar 2012 15:16**

ah, du hast eine ältere version der simplefaq app installiert. die musst du auch updaten (verfügbar im download).

**Comment by Gloirin** [comment]
**Comment posted by asom on 5 Mar 2012 07:44**

Jetzt funktioniert es, ich musste zusätzlich alte sessions löschen!
