### ISSUE TITLE
0005976:
Delete all adressbooks -> exception -> No login

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3042]
**Reported by Canny on 8 Mar 2012 23:00**

**Version:** Milan (2012-03-1)

I executed a clean tine installation. After the first login I deleted the addressbook of the inital created admin user an also the shared internal address.
After that no login is possible anymore. See the exception attached.

**Additional information:** 2012-03-08T22:54:52+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Backend/Sql/Abstract.php(202): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;1&#039;, &#039;id&#039;, false)
#1 .../Admin/Frontend/Json.php(85): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;1&#039;)
#2 .../Tinebase/Frontend/Json.php(626): Admin_Frontend_Json-&gt;getRegistryData()
#3 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(57): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:27**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: f6174161cc96d45b89d1a97a9cf085e5c1000b3e 
Author: Philipp Schüle
Log: 
#5976: Delete all adressbooks -&gt; exception -&gt; No login
Changed paths:
 tine20/Tinebase/Exception/Record/SystemContainer.php
 tine20/Tinebase/js/widgets/tree/ContextMenu.js
 tine20/Tinebase/Container.php
 tine20/Tinebase/js/ExceptionHandler.js
 tine20/Addressbook/js/Addressbook.js
 tine20/Admin/Controller/Container.php
 tine20/Tinebase/js/widgets/grid/GridPanel.js
