### ISSUE TITLE
0006006:
ActiveSync should not depend on Tasks or Calendar apps

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3057]
**Reported by pschuele on 12 Mar 2012 12:18**

**Version:** Milan (2012-03-1)

ActiveSync should not depend on Tasks or Calendar apps

**Additional information:** 0cb62 Admin Account, Tine 2.0 - 2012-03-12T06:38:03+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Container.php(478): Tinebase_Application-&gt;getApplicationByName(&#039;Tasks&#039;)
#1 .../Tinebase/Preference/Abstract.php(792): Tinebase_Container-&gt;getPersonalContainer(&#039;47f488d1adc5f7b...&#039;, &#039;Tasks&#039;, &#039;47f488d1adc5f7b...&#039;, 0, true)
#2 .../ActiveSync/Preference.php(108): Tinebase_Preference_Abstract-&gt;_getDefaultContainerPreferenceDefaults(Object(Tinebase_Model_Preference), &#039;47f488d1adc5f7b...&#039;, &#039;Tasks&#039;, &#039;defaultTaskList&#039;)
#3 .../Tinebase/Preference/Abstract.php(281): ActiveSync_Preference-&gt;getApplicationPreferenceDefaults(&#039;defaultTaskList&#039;, &#039;47f488d1adc5f7b...&#039;, &#039;user&#039;)
#4 .../Tinebase/Preference/Abstract.php(241): Tinebase_Preference_Abstract-&gt;getValueForUser(&#039;defaultTaskList&#039;, &#039;47f488d1adc5f7b...&#039;, &#039;user&#039;)
#5 .../Tinebase/Preference/Abstract.php(112): Tinebase_Preference_Abstract-&gt;getValue(&#039;defaultTaskList&#039;)
#6 .../Tinebase/Frontend/Json.php(646): Tinebase_Preference_Abstract-&gt;__get(&#039;defaultTaskList&#039;)
#7 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#8 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#9 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#11 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#12 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#13 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#14 .../index.php(57): Tinebase_Core::dispatchRequest()
#15 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 08:11**

should check if app is disabled, too.

same for calendar.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 10:08**

same for mail app, ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 10:43**

@kay: please add a feature request for this ... the tasks and calendar dependency is slightly different.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 15:05**

Integrated in tine20:1,736  ( See http://ci.tine20.org/job/tine20/1736/ ).

Revision/Changeset: beab1d831b2344a1b3ba355011736a8c9af64b4c 
Author: Philipp Schüle
Log: 
 #6006: ActiveSync should not depend on apps
Changed paths:
 tine20/Tinebase/Frontend/Json.php
 tine20/Tinebase/Model/Filter/ForeignId.php
 tine20/Tinebase/Application.php
 tine20/Tinebase/Model/Filter/ForeignRecord.php
 tine20/Tinebase/Model/Filter/Relation.php
 tine20/Calendar/Model/ContactAttendeeFilter.php
 tine20/ActiveSync/Preference.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: a7379da8ab9af2f1f2033e8205c7e7989a77ff6d 
Author: Philipp Schüle
Log: 
 #6006: ActiveSync should not depend on apps
Changed paths:
 tine20/Tinebase/Frontend/Json.php
 tine20/Tinebase/Model/Filter/ForeignId.php
 tine20/Tinebase/Application.php
 tine20/Tinebase/Model/Filter/ForeignRecord.php
 tine20/Tinebase/Model/Filter/Relation.php
 tine20/Calendar/Model/ContactAttendeeFilter.php
 tine20/ActiveSync/Preference.php
