### ISSUE TITLE
0006056:
check dependencies when uninstalling an application

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3082]
**Reported by pschuele on 15 Mar 2012 09:33**

check dependencies when uninstalling an application

- uninstall dependent apps, too or prevent uninstall of an application that other apps depend on

**Steps to reproduce:** - CRM + Tasks are installed
- uninstall Tasks
- try to login
-&gt; crash (see trace in Additional Information)

**Additional information:** 2cc00 Admin Account, Tine 2.0 - 2012-03-15T09:04:22+00:00 NOTICE (5): Tinebase_Acl_Roles::hasRight::107 Application Tasks is not installed.
2cc00 Admin Account, Tine 2.0 - 2012-03-15T09:04:22+00:00 WARN (4): Tinebase_Frontend_Json::getAllRegistryData::629 No right to access application Tasks
2cc00 Admin Account, Tine 2.0 - 2012-03-15T09:04:22+00:00 NOTICE (5): Tinebase_Frontend_Json::getAllRegistryData::630 #0 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(128): Tinebase_Core::getApplicationInstance(&#039;Tasks&#039;, &#039;Task&#039;)
#1 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/Relation.php(44): Tinebase_Controller_Record_Abstract::getController(&#039;Tasks_Model_Tas...&#039;)
#2 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/ForeignRecord.php(64): Tinebase_Model_Filter_Relation-&gt;_getController()
#3 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/Abstract.php(103): Tinebase_Model_Filter_ForeignRecord-&gt;setValue(Array)
#4 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php(447): Tinebase_Model_Filter_Abstract-&gt;__construct(Array)
#5 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php(327): Tinebase_Model_Filter_FilterGroup-&gt;createFilter(Array)
#6 /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php(227): Tinebase_Model_Filter_FilterGroup-&gt;_createStandardFilterFromArray(Array)
#7 /usr/local/workspace/tine20/tine20/Tinebase/Model/PersistentFilter.php(139): Tinebase_Model_Filter_FilterGroup-&gt;setFromArray(Array)
#8 /usr/local/workspace/tine20/tine20/Tinebase/Model/PersistentFilter.php(86): Tinebase_Model_PersistentFilter::getFilterGroup(&#039;Crm_Model_LeadF...&#039;, Array)
#9 /usr/local/workspace/tine20/tine20/Tinebase/Record/Abstract.php(180): Tinebase_Model_PersistentFilter-&gt;setFromArray(Array)
#10 /usr/local/workspace/tine20/tine20/Tinebase/Record/RecordSet.php(75): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#11 /usr/local/workspace/tine20/tine20/Tinebase/PersistentFilter/Backend/Sql.php(96): Tinebase_Record_RecordSet-&gt;__construct(&#039;Tinebase_Model_...&#039;, Array, true)
#12 /usr/local/workspace/tine20/tine20/Tinebase/Backend/Sql/Abstract.php(448): Tinebase_PersistentFilter_Backend_Sql-&gt;_rawDataToRecordSet(Array)
#13 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(149): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Tinebase_Model_PersistentFilterFilter), Object(Tinebase_Model_Pagination), false)
#14 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/Abstract.php(127): Tinebase_Controller_Record_Abstract-&gt;search(Object(Tinebase_Model_PersistentFilterFilter), Object(Tinebase_Model_Pagination), false)
#15 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/PersistentFilter.php(31): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, NULL, Object(Tinebase_PersistentFilter), &#039;Tinebase_Model_...&#039;)
#16 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/PersistentFilter.php(83): Tinebase_Frontend_Json_PersistentFilter-&gt;searchPersistentFilter(Array, NULL)
#17 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json.php(597): Tinebase_Frontend_Json_PersistentFilter::getAllPersistentFilters()
#18 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json.php(627): Tinebase_Frontend_Json-&gt;getRegistryData()
#19 [internal function]: Tinebase_Frontend_Json-&gt;getAllRegistryData()
#20 /usr/local/workspace/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#21 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#22 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#23 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#24 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#25 /usr/local/workspace/tine20/tine20/Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#26 /usr/local/workspace/tine20/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#27 {main}

**Comment by pschuele** [comment]
maybe no longer relevant. should be checked again.
