### ISSUE TITLE
0006226:
Data truncated for column 'adr_two_lon'

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3167]
**Reported by pschuele on 11 Apr 2012 11:41**

**Version:** Milan (2012-03-1)

Data truncated for column &#039;adr_two_lon&#039;

**Steps to reproduce:** got this error during the import of duplicate contacts (&#039;keep both&#039;).

**Additional information:** a59b7 schüle, phil - 2012-04-11T11:33:34+00:00 INFO (6): Tinebase_Import_Abstract::_handleImportException::683 SQLSTATE[01000]: Warning: 1265 Data truncated for
 column &#039;adr_two_lon&#039; at row 1
a59b7 schüle, phil - 2012-04-11T11:33:34+00:00 DEBUG (7): Tinebase_Import_Abstract::_handleImportException::684 #0 /usr/local/workspace/tine20/tine20/library/Ze
nd/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/local/workspace/tine20/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/local/workspace/tine20/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /usr/local/workspace/tine20/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /usr/local/workspace/tine20/tine20/Tinebase/Backend/Sql/Abstract.php(760): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_addressb...&#039;, Array)
#5 /usr/local/workspace/tine20/tine20/Addressbook/Backend/Sql.php(104): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#6 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(420): Addressbook_Backend_Sql-&gt;create(Object(Addressbook_Model_Contact))
#7 [internal function]: Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact), false)
#8 /usr/local/workspace/tine20/tine20/Tinebase/Import/Abstract.php(661): call_user_func(Array, Object(Addressbook_Model_Contact), false)
#9 /usr/local/workspace/tine20/tine20/Tinebase/Import/Abstract.php(406): Tinebase_Import_Abstract-&gt;_importAndResolveConflict(Object(Addressbook_Model_Contact), 
&#039;keep&#039;)
#10 /usr/local/workspace/tine20/tine20/Tinebase/Import/Abstract.php(204): Tinebase_Import_Abstract-&gt;_importRecord(Object(Addressbook_Model_Contact), &#039;keep&#039;, Arr
ay)
#11 /usr/local/workspace/tine20/tine20/Tinebase/Import/Abstract.php(133): Tinebase_Import_Abstract-&gt;_doImport(Resource id #216, Array)
#12 /usr/local/workspace/tine20/tine20/Tinebase/Import/Abstract.php(94): Tinebase_Import_Abstract-&gt;import(Resource id #216, Array)
#13 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/Abstract.php(277): Tinebase_Import_Abstract-&gt;importFile(&#039;/opt/tinefiles/...&#039;, Array)
#14 /usr/local/workspace/tine20/tine20/Addressbook/Frontend/Json.php(159): Tinebase_Frontend_Json_Abstract-&gt;_import(&#039;d52ae9345b3c2e5...&#039;, &#039;c588fa5c8d191e5...&#039;, 
Array, Array)
#15 [internal function]: Addressbook_Frontend_Json-&gt;importContacts(&#039;d52ae9345b3c2e5...&#039;, &#039;c588fa5c8d191e5...&#039;, Array, Array)
#16 /usr/local/workspace/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#17 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#18 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#19 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#20 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#21 /usr/local/workspace/tine20/tine20/Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#22 /usr/local/workspace/tine20/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#23 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Apr 2012 13:39**

Integrated in tine20:1,692  ( See http://ci.tine20.org/job/tine20/1692/ ).

Revision/Changeset: c23adb3e6abb688b47a41db22fc8939fde43ba77 
Author: Philipp Schüle
Log: 
 #6226: Data truncated for column &#039;adr_two_lon&#039;
Changed paths:
 tests/tine20/Addressbook/JsonTest.php
 tine20/Addressbook/Model/Contact.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: 49ee51cee2364c16b112556233c986d113a2dfd1 
Author: Philipp Schüle
Log: 
 #6226: Data truncated for column &#039;adr_two_lon&#039;
Changed paths:
 tests/tine20/Addressbook/JsonTest.php
 tine20/Addressbook/Model/Contact.php
