### ISSUE TITLE
0006234:
setting flags for removed email fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3171]
**Reported by pschuele on 11 Apr 2012 16:34**

**Version:** Milan (2012-03-1)

setting flags for removed email fails

- client should be notified of deleted mail

**Additional information:** Syncope_Command_Sync::handle::289 failed to update entry exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Felamimail_Mode
l_Message record with id = cc9fa3880582968df5014910595e85b93cc0a242 not found!&#039; in /opt/local/tine/2012-03-2/htdocs/Tinebase/Backend/Sql/Abstract.php:247
Stack trace:
#0 /opt/local/tine/2012-03-2/htdocs/Tinebase/Backend/Sql/Abstract.php(202): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;cc9fa3880582968...&#039;, &#039;id&#039;, false)
#1 /opt/local/tine/2012-03-2/htdocs/Tinebase/Controller/Record/Abstract.php(304): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;cc9fa3880582968...&#039;)
#2 /opt/local/tine/2012-03-2/htdocs/ActiveSync/Controller/Email.php(421): Tinebase_Controller_Record_Abstract-&gt;get(&#039;cc9fa3880582968...&#039;)
#3 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Command/Sync.php(279): ActiveSync_Controller_Email-&gt;updateEntry(&#039;be183a596263868...&#039;, &#039;cc9fa3880582968...&#039;, Object(SimpleX
MLElement))
#4 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Server.php(134): Syncope_Command_Sync-&gt;handle()
#5 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Server.php(64): Syncope_Server-&gt;_handlePost()
#6 /opt/local/tine/2012-03-2/htdocs/ActiveSync/Server/Http.php(99): Syncope_Server-&gt;handle()
#7 /opt/local/tine/2012-03-2/htdocs/Tinebase/Core.php(235): ActiveSync_Server_Http-&gt;handle()
#8 /opt/local/tine/2012-03-2/htdocs/index.php(57): Tinebase_Core::dispatchRequest()
#9 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Apr 2012 09:17**

Integrated in tine20:1,696  ( See http://ci.tine20.org/job/tine20/1696/ ).

Revision/Changeset: 11660462da69dc8ef987f30200e1f9691322dbb6 
Author: Philipp Schüle
Log: 
 #6234: setting flags for removed email fails
Changed paths:
 tine20/ActiveSync/Controller/Email.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: d0a3e085ec30a2afd367dbdbab93b74fdb989f16 
Author: Philipp Schüle
Log: 
 #6234: setting flags for removed email fails
Changed paths:
 tine20/ActiveSync/Controller/Email.php
