### ISSUE TITLE
0006236:
convert TENF to syncope exception in all update fns

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3172]
**Reported by pschuele on 12 Apr 2012 09:38**

**Version:** Milan (2012-03-1)

convert TENF to syncope exception in all update fns

**Additional information:** Syncope_Command_Sync::handle::289 failed to update entry exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Felamimail_Mode
l_Message record with id = cc9fa3880582968df5014910595e85b93cc0a242 not found!&#039; in /opt/local/tine/2012-03-2/htdocs/Tinebase/Backend/Sql/Abstract.php:247
Stack trace:
#0 /opt/local/tine/2012-03-2/htdocs/Tinebase/Backend/Sql/Abstract.php(202): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;cc9fa3880582968...&#039;, &#039;id&#039;, false)
#1 /opt/local/tine/2012-03-2/htdocs/Tinebase/Controller/Record/Abstract.php(304): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;cc9fa3880582968...&#039;)
#2 /opt/local/tine/2012-03-2/htdocs/ActiveSync/Controller/Email.php(421): Tinebase_Controller_Record_Abstract-&gt;get(&#039;cc9fa3880582968...&#039;)
#3 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Command/Sync.php(279): ActiveSync_Controller_Email-&gt;updateEntry(&#039;be183a596263868...&#039;, &#039;cc9fa3880582968...&#039;, Object(SimpleX
MLElement))
#4 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Server.php(134): Syncope_Command_Sync-&gt;handle()
#5 /opt/local/tine/2012-03-2/htdocs/library/Syncope/lib/Syncope/Server.php(64): Syncope_Server-&gt;_handlePost()
#6 /opt/local/tine/2012-03-2/htdocs/ActiveSync/Server/Http.php(99): Syncope_Server-&gt;handle()
#7 /opt/local/tine/2012-03-2/htdocs/Tinebase/Core.php(235): ActiveSync_Server_Http-&gt;handle()
#8 /opt/local/tine/2012-03-2/htdocs/index.php(57): Tinebase_Core::dispatchRequest()
#9 {main}

**Comment by Gloirin** [comment]
Related to #3171

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Apr 2012 12:20**

Integrated in tine20:1,698  ( See http://ci.tine20.org/job/tine20/1698/ ).

Revision/Changeset: f89f48dee90f5c2f7c223286b9abbfbc74ae2dab 
Author: Philipp Schüle
Log: 
 #6236: convert TENF to syncope exception in all update fns
Changed paths:
 tine20/ActiveSync/Controller/Abstract.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: b9075c74ae0dd8aa2b30085175b0448167990c83 
Author: Philipp Schüle
Log: 
 #6236: convert TENF to syncope exception in all update fns
Changed paths:
 tine20/ActiveSync/Controller/Abstract.php
