### ISSUE TITLE
0006246:
Error with service release 2012-03-02 on repo-install when updating on console

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3177]
**Reported by andydld on 13 Apr 2012 06:30**

**Version:** Milan (2012-03-2)

If i update an Tine 2.0-Installation on Debian thru console/ssh i got this error:

&quot;PHP Fatal error:  Uncaught exception &#039;Zend_Db_Table_Exception&#039; with message &#039;No                                                                                                                                                              adapter found for Tinebase_Db_Table&#039; in /usr/share/tine20/library/Zend/Db/Table/                                                                                                                                                             Abstract.php:754&quot;

Update thru browser-gui works fine.

**Steps to reproduce:** - Existing Tine 2.0 (2012-03-01)-Installation, installed over the repository
- apt-get update &amp;&amp; apt-get upgrade
- php /usr/share/tine20/setup.php --update

**Additional information:** Console-Output:

PHP Fatal error:  Uncaught exception &#039;Zend_Db_Table_Exception&#039; with message &#039;No                                                                                                                                                              adapter found for Tinebase_Db_Table&#039; in /usr/share/tine20/library/Zend/Db/Table/                                                                                                                                                             Abstract.php:754
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Table/Abstract.php(739): Zend_Db_Table_Abst                                                                                                                                                             ract-&gt;_setupDatabaseAdapter()
#1 /usr/share/tine20/library/Zend/Db/Table/Abstract.php(268): Zend_Db_Table_Abst                                                                                                                                                             ract-&gt;_setup()
#2 /usr/share/tine20/Tinebase/Application.php(72): Zend_Db_Table_Abstract-&gt;__con                                                                                                                                                             struct(Array)
#3 /usr/share/tine20/Tinebase/Application.php(99): Tinebase_Application-&gt;__const                                                                                                                                                             ruct()
#4 /usr/share/tine20/Setup/Frontend/Cli.php(186): Tinebase_Application::getInsta                                                                                                                                                             nce()
#5 /usr/share/tine20/Setup/Frontend/Cli.php(54): Setup_Frontend_Cli-&gt;_update(Obj                                                                                                                                                             ect(Zend_Console_Getopt))
#6 /usr/share/tine20/Setup/Server/Cli.php(88): Setup_Frontend_Cli-&gt;handle(Object                                                                                                                                                             (Zend_Console_Getopt))
#7 /usr/share/tine20/Setup/Core.php(103): Setup_Server_Cli-&gt;handle()
#8 /usr/share/tine20/setup.php(53): Setup_Core::dispatchRequest()
#9 {main}
  thrown in /usr/share/tine20/library/Zend/Db/Table/Abstract.php on line 754

Fatal error: Uncaught exception &#039;Zend_Db_Table_Exception&#039; with message &#039;No adapt                                                                                                                                                             er found for Tinebase_Db_Table&#039; in /usr/share/tine20/library/Zend/Db/Table/Abstr                                                                                                                                                             act.php:754
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Table/Abstract.php(739): Zend_Db_Table_Abst                                                                                                                                                             ract-&gt;_setupDatabaseAdapter()
#1 /usr/share/tine20/library/Zend/Db/Table/Abstract.php(268): Zend_Db_Table_Abst                                                                                                                                                             ract-&gt;_setup()
#2 /usr/share/tine20/Tinebase/Application.php(72): Zend_Db_Table_Abstract-&gt;__con                                                                                                                                                             struct(Array)
#3 /usr/share/tine20/Tinebase/Application.php(99): Tinebase_Application-&gt;__const                                                                                                                                                             ruct()
#4 /usr/share/tine20/Setup/Frontend/Cli.php(186): Tinebase_Application::getInsta                                                                                                                                                             nce()
#5 /usr/share/tine20/Setup/Frontend/Cli.php(54): Setup_Frontend_Cli-&gt;_update(Obj                                                                                                                                                             ect(Zend_Console_Getopt))
#6 /usr/share/tine20/Setup/Server/Cli.php(88): Setup_Frontend_Cli-&gt;handle(Object                                                                                                                                                             (Zend_Console_Getopt))
#7 /usr/share/tine20/Setup/Core.php(103): Setup_Server_Cli-&gt;handle()
#8 /usr/share/tine20/setup.php(53): Setup_Core::dispatchRequest()
#9 {main}
  thrown in /usr/share/tine20/library/Zend/Db/Table/Abstract.php on line 754

This error is discribed ob the forum, too:

http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10892

(german)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 13 Apr 2012 07:05**

Please try this command:

php /usr/share/tine20/setup.php --config /etc/tine20/config.inc.php --update
