### ISSUE TITLE
0006254:
edit/create user is not possible

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3180]
**Reported by splinter03 on 13 Apr 2012 15:41**

**Version:** Milan (2012-03-2)

I&#039;ve a role called &quot;Admin&quot;. This role has all rights! The role contains to the group &quot;Administrators&quot;. My user contains to this group. If i try to create a new user, tine says: &quot;Sie sind nicht berechtigt diese Aktion auszuführen&quot;. Also i can&#039;t edit users, cause the button is disabled.

**Additional information:** 0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Admin.saveUser
            [params] =&gt; Array
                (
                    [recordData] =&gt; Array
                        (
                            [sambaSAM] =&gt; Array
                                (
                                    [sid] =&gt; 
                                    [primaryGroupSID] =&gt; 
                                    [acctFlags] =&gt; 
                                    [homeDrive] =&gt; 
                                    [homePath] =&gt; 
                                    [profilePath] =&gt; 
                                    [logonScript] =&gt; 
                                    [logonTime] =&gt; 
                                    [logoffTime] =&gt; 
                                    [kickoffTime] =&gt; 
                                    [pwdLastSet] =&gt; 
                                    [pwdCanChange] =&gt; 
                                    [pwdMustChange] =&gt; 
                                )

                            [emailUser] =&gt; Array
                                (
                                    [emailUID] =&gt; 
                                    [emailGID] =&gt; 
                                    [emailMailQuota] =&gt; 
                                    [emailMailSize] =&gt; 
                                    [emailSieveQuota] =&gt; 
                                    [emailSieveSize] =&gt; 
                                    [emailLastLogin] =&gt; 
                                    [emailUserId] =&gt; 
                                    [emailAliases] =&gt; 
                                    [emailForwards] =&gt; 
                                    [emailForwardOnly] =&gt; 
                                    [emailAddress] =&gt; 
                                    [emailUsername] =&gt; 
                                )

                            [accountStatus] =&gt; enabled
                            [visibility] =&gt; displayed
                            [container_id] =&gt; 61
                            [accountPrimaryGroup] =&gt; dbe5dd9967ed1de2e047a3da3524b92be1282996
                            [accountLastLogin] =&gt; 
                            [accountLastPasswordChange] =&gt; 
                            [accountFirstName] =&gt; test
                            [accountLastName] =&gt; test
                            [accountLoginName] =&gt; test
                            [accountPassword] =&gt; test
                            [accountExpires] =&gt; 
                            [accountLastLoginfrom] =&gt; 
                            [accountEmailAddress] =&gt; 
                            [openid] =&gt; 
                            [groups] =&gt; Array
                                (
                                    [0] =&gt; dbe5dd9967ed1de2e047a3da3524b92be1282996
                                )

                            [accountRoles] =&gt; Array
                                (
                                )

                            [customfields] =&gt; Array
                                (
                                )

                        )

                )

            [id] =&gt; 53
        )

)

0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Admin.saveUser
0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 DEBUG (7): Tinebase_User_Registration::__construct::57 no config for registration found! 
0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 DEBUG (7): Tinebase_User::getInstance::139 accounts backend: Sql
0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 INFO (6): Tinebase_User::factory::197 Created user backend of type Sql
0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 DEBUG (7): Tinebase_CustomField::getCustomFieldsForApplication::186 Got 0 uncached custom fields for app id 34f1bf70a0f03c4cf83729d08e378a1d4037fa33 (cacheid: getCustomFieldsForApplication34f1bf70a0f03c4cf83729d08e378a1d4037fa33Addressbook_Model_ContactreadGrant)
0ff50 *******, Michael - 2012-04-13T15:33:00+00:00 DEBUG (7): Tinebase_User_Sql::addUserInSqlBackend::681 Adding user to SQL backend: test
0ff50 *******, Michael - 2012-04-13T15:33:01+00:00 ERR (3): Admin_Controller_User::create::252 No permission to add list member.
0ff50 *******, Michael - 2012-04-13T15:33:01+00:00 DEBUG (7): Admin_Controller_User::create::253 #0 /var/www/tine20/Addressbook/Controller/List.php(97): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;update&#039;, true, &#039;No permission t...&#039;)
#1 /var/www/tine20/Admin/Controller/Group.php(264): Addressbook_Controller_List-&gt;addListMember(&#039;19f26bf2ff2c4f3...&#039;, &#039;ce50fc78875690f...&#039;)
#2 /var/www/tine20/Admin/Controller/Group.php(135): Admin_Controller_Group-&gt;addGroupMember(&#039;dbe5dd9967ed1de...&#039;, &#039;7e0aaadba93d20c...&#039;)
#3 /var/www/tine20/Admin/Controller/User.php(246): Admin_Controller_Group-&gt;setGroupMemberships(Object(Tinebase_Model_FullUser), Array)
#4 /var/www/tine20/Admin/Frontend/Json.php(372): Admin_Controller_User-&gt;create(Object(Tinebase_Model_FullUser), &#039;test&#039;, &#039;test&#039;)
#5 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#6 /var/www/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 /var/www/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 /var/www/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 /var/www/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 /var/www/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 /var/www/tine20/Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#12 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}
0ff50 *******, Michael - 2012-04-13T15:33:01+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_AccessDenied -&gt; No permission to add list member.
0ff50 *******, Michael - 2012-04-13T15:33:01+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Addressbook/Controller/List.php(97): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;update&#039;, true, &#039;No permission t...&#039;)
#1 .../Admin/Controller/Group.php(264): Addressbook_Controller_List-&gt;addListMember(&#039;19f26bf2ff2c4f3...&#039;, &#039;ce50fc78875690f...&#039;)
#2 .../Admin/Controller/Group.php(135): Admin_Controller_Group-&gt;addGroupMember(&#039;dbe5dd9967ed1de...&#039;, &#039;7e0aaadba93d20c...&#039;)
#3 .../Admin/Controller/User.php(246): Admin_Controller_Group-&gt;setGroupMemberships(Object(Tinebase_Model_FullUser), Array)
#4 .../Admin/Frontend/Json.php(372): Admin_Controller_User-&gt;create(Object(Tinebase_Model_FullUser), &#039;test&#039;, &#039;test&#039;)
#5 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#6 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#12 .../index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Apr 2012 16:11**

looks like you do not have the needed container grants to change the members of the corresponding list (belonging to group dbe5dd9967ed1de2e047a3da3524b92be1282996). can you check the grants of your internal contacts container in the addressbook? and have a look at the group details (which container it is in, is it visible).

edit: perhaps it should be possible to save the user even if the group / list memberships could not be updated.

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 13 Apr 2012 16:20**

you&#039;re right, the problem are missinge rights to edit the internal contacts container. thanks!

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 13 Apr 2012 17:07**

Looks like my problem indeed, thanks for pointing me here.

But I don&#039;t know what to do :p

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Apr 2012 18:41**

@Gurney: check your &quot;Internal Contacts&quot; shared container in the Addressbook for the correct grants. Admin group should have the admin grant here.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 14 Apr 2012 09:43**

OK. I indeed had only read access. I&#039;ve updated the ACLs accordingly. :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Apr 2012 09:56**

TODO: we should not allow to chose a container for users/groups without the required grants.
think about the edit user button. what should happen here? perhaps we should only update the account data but not the corresponding contact?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 14 May 2012 12:55**

lets ignore containerACL for those admin tasks

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Jul 2012 11:24**

Integrated in tine20:1,886  ( See http://ci.tine20.org/job/tine20/1886/ ).

Revision/Changeset: 105316cc81434d86519d25b9c3f5d03beaad47b8 
Author: Philipp Schüle
Log: 
#6254: edit/create user is not possible
Changed paths:
 tine20/Admin/Controller/Group.php
 tine20/Tinebase/Container.php
 tests/tine20/Admin/JsonTest.php
 tine20/Admin/Controller/User.php
