### ISSUE TITLE
0006274:
Can no longer change calendar's color

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3189]
**Reported by weberho on 17 Apr 2012 13:58**

**Version:** Milan (2012-03-2)

When I try to change one of our shared calendars, the running-circle starts to run and never stops. In the log I can see the following exception:

2aa3f ... DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase_Container.setContainerColor
            [params] =&gt; Array
                (
                    [containerId] =&gt; 44
                    [color] =&gt; #99CC00
                )

            [id] =&gt; 44
        )

)

2aa3f ... INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Tinebase_Container.setContainerColor
2aa3f ... NOTICE (5): Tinebase_Core::errorHandler::378 Undefined variable: containerId in /usr/share/tine20/Tinebase/Container.php::86
3 (8)
2aa3f ... NOTICE (5): Tinebase_Container::hasGrant::890 Container id can not b
e 0 ().
2aa3f ... DEBUG (7): Tinebase_Container::hasGrant::891 #0 /usr/share/tine20/Tinebase/Container.php(888): Tinebase_Model_Container::convertContainerIdToInt(NULL)
#1 /usr/share/tine20/Tinebase/Container.php(863): Tinebase_Container-&gt;hasGrant(Object(Tinebase_Model_FullUser), NULL, &#039;adminGrant&#039;)
#2 /usr/share/tine20/Tinebase/Frontend/Json/Container.php(141): Tinebase_Container-&gt;setContainerColor(&#039;44&#039;, &#039;#99CC00&#039;)
#3 [internal function]: Tinebase_Frontend_Json_Container-&gt;setContainerColor(&#039;44&#039;, &#039;#99CC00&#039;)
#4 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 /usr/share/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 /usr/share/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#9 /usr/share/tine20/Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#10 /usr/share/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#11 {main}
2aa3f ... NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception -&gt; Container not found or permission to set containername denied!
2aa3f ... NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 [internal function]: Tinebase_Frontend_Json_Container-&gt;setContainerColor(&#039;44&#039;, &#039;#99CC00&#039;)
#1 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#2 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#3 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#4 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#5 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#6 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#7 .../index.php(57): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2012 08:33**

should work again (see attached changeset).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2012 08:47**

Integrated in tine20:1,704  ( See http://ci.tine20.org/job/tine20/1704/ ).

Revision/Changeset: aedc2f8f4ce2b4922639c8a6b3b345b0ecc03881 
Author: Philipp Schüle
Log: 
 #6274: Can no longer change calendar&#039;s color
Changed paths:
 tine20/Tinebase/Container.php
 tests/tine20/Tinebase/ContainerTest.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: 5d1c334d4b0bb0a4f6b7dc9b732122287806b3d9 
Author: Philipp Schüle
Log: 
 #6274: Can no longer change calendar&#039;s color
Changed paths:
 tine20/Tinebase/Container.php
 tests/tine20/Tinebase/ContainerTest.php
