### ISSUE TITLE
0006278:
concurrency conflict when saving product

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3191]
**Reported by asom on 18 Apr 2012 07:11**

**Version:** Milan (2012-03-2)

Als information erscheint die folgende Message-Box:

&#039;Passende Updates&#039;
&#039;Der Eintrag wurde von jemand anderem geändert während Sie daran arbeiteten. Sie müssen aktualisieren und die Änderungen erneut durchführen.&#039;

Dies &#039;von jemand anderem geändert&#039; ist aber nicht der Fall.

Auch auf der Demoseite von tine20 ist dieser effekt reproduzierbar!
Bei 1 oder 2 von z.B. 10 &#039;Produkten&#039; klappt es immer, bei den anderen jedoch nie!

**Steps to reproduce:** - add product
- add note to product + save
- edit product again
- change name + save
-&gt; concurrency error!

**Additional information:** d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::908 given localeString &#039;auto&#039;
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::917 session value: de
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 INFO (6): Tinebase_Core::setupUserLocale::947 Setting user locale: de
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::1028 setting execution life time to: 0
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 INFO (6): Tinebase_User::setBackendType::236 Setting backend type to Sql
d68d7 schüle, phil - 2012-04-22T11:25:36+00:00 DEBUG (7): Tinebase_Group::getInstance::71 groups backend: Sql
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::959 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Sales.saveProduct
            [params] =&gt; Array
                (
                    [recordData] =&gt; Array
                        (
                            [id] =&gt; 58f0f7afb4d6a12d29e23d2ec4864fda8e7294dd
                            [name] =&gt; prodxyz1
                            [description] =&gt; 
                            [price] =&gt; 43221
                            [manufacturer] =&gt; 
                            [category] =&gt; 
                            [tags] =&gt; Array
                                (
                                )

                            [notes] =&gt; Array
                                (
                                    [0] =&gt; Array
                                        (
                                            [id] =&gt; e6c1cc35150920e2f5c6f1ad4dd67f807ea62efb
                                            [note_type_id] =&gt; 1
                                            [note] =&gt; jsakdc
                                            [creation_time] =&gt; 2012-04-22 13:25:30
                                            [created_by] =&gt; schüle, phil
                                        )

                                )

                            [relations] =&gt; Array
                                (
                                )

                            [customfields] =&gt; Array
                                (
                                )

                        )

                )

            [id] =&gt; 2
        )

)

d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Sales.saveProduct
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 INFO (6): Tinebase_Controller_Record_Abstract::update::590 Update Sales_Model_Product
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_updateACLCheck::653 Doing ACL check ...
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_concurrencyManagement::680 Doing concurrency check ...
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::manageConcurrentUpdates::271 concurrent updates: current record last updated &#039;2012-04-22 11:25:29&#039; where record to be updated was last updated &#039;2012-04-22 11:02:28&#039;
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::manageConcurrentUpdates::278 during the concurrent update, the following changes have been made: Array
(
    [0] =&gt; Array
        (
            [id] =&gt; 53f9c278459154f668e7e96ce2e794bbf1c64dd6
            [application_id] =&gt; 06990bc952367d57ea7da42696177b7cbcf78675
            [record_id] =&gt; 58f0f7afb4d6a12d29e23d2ec4864fda8e7294dd
            [record_type] =&gt; Sales_Model_Product
            [record_backend] =&gt; Sql
            [modification_time] =&gt; 2012-04-22 11:02:51
            [modification_account] =&gt; 3cebf5c5b4c4d3cb7b546ab1ab3d7f07c25c4ba1
            [modified_attribute] =&gt; name
            [old_value] =&gt; prod
            [new_value] =&gt; prodxyz
        )

)

d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 ERR (3): Tinebase_Timemachine_ModificationLog::manageConcurrentUpdates::296 non resolvable conflict!
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::451 exception &#039;Tinebase_Timemachine_Exception_ConcurrencyConflict&#039; with message &#039;concurrency conflict!&#039; in /usr/local/workspace/tine20/tine20/Tinebase/Timemachine/ModificationLog.php:297
Stack trace:
#0 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(684): Tinebase_Timemachine_ModificationLog-&gt;manageConcurrentUpdates(Object(Sales_Model_Product), Object(Sales_Model_Product), &#039;Sales_Model_Pro...&#039;, &#039;Sql&#039;, &#039;58f0f7afb4d6a12...&#039;)
#1 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(604): Tinebase_Controller_Record_Abstract-&gt;_concurrencyManagement(Object(Sales_Model_Product), Object(Sales_Model_Product))
#2 [internal function]: Tinebase_Controller_Record_Abstract-&gt;update(Object(Sales_Model_Product))
#3 /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/Abstract.php(184): call_user_func_array(Array, Array)
#4 /usr/local/workspace/tine20/tine20/Sales/Frontend/Json.php(149): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Sales_Controller_Product), &#039;Product&#039;)
#5 [internal function]: Sales_Frontend_Json-&gt;saveProduct(Array)
#6 /usr/local/workspace/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 /usr/local/workspace/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 /usr/local/workspace/tine20/tine20/Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#12 /usr/local/workspace/tine20/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Timemachine_Exception_ConcurrencyConflict -&gt; concurrency conflict!
d68d7 schüle, phil - 2012-04-22T11:25:37+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Controller/Record/Abstract.php(684): Tinebase_Timemachine_ModificationLog-&gt;manageConcurrentUpdates(Object(Sales_Model_Product), Object(Sales_Model_Product), &#039;Sales_Model_Pro...&#039;, &#039;Sql&#039;, &#039;58f0f7afb4d6a12...&#039;)
#1 .../Tinebase/Controller/Record/Abstract.php(604): Tinebase_Controller_Record_Abstract-&gt;_concurrencyManagement(Object(Sales_Model_Product), Object(Sales_Model_Product))
#2 [internal function]: Tinebase_Controller_Record_Abstract-&gt;update(Object(Sales_Model_Product))
#3 .../Tinebase/Frontend/Json/Abstract.php(184): call_user_func_array(Array, Array)
#4 .../Sales/Frontend/Json.php(149): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Sales_Controller_Product), &#039;Product&#039;)
#5 [internal function]: Sales_Frontend_Json-&gt;saveProduct(Array)
#6 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#11 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#12 .../index.php(57): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Apr 2012 11:27**

looks like there is a problem with the concurrent update check for notes!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 May 2012 11:37**

notes are working correctly, the problem was that the modlog fields were not send by the client ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 May 2012 09:38**

Integrated in tine20:1,744  ( See http://ci.tine20.org/job/tine20/1744/ ).

Revision/Changeset: a839afc490f009ac105b84829083b7746d52ff8f 
Author: Philipp Schüle
Log: 
 #6278: concurrency conflict when saving product
Changed paths:
 tine20/Sales/Controller/Contract.php
 tests/tine20/Sales/JsonTest.php
 tine20/Sales/js/Models.js

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: 24a5c95bf185bcac509c98aed3be6541f150706d 
Author: Philipp Schüle
Log: 
 #6278: concurrency conflict when saving product
Changed paths:
 tine20/Sales/Controller/Contract.php
 tests/tine20/Sales/JsonTest.php
 tine20/Sales/js/Models.js
