### ISSUE TITLE
0006304:
client state too long for DB

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3204]
**Reported by pschuele on 22 Apr 2012 11:08**

**Version:** Milan (2012-03-2)

client state too long for DB

Zend_Db_Statement_Exception -&gt; SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;data&#039; at row 1

**Additional information:** 98f0f user, demo - 2012-04-20T09:32:59+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Zend_Db_Statement_Exception -&gt; SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;data&#039; at row 1
98f0f user, demo - 2012-04-20T09:32:59+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;UPDATE `tine20_...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(604): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;UPDATE `tine20_...&#039;, Array)
#4 .../Tinebase/Backend/Sql/Abstract.php(975): Zend_Db_Adapter_Abstract-&gt;update(&#039;tine20_state&#039;, Array, Array)
#5 .../Tinebase/State.php(124): Tinebase_Backend_Sql_Abstract-&gt;update(Object(Tinebase_Model_State))
#6 .../Tinebase/State.php(96): Tinebase_State-&gt;saveStateInfo(Array)
#7 .../Tinebase/Frontend/Json.php(211): Tinebase_State-&gt;setState(&#039;tinebase-mainsc...&#039;, &#039;o%3AcurrentTabs...&#039;)
#8 [internal function]: Tinebase_Frontend_Json-&gt;setState(&#039;tinebase-mainsc...&#039;, &#039;o%3AcurrentTabs...&#039;)
#9 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 .../Tinebase/Server/Json.php(140): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#14 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#15 .../index.php(57): Tinebase_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Apr 2012 14:04**

this happens in the demo. do we need to compress the data?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 14 May 2012 12:47**

the user doesn&#039;t recognize this problem =&gt; solve in joey

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2013 13:35**

state needs to be splitted by state_id
