### ISSUE TITLE
0006376:
Moving a contact from one addressbook to an other fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3239]
**Reported by jan on 2 May 2012 19:48**

**Version:** Milan (2012-03-2)

When a contact is moved from one addressbook to another, the contact gets:

1.) marked as deleted in db (is_deleted = 1)
2.) created again with same id

This results in a Integrity constraint violation

**Steps to reproduce:** Create two CardDAV addressbooks in TB with SOGo Connector
Move a contact from one addressbook to the other

**Additional information:** 2b2d7 Schneider, Jan - 2012-05-02T19:33:53+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::451 exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;438&#039; for key &#039;PRIMARY&#039;&#039; in /var/www/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/tine20/Tinebase/Backend/Sql/Abstract.php(760): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_addressb...&#039;, Array)
#5 /var/www/tine20/Addressbook/Backend/Sql.php(104): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#6 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(420): Addressbook_Backend_Sql-&gt;create(Object(Addressbook_Model_Contact))
#7 /var/www/tine20/Addressbook/Frontend/WebDAV/Contact.php(74): Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact), false)
#8 /var/www/tine20/Tinebase/WebDav/Container/Abstract.php(66): Addressbook_Frontend_WebDAV_Contact::create(Object(Tinebase_Model_Container), &#039;438.vcf&#039;, Resource id #256)
#9 /var/www/tine20/library/Sabre/DAV/Server.php(1430): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;438.vcf&#039;, Resource id #256)
#10 /var/www/tine20/library/Sabre/DAV/Server.php(833): Sabre_DAV_Server-&gt;createFile(&#039;addressbooks/2/...&#039;, Resource id #256)
#11 [internal function]: Sabre_DAV_Server-&gt;httpPut(&#039;addressbooks/2/...&#039;)
#12 /var/www/tine20/library/Sabre/DAV/Server.php(454): call_user_func(Array, &#039;addressbooks/2/...&#039;)
#13 /var/www/tine20/library/Sabre/DAV/Server.php(201): Sabre_DAV_Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;addressbooks/2/...&#039;)
#14 /var/www/tine20/Tinebase/Server/WebDAV.php(90): Sabre_DAV_Server-&gt;exec()
#15 /var/www/tine20/Tinebase/Core.php(235): Tinebase_Server_WebDAV-&gt;handle()
#16 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#17 {main}
2b2d7 Schneider, Jan - 2012-05-02T19:33:53+00:00 DEBUG (7): Sabre_DAV_Server::exec::205 webdav exception SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;438&#039; for key &#039;PRIMARY&#039;
2b2d7 Schneider, Jan - 2012-05-02T19:33:53+00:00 DEBUG (7): Sabre_DAV_Server::exec::207 webdav exception stacktrace #0 /var/www/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/tine20/Tinebase/Backend/Sql/Abstract.php(760): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_addressb...&#039;, Array)
#5 /var/www/tine20/Addressbook/Backend/Sql.php(104): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#6 /var/www/tine20/Tinebase/Controller/Record/Abstract.php(420): Addressbook_Backend_Sql-&gt;create(Object(Addressbook_Model_Contact))
#7 /var/www/tine20/Addressbook/Frontend/WebDAV/Contact.php(74): Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact), false)
#8 /var/www/tine20/Tinebase/WebDav/Container/Abstract.php(66): Addressbook_Frontend_WebDAV_Contact::create(Object(Tinebase_Model_Container), &#039;438.vcf&#039;, Resource id #256)
#9 /var/www/tine20/library/Sabre/DAV/Server.php(1430): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;438.vcf&#039;, Resource id #256)
#10 /var/www/tine20/library/Sabre/DAV/Server.php(833): Sabre_DAV_Server-&gt;createFile(&#039;addressbooks/2/...&#039;, Resource id #256)
#11 [internal function]: Sabre_DAV_Server-&gt;httpPut(&#039;addressbooks/2/...&#039;)
#12 /var/www/tine20/library/Sabre/DAV/Server.php(454): call_user_func(Array, &#039;addressbooks/2/...&#039;)
#13 /var/www/tine20/library/Sabre/DAV/Server.php(201): Sabre_DAV_Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;addressbooks/2/...&#039;)
#14 /var/www/tine20/Tinebase/Server/WebDAV.php(90): Sabre_DAV_Server-&gt;exec()
#15 /var/www/tine20/Tinebase/Core.php(235): Tinebase_Server_WebDAV-&gt;handle()
#16 /var/www/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#17 {main}

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 14 May 2012 12:45**

this is already solved in calendar, there is a move function implemented in tree

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 May 2012 13:16**

implement &quot;real&quot; move request / function.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Jul 2012 14:59**

see https://gerrit.tine20.org/tine20/#/c/636/
