### ISSUE TITLE
0006384:
Can't update - Fix error in setup

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3243]
**Reported by kaystrobach on 3 May 2012 14:32**

**Version:** Milan (2012-03-2)

I can&#039;t update from Maischa -&gt; Milan :( -&gt; replaying backup ... grr again ;)

**Steps to reproduce:** php setup.php --update

the first rounds work well, but it fails from the 5.0 version point :(

**Additional information:** 346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Tinebase_Core::setupLogger::481 Logger initialized
346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Tinebase_Core::setupCache::559 cache disabled
346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Tinebase_Core::setSessionBackend::761 Session of backend type &#039;File&#039; configured.
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::908 given localeString &#039;auto&#039;
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Translation::getLocale::195 given localeString &#039;auto&#039;
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Translation::getLocale::207 &#039;en_US&#039; is not supported, checking fallback
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Translation::getLocale::230 selected locale: &#039;en&#039;
346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Tinebase_Core::setupUserLocale::947 Setting user locale: en
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::959 Setting CTYPE locale from &quot;en_US&quot; to &quot;en_US.UTF8&quot;.
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Setup_Server_Cli::handle::84 Is cli request. method: EMPTY
346be -- none -- - 2012-05-03T14:29:22+00:00 DEBUG (7): Tinebase_Record_RecordSet::_getMatchingRecords::545 filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Setup_Controller::updateApplication::398 Executing updates for Tasks (starting at 5.0)
346be -- none -- - 2012-05-03T14:29:22+00:00 INFO (6): Setup_Controller::updateApplication::422 Updating Tasks - update_0
346be -- none -- - 2012-05-03T14:29:22+00:00 ERR (3): Setup_Controller::updateApplication::432 SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./db1049038@002dtine20/tine20_tasks&#039; to &#039;./db1049038@002dtine20/#sql2-cd0-52440&#039; (errno: 152)
346be -- none -- - 2012-05-03T14:29:22+00:00 ERR (3): Setup_Controller::updateApplication::433 #0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Backend/Abstract.php(370): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Tasks/Setup/Update/Release5.php(22): Setup_Backend_Abstract-&gt;dropForeignKey(&#039;tasks&#039;, &#039;tasks::status_i...&#039;)
#6 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Controller.php(426): Tasks_Setup_Update_Release5-&gt;update_0()
#7 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Controller.php(325): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;5&#039;)
#8 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Frontend/Cli.php(215): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Frontend/Cli.php(54): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#10 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Server/Cli.php(88): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#11 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/Setup/Core.php(103): Setup_Server_Cli-&gt;handle()
#12 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps/tine20/setup.php(53): Setup_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
Related to #3297

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 4 May 2012 15:21**

mhmm what about a database integrity check?

perhaps you know TYPO3, there we have a tool (installtool &gt; db &gt; compare) which allows us to show the difference between the database and the expected database scheme for a given version ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 09:36**

something is strange with your foreign key constraints of the tasks table. could you please check this?

SHOW CREATE TABLE [tine20_]tasks;

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 10:06**

for sure - thanks ;)

CREATE TABLE `tine20_tasks` (
 `id` varchar(40) NOT NULL,
 `container_id` int(11) unsigned DEFAULT NULL,
 `created_by` varchar(40) DEFAULT NULL,
 `creation_time` datetime DEFAULT NULL,
 `last_modified_by` varchar(40) DEFAULT NULL,
 `last_modified_time` datetime DEFAULT NULL,
 `is_deleted` tinyint(1) unsigned DEFAULT &#039;0&#039;,
 `deleted_by` varchar(40) DEFAULT NULL,
 `deleted_time` datetime DEFAULT NULL,
 `percent` tinyint(4) unsigned DEFAULT NULL,
 `completed` datetime DEFAULT NULL,
 `due` datetime DEFAULT NULL,
 `class` varchar(40) NOT NULL DEFAULT &#039;PUBLIC&#039;,
 `description` longtext,
 `geo` double unsigned DEFAULT NULL,
 `location` varchar(255) DEFAULT NULL,
 `organizer` varchar(40) DEFAULT NULL,
 `originator_tz` varchar(255) DEFAULT NULL,
 `priority` int(11) unsigned DEFAULT NULL,
 `status_id` int(11) unsigned DEFAULT NULL,
 `summary` varchar(255) DEFAULT NULL,
 `url` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `container_id` (`container_id`),
 KEY `organizer` (`organizer`),
 KEY `status_id` (`status_id`),
 KEY `class` (`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 10:50**

ah, no foreign key set ... trying to fix this.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 12:05**

mhmm, do you think it&#039;s realistic to build such a database health check?

e.g.

 - check if all tables are available (if not show missing table)
 - iterate over all tables and check integrity, show differences

Libs:
 - http://pear.php.net/package/SQL_Parser/download/0.6.0/

Example:
 - http://api.typo3.org/typo3v4/45/html/classt3lib__install.html
 -&gt; http://www.typo3forum.net/forum/attachments/typo3-4-x-installation-updates/1988d1264083007t-4-2-4-3-update-database-compare-funktioniert-t3screen1.jpg

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 12:05**

which foreign key is needed?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 12:16**

- health check sounds like a good idea, please add a feature request with the infos from your note (https://forge.tine20.org/mantisbt/view.php?id=6384#c7418)

- the fk is tasks::status_id--tasks_status::id
-&gt; in the update script it is dropped, so if it did not exist, the exception is catched now ... fix is comming to the git repo in a few minutes ;)

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 12:20**

thanks

i&#039;ve created the feature request -&gt; #6408

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 14:50**

thx.

you can test the update with the attached changeset file (Release5.php).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 15:05**

Integrated in tine20:1,736  ( See http://ci.tine20.org/job/tine20/1736/ ).

Revision/Changeset: b6510decb82d2b2617adcc7346868c381d9e3fa3 
Author: Philipp Schüle
Log: 
 #6384: Can&#039;t update - Fix error in setup
Changed paths:
 tests/tine20/Tinebase/TagsTest.php
 tine20/Tasks/Setup/Update/Release5.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 May 2012 16:57**

should work now. please reopen if you still run into problems.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 24 May 2012 05:33**

sry, for late response, it works in general, but i need to open a new ticket for upgrading felamimail 5.0 to 5.6 ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: 1267f8ca5be252d422f0025dae7c7e3a4dfae600 
Author: Philipp Schüle
Log: 
 #6384: Can&#039;t update - Fix error in setup
Changed paths:
 tests/tine20/Tinebase/TagsTest.php
 tine20/Tasks/Setup/Update/Release5.php
