### ISSUE TITLE
0006400:
Occasionally occuring: Attempt to request a privileged Json-API method (Felamimail.updateMessageCache) without authorisation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3250]
**Reported by weberho on 5 May 2012 06:38**

**Version:** Milan (2012-03-2)

4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Core::setupLogger::481 Logger initialized
4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Core::setupCache::547 cache of backend type &#039;File&#039; enabled
4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Core::setSessionBackend::761 Session of backend type &#039;File&#039; configured.
4c567 -- none -- - 2012-05-05T06:28:43+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::96 Using credential cache apapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
4c567 -- none -- - 2012-05-05T06:28:43+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::908 given localeString &#039;auto&#039;
4c567 -- none -- - 2012-05-05T06:28:43+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::917 session value: de
4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Core::setupUserLocale::947 Setting user locale: de
4c567 -- none -- - 2012-05-05T06:28:43+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::959 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
4c567 -- none -- - 2012-05-05T06:28:43+00:00 DEBUG (7): Tinebase_Server_Json::handle::65 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Felamimail.updateMessageCache
            [params] =&gt; Array
                (
                    [folderId] =&gt; c9285e74d7e14f3c865c3658dd75a6aea9bd0bbd
                    [time] =&gt; 120
                )

            [id] =&gt; 686
        )

)

4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Server_Json::_handle::96 is JSON request. method: Felamimail.updateMessageCache
4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): Tinebase_Server_Json::_checkJsonKey::308 Attempt to request a privileged Json-API method (Felamimail.updateMessageCache) without authorisation from &quot;93.82.3.253&quot;. (session timeout?)
4c567 -- none -- - 2012-05-05T06:28:43+00:00 NOTICE (5): Tinebase_Server_Json::_handleException::161 Tinebase_Exception_AccessDenied -&gt; Not Authorised
4c567 -- none -- - 2012-05-05T06:28:43+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::228 #0 .../Tinebase/Server/Json.php(99): Tinebase_Server_Json-&gt;_checkJsonKey(&#039;Felamimail.upda...&#039;, &#039;d8398dedfff4c49...&#039;)
#1 .../Tinebase/Server/Json.php(76): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server), Object(Zend_Json_Server_Request))
#2 .../Tinebase/Core.php(235): Tinebase_Server_Json-&gt;handle()
#3 .../index.php(57): Tinebase_Core::dispatchRequest()
#4 {main}
4c567 -- none -- - 2012-05-05T06:28:43+00:00 INFO (6): index.php (75) TIME: 0.10141086578369 seconds  MEMORY: 7.5 MBytes  REALPATHCACHESIZE: 0

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 May 2012 13:38**

could this be an ordinary session timeout?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 7 May 2012 04:46**

YOu are right, that could be a browser with an invalid, open session.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 May 2012 07:56**

i do not think we can do something about this ... perhaps the log message should be clarified.
