### ISSUE TITLE
0006486:
fix testDetachTagsFromMultipleRecords

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3292]
**Reported by pschuele on 18 May 2012 21:03**

**Version:** Milan (2012-03-2)

fix testDetachTagsFromMultipleRecords

- it causes modlog errors

**Additional information:** exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;4bddd6ae871e92fd078882971059ffcba7930284-4d2509ce8f37236e259a703&#039; for key &#039;unique-fields&#039;&#039; in /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Statement/Pdo.php:238
     [exec] Stack trace:
     [exec] #0 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
     [exec] #1 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
     [exec] #2 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
     [exec] #3 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
     [exec] #4 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/library/Zend/Db/Table/Abstract.php(1047): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_timemach...&#039;, Array)
     [exec] #5 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Tinebase/Timemachine/ModificationLog.php(233): Zend_Db_Table_Abstract-&gt;insert(Array)
     [exec] #6 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Tinebase/Timemachine/ModificationLog.php(416): Tinebase_Timemachine_ModificationLog-&gt;setModification(Object(Tinebase_Model_ModificationLog))
     [exec] #7 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Tinebase/Timemachine/ModificationLog.php(469): Tinebase_Timemachine_ModificationLog-&gt;_loopModifications(Array, Object(Tinebase_Model_ModificationLog), Object(Tinebase_Record_RecordSet), Array)
     [exec] #8 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Tinebase/Controller/Record/Abstract.php(820): Tinebase_Timemachine_ModificationLog-&gt;writeModLogMultiple(Array, Array, Array, &#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array)
     [exec] #9 /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Tinebase/Tags.php(652): Tinebase_Controller_Record_Abstract-&gt;concurrencyManagementAndModlogMultiple(Array, Array, Array)
     [exec] #10 /var/lib/jenkins/jobs/tine20gerrit/workspace/tests/tine20/Tinebase/TagsTest.php(223): Tinebase_Tags-&gt;detachTagsFromMultipleRecords(Object(Addressbook_Model_ContactFilter), Array)
     [exec] #11 [internal function]: Tinebase_TagsTest-&gt;testDetachTagsFromMultipleRecords()
     [exec] #12 /usr/share/php/PHPUnit/Framework/TestCase.php(822): ReflectionMethod-&gt;invokeArgs(Object(Tinebase_TagsTest), Array)
     [exec] #13 /usr/share/php/PHPUnit/Framework/TestCase.php(706): PHPUnit_Framework_TestCase-&gt;runTest()
     [exec] #14 /usr/share/php/PHPUnit/Framework/TestResult.php(687): PHPUnit_Framework_TestCase-&gt;runBare()
     [exec] #15 /usr/share/php/PHPUnit/Framework/TestCase.php(653): PHPUnit_Framework_TestResult-&gt;run(Object(Tinebase_TagsTest))
     [exec] #16 /usr/share/php/PHPUnit/Framework/TestSuite.php(757): PHPUnit_Framework_TestCase-&gt;run(Object(PHPUnit_Framework_TestResult))
     [exec] #17 /usr/share/php/PHPUnit/Framework/TestSuite.php(732): PHPUnit_Framework_TestSuite-&gt;runTest(Object(Tinebase_TagsTest), Object(PHPUnit_Framework_TestResult))
     [exec] #18 /usr/share/php/PHPUnit/Framework/TestSuite.php(675): PHPUnit_Framework_TestSuite-&gt;run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
     [exec] #19 /usr/share/php/PHPUnit/Framework/TestSuite.php(675): PHPUnit_Framework_TestSuite-&gt;run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
     [exec] #20 /usr/share/php/PHPUnit/TextUI/TestRunner.php(350): PHPUnit_Framework_TestSuite-&gt;run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
     [exec] #21 /usr/share/php/PHPUnit/TextUI/Command.php(214): PHPUnit_TextUI_TestRunner-&gt;doRun(Object(PHPUnit_Framework_TestSuite), Array)
     [exec] #22 /usr/share/php/PHPUnit/TextUI/Command.php(147): PHPUnit_TextUI_Command-&gt;run(Array, true)
     [exec] #23 /usr/bin/phpunit(52): PHPUnit_TextUI_Command::main()
     [exec] #24 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 May 2012 09:31**

Integrated in tine20:1,765  ( See http://ci.tine20.org/job/tine20/1765/ ).

Revision/Changeset: b995e90652374d28d177c46c5c5426d7ec82b0b3 
Author: Philipp Schüle
Log: 
 #6486: fix testDetachTagsFromMultipleRecords
Changed paths:
 tine20/Tinebase/Tags.php
 tests/tine20/Tinebase/TagsTest.php
 tine20/Tinebase/Timemachine/ModificationLog.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jul 2012 11:28**

Integrated in tine20:1,865  ( See http://ci.tine20.org/job/tine20/1865/ ).

Revision/Changeset: b5e0371570683c0f8da9ba6028bea8e95a613f31 
Author: Philipp Schüle
Log: 
 #6486: fix testDetachTagsFromMultipleRecords
Changed paths:
 tine20/Tinebase/Tags.php
 tests/tine20/Tinebase/TagsTest.php
 tine20/Tinebase/Timemachine/ModificationLog.php
