### ISSUE TITLE
0006496:
ActiveSync 5.0 to 5.8 Update fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3297]
**Reported by kaystrobach on 24 May 2012 05:39**

is related to #0006384

I upgraded like described here:

http://www.tine20.org/wiki/index.php/Update_Howto

php setup.php --update

**Additional information:** CMD:

user@host:/tine_path/tine20$ clear
user@host:/tine_path/tine20$ php setup.php --update
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./database@002dtine20/tine20_acsync_synckey&#039; to &#039;./database@002dtine20/#sql2-6988-52b28&#039; (errno: 152)&#039; in /tine_path/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /tine_path/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /tine_path/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /tine_path/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /tine_path/tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /is/htdocs/w in /tine_path/tine20/library/Zend/Db/Statement/Pdo.php on line 238

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./database@002dtine20/tine20_acsync_synckey&#039; to &#039;./database@002dtine20/#sql2-6988-52b28&#039; (errno: 152)&#039; in /tine_path/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /tine_path/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /tine_path/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /tine_path/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /tine_path/tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /is/htdocs/w in /tine_path/tine20/library/Zend/Db/Statement/Pdo.php on line 238
user@host:/tine_path/tine20$

-----------------------------------------
WEB:

SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./dbuser@002dtine20/tine20_acsync_synckey&#039; to &#039;./dbuser@002dtine20/#sql2-6988-52dc6&#039; (errno: 152)
.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Setup/Backend/Abstract.php(370): Setup_Backend_Abstract-&gt;execQueryVoid()
.../ActiveSync/Setup/Update/Release5.php(28): Setup_Backend_Abstract-&gt;dropForeignKey()
.../Setup/Controller.php(426): ActiveSync_Setup_Update_Release5-&gt;update_0()
.../Setup/Controller.php(325): Setup_Controller-&gt;updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications()
.../library/Zend/Server/Abstract.php(232): Setup_Frontend_Json-&gt;updateApplications()
.../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle()
.../Setup/Core.php(103): Setup_Server_Json-&gt;handle()
.../setup.php(53): Setup_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 24 May 2012 06:14**

solution:

uninstall active sync temporarly
update felamimail
install active sync
