### ISSUE TITLE
0006778:
Update von 6.2 auf 6.3 scheitert

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3437]
**Reported by GWI on 18 Jul 2012 18:46**

**Version:** git master

Beim Update von Tinebase von 6.2 auf 6.3 kommt ein Fehler
das die Spalte &quot;model&quot; schon vorhanden ist.

Das erste Update Brach mit einer Fehlermeldung ab und
ein erneutes Update brachte den Fehler das &quot;model&quot; schon
vorhanden ist.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 18 Jul 2012 18:49**

INFO (6): Tinebase_Core::setExecutionLifeTime::1070 setting execution life time to: 0
INFO (6): Setup_Controller::updateApplications::314 Updating Tinebase to version 6.3
INFO (6): Setup_Controller::updateApplication::398 Executing updates for Tinebase (starting at 6.2)
INFO (6): Setup_Controller::updateApplication::422 Updating Tinebase - update_2
ERR (3): Setup_Controller::updateApplication::432 SQLSTATE[42S21]: Column already exists: 1060 Doppelter Spaltenname: &#039;model&#039;
ERR (3): Setup_Controller::updateApplication::433 
#0 ***/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 ***/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 ***/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 ***/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 ***/Setup/Backend/Mysql.php(185): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 ***/Tinebase/Setup/Update/Release6.php(56): Setup_Backend_Mysql-&gt;addCol(&#039;container&#039;, Object(Setup_Backend_Schema_Field_Xml))
#6 ***/Setup/Controller.php(426): Tinebase_Setup_Update_Release6-&gt;update_2()
#7 ***/Setup/Controller.php(317): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;6&#039;)
#8 ***/Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 ***/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 ***/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 ***/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 ***/Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 ***/Setup/Core.php(101): Setup_Server_Json-&gt;handle()
#15 ***/setup.php(53): Setup_Core::dispatchRequest()
#16 {main}
NOTICE (5): Tinebase_Server_Json::_handleException::223 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S21]: Column already exists: 1060 Doppelter Spaltenname: &#039;model&#039;
NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::290 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 .../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 .../Setup/Backend/Mysql.php(185): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 .../Tinebase/Setup/Update/Release6.php(56): Setup_Backend_Mysql-&gt;addCol(&#039;container&#039;, Object(Setup_Backend_Schema_Field_Xml))
#6 .../Setup/Controller.php(426): Tinebase_Setup_Update_Release6-&gt;update_2()
#7 .../Setup/Controller.php(317): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;6&#039;)
#8 .../Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#10 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 .../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#14 .../Setup/Core.php(101): Setup_Server_Json-&gt;handle()
#15 .../setup.php(53): Setup_Core::dispatchRequest()
#16 {main}
acbd7 -- none -- - 2012-07-18T18:43:40+00:00 INFO (6): Tinebase_Core::setupLogger::523 Logger initialized

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 19 Jul 2012 06:16**

There is also problem with updating if some of applications that are to be updated with model are not installed.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Jul 2012 11:32**

Integrated in tine20:1,894  ( See http://ci.tine20.org/job/tine20/1894/ ).

Revision/Changeset: 41e12c1538a27199e500be223bd3a07ed9453b82 
Author: Philipp Schüle
Log: 
 #6778: Update von 6.2 auf 6.3 scheitert
Changed paths:
 tine20/Tinebase/Setup/Update/Release6.php

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 19 Jul 2012 12:06**

sollte soweit wieder funktionieren. bei euch auch? könnt ja mal testen.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 19 Jul 2012 18:14**

BINGO Update Funzt und Tine rennt wieder.

Ready to Close
