### ISSUE TITLE
0006884:
Could not create Table

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3490]
**Reported by GWI on 4 Aug 2012 21:46**

**Version:** git master

Beim Aktivieren von HR kann das Setup die Tabelle *_humanresources_contract
nicht anlegen

**Additional information:** INFO (6): Setup_Controller::installApplications::1230 Installing applications: Array
(
    [0] =&gt; HumanResources
)

NOTICE (5): Tinebase_Server_Json::_handleException::223 Tinebase_Exception_Backend_Database -&gt; Could not create table: SQLSTATE[HY000]: General error: 1005 Kann Tabelle &#039;datacenter.tine20_humanresources_contract&#039; nicht erzeugen (Fehler: 150)
NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::290 #0 .../Setup/Controller.php(1233): Setup_Controller-&gt;_installApplication(Object(SimpleXMLElement), NULL)
#1 .../Setup/Frontend/Json.php(91): Setup_Controller-&gt;installApplications(Array, NULL)
#2 [internal function]: Setup_Frontend_Json-&gt;installApplications(Array, NULL)
#3 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 .../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#7 .../Setup/Core.php(101): Setup_Server_Json-&gt;handle()
#8 .../setup.php(53): Setup_Core::dispatchRequest()
#9 {main}

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 6 Aug 2012 15:36**

Hallo, ich kann das gerade nicht nachvollziehen. Eigentlich sollte die app gar nicht aktiviert werden müssen, sondern erscheinen, sobald sie aktiviert ist. 

Ist Sales auch installiert? In der aktuellen Version?

**Comment by Gloirin** [comment]
**Comment posted by GWI on 7 Aug 2012 09:16**

Also Sales ist in unserer GIT Version Aktiv, Version 6.1

HR erscheint als Uninstalled, beim &quot;Anwendung Installieren&quot; kommt
der Abbruch das die Tabelle nicht anlegen kann.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 7 Aug 2012 09:17**

Bin gerade unterwegs und werde mal heut Abend ein paar Pics 
machen.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 12 Aug 2012 20:50**

Bilder!!

Bild 1 ist das Setup
Wenn ich HR versuche zu Installieren erzeugt er die
Fehlermeldung in Bild 2

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2012 12:57**

leider hat im master (joey) ein update script gefehlt.

nun sollte es aber klappen.

@sven: bitte mal testen :)

**Comment by Gloirin** [comment]
**Comment posted by GWI on 22 Aug 2012 20:37**

JUPP, rennt wieder. install geht sauber über die bühne.

Ist HR schon benutzbar?? Wenn ich nen Mitarbeiter anlege erscheint
einmalig die auswahlbox bei &quot;Benutzerkonto&quot; und dann nie wieder.

Ansonsten schöner Schritt in Richtung KillerApp

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Aug 2012 07:42**

HR sollte eigentlich schon benutzbar sein.

aber wenn dir fehler/komische sachen auffallen, gern ein ticket dafür anlegen.

ich bin leider nicht so ganz im thema drin, aber die anderen jungs können sicher helfen ... ;)
