### ISSUE TITLE
0007090:
Activesync emails show up twice.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3592]
**Reported by Gurney on 13 Sep 2012 13:21**

**Version:** git master

Lars has already the log.

It seems that mails are synced two times:
- once by synchrotron
- then by &quot;AirsyncBase:data&quot;.

Using the Activesync version with HeartBeat.

**Comment by Gloirin** [comment]
Related to #3462

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 19 Oct 2012 14:41**

It happens also with:
- tasks
- calendar events

and it&#039;s probably related to #7050

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 23 Oct 2012 07:23**

Something has changed since Friday evening.

Calendar sync is proper now. No doubles/triples anymore.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 23 Oct 2012 08:48**

Could be because of this change:
http://git.tine20.org/git?p=tine20;a=commitdiff;h=f49567fde8ada4dd6c719c1226c3974f7f3452b7

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 23 Oct 2012 08:54**

Could be ! That fits with the dates :)

Maybe taht&#039;s something to replicate in the other Activesync apps (mail, tasks).

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 3 Dec 2012 09:41**

I found that in the error log from the webserver :

[Mon Dec 03 09:06:07 2012] [error] [client 192.168.0.41] PHP Fatal error:  Uncaught exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: Invalid character at line 3&#039; in /media/server/www/tine20/tine20/library/Syncroton/lib/Syncroton/Wbxml/Encoder.php:164
Stack trace:
#0 /media/server/www/tine20/tine20/library/Syncroton/lib/Syncroton/Server.php(184): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /media/server/www/tine20/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#2 /media/server/www/tine20/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#3 /media/server/www/tine20/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#4 /media/server/www/tine20/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#5 {main}
  thrown in /media/server/www/tine20/tine20/library/Syncroton/lib/Syncroton/Wbxml/Encoder.php on line 164

**Comment by Gloirin** [comment]
**Comment posted by HarryMe on 25 Dec 2012 22:56**

This happens with all of my Android devices (Galaxy S3 and Galaxy Note 2 and Iconia A501). I am running Tine 2.0 on a Synology NAS and I think the problem has something to do with the encoding of the respective mails. I know you changed something in Joey for making ISO -1 and -15 encoded mails to show up correctly.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jan 2013 16:05**

some more information about this bug from HarryMe: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11912#p45532

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 12 Mar 2013 16:29**

Please replace  library/Syncroton/lib/Syncroton/Command/Sync.php with attached Sync.php and report back if the problem has gone.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 13 Mar 2013 12:59**

Not sure whether it has been pushed yet to the GIT or not, but I still have the problem with this morning&#039;s GIT snapshot.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 14 Mar 2013 06:48**

It&#039;s pushed to git. Please update to latest stable git branch or master.

Then please send me an update logfile, which contains the email which got duplicated on the phone.

Btw: What kind of phone do you use?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 14 Mar 2013 13:22**

Hi Lars,

It&#039;s not in the current Git? Say, if I &quot;git pull&quot; now, I won&#039;t have the proper Sync file ?

Should I use the attached Sync file instead ?

I&#039;m using a Galaxy S3 4.1.2

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 14 Mar 2013 14:36**

I&#039;ve tried with the attached Sync.php in latest Git Pull and it seems to work indeed! :)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 14 Mar 2013 15:59**

That&#039;s great to know. So we have finally solved the problem.
