### ISSUE TITLE
0007128:
sync_accounts_from_ldap throws exception about duplicate entry "admin"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3611]
**Reported by HubertB on 20 Sep 2012 08:40**

**Version:** Joey (2012.10.1~beta1)

I&#039;m using LDAP as account backend and I added some test users using phpldapadmin. The test users can log in via SSH and receive &amp; sent email so I don&#039;t expect a problem here.

Googling revealed that I&#039;m supposed to run
# php setup.php --sync_accounts_from_ldap

But this gives the following output:
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;admin&#039; for key &#039;name&#039;&#039; in /var/www/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/library/Zend/Db/Table/Abstract.php(1047): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_groups&#039;, Array)
#5 /var/www/Tinebase/Group/Sql.php(408): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /var/www/Tinebase/Group.php(239): Tinebase_Group_Sql-&gt;addGroupInSqlBackend(Object(Tinebase_Model_Group))
#7 /var/www/Setup/Frontend/Cli.php(284): Tinebase_Group::syncGroups()
#8 /var/www/Setup/Fr in /var/www/library/Zend/Db/Statement/Pdo.php on line 238

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;admin&#039; for key &#039;name&#039;&#039; in /var/www/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/library/Zend/Db/Table/Abstract.php(1047): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_groups&#039;, Array)
#5 /var/www/Tinebase/Group/Sql.php(408): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /var/www/Tinebase/Group.php(239): Tinebase_Group_Sql-&gt;addGroupInSqlBackend(Object(Tinebase_Model_Group))
#7 /var/www/Setup/Frontend/Cli.php(284): Tinebase_Group::syncGroups()
#8 /var/www/Setup/Fr in /var/www/library/Zend/Db/Statement/Pdo.php on line 238

**Steps to reproduce:** 1. Have tine20 use LDAP as account backend
2. Add new users to the LDAP using e.g. phpldapadmin
3. Run &quot;php setup.php --sync_accounts_from_ldap&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Nov 2012 12:04**

could you please post the group ids in ldap and in the tine db. they seem to be out of sync.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 7 Nov 2012 11:25**

Hi! The entryUUID of the &quot;admin&quot; group indeed differs. I think this is caused by the fact that the LDAP server used by Tine 2.0 is not participating in the sync/repl-cluster because Tine 2.0 is more or less a test installation and I wanted to be on the save side (cf. http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=9852).

Instead, the sync between the LDAP server has been done manually with a script that actually removed the entryUUID. Thus, the LDAP server used by Tine 2.0 created new ones on each data import, which then in turn was imported/synced to Tine 2.0.

Thus, the whole thing might be actually my fault. Sorry!

Is there an elegant way to resolve this? I tried deleting the group in question using Tine 2.0&#039;s web interface in order to re-sync it with LDAP again, but it reports that &quot;Some error&quot; occured.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Nov 2012 11:45**

hm, then it would be good to know what &quot;Some error&quot; exactly is. perhaps you would need to switch the accounts backend to Sql, delete the group and switch back to LDAP afterwards to make this work.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 7 Nov 2012 19:00**

Hi again!

Here is a stack trace from the log file when I try to delete the &quot;admin&quot; group:

 e88cd tine20admin - 2012-11-07T18:56:02+00:00 WARN (4): Tinebase_Server_Json::_handleException::226 Tinebase_Exception_Backend -&gt; SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`tine20`.`tine20_accounts`, CONSTRAINT `tine20_accounts::primary_group_id--groups::id` FOREIGN KEY (`primary_group_id`) REFERENCES `tine20_groups` (`id`))
 e88cd tine20admin - 2012-11-07T18:56:02+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::293 #0 .../Admin/Controller/Group.php(369): Tinebase_Group_Sql-&gt;deleteGroups(Array)
#1 .../Admin/Frontend/Json.php(659): Admin_Controller_Group-&gt;delete(Array)
#2 [internal function]: Admin_Frontend_Json-&gt;deleteGroups(Array)
#3 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 .../Tinebase/Server/Json.php(203): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#9 .../index.php(17): Tinebase_Core::dispatchRequest()
#10 {main}

I assume this error pops up because the user &quot;tine20admin&quot; is a member of the &quot;admin&quot; group and the &quot;tine20admin&quot; account is also listed under https://&lt;your URL here&gt;/setup in the &quot;Authentication/Accounts&quot; -&gt; &quot;Account storage&quot; section.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 7 Nov 2012 19:42**

Update: Switching the backend to SQL in order to be able to delete the group did not work either.

I just tried to fix it with a &quot;hammer&quot; (never mind):
1. Stop Apache
2. Dump the mysql data
3. Search &amp; Replace the entryUUID with the correct one
4. Restore the dump
5. Start Apache
6. Do a fresh sync (&quot;php setup.php --sync_accounts_from_ldap&quot;)
7. System works like a charm

If you need further help / reports with the stack backtrace reported above by me, let me know. I created a backup of the mysql dump before search-and-replacing, so I can revert back to the original situation.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Nov 2012 20:19**

ah, ok ... the primary group has been the problem. you could have changed the (primary) group memberships of the user and delete the group afterwards.

but your &quot;hammer&quot; is a good solution, too :)

i&#039;ll create a task for solving the &quot;primary group delete&quot; and close this one.

thanks for reporting and testing :)
