### ISSUE TITLE
0007158:
activesync mit Windows Phone 7.5 causes Zend_Db_Statement_Exception

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3626]
**Reported by Olodin on 26 Sep 2012 20:41**

**Version:** Joey (2012.10.1~beta2)

Just got a new Nokia Lumia 710 with Windows Phone 7.5 and tried to setup activesync.

But I get this error in apache error log:

[Wed Sep 26 22:34:06 2012] [error] [client 192.168.97.161] PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1366 Incorrect string value: &#039;\\x86\\x0BM\\x0B\\x86\\xE0...&#039; for column &#039;deviceid&#039; at row 1&#039; in /usr/local/www/tine20migrationstest/library/Zend/Db/Statement/Pdo.php:238\nStack trace:\n#0 /usr/local/www/tine20migrationstest/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)\n#1 /usr/local/www/tine20migrationstest/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)\n#2 /usr/local/www/tine20migrationstest/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)\n#3 /usr/local/www/tine20migrationstest/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)\n#4 /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Backend/ABackend.php(56): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_acsync_d...&#039;, Array)\n#5 /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncrot in /usr/local/www/tine20migrationstest/library/Zend/Db/Statement/Pdo.php on line 238

These are the last lines of trace log:
2012-09-26T20:20:45+00:00 DEBUG (7): Syncroton_Server::_handlePost::89 REQUEST Array
(   
    [protocolVersion] =&gt; 141
    [command] =&gt; FolderSync
    [deviceId] =&gt; ~F^KM^K~F?^C~T/^OB??w
  [deviceType] =&gt; WP
  [saveInSent] =&gt;
  [collectionId] =&gt;
  [itemId] =&gt;
  [attachmentName] =&gt;
  [userAgent] =&gt; WP
  [policyKey] =&gt;
  [contentType] =&gt; application/vnd.ms-sync
)

The account setup on the phone stops with an error and nothing can be synced.

Any idea?

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11586

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Sep 2012 08:17**

the device id seems to contain invalid chars. maybe we should convert it to utf-8 or filter those chars.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 27 Sep 2012 08:34**

I tested this with Milan 2012.03.6: there it works. And the device is listed in my favorites and can be used as Active Sync filter.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Sep 2012 08:50**

ok, thanks for testing. lars will have a look at this.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 27 Sep 2012 08:58**

Can you please post the entry from the access_log, when the phone try&#039;s to sync folders?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 27 Sep 2012 16:21**

This is the access log when trying to sync:
[27/Sep/2012:17:56:35 +0200] &quot;OPTIONS /Microsoft-Server-ActiveSync?                                                                    *User=testuser&amp;DeviceId=860B4D0B86E0CB03F1942F0F42F0DA77&amp;DeviceType=WindowsPhone HTTP/1.1&quot; 200 - &quot;-&quot; &quot;MSFT-WP/7.10.8773&quot;
[27/Sep/2012:17:56:36 +0200] &quot;POST /Microsoft-Server-ActiveSync?jQkHBBCGC00LhuDLA/GULw9C8Np3BAAAAAACV1A= HTTP/1.1&quot; 200 1173 &quot;-         *&quot; &quot;-&quot;

Immediately after that there is no more communication and the error 8501001D is shown on the phone.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 28 Sep 2012 09:36**

That helps. Decoding  the get parameter of /Microsoft-Server-ActiveSync?jQkHBBCGC00LhuDLA/GULw9C8Np3BAAAAAACV1A= fails somehow. In the options request before we can see the expected deviceid.

I&#039;ll check this.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 30 Sep 2012 09:57**

This bugs prevents me from testing all other ActiveSync features with Windows Phone 7.5. 
Since we are currently evaluating alternatives for our aged webOS devices a fix would really be helpful.
Testing with Trunk from git is also no problem :)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 3 Oct 2012 04:10**

The device sends a very strange deviceid. The code seems to be correct. I can&#039;t find any problem. But the decoded deviceid is just garbage.

Just don&#039;t know to handle this.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 3 Oct 2012 06:34**

I&#039;ll try again with a fresh install, maybe this helps somehow.

Since sync with Milan and Windows Phone 7.5 also does not work correctly (see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11096&amp;start=10) I&#039;m stuck :(

Over in this thread I attached a inital sync debug log, maybe that helps somehow?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 3 Oct 2012 06:57**

Just to clear up: initial sync works in Milan! So I think this problem was introduced in Joey.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 4 Oct 2012 08:24**

It has been working with Milan, because we did not support AS 14.1. Now we do, which leads to a different kind of communication between the client and Tine 2.0.

I implemented a fix, which is already in our GIT repository. Can please try with the latest GIT checkout?

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 4 Oct 2012 18:19**

Just tested and get the same error as described in #0007186. The phone shows error id 8500201D.

Here&#039;s the log:
2c774 testuser - 2012-10-04T18:12:00+00:00 WARN (4): Zend_Cache_Core::save() : impossible to save cache (id=getApplicationByName_Tasks)
2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::302 Loading all configs for app ActiveSync
2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::309 Found 0 configs.
2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Syncroton_Server::handle::56 REQUEST METHOD: POST
2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Syncroton_Server::_handlePost::89 REQUEST Array
(
    [protocolVersion] =&gt; 141
    [command] =&gt; Sync
    [deviceId] =&gt; fcfe778c2f25a57d06d67f755066371e
    [deviceType] =&gt; WP
    [policyKey] =&gt; 
    [saveInSent] =&gt; 
    [collectionId] =&gt; 
    [itemId] =&gt; 
    [attachmentName] =&gt; 
    [userAgent] =&gt; WP
    [contentType] =&gt; application/vnd.ms-sync
)

2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::146 sync timestamp: 2012-10-04 18:12:00
2c774 testuser - 2012-10-04T18:12:00+00:00 WARN (4): Tinebase_Core::errorHandler::426 simplexml_import_dom() expects parameter 1 to be object, resource given in /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Sync.php::116 (2)
2c774 testuser - 2012-10-04T18:12:00+00:00 NOTICE (5): Tinebase_Core::errorHandler::437 Trying to get property of non-object in /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Sync.php::130 (8)
2c774 testuser - 2012-10-04T18:12:00+00:00 NOTICE (5): Tinebase_Core::errorHandler::437 Trying to get property of non-object in /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Sync.php::130 (8)
2c774 testuser - 2012-10-04T18:12:00+00:00 WARN (4): Tinebase_Core::errorHandler::426 Invalid argument supplied for foreach() in /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Sync.php::130 (2)
2c774 testuser - 2012-10-04T18:12:00+00:00 DEBUG (7): Syncroton_Server::_handlePost::163 xml response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;Sync xmlns=&quot;uri:AirSync&quot; xmlns:Syncroton=&quot;uri:Syncroton&quot;&gt;
  &lt;Collections/&gt;
&lt;/Sync&gt;

Initial sync works, though, the deviceid is hashed :)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Oct 2012 12:42**

I can reproduce the problem with our Windows Phone 7.5  test device. But I still don&#039;t know how to decode the data correctly.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Oct 2012 12:54**

Found the problem. Just have to implement the final solution.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 5 Oct 2012 19:14**

Ok, I&#039;m ready to test :)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Oct 2012 21:17**

Please update from GIT. It should be working now.

Forwarding emails is not yet working. I&#039;ll fix that the next few days.

**Comment by Gloirin** [comment]
**Comment posted by Michels on 6 Oct 2012 16:44**

For me the problem isn&#039;t solved.

In the logs it seems to be successfully synced but the mobile shows me error code: 0x80004005

I just can&#039;t figure out the error in the logs.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 6 Oct 2012 20:13**

With a fresh installation sync works now! Enabled required tine20 applications, created a testuser and some dummy content and it syncs!

I just noticed that _every_ mails gets synced (independent from phone setting).

But with a copy of my productive installation I have problems:
* initial sync fails for some users
* some user don&#039;t get contacts synced
* one account (with admin rights) syncs everything but in addition gets error 85002012 on the phone

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 6 Oct 2012 20:39**

Just found an httpd_error that occured during account setup with the testsytem:

[Sat Oct 06 21:56:44 2012] [error] [client 192.168.97.161] PHP Fatal error:  Undefined class constant &#039;PING_TIMEOUT&#039; in /usr/local/www/tine20migrationstest/library/Syncroton/lib/Syncroton/Command/Sync.php on line 406

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 7 Oct 2012 18:55**

I could reproduce error 85002012 on a fresh git installation: created a testuser and some dummy content and it syncs.
Deleted account from phone and set it up again -&gt; error 85002012.

I&#039;ve attachd a debug log of this error as &quot;20121007_error_85002012.log&quot;.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 8 Oct 2012 21:24**

Just did some more (quick) tests with git from now:
* cannot add contacts: 
    2012-10-08T20:56:06+00:00 WARN (4): Syncroton_Command_Sync::handle::271 failed to add entry Data is no valid property of Syncroton_Model_EmailBody
** Siehe auch hier: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11654&amp;sid=e68efd2e56b52ca9b5b40461b398de09
* add event series on phone, delete one entry deletes complete series

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 22 Oct 2012 19:45**

Can&#039;t do anymore tests with this.
I&#039;ve sent back the Lumia and now don&#039;t have access to a Windows Phone 7.5 test device anymore. Sorry.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 10 Nov 2012 14:18**

We had the same issue with an HTC Incredible S Smartphone and Joey (2012.10.1).
The workaround from the forum helps.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2012 14:26**

this is almost done.
