### ISSUE TITLE
0007220:
Nokia Mail for Exchange 3.0 crashes because of Addressbook_Exception_AccessDenied

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3657]
**Reported by kocsv on 11 Oct 2012 13:14**

**Version:** Milan (2012.03.7)

Synced a Nokia E71 with the filter in Tine set to &quot;All Contacts&quot;
&quot;All Contacts&quot; in my case includes the personal addressbook and also a shared one, for which i only have read permissions.

Then deleted 1 contact on the phone out of the shared addressbook (which is a Tine account). When syncing, Mail for Exchange on the phone gives this output (adminlog):

&quot;09.10.2012 18:21:08 PeakTime active

09.10.2012 18:21:08 Setting OFFLINE Status to False

09.10.2012 18:21:08 Setting ROAMING status to True

09.10.2012 18:21:08 Setting DISK FULL status to False

09.10.2012 18:21:15 Setting ROAMING status to False

09.10.2012 18:21:21 start E-Mail sync

09.10.2012 18:21:24 client-&gt;server adds=0 changes=2 deletes=0 fails=0

09.10.2012 18:21:24 server-&gt;client adds=0 changes=0 deletes=0 fails=0

09.10.2012 18:21:24 end Email sync

09.10.2012 18:21:24 start User sync

09.10.2012 18:21:24 Nothing to sync

09.10.2012 18:21:24 end User sync

09.10.2012 18:21:24 start Calendar sync

09.10.2012 18:21:24 Nothing to sync

09.10.2012 18:21:24 end Calendar sync

09.10.2012 18:21:25 start Kontakte sync

09.10.2012 18:21:30 HTTP error code=500

09.10.2012 18:21:30 HTTP Server Error 500: Internal Server Error

09.10.2012 18:21:30 end Contacts sync&quot;

Corresponding log from Tine:

&quot;exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;either &quot;org_name&quot; or &quot;n_family&quot; must be given!&#039; in /srv/http/********/Addressbook/Model/Contact.php:315
Stack trace:
#0 /srv/http/********/Tinebase/Controller/Record/Abstract.php(416): Addressbook_Model_Contact-&gt;isValid(true)
#1 /srv/http/********/ActiveSync/Controller/Abstract.php(301): Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#2 /srv/http/********/library/Syncope/lib/Syncope/Command/Sync.php(242): ActiveSync_Controller_Abstract-&gt;createEntry(&#039;addressbook-roo...&#039;, Object(SimpleXMLElement))
#3 /srv/http/********/library/Syncope/lib/Syncope/Server.php(134): Syncope_Command_Sync-&gt;handle()
#4 /srv/http/********/library/Syncope/lib/Syncope/Server.php(64): Syncope_Server-&gt;_handlePost()
#5 /srv/http/********/ActiveSync/Server/Http.php(99): Syncope_Server-&gt;handle()
#6 /srv/http/********/Tinebase/Core.php(247): ActiveSync_Server_Http-&gt;handle()
#7 /srv/http/********/index.php(57): Tinebase_Core::dispatchRequest()
#8 {main}
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry either &quot;org_name&quot; or &quot;n_family&quot; must be given!
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 ERR (3): Addressbook_Model_Contact::isValid::316:
Array
(
     [0] =&gt; Array
         (
             [id] =&gt; org_name
             [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
         )

     [1] =&gt; Array
         (
             [id] =&gt; n_family
             [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
         )

     [2] =&gt; Array
         (
             [id] =&gt; org_name
             [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
         )

     [3] =&gt; Array
         (
             [id] =&gt; n_family
             [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
         )

)
exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;either &quot;org_name&quot; or &quot;n_family&quot; must be given!&#039; in /srv/http/********/Addressbook/Model/Contact.php:315
Stack trace:
#0 /srv/http/********/Tinebase/Controller/Record/Abstract.php(416): Addressbook_Model_Contact-&gt;isValid(true)
#1 /srv/http/********/ActiveSync/Controller/Abstract.php(301): Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact))
#2 /srv/http/********/library/Syncope/lib/Syncope/Command/Sync.php(242): ActiveSync_Controller_Abstract-&gt;createEntry(&#039;addressbook-roo...&#039;, Object(SimpleXMLElement))
#3 /srv/http/********/library/Syncope/lib/Syncope/Server.php(134): Syncope_Command_Sync-&gt;handle()
#4 /srv/http/********/library/Syncope/lib/Syncope/Server.php(64): Syncope_Server-&gt;_handlePost()
#5 /srv/http/********/ActiveSync/Server/Http.php(99): Syncope_Server-&gt;handle()
#6 /srv/http/********/Tinebase/Core.php(247): ActiveSync_Server_Http-&gt;handle()
#7 /srv/http/********/index.php(57): Tinebase_Core::dispatchRequest()
#8 {main}
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry either &quot;org_name&quot; or &quot;n_family&quot; must be given!
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:09+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 WARN (4): Syncope_Command_Sync::handle::260 failed to add entry Duplicate record(s) found
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 ERR (3): Tinebase_Controller_Record_Abstract::delete::958 It is not allowed to delete a contact linked to an user account!
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 ERR (3): Tinebase_Controller_Record_Abstract::delete::959 
#0 /srv/http/********/Tinebase/Controller/Record/Abstract.php(944): Addressbook_Controller_Contact-&gt;_deleteRecord(Object(Addressbook_Model_Contact))
#1 /srv/http/********/ActiveSync/Controller/Abstract.php(349): Tinebase_Controller_Record_Abstract-&gt;delete(&#039;a1adedcf7000c99...&#039;)
#2 /srv/http/********/library/Syncope/lib/Syncope/Command/Sync.php(310): ActiveSync_Controller_Abstract-&gt;deleteEntry(&#039;addressbook-roo...&#039;, &#039;a1adedcf7000c99...&#039;, Array)
#3 /srv/http/********/library/Syncope/lib/Syncope/Server.php(134): Syncope_Command_Sync-&gt;handle()
#4 /srv/http/********/library/Syncope/lib/Syncope/Server.php(64): Syncope_Server-&gt;_handlePost()
#5 /srv/http/********/ActiveSync/Server/Http.php(99): Syncope_Server-&gt;handle()
#6 /srv/http/********/Tinebase/Core.php(247): ActiveSync_Server_Http-&gt;handle()
#7 /srv/http/********/index.php(57): Tinebase_Core::dispatchRequest()
#8 {main}
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 CRIT (2): Syncope_Server::_handlePost::156 unexpected exception occured: Addressbook_Exception_AccessDenied
8ad7a &lt;username&gt; - 2012-10-09T16:22:10+00:00 CRIT (2): Syncope_Server::_handlePost::158 exception message: It is not allowed to delete a contact linked to an user ccount!&quot;

**Steps to reproduce:** Delete a contact linked to an user account on the phone and try to sync.

**Comment by Gloirin** [comment]
**Comment posted by kocsv on 11 Oct 2012 13:15**

MfE not really crashes, but stops sync.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Oct 2012 14:17**

i&#039;m not sure if we&#039;ll fix this because we decided to no longer support MfE. but i&#039;ll assign this to lars nevertheless and he can decide if this might affect other clients.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Nov 2012 12:12**

could you please test with Joey? if you still have the problem please attach the logfile (DEBUG mode). we need the xml-snippet to write a fix for the problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Jan 2013 12:44**

should be fixed in Joey. if not, please reopen the bugreport.
