### ISSUE TITLE
0007298:
DirectoryIterator - hourly error

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3695]
**Reported by flocsi on 25 Oct 2012 10:16**

**Version:** Joey (2012.10.1)

Since updating to 2012.10.1 the following error is sent hourly.
The same config file is used as in the previous version; file/folder rights are set correctly.

    PHP Fatal error:  Uncaught exception &#039;UnexpectedValueException&#039; with message &#039;DirectoryIterator::__construct(/var/lib/php-sessions): failed to open dir: Permission denied&#039; in /pfad/zu/tine/Tinebase/Controller.php:381
    Stack trace:
    #0 /pfad/zu/tine/Tinebase/Controller.php(381): DirectoryIterator-&gt;__construct(&#039;/var/lib/php-se...&#039;)
    #1 [internal function]: Tinebase_Controller-&gt;cleanupSessions()
    #2 /pfad/zu/tine/Tinebase/Scheduler/Task.php(236): call_user_func_array(Array, Array)
    #3 /pfad/zu/tine/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
    #4 /pfad/zu/tine/Tinebase/Frontend/Cli.php(113): Zend_Scheduler-&gt;run()
    #5 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
    #6 /pfad/zu/tine/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
    #7 /pfad/zu/tine/Tineb in /pfad/zu/tine/Tinebase/Controller.php on line 381

**Comment by Gloirin** [comment]
**Comment posted by flocsi on 25 Oct 2012 10:18**

Seems to be caused by a new scheduler task which cleans sessions hourly. See: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11728
