### ISSUE TITLE
0007316:
Syncroton - gal_data_class

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3703]
**Reported by splinter03 on 27 Oct 2012 09:28**

**Version:** Joey (2012.10.1)

Since i&#039;ve updated to joey, the follwoing error occurs in log: 

037c3 ***** - 2012-10-26T14:02:09+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Exception
037c3 ***** - 2012-10-26T14:02:09+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: No entry is registered for key &#039;gal_data_class&#039;
037c3 ***** - 2012-10-26T14:02:09+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /var/www/tine20/library/Syncroton/lib/Syncroton/Data/Factory.php(57): Syncroton_Registry::get(&#039;gal_data_class&#039;)
#1 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Search.php(53): Syncroton_Data_Factory::factory(&#039;GAL&#039;, Object(Syncroton_Model_Device), Object(DateTime))
#2 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Search-&gt;getResponse()
#3 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
#4 /var/www/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
#5 /var/www/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#6 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#7 {main}

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 8 Nov 2012 05:24**

The problem is fixed in our GIT repository and the fix will be included in the next Tine 2.0 service release.
