### ISSUE TITLE
0007370:
Unable to upload files

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3730]
**Reported by ug2k on 5 Nov 2012 21:24**

**Version:** Joey (2012.10.1)

error message: &quot;Sorry, you are not permitted to perform this action&quot;

**Additional information:** log:

68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::385 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::386 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::387 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Server_Json::_handleException::229 Tinebase_Exception_AccessDenied -&gt; Permission denied to create file (filename /5030412e6375f63d7f72b100b90113cb3e220256/folders/shared/26/Neues Textdokument.txt)
68d64 admin - 2012-11-01T21:13:36+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::296 #0 .../Filemanager/Controller/Node.php(596): Filemanager_Controller_Node-&gt;_createNodeInBackend(&#039;/5030412e6375f6...&#039;, &#039;file&#039;, NULL)
#1 .../Filemanager/Controller/Node.php(500): Filemanager_Controller_Node-&gt;_createNode(&#039;/shared/neu/Neu...&#039;, &#039;file&#039;, NULL, false)
#2 .../Filemanager/Frontend/Json.php(94): Filemanager_Controller_Node-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#3 [internal function]: Filemanager_Frontend_Json-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(206): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(17): Tinebase_Core::dispatchRequest()
#11 {main}
12fb3 admin - 2012-11-01T21:13:45+00:00 NOTICE (5): Filemanager_Controller_Node::_checkFilterACL::297 Could not determine path, setting root path (Duplicate container found: Persönliche Dateien von Tine 2.0 Admin Account)
e5e74 admin - 2012-11-01T21:13:45+00:00 NOTICE (5): Filemanager_Controller_Node::_checkFilterACL::297 Could not determine path, setting root path (Duplicate container found: Persönliche Dateien von Tine 2.0 Admin Account)

**Comment by Gloirin** [comment]
**Comment posted by martin on 24 Jan 2013 18:36**

same for me on my hosteurope webpack
(folders are displayed correctly)
read / write permission is granted

**Comment by Gloirin** [comment]
**Comment posted by martin on 24 Jan 2013 18:52**

added some logger:
...
Tinebase_Core::getLogger()-&gt;err(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; handle:&#039; . $handle);
Tinebase_Core::getLogger()-&gt;err(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; mode:&#039; . $_mode);
Tinebase_Core::getLogger()-&gt;err(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; node:&#039; . $node);
        
stream_context_set_option ($handle, &#039;tine20&#039;, &#039;path&#039;, $_path);
stream_context_set_option ($handle, &#039;tine20&#039;, &#039;mode&#039;, $_mode);
stream_context_set_option ($handle, &#039;tine20&#039;, &#039;node&#039;, $node);
...

and got this log:

 4d18a admin - 2013-01-24T18:46:36+00:00 ERR (3): Tinebase_FileSystem::fopen::386 handle:
 4d18a admin - 2013-01-24T18:46:36+00:00 ERR (3): Tinebase_FileSystem::fopen::387 mode:w
 4d18a admin - 2013-01-24T18:46:36+00:00 ERR (3): Tinebase_FileSystem::fopen::388 node:Array
(
    [id] =&gt; bd256b96b81ef215b2f1a0908d0f9062a2111e17
    [parent_id] =&gt; 29a6b47e63d0cd47f13b0ad9a3ce9a8e2e7a3ac5
    [object_id] =&gt; 5a2dc9c5aa3f4d77a4682c9b3caab04d1193e6f9
    [name] =&gt; test.TXT
    [islink] =&gt; 0
    [type] =&gt; file
    [created_by] =&gt; e00dd639e611956b73c2a4c93439143f74533ac7
    [creation_time] =&gt; 2013-01-24 18:46:36
    [last_modified_by] =&gt; 
    [last_modified_time] =&gt; 
    [revision] =&gt; 0
    [contenttype] =&gt; application/octet-stream
    [hash] =&gt; 
    [size] =&gt; 
)

 4d18a admin - 2013-01-24T18:46:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /is/htdocs/wp10744784_GT65GVQU3J/intern/Tinebase/FileSystem.php::390 (2)
 4d18a admin - 2013-01-24T18:46:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /is/htdocs/wp10744784_GT65GVQU3J/intern/Tinebase/FileSystem.php::391 (2)
 4d18a admin - 2013-01-24T18:46:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /is/htdocs/wp10744784_GT65GVQU3J/intern/Tinebase/FileSystem.php::392 (2)
 4d18a admin - 2013-01-24T18:46:36+00:00 WARN (4): Tinebase_Server_Json::_handleException::230 Tinebase_Exception_AccessDenied -&gt; Permission denied to create file (filename /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/8/Tine/test.TXT)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2013 15:04**

hey guys,

i looked up the docs of stream_context_set_option (http://de3.php.net/manual/en/function.stream-context-set-option.php) and used the 2 params version in the Filesystem class.

please try it again with the attached version (Tinebase/FileSystem.php). maybe that fixes those permission denied errors.

**Comment by Gloirin** [comment]
**Comment posted by martin on 28 Jan 2013 15:33**

Hi Phil,

thanks for the quick response :-) But the patch did not solve the problem :-(

099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1030 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Server_Json::handle::67 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Filemanager.createNodes
            [params] =&gt; Array
                (
                    [filenames] =&gt; Array
                        (
                            [0] =&gt; /shared/Divers/Tine/test.TXT
                        )

                    [type] =&gt; file
                    [tempFileIds] =&gt; Array
                        (
                        )

                    [forceOverwrite] =&gt; 
                )

            [id] =&gt; 12
        )

)

099de cd19d admin - 2013-01-28T15:24:52+00:00 INFO (6): Tinebase_Server_Json::_handle::164 is JSON request. method: Filemanager.createNodes
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Model_Tree_Node_Path::_parsePath::193 Parsing path: /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/Divers/Tine/test.TXT
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Model_Tree_Node_Path::_getStatPath::368 Path to stat: /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/8/Tine/test.TXT
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Model_Tree_Node_Path::_parsePath::193 Parsing path: /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/Divers/Tine
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Tinebase_Model_Tree_Node_Path::_getStatPath::368 Path to stat: /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/8/Tine
099de cd19d admin - 2013-01-28T15:24:52+00:00 DEBUG (7): Filemanager_Controller_Node::_createNodeInBackend::611 Creating new path /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/8/Tine/test.TXT of type file
099de cd19d admin - 2013-01-28T15:24:52+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /is/htdocs/wp10744784_GT65GVQU3J/intern/Tinebase/FileSystem.php::391 (2)
099de cd19d admin - 2013-01-28T15:24:52+00:00 WARN (4): Tinebase_Server_Json::_handleException::230 Tinebase_Exception_AccessDenied -&gt; Permission denied to create file (filename /58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/8/Tine/test.TXT)
099de cd19d admin - 2013-01-28T15:24:52+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::297 #0 .../Filemanager/Controller/Node.php(596): Filemanager_Controller_Node-&gt;_createNodeInBackend(&#039;/58693eaeeda898...&#039;, &#039;file&#039;, NULL)
#1 .../Filemanager/Controller/Node.php(500): Filemanager_Controller_Node-&gt;_createNode(&#039;/shared/Divers/...&#039;, &#039;file&#039;, NULL, false)
#2 .../Filemanager/Frontend/Json.php(94): Filemanager_Controller_Node-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#3 [internal function]: Filemanager_Frontend_Json-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(17): Tinebase_Core::dispatchRequest()
#11 {main}
099de cd19d admin - 2013-01-28T15:24:52+00:00 INFO (6): index.php (36) METHOD: Tinebase_Server_Json::Filemanager.createNodes / TIME: 0.60504603385925 seconds / MEMORY: 11 MBytes / REALPATHCACHESIZE: 74797

I&#039;m not sure what happens here, but this absolute path:
&quot;/58693eaeeda8985618f899963d3af49bed4e3e02/folders/shared/Divers/Tine/test.TXT&quot;
looks strange to me (does not exist)...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2013 16:10**

ok, i think, the $handle might be NULL or empty in your case.

it looks like 

$handle = tmpfile();

fails. maybe because your hoster prevents the usage of /tmp

perhaps we could use tempnam() here to create a temporary file.

$tmpfname = tempnam(&quot;/path/to/writeable/tempdir&quot;, &quot;somehash&quot;);
$handle = fopen($tmpfname, &quot;w&quot;);

could you please try if that works?

**Comment by Gloirin** [comment]
**Comment posted by martin on 28 Jan 2013 17:16**

now I get a valid resource id and the upload process starts without any error; but: after uploading I have a 0 Byte file with inode/x-empty

there are now 3 files in my tmp folder:
dedc1b4582c76b231a4ae79fe25005da517e1f3dhUghh5 : 0 Bytes
dedc1b4582c76b231a4ae79fe25005da517e1f3dERF7MN : 3 Bytes
tine_tempfile_QWVOy0                           : 3 Bytes

and one in the file-storage folder

files/da3/9a3ee5e6b4b0d3255bfef95601890afd80709 : 0 Bytes

I attach the log (1) because it&#039;s getting big

[EDIT]
the error messages in the log are my debugging output

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Jan 2013 09:29**

ok, i&#039;ll run some tests with the changed tempfile handling, too.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 09:44**

new idea:
- remove tmpfile() calls
- always use our own tempfile handling -&gt; Tinebase_TempFile::getTempFilehandle()
- add new (or modify) scheduler task -&gt; tempfile cleanup that removes files older than one week (?)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 09:44**

https://gerrit.tine20.org/tine20/#/c/1562/5
