### ISSUE TITLE
0007372:
nested folders

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3731]
**Reported by ug2k on 5 Nov 2012 21:33**

**Version:** Joey (2012.10.1)

&quot;my folder&quot; includes &quot;personal folder of...&quot; and conversely

**Additional information:** screenshot attached

**Comment by Gloirin** [comment]
**Comment posted by ug2k on 5 Nov 2012 21:36**

log:

68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::385 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::386 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Core::errorHandler::426 stream_context_set_option() [&lt;a href=&#039;function.stream-context-set-option&#039;&gt;function.stream-context-set-option&lt;/a&gt;]: called with wrong number or type of parameters; please RTM in /www/tine/Tinebase/FileSystem.php::387 (2)
68d64 admin - 2012-11-01T21:13:36+00:00 WARN (4): Tinebase_Server_Json::_handleException::229 Tinebase_Exception_AccessDenied -&gt; Permission denied to create file (filename /5030412e6375f63d7f72b100b90113cb3e220256/folders/shared/26/Neues Textdokument.txt)
68d64 admin - 2012-11-01T21:13:36+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::296 #0 .../Filemanager/Controller/Node.php(596): Filemanager_Controller_Node-&gt;_createNodeInBackend(&#039;/5030412e6375f6...&#039;, &#039;file&#039;, NULL)
#1 .../Filemanager/Controller/Node.php(500): Filemanager_Controller_Node-&gt;_createNode(&#039;/shared/neu/Neu...&#039;, &#039;file&#039;, NULL, false)
#2 .../Filemanager/Frontend/Json.php(94): Filemanager_Controller_Node-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#3 [internal function]: Filemanager_Frontend_Json-&gt;createNodes(Array, &#039;file&#039;, Array, false)
#4 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#5 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 .../Tinebase/Server/Json.php(206): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#9 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#10 .../index.php(17): Tinebase_Core::dispatchRequest()
#11 {main}
12fb3 admin - 2012-11-01T21:13:45+00:00 NOTICE (5): Filemanager_Controller_Node::_checkFilterACL::297 Could not determine path, setting root path (Duplicate container found: Persönliche Dateien von Tine 2.0 Admin Account)
e5e74 admin - 2012-11-01T21:13:45+00:00 NOTICE (5): Filemanager_Controller_Node::_checkFilterACL::297 Could not determine path, setting root path (Duplicate container found: Persönliche Dateien von Tine 2.0 Admin Account)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2013 15:31**

please try the FileSystem.php attached to task #7370. maybe it helps with this bug, too.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 09:46**

duplicate of #7370
