### ISSUE TITLE
0007384:
deleting a group that is an accounts primary group fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3737]
**Reported by pschuele on 7 Nov 2012 20:22**

**Version:** Kristina (2013.03.2)

deleting a group that is an accounts primary group fails

- we should create a better error message for the user
- and/or allow the user to select a new primary group for the accounts in question

**Additional information:** e88cd tine20admin - 2012-11-07T18:56:02+00:00 WARN (4): Tinebase_Server_Json::_handleException::226 Tinebase_Exception_Backend -&gt; SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`tine20`.`tine20_accounts`, CONSTRAINT `tine20_accounts::primary_group_id--groups::id` FOREIGN KEY (`primary_group_id`) REFERENCES `tine20_groups` (`id`))
 e88cd tine20admin - 2012-11-07T18:56:02+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::293 #0 .../Admin/Controller/Group.php(369): Tinebase_Group_Sql-&gt;deleteGroups(Array)
#1 .../Admin/Frontend/Json.php(659): Admin_Controller_Group-&gt;delete(Array)
0000002 [internal function]: Admin_Frontend_Json-&gt;deleteGroups(Array)
#3 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
0000004 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 .../Tinebase/Server/Json.php(203): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
0000008 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#9 .../index.php(17): Tinebase_Core::dispatchRequest()
0000010 {main}

**Comment by Gloirin** [comment]
Related to #3611

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 14:54**

we could just set the default user group for accounts with the deleted primary group.
