### ISSUE TITLE
0007440:
Unable to delete Mails - Integrity constraint violation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3763]
**Reported by splinter03 on 17 Nov 2012 09:09**

**Version:** Joey (2012.10.1)

Als ich mich eben eingeloggt habe, musste ich feststellen, das Tine die Zuordnung der Mail-Ordner geändert hat. Die Ordner heißen wie bisher, im Dialog &quot;Andere Einstellungen&quot; hat Tine jedoch vor jedem Ordnernamen ein &quot;F&quot; gehängt. Ich habe die Zuordnung korrigiert. Alles OK. Doch als ich versucht habe, Mails zu löschen, ging das nicht. Die Mails erscheinen einfach wieder.

**Additional information:** f97b7 **************** - 2012-11-16T18:36:01+00:00 WARN (4): ActiveSync_Controller_Email::updateCache::820 catched exception Felamimail_Exception_IMAPServiceUnavailable
f97b7 **************** - 2012-11-16T18:36:01+00:00 WARN (4): ActiveSync_Controller_Email::updateCache::822 cannot connect to host : 0 : php_network_getaddresses: getaddrinfo failed: Name or service not known
409ec **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Db_Statement_Exception
409ec **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;10a6284960fb49875e002368ca2316d4cee2bd35-987ef35a243cb3dc2e7634e&#039; for key &#039;PRIMARY&#039;
409ec **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /var/www/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/tine20/library/Syncroton/lib/Syncroton/Backend/ABackend.php(56): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_acsync_s...&#039;, Array)
#5 /var/www/tine20/library/Syncroton/lib/Syncroton/Backend/SyncState.php(33): Syncroton_Backend_ABackend-&gt;create(Object(Syncroton_Model_SyncState))
#6 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php(834): Syncroton_Backend_SyncState-&gt;create(Object(Syncroton_Model_SyncState), true)
#7 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Sync-&gt;getResponse()
#8 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
#9 /var/www/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
#10 /var/www/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#11 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}
9b9be **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Db_Statement_Exception
9b9be **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;10a6284960fb49875e002368ca2316d4cee2bd35-987ef35a243cb3dc2e7634e&#039; for key &#039;PRIMARY&#039;
9b9be **************** - 2012-11-16T23:04:34+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /var/www/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/tine20/library/Syncroton/lib/Syncroton/Backend/ABackend.php(56): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_acsync_s...&#039;, Array)
#5 /var/www/tine20/library/Syncroton/lib/Syncroton/Backend/SyncState.php(33): Syncroton_Backend_ABackend-&gt;create(Object(Syncroton_Model_SyncState))
#6 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php(834): Syncroton_Backend_SyncState-&gt;create(Object(Syncroton_Model_SyncState), true)
#7 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Sync-&gt;getResponse()
#8 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
#9 /var/www/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
#10 /var/www/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#11 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 17 Nov 2012 09:27**

Nach einem &quot;Logout-Login&quot; geht es nun wieder, trotzdem komisch das Tine eine identische Schlüsselkombination anlegen wollte...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2012 09:36**

hm, die geposteten fehler kommen aber aus dem ActiveSync modul.

das mit dem &quot;F&quot; haben wir auch schon in einem bugreport: #5138
leider habe ich da noch keine idee, wie man das reproduzieren kann.

ich weiss nun nicht genau, was wir mit diesem bugreport machen. vielleicht ist es auch nur ein folgefhler von #5138.

bist du auch bei web.de oder gmx?

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 20 Nov 2012 08:33**

Ich glaube der Fehler wurde durch das ActiveSync-Modul verursacht und hat dann Felamimail am löschen gehindert.

Meine Emails liegen auf einem 1&amp;1-Server.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Nov 2012 09:32**

ich gebe das mal an lars, vielleicht hat er eine spontane idee.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 21 Nov 2012 12:00**

Das Problem wird mit dem nächsten Service Release behoben.
