### ISSUE TITLE
0007444:
Outlook 2013 Sync does not work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3765]
**Reported by Faultier89 on 18 Nov 2012 11:14**

**Version:** Joey (2012.10.1)

tine20 is installed on my Homeserver. It is only accessable from the intranet.

It works very well with my Anroid smartphones. But it doesn&#039;t work with Outlook 2013. 

I created a new Account (Konto in german) where i selected &#039;ActiveSync Exchange&#039;. Everything seemd to work. No errors in Outlook. Outlook says the status is &#039;Connected&#039; and &#039;Waiting for the Serverresponse&#039;. (in German: &#039;Verbunden&#039; und &#039;Auf die Serverantwort wird gewartet&#039;.

I recreated the Outlook-Account a few times. Always the same result. 

**Additional information:** 2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setupLogger::539 Logger initialized
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setupCache::605 cache of backend type &#039;File&#039; enabled
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setSessionBackend::831 Session of backend type &#039;File&#039; configured.
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setupUserLocale::1017 Setting user locale: en
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): ActiveSync_Server_Http::handle::42 is ActiveSync request.
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::1094 setting execution life time to: 0
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Auth::authenticate::205 Authentication of Tobias succeeded
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_User::setBackendType::234 Setting backend type to Sql
2074b -- none -- - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_User::factory::195 Created user backend of type Sql
2074b tobias - 2012-11-10T11:59:10+00:00 INFO (6): Tinebase_Core::setupUserLocale::1017 Setting user locale: en
2074b tobias - 2012-11-10T11:59:10+00:00 WARN (4): Tinebase_Core::errorHandler::426 include_once(C:\xampp\htdocs\tine20/library/Syncroton/lib/Syncroton\Wbxml\Dtd\ActiveSync\CodePage254.php): failed to open stream: No such file or directory in C:\xampp\htdocs\tine20\Tinebase\Autoloader.php::52 (2)
2074b tobias - 2012-11-10T11:59:10+00:00 WARN (4): Tinebase_Core::errorHandler::426 include_once(): Failed opening &#039;C:\xampp\htdocs\tine20/library/Syncroton/lib/Syncroton\Wbxml\Dtd\ActiveSync\CodePage254.php&#039; for inclusion (include_path=&#039;C:\xampp\htdocs\tine20;C:\xampp\htdocs\tine20\library;.;\xampp\php\PEAR&#039;) in C:\xampp\htdocs\tine20\Tinebase\Autoloader.php::52 (2)

**Comment by Gloirin** [comment]
**Comment posted by smunn on 26 Nov 2012 17:19**

Having just installed the service pack for Joey, I was hoping Outlook 2013 would work OK (not the 365 version).

Activesync works OK on my iPhone; logging into Microsoft-Server-ActiveSync also passes and Outlook 2013 says the connection is OK.

However, whenever I attempt to send or recieve data I get the following error in Outlook, multiple times:

The server configuration prevents you from synchronising. Contact your system administrator.

File: outlook\pstprx\storeas\utils\airsyncstatuscodes.h
Line: 200
HTTP/1.1 403 Forbidden
FolderStatus: 403
To re-try press F9...
Error Code: 0x80004005

Before the service pack is was a similiar error but talked about synchroton files. Do I need to tweak something or is support still not available.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 26 Nov 2012 21:07**

Same here. We have a equal error about failed opening/missing files:

2ed20 andy - 2012-11-26T20:59:54+00:00 WARN (4): Tinebase_Core::errorHandler::426 include_once(C:\Apache24\htdocs\tine20/library/Syncroton/lib/Syncroton\Wbxml\Dtd\ActiveSync\CodePage254.php): failed to open stream: No such file or directory in C:\Apache24\htdocs\tine20\Tinebase\Autoloader.php::52 (2)
2ed20 andy - 2012-11-26T20:59:54+00:00 WARN (4): Tinebase_Core::errorHandler::426 include_once(): Failed opening &#039;C:\Apache24\htdocs\tine20/library/Syncroton/lib/Syncroton\Wbxml\Dtd\ActiveSync\CodePage254.php&#039; for inclusion (include_path=&#039;C:\Apache24\htdocs\tine20;C:\Apache24\htdocs\tine20\library;.;C:\php\pear&#039;) in C:\Apache24\htdocs\tine20\Tinebase\Autoloader.php::52 (2)

I checked the folder on two systems (both Windows), there&#039;s no &quot;CodePage254.php&quot;-file.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 27 Nov 2012 15:40**

CodePage 254 is completely out of range.

Please add following lines to /library/Syncroton/lib/Syncroton/Server.php after line 121 (try[)

                // log body
                $tempStream = fopen(&quot;php://temp&quot;, &#039;r+&#039;);
                stream_copy_to_stream($this-&gt;_body, $tempStream);
                rewind($tempStream);
                file_put_contents(tempnam(&#039;/tmp&#039;, &#039;wbxml&#039;), $tempStream);
                $this-&gt;_body = $tempStream;
                rewind($this-&gt;_body);
                
If everything goes well, there will be a new file in /tmp containiing the WBXML encoded request. That&#039;s what I need. 

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by andydld on 27 Nov 2012 15:58**

This generates an php-error:

27-Nov-2012 15:56:10 UTC] PHP Parse error:  syntax error, unexpected &#039;^&#039;, expecting &#039;]&#039; in C:\Apache24\htdocs\tine20\library\Syncroton\lib\Syncroton\Server.php on line 123

Line 123 is:

$tempStream = fopen(&quot;php://temp&quot;...

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 27 Nov 2012 18:12**

Argl....

Mantis added some additional characters.

I&#039;ll attach the whole file.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 27 Nov 2012 18:30**

Thanks for the file.

It now creates alot of files named &quot;wbx*.tmp&quot;, all have a size of 1 KB and all have this content:

j  VR0  þEFGPermission FGInternalFolderType 

And i&#039;ve got an new php-error:

[27-Nov-2012 18:26:08 UTC] PHP Fatal error:  Uncaught exception &#039;Zend_Exception&#039; with message &#039;File &quot;C:\Apache24\htdocs\tine20/library/Syncroton/lib/Syncroton\Wbxml\Dtd\ActiveSync\CodePage254.php&quot; does not exist or class &quot;Syncroton_Wbxml_Dtd_ActiveSync_CodePage254&quot; was not found in the file&#039; in C:\Apache24\htdocs\tine20\Tinebase\Autoloader.php:55
Stack trace:
#0 C:\Apache24\htdocs\tine20\library\Zend\Loader\Autoloader.php(115): Tinebase_Autoloader-&gt;autoload(&#039;Syncroton_Wbxml...&#039;)
#1 [internal function]: Zend_Loader_Autoloader::autoload(&#039;Syncroton_Wbxml...&#039;)
#2 C:\Apache24\htdocs\tine20\library\Syncroton\lib\Syncroton\Wbxml\Dtd\ActiveSync.php(84): spl_autoload_call(&#039;Syncroton_Wbxml...&#039;)
#3 C:\Apache24\htdocs\tine20\library\Syncroton\lib\Syncroton\Wbxml\Decoder.php(164): Syncroton_Wbxml_Dtd_ActiveSync-&gt;switchCodePage(254)
#4 C:\Apache24\htdocs\tine20\library\Syncroton\lib\Syncroton\Server.php(131): Syncroton_Wbxml_Decoder-&gt;decode()
#5 C:\Apache24\htdocs\tine20\library\Syncroton\lib\Syncroton\Server.php(69): Syncroton_Server-&gt;_handlePost()
#6 C:\Apache24\ht in C:\Apache24\htdocs\tine20\Tinebase\Autoloader.php on line 55

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 28 Nov 2012 09:57**

Please attach that file to this bug report. It contains unprintable characters.

The error messages can be ignored. The additional code only dumped the request to that file, but did not change anything else.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 28 Nov 2012 14:19**

File (&quot;wbx13AA.tmp&quot;) attached. Good luck!

**Comment by Gloirin** [comment]
**Comment posted by andydld on 28 Nov 2012 14:27**

I just noticed, that today Outlook 2013 connects to Tine. Maybe this occurs because of the &quot;new&quot; Server.php?

Sometimes i lost events and i noticed that events created with Outlook appears in Tine with the following description (Beschreibung) content:

&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2//EN&quot;&gt;
&lt;HTML&gt;
&lt;HEAD&gt;
&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=iso-8859-1&quot;&gt;
&lt;META NAME=&quot;Generator&quot; CONTENT=&quot;MS Exchange Server version rmj.rmm.rup.rpr&quot;&gt;
&lt;TITLE&gt;Test 6&lt;/TITLE&gt;
&lt;/HEAD&gt;
&lt;BODY&gt;
&lt;!-- Converted from text/rtf format --&gt;

&lt;P DIR=LTR&gt;&lt;SPAN LANG=&quot;de&quot;&gt;&lt;/SPAN&gt;&lt;/P&gt;

&lt;/BODY&gt;
&lt;/HTML&gt;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Nov 2012 16:37**

please test again after replacing your ActiveSync/Server/Http.php with the attached file.

the changes in Syncroton/Server.php can be removed.

i think, the event problems should be put into a separate bugreport. ;)

**Comment by Gloirin** [comment]
**Comment posted by andydld on 28 Nov 2012 18:55**

Thanks, seems be be working (so far).

**Comment by Gloirin** [comment]
**Comment posted by smunn on 28 Nov 2012 21:08**

Yes, it looks OK at the moment. Thx.

EDIT. I am seeing the calender rescheduling problem reported in 0007508

POST EDIT. Added another account in outlook and the same error appears for the new account, although the existing one is fine?!

**Comment by Gloirin** [comment]
**Comment posted by smunn on 29 Nov 2012 11:31**

Just installed Outlook on a second PC and the errors are appearing again with my usual account, although the existing PC with the same account is OK.

On my original PC I previously did the server.php changes which didn&#039;t work. Removed the changes and installed the http.php file. This didn&#039;t work initially. I tried it later in the day and it was all OK.

Log file attached.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 29 Nov 2012 13:40**

I uploaded Http.php again and deleted the previous version. Please use the new version.

The new version again dumps the request to /tmp.

Please attach a file from a request which creates a error.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 29 Nov 2012 17:47**

I&#039;v updated the Http.php.
I just noticed, that sending mail doesn&#039;t work, too.
I attached a new tmp-file.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 20 Feb 2013 19:04**

I was waiting for this bug to be solved since two months already, now it was again re-sheduled the second time, so I decided to create an account so that I can on the one hand show, that this bug is important to some people, and on the other hand: What can I do to help solving this bug?
I really could need the ActiveSync with Office!

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 21 Feb 2013 12:40**

We are working on this bug already. But our tests still need some time. Because of that we had to reschedule this bug again.

**Comment by Gloirin** [comment]
**Comment posted by admin4 on 22 Feb 2013 18:14**

dont work for me too :/ do you need more logs?

**Comment by Gloirin** [comment]
**Comment posted by smunn on 7 Mar 2013 19:16**

Updated to Kristina and seeing the following errors:

[Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: PHP Fatal error: Uncaught exception &#039;Zend_Exception&#039; with message &#039;File &quot;/var/www/vhosts/test.org.uk/httpdocs/tine/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync/CodePage254.php&quot; does not exist or class &quot;Syncroton_Wbxml_Dtd_ActiveSync_CodePage254&quot; was not found in the file&#039; in /var/www/vhosts/test.org.uk/httpdocs/tine/Tinebase/Autoloader.php:55 
[Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: #0 /var/www/vhosts/test.org.uk/httpdocs/tine/library/Zend/Loader/Autoloader.php(115): Tinebase_Autoloader-&gt;autoload(&#039;Syncroton_Wbxml...&#039;)
 [Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: #1 [internal function]: Zend_Loader_Autoloader::autoload(&#039;Syncroton_Wbxml...&#039;)
 [Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: #2 /var/www/vhosts/test.org.uk/httpdocs/tine/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync.php(84): spl_autoload_call(&#039;Syncroton_Wbxml...&#039;)
 [Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: #3 /var/www/vhosts/test.org.uk/httpdocs/tine/library/Syncroton/lib/Syncroton/Wbxml/Decoder.php(164): Syncroton_Wbxml_Dtd_ActiveSync-&gt;switchCodePage(254)
 [Thu Mar 07 19:08:00 2013] [warn] [client 2.219.194.9] mod_fcgid: stderr: #4 /var/www/vhosts/test.org.uk/httpdocs/tine in /var/www/vhosts/test.org.uk/httpdocs/tine/Tinebase/Autoloader.php on line 55

**Comment by Gloirin** [comment]
**Comment posted by didda on 23 Mar 2013 14:59**

I have a question I can&#039;t read out here so far. I also installed Kristina and I can connect with Outlook 2013. But there where no Item&#039;s synced from Tine to Outlook regardless of Contacts or Calender. With Android It works. 
Is the the same problem or do you get items with update to Kristina.

Thanks.

PS: I use Ubuntu as webserver, not Windows.

Here is my Apache log:
[Sat Mar 23 08:14:25 2013] [error] [client 192.168.0.100] PHP Fatal error:  Uncaught exception &#039;Zend_Exception&#039; with message &#039;File &quot;/usr/share/tine20/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync/CodePage254.php&quot; does not exist or class &quot;Syncroton_Wbxml_Dtd_ActiveSync_CodePage254&quot; was not found in the file&#039; in /usr/share/tine20/Tinebase/Autoloader.php:55\nStack trace:\n#0 /usr/share/tine20/library/Zend/Loader/Autoloader.php(115): Tinebase_Autoloader-&gt;autoload(&#039;Syncroton_Wbxml...&#039;)\n#1 [internal function]: Zend_Loader_Autoloader::autoload(&#039;Syncroton_Wbxml...&#039;)\n#2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync.php(84): spl_autoload_call(&#039;Syncroton_Wbxml...&#039;)\n#3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Wbxml/Decoder.php(164): Syncroton_Wbxml_Dtd_ActiveSync-&gt;switchCodePage(254)\n#4 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(123): Syncroton_Wbxml_Decoder-&gt;decode()\n#5 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()\n#6 /usr/share/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;h in /usr/share/tine20/Tinebase/Autoloader.php on line 55

The File CodePage254.php does not exist, but I think the Path /usr/share/tine20/is mysterious, isn&#039;t it? I think it should access library/ in the www root?!

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 4 Apr 2013 15:40**

@didda: The Path is okay, the Package is always installed in /usr/share/tine20 and then symlinked to the www-root.

An die Dev&#039;s:
Vielleicht klärt diese Seite hier etwas auf: http://social.msdn.microsoft.com/Forums/en-US/os_exchangeprotocols/thread/75562e26-158c-45d3-b114-b2b82928c3a7

Offensichtlich bring Outlook2013 ein &quot;Feature&quot; mit um sich mit Hotmail zu syncen. Outlook fragt scheinbar die Codepage 254 ab, sozusagen ob es sich um einen Hotmail Account handelt, genau da ist dann der Hase im Pfeffer. Man könnte eventuell eine Codepage254.php anlegen und sie mit entsprechendem Inhalt füllen, dann sollte sich auch Outlook2013 anständig syncen können.

**Comment by Gloirin** [comment]
**Comment posted by Christian on 10 Apr 2013 16:51**

Hi,

ich habe eine CodePage254.php Datei hochgeladen.
Mit der funktioniert es bei mir.

**Comment by Gloirin** [comment]
**Comment posted by admin4 on 10 Apr 2013 18:49**

Was muss man mit der CodePage254 machen? In meiner Installation gibt es diese gar nicht.

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 10 Apr 2013 19:20**

Ich kann bestätigen, das Chritians Lösung funktioniert. Kalender, Kontakte, Mail, Aufgaben alles wird erfolgreich mit Outlook 2013 gesynct.

Zur Erklärung: Christian hat oben hier im Mantis-Tracker die Datei &quot;Codepage254.php&quot; hinzugefügt.

Unter Ubuntu/Debian muss sie in diesen Pfad geladen werden: /usr/share/tine20/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync

bei anderen Systemen entsprechend in:
TINE-INSTALLATION/library/Syncroton/lib/Syncroton/Wbxml/Dtd/ActiveSync

danach ggf. altes &quot;Exchange-Konto&quot; in Outlook entfernen, neu erstellen und glücklich sein.

Vielen Dank für Deine gute Arbeit, Christian!

**Comment by Gloirin** [comment]
**Comment posted by admin4 on 10 Apr 2013 19:54**

Chrtistian 4 Präsident....Es funktioniert!!!!! :o)

**Comment by Gloirin** [comment]
**Comment posted by admin4 on 10 Apr 2013 20:16**

Kleines Update, bei mir funktioniert es soweit sehr gut, das einzige was gerade aufgefallen ist, das alle Unterordner welche neben Gesendete / Gelöschte oder dem Posteingang sind zwar angezeigt werden jedoch leer sind.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 12 Apr 2013 10:56**

Kalender, Aufgaben und Kontakte funktionieren so bei mir, wirklich perfekt!
Wahnsinn wie klein die Datei doch ist, gerade mal ein String und vier Zahlen, und es läuft... vielen Dank für die Codepage254!

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 12 Apr 2013 15:30**

Wtf! :-) Bin immer davon ausgegangen, das unser Parser Code ein Problem hat, weil Codepage 254 nicht dokumentiert ist.

Schön das wir das Problem gemeinsam lösen konnten. Ich nehme die Datei in den Code auf. Es steht auch bald wieder ein Service Release an. Da wird die Datei dann auch enthalten sein.

Danke an alle die an der Lösung dieses Problems mitgeholfen haben.
