### ISSUE TITLE
0007454:
no email reply or forward (iOS/android 4.1.1)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3770]
**Reported by tuxnet on 20 Nov 2012 22:00**

**Version:** Joey (2012.10.1)

Bei Erstellung und Versandversuch oder Antwort und Versandversuch einer Mail per ActiveSync mit einem Anhang (Größe beim mir egal) über ein iPhone 3GS bricht dieses mit der Fehlermeldung &quot;E-Mail konnte nicht gesendet werden!&quot; ab.

Mails ohne Anhang lassen sich jedoch problemlos versenden.

Gleiche Problematik auch mit einem Android 4.1.1-Gerät.

Wenn Mailserver direkt von den mob. Devices (z. B. per SMTP) kontaktiert wird, funktioniert der Mailversand mit Anhängen problemlos.

**Additional information:** Ausgabe von tail -f /var/log/tine20/tine20.log während Versandversuchen:

    a0896 USER - 2012-11-02T22:32:29+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Exception
    a0896 USER - 2012-11-02T22:32:29+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: No entry is registered for key &#039;gal_data_class&#039;
    a0896 USER - 2012-11-02T22:32:29+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Data/Factory.php(57): Syncroton_Registry::get(&#039;gal_data_class&#039;)
    #1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Search.php(53): Syncroton_Data_Factory::factory(&#039;GAL&#039;, Object(Syncroton_Model_Device), Object(DateTime))
    #2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Search-&gt;getResponse()
    #3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
    #4 /usr/share/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
    #5 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
    #6 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
    #7 {main}
    e95a1 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Exception
    e95a1 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: No entry is registered for key &#039;gal_data_class&#039;
    e95a1 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Data/Factory.php(57): Syncroton_Registry::get(&#039;gal_data_class&#039;)
    #1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Search.php(53): Syncroton_Data_Factory::factory(&#039;GAL&#039;, Object(Syncroton_Model_Device), Object(DateTime))
    #2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Search-&gt;getResponse()
    #3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
    #4 /usr/share/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
    #5 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
    #6 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
    #7 {main}
    a6a39 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Exception
    a6a39 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: No entry is registered for key &#039;gal_data_class&#039;
    a6a39 USER - 2012-11-02T22:42:56+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Data/Factory.php(57): Syncroton_Registry::get(&#039;gal_data_class&#039;)
    #1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Search.php(53): Syncroton_Data_Factory::factory(&#039;GAL&#039;, Object(Syncroton_Model_Device), Object(DateTime))
    #2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Search-&gt;getResponse()
    #3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
    #4 /usr/share/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
    #5 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
    #6 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
    #7 {main}
    9b358 USER - 2012-11-02T22:42:57+00:00 CRIT (2): Syncroton_Server::_handlePost::147 unexpected exception occured: Zend_Exception
    9b358 USER - 2012-11-02T22:42:57+00:00 CRIT (2): Syncroton_Server::_handlePost::149 exception message: No entry is registered for key &#039;gal_data_class&#039;
    9b358 USER - 2012-11-02T22:42:57+00:00 CRIT (2): Syncroton_Server::_handlePost::151 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Data/Factory.php(57): Syncroton_Registry::get(&#039;gal_data_class&#039;)
    #1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Search.php(53): Syncroton_Data_Factory::factory(&#039;GAL&#039;, Object(Syncroton_Model_Device), Object(DateTime))
    #2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(130): Syncroton_Command_Search-&gt;getResponse()
    #3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(64): Syncroton_Server-&gt;_handlePost()
    #4 /usr/share/tine20/ActiveSync/Server/Http.php(101): Syncroton_Server-&gt;handle()
    #5 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
    #6 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
    #7 {main}

**Comment by Gloirin** [comment]
Related to #3765

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Nov 2012 09:51**

bug still exists (see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11766&amp;start=10#p44982).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Nov 2012 09:52**

i&#039;ll try to reproduce this with a current iOS.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Nov 2012 16:36**

please test again after replacing your ActiveSync/Server/Http.php with the attached file.

**Comment by Gloirin** [comment]
**Comment posted by tuxnet on 28 Nov 2012 18:10**

Hi Philipp,

the problem was soved by replacing the original file with your attached file.

Good job!! It works fine for me.

Greets, Joerg.
