### ISSUE TITLE
0007486:
iPhones can't sync mails after upgrade to 'Joey'

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3786]
**Reported by weberho on 26 Nov 2012 05:40**

**Version:** Joey (2012.10.2)

Since upgrading to Joey, I&#039;m constantly getting the following error:

Nov 25 02:31:58 s3 Tine 2.0[19744]: Tinebase_Core::errorHandler::426 include(Syncope/Model/Folder.php): failed to open stream: No such file or directory in /usr/share/tine20/library/Zend/Loader.php::83 (2)
Nov 25 02:31:58 s3 Tine 2.0[19744]: Tinebase_Core::errorHandler::426 include(): Failed opening &#039;Syncope/Model/Folder.php&#039; for inclusion (include_path=&#039;/usr/share/tine20:/usr/share/tine20/library:.:/usr/share/php5:/usr/share/php5/PEAR&#039;) in /usr/share/tine20/library/Zend/Loader.php::83 (2)
Nov 25 02:32:58 s3 Tine 2.0[19744]: Tinebase_Core::errorHandler::426 PDO::quote() expects parameter 1 to be string, object given in /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php::296 (2)
Nov 25 02:32:58 s3 Tine 2.0[19744]: Syncroton_Server::_handlePost::159 unexpected exception occured: Zend_Db_Statement_Exception
Nov 25 02:32:58 s3 Tine 2.0[19744]: Syncroton_Server::_handlePost::161 exception message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;)&#039; at line 1
Nov 25 02:32:58 s3 Tine 2.0[19744]: Syncroton_Server::_handlePost::163 
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#012#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#012#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#012#3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Backend/ABackend.php(91): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#012#4 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Ping.php(105): Syncroton_Backend_ABackend-&gt;get(Object(__PHP_Incomplete_Class))
#012#5 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(140): Syncroton_Command_Ping-&gt;handle()
#012#6 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#012#7 /usr/share/tine20/ActiveSync/Server/Http.php(104): Syncroton_Server-&gt;handle()
#012#8 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#012#9 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#012#10 {main}

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Nov 2012 09:10**

I think, that issue is in close relation to #0007360; it seem to occure only with syncing iPhones;

Is there a way to log the complete, failing SQL statement?

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 26 Nov 2012 09:23**

That&#039;s strange: include(Syncope/Model/Folder.php)

Syncope is the previous name of Syncroton. I just searched for Syncope in our source code, but could not found it anymore.

Can you please try to find the place where Syncope_Model_Folder will be included?

Hint: Just search/grep for Syncope.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Nov 2012 09:34**

I can&#039;t find it in the source, but there are several occurences in the table tine20_acsync_device;

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Nov 2012 10:30**

Lars, should I truncate the tine20_async tables?

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 26 Nov 2012 10:43**

Just truncate tine20_acsync_device. That should be enough.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Nov 2012 10:48**

After &quot;truncate tine20_acsync_device;&quot; I get the following messages:

04196 kri - 2012-11-26T10:46:12+00:00 CRIT (2): Syncroton_Server::_handlePost::159 unexpected exception occured: Syncroton_Exception_NotFound
04196 kri - 2012-11-26T10:46:12+00:00 CRIT (2): Syncroton_Server::_handlePost::161 exception message: id not found
04196 kri - 2012-11-26T10:46:12+00:00 CRIT (2): Syncroton_Server::_handlePost::163 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/Ping.php(105): Syncroton_Backend_ABackend-&gt;get(false)
#1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(140): Syncroton_Command_Ping-&gt;handle()
#2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#3 /usr/share/tine20/ActiveSync/Server/Http.php(104): Syncroton_Server-&gt;handle()
#4 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#5 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#6 {main}

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Nov 2012 11:17**

This message still occures after I have truncated all &#039;tine20_acsync*&#039; tables except the tine20_acsync_policy table.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 27 Nov 2012 08:35**

Current state is: After truncating the table(s) (I think it would have been enough to truncate tine20_acsync_device), iPhones start syncing eMails again. The log-entry from 7486#c95550 keep occuring in the logs, but the first reported SQL-exceptions disappeared completely.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 28 Nov 2012 12:32**

Can you please post the complete log for such a request?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 29 Nov 2012 08:14**

Do you mean the first issue (which has been resolved after tuncation of the involved table) or the log-entries I still see? This issue should possibly be split into two issues.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 29 Nov 2012 09:42**

I mean the second. I agree that we should split this issue. Please create a new bug report for the remaining problem.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 29 Nov 2012 16:21**

Those messages have stopped to appear; therefore I can&#039;t upload a log. I don&#039;t have any explanation for that, nothing changed on the server.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 4 Feb 2013 09:24**

Found the source for this problem. A fix is on the way.
