### ISSUE TITLE
0007518:
Marking task finished at an Android device doesn't work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3802]
**Reported by csvarer on 29 Nov 2012 08:44**

**Version:** Joey (2012.10.2)

The problem has been described in the following discussion:

http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=11946

Task creation and syncronization works perfectly well both from Android device and webinterface. When you then at the Android device marks a task finished, this information is not synced to the tine system, instead an error message is shown in tine error log. (see link above for error message). You can perfectly well mark the task finished in the webinterface and this information is then also correctly synced to the phone

**Comment by Gloirin** [comment]
**Comment posted by csvarer on 16 Jan 2013 14:58**

I just tested it in the v. 10.3 and the problems seems to still be present. In the tine20 log it is reported like:

0d56d csvarer - 2013-01-16T14:51:58+00:00 WARN (4): Syncroton_Command_Sync::handle::334 failed to update entry exception &#039;InvalidArgumentExce
ption&#039; with message &#039;DateCompleted is no valid property of Syncroton_Model_Task&#039; in /srv/www/vhosts/tinetest/library/Syncroton/lib/Syncroton/
Model/AEntry.php:236
Stack trace:
#0 /srv/www/vhosts/tinetest/library/Syncroton/lib/Syncroton/Model/AEntry.php(301): Syncroton_Model_AEntry-&gt;_getElementProperties(&#039;DateComplet
ed&#039;)
#1 /srv/www/vhosts/tinetest/ActiveSync/Controller/Tasks.php(204): Syncroton_Model_AEntry-&gt;__get(&#039;DateCompleted&#039;)
#2 /srv/www/vhosts/tinetest/ActiveSync/Controller/Abstract.php(335): ActiveSync_Controller_Tasks-&gt;toTineModel(Object(Syncroton_Model_Task), O
bject(Tasks_Model_Task))
#3 /srv/www/vhosts/tinetest/library/Syncroton/lib/Syncroton/Command/Sync.php(321): ActiveSync_Controller_Abstract-&gt;updateEntry(&#039;tasks-root&#039;, 
&#039;c4862a94d286d16...&#039;, Object(Syncroton_Model_Task))
#4 /srv/www/vhosts/tinetest/library/Syncroton/lib/Syncroton/Server.php(140): Syncroton_Command_Sync-&gt;handle()
#5 /srv/www/vhosts/tinetest/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#6 /srv/www/vhosts/tinetest/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#7 /srv/www/vhosts/tinetest/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#8 /srv/www/vhosts/tinetest/index.php(17): Tinebase_Core::dispatchRequest()
#9 {main}

**Comment by Gloirin** [comment]
**Comment posted by csvarer on 16 Jan 2013 15:28**

I just tried to update line 324 in file

ActiveSync/Controller/Tasks.php 

from 

                       $task-&gt;$tine20Property = $data-&gt;DateCompleted;
 
to

                       $task-&gt;$tine20Property = $data-&gt;dateCompleted;
 
and it seems to solve the problem, I think this field should be spelled with none capital &quot;Date&quot;, could that be correct?
