### ISSUE TITLE
0007548:
Cannot create new events: wrong integer value for 'seq'

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3816]
**Reported by GWI on 3 Dec 2012 21:08**

**Version:** git master

beim anlegen neuer Termine bricht tine zusammen,
fehlermeldung im LOG:

58ddd roellig@roellig-ltd.de - 2012-12-03T20:52:37+00:00 WARN (4): Tinebase_Server_Json::_handleException::230 Zend_Db_Statement_Exception -&gt; SQLSTATE[HY000]: General error: 1366 Falscher integer-Wert: &#039;&#039; f?r Feld &#039;seq&#039; in Zeile 1
 58ddd roellig@roellig-ltd.de - 2012-12-03T20:52:37+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::297 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Tinebase/Backend/Sql/Abstract.php(817): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_cal_even...&#039;, Array)
#5 .../Calendar/Backend/Sql.php(97): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Calendar_Model_Event))
#6 .../Tinebase/Controller/Record/Abstract.php(461): Calendar_Backend_Sql-&gt;create(Object(Calendar_Model_Event))
#7 .../Calendar/Controller/Event.php(177): Tinebase_Controller_Record_Abstract-&gt;create(Object(Calendar_Model_Event))
#8 [internal function]: Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), 1)
#9 .../Tinebase/Frontend/Json/Abstract.php(278): call_user_func_array(Array, Array)
#10 .../Calendar/Frontend/Json.php(193): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#11 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1)
#12 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 .../Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#17 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#18 .../index.php(17): Tinebase_Core::dispatchRequest()
#19 {main}

**Comment by Gloirin** [comment]
**Comment posted by GWI on 4 Dec 2012 11:38**

Termine über das Telefon und anschließenden Syncen klappt Perfekt

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Dec 2012 12:45**

konnte es reproduzieren und der fix wird bald im master sein. danke fürs melden.
