### ISSUE TITLE
0007590:
sync_accounts_from_ldap Task throws Exception

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3837]
**Reported by shochdoerfer on 16 Dec 2012 16:05**

**Version:** Joey (2012.10.2)

When calling the sync_accounts_from_ldap Task of setup.php I get the following exception:
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_AccessDenied&#039; with message &#039;User object required to check grants&#039; in /srv/tine20/Tinebase/Controller/Record/Abstract.php:1278
Stack trace:
#0 /srv/tine20/Tinebase/Controller/Record/Abstract.php(318): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;get&#039;)
#1 /srv/tine20/Addressbook/Controller/List.php(86): Tinebase_Controller_Record_Abstract-&gt;get(&#039;0f76ecac57a3c33...&#039;, NULL)
#2 /srv/tine20/Addressbook/Controller/List.php(329): Addressbook_Controller_List-&gt;get(&#039;0f76ecac57a3c33...&#039;)
#3 /srv/tine20/Tinebase/Group.php(212): Addressbook_Controller_List-&gt;createByGroup(Object(Tinebase_Model_Group))
#4 /srv/tine20/Tinebase/Group.php(171): Tinebase_Group::syncListsOfUserContact(Array, &#039;8323db0a48a9dd4...&#039;)
#5 /srv/tine20/Tinebase/User.php(464): Tinebase_Group::syncMemberships(Object(Tinebase_Model_FullUser))
#6 /srv/tine20/Tinebase/User.php(517): Tinebase_User::syncUser(Object(Tinebase_Model_FullUser), Array)
#7 /srv/tine20/Setup/Frontend/Cli.php(29 in /srv/tine20/Tinebase/Controller/Record/Abstract.php on line 1278

**Steps to reproduce:** Just run the following command from the command line:
php setup.php --sync_accounts_from_ldap

**Additional information:** The problem is located in the file Setup/Frontend/Cli.php in the _importAccounts() method. The call of Tinebase_User::syncUsers($options); fails as the first parameter of the Tinebase_User::syncUsers() method should be the $username to sync.

**Comment by Gloirin** [comment]
Related to #3869

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 2 Jan 2013 15:44**

It looks like my assumption was wrong. The root cause is not the call to Tinebase_User::syncUsers($options); but the call to Tinebase_Core::getUser() in the _checkGrant() method in file Tinebase/Controller/Record/Abstract.php - it looks like the method expects a user to be logged in which is not the case when calling the script command line I guess.

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 3 Jan 2013 20:06**

As a fix I changed the foreach loop in Tinebase_User::syncUsers() to:
foreach($users as $user) {
  try {
    // simulating user login
    Zend_Registry::set(Tinebase_Core::USER, $user);
    $user = self::syncUser($user, $options);
  } catch (Tinebase_Exception_NotFound $ten) {
    Tinebase_Core::getLogger()-&gt;crit(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; User {$user-&gt;accountLoginName} not synced: &quot;
      . $ten-&gt;getMessage());
  }
}

The call to Zend_Registry::set() sets the user as logged in user internally and thus the _checkGrant() method of Tinebase_Controller_Record_Abstract gets a valid user returned. Maybe there`s a better fix for the problem at least it seems to work for me.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Feb 2013 15:00**

hi,

i think, this has already been fixed in Joey 2012.10.3 (#7656).

could you please remove your patch and try it again with 2012.10.3?

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 11 Feb 2013 15:37**

Seems to work fine, I do not get the exception message anymore. You can close the issue. Thank you.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Feb 2013 15:46**

ok, thanks for testing :)
