### ISSUE TITLE
0007656:
sync users/groups does not work when switching to LDAP

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3869]
**Reported by pschuele on 10 Jan 2013 09:00**

**Version:** Joey (2012.10.2)

sync users/groups does not work when switching to LDAP

**Additional information:** 4f657 -- none -- - 2013-01-03T22:37:56+00:00 ERR (3): Setup_Controller::_updateAccountsStorage::917 User object required to check grants
4f657 -- none -- - 2013-01-03T22:37:56+00:00 ERR (3): Setup_Controller::_updateAccountsStorage::918 #0 /media/server/www/tine20/tine20/Tinebase/Controller/Record/Abstract.php(318): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Addressbook_Model_List), &#039;get&#039;)
#1 /media/server/www/tine20/tine20/Addressbook/Controller/List.php(86): Tinebase_Controller_Record_Abstract-&gt;get(&#039;75438c4e5eb38f5...&#039;, NULL)
#2 /media/server/www/tine20/tine20/Addressbook/Controller/List.php(329): Addressbook_Controller_List-&gt;get(&#039;75438c4e5eb38f5...&#039;)
#3 /media/server/www/tine20/tine20/Tinebase/Group.php(212): Addressbook_Controller_List-&gt;createByGroup(Object(Tinebase_Model_Group))
#4 /media/server/www/tine20/tine20/Tinebase/Group.php(171): Tinebase_Group::syncListsOfUserContact(Array, &#039;dfcf65d97047cdf...&#039;)
#5 /media/server/www/tine20/tine20/Tinebase/User.php(464): Tinebase_Group::syncMemberships(Object(Tinebase_Model_FullUser))
#6 /media/server/www/tine20/tine20/Tinebase/User.php(517): Tinebase_User::syncUser(Object(Tinebase_Model_FullUser), Array)
#7 /media/server/www/tine20/tine20/Setup/Controller.php(957): Tinebase_User::syncUsers(Array)
#8 /media/server/www/tine20/tine20/Setup/Controller.php(912): Setup_Controller-&gt;_migrateFromSqlAccountsStorage()
#9 /media/server/www/tine20/tine20/Setup/Controller.php(843): Setup_Controller-&gt;_updateAccountsStorage(Array)
#10 /media/server/www/tine20/tine20/Setup/Controller.php(819): Setup_Controller-&gt;_updateAuthentication(Array)
#11 /media/server/www/tine20/tine20/Setup/Frontend/Json.php(241): Setup_Controller-&gt;saveAuthentication(Array)
#12 [internal function]: Setup_Frontend_Json-&gt;saveAuthentication(Array)
#13 /media/server/www/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#14 /media/server/www/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#15 /media/server/www/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#16 /media/server/www/tine20/tine20/Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#17 /media/server/www/tine20/tine20/Setup/Core.php(89): Setup_Server_Json-&gt;handle()
#18 /media/server/www/tine20/tine20/setup.php(14): Setup_Core::dispatchRequest()
#19 {main}

**Comment by Gloirin** [comment]
Related to #2391

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Jan 2013 08:19**

Ok, so it means that we would need a &quot;syncUsers&quot; function that would skip the grant check if that&#039;s during a backend update?

Actually, I&#039;m wondering, do we need grant checks at all for this function? Isn&#039;t it something that is always called by the &quot;root&quot; of Tine and never called by a user?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Jan 2013 09:55**

yup, the grant checking needs to be disabled here. i hope, i&#039;ll find some time for this today.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Jan 2013 11:26**

salut,

please try again with the current master, this problem should be fixed!

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 Jan 2013 13:17**

Guten tag,

It worked! :)

That said, I spotted another problem, I am not sure if it is a bug though.

I have two groups: admin and users.

my main user is etienne, and belonged only to admin so far. (i.e. I have a memberuid field in the LDAP group with &quot;etienne&quot; as a value)

users was empty.

And I was getting the following error:
653ef -- none -- - 2013-01-11T13:04:54+00:00 DEBUG (7): Tinebase_Group_Ldap::addGroupInSyncBackend::517  $dn: cn=users,ou=Group,dc=arrakis,dc=net
653ef -- none -- - 2013-01-11T13:04:54+00:00 ERR (3): Setup_Controller::_updateAccountsStorage::917 0x41 (Object class violation; invalid structural object class chain (posixGroup/groupOfNames)): adding: cn=users,ou=Group,dc=arrakis,dc=net
653ef -- none -- - 2013-01-11T13:04:54+00:00 ERR (3): Setup_Controller::_updateAccountsStorage::918 #0 /media/server/www/tine20/tine20/Tinebase/Group/Ldap.php(519): Zend_Ldap-&gt;add(&#039;cn=users,ou=Gro...&#039;, Array)
#1 /media/server/www/tine20/tine20/Tinebase/Group/Sql.php(362): Tinebase_Group_Ldap-&gt;addGroupInSyncBackend(Object(Tinebase_Model_Group))
#2 /media/server/www/tine20/tine20/Tinebase/Group/Abstract.php(173): Tinebase_Group_Sql-&gt;addGroup(Object(Tinebase_Model_Group))
#3 /media/server/www/tine20/tine20/Tinebase/Group/Abstract.php(115): Tinebase_Group_Abstract-&gt;_getDefaultGroup(&#039;Users&#039;)
#4 /media/server/www/tine20/tine20/Tinebase/Acl/Roles.php(737): Tinebase_Group_Abstract-&gt;getDefaultGroup()
#5 /media/server/www/tine20/tine20/Setup/Controller.php(959): Tinebase_Acl_Roles-&gt;createInitialRoles()
#6 /media/server/www/tine20/tine20/Setup/Controller.php(912): Setup_Controller-&gt;_migrateFromSqlAccountsStorage()
#7 /media/server/www/tine20/tine20/Setup/Controller.php(843): Setup_Controller-&gt;_updateAccountsStorage(Array)
#8 /media/server/www/tine20/tine20/Setup/Controller.php(819): Setup_Controller-&gt;_updateAuthentication(Array)
#9 /media/server/www/tine20/tine20/Setup/Frontend/Json.php(241): Setup_Controller-&gt;saveAuthentication(Array)
#10 [internal function]: Setup_Frontend_Json-&gt;saveAuthentication(Array)
#11 /media/server/www/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /media/server/www/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /media/server/www/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /media/server/www/tine20/tine20/Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#15 /media/server/www/tine20/tine20/Setup/Core.php(89): Setup_Server_Json-&gt;handle()
#16 /media/server/www/tine20/tine20/setup.php(14): Setup_Core::dispatchRequest()
#17 {main}

I had to add a memberuid=etienne attribute in the users group to remove the error. Is it intended?

Cheers!!!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Jan 2013 14:28**

hi Etienne,

I&#039;m not sure about this error. But you could add another bugreport describing the problem.

Closing this task.
