### ISSUE TITLE
0007732:
state contains sort info of a column that has been renamed/deleted

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3907]
**Reported by pschuele on 28 Jan 2013 13:38**

**Version:** Joey (2012.10.3)

state contains sort info of a column that has been renamed/deleted

- maybe we should remove saved states of apps when columns are renamed/deleted

**Additional information:** - for example the user has sorted by &#039;from&#039; and the column has been renamed to &#039;from_email&#039;:

691b0 xxxx - 2013-01-08T10:34:20+00:00 NOTICE (5): 
Tinebase_Server_Json::_handleException::216 Zend_Db_Statement_Exception -&gt; 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 
&#039;felamimail_cache_message.from&#039; in &#039;field list&#039;
691b0 xxxx - 2013-01-08T10:34:20+00:00 NOTICE (5): 
Tinebase_Server_Json::_logExceptionTrace::283 #0 
.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-
&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): 
Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(600): Zend_Db_Adapter_Pdo_Abstract-
&gt;query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(431): Tinebase_Backend_Sql_Abstract-
&gt;_fetch(Object(Zend_Db_Select))
#5 .../Tinebase/Controller/Record/Abstract.php(150): 
Tinebase_Backend_Sql_Abstract-&gt;search(Object(Felamimail_Model_MessageFilter), 
Object(Tinebase_Model_Pagination), false)
#6 .../Tinebase/Frontend/Json/Abstract.php(127): 
Tinebase_Controller_Record_Abstract-
&gt;search(Object(Felamimail_Model_MessageFilter), 
Object(Tinebase_Model_Pagination), false)
#7 .../Felamimail/Frontend/Json.php(157): Tinebase_Frontend_Json_Abstract-
&gt;_search(Array, Array, Object(Felamimail_Controller_Message), 
&#039;Felamimail_Mode...&#039;)
#8 [internal function]: Felamimail_Frontend_Json-&gt;searchMessages(Array, Array)
#9 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, 
Array)
#10 .../Zend/Json/Server.php(558): Zend_Server_Abstract-
&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 .../Tinebase/Server/Json.php(192): Zend_Json_Server-
&gt;handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Server/Json.php(71): Tinebase_Server_Json-
&gt;_handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Core.php(241): Tinebase_Server_Json-&gt;handle()
#15 .../index.php(57): Tinebase_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
Related to #3204

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Feb 2013 12:15**

ask sql schema if column exists (consider joined tables, too).
