### ISSUE TITLE
0007766:
saving of group fails because ldap group memberships out of sync

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3924]
**Reported by pschuele on 5 Feb 2013 15:38**

**Version:** Joey (2012.10.3)

saving of group fails because ldap group memberships out of sync

**Additional information:** fd5fe 0cd90 xxx - 2013-01-30T10:45:52+00:00 NOTICE (5): 
Tinebase_Server_Json::_logExceptionTrace::297 #0 
.../Tinebase/Group/Ldap.php(233): Tinebase_Group_Ldap-&gt;_getAccountsMetaD
ata(Array)
#1 .../Tinebase/Group/Sql.php(149): Tinebase_Group_Ldap-
&gt;setGroupMembersInSyncBackend(&#039;15&#039;, Array)
#2 .../Admin/Controller/Group.php(239): Tinebase_Group_Sql-
&gt;setGroupMembers(&#039;15&#039;, Array)
#3 .../Admin/Frontend/Json.php(649): Admin_Controller_Group-
&gt;update(Object(Tinebase_Model_Group))
#4 [internal function]: Admin_Frontend_Json-&gt;saveGroup(Array, Array)
#5 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, 
Array)
#6 .../Zend/Json/Server.php(558): Zend_Server_Abstract-
&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 .../Tinebase/Server/Json.php(208): Zend_Json_Server-
&gt;handle(Object(Zend_Json_Server_Request))
#9 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-
&gt;_handle(Object(Zend_Json_Server_Request))
#10 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#11 .../index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Feb 2013 09:29**

90f23 pschuele - 2013-02-07T09:27:26+00:00 WARN (4): Tinebase_Server_Json::_handleException::230 Zend_Db_Statement_Exception -&gt; SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`metaways`.`tine20_group_members`, CONSTRAINT `tine20_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine20_accounts` (`id`))
 90f23 pschuele - 2013-02-07T09:27:26+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::297 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Tinebase/Group/Sql.php(177): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_group_me...&#039;, Array)
#5 .../Tinebase/Group/Sql.php(152): Tinebase_Group_Sql-&gt;setGroupMembersInSqlBackend(&#039;15&#039;, Array)
#6 .../Admin/Controller/Group.php(239): Tinebase_Group_Sql-&gt;setGroupMembers(&#039;15&#039;, Array)
#7 .../Admin/Frontend/Json.php(649): Admin_Controller_Group-&gt;update(Object(Tinebase_Model_Group))
#8 [internal function]: Admin_Frontend_Json-&gt;saveGroup(Array, Array)
#9 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 .../Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#15 .../index.php(17): Tinebase_Core::dispatchRequest()
#16 {main}
