### ISSUE TITLE
0007768:
Sieve - Vacation notify frequency not being set (Cyrus)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3925]
**Reported by AdrianSt on 5 Feb 2013 19:23**

**Version:** Joey (2012.10.3)

The vacation notify frequency cannot being set to other values than 7 days.
My setup is using Cyrus IMAPd 2.4.12 and its Sieve.

**Steps to reproduce:** -Open Felamimail
-Edit vacation message
-Advanced: Only send all X days to the same sender

**Additional information:** 8a2c7 aa0c0 ast - 2013-02-05T19:20:06+00:00 DEBUG (7): Felamimail_Backend_SieveFactory::factory::41 Connecting to server localhost:4190 (secure: none) with user blah@foo.com
8a2c7 aa0c0 ast - 2013-02-05T19:20:06+00:00 NOTICE (5): Tinebase_Core::errorHandler::450 Undefined offset: 1 in /usr/share/tine20/Zend/Mail/Protocol/Sieve.php::420 (8)
8a2c7 aa0c0 ast - 2013-02-05T19:20:06+00:00 NOTICE (5): Tinebase_Core::errorHandler::451 #0 /usr/share/tine20/Zend/Mail/Protocol/Sieve.php(420): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;/usr/share/tine...&#039;, 420, Array)
#1 /usr/share/tine20/Felamimail/Controller/Sieve.php(308): Zend_Mail_Protocol_Sieve-&gt;capability()
#2 /usr/share/tine20/Felamimail/Controller/Sieve.php(217): Felamimail_Controller_Sieve-&gt;_checkCapabilities(Object(Felamimail_Model_Sieve_Vacation))
#3 /usr/share/tine20/Felamimail/Frontend/Json.php(480): Felamimail_Controller_Sieve-&gt;setVacation(Object(Felamimail_Model_Sieve_Vacation))
#4 [internal function]: Felamimail_Frontend_Json-&gt;saveVacation(Array)
#5 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 /usr/share/tine20/Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 /usr/share/tine20/Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#10 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#11 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}
8a2c7 aa0c0 ast - 2013-02-05T19:20:06+00:00 INFO (6): Felamimail_Controller_Sieve::setVacation::228 Put updated vacation SIEVE script felamimail2.0

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Feb 2013 14:55**

hi AdrianSt,

it looks like your cyrus delivers its capabilities in a different format.

i attached a modified Zend/Mail/Protocol/Sieve.php file. please replace the existing file, try again and show me the debug log.

**Comment by Gloirin** [comment]
**Comment posted by AdrianSt on 11 Feb 2013 15:15**

Hi pschuele,

This is what I&#039;ve got with your modified Sieve.php:

fe483 -- none -- - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Core::setupLogger::554 Logger initialized
fe483 -- none -- - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Core::dispatchRequest::162 Client transaction b753d220f3f7bdfe634bf1cf1f7f5fa5a376dfc1
fe483 b753d -- none -- - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Core::setupCache::620 cache of backend type &#039;Memcached&#039; enabled
fe483 b753d -- none -- - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Core::setSessionBackend::847 Session of backend type &#039;File&#039; configured.
fe483 b753d ast - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Core::setupUserLocale::1033 Setting user locale: de
fe483 b753d ast - 2013-02-11T15:13:06+00:00 WARN (4): Tinebase_Core::setExecutionLifeTime::1104 max_execution_time(300) is too low. Can&#039;t set limit to 0 because of safe mode restrictions.
fe483 b753d ast - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_User::setBackendType::234 Setting backend type to Ldap
fe483 b753d ast - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_Server_Json::_handle::164 is JSON request. method: Felamimail.saveVacation
fe483 b753d ast - 2013-02-11T15:13:06+00:00 INFO (6): Tinebase_User::factory::195 Created user backend of type Ldap
fe483 b753d ast - 2013-02-11T15:13:07+00:00 NOTICE (5): Tinebase_Core::errorHandler::450 Undefined offset: 1 in /usr/share/tine20/Zend/Mail/Protocol/Sieve.php::423 (8)
fe483 b753d ast - 2013-02-11T15:13:07+00:00 NOTICE (5): Tinebase_Core::errorHandler::451 #0 /usr/share/tine20/Zend/Mail/Protocol/Sieve.php(423): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;/usr/share/tine...&#039;, 423, Array)
#1 /usr/share/tine20/Felamimail/Controller/Sieve.php(308): Zend_Mail_Protocol_Sieve-&gt;capability()
#2 /usr/share/tine20/Felamimail/Controller/Sieve.php(217): Felamimail_Controller_Sieve-&gt;_checkCapabilities(Object(Felamimail_Model_Sieve_Vacation))
#3 /usr/share/tine20/Felamimail/Frontend/Json.php(480): Felamimail_Controller_Sieve-&gt;setVacation(Object(Felamimail_Model_Sieve_Vacation))
#4 [internal function]: Felamimail_Frontend_Json-&gt;saveVacation(Array)
#5 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 /usr/share/tine20/Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 /usr/share/tine20/Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#10 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#11 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}
fe483 b753d ast - 2013-02-11T15:13:07+00:00 INFO (6): Felamimail_Controller_Sieve::setVacation::228 Put updated vacation SIEVE script felamimail2.0
fe483 b753d ast - 2013-02-11T15:13:07+00:00 INFO (6): Felamimail_Controller_Sieve::activateScript::410 Activate vacation SIEVE script felamimail2.0
fe483 b753d ast - 2013-02-11T15:13:07+00:00 INFO (6): index.php (36) METHOD: Tinebase_Server_Json::Felamimail.saveVacation / TIME: 0.48548793792725 seconds / MEMORY: 21.75 MBytes / REALPATHCACHESIZE: 0

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Feb 2013 15:35**

oh, i forgot to say that you need to set the loglevel to DEBUG for this.

**Comment by Gloirin** [comment]
**Comment posted by AdrianSt on 12 Feb 2013 12:13**

Whoops, sorry.

This should be more sufficient:
093e0 -- none -- - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::setupLogger::554 Logger initialized
093e0 -- none -- - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::306 Loading all configs for app Tinebase
093e0 -- none -- - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::313 Found 18 configs.
093e0 -- none -- - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::setupLogger::554 Logger initialized
093e0 -- none -- - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::dispatchRequest::162 Client transaction 894269cd5084dccd21bcfa6f92a46b61c2d47e81
093e0 89426 -- none -- - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::setupCache::620 cache of backend type &#039;File&#039; enabled
093e0 89426 -- none -- - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::setSessionBackend::847 Session of backend type &#039;File&#039; configured.
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::98 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::994 given localeString &#039;auto&#039;
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1003 session value: en
093e0 89426 ast - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Core::setupUserLocale::1033 Setting user locale: en
093e0 89426 ast - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_User::setBackendType::234 Setting backend type to Ldap
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Group::getInstance::71 groups backend: Ldap
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1045 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
093e0 89426 ast - 2013-02-12T12:11:45+00:00 DEBUG (7): Tinebase_Server_Json::handle::67 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Felamimail.saveVacation
            [params] =&gt; Array
                (
                    [recordData] =&gt; Array
                        (
                            [creation_time] =&gt;
                            [created_by] =&gt;
                            [last_modified_time] =&gt;
                            [last_modified_by] =&gt;
                            [is_deleted] =&gt;
                            [deleted_time] =&gt;
                            [deleted_by] =&gt;
                            [container_id] =&gt;
                            [id] =&gt; 382134f587297fc4aac80a41b51aaa6f31b4594d
                            [reason] =&gt; Test der Abwesenheitsnotiz
                            [enabled] =&gt; 1
                            [days] =&gt; 3
                            [start_date] =&gt;
                            [end_date] =&gt;
                            [contact_ids] =&gt; Array
                                (
                                )

                            [template_id] =&gt;
                            [signature] =&gt;
                            [mime] =&gt; multipart/alternative
                            [customfields] =&gt; Array
                                (
                                )

                        )

                )

            [id] =&gt; 3
        )

)

093e0 89426 ast - 2013-02-12T12:11:45+00:00 INFO (6): Tinebase_Server_Json::_handle::164 is JSON request. method: Felamimail.saveVacation
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User::getInstance::137 accounts backend: Ldap
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::388 Registering Tinebase_EmailUser_Imap_Cyrus plugin.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::388 Registering Tinebase_EmailUser_Smtp_LdapQmailSchema plugin.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::388 Registering Tinebase_User_Plugin_Samba plugin.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User_Ldap::registerLdapPlugin::184 Registering Tinebase_EmailUser_Smtp_LdapQmailSchema LDAP plugin.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_User_Ldap::registerLdapPlugin::184 Registering Tinebase_User_Plugin_Samba LDAP plugin.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 INFO (6): Tinebase_User::factory::195 Created user backend of type Ldap
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_EmailUser_Imap_Cyrus::inspectGetUserByProperty::123 Got quota: Array
(
)

093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::306 Loading all configs for app Addressbook
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::313 Found 1 configs.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_Config::getConfig::673 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_CustomField::_getCustomFields::557 Fetched 0 customfield values.
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Felamimail_Backend_SieveFactory::factory::41 Connecting to server localhost:4190 (secure: none) with user ast@zer0.de
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Tinebase_EmailUser_Imap_Cyrus::inspectGetUserByProperty::123 Got quota: Array
(
)

093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Zend_Mail_Protocol_Sieve::capability::418 Array
(
    [0] =&gt; Array
        (
            [0] =&gt; IMPLEMENTATION
            [1] =&gt; Cyrus timsieved v2.4.12-Debian-2.4.12-2
        )

    [1] =&gt; Array
        (
            [0] =&gt; SIEVE
            [1] =&gt; comparator-i;ascii-numeric fileinto reject vacation imapflags notify envelope relational regex subaddress copy
        )

    [2] =&gt; Array
        (
            [0] =&gt; UNAUTHENTICATE
        )

)

093e0 89426 ast - 2013-02-12T12:11:46+00:00 NOTICE (5): Tinebase_Core::errorHandler::450 Undefined offset: 1 in /usr/share/tine20/Zend/Mail/Protocol/Sieve.php::423 (8)
093e0 89426 ast - 2013-02-12T12:11:46+00:00 NOTICE (5): Tinebase_Core::errorHandler::451 #0 /usr/share/tine20/Zend/Mail/Protocol/Sieve.php(423): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;/usr/share/tine...&#039;, 423, Array)
#1 /usr/share/tine20/Felamimail/Controller/Sieve.php(308): Zend_Mail_Protocol_Sieve-&gt;capability()
#2 /usr/share/tine20/Felamimail/Controller/Sieve.php(217): Felamimail_Controller_Sieve-&gt;_checkCapabilities(Object(Felamimail_Model_Sieve_Vacation))
#3 /usr/share/tine20/Felamimail/Frontend/Json.php(480): Felamimail_Controller_Sieve-&gt;setVacation(Object(Felamimail_Model_Sieve_Vacation))
#4 [internal function]: Felamimail_Frontend_Json-&gt;saveVacation(Array)
#5 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#6 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#7 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#8 /usr/share/tine20/Tinebase/Server/Json.php(208): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#9 /usr/share/tine20/Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#10 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
#11 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}
093e0 89426 ast - 2013-02-12T12:11:46+00:00 INFO (6): Felamimail_Controller_Sieve::setVacation::228 Put updated vacation SIEVE script felamimail2.0
093e0 89426 ast - 2013-02-12T12:11:46+00:00 DEBUG (7): Felamimail_Controller_Sieve::_putScript::360 #Generated by Felamimail_Sieve
require [&quot;fileinto&quot;,&quot;reject&quot;,&quot;vacation&quot;];

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Feb 2013 09:51**

ah, i see the problem:

    [2] =&gt; Array
        (
            [0] =&gt; UNAUTHENTICATE
        )

tine expects a second element in this array. i&#039;ll fix that.

thanks for helping to debug this!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Feb 2013 13:03**

please try again with the attached Zend/Mail/Protocol/Sieve.php. it should fix the error.

**Comment by Gloirin** [comment]
**Comment posted by AdrianSt on 14 Feb 2013 16:00**

The script for Sieve is being generated as it should be.
But unfortunately the feedback in Felamimail still shows 7 Days

vacation :days 3 :addresses [&quot;ast@zer0.de&quot;] text:
Test der Abwesenheitsnotiz

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Mar 2013 16:07**

problem should be fixed now.

if you like to try:

-            -&gt;setDays((is_int($this-&gt;days) &amp;&amp; $this-&gt;days &gt; 0) ? $this-&gt;days : 7)
+            -&gt;setDays(($this-&gt;days &amp;&amp; $this-&gt;days &gt; 0) ? $this-&gt;days : 7)

in Felamimail/Model/Sieve/Vacation.php

**Comment by Gloirin** [comment]
**Comment posted by AdrianSt on 16 Mar 2013 12:32**

This does indeed fix the problem now.
