### ISSUE TITLE
0007870:
Can't send mail without subject

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#3975]
**Reported by lab-at-nohl on 20 Feb 2013 21:12**

**Version:** Joey (2012.10.3)

ActiveSync Version 14.1 can&#039;t send mails without subject. 

**Steps to reproduce:** Send mail from Android (stock 4.1.2 mail client) - make sure your client isn&#039;t replacing &quot;&quot; with &quot;(no subject)&quot;. 

- without subject: mail isn&#039;t sent
- with subject: works

In my testings it doesn&#039;t matter if mail has a body because it is convertet to base64 anyway. 

Compare the logs in &quot;Additional Informations&quot;: 1) ERROR, 2) WORKING

**Additional information:** 1) Debug-Log WITHOUT subject (but text)
---------------------------------------
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Syncroton_Server::_handlePost::126 xml request:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;SendMail xmlns=&quot;uri:ComposeMail&quot;&gt;
  &lt;ClientId&gt;SendMail-26221086029055&lt;/ClientId&gt;
  &lt;SaveInSentItems/&gt;
  &lt;Mime&gt;Date: Wed, 20 Feb 2013 21:45:34 +0100
Message-ID: &lt;2yq13hpnu0192ivw945eq5sr.1361393134015@email.android.com&gt;
From: johannes.nohl@knet
To: Johannes Nohl &lt;johannes.nohl@wde&gt;
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

dGVzdA==
&lt;/Mime&gt;
&lt;/SendMail&gt;

8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2013-02-20 20:45:35
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Syncroton_Command_SendMail::handle::66 saveInSent: 1
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::306 Loading all configs for app Addressbook
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::313 Found 1 configs.
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Tinebase_Config::getConfig::673 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Tinebase_CustomField::_getCustomFields::557 Fetched 0 customfield values.
8c756 johannes - 2013-02-20T20:45:35+00:00 CRIT (2): Syncroton_Server::_handlePost::159 unexpected exception occured: Zend_Mail_Exception
8c756 johannes - 2013-02-20T20:45:35+00:00 CRIT (2): Syncroton_Server::_handlePost::161 exception message: no Header with Name subject or subject found
8c756 johannes - 2013-02-20T20:45:35+00:00 CRIT (2): Syncroton_Server::_handlePost::163 #0 /var/www/tine/ActiveSync/Controller/Email.php(347): Zend_Mail_Part-&gt;getHeader(&#039;subject&#039;)
#1 /var/www/tine/library/Syncroton/lib/Syncroton/Command/SendMail.php(79): ActiveSync_Controller_Email-&gt;sendEmail(&#039;Date: Wed, 20 F...&#039;, true)
#2 /var/www/tine/library/Syncroton/lib/Syncroton/Server.php(142): Syncroton_Command_SendMail-&gt;getResponse()
#3 /var/www/tine/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#4 /var/www/tine/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#5 /var/www/tine/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()
#6 /var/www/tine/index.php(17): Tinebase_Core::dispatchRequest()
#7 {main}
8c756 johannes - 2013-02-20T20:45:35+00:00 INFO (6): Tinebase_Controller_Record_Abstract::update::633 Update Tinebase_Model_AccessLog
8c756 johannes - 2013-02-20T20:45:35+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_updateACLCheck::695 Doing ACL check ...
8c756 johannes - 2013-02-20T20:45:35+00:00 INFO (6): index.php (36) METHOD: ActiveSync_Server_Http::POST / TIME: 0.32873201370239 seconds / MEMORY: 21.25 MBytes / REALPATHCACHESIZE: 16339

2) Debug-Log WITH SUBJECT (no text) - WORKS
-------------------------------------------
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Syncroton_Server::_handlePost::126 xml request:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;SendMail xmlns=&quot;uri:ComposeMail&quot;&gt;
  &lt;ClientId&gt;SendMail-26200530456545&lt;/ClientId&gt;
  &lt;SaveInSentItems/&gt;
  &lt;Mime&gt;Date: Wed, 20 Feb 2013 21:45:13 +0100
Subject: test
Message-ID: &lt;6yded7o8kfos9oue77napwuv.1361393113590@email.android.com&gt;
From: johannes.nohl@knet
To: Johannes Nohl &lt;johannes.nohl@wde&gt;
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

&lt;/Mime&gt;
&lt;/SendMail&gt;

59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2013-02-20 20:45:14
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Syncroton_Command_SendMail::handle::66 saveInSent: 1
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::306 Loading all configs for app Addressbook
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::313 Found 1 configs.
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Tinebase_Config::getConfig::673 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Tinebase_CustomField::_getCustomFields::557 Fetched 0 customfield values.
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): ActiveSync_Controller_Email::sendEmail::347 Send Message with subject test (saveInSent: 1)
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::sendZendMail::313 Sending message with subject test
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_setMailFrom::376 Set from for mail: johannes.nohl@knet / Johannes Nohl
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_setMailHeaders::430 Setting mail headers
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_sendMailViaTransport::197 About to send message via SMTP ...
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): Tinebase_Smtp::createDefaultTransport::70 Setting default SMTP transport. Hostname: localhost
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): Tinebase_Smtp::setDefaultTransport::107 Setting SMTP transport: Zend_Mail_Transport_Smtp
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_sendMailViaTransport::199 successful.
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::42 Connecting to server localhost:143 (none) with username johannes
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Backend_Imap::connectAndLogin::103 CONNECT TIME: 0.00063610076904297 seconds
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Backend_Imap::connectAndLogin::104 LOGIN TIME: 0.00078105926513672 seconds
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::518 Getting capabilities of account johannes.nohl@knet
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::531 Updating capabilities for account: johannes.nohl@knet
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Account::getSystemFolder::678 Found system folder: Sent
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_saveInSent::281 About to save message in sent folder (Sent) ...
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): Felamimail_Controller_Message_Send::_saveInSent::284 Saved sent message in &quot;Sent&quot;.
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): Tinebase_Controller_Record_Abstract::update::633 Update Tinebase_Model_AccessLog
59f02 johannes - 2013-02-20T20:45:14+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_updateACLCheck::695 Doing ACL check ...
59f02 johannes - 2013-02-20T20:45:14+00:00 INFO (6): index.php (36) METHOD: ActiveSync_Server_Http::POST / TIME: 0.45768094062805 seconds / MEMORY: 24.25 MBytes / REALPATHCACHESIZE: 16339

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Feb 2013 13:37**

should be fixed in 2012.10.4. if not, please reopen this bugreport.
