### ISSUE TITLE
0007954:
Attachments in synced emails can't be downloaded

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4017]
**Reported by robi on 28 Feb 2013 12:24**

**Version:** Joey (2012.10.4)

On my Android 4.0.4 phone, ActiveSync works fine, except one thing: can&#039;t download the attachment of the e-mails. The device shows correctly that there are attachments to the e-mail, the user can see them in the list. Tapping the attachment selected should start its download, it looks like it starts but nothing is downloaded. Progress bar stays at 0% for about a minute, and then gives up trying.

Same with a native Microsoft Exchange server works fine, on the same device, thus the problem must be in Tine20. Log file attached.

The attachment displays perfectly in Felamimail.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Feb 2013 12:57**

could you please test this with Kristina 2013.03.1?

**Comment by Gloirin** [comment]
**Comment posted by robi on 1 Mar 2013 10:57**

Tested, exactly the same behaviour with Kristina 2013.03.1, attached a new logfile.

Even updated the phone to Android 4.1.1, issue still exists with tine20.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 1 Mar 2013 16:18**

Please try to replace

const LONGID_DELIMITER = &quot;\xe2\x87\x94&quot;; # ?

with 

const LONGID_DELIMITER = &quot;§&quot;;

in ActiveSync/Controller/Abstract.php. After you made the changes send yourself a new email with an attachment and try to download the attachment.

**Comment by Gloirin** [comment]
**Comment posted by robi on 1 Mar 2013 16:33**

Replaced as requested.

Now it behaves differently: the Android client immediately shows &quot;Cannot download attachment&quot; error message (earlier it timed out).

See attached log activesync_attachment_not_downloading_kristina_patch1a.log.txt

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 1 Mar 2013 16:41**

Let&#039;s try something different.

Please change the LONGID_DELIMITER to &#039;#&#039;.

const LONGID_DELIMITER = &quot;#&quot;;

After that change you should see the # in the logfile. Search for attachmentName.

[attachmentName] =&gt; 9944a2a0f5c8affd46702db9f10f49530d9fdca3#2

Be aware that this change only works for emails send to the phone after you made the change.

Somehow the LONGID_DELIMITER changes on it&#039;s way to the phone and back to Tine 2.0 again.

**Comment by Gloirin** [comment]
**Comment posted by robi on 1 Mar 2013 17:03**

Done.

Sttill not OK :(

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 1 Mar 2013 17:13**

Maybe we send the wrong data to the phone. Please left the LONGID_DELIMITER set to #.

But please capture more data from the logfile. There must be a Sync command before the Fetch command. Please capture the part where the email is send to the phone (Sync command) and where the phone tries to download the attachment(Fetch or GetAttachment command).

This way we can see, if we send the phone a broken id already.

**Comment by Gloirin** [comment]
**Comment posted by robi on 1 Mar 2013 18:08**

Strange!

Now a new e-mail with attachment worked fine! The old ones don&#039;t.

With const LONGID_DELIMITER = &quot;#&quot;;, here&#039;s the log attached.

But still can&#039;t download attachment of the old ones.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 2 Mar 2013 09:30**

The change will work for new emails only.

 Try to delete the account on your phone and add it again. This will force a resync of all data. After that you will be able to download all attachments.

Can you please try if 

const LONGID_DELIMITER = &quot;§&quot;;

is working too?

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Mar 2013 12:21**

Tested: sent two new e-mails with attachments from a different account, and with &quot;#&quot; it works, with &quot;§&quot; it does not work.

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Mar 2013 12:29**

Thanks for the tip about removing and re-adding the Exchange account on the phone. That allowed me to download old attachments aswell.

LONGID_DELIMITER = &quot;#&quot;; seems to be the solution.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 10 Mar 2013 13:09**

I tried to reproduce this problem with other phones, but I can&#039;t.

Which phone do you use?
And can you please tell me something about your system Tine 2.0 is running on? Something like OS, PHP version, Apache and so on.

**Comment by Gloirin** [comment]
**Comment posted by robi on 14 Mar 2013 12:46**

Unfortunately I noticed that the attachment fix broke something else: messages&#039; read status doesn&#039;t update on the phone anymore. (if I read a message in the e-mail client on a PC, it doesn&#039;t change status to read on the phone).

:(

I&#039;m using an HTC One S, with stock Android v. 4.1.1.

Tine runs on a dedicated virtual machine running Ubuntu 10.04.4 LTS, Apache/2.2.14, PHP Version 5.4.12-1~lucid+1. Please find attached my phpinfo() (sensitive data removed).

**Comment by Gloirin** [comment]
**Comment posted by robi on 15 Mar 2013 09:21**

Reverted to the original setting in Tine.

Unfortunately the Attachments can&#039;t be downloaded issue reproduces on an HTC Desire S too, with Android 4.0.4. :-(

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 20 Mar 2013 14:24**

I&#039;m unable to reproduce this problem on any of our test servers and test devices.

But I just discovered that your system is running PHP 5.4. Maybe that&#039;s the problem.

I&#039;ll check that.

In the meantime, can you post a full log, where I can see how the e-mail got synchronized to the phone and see also the request where the phone tries to download the attachment.

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Apr 2013 13:31**

Log attached. It contains info following these steps:
- deleted activesync profile from the phone
- enabled logging
- added activesync profile to the phone
- synced with default settings (3 days earlier, etc)
- extended e-mail sync period to 14 days + added imap subfolders
- synced again
- trying to open unsuccessfully a couple of attachments from different e-mails
- disabled logging

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Apr 2013 13:39**

Might happened during the logging procedure that a desktop carddav/caldav client tried to synk too, I hope that won&#039;t cause problems for debugging.

**Comment by Gloirin** [comment]
**Comment posted by robi on 25 Jun 2013 11:47**

Guys this is still a problem in Kristina (2013.03.5) too.

I originally thought that it may be a problem with my setup, but it&#039;s not - I installed a brand new Ubuntu Server especially for this, deleted the ActiveSync account from all the phones and re-added - issue still there.

**Comment by Gloirin** [comment]
**Comment posted by robi on 25 Jun 2013 15:53**

Please find attached a new debug log.

I request developer who takes care of this, to remove attachments when he/she gets it, because they may contain sensitive data. Thanks.

**Comment by Gloirin** [comment]
**Comment posted by robi on 25 Jun 2013 15:54**

ISSUE STILL UNRESOLVED

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Jul 2013 09:30**

we&#039;ll have a look soon. thanks for the logfiles and for testing + reporting.

**Comment by Gloirin** [comment]
**Comment posted by robi on 22 Aug 2013 13:40**

Still in v.2013.03.7

**Comment by Gloirin** [comment]
**Comment posted by robi on 15 Nov 2013 12:04**

Still issue in 2013.10.1

**Comment by Gloirin** [comment]
**Comment posted by robi on 11 May 2014 09:41**

Since the reported problem wasn&#039;t fixed for almost a year, and this is also trivially important in our setup, we fixed it by migrating from Tine to Kolab. Sorry.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 May 2014 09:06**

moving this to known bugs. software updates of devices should fix this :)

**Comment by Gloirin** [comment]
**Comment posted by robi on 15 May 2014 10:16**

Sorry but this is not a device problem. We&#039;ve tested various devices with Android versions between 4.0.4 and 4.4 (ICS, JB and KK), all experience the same issue with Tine20. With Kolab and MS Exchange servers the same devices are able to handle attachments without problems.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 May 2014 11:26**

ah, sorry, i meant &quot;software update of your server&quot;.

did you update your server in the meantime? maybe this is only a problem in the old version of ubuntu that you are running. we could not reproduce this on our servers.

**Comment by Gloirin** [comment]
**Comment posted by robi on 15 May 2014 11:37**

Yes we&#039;re using Ubuntu 12.04 kept up to date with the latest supported LTS kernel (3.11.0-20) and packages.

**Comment by Gloirin** [comment]
**Comment posted by emersonfaria on 19 Jun 2015 18:17**

Samsung Galaxy S5 was not downloading attachments.

I found some discussions in the Horde and Zarafa communities that addressed this behavior. It seems that is a problem related to 14.1 version of the protocol.
https://jira.zarafa.com/browse/ZP-469
https://jira.zarafa.com/browse/ZP-263

I obtained the algorithm from the Horde community.
https://github.com/horde/horde/blob/master/framework/ActiveSync/lib/Horde/ActiveSync/Request/ItemOperations.php

Try this:

https://gerrit.tine20.org/syncroton/#/c/277/

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Jun 2015 20:07**

thanks, Emerson.

I&#039;ll ask Lars if he could review the change.

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 22 Jun 2015 19:11**

I have the same issue with my HTC Desire HD with Android 4.0.4, HTC Sense 4.1 &amp; Android 5.1.1,  CyanogenMod 12.1 Nightlie (same device). With the same Tine Account on iPhone 6 or Android 2.3.5 the download of the attachments work!

Is there any fix that i can test?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Jun 2015 08:06**

i attached a fixed vendor/syncroton/syncroton/lib/Syncroton/Command/ItemOperations.php

please test ... :)

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 25 Jun 2015 14:29**

I updated the change in Gerrit. 

@emersonfaria: Please review.

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 30 Jun 2015 09:05**

@pschuele I replaced the ItemOperations.php with my, but not working wit Android 4.0.4. Same es before. I have Tine 2.0, 2014.09.10

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Jul 2015 08:14**

@robi: could you please test again with the upcoming release?
@gongoscho: please test with the new release, too. but maybe there is still a problem with Android 4.0.4 that is not solved yet. you could open a new issue for that.

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 8 Jul 2015 11:15**

Same es before now with new release 2015.07.1 and new clean installation

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 13 Oct 2015 09:19**

I found errors in the tine log (level: debug). I changed the host, path in the log:

a624b name@domain.tld - 2015-10-12T21:41:28+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined offset: 1 in /www/htdocs/v12345/www/domain/test/tine/Felamimail/Frontend/ActiveSync.php::253 (8)
a624b name@domain.tld - 2015-10-12T21:41:28+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /www/htdocs/v12345/www/domain/test/tine/Felamimail/Frontend/ActiveSync.php(253): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;/www/htdocs/v14...&#039;, 253, Array)

a624b name@domain.tld - 2015-10-12T21:41:28+00:00 ERR (3): Syncroton_Server::_handlePost::190 Could not encode output: exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: Invalid character at line 3&#039; in /www/htdocs/v12345/www/domain/test/tine/vendor/syncroton/syncroton/lib/Syncroton/Wbxml/Encoder.php:174

96f04 name@domain.tld - 2015-10-12T21:41:29+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::42 Connecting to server v12345.kasserver.com:143 (TLS) with username name@domain.tld
96f04 name@domain.tld - 2015-10-12T21:41:29+00:00 DEBUG (7): Felamimail_Backend_Imap::connectAndLogin::127 CONNECT TIME: 0.00483298301697 seconds
96f04 name@domain.tld - 2015-10-12T21:41:29+00:00 DEBUG (7): Felamimail_Backend_Imap::connectAndLogin::128 LOGIN TIME: 0.00261187553406 seconds




My System:
2015.07.4 + BUG 0011338 (Application.php &amp; Abstract.php)
MySQL 5.6.24
PHP 5.5.26
Host: all-inkl

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Oct 2015 13:42**

@gongoscho: i uploaded a patched version of Felamimail/Frontend/ActiveSync.php that should fix your problem with the undefined index. but i&#039;m not sure if this fixes the attachment problem in general.

could you have another look into the logfile? the line before the error (with &quot;fileReference&quot;) is missing from your log snippet. it would be good to know how this string looks like...

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 16 Oct 2015 13:05**

I uploaded the log (with patched activesync.php), when i klick on my htc to download a attachment. it is the full log. i chagend the ip, host, domain, mail and path.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Oct 2015 08:35**

ok, thanks. I&#039;ll check that in the next days.

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 28 Mar 2016 13:27**

Same with Egon v2016.03.1

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 6 Jun 2016 13:11**

Problem only occurs if moved to subfolder.

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 12 Jul 2017 11:40**

Hi,

is there any other idea what we can do to fix it? :-( With Version: 2016.09 i have in log (Loglevel 4) this error:

57e03 mail@domain.at - 2017-07-12T11:35:34+00:00 ERR (3): Syncroton_Server::_handlePost::192 Could not encode output: exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: Invalid character at line 3&#039; in /www/htdocs/www/domain/test/tine/vendor/syncroton/syncroton/lib/Syncroton/Wbxml/Encoder.php:174
Stack trace:
#0 /www/htdocs/www/domain/test/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(189): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /www/htdocs/www/domain/test/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#2 /www/htdocs/www/domain/test/tine/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#3 /www/htdocs/www/domain/test/tine/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#4 /www/htdocs/www/domain/test/tine/index.php(18): Tinebase_Core::dispatchRequest()
#5 {main}
57e03 mail@domain.at - 2017-07-12T11:35:34+00:00 WARN (4): Syncroton_Server::_handlePost::193 xml response(0):
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;ItemOperations xmlns=&quot;uri:ItemOperations&quot; xmlns:Syncroton=&quot;uri:Syncroton&quot; xmlns:AirSyncBase=&quot;uri:AirSyncBase&quot; xmlns:AirSync=&quot;uri:AirSync&quot; xmlns:Search=&quot;uri:Search&quot;&gt;
&lt;Status&gt;1&lt;/Status&gt;
&lt;Response&gt;
&lt;Fetch&gt;
&lt;Status&gt;1&lt;/Status&gt;
&lt;AirSyncBase:FileReference&gt;f434c137d01ecafe25d78f99becebb01f79175acÔ4&lt;/AirSyncBase:FileReference&gt;
&lt;/Fetch&gt;
&lt;Status&gt;3&lt;/Status&gt;
&lt;/Response&gt;
&lt;/ItemOperations&gt;
 



grEEtZ,
gongoscho

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 12 Jul 2017 11:52**

Debug Log attached.

Try to download a 2,51 KB jpg

**Comment by gongoscho** [comment]
Hi,

same problem with v2018.08.5 [Debug Log](https://github.com/tine20/tine20/files/2531932/Debug.Log.log) 👎 

Any ideas?

grEEtZ

**Comment by paulmhh** [comment]
just 2 notes FYI
the filereference contains a utf8 character: Ô (after 40 characters)
the filereference is longer than 40 characters

**Comment by gongoscho** [comment]
Maybe there is a problem with the MySQL DB Collation? I use Characters like: ý ö ä ü á
