### ISSUE TITLE
0008114:
Re-Syncing users and groups from LDAP throws an exception.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4084]
**Reported by weberho on 26 Mar 2013 11:17**

**Version:** Kristina (2013.03.1)

Re-syncing throws the given exception.

Removing line 284 from Setup/Frontend/Cli.php (Tinebase_Group::syncGroups();) makes the tool re-sync all items correctly (without group sync, I guess).

**Steps to reproduce:** omega:/var/lib/tine20/webroot # php setup.php --verbose --sync_accounts_from_ldap
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;Account Operators&#039; for key &#039;name&#039;&#039; in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /usr/share/tine20/Zend/Db/Table/Abstract.php(1054): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_groups&#039;, Array)
#5 /usr/share/tine20/Tinebase/Group/Sql.php(424): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /usr/share/tine20/Tinebase/Group.php(248): Tinebase_Group_Sql-&gt;addGroupInSqlBackend(Object(Tinebase_Model_Group))
#7 /usr/share/ in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php on line 238

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;Account Operators&#039; for key &#039;name&#039;&#039; in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /usr/share/tine20/Zend/Db/Table/Abstract.php(1054): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_groups&#039;, Array)
#5 /usr/share/tine20/Tinebase/Group/Sql.php(424): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /usr/share/tine20/Tinebase/Group.php(248): Tinebase_Group_Sql-&gt;addGroupInSqlBackend(Object(Tinebase_Model_Group))
#7 /usr/share/ in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 14:22**

please try again with the attached Tinebase/Group.php file. that should fix it.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 14:22**

https://gerrit.tine20.org/tine20/1916

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Apr 2013 10:35**

With that file I get:

# php setup.php --verbose --sync_accounts_from_ldap
PHP Fatal error:  Method name must be a string in /usr/share/tine20/Tinebase/Group.php on line 247

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2013 10:53**

ouch, I&#039;ll fix that ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2013 10:55**

just uploaded a fixed version. sorry for the syntax error.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Apr 2013 13:31**

There is another exception, now:

# php setup.php --verbose --sync_accounts_from_ldap
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_Record_NotDefined&#039; with message &#039;Group not found.&#039; in /usr/share/tine20/Tinebase/Group/Sql.php:610
Stack trace:
#0 /usr/share/tine20/Tinebase/Group/Sql.php(474): Tinebase_Group_Sql-&gt;getGroupById(&#039;165094e8-667a-1...&#039;)
#1 /usr/share/tine20/Tinebase/Group.php(256): Tinebase_Group_Sql-&gt;updateGroupInSqlBackend(Object(Tinebase_Model_Group))
#2 /usr/share/tine20/Setup/Frontend/Cli.php(284): Tinebase_Group::syncGroups()
#3 /usr/share/tine20/Setup/Frontend/Cli.php(60): Setup_Frontend_Cli-&gt;_importAccounts(Object(Zend_Console_Getopt))
#4 /usr/share/tine20/Setup/Server/Cli.php(91): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#5 /usr/share/tine20/Setup/Core.php(89): Setup_Server_Cli-&gt;handle()
#6 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}
  thrown in /usr/share/tine20/Tinebase/Group/Sql.php on line 610

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2013 13:53**

ok, i refactored the logic a little bit:

if a group with the same name (but different id) is found in the sql backend, the current group is deleted and the group from ldap is added.

please test again with the attached file.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Apr 2013 14:28**

How did that happen? But, however, here is the new exception:


# php setup.php --verbose --sync_accounts_from_ldap
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_Backend&#039; with message &#039;Group with id 470c3e5a-4c92-1030-8c93-e914d354739e not found.&#039; in /usr/share/tine20/Tinebase/Group/Sql.php:512
Stack trace:
#0 /usr/share/tine20/Tinebase/Group.php(258): Tinebase_Group_Sql-&gt;deleteGroups(Object(Tinebase_Model_Group))
#1 /usr/share/tine20/Setup/Frontend/Cli.php(284): Tinebase_Group::syncGroups()
#2 /usr/share/tine20/Setup/Frontend/Cli.php(60): Setup_Frontend_Cli-&gt;_importAccounts(Object(Zend_Console_Getopt))
#3 /usr/share/tine20/Setup/Server/Cli.php(91): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#4 /usr/share/tine20/Setup/Core.php(89): Setup_Server_Cli-&gt;handle()
#5 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#6 {main}
  thrown in /usr/share/tine20/Tinebase/Group/Sql.php on line 512

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2013 19:12**

&gt; How did that happen?

i have no idea. maybe the group has been deleted in LDAP and was added again soon afterwards?

nevertheless, i just uploaded new files for you to test. i had to add a new function to Tinebase/Group/Sql.php, so please replace that as well.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2013 06:08**

reopening the task: this needs to be verified by weberho before resolving.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 19 Apr 2013 07:15**

Thank you! The script is running without any output, so I guess it&#039;s working now!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2013 07:56**

ok, thanks for testing :)
