### ISSUE TITLE
0008140:
Numeric value out of range when saving employee

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4095]
**Reported by pschuele on 4 Apr 2013 10:48**

**Version:** git master

Numeric value out of range when saving employee

**Steps to reproduce:** 1. create new employee (fill in required fields)
2. add a contract (do not change the defaults)
3. save contract
4. save employee
-&gt; bam

**Additional information:** Numeric value out of range: 1264 Out of range value for column &#039;year&#039; at row 1.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Tinebase/Backend/Sql/Abstract.php(824): Zend_Db_Adapter_Abstract-&gt;insert()
.../Tinebase/Controller/Record/Abstract.php(462): Tinebase_Backend_Sql_Abstract-&gt;create()
.../HumanResources/Controller/Employee.php(117): Tinebase_Controller_Record_Abstract-&gt;create()
.../Tinebase/Controller/Record/Abstract.php(463): HumanResources_Controller_Employee-&gt;_inspectAfterCreate()

**Comment by Gloirin** [comment]
Related to #4247

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Apr 2013 20:00**

problem still occurs (added new employee WITHOUT a contract):

e0391 pschuele - 2013-04-09T19:58:26+00:00 WARN (4): Tinebase_Server_Json::_handleException::253 Zend_Db_Statement_Exception -&gt; SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column &#039;year&#039; at row 1
 e0391 pschuele - 2013-04-09T19:58:26+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::320 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Tinebase/Backend/Sql/Abstract.php(824): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_humanres...&#039;, Array)
#5 .../Tinebase/Controller/Record/Abstract.php(462): Tinebase_Backend_Sql_Abstract-&gt;create(Object(HumanResources_Model_Account))
#6 .../HumanResources/Controller/Employee.php(119): Tinebase_Controller_Record_Abstract-&gt;create(Object(HumanResources_Model_Account))
#7 .../Tinebase/Controller/Record/Abstract.php(463): HumanResources_Controller_Employee-&gt;_inspectAfterCreate(Object(HumanResources_Model_Employee), Object(HumanResources_Model_Employee))
#8 [internal function]: Tinebase_Controller_Record_Abstract-&gt;create(Object(HumanResources_Model_Employee))
#9 .../Tinebase/Frontend/Json/Abstract.php(285): call_user_func_array(Array, Array)
#10 .../HumanResources/Frontend/Json.php(132): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(HumanResources_Controller_Employee), &#039;Employee&#039;)
#11 [internal function]: HumanResources_Frontend_Json-&gt;saveEmployee(Array)
#12 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 .../Tinebase/Server/Json.php(231): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 .../Tinebase/Server/Json.php(101): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#17 .../Tinebase/Core.php(230): Tinebase_Server_Json-&gt;handle()
#18 .../index.php(17): Tinebase_Core::dispatchRequest()
#19 {main}
