### ISSUE TITLE
0008162:
xml parsing error

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4106]
**Reported by splinter03 on 5 Apr 2013 16:06**

**Version:** Egon Community Edition (2016.03.2)

the following error triggers multiple times in a hour:

fffdc ******** - 2013-04-05T15:51:39+00:00 WARN (4): Syncroton_Command_Sync::handle::179 folder  not found
fffdc ******** - 2013-04-05T15:51:39+00:00 ERR (3): Syncroton_Server::_handlePost::189 Could not encode output: exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: Invalid character at line 3&#039; in /var/www/tine20/library/Syncroton/lib/Syncroton/Wbxml/Encoder.php:164
Stack trace:
#0 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(186): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#2 /var/www/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#3 /var/www/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#4 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#5 {main}
fffdc ******** - 2013-04-05T15:51:39+00:00 ERR (3): Syncroton_Server::_handlePost::190 xml response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;Sync xmlns=&quot;uri:AirSync&quot; xmlns:Syncroton=&quot;uri:Syncroton&quot;&gt;&lt;Collections&gt;&lt;Collection&gt;&lt;SyncKey&gt;0&lt;/SyncKey&gt;&lt;CollectionId&gt;&lt;/CollectionId&gt;&lt;Status&gt;12&lt;/Status&gt;&lt;/Collection&gt;&lt;/Collections&gt;&lt;/Sync&gt;
...
bb45d ******** - 2013-04-05T15:55:20+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php::1033 (2)
bb45d ******** - 2013-04-05T15:55:20+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/var/www/tine20...&#039;, 1033, Array)
#1 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php(1033): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /var/www/tine20/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(140): Syncroton_Command_Sync-&gt;handle()
#4 /var/www/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /var/www/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /var/www/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /var/www/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
Related to #6025

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Apr 2013 18:45**

hi splinter,

which version of tine are you using?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Apr 2013 18:46**

we might need some more logging information. could you please set the loglevel to debug and post the complete request that leads to this error?

**Comment by Gloirin** [comment]
**Comment posted by splinter03 on 5 Apr 2013 20:41**

Hey, i&#039;m using the current stable version: Kristina (2013.03.2). Extended log file will follow.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Apr 2013 07:45**

thanks,

i hope, lars is able to reproduce and fix this.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 May 2013 13:52**

this is no critical error, syncroton does not accept the folder name that is requested by the phone. to &quot;fix&quot; this, syncroton needs to be refactored and should throw more meaningful exceptions and return some error code to the phone.

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 24 Apr 2016 19:18**

This had target version &quot;known bugs&quot; before. 

@pschuele I attached a recent log for a sasmsung device. Could you have another look? 

I doubt this is &quot;normal&quot; behavior. The alleged folder is four times 0x01 which is exactly the number of open tags at this point (0x01 in WBXML means closing tag). In other words: It seems to me that the folder is simply empty. Or the string isn&#039;t closed properly. 

Since I see this with several devices I guess it has a meaning. And the log output changed recently (with Egon?). Now the response has a status 12 = folder has changed additionally. 

Expected behavior: The collectionId is ignored sinve SyncKey is Zero.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 May 2016 10:20**

I&#039;ll had a quick look. but I&#039;m still not sure how this should be handled. how would the correct response look like? if you could provide that, I could try to implement it :)

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 2 May 2016 12:38**

I don&#039;t know what the client really sends. The XML maybe already sanitized. The obvious problem is that the CollectionId is converted to 0x01 0x01 0x01 0x01. This means either the client misses the 0x00 on empty strings (to end the CollectionId-string) and therefor the server takes the following closing-tags (0x01) as the string. Or there never was a collectionId on the first hand and it is inserted by the wbxml-parser which destroys the dom. 

First thought, the wbxml-parser should end an empty string also if an 0x01 occurs (see http://git.syncroton.org/?p=Syncroton;a=blob;f=lib/Syncroton/Wbxml/Abstract.php line 183). 

Second thougth (more deeply), something earlier in decoding breaks. I suspect probing of wbxml content to decode opaque string (http://git.syncroton.org/?p=Syncroton;a=blob;f=lib/Syncroton/Wbxml/Decoder.php line 132 ff.); probing isn&#039;t a good idea if the following byte is 0x00 or 0x01. 

For what I see IMO an empty CollectionId should never occur. If in combination with SyncKey = 0 it can simply be ignored. The server should reinitialize and then wait for next sync request.

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 28 Sep 2016 17:04**

I had a look into the request. Those are simply empty (zero bytes). 

Does Synchrotron implements the empty Sync feature?
https://msdn.microsoft.com/en-us/library/ee202899%28v=exchg.80%29.aspx

I use my own LogFormat but a request looks like: 
93.133.xxx.xxx [26/Sep/2016:08:24:44 +0200] &quot;POST /Microsoft-Server-ActiveSync?Cmd=Sync&amp;User=smsng&amp;DeviceId=SEC1730D48133369&amp;DeviceType=SAMSUNGSMG800F HTTP/1.1&quot; 200  agent: &quot;Android-SAMSUNG-SM-G800F/101.50101&quot; size: -b duration: 0s +

--&gt; Sync request, user agent, size of body (-b = zero bytes), time to response (zero seconds), &quot;+&quot; = Connection may be kept alive after the response is sent (that means the php thread terminated unexpected). 

As I understand usually the server controls if empty Sync-requests are used. But it seems to me, Samsung devices enforce this. Synchrotron converts empty bodies therefore the CollectionId-field is empty...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Sep 2016 06:47**

we now have a fix for the xml encoder (#12178).

could you please check if you still have problems with your samsung device with the 2016.09.1 release?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Sep 2016 06:49**

&gt; Does Synchrotron implements the empty Sync feature?

yes, it should. we&#039;ll see what happens, if the current version is used.
