### ISSUE TITLE
0008186:
catch Integrity constraint violations in state update script

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4118]
**Reported by pschuele on 9 Apr 2013 20:11**

**Version:** Kristina (2013.03.2)

catch Integrity constraint violations in state update script

- it should ignore those errors
- all following state records have been lost

**Additional information:** PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;3310-Filemanager-File-GridPanel-Grid&#039; for key &#039;user_id--state_id&#039;&#039; in /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /opt/local/tine/2013.03.2metaways1/htdocs/Tinebase/Backend/Sql/Abstract.php(824): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_state&#039;, Array)
#5 /opt/local/tine/2013.03.2metaways1/ in /opt/local/tine/2013.03.2metaways1/htdocs/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
Related to #3204
