### ISSUE TITLE
0008232:
Syncroton_Wbxml_Exception while syncing

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4141]
**Reported by balticer on 18 Apr 2013 20:44**

**Version:** git master

Hi,

i have an outlook 2013 client which uses activesync to sync with tine20. The sync process starts and after some seconds an exception is thrown:

bba65 hans.wurst - 2013-04-18T20:16:06+00:00 ERR (3): Syncroton_Server::_handlePost::189 Could not encode output: exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: No memory at line 130898&#039; in /srv/$
Stack trace:
#0 /srv/www/htdocs/library/Syncroton/lib/Syncroton/Server.php(186): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /srv/www/htdocs/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#2 /srv/www/htdocs/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#3 /srv/www/htdocs/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#4 /srv/www/htdocs/index.php(17): Tinebase_Core::dispatchRequest()
#5 {main}

I think it is because of large mails. There are only some small mails synced and then there is a multipart big one (5+MB).

regards
Kai

**Comment by Gloirin** [comment]
Related to #2154

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Nov 2016 07:45**

closing this issue as it is a duplicate of #12258
