### ISSUE TITLE
0008244:
"rrule until must not be before dtstart" when updating recur exception (THISANDFUTURE)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4147]
**Reported by pschuele on 24 Apr 2013 10:35**

**Version:** Kristina (2013.03.2)

&quot;rrule until must not be before dtstart&quot; when updating recur exception (THISANDFUTURE)

**Comment by Gloirin** [comment]
Related to #4218

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Aug 2013 12:47**

it happened again:

4db62 e4b14 kfreymann - 2013-08-29T11:23:41+00:00 DEBUG (7): Calendar_Controller_Event::update::485 Rolling back because: exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;rrule until must not be before dtstart&#039; in /usr/share/tine20/Calendar/Model/Event.php:428
Stack trace:
#0 /usr/share/tine20/Calendar/Controller/Event.php(1361): Calendar_Model_Event-&gt;setRruleUntil()
#1 /usr/share/tine20/Calendar/Controller/Event.php(168): Calendar_Controller_Event-&gt;_inspectEvent(Object(Calendar_Model_Event))
#2 /usr/share/tine20/Calendar/Controller/Event.php(1024): Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), false)
#3 /usr/share/tine20/Calendar/Controller/Event.php(1596): Calendar_Controller_Event-&gt;createRecurException(Object(Calendar_Model_Event), false, true)
#4 /usr/share/tine20/Calendar/Controller/Event.php(864): Calendar_Controller_Event-&gt;attenderStatusCreateRecurException(Object(Calendar_Model_Event), Object(Calendar_Model_Attender), &#039;7707308ce0f1dae...&#039;, true)
#5 /usr/share/tine20/Calendar/Controller/Event.php(554): Calendar_Controller_Event-&gt;createRecurException(Object(Calendar_Model_Event), false, true)
#6 /usr/share/tine20/Calendar/Controller/Event.php(480): Calendar_Controller_Event-&gt;_updateExdateRange(Object(Calendar_Model_Event), &#039;THISANDFUTURE&#039;, Object(Calendar_Model_Event))
#7 [internal function]: Calendar_Controller_Event-&gt;update(Object(Calendar_Model_Event), true, &#039;THISANDFUTURE&#039;)
#8 /usr/share/tine20/Tinebase/Frontend/Json/Abstract.php(287): call_user_func_array(Array, Array)
#9 /usr/share/tine20/Calendar/Frontend/Json.php(218): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#10 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, true, &#039;THISANDFUTURE&#039;)
#11 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /usr/share/tine20/Tinebase/Server/Json.php(234): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 /usr/share/tine20/Tinebase/Server/Json.php(104): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#16 /usr/share/tine20/Tinebase/Core.php(230): Tinebase_Server_Json-&gt;handle()
#17 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#18 {main}
4db62 e4b14 kfreymann - 2013-08-29T11:23:41+00:00 WARN (4): Tinebase_Exception::log::64 Tinebase_Exception_Record_Validation -&gt; rrule until must not be before dtstart
4db62 e4b14 kfreymann - 2013-08-29T11:23:41+00:00 NOTICE (5): Tinebase_Exception::log::72 #0 .../Calendar/Controller/Event.php(1361): Calendar_Model_Event-&gt;setRruleUntil()
#1 .../Calendar/Controller/Event.php(168): Calendar_Controller_Event-&gt;_inspectEvent(Object(Calendar_Model_Event))
#2 .../Calendar/Controller/Event.php(1024): Calendar_Controller_Event-&gt;create(Object(Calendar_Model_Event), false)
#3 .../Calendar/Controller/Event.php(1596): Calendar_Controller_Event-&gt;createRecurException(Object(Calendar_Model_Event), false, true)
#4 .../Calendar/Controller/Event.php(864): Calendar_Controller_Event-&gt;attenderStatusCreateRecurException(Object(Calendar_Model_Event), Object(Calendar_Model_Attender), &#039;7707308ce0f1dae...&#039;, true)
#5 .../Calendar/Controller/Event.php(554): Calendar_Controller_Event-&gt;createRecurException(Object(Calendar_Model_Event), false, true)
#6 .../Calendar/Controller/Event.php(480): Calendar_Controller_Event-&gt;_updateExdateRange(Object(Calendar_Model_Event), &#039;THISANDFUTURE&#039;, Object(Calendar_Model_Event))
#7 [internal function]: Calendar_Controller_Event-&gt;update(Object(Calendar_Model_Event), true, &#039;THISANDFUTURE&#039;)
#8 .../Tinebase/Frontend/Json/Abstract.php(287): call_user_func_array(Array, Array)
#9 .../Calendar/Frontend/Json.php(218): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#10 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, true, &#039;THISANDFUTURE&#039;)
#11 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 .../Tinebase/Server/Json.php(234): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Server/Json.php(104): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#16 .../Tinebase/Core.php(230): Tinebase_Server_Json-&gt;handle()
#17 .../index.php(17): Tinebase_Core::dispatchRequest()
#18 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Aug 2013 13:06**

should be finally fixed with #8386
