### ISSUE TITLE
0008264:
No login possible with active IMAP and DBmail MySQL-Backend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4157]
**Reported by andydld on 25 Apr 2013 14:32**

**Version:** Kristina (2013.03.3)

I tried to setup debian squeeze with postfix, dbmail and tine 2.0 (repository).
After i activate IMAP and set the Backend to &quot;DBmail MySQL&quot; no login with initial admin is possible.
If i deactivate IMAP or set the backend to &quot;Standard IMAP&quot; everything is fine.
The rest of the Tine-Setup is standard-like.

I think there are two things:

1) Missing table for DBmail within the Tine-DB.
2) The logon should be possible independent of the IMAP-backend within the mail-config of Tine-Setup.

**Steps to reproduce:** - Setup Tine the Standard-Way, means Auth=Sql, Mail inactive.
- Logon with initial admin.
- Everything is ok.
- Logoff.
- Switch IMAP-backend to &quot;DBmail MySQL&quot; in Tine-Mail-Setup.
- Try to logon again.

**Additional information:** Philipp found this within the logs:

0f952 38650 -- none -- - 2013-04-25T08:14:44+00:00 WARN (4): Tinebase_Server_Json::_handleException::253 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.dbmail_users&#039; doesn&#039;t exist
0f952 38650 -- none -- - 2013-04-25T08:14:44+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::320 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DESCRIBE `dbmai...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Pdo/Mysql.php(156): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DESCRIBE `dbmai...&#039;)

It seems to be a missing table.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Apr 2013 13:45**

a note on this: we do not create the dbmail_users table in tine. there might be already an existing table or you use a slightly different table layout. please refer to the wiki or the email backend php classes for the create table statements.

nevertheless, i&#039;ll try to fix the problem with the login.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 30 Apr 2013 14:58**

&gt; we do not create the dbmail_users table in tine.
&gt; there might be already an existing table or

No.

&gt; you use a slightly different table layout.

Not that I&#039;m aware of.

&gt; please refer to the wiki or  

The wiki only tells about dovecot.

The first time i tried to install dbmail and Tine i found the &quot;wrong password hash&quot;-thing. At that time i documented all steps. The second time i tried this combination, i get this missing table.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 May 2013 10:00**

ok, nothing in the wiki (nor in the php class), you are correct.

but if you already installed dbmail (with mysql) you should have the tables right there. just tell tine where to find them.

i uploaded a change which fixes the login issue to our review system.

**Comment by Gloirin** [comment]
**Comment posted by andydld on 3 May 2013 12:19**

Do you mean the &quot;dbmail_users&quot;-table within the dbmail-database?

How can i tell tine where to look for this table?
I think somewhere within setup-authentication/user-accounts.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 May 2013 12:34**

yup, that is the table.

when you switch to dbmail mysql imap backend in the email section of the setup, you&#039;ll see some input fields for the database connection appear.
