### ISSUE TITLE
0008460:
WebDAV File Upload fails "Tinebase_Exception_Record_Validation' with message 'some fields session_id have invalid content"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4255]
**Reported by 80686 on 31 May 2013 08:10**

**Version:** Kristina (2013.03.4)

The problem started after I updated from Joey to Kristina (2013.03.3) and it still persists in 2013.03.4.

I am using WebDAV to store files - either through KDE / Konqueror, through mount.davfs or on Windows with a simple drive mapping. The problem applies to all three use-cases.

On client side I get &quot;permission denied&quot; when uploading a file.

On server side I see: 
May 31 09:57:02 srv98120 Tine 2.0[5625]: Tinebase_Record_Abstract::isValid::532:
May 31 09:57:02 srv98120 Array
May 31 09:57:02 srv98120 (
May 31 09:57:02 srv98120 [0] =&gt; Array
May 31 09:57:02 srv98120 (
May 31 09:57:02 srv98120 [id] =&gt; session_id
May 31 09:57:02 srv98120 [msg] =&gt; Array
May 31 09:57:02 srv98120 (
May 31 09:57:02 srv98120 [isEmpty] =&gt; You must give a non-empty value for field &#039;session_id&#039;
May 31 09:57:02 srv98120 )
May 31 09:57:02 srv98120 )
May 31 09:57:02 srv98120 )
May 31 09:57:02 srv98120 exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;some fields session_id have invalid content&#039; in /var/www/intern/office/Tinebase/Record/Abstract.php:531
May 31 09:57:02 srv98120 Stack trace:
May 31 09:57:02 srv98120 #0 /var/www/intern/office/Tinebase/Record/Abstract.php(366): Tinebase_Record_Abstract-&gt;isValid(true)
May 31 09:57:02 srv98120 #1 /var/www/intern/office/Tinebase/Record/Abstract.php(238): Tinebase_Record_Abstract-&gt;setFromArray(Array)
May 31 09:57:02 srv98120 #2 /var/www/intern/office/Tinebase/TempFile.php(192): Tinebase_Record_Abstract-&gt;__construct(Array)
May 31 09:57:02 srv98120 #3 /var/www/intern/office/Tinebase/TempFile.php(286): Tinebase_TempFile-&gt;createTempFile(&#039;/tmp/tine_tempf...&#039;)
May 31 09:57:02 srv98120 #4 /var/www/intern/office/Tinebase/FileSystem.php(378): Tinebase_TempFile-&gt;openTempFile()
May 31 09:57:02 srv98120 #5 /var/www/intern/office/Tinebase/Frontend/WebDAV/File.php(73): Tinebase_FileSystem-&gt;fopen(&#039;/758c20e8525b55...&#039;, &#039;w&#039;)
May 31 09:57:02 srv98120 #6 /var/www/intern/office/library/Sabre/DAV/Server.php(826): Tinebase_Frontend_WebDAV_File-&gt;put(Resource id #8)
May 31 09:57:02 srv98120 #7 [internal function]: Sabre_DAV_Server-&gt;httpPut(&#039;webdav/Filemana...&#039;)
May 31 09:57:02 srv98120 #8 /var/www/intern/office/library/Sabre/DAV/Server.php(454): call_user_func(Array, &#039;webdav/Filemana...&#039;)
May 31 09:57:02 srv98120 #9 /var/www/intern/office/library/Sabre/DAV/Server.php(201): Sabre_DAV_Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;webdav/Filemana...&#039;)
May 31 09:57:02 srv98120 #10 /var/www/intern/office/Tinebase/Server/WebDAV.php(126): Sabre_DAV_Server-&gt;exec()
May 31 09:57:02 srv98120 #11 /var/www/intern/office/Tinebase/Core.php(230): Tinebase_Server_WebDAV-&gt;handle()
May 31 09:57:02 srv98120 #12 /var/www/intern/office/index.php(17): Tinebase_Core::dispatchRequest()
May 31 09:57:02 srv98120 #13 {main}

**Steps to reproduce:** 1) Mount Filemanager as a WebDAV ressource.
2) Upload a file to the WebDAV drive (wherever you have write-access to).
3) Get error message &quot;permission denied&quot;.
4) See a 0 Byte file you just uploaded.
5) Sometimes uploading the same file again works.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jun 2013 13:30**

please test with the attached Tinebase/TempFile.php

we no longer start a session during a webdav request.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 4 Jun 2013 14:01**

Thanks for the patch!

Tried with new TempFile.php as attached:
* overwriting existing files (including 0 Byte files from failed uploads) works nicely
* uploading a new file failed with a new error message:


[Tue Jun 04 15:59:08 2013] [error] [client 46.237.196.246] PHP Fatal error:  Can&#039;t use function return value in write context in /var/www/intern/office/Tinebase/TempFile.php on line 183
[Tue Jun 04 15:59:11 2013] [error] [client 46.237.196.246] PHP Fatal error:  Can&#039;t use function return value in write context in /var/www/intern/office/Tinebase/TempFile.php on line 183

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 4 Jun 2013 14:05**

It seems that some of the overwritten prior 0 Byte files look like a successful upload but a few seconds later, after a failed upload of a new file, some of them revert to 0 Byte again...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jun 2013 14:09**

ok, thanks for testing. i&#039;ll upload a new patch in a few minutes :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jun 2013 14:14**

uploaded a new TempFile.php for testing.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 4 Jun 2013 14:20**

Yay! It works! Thanks a lot!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Apr 2014 15:28**

there is a problem with the string &quot;no_session_id&quot; (see https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=15992&amp;start=10).

will fix that.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Apr 2014 15:32**

added another improved TempFile.php
