### ISSUE TITLE
0008556:
Contacts created on Android device do not sync via ActiveSync, syncing breaks

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4303]
**Reported by robi on 25 Jun 2013 13:12**

**Version:** Kristina (2013.03.5)

Contacts created on Android device do not sync via ActiveSync, syncing breaks.

Using Android 4.1.1, HTC One S, factory firmware.

**Steps to reproduce:** Created a couple of contacts in the Phones&#039;s memory.
Copied them to the ActiveSync container of the phone.
Started sync (manual/automatic, doesn&#039;t matter) - sync stops, and breaks. 
Contacts are not synced.

**Additional information:** Logfile says:

a61da robi - 2013-06-25T13:08:36+00:00 ERR (3): Addressbook_Model_Contact::isValid::370:
Array
(
    [0] =&gt; Array
        (
            [id] =&gt; org_name
            [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
        )

    [1] =&gt; Array
        (
            [id] =&gt; n_family
            [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
        )

    [2] =&gt; Array
        (
            [id] =&gt; org_name
            [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
        )

    [3] =&gt; Array
        (
            [id] =&gt; n_family
            [msg] =&gt; either &quot;org_name&quot; or &quot;n_family&quot; must be given!
        )

)
exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;either &quot;org_name&quot; or &quot;n_family&quot; must be given!&#039; in /mnt/www/wwi/t
ine20_2013.03.5/Addressbook/Model/Contact.php:369
Stack trace:
#0 /mnt/www/wwi/tine20_2013.03.5/Tinebase/Controller/Record/Abstract.php(450): Addressbook_Model_Contact-&gt;isValid(true)
#1 /mnt/www/wwi/tine20_2013.03.5/ActiveSync/Controller/Abstract.php(232): Tinebase_Controller_Record_Abstract-&gt;create(Object(Add
ressbook_Model_Contact))
#2 /mnt/www/wwi/tine20_2013.03.5/library/Syncroton/lib/Syncroton/Command/Sync.php(286): ActiveSync_Controller_Abstract-&gt;createEn
try(&#039;addressbook-roo...&#039;, Object(Syncroton_Model_Contact))
#3 /mnt/www/wwi/tine20_2013.03.5/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /mnt/www/wwi/tine20_2013.03.5/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /mnt/www/wwi/tine20_2013.03.5/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /mnt/www/wwi/tine20_2013.03.5/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /mnt/www/wwi/tine20_2013.03.5/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
**Comment posted by robi on 25 Jun 2013 14:46**

Must be related to bug #0008486, as after a while sync succeedes, but it deletes all the contacts from the phone&#039;s container.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 2 Jul 2013 10:48**

Please replace attached file ActiveSync/Controller/Contacts.php and test again.

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Jul 2013 11:08**

Replaced the file. Situation changed a bit, it behaves differently:
- if I copy some contact from the phone memory to Tine&#039;s contact list and do a sync, all tine contacts will be deleted from the phone except the ones I copied
- the contacts copied on the phone will be added successfully to Tine&#039;s database
- the contacts which had only one name, have &#039;imported&#039; at the family name in Tine, and the name given on the phone on the little name. I think Tine is too strict about that...
- if I rename the contact with the &#039;imported&#039; family name to something else, at next sync contact will be duplicated, I mean it will come back again from the phone as a new contact with &#039;imported&#039; family name. The renamed contact will remain in the database too, but won&#039;t sync back to the phone.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 2 Jul 2013 11:12**

Can you please provide logfiles for the different problems?

One for the case where you move the contact to Tine 2.0&#039;s contact and one logfile where the duplication happens.

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Jul 2013 11:36**

Hmmm strange. I had to delete the Tine&#039;s Exchange account from the phone and re-create it, to recover lost contacst from the previous case.

Now I can&#039;t reproduce the issue anymore:
- copying contact from phone&#039;s memory to Tine&#039;s exchange addressbook doesn&#039;t delete the other contacts anymore
- contact without a family name on the phone gets &#039;imported&#039; family name in Tine&#039;s web interface but remains without a family name on the phone after a sync
- renaming the family name to something else in Tine&#039;s web interface syncs back to the phone correctly

Seems to be fine...

Should I had to remove the account and re-add it before testing with the new ActiveSync/Controller/Contacts.php?

**Comment by Gloirin** [comment]
**Comment posted by robi on 2 Jul 2013 11:46**

One thing though, if I delete a contact from Tine&#039;s web interface, it doesn&#039;t delete it from the phone&#039;s Tine contact list after a sync. Maybe it&#039;s like that on purpose?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2013 11:00**

&gt; Should I had to remove the account and re-add it before testing with the new 
&gt; ActiveSync/Controller/Contacts.php?

that should not be required.

&gt; One thing though, if I delete a contact from Tine&#039;s web interface, it doesn&#039;t 
&gt; delete it from the phone&#039;s Tine contact list after a sync. Maybe it&#039;s like that 
&gt; on purpose?

no, it should be deleted. we created a new issue for that: #8576

**Comment by Gloirin** [comment]
**Comment posted by robi on 22 Aug 2013 13:38**

Issue still persists, it behaves just like before on v.2013.03.7 :(

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2013 13:42**

which issue do you mean? could you create a new logfile for this in version 2013.03.7?

**Comment by Gloirin** [comment]
**Comment posted by robi on 22 Aug 2013 13:54**

The issue is that if I simply add a new contact on the phone (for example just by pressing the &quot;+&quot; sign in the calls list for an unknown number, and just filling a name, then pressing save), at the next sync all the contacts are deleted from the phone and only the contact just added stays in, which does not sync back to the server.

Please find the log I just created moments ago, attached.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2013 14:12**

ok, then it is a duplicate of #8486. we&#039;ll try to fix that soon!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2013 14:14**

closing this (duplicate). thanks for the log, I&#039;ll mention that in the other bugreport, too.
