### ISSUE TITLE
0008650:
Option queryProfiles if config.inc.php causes error in database connection

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4349]
**Reported by fgsl on 22 Jul 2013 09:43**

**Version:** git master

The method setupDatabaseConnection() of Tinebase_Core uses all the elements of $config-&gt;database for opening the database connection with a Zend_Db_Adapter class.
When we uses option queryProfiles into array database in config.inc.php, this option causes an error:

Fatal error: Uncaught exception &#039;Zend_Db_Adapter_Exception&#039; with message &#039;SQLSTATE[08006] [7] invalid connection option &quot;queryProfiles&quot;&#039; in /var/www/expressov3/library/Zend/Db/Adapter/Pdo/Abstract.php:144 Stack trace: #0 /var/www/expressov3/library/Zend/Db/Adapter/Pdo/Pgsql.php(87): Zend_Db_Adapter_Pdo_Abstract-&gt;_connect() #1 /var/www/expressov3/library/Zend/Db/Adapter/Abstract.php(448): Zend_Db_Adapter_Pdo_Pgsql-&gt;_connect() #2 /var/www/expressov3/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array) #3 /var/www/expressov3/library/Zend/Db/Adapter/Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select), Array) #4 /var/www/expressov3/Tinebase/Core.php(982): Zend_Db_Adapter_Abstract-&gt;fetchOne(Object(Zend_Db_Select)) #5 /var/www/expressov3/Tinebase/Core.php(755): Tinebase_Core::checkUnaccentExtension(Object(Zend_Db_Adapter_Pdo_Pgsql)) #6 /var/www/expressov3/Tinebase/Core.php(741): Tinebase_Core::setDbCapabilitiesInSession(Object(Zend_Session_Namespa in /var/www/expressov3/library/Zend/Db/Adapter/Pdo/Abstract.php on line 144 

**Steps to reproduce:** Insert the element &#039;queryProfiles&#039; =&gt; TRUE into array database in config.inc.php.

**Additional information:** As methods setupDatabaseConnection() and getDbProfiling() of Tinebase_Core uses array database and their interests are conflicting, the suggestion is to take off the elements profiler and queryProfiler of array database and to put them into another array.

Instead of that, for example:

&#039;database&#039; =&gt; 
  array (
    &#039;host&#039; =&gt; &#039;localhost&#039;,
    &#039;dbname&#039; =&gt; $version,
    &#039;username&#039; =&gt; &#039;root&#039;,
    &#039;password&#039; =&gt; &#039;***&#039;,
    &#039;adapter&#039; =&gt; &#039;pdo_mysql&#039;,
    &#039;tableprefix&#039; =&gt; &#039;tine20_&#039;,
// here are the profiler options:
     &#039;profiler&#039; =&gt; TRUE,
     &#039;queryProfiles&#039; =&gt; TRUE,
  ),

We write so:

&#039;database&#039; =&gt; 
  array (
    &#039;host&#039; =&gt; &#039;localhost&#039;,
    &#039;dbname&#039; =&gt; $version,
    &#039;username&#039; =&gt; &#039;root&#039;,
    &#039;password&#039; =&gt; &#039;***&#039;,
    &#039;adapter&#039; =&gt; &#039;pdo_mysql&#039;,
    &#039;tableprefix&#039; =&gt; &#039;tine20_&#039;,
  ),
&#039;profiler&#039; =&gt; 
  array (
     &#039;queryProfiles&#039; =&gt; TRUE,
  ),

So we can remove an if statement of method Tinebase_Core::getDbProfiling() and it will be so:

    public static function getDbProfiling()
    {
        if (! self::getConfig() || ! self::getConfig()-&gt;profiler) {
            return;
        }
    
        $config = self::getConfig()-&gt;profiler;    
    
        $profiler = Zend_Db_Table::getDefaultAdapter()-&gt;getProfiler();
    
        if (! empty($config-&gt;profilerFilterElapsedSecs)) {
            $profiler-&gt;setFilterElapsedSecs($config-&gt;profilerFilterElapsedSecs);
        }
    
        $data = array(
                &#039;totalNumQueries&#039; =&gt; $profiler-&gt;getTotalNumQueries(),
                &#039;totalElapsedSec&#039; =&gt; $profiler-&gt;getTotalElapsedSecs(),
                &#039;longestTime&#039;        =&gt; 0,
                &#039;longestQuery&#039;       =&gt; &#039;&#039;
        );
    
        if ((bool) $config-&gt;queryProfiles) {
            $data[&#039;queryProfiles&#039;] = array();
            foreach($profiler-&gt;getQueryProfiles() as $profile) {
                if ((bool) $config-&gt;queryProfilesDetails) {
                    $data[&#039;queryProfiles&#039;][] = array(
                            &#039;query&#039;       =&gt; $profile-&gt;getQuery(),
                            &#039;elapsedSecs&#039; =&gt; $profile-&gt;getElapsedSecs(),
                    );
                }
    
                if ($profile-&gt;getElapsedSecs() &gt; $data[&#039;longestTime&#039;]) {
                    $data[&#039;longestTime&#039;]  = $profile-&gt;getElapsedSecs();
                    $data[&#039;longestQuery&#039;] = $profile-&gt;getQuery();
                }
            }
        }
    
        self::getLogger()-&gt;debug(__METHOD__ . &#039; (&#039; . __LINE__ . &#039;) value: &#039; . print_r($data, true));
    
    }

**Comment by Gloirin** [comment]
**Comment posted by fgsl on 22 Jul 2013 10:55**

From jenkins user:

jenkins user has posted comments on this change.

Change subject: - #8650 Option queryProfiles if config.inc.php causes error in database connection
......................................................................


Patch Set 1: Verified

Build Successful

http://ci.tine20.org/job/tine20gerrit/3740/ : SUCCESS

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jul 2013 11:29**

add doc for this in the docblock of getDbProfiling()
