### ISSUE TITLE
0008660:
Fehlermeldung bei schicken von großen Anhängen per E-Mail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4354]
**Reported by Solivagus on 23 Jul 2013 10:47**

**Version:** Kristina (2013.03.6)

Schickt man eine E-Mail mit größerem Anhang (20-50mb PDF), kommt eine Fehlermeldung mit &quot;internal server error&quot;

Einen Ausschnitt aus dem Logfile habe ich mit angehängt.

**Additional information:** post_max_size = 50M
upload_max_filesize = 50M

in /etc/php5/apache2/php.ini habe ich eingestellt.

**Comment by Gloirin** [comment]
Related to #4337

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Jul 2013 11:13**

hallo arne,

wenn ich mir das logfile so ansehe, finde ich nur diesen fehler:

 76b1f aklingenberg - 2013-07-23T10:42:29+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadHTML() [&lt;a href=&#039;domdocument.loadhtml&#039;&gt;domdocument.loadhtml&lt;/a&gt;]: ID  already defined in Entity, line: 1 in /usr/share/tine20/Felamimail/Model/Message.php::728 (2)
 76b1f aklingenberg - 2013-07-23T10:42:29+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/usr/share/tine...&#039;, 728, Array)
#1 /usr/share/tine20/Felamimail/Model/Message.php(728): DOMDocument-&gt;loadHTML(&#039;&lt;?xml encoding=...&#039;)
#2 /usr/share/tine20/Felamimail/Model/Message.php(699): Felamimail_Model_Message::convertHTMLToPlainTextWithQuotes(&#039;test - bitte l?...&#039;)
#3 /usr/share/tine20/Felamimail/Controller/Message/Send.php(375): Felamimail_Model_Message-&gt;getPlainTextBody()
#4 /usr/share/tine20/Felamimail/Controller/Message/Send.php(192): Felamimail_Controller_Message_Send-&gt;_setMailBody(Object(Tinebase_Mail), Object(Felamimail_Model_Message))

das hat vermutlich nichts mit der größe der nachricht (bzw. deren attachments) zu tun, da hier der body zusammengebaut wird.

wäre gut, wenn du mal den kompletten request (tine log im DEBUG mode) hier hochladen könntest.

**Comment by Gloirin** [comment]
**Comment posted by Solivagus on 23 Jul 2013 12:36**

Erledigt.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Jul 2013 13:02**

danke, damit kann ich testen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Sep 2016 10:24**

problem should be solved since we updated Zend Framework. The logging in Zend/Mail/Protocol/Abstract caused some issues with memory (see #4169).
