### ISSUE TITLE
0008664:
Sync problems with Samsung Galaxy S4

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4356]
**Reported by linuxq on 24 Jul 2013 13:53**

**Version:** Kristina (2013.03.6)

Sync with a Samsung Galaxy S4 doesn&#039;t work. Mails do sync, but no calender events and only 1 task got sent to the GS4!

If I add an calender event on the GS4, it appears in Tine!

**Additional information:** 44464 nadine - 2013-07-22T14:48:24+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php::1030 (2)
44464 nadine - 2013-07-22T14:48:24+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/www/htdocs/w00...&#039;, 1030, Array)
#1 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(1030): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}
44464 nadine - 2013-07-22T14:48:24+00:00 WARN (4): Syncroton_Command_Sync::handle::179 folder  not found
44464 nadine - 2013-07-22T14:48:24+00:00 CRIT (2): Syncroton_Server::_handlePost::162 unexpected exception occured: Zend_Db_Statement_Exception
44464 nadine - 2013-07-22T14:48:24+00:00 CRIT (2): Syncroton_Server::_handlePost::164 exception message: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
44464 nadine - 2013-07-22T14:48:24+00:00 CRIT (2): Syncroton_Server::_handlePost::166 #0 /www/htdocs/w008068a/tine-work/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /www/htdocs/w008068a/tine-work/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /www/htdocs/w008068a/tine-work/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Backend/ABackend.php(102): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(964): Syncroton_Backend_ABackend-&gt;get(NULL)
#5 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_Sync-&gt;getResponse()
#6 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#7 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#8 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#9 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#10 {main}

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 24 Jul 2013 14:04**

Contacts don&#039;t get synced either!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Jul 2013 08:52**

hi linuxq,

thanks for the report.

for further research, we need the full log of the sync request (DEBUG level). could you please add that to this bugreport?

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 25 Jul 2013 12:29**

Hi, I hope this helps:


4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setupLogger::555 Logger initialized
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::321 Loading all configs for app Tinebase
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::328 Found 6 configs.
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setupLogger::555 Logger initialized
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): ActiveSync_Server_Http::handle::62 is ActiveSync request.
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setupCache::627 cache of backend type &#039;File&#039; enabled
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setSessionBackend::853 Session of backend type &#039;File&#039; configured.
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::98 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1002 given localeString &#039;auto&#039;
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1029 Try to detect the locale of the user (browser, environment, default)
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::204 given localeString &#039;auto&#039;
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::216 &#039;en&#039; is not supported, checking fallback
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::242 selected locale: &#039;en&#039;
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setupUserLocale::1046 Setting user locale: en
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1058 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::1123 setting execution life time to: 0
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Auth::setBackend::263 authentication backend: Sql
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Auth::authenticate::192 Trying to authenticate nadine
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Auth::authenticate::206 Authentication of nadine succeeded
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_User::setBackendType::244 Setting backend type to Sql
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_User::getInstance::137 accounts backend: Sql
4ccc9 -- none -- - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_User::factory::205 Created user backend of type Sql
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1002 given localeString &#039;auto&#039;
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1029 Try to detect the locale of the user (browser, environment, default)
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::204 given localeString &#039;auto&#039;
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::216 &#039;en&#039; is not supported, checking fallback
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Translation::getLocale::242 selected locale: &#039;en&#039;
4ccc9 nadine - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Core::setupUserLocale::1046 Setting user locale: en
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Group::getInstance::71 groups backend: Sql
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::create::436 Create new Tinebase_Model_AccessLog
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::321 Loading all configs for app ActiveSync
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::328 Found 0 configs.
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Syncroton_Server::handle::61 REQUEST METHOD: POST
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Syncroton_Server::_handlePost::103 REQUEST Array
(
    [protocolVersion] =&gt; 14.1
    [command] =&gt; Sync
    [deviceId] =&gt; SEC16CD7589DAA2A
    [deviceType] =&gt; SAMSUNGGTI9505
    [policyKey] =&gt; 0
    [saveInSent] =&gt; 
    [collectionId] =&gt; 
    [itemId] =&gt; 
    [attachmentName] =&gt; 
    [acceptMultipart] =&gt; 
    [userAgent] =&gt; SAMSUNG-GT-I9505/101.40202
    [contentType] =&gt; application/vnd.ms-sync.wbxml
)
 
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Syncroton_Server::_handlePost::126 xml request:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;Sync xmlns=&quot;uri:AirSync&quot;&gt;
  &lt;Collections&gt;
    &lt;Collection&gt;
      &lt;SyncKey&gt;0&lt;/SyncKey&gt;
      &lt;CollectionId&gt;&lt;/CollectionId&gt;
    &lt;/Collection&gt;
  &lt;/Collections&gt;
&lt;/Sync&gt;
 
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2013-07-25 12:25:41
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php::1030 (2)
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/www/htdocs/w00...&#039;, 1030, Array)
#1 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(1030): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php::1030 (2)
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/www/htdocs/w00...&#039;, 1030, Array)
#1 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(1030): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php::1030 (2)
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/www/htdocs/w00...&#039;, 1030, Array)
#1 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(1030): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::438 DOMDocument::loadXML() [&lt;a href=&#039;domdocument.loadxml&#039;&gt;domdocument.loadxml&lt;/a&gt;]: PCDATA invalid Char value 1 in Entity, line: 7 in /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php::1030 (2)
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;DOMDocument::lo...&#039;, &#039;/www/htdocs/w00...&#039;, 1030, Array)
#1 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(1030): DOMDocument-&gt;loadXML(&#039;&lt;?xml version=&quot;...&#039;)
#2 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(116): Syncroton_Command_Sync-&gt;_mergeSyncRequest(Object(DOMDocument), Object(Syncroton_Model_Device))
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Sync-&gt;handle()
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Syncroton_Command_Sync::handle::159 restored options to Array
(
    [filterType] =&gt; 0
    [mimeSupport] =&gt; 0
    [mimeTruncation] =&gt; 8
    [bodyPreferences] =&gt; Array
        (
        )
 
)
 
4ccc9 nadine - 2013-07-25T12:25:41+00:00 WARN (4): Syncroton_Command_Sync::handle::179 folder  not found
4ccc9 nadine - 2013-07-25T12:25:41+00:00 CRIT (2): Syncroton_Server::_handlePost::162 unexpected exception occured: Zend_Db_Statement_Exception
4ccc9 nadine - 2013-07-25T12:25:41+00:00 CRIT (2): Syncroton_Server::_handlePost::164 exception message: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
4ccc9 nadine - 2013-07-25T12:25:41+00:00 CRIT (2): Syncroton_Server::_handlePost::166 #0 /www/htdocs/w008068a/tine-work/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /www/htdocs/w008068a/tine-work/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /www/htdocs/w008068a/tine-work/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Backend/ABackend.php(102): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Command/Sync.php(964): Syncroton_Backend_ABackend-&gt;get(NULL)
#5 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_Sync-&gt;getResponse()
#6 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#7 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#8 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#9 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#10 {main}
4ccc9 nadine - 2013-07-25T12:25:41+00:00 INFO (6): Tinebase_Controller_Record_Abstract::update::633 Update Tinebase_Model_AccessLog
4ccc9 nadine - 2013-07-25T12:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_updateACLCheck::695 Doing ACL check ...
4ccc9 nadine - 2013-07-25T12:25:41+00:00 INFO (6): index.php (36) METHOD: ActiveSync_Server_Http::POST / TIME: 0.284184932709 seconds / MEMORY: 17.25 MBytes / REALPATHCACHESIZE: 0

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Jul 2013 15:12**

could you please attach the logfile as an attachment? there are some strange chars that might be lost during copy&amp;paste in mantis.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Jul 2013 15:14**

it would be great if you could attach the log of the initial folder sync, too.

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 2 Aug 2013 08:26**

I have 2 sets now, since I retried. The last time, all tasks were synced to the GS$, but no calender events at all. Another time some calender tasks wer synced, but only 1 task. 

@pschuele: Since there is contact data visible in the log, I don&#039;t want to upload it publically. Send me a mail ( mmeissel ad gmail dot com)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Aug 2013 09:47**

i sent you an email.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Aug 2013 08:23**

lars will have a look at this in about two or three weeks.

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 16 Aug 2013 04:29**

Habe gester auf Kristina (2013.03.7) upgedated. Keine Besserung!
