### ISSUE TITLE
0008736:
Integrity constraint and NotFound errors during folder sync

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4392]
**Reported by pschuele on 5 Aug 2013 13:39**

**Version:** Kristina (2013.03.6)

Integrity constraint and NotFound errors during folder sync

- please ask if you need more information

**Additional information:** 51e64 ptraut - 2013-08-01T20:51:06+00:00 CRIT (2): Syncroton_Server::_handlePost::162 unexpected exception occured: Syncroton_Exception_NotFound
51e64 ptraut - 2013-08-01T20:51:06+00:00 CRIT (2): Syncroton_Server::_handlePost::164 exception message: id not found
51e64 ptraut - 2013-08-01T20:51:06+00:00 CRIT (2): Syncroton_Server::_handlePost::166 #0 /usr/share/tine20/library/Syncroton/lib/Syncroton/Backend/ABackend.php(63): Syncroton_Backend_ABackend-&gt;get(&#039;22e09066a18896f...&#039;)
#1 /usr/share/tine20/library/Syncroton/lib/Syncroton/Backend/SyncState.php(33): Syncroton_Backend_ABackend-&gt;create(Object(Syncroton_Model_SyncState))
#2 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/FolderSync.php(256): Syncroton_Backend_SyncState-&gt;create(Object(Syncroton_Model_SyncState))
#3 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_FolderSync-&gt;getResponse()
#4 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#5 /usr/share/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#6 /usr/share/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#7 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#8 {main}

    2dcdf ptraut - 2013-08-01T20:49:05+00:00 CRIT (2): Syncroton_Server::_handlePost::162 unexpected exception occured: Zend_Db_Statement_Exception
    2dcdf ptraut - 2013-08-01T20:49:05+00:00 CRIT (2): Syncroton_Server::_handlePost::164 exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;39756b8aaae311520839e4d15b2fcea70d147af5-FolderSync-1&#039; for key &#039;PRIMARY&#039;
    2dcdf ptraut - 2013-08-01T20:49:05+00:00 CRIT (2): Syncroton_Server::_handlePost::166 #0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
    #1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
    #2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
    #3 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
    #4 /usr/share/tine20/library/Syncroton/lib/Syncroton/Backend/ABackend.php(61): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_acsync_s...&#039;, Array)
    #5 /usr/share/tine20/library/Syncroton/lib/Syncroton/Backend/SyncState.php(33): Syncroton_Backend_ABackend-&gt;create(Object(Syncroton_Model_SyncState))
    #6 /usr/share/tine20/library/Syncroton/lib/Syncroton/Command/FolderSync.php(256): Syncroton_Backend_SyncState-&gt;create(Object(Syncroton_Model_SyncState))
    #7 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_FolderSync-&gt;getResponse()
    #8 /usr/share/tine20/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
    #9 /usr/share/tine20/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
    #10 /usr/share/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
    #11 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
    #12 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Aug 2013 08:29**

collect some more information: what is in the database?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Aug 2013 13:43**

i no longer see the error in the logs.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Aug 2013 13:44**

i attached a txt file with some current db information of the as device of the user.
