### ISSUE TITLE
0008828:
Sent mails are reported as not sent

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4438]
**Reported by linuxq on 23 Aug 2013 06:41**

**Version:** Kristina (2013.03.7)

Sending mails on the Blackberry Z10 works. But the Z10 sends them up to 3 times and still shows a sign as if it hasn&#039;t been able to send the mail!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Aug 2013 09:21**

i see this error in the logs:

d9b95 testfritz - 2013-08-23T06:29:04+00:00 WARN (4): Tinebase_Core::errorHandler::438 include(we2h4i58hd92jdfp/jkv4kdn.php) [&lt;a href=&#039;function.include&#039;&gt;function.include&lt;/a&gt;]: failed to open stream: No such file or directory in /www/htdocs/w008068a/tine-work/library/Zend/Loader.php::83 (2)
d9b95 testfritz - 2013-08-23T06:29:04+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 /www/htdocs/w008068a/tine-work/library/Zend/Loader.php(83): Tinebase_Core::errorHandler(2, &#039;include(we2h4i5...&#039;, &#039;/www/htdocs/w00...&#039;, 83, Array)
#1 /www/htdocs/w008068a/tine-work/library/Zend/Loader.php(83): Zend_Loader::loadClass()
#2 [internal function]: Zend_Loader::loadClass(&#039;we2h4i58hd92jdf...&#039;)
#3 /www/htdocs/w008068a/tine-work/library/Zend/Loader/Autoloader.php(443): call_user_func(Array, &#039;we2h4i58hd92jdf...&#039;)
#4 [internal function]: Zend_Loader_Autoloader-&gt;_autoload(&#039;we2h4i58hd92jdf...&#039;)
#5 /www/htdocs/w008068a/tine-work/library/Zend/Loader/Autoloader.php(125): call_user_func(Array, &#039;we2h4i58hd92jdf...&#039;)
#6 [internal function]: Zend_Loader_Autoloader::autoload(&#039;we2h4i58hd92jdf...&#039;)
#7 [internal function]: spl_autoload_call(&#039;we2h4i58hd92jdf...&#039;)
#8 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Wbxml/Abstract.php(114): defined(&#039;Syncroton_Wbxml...&#039;)
#9 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Wbxml/Decoder.php(246): Syncroton_Wbxml_Abstract-&gt;getDPI(111)
#10 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Wbxml/Decoder.php(72): Syncroton_Wbxml_Decoder-&gt;_getDPI()
#11 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Wbxml/Decoder.php(139): Syncroton_Wbxml_Decoder-&gt;__construct(Resource id #475)
#12 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(123): Syncroton_Wbxml_Decoder-&gt;decode()
#13 /www/htdocs/w008068a/tine-work/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#14 /www/htdocs/w008068a/tine-work/ActiveSync/Server/Http.php(126): Syncroton_Server-&gt;handle()
#15 /www/htdocs/w008068a/tine-work/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()
#16 /www/htdocs/w008068a/tine-work/index.php(17): Tinebase_Core::dispatchRequest()
#17 {main}

@Lars: could you please have a look? maybe a Syncroton problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Aug 2013 10:52**

need to log wbxml before decoding.

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 30 Aug 2013 12:08**

Do you need any further help or logs I can gather?

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Aug 2013 12:42**

Are you able to capture the data using tcpdump or Wireshark?

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 30 Aug 2013 12:50**

Unfortunately not! But I&#039;ll ask a friend (with a Q10) if he can do it.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Aug 2013 13:15**

That would be great. 

If that&#039;s not possible, I can also provide a modified file, which stores the raw files in a directory. But a capture of the data as send on the wire(less) would be much better.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 24 Sep 2013 05:27**

I&#039;m pretty sure that we have fixed this problem. If not, please reopen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Oct 2013 13:00**

looks like the problem is still there: https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=15100

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Oct 2013 13:01**

ah, sorry, he is using Kristina.

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 29 Oct 2013 11:49**

Just updated to Collin and My Blackberry Z10 got BB10.2 last week. The problem is still there. Mails get sent several times and eventually will be show as not sent on the device!

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Oct 2013 10:20**

Can you capture the lines from the tine20.log file created when the phone tries to send the email?

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 31 Oct 2013 10:46**

Just added a logfile

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Feb 2014 09:07**

i can&#039;t see anything suspicious in the logs ...

is anyone able to dump the traffic via wireshark/tcpdump?

maybe we could use an emulator (BlackBerry 10 simulator) for debugging -&gt; http://us.blackberry.com/sites/developers/resources/simulators.html

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Feb 2014 13:09**

suvuk is trying to capture the packets send from bb -&gt; tine 2.0

see https://twitter.com/SuVuK/status/438970560954257408

**Comment by Gloirin** [comment]
**Comment posted by alec on 31 Mar 2014 15:43**

We investigated this issue for Kolab. See https://issues.kolab.org/show_bug.cgi?id=2952 for proposed fix.

**Comment by Gloirin** [comment]
**Comment posted by kaba71 on 26 May 2014 10:20**

Try the solution/fix described here 

https://issues.kolab.org/show_bug.cgi?id=2952 

i modified 
/vendor/syncrotron/syncroton/lib/Syncrotron/Server.php Line 137
ini_set(&#039;default_mimetype&#039;, null);

to
ini_set(&#039;default_mimetype&#039;, &#039;application/vnd.ms-sync.wbxml&#039;);

hope it helps. It works for me and a z10 with BB 10.2.1.2102

**Comment by Gloirin** [comment]
**Comment posted by suvuk on 26 May 2014 18:50**

This seems to work so far. Tested on 2 servers with several BB10 Devices.

**Comment by Gloirin** [comment]
**Comment posted by linuxq on 27 May 2014 08:08**

Works here also with my Z10 and Collin fro 05/26 :)

**Comment by Gloirin** [comment]
**Comment posted by mschnbeck on 29 May 2014 22:10**

I investigated this theme also without knowing this bugreport. Because the other command leave their getResponse with a result, I tried to do so in SendMail also by moving the second last braces up one line. So that &quot;return $this-&gt;_outputDom;&quot; is executed when leaving normal. This works for me, but because I&#039;m not sure, which one is the right solution, I also tried the above mentioned solution. Which works also.

**Comment by Gloirin** [comment]
**Comment posted by mschnbeck on 2 Oct 2014 14:51**

After installing Koriander the problem doesn&#039;t arise any longer with my Q10. As Koriander contains the syncrotron-code without the abovementioned changes, I don&#039;t know, whether changes anywhere else in Tine20 removed the problem or whether an update of blackberry did it.
