### ISSUE TITLE
0000706:
Release0.php throws Exception on altering table applications

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#444]
**Reported by ipavkovic on 15 Jan 2009 14:31**

**Version:** Lara (2009-02) Milestone 2

I used version http://svn.tine20.org/svn/branches/2009-02/tine20, revision 6234. Calling setup.php throws the following exception:

Application Phone is already up to date! Skipped...
Application Admin is already up to date! Skipped...
Application Tasks is already up to date! Skipped...
Executing updates for Tinebase (starting at 0.17)

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./tine20/#sql-c72_9f36&#039; to &#039;./tine20/tine20_applications&#039; (errno: 150)&#039; in /usr/share/php/libzend-framework-php/Zend/Db/Statement/Pdo.php:238 Stack trace: #0 /usr/share/php/libzend-framework-php/Zend/Db/Statement.php(283): Zend_Db_Statement_Pdo-&gt;_execute(Array) #1 /usr/share/php/libzend-framework-php/Zend/Db/Adapter/Abstract.php(406): Zend_Db_Statement-&gt;execute(Array) #2 /usr/share/php/libzend-framework-php/Zend/Db/Adapter/Pdo/Abstract.php(206): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array) #3 /var/www/tine20.kel.apliki.de/svn/tine20-2009-02/Setup/Backend/Abstract.php(137): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;) #4 /var/www/tine20.kel.apliki.de/svn/tine20-2009-02/Setup/Backend/Mysql.php(260): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;) #5 /var/www/tine20.kel.apliki.de/svn/tine20-2009-02/Tinebase/Setup/Update/Release0.php(1426): Setup_Backend_ in /usr/share/php/libzend-framework-php/Zend/Db/Statement/Pdo.php on line 238

the attached diff fixes this problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Feb 2009 15:20**

- added transaction to update script
- dropped correct foreign key in container table
