### ISSUE TITLE
0008976:
Passwords in plaintext in apache2-log

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4511]
**Reported by Solivagus on 30 Sep 2013 07:20**

**Version:** Kristina (2013.03.8)

The passwords of the users are written in apache2/error.log in plaintext.
should be removed from this.

**Additional information:** Mon Sep 16 10:01:56 2013] [error] [client 192.168.0.109] PHP Fatal error: Uncaught exception &#039;Zend_Auth_Adapter_Exception&#039; with message &#039;Domain is not an authority for user: NAME@DOMÄNE.de&#039; in /usr/share/tine20/Tinebase/Auth/Sql.php:52\nStack trace:\n#0 /usr/share/tine20/Tinebase/Auth/Sql.php(32): Tinebase_Auth_Sql-&gt;getCanonicalAccountName(&#039;NAME@DOMÄNE.de...&#039;)\n#1 /usr/share/tine20/Tinebase/Auth.php(195): Tinebase_Auth_Sql-&gt;setIdentity(&#039;NAME@DOMÄNE.de....&#039;)\n#2 /usr/share/tine20/Tinebase/Controller.php(74): Tinebase_Auth-&gt;authenticate(&#039;NAME@DOMÄNE.de....&#039;, &#039;PASSWORT_IM_KLARTEXT&#039;)\n#3 /usr/share/tine20/ActiveSync/Server/Http.php(159): Tinebase_Controller-&gt;login(&#039;NAME@DOMÄNE.de....&#039;, &#039;PASSWORT_IM_KLARTEXT&#039;, &#039;192.168.0.109&#039;, &#039;TineActiveSync&#039;)\n#4 /usr/share/tine20/ActiveSync/Server/Http.php(96): ActiveSync_Server_Http-&gt;_authenticate(&#039;DOMÄNE.de\\NAME...&#039;, &#039;PASSWORT_IM_KLARTEXT&#039;, &#039;192.168.0.109&#039;)\n#5 /usr/share/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle()\n#6 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()\n#7 {main}\n thrown in /usr/share/tine20/Tinebase/Auth/Sql.php on line 52

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Oct 2013 10:06**

check why the exception is not caught by generic exception handler.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Oct 2013 13:09**

- exception is now caught
- passwords are removed from trace string
