### ISSUE TITLE
0009066:
iCal .ics file import fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4554]
**Reported by HubertB on 17 Oct 2013 12:55**

**Version:** Collin (2013.10.1~rc2)

I&#039;m attemting to import an ics file, but it fails:

-----------------%&lt;----------------
# php tine20.php --verbose --username tine20admin --method Calendar.import plugin=Calendar_Import_Ical importContainerId=14 /root/mt_lightning.ics

password&gt;
reading file /root/mt_lightning.ics ...failed (can not parse ical file =&gt; syntax errors ?).
-----------------%&lt;----------------

I sent the .ics-file to pschuele in a separate email. Please do not publish it in any way as it contains privacy related and thus sensitive data.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Oct 2013 13:03**

i found the problem, one of the email addresses is too long. looks like we have to truncate this.

87d3e unittest - 2013-10-18T13:02:15+00:00 INFO (6): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::563 SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;email&#039; at row 1
87d3e unittest - 2013-10-18T13:02:16+00:00 DEBUG (7): Tinebase_Frontend_Cli_Abstract::_import::329 can not parse ical file =&gt; syntax errors ?
87d3e unittest - 2013-10-18T13:02:16+00:00 DEBUG (7): Tinebase_Frontend_Cli_Abstract::_import::330 #0 /home/pschuele/workspace/tine20/tine20/Tinebase/Import/Abstract.php(101): Calendar_Import_Ical-&gt;import(Resource id #337, Array)
#1 /home/pschuele/workspace/tine20/tine20/Tinebase/Frontend/Cli/Abstract.php(319): Tinebase_Import_Abstract-&gt;importFile(&#039;/home/pschuele/...&#039;)
#2 /home/pschuele/workspace/tine20/tine20/Calendar/Frontend/Cli.php(54): Tinebase_Frontend_Cli_Abstract-&gt;_import(Object(Zend_Console_Getopt))
#3 [internal function]: Calendar_Frontend_Cli-&gt;import(Object(Zend_Console_Getopt))
#4 /home/pschuele/workspace/tine20/tine20/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#5 /home/pschuele/workspace/tine20/tine20/Tinebase/Server/Cli.php(79): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#6 /home/pschuele/workspace/tine20/tine20/Tinebase/Core.php(240): Tinebase_Server_Cli-&gt;handle()
#7 /home/pschuele/workspace/tine20/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Oct 2013 13:07**

Calendar_Model_Attender::resolveEmailToContact should truncate the given email address if it is longer than 64 chars.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 18 Oct 2013 13:14**

It would also be nice to inform the user if such a truncation occurs during the import.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Oct 2013 13:31**

this should be solved in the final release (2013.10.1).

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 25 Oct 2013 09:21**

I updated to Collin (2013.10.1) today and re-tried the import. It is still failing. I&#039;ll send you the file via email.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Oct 2013 09:43**

thanks. I&#039;ll check that again.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 13 Dec 2013 09:31**

I don&#039;t see this issue on the roadmap. Any chance this makes it into Collin (2013.10.3)?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Dec 2013 10:05**

i&#039;ll try to solve this for 2013.10.3.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 2 Jan 2014 15:25**

Hi &amp; Happy New Year!

Have you&#039;ve been able to fix this in 2013.10.3? I&#039;m asking because I just updated to 2013.10.3 but the import is still failing.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jan 2014 10:38**

happy new year to you, too.

i hope, i&#039;ll find the time to look at the problem this week.

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 8 Jan 2014 13:34**

Ok thanks. I&#039;d be happy to help with testing so just let me know when you have something.

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Nov 2016 08:24**

is this issue still present?

**Comment by Gloirin** [comment]
**Comment posted by HubertB on 15 Nov 2016 16:46**

Unfortunately, I don&#039;t have that old setup anymore. It has been decided to migrate everything to Exchange / Outlook (narf) :-(
