### ISSUE TITLE
0009124:
After update calendar won´t work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4583]
**Reported by bofh1976 on 24 Oct 2013 14:55**

**Version:** Collin (2013.10.1)

New installation or Update from Kristin to Collin 2013.10.1 the calendar doesn´t respond any more. It always throws the error:
&quot;Dienst nicht verfügbar
Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.&quot;

ENG(short): Service is not available. 

**Steps to reproduce:** Install Kristina and set it up.
Then copy the new 2013.10.1 files into the webfolder.
Go to setup page and update the applications.
After that in the webapp calendar you can see the error.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 24 Oct 2013 15:24**

Can you please check the logfiles(tine20.log and apache error log file)? 

There must be an error message somewhere.

**Comment by Gloirin** [comment]
**Comment posted by bofh1976 on 24 Oct 2013 19:47**

I have attached some files. I´m not sure if these are the logs you need, as I´m no expert.
The tine20.log is made in &quot;trace&quot; mode.
If you need something else, please advice how I can get the information.

**Comment by Gloirin** [comment]
**Comment posted by bofh1976 on 25 Oct 2013 06:59**

Additional Information, as there were no errors in the logs.

Creating a new calender within an Tine20 account works for a couple of minutes as expected and then throws the error.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Oct 2013 08:24**

this is the problem:

38a88 656d8 chris - 2013-10-24T19:44:16+00:00 WARN (4): Tinebase_Server_Json::_handleException::261 Tinebase_Exception_Backend -&gt; No base path (filesdir) configured or path not writeable
38a88 656d8 chris - 2013-10-24T19:44:16+00:00 WARN (4): Tinebase_Exception::log::99 Tinebase_Exception_Backend -&gt; No base path (filesdir) configured or path not writeable
38a88 656d8 chris - 2013-10-24T19:44:16+00:00 NOTICE (5): Tinebase_Exception::log::107 #0 .../Tinebase/FileSystem.php(83): Tinebase_FileSystem-&gt;__construct()
#1 .../Tinebase/FileSystem/RecordAttachments.php(40): Tinebase_FileSystem::getInstance()
#2 .../Tinebase/FileSystem/RecordAttachments.php(51): Tinebase_FileSystem_RecordAttachments-&gt;__construct()
#3 .../Calendar/Convert/Event/Json.php(99): Tinebase_FileSystem_RecordAttachments::getInstance()
#4 .../Tinebase/Frontend/Json/Abstract.php(503): Calendar_Convert_Event_Json-&gt;fromTine20RecordSet(Object(Tinebase_Record_RecordSet), Object(Calendar_Model_EventFilter), Object(Tinebase_Model_Pagination))
#5 .../Calendar/Frontend/Json.php(187): Tinebase_Frontend_Json_Abstract-&gt;_multipleRecordsToJson(Object(Tinebase_Record_RecordSet), Object(Calendar_Model_EventFilter), Object(Tinebase_Model_Pagination))
#6 [internal function]: Calendar_Frontend_Json-&gt;searchEvents(Array, Array)
#7 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#8 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#9 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#10 .../Tinebase/Server/Json.php(234): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#11 .../Tinebase/Server/Json.php(104): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#12 .../Tinebase/Core.php(240): Tinebase_Server_Json-&gt;handle()
#13 .../index.php(17): Tinebase_Core::dispatchRequest()
#14 {main}

you have to configure a path for the tine 2.0 filesystem in the setup.
this should fix it.

but: I&#039;ll have a look at this, because the configured path should not be mandatory.

**Comment by Gloirin** [comment]
**Comment posted by bofh1976 on 25 Oct 2013 11:41**

Yes, that´s the reason!

I created and configured a path for the filesystem and now the error won´t appear anymore and I can see the entries in the calendars again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Oct 2013 12:42**

ok :)

thanks for testing.

the filesdir will be optional again in the version 2013.10.2

**Comment by Gloirin** [comment]
**Comment posted by bofh1976 on 25 Oct 2013 15:37**

You´re welcome, thanks for your help!
