### ISSUE TITLE
0009130:
Can't open login page on Ubuntu "due to a temporary overloading"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4586]
**Reported by 80686 on 25 Oct 2013 08:28**

**Version:** Collin (2013.10.1)

This problem existed both in 2013.08.03 and still exists with 2013.10.1.

Tine 2.0 works fine for various users on various platforms but Ubuntu users complain they cant access Tine 2.0 at all, the don&#039;t even get to the login screen:
&quot;The server is currently unable to handle the request due to a temporary overloading, maintenance or misconfiguration of the server. Please try again or contact your administrator.&quot;

This occurs both in Firefox and Chromium for at least to users on Ubuntu.

At the same time Apache and MySQL work fine and other users can use Tine with no problems.

The only hint I can find is in the Apache error_log:

&quot;[Thu Oct 24 18:48:27 2013] [error] [client 178.196.25.204] PHP Fatal error:  Uncaught exception &#039;ErrorException&#039; with message &#039;Method Zend_Json_Ser
ver_Response_Http::__toString() must return a string value&#039; in /var/www/intern/office/Tinebase/Server/Json.php:112
Stack trace:
#0 /var/www/intern/office/Tinebase/Server/Json.php(112): Tinebase_Core::errorHandler(4096, &#039;Method Zend_Jso...&#039;, &#039;/var/www/intern...&#039;, 112, Array)
#1 /var/www/intern/office/Tinebase/Core.php(240): Tinebase_Server_Json-&gt;handle()
#2 /var/www/intern/office/index.php(17): Tinebase_Core::dispatchRequest()
#3 {main}
  thrown in /var/www/intern/office/Tinebase/Server/Json.php on line 112, referer: https://intern.wikimedia.ch/office/&quot;

These errors only appear if one of these users access Tine.

**Steps to reproduce:** * open https://intern.wikimedia.ch/office/ on Ubuntu
* error message appears, login page doesn&#039;t load

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 4 Nov 2013 10:50**

I just experienced the same issue again on another computer I was helping the user to setup synchronisation with Tine.

Windows 8 Pro, Firefox 25.0 or Google Chrome 30.0.1599.101m - cannot open login page, same error as above

same computer, Internet Explorer 10 - works

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 5 Nov 2013 20:16**

Hi,

I am running Ubuntu too, (well, Kubuntu 13.10) with both Chrome and Firefox.
No issues for both Collin and git master.
Also running Windows7 with Firefox and Chrome on another machine. No issues.

**Comment by Gloirin** [comment]
**Comment posted by Kelson on 6 Nov 2013 09:37**

@ingoratsdorf
Do you have tried with this url https://intern.wikimedia.ch/office/ ?

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 6 Nov 2013 10:24**

Yup, just now using ubuntu and firefox. I get a login screen.

**Comment by Gloirin** [comment]
**Comment posted by Kelson on 6 Nov 2013 10:48**

@ingoratsdorf
I have tried again and I have got a few information more. Let us focus of FF.

If I do
$rm -rf ~/.mozilla ; firefox http://intern.wikimedia.ch/office/

I get the Tine login screen, so everything works well. But, if I simply restart Firefox then it fails (like described before). I have launched the console debugging and it ends with:
[11:42:14,669] &quot;RecordPickerManager::registerItem: AddressbookContact&quot;
[11:42:14,673] &quot;RecordPickerManager::registerItem: ProjectsProject&quot;
[11:42:14,676] &quot;RecordPickerManager::registerItem: FilemanagerNode&quot;
[11:42:14,680] &quot;Initializing relation renderer with config:&quot;
[11:42:14,680] &quot;appName: Tasks, type: TASK, foreignApp: Crm, foreignModel: Lead&quot;
[11:42:14,697] &quot;RecordPickerManager::registerItem: TimetrackerTimeaccount&quot;
[11:42:14,699] &quot;RecordPickerManager::registerItem: CalendarEvent&quot;
[11:42:14,869] &quot;RecordPickerManager::registerItem: TinebaseContainer&quot;
[11:42:15,426] TypeError: b.get is not a function @ https://intern.wikimedia.ch/office/index.php?method=Tinebase.getJsFiles:45

This error seems not to be there if I launch without any profile... So, this seems to me to be related to the problem.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 6 Nov 2013 10:56**

Hmm, sorry mate.
I restarted firefox, I reloaded the page several times, closed it and loaded again, ....

I still get a login screen. Nothing unusual.

Maybe something in your configuration, some network filter, some setting, some plugin, ...??

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 20 May 2014 19:04**

Can we please get rid of this bug? I have seen users on Mac who cannot access the Tine interface no matter what they do, reproducable on several computers and with different Tine instances on different installations.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 May 2014 16:13**

hi,

@80686: do you see errors in you javascript console, too? if not, there is a problem on your server and you should check your server log files (error.log + tine log). did you already update your Tine 2.0 installation to the latest service release?

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 21 May 2014 21:13**

yes, the problem persists through all the versions, from 2013.08.03 to today 2013.10.5.

You can check yourself: https://intern.wikimedia.ch/office/

It works perfectly fine for me and most users, but not for some, as the user with Ubuntu has described above in this bug report and what our Apple user reports to me regularly.

I still see the same error message I have reported initially:
[Tue May 20 22:42:05 2014] [error] [client 144.85.179.17] PHP Fatal error:  Uncaught exception &#039;ErrorException&#039; with message &#039;Method Zend_Json_Serv
er_Response_Http::__toString() must return a string value&#039; in /var/www/intern/auth-int/office/Tinebase/Server/Json.php:116\nStack trace:\n#0 /var/w
ww/intern/auth-int/office/Tinebase/Server/Json.php(116): Tinebase_Core::errorHandler(4096, &#039;Method Zend_Jso...&#039;, &#039;/var/www/intern...&#039;, 116, Array)\
n#1 /var/www/intern/auth-int/office/Tinebase/Core.php(251): Tinebase_Server_Json-&gt;handle()\n#2 /var/www/intern/auth-int/office/index.php(19): Tineb
ase_Core::dispatchRequest()\n#3 {main}\n  thrown in /var/www/intern/auth-int/office/Tinebase/Server/Json.php on line 116, referer: https://intern.w
ikimedia.ch/office/

These are the requests:

144.85.179.17 - - [20/May/2014:22:42:03 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/qtip/tip-sprite.gif HTTP/1.1&quot; 200 4271 &quot;https://i
ntern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:03 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/qtip/tip-anchor-sprite.gif HTTP/1.1&quot; 200 951 &quot;htt
ps://intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:05 +0200] &quot;POST /office/index.php?transactionid=de2408ec2c8ddb7a743fc658610abb90e428d5eb HTTP/1.1&quot; 200 678 &quot;ht
tps://intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:06 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/window/left-corners.png HTTP/1.1&quot; 200 200 &quot;https:
//intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:06 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/window/right-corners.png HTTP/1.1&quot; 200 256 &quot;https
://intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:06 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/window/top-bottom.png HTTP/1.1&quot; 200 180 &quot;https://
intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:06 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/window/left-right.png HTTP/1.1&quot; 200 152 &quot;https://
intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:06 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/panel/tool-sprites.gif HTTP/1.1&quot; 200 4392 &quot;https:
//intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:07 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/button/btn.gif HTTP/1.1&quot; 200 4298 &quot;https://intern
.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:08 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/qtip/bg.gif HTTP/1.1&quot; 200 1091 &quot;https://intern.wi
kimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:08 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/progress/progress-bg.gif HTTP/1.1&quot; 200 834 &quot;https
://intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:09 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/window/icon-warning.gif HTTP/1.1&quot; 200 1483 &quot;https
://intern.wikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:09 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/shadow-lr.png HTTP/1.1&quot; 200 135 &quot;https://intern.w
ikimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:09 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/shadow.png HTTP/1.1&quot; 200 311 &quot;https://intern.wiki
media.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;
144.85.179.17 - - [20/May/2014:22:42:09 +0200] &quot;GET /office/themes/tine20/resources/images/tine20/shadow-c.png HTTP/1.1&quot; 200 118 &quot;https://intern.wi
kimedia.ch/office/&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36&quot;

**Comment by Gloirin** [comment]
**Comment posted by martin on 22 May 2014 00:44**

I can see the login screen with Firefox &amp; Chrome on Ubuntu 14.04

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 22 May 2014 10:16**

Works for me too  :-)
Ubuntu 14.04, Firefox 29.0.

Loaded, reloaded, closed, loaded, ... All okay, no errors. I get a login screen.

On anoher note: Your UA is saying that you are using Chrome on Windows 7.... not ubuntu?

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 22 May 2014 10:58**

The problem initially appeared with a user running Ubuntu but as written in the other comments above we have seen this problem in Windows 8 and on Macs, on several different browsers.

Again, I am running Linux with Firefox and it works perfectly for me. But then again, we have users that have no way in accessing the Tine interface, no matter what they do. So there is a problem we need to find and fix.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 22 May 2014 10:59**

One common denominator is actually that all these users - the Ubuntu user, the Windows 8 user (now on Windows 7 where it works on Firefox but not in Chrome) and the Apple user who tried different devices and browsers with no luck at all are french-speakers, so I guess they have a french locale.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 May 2014 07:31**

ah, that&#039;s a good hint. there might be a problem with the french translations. maybe a broken utf-8 string.

you could try setting the browser locale to english and remove the Tine 2.0 cookies. that should reset the login screen locale to en. if it works then, we have a closer look at the frensh translations / locale and try to reproduce the problem.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 29 May 2014 10:27**

I also read about some broken French in Debian. I came across that when downloading clonezilla. Maybe related, maybe not. And Ubuntu is Debian based....

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 2 Jun 2014 10:42**

Bingo.

I am running Firefox 24.3.0 on GNU/Linux and have always used Tine without any problems. My language settings in Firefox are de / en / en-us.

Today I added language fr and moved it at highest priority. Then I loaded the Tine login screen and got this error message.

After removing fr from the list of languages and reloading the login page everything was back to normal.

Conclusion: The problem is caused by the french language.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 9 Jun 2014 18:07**

Did some further research:

Line 1 in Tinebase/js/Tinebase-lang-fr.js has a strange line-ending. I removed it but no change so far. Maybe a caching issue.

Tried several variants of french language settings:

fr: BUG
fr_BE: OK
fr_CA: BUG
fr_CH: OK
fr_FR: BUG
fr_LU: OK
fr_MC: BUG

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 9 Jun 2014 22:31**

I could track the issue back to Tinebase/Frontend/Json.php (604):

        $numberString = Zend_Locale_Format::toFloat(1234.56);

This return value must be wrong when these locales have been loaded. The thousandSeperator gets assigned an invalid value on line 631:

            &#039;thousandSeparator&#039; =&gt; $numberString[1],

I couldn&#039;t yet find my way through the jungle of Zend classes and abstract method to find out from which locale file the locale is actually being loaded.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 9 Jun 2014 22:57**

value in JSON response array:
[&quot;thousandSeparator&quot;] =&gt; string(1) &quot;Â&quot;

library/Zend/Locale/Data/fr.xml:
                        &lt;group&gt; &lt;/group&gt;

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 12 Jun 2014 08:48**

In fact there are 2 characters between &lt;group&gt; &lt;/group&gt;. 

If you have a look at this file with a hex editor, you will find the ASCII codes C2 and A0 between the tags. Which resolves to Â and the space character.

Please try following. Delete the whole line and add it again with only a space character between the group tags. That should fix the problem.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 12 Jun 2014 10:16**

the problem is: Whatever I change here it doesn&#039;t make any difference. Already tried STRG+F5, restarting Apache... no luck.

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 12 Jun 2014 12:44**

after rm -r /tmp/zend_cache* this works...

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 12 Jun 2014 12:58**

http://framework.zend.com/issues/browse/ZF-9242

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 12 Jun 2014 13:26**

Patch submission:

I think in general the hack with $numberString = Zend_Locale_Format::toFloat(1234.56); / &#039;thousandSeparator&#039; =&gt; $numberString[1] is relatively ugly.
We should better ask Zend_Locale directly what values it had set.

This can easily be done:

Tinebase/Frontend/Json.php
604,605c604,605
&lt;         $numberString = Zend_Locale_Format::toFloat(1234.56);
&lt; var_dump( Zend_Locale::getTranslationList(&#039;symbols&#039;, $locale));
---
&gt;         $symbols = Zend_Locale::getTranslationList( &#039;symbols&#039;, $locale );
&gt;         
631,632c631,632
&lt;             &#039;thousandSeparator&#039; =&gt; $numberString[1],
&lt;             &#039;decimalSeparator&#039;  =&gt; $numberString[5],
---
&gt;             &#039;thousandSeparator&#039; =&gt; $symbols[&#039;group&#039;],
&gt;             &#039;decimalSeparator&#039;  =&gt; $symbols[&#039;decimal&#039;],

**Comment by Gloirin** [comment]
**Comment posted by 80686 on 12 Jun 2014 13:30**

I want to add that the patch above even works with the original fr.xml file with the multibyte character.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Jun 2014 19:09**

good work :)

I&#039;ll add that to our gerrit review system to be reviewed for the upcoming release.
