### ISSUE TITLE
0009152:
saving of record fails because of too many relations

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4597]
**Reported by pschuele on 28 Oct 2013 14:59**

**Version:** Collin (2013.10.1)

saving of record fails because of too many relations

**Additional information:** e995d 7a21d pschuele - 2013-10-24T09:08:08+00:00 WARN (4): 
Tinebase_Exception::log::99 Zend_Db_Statement_Exception -&gt; SQLSTATE[22001]: 
String data, right truncated: 1406 Data too long for column &#039;old_valu
e&#039; at row 1
e995d 7a21d pschuele - 2013-10-24T09:08:08+00:00 NOTICE (5): 
Tinebase_Exception::log::107 #0 .../library/Zend/Db/Statement.php(284): 
Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-
&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): 
Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): 
Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Zend/Db/Table/Abstract.php(1055): Zend_Db_Adapter_Abstract-
&gt;insert(&#039;tine20_timemach...&#039;, Array)
#5 .../Tinebase/Timemachine/ModificationLog.php(270): Zend_Db_Table_Abstract-
&gt;insert(Array)
#6 .../Tinebase/Timemachine/ModificationLog.php(652): 
Tinebase_Timemachine_ModificationLog-
&gt;setModification(Object(Tinebase_Model_ModificationLog))
#7 .../Tinebase/Timemachine/ModificationLog.php(575): 
Tinebase_Timemachine_ModificationLog-&gt;_loopModifications(Array, 
Object(Tinebase_Model_ModificationLog), Object(Tinebase_Record_RecordSet),

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Oct 2013 15:24**

we should add an update script (if it does not exist already) that increases old_value size to longtext.
