### ISSUE TITLE
0009226:
js problem with foreign record filter

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4632]
**Reported by pschuele on 11 Nov 2013 10:49**

**Version:** Collin (2013.10.1)

js problem with foreign record filter

HR app shows ERROR in toolbar and grid

**Additional information:** TypeError: Cannot call method &#039;getMeta&#039; of undefined
    at Tine.widgets.grid.ForeignRecordFilter.Ext.extend.initExplicit (https://demo.tine20.net/index.php?method=Tinebase.getJsFiles:31033:53)
    at Tine.widgets.grid.ForeignRecordFilter.Ext.extend.initComponent (https://demo.tine20.net/index.php?method=Tinebase.getJsFiles:30981:65)
    at Tine.widgets.grid.FilterModel (https://demo.tine20.net/index.php?method=Tinebase.getJsFiles:26909:10)
    at sb (https://demo.tine20.net/library/ExtJS/adapter/ext/ext-base-debug.js:241:94)
    at new sb (https://demo.tine20.net/library/ExtJS/adapter/ext/ext-base-debug.js:241:94)
    at Ext.extend.createFilterModel (https://demo.tine20.net/index.php?method=Tinebase.getJsFiles:28651:20)
    at Ext.extend.initComponent (https://demo.tine20.net/index.php?method=Tinebase.getJsFiles:28596:27)
    at Ext.Component (https://demo.tine20.net/library/ExtJS/ext-all-debug.js:14722:10)
    at sb (https://demo.tine20.net/library/ExtJS/adapter/ext/ext-base-debug.js:241:94)
    at sb (https://demo.tine20.net/library/ExtJS/adapter/ext/ext-base-debug.js:241:94)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Nov 2013 11:04**

config (foreignRecordClass, ownRecordClass) seems to be missing.
