### ISSUE TITLE
0009256:
Bei Passwort mit bestimmten Sonderzeichen keine Anmeldung CalDAV möglich

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4647]
**Reported by Hugo76 on 14 Nov 2013 17:53**

**Version:** Collin (2013.10.1)

Setzt man ein Passwort, welches bestimmte Sonderzeichen enthält, ist keine Anmeldung z.B. über http://tinedomain/calendars möglich.
Es erscheint immer wieder die Passwortabfrage.
Die Anmeldung über das Web-Frontend funktioniert dagegen problemlos.

Fehlermeldungen im Log:
e6dbb -- none -- - 2013-11-14T17:33:47+00:00 WARN (4): Tinebase_Auth::authenticate::216 Authentication of tinenutzer failed
e6dbb -- none -- - 2013-11-14T17:33:47+00:00 WARN (4): Tinebase_User_Sql::setLastLoginFailure::570 Login of user tinenutzer failed.

**Steps to reproduce:** 1. Setzen eines Passworts im Web-Frontend: &quot;test&quot; -&gt; Anmeldung funktioniert
2. Passwort ändern im Web-Frontend: &quot;test:&quot; -&gt; schlägt fehl
3. zurücksetzen auf &quot;test&quot; -&gt; Anmeldung funktioniert

=&gt; Der Doppelpunkt im Passwort, macht das Passwort zur caldav-Anmeldung unbrauchbar

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 15 Nov 2013 11:46**

Fix for the problem:

Replace

list($loginName, $password) = explode(&quot;:&quot;, $basicAuthData);

with 

list($loginName, $password) = explode(&quot;:&quot;, $basicAuthData, 1);

in Tinebase\Server\WebDAV.php

**Comment by Gloirin** [comment]
**Comment posted by Hugo76 on 15 Nov 2013 12:44**

with this fix call of http://tinedomain.de/calendars throws this error:

Fatal error: Uncaught exception &#039;Zend_Auth_Adapter_Exception&#039; with message &#039;A credential value was not provided prior to authentication with Zend_Auth_Adapter_DbTable.&#039; in /tine/library/Zend/Auth/Adapter/DbTable.php:344 Stack trace: #0 /tine/library/Zend/Auth/Adapter/DbTable.php(304): Zend_Auth_Adapter_DbTable-&gt;_authenticateSetup() #1 /tine/library/Zend/Auth.php(117): Zend_Auth_Adapter_DbTable-&gt;authenticate() #2 /tine/Tinebase/Auth.php(209): Zend_Auth-&gt;authenticate(Object(Tinebase_Auth_Sql)) #3 /tine/Tinebase/Controller.php(75): Tinebase_Auth-&gt;authenticate(&#039;tinenutzer&#039;, NULL) #4 /tine/Tinebase/Server/WebDAV.php(69): Tinebase_Controller-&gt;login(&#039;tinenutzer&#039;, NULL, &#039;hierstehtIP&#039;, &#039;TineWebDav&#039;) #5 /ti in /tine/library/Zend/Auth/Adapter/DbTable.php on line 344

in log:
aa07a -- none -- - 2013-11-15T12:32:51+00:00 NOTICE (5): Tinebase_Core::errorHandler::478 Undefined offset: 1 in .../Tinebase/Server/WebDAV.php::59 (8)
aa07a -- none -- - 2013-11-15T12:32:51+00:00 NOTICE (5): Tinebase_Core::errorHandler::479 #0 .../Tinebase/Server/WebDAV.php(59): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;...&#039;, 59, Array)
#1 .../Tinebase/Core.php(240): Tinebase_Server_WebDAV-&gt;handle()
#2 .../index.php(17): Tinebase_Core::dispatchRequest()
#3 {main}

no problems in web-frontend

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 15 Nov 2013 12:57**

Sorry! It has to be this way:

list($loginName, $password) = explode(&quot;:&quot;, $basicAuthData, 2);

**Comment by Gloirin** [comment]
**Comment posted by Hugo76 on 15 Nov 2013 13:31**

yes, this seems to be good for &quot;:&quot;

but there seems to be other signs with the same problem: &quot; § # and Umlaute for example.

I think all passwords, which are possible with web-frontend, also should be possible with caldav.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 21 Nov 2013 05:33**

Fix for colon is commited. Problems with other passwords still have to be investigated.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Nov 2013 09:38**

maybe we need to convert pws to utf8. further research required.
