### ISSUE TITLE
0009262:
Import Calender fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4650]
**Reported by vignesh_murali on 14 Nov 2013 22:00**

**Version:** Kristina (2013.03.8)

I try to import calendars by using the following command

php tine20.php --method=Calendar.import --username=user -v plugin=Calendar_Import_Ical importContainerId=362 /Calendar_2010-2014.ics 
password&gt; 
reading file /Calendar_2010-2014.ics ...failed (can not parse ical file =&gt; syntax errors ?).

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 14 Nov 2013 23:36**

I had similar issues when importing my calendars still under CollinRC2 a months or so back.
It apparently complained about ALL recurring events. Simple events imported, recurring ones did simply not.
Trouble is that the import function is not really a chatterbox... ;-)
There&#039;s no chance in finding out what the issue is.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 14 Nov 2013 23:39**

@vignesh_murali: Are you sure it&#039;s okay to leave your calendar ICS file here? This bug tracker is public....
Just asking.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Nov 2013 07:47**

i downloaded and deleted the file. I&#039;ll test the import with the current stable branch (Collin).

maybe I&#039;ll add some better error reporting to the import function, too. but you can always look into the logfile, all problems (except uncatchable errors) should appear there...

**Comment by Gloirin** [comment]
**Comment posted by vignesh_murali on 15 Nov 2013 15:59**

Thank you for the prompt response. I didn&#039;t see any significant errors in the log file. Is it a bug in Calendar import function of the Kristina version or error in the ICS file?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2013 10:17**

there is indeed a problem with your ics file (and no helpful logging in tine). I added some logging to the import and got this error:

c6028 pschuele - 2013-11-18T10:15:50+00:00 WARN (4): Tinebase_Exception::log::99 Sabre\VObject\ParseException -&gt; Invalid Mimedir file. Line starting at 14 did not follow iCalendar/vCard conventions
c6028 pschuele - 2013-11-18T10:15:50+00:00 NOTICE (5): Tinebase_Exception::log::107 #0 .../vendor/sabre/vobject/lib/Sabre/VObject/Parser/MimeDir.php(175): Sabre\VObject\Parser\MimeDir-&gt;readProperty(&#039;ATTENDEE;CN=Oso...&#039;)
#1 .../vendor/sabre/vobject/lib/Sabre/VObject/Parser/MimeDir.php(158): Sabre\VObject\Parser\MimeDir-&gt;parseLine(&#039;ATTENDEE;CN=Oso...&#039;)
#2 .../vendor/sabre/vobject/lib/Sabre/VObject/Parser/MimeDir.php(123): Sabre\VObject\Parser\MimeDir-&gt;parseLine(&#039;BEGIN:VEVENT&#039;)
#3 .../vendor/sabre/vobject/lib/Sabre/VObject/Parser/MimeDir.php(61): Sabre\VObject\Parser\MimeDir-&gt;parseDocument()
#4 .../vendor/sabre/vobject/lib/Sabre/VObject/Reader.php(44): Sabre\VObject\Parser\MimeDir-&gt;parse(&#039;BEGIN:VCALENDAR...&#039;, 0)
#5 .../Calendar/Convert/Event/VCalendar/Abstract.php(495): Sabre\VObject\Reader::read(&#039;BEGIN:VCALENDAR...&#039;)
#6 .../Calendar/Convert/Event/VCalendar/Abstract.php(466): Calendar_Convert_Event_VCalendar_Abstract::readVCalBlob(&#039;BEGIN:VCALENDAR...&#039;)
#7 .../Calendar/Convert/Event/VCalendar/Abstract.php(432): Calendar_Convert_Event_VCalendar_Abstract::getVObject(Resource id #342)
#8 .../Calendar/Import/Ical.php(108): Calendar_Convert_Event_VCalendar_Abstract-&gt;toTine20RecordSet(Resource id #342)
#9 .../Tinebase/Import/Abstract.php(101): Calendar_Import_Ical-&gt;import(Resource id #342, Array)
#10 .../Tinebase/Frontend/Cli/Abstract.php(319): Tinebase_Import_Abstract-&gt;importFile(&#039;/home/pschuele/...&#039;)
#11 .../Calendar/Frontend/Cli.php(54): Tinebase_Frontend_Cli_Abstract-&gt;_import(Object(Zend_Console_Getopt))
#12 [internal function]: Calendar_Frontend_Cli-&gt;import(Object(Zend_Console_Getopt))
#13 .../Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#14 .../Tinebase/Server/Cli.php(79): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#15 .../Tinebase/Core.php(240): Tinebase_Server_Cli-&gt;handle()
#16 .../tine20.php(73): Tinebase_Core::dispatchRequest()
#17 {main}

**Comment by Gloirin** [comment]
**Comment posted by vignesh_murali on 19 Nov 2013 17:06**

Hey thanks for the error logging . I now get the following error messgae

 php tine20.php --method=Calendar.import --username=user -v plugin=Calendar_Import_Ical importContainerId=362 /eve.ics 

password&gt; 
reading file /eve.ics ...failed (Tinebase_Model_Container record with id = 362 not found!).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Nov 2013 10:52**

you need to make sure that you use the correct container id for the import. it must be existing. you can find the id in Admin/Containers or by right-clicking on the calendar (properties: CalDAV URL -&gt; number after the last slash).

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Nov 2016 08:25**

should be fixed long time ago. Please reopen if still an issue for you
