### ISSUE TITLE
0009290:
simplexml_load_file error when loading locale

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4664]
**Reported by Gurney on 21 Nov 2013 13:54**

**Version:** git master

Hi,

With the latest git and composer update (today), I get the following error (I think it&#039;s for each translation).

Any clue what&#039;s going on?

It happens for:
library/Zend/Locale/Data/bg.xml
library/Zend/Locale/Data/root.xml

and I think for every translation.

**Additional information:** 70ce5 -- none -- - 2013-11-21T13:38:00+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1123 given localeString &#039;auto&#039;
70ce5 -- none -- - 2013-11-21T13:38:00+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1150 Try to detect the locale of the user (browser, environment, default)
70ce5 -- none -- - 2013-11-21T13:38:00+00:00 DEBUG (7): Tinebase_Translation::getLocale::204 given localeString &#039;auto&#039;
70ce5 -- none -- - 2013-11-21T13:38:00+00:00 WARN (4): Tinebase_Core::errorHandler::477 simplexml_load_file(): I/O warning : failed to load external entity &quot;/media/server/www/tine20/tine20/library/Zend/Locale/Data/bg.xml&quot; in /media/server/www/tine20/tine20/library/Zend/Locale/Data.php::154 (2)
70ce5 -- none -- - 2013-11-21T13:38:00+00:00 WARN (4): Tinebase_Core::errorHandler::478 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;simplexml_load_...&#039;, &#039;/media/server/w...&#039;, 154, Array)
#1 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(154): simplexml_load_file(&#039;/media/server/w...&#039;)
#2 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(224): Zend_Locale_Data::_findRoute(&#039;bg&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;, false, Array)
#3 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(944): Zend_Locale_Data::_getFile(&#039;bg&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;)
#4 /media/server/www/tine20/tine20/library/Zend/Locale.php(607): Zend_Locale_Data::getContent(&#039;bg&#039;, &#039;language&#039;, &#039;bg&#039;)
#5 /media/server/www/tine20/tine20/Tinebase/Translation.php(121): Zend_Locale::getTranslation(&#039;bg&#039;, &#039;language&#039;, Object(Zend_Locale))
#6 /media/server/www/tine20/tine20/Tinebase/Translation.php(210): Tinebase_Translation::getAvailableTranslations()
#7 /media/server/www/tine20/tine20/Tinebase/Core.php(1155): Tinebase_Translation::getLocale(&#039;auto&#039;)
#8 /media/server/www/tine20/tine20/Tinebase/Core.php(416): Tinebase_Core::setupUserLocale()
#9 /media/server/www/tine20/tine20/ActiveSync/Server/Http.php(53): Tinebase_Core::initFramework()
#10 /media/server/www/tine20/tine20/Tinebase/Core.php(240): ActiveSync_Server_Http-&gt;handle()
#11 /media/server/www/tine20/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#12 {main}

[...]

14868 etienne - 2013-11-21T13:38:24+00:00 WARN (4): Tinebase_Core::errorHandler::477 simplexml_load_file(): I/O warning : failed to load external entity &quot;/media/server/www/tine20/tine20/library/Zend/Locale/Data/root.xml&quot; in /media/server/www/tine20/tine20/library/Zend/Locale/Data.php::154 (2)
14868 etienne - 2013-11-21T13:38:24+00:00 WARN (4): Tinebase_Core::errorHandler::478 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;simplexml_load_...&#039;, &#039;/media/server/w...&#039;, 154, Array)
#1 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(154): simplexml_load_file(&#039;/media/server/w...&#039;)
#2 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(224): Zend_Locale_Data::_findRoute(&#039;root&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;, false, Array)
#3 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(240): Zend_Locale_Data::_getFile(&#039;root&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;, false, Array)
#4 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(238): Zend_Locale_Data::_getFile(&#039;zh&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;, false, Array)
#5 /media/server/www/tine20/tine20/library/Zend/Locale/Data.php(953): Zend_Locale_Data::_getFile(&#039;zh_TW&#039;, &#039;/ldml/localeDis...&#039;, &#039;type&#039;)
#6 /media/server/www/tine20/tine20/library/Zend/Locale.php(607): Zend_Locale_Data::getContent(&#039;zh_TW&#039;, &#039;country&#039;, &#039;TW&#039;)
#7 /media/server/www/tine20/tine20/Tinebase/Translation.php(123): Zend_Locale::getTranslation(&#039;TW&#039;, &#039;country&#039;, Object(Zend_Locale))
#8 /media/server/www/tine20/tine20/Tinebase/Translation.php(210): Tinebase_Translation::getAvailableTranslations()
#9 /media/server/www/tine20/tine20/Tinebase/Core.php(1155): Tinebase_Translation::getLocale(&#039;auto&#039;)
#10 /media/server/www/tine20/tine20/Tinebase/Controller.php(201): Tinebase_Core::setupUserLocale(&#039;auto&#039;)
#11 /media/server/www/tine20/tine20/Tinebase/Controller.php(98): Tinebase_Controller-&gt;_initUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_AccessLog), &#039;********&#039;)
#12 /media/server/www/tine20/tine20/ActiveSync/Server/Http.php(151): Tinebase_Controller-&gt;login(&#039;etienne&#039;, &#039;********&#039;, &#039;64.79.144.10&#039;, &#039;TineActiveSync&#039;)
#13 /media/server/www/tine20/tine20/ActiveSync/Server/Http.php(73): ActiveSync_Server_Http-&gt;_authenticate(&#039;etienne&#039;, &#039;********&#039;, &#039;64.79.144.10&#039;)
#14 /media/server/www/tine20/tine20/Tinebase/Core.php(240): ActiveSync_Server_Http-&gt;handle()
#15 /media/server/www/tine20/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Nov 2013 14:38**

hi Etienne, we did not change those xml files. are you sure, it&#039;s no filesystem problem on your server? can you open the files with an editor?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 21 Nov 2013 18:11**

I just checked and all permissions are correc, files open correctly.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2013 09:46**

does this only happen for ActiveSync request or do you see the errors when logged in with the web client, too?
