### ISSUE TITLE
0009296:
can not create group

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4667]
**Reported by martin on 22 Nov 2013 12:43**

**Version:** Collin (2013.10.2)

see logfile

**Additional information:** b320 0ad82 user - 2013-11-22T11:39:53+00:00 DEBUG (7): Tinebase_Server_Json::handle::96 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Admin.saveGroup
            [params] =&gt; Array
                (
                    [groupData] =&gt; Array
                        (
                            [visibility] =&gt; hidden
                            [container_id] =&gt; 
                            [name] =&gt; sync
                            [description] =&gt; 
                        )

                    [groupMembers] =&gt; Array
                        (
                        )

                )

            [id] =&gt; 2
        )

)

3b320 0ad82 user - 2013-11-22T11:39:53+00:00 INFO (6): Tinebase_Server_Json::_handle::193 is JSON request. method: Admin.saveGroup
3b320 0ad82 user - 2013-11-22T11:39:53+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::341 Loading all configs for app Admin
3b320 0ad82 user - 2013-11-22T11:39:53+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::348 Found 0 configs.
3b320 0ad82 user - 2013-11-22T11:39:53+00:00 NOTICE (5): Addressbook_Controller_List::_getDefaultInternalAddressbook::206 Default internal addressbook not found. Creating new config setting.
3b320 0ad82 user - 2013-11-22T11:39:54+00:00 WARN (4): Tinebase_Server_Json::_handleException::264 Tinebase_Exception_NotFound -&gt; Container Internal Contacts not found.
3b320 0ad82 user - 2013-11-22T11:39:54+00:00 WARN (4): Tinebase_Exception::log::103 Tinebase_Exception_NotFound -&gt; Container Internal Contacts not found.
3b320 0ad82 user - 2013-11-22T11:39:54+00:00 NOTICE (5): Tinebase_Exception::log::111 #0 .../Addressbook/Setup/Initialize.php(243): Tinebase_Container-&gt;getContainerByName(&#039;Addressbook&#039;, &#039;Internal Contac...&#039;, &#039;shared&#039;)
#1 .../Addressbook/Controller/List.php(208): Addressbook_Setup_Initialize::setDefaultInternalAddressbook()
#2 .../Addressbook/Controller/List.php(315): Addressbook_Controller_List-&gt;_getDefaultInternalAddressbook()
#3 .../Addressbook/Controller/List.php(296): Addressbook_Controller_List-&gt;createByGroup(Object(Tinebase_Model_Group))
#4 .../Admin/Controller/Group.php(416): Addressbook_Controller_List-&gt;createOrUpdateByGroup(Object(Tinebase_Model_Group))
#5 .../Admin/Controller/Group.php(180): Admin_Controller_Group-&gt;createOrUpdateList(Object(Tinebase_Model_Group))
#6 .../Admin/Frontend/Json.php(651): Admin_Controller_Group-&gt;create(Object(Tinebase_Model_Group))
#7 [internal function]: Admin_Frontend_Json-&gt;saveGroup(Array, Array)
#8 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#9 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#11 .../Tinebase/Server/Json.php(237): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#12 .../Tinebase/Server/Json.php(107): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Core.php(240): Tinebase_Server_Json-&gt;handle()
#14 .../index.php(17): Tinebase_Core::dispatchRequest()
#15 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2013 13:40**

did you rename or remove the &quot;Internal Contacts&quot; addressbook container?

**Comment by Gloirin** [comment]
**Comment posted by martin on 22 Nov 2013 15:24**

hmmm - I can&#039;t remember exactly. I guess I renamed it.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2013 20:08**

ok, I&#039;ll have a look. this should not happen even if it was renamed or deleted.

**Comment by Gloirin** [comment]
**Comment posted by martin on 16 Apr 2014 13:19**

In Collin (2013.10.5) it seams that a group has to be shown in an addressbook. The error only appears if the group is not assigned to an addressbook.
