### ISSUE TITLE
0009400:
Passwords in plaintext in tine log

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4719]
**Reported by pschuele on 12 Dec 2013 14:47**

**Version:** Collin (2013.10.2)

The passwords of the users are written in tine log (exception trace)
should be removed from this.

**Additional information:** ee2f2 -- none -- - 2013-12-12T13:02:48+00:00 NOTICE (5): Addressbook_Backend_Sql::_saveImage::191 Invalid image blob data, preserving old image. Error: exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;given blob does not contain valid image data.&#039; in /opt/local/tine/2013.10.2metaways3/htdocs/Tinebase/ImageHelper.php:61
Stack trace:
#0 /opt/local/tine/2013.10.2metaways3/htdocs/Addressbook/Backend/Sql.php(189): Tinebase_ImageHelper::getImageInfoFromBlob(&#039;1&#039;)
#1 /opt/local/tine/2013.10.2metaways3/htdocs/Addressbook/Backend/Sql.php(144): Addressbook_Backend_Sql-&gt;_saveImage(&#039;6399&#039;, &#039;1&#039;)
#2 /opt/local/tine/2013.10.2metaways3/htdocs/Tinebase/User.php(507): Addressbook_Backend_Sql-&gt;update(Object(Addressbook_Model_Contact))
#3 /opt/local/tine/2013.10.2metaways3/htdocs/Tinebase/Controller.php(133): Tinebase_User::syncUser(&#039;pschuele&#039;, Array)
#4 /opt/local/tine/2013.10.2metaways3/htdocs/Tinebase/Controller.php(91): Tinebase_Controller-&gt;_getLoginUser(&#039;pschuele&#039;, Object(Tinebase_Model_AccessLog))
#5 /opt/local/tine/2013.10.2metaways3/htdocs/ActiveSync/Server/Http.php(151): Tinebase_Controller-&gt;login(&#039;pschuele&#039;, &#039;PASSWORT_IM_KLARTEXT&#039;, &#039;11.11.11.11&#039;, &#039;TineActiveSync&#039;)
#6 /opt/local/tine/2013.10.2metaways3/htdocs/ActiveSync/Server/Http.php(73): ActiveSync_Server_Http-&gt;_authenticate(&#039;pschuele&#039;, &#039;PASSWORT_IM_KLARTEXT&#039;, &#039;11.11.11.11&#039;)

**Comment by Gloirin** [comment]
Related to #4511
