### ISSUE TITLE
0009454:
visibility is not updated when saving user

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4746]
**Reported by pschuele on 26 Dec 2013 21:09**

**Version:** Collin (2013.10.3)

visibility is not updated when saving user

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Dec 2013 21:30**

this only happens if there is an error during the email-user update (because the transaction is rolled back).

66b1d ef300 pschuele 418ms 246ms - 2013-12-26T21:28:19+00:00 ERR (3): Tinebase_EmailUser_Sql::_addUser::297 Error while creating email user: exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;unittest@tine20.org&#039; for key &#039;username&#039;&#039; in /home/pschuele/workspace/tine20/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /home/pschuele/workspace/tine20/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /home/pschuele/workspace/tine20/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /home/pschuele/workspace/tine20/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `sm...&#039;, Array)
#3 /home/pschuele/workspace/tine20/tine20/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `sm...&#039;, Array)
#4 /home/pschuele/workspace/tine20/tine20/Tinebase/EmailUser/Sql.php(287): Zend_Db_Adapter_Abstract-&gt;insert(&#039;smtp_users&#039;, Array)
#5 /home/pschuele/workspace/tine20/tine20/Tinebase/User/Plugin/Abstract.php(57): Tinebase_EmailUser_Sql-&gt;_addUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#6 /home/pschuele/workspace/tine20/tine20/Tinebase/User/Sql.php(709): Tinebase_User_Plugin_Abstract-&gt;inspectUpdateUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#7 /home/pschuele/workspace/tine20/tine20/Tinebase/User/Sql.php(695): Tinebase_User_Sql-&gt;updatePluginUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#8 /home/pschuele/workspace/tine20/tine20/Admin/Controller/User.php(198): Tinebase_User_Sql-&gt;updateUser(Object(Tinebase_Model_FullUser))
#9 /home/pschuele/workspace/tine20/tine20/Admin/Frontend/Json.php(373): Admin_Controller_User-&gt;update(Object(Tinebase_Model_FullUser), &#039;&#039;, &#039;&#039;)
#10 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#11 /home/pschuele/workspace/tine20/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /home/pschuele/workspace/tine20/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /home/pschuele/workspace/tine20/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /home/pschuele/workspace/tine20/tine20/Tinebase/Server/Json.php(238): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 /home/pschuele/workspace/tine20/tine20/Tinebase/Server/Json.php(108): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#16 /home/pschuele/workspace/tine20/tine20/Tinebase/Core.php(251): Tinebase_Server_Json-&gt;handle()
