### ISSUE TITLE
0009484:
SQL Error on 'All highlighted mail': column flags not exists

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4761]
**Reported by kronoc on 6 Jan 2014 12:49**

**Version:** Collin (2013.10.3)

An SQL Error occurs every time clicking &#039;All highlighted mail&#039; in Felamimail using PostgreSQL 9.3.1 as database.

Stacktrace:

1dc48 512e0 auser - 2014-01-06T12:28:41+00:00 DEBUG (7): Tinebase_Server_Json::handle::96 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Felamimail.searchMessages
            [params] =&gt; Array
                (
                    [filter] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [field] =&gt; flags
                                    [operator] =&gt; in
                                    [value] =&gt; \Flagged
                                )

                        )

                    [paging] =&gt; Array
                        (
                            [sort] =&gt; received
                            [dir] =&gt; DESC
                            [start] =&gt; 0
                            [limit] =&gt; 50
                        )

                )

            [id] =&gt; 24
        )

)

1dc48 512e0 auser - 2014-01-06T12:28:41+00:00 INFO (6): Tinebase_Server_Json::_handle::193 is JSON request. method: Felamimail.searchMessages
1dc48 512e0 auser - 2014-01-06T12:28:41+00:00 WARN (4): Tinebase_Server_Json::_handleException::264 Zend_Db_Statement_Exception -&gt; SQLSTATE[42703]: Undefined column: 7 ERROR:  column &quot;flags&quot; does not exist
LINE 3: ... GROUP BY &quot;felamimail_cache_message&quot;.&quot;id&quot; HAVING (flags LIKE...
                                                             ^
1dc48 512e0 auser - 2014-01-06T12:28:41+00:00 WARN (4): Tinebase_Exception::log::103 Zend_Db_Statement_Exception -&gt; SQLSTATE[42703]: Undefined column: 7 ERROR:  column &quot;flags&quot; does not exist
LINE 3: ... GROUP BY &quot;felamimail_cache_message&quot;.&quot;id&quot; HAVING (flags LIKE...
                                                             ^
1dc48 512e0 auser - 2014-01-06T12:28:41+00:00 NOTICE (5): Tinebase_Exception::log::111 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(713): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(507): Tinebase_Backend_Sql_Abstract-&gt;_fetch(Object(Zend_Db_Select))
#5 .../Tinebase/Controller/Record/Abstract.php(192): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Felamimail_Model_MessageFilter), Object(Tinebase_Model_Pagination), false)
#6 .../Tinebase/Frontend/Json/Abstract.php(244): Tinebase_Controller_Record_Abstract-&gt;search(Object(Felamimail_Model_MessageFilter), Object(Tinebase_Model_Pagination), false)
#7 .../Felamimail/Frontend/Json.php(157): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Felamimail_Controller_Message), &#039;Felamimail_Mode...&#039;)
#8 [internal function]: Felamimail_Frontend_Json-&gt;searchMessages(Array, Array)
#9 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 .../Tinebase/Server/Json.php(237): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Server/Json.php(107): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Core.php(240): Tinebase_Server_Json-&gt;handle()
#15 .../index.php(17): Tinebase_Core::dispatchRequest()
#16 {main}

**Steps to reproduce:** click &#039;All highlighted mail&#039; in PostgreSQL environment.

**Additional information:** Generated SQL-Query causing the issue:

SELECT &quot;felamimail_cache_message&quot;.&quot;id&quot;, MIN(&quot;felamimail_cache_message&quot;.&quot;received&quot;) AS &quot;received&quot;, array_to_string(ARRAY(SELECT DISTINCT unnest(array_agg(&quot;felamimail_cache_msg_flag&quot;.&quot;flag&quot;)) ORDER BY 1),&#039;,&#039;) AS &quot;flags&quot; FROM &quot;tine20_felamimail_cache_message&quot; AS &quot;felamimail_cache_message&quot; LEFT JOIN &quot;tine20_felamimail_cache_msg_flag&quot; AS &quot;felamimail_cache_msg_flag&quot; ON &quot;felamimail_cache_message&quot;.&quot;id&quot; = &quot;felamimail_cache_msg_flag&quot;.&quot;message_id&quot; LEFT JOIN &quot;tine20_felamimail_folder&quot; AS &quot;aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0folder&quot; ON &quot;aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0folder&quot;.&quot;id&quot; = felamimail_cache_message.folder_id WHERE (&quot;aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0folder&quot;.&quot;account_id&quot; IN (&#039;8888888888888888888888888888888888888888&#039;)) GROUP BY &quot;felamimail_cache_message&quot;.&quot;id&quot; HAVING ((flags NOT LIKE &#039;%\Seen%&#039;) OR flags IS NULL) ORDER BY &quot;received&quot; DESC LIMIT 50;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Jan 2014 15:10**

(04:08:55 PM) lkneschke: Auch im Having Statement darf kein Alias verwendet werden. 	  				 	 	 	    		  	   		  		
(04:09:14 PM) lkneschke: Das müsste da also auch wie beim Group By ersetzt werden.
