### ISSUE TITLE
0009586:
Cyrus Shared Mailbox disappears in Tine20 Felamimail

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4810]
**Reported by dragon on 24 Jan 2014 18:30**

**Version:** Collin (2013.10.4)

I have a shared public mailbox and it just disappears some seconds after reloading the tine20 website.

Note that I use the 2013.10.2 release.

**Steps to reproduce:** 1. Create a shared cyrus mailbox, my setup is like:
localhost&gt; lam user.yaaf
yaaf lrswipkxtecd
anyone p
localhost&gt; lam user.yaaf.Support
matthid lrswipted
yaaf lrswipkxtecd
glashauser lrswipted
anyone p
localhost&gt; lam user.yaaf.Support.Yaaf
matthid lrswipted
yaaf lrswipkxtecd
anyone p
localhost&gt; lam user.yaaf.Public
matthid lrswipted
yaaf lrswipkxtecd
anyone lr

2. I did setup cyrus to show shared mailboxes within a &quot;Shared&quot; mailbox.
3. Login to time with matthid, =&gt; click on the Shared.yaaf.Support mailbox and wait for it to disappear.

**Additional information:** Important part of the logfile with priority 7:

0ed70 2e129 matthid - 2014-01-24T17:18:08+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::532 Updating capabilities for account: matthid@yaaf.de
0ed70 2e129 matthid - 2014-01-24T17:18:08+00:00 INFO (6): Felamimail_Controller_Cache_Message::_expungeCacheFolder::321 Removing no longer existing folder Shared.yaaf from cache. cannot change folder, maybe it does not exist
0ed70 2e129 matthid - 2014-01-24T17:18:08+00:00 WARN (4): Tinebase_Server_Json::_handleException::264 Felamimail_Exception_IMAPFolderNotFound -&gt; Folder not found: Shared.yaaf
0ed70 2e129 matthid - 2014-01-24T17:18:08+00:00 WARN (4): Tinebase_Exception::log::103 Felamimail_Exception_IMAPFolderNotFound -&gt; Folder not found: Shared.yaaf
0ed70 2e129 matthid - 2014-01-24T17:18:08+00:00 NOTICE (5): Tinebase_Exception::log::111 #0 .../Felamimail/Controller/Cache/Message.php(266): Felamimail_Controller_Cache_Message-&gt;_expungeCacheFolder(Object(Felamimail_Model_Folder), Object(Felamimail_Backend_ImapProxy))
#1 .../Felamimail/Frontend/Json.php(175): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;c7ddf0163be047f...&#039;, 120)
#2 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;c7ddf0163be047f...&#039;, 120)
#3 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#4 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#5 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#6 .../Tinebase/Server/Json.php(237): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#7 .../Tinebase/Server/Json.php(107): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#8 .../Tinebase/Core.php(240): Tinebase_Server_Json-&gt;handle()
#9 .../index.php(17): Tinebase_Core::dispatchRequest()
#10 {main}

I solved the problem for me by writing &quot;return true;&quot; (instead of &quot;return FALSE;&quot;) after
    protected function _doNotUpdateCache(Felamimail_Model_Folder $_folder, $_lockFolder = TRUE)
    {
        if ($_folder-&gt;is_selectable == false) {
in Felamimail/Controller/Cache/Message.php, but I don&#039;t think this is the &quot;right&quot; solution as now i get an error when i click on the &quot;yaaf&quot; folder.

**Comment by Gloirin** [comment]
**Comment posted by dragon on 24 Jan 2014 20:43**

Note on 2013.10.4 I also had to change Felamimail/Controller/Cache/Folder.php to make it work. Something with the selectable flag seems to be wrong.

diff --git a/Felamimail/Controller/Cache/Folder.php b/Felamimail/Controller/Cache/Folder.php
index a7aba05..99aabd0 100644
--- a/Felamimail/Controller/Cache/Folder.php
+++ b/Felamimail/Controller/Cache/Folder.php
@@ -446,7 +446,7 @@ class Felamimail_Controller_Cache_Folder extends Tinebase_Controller_Abstract
     {
         $result = TRUE;

-        if (! $_folderData[&#039;isSelectable&#039;] == &#039;1&#039;) {
+        #if (! $_folderData[&#039;isSelectable&#039;] == &#039;1&#039;) {
             if (Tinebase_Core::isLogLevel(Zend_Log::INFO)) Tinebase_Core::getLogger()-&gt;info(
                 __METHOD__ . &#039;::&#039; . __LINE__ . &#039; Folder &#039; . $_folderData[&#039;globalName&#039;] . &#039; is not selectable.&#039;);

@@ -459,7 +459,7 @@ class Felamimail_Controller_Cache_Folder extends Tinebase_Controller_Abstract
                     __METHOD__ . &#039;::&#039; . __LINE__ . &#039; Could not select folder. Skipping it.&#039;);
                 $result = FALSE;
             }
-        }
+        #}

         return $result;
     }
