### ISSUE TITLE
0009608:
Update von 8.3 auf 8.4 schlägt fehl

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4821]
**Reported by GWI on 29 Jan 2014 14:26**

**Version:** git master

Das Update von 8.3 auf 8.4 wird mit folgendem Fehler
abgebrochen:

This update could be run from cli only!
.../Sales/Setup/Update/Release8.php(137): Setup_Update_Abstract-&gt;promptForUsername()
.../Sales/Setup/Update/Release8.php(337): Sales_Setup_Update_Release8-&gt;_updateContractsFields()
.../Setup/Controller.php(529): Sales_Setup_Update_Release8-&gt;update_3()
.../Setup/Controller.php(428): Setup_Controller-&gt;updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller-&gt;updateApplications()
[internal function]: Setup_Frontend_Json-&gt;updateApplications()
.../library/Zend/Server/Abstract.php(232): call_user_func_array()
.../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Setup/Server/Json.php(77): Zend_Json_Server-&gt;handle()
.../Setup/Core.php(89): Setup_Server_Json-&gt;handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Jan 2014 17:08**

@Sven: this update needs to be run from the command line:

setup.php --update

we&#039;ll discuss this in our next team meeting. it should be possible to update applications via the setup gui, too.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 29 Jan 2014 17:21**

Das ist mir schon klar!
Nur für die ganzen Leute die KEINE Console haben
sollte ein Update IMMER über die GUI machbar sein.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 29 Jan 2014 17:26**

Trotzdem beim Update über die CLI kommt folgende Fehlermeldung:

PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42000]: Syntax error or access violation: 1091 Kann &#039;cleared_in&#039; nicht löschen. Existiert die Spalte oder der Schlüssel?&#039; in ***/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 ***/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 ***/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 ***/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 ***/Setup/Backend/Abstract.php(217): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 ***/Setup/Backend/Abstract.php(322): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 ***/Sales/Setup/Update/Release8.php(230): Setup_Backend_Abstract-&gt;dropCol(&#039;sales_cont in ***/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Jan 2014 17:49**

hmm, das scheint mir ein folgefehler zu sein. hast du schon daten im Sales? vielleicht wäre es einfacher, das eben neu zu installieren ...

zum generellen prob mit dem user prompt: denke es sollte nicht so schwer sein, das auch in die gui einzubauen. dann werden beim update eben noch z.b. über ne combo die verfügbaren user angezeigt und man sucht sich einen aus. damit wird dann das update gestartet. das muss eben schon ganz am anfang passiert, damit man sich nichts zerschiesst.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 29 Jan 2014 18:10**

Das verstehe ich nicht so ganz!

Alle Updates sind bisher immer über den Webzugriff 
gelaufen, warum muss ich jetzt bei Sales das Update
über die Console machen??

Denn Rest mit den &quot;über ne combo die verfügbaren user angezeigt&quot; verstehe ich irgend wie nicht? Ich mach die Updates als ADMIN und nicht als User über sie Setup.php.

Irgendwie hab ich jetzt nen Knoten in Hirn.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Jan 2014 08:57**

@Alex: magst du ihm das erklären?

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 30 Jan 2014 15:01**

Hi,

im Setup loggt man sich als Setup-User ein, es wird kein Tine-Account Initialisiert.

Bei dem aktuellen Update von Sales fallen die Felder &quot;cleared&quot;, &#039;cleared_in&quot;, &quot;status&quot; weg. Damit die Informationen nicht verloren gehen, werden die Werte der Felder an die Beschreibung angehängt. 

Dieser Vorgang soll in der Historie verfolgbar sein, die Felder (Label + Wert) sollen übersetzt werden.

Die Historie wird im Controller geschrieben, dazu braucht man den Tine-Benutzer-Account. Die Übersetzung läuft mit der Standard-Sprache des Benutzers.

Dafür braucht man hier den Account. Dass die Exception nicht abgefangen wurde liegt daran, dass wir noch keine Zeit hatten, das zu implementieren, spätestens zum Release kann man über die GUI den Benutzer setzen.

Ich hoffe, deinen Knoten lösen zu können ;)

Alex

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Feb 2014 14:48**

die exception wird nun gefangen und das update via gui sollte wieder funktionieren.
