### ISSUE TITLE
0009676:
allow self signed certificates for imap tls

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4854]
**Reported by pschuele on 14 Feb 2014 10:11**

**Version:** Collin (2013.10.5)

allow self signed certificates for imap tls

**Additional information:** ticket has been renamed as certificate check is now enabled by default (see https://forge.tine20.org/view.php?id=9676#c17378)

**Comment by Gloirin** [comment]
Related to #5733

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 1 Feb 2016 23:26**

Up to Ubuntu 14.10 all was working well with self-signed certificates. Since the update yesterday to ubuntu 15.04, self-signed certificates do not work any more with Felamimail. Assume there was an update to PEAR/Mail-Imap???

error messages with TLS on port 143:

c7a66 10046 someuser - 2016-02-01T23:10:49+00:00 WARN (4): Tinebase_Core::errorHandler::517 stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /var/wwwroot/tine20/Felamimail/Protocol/Imap.php::148 (2)
c7a66 10046 someuser - 2016-02-01T23:10:49+00:00 WARN (4): Tinebase_Core::errorHandler::518 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;stream_socket_e...&#039;, &#039;/var/wwwroot/ti...&#039;, 148, Array)
#1 /var/wwwroot/tine20/Felamimail/Protocol/Imap.php(148): stream_socket_enable_crypto(Resource id #17, true, 57)
#2 /var/wwwroot/tine20/Felamimail/Backend/Imap.php(97): Felamimail_Protocol_Imap-&gt;connect(&#039;ratsdorf.dyndns...&#039;, &#039;143&#039;, &#039;TLS&#039;)
#3 /var/wwwroot/tine20/Felamimail/Backend/Imap.php(75): Felamimail_Backend_Imap-&gt;connectAndLogin(Object(stdClass))
#4 /var/wwwroot/tine20/Felamimail/Backend/ImapProxy.php(66): Felamimail_Backend_Imap-&gt;__construct(Object(stdClass))
#5 /var/wwwroot/tine20/Felamimail/Backend/ImapFactory.php(48): Felamimail_Backend_ImapProxy-&gt;__construct(Array)
#6 /var/wwwroot/tine20/Felamimail/Controller/Cache/Message.php(263): Felamimail_Backend_ImapFactory::factory(&#039;cad32e9cac90dab...&#039;)
#7 /var/wwwroot/tine20/Felamimail/Frontend/Json.php(178): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;f99545b21aa2025...&#039;, 10)
#8 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;f99545b21aa2025...&#039;, 10)
#9 /var/wwwroot/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /var/wwwroot/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /var/wwwroot/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /var/wwwroot/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /var/wwwroot/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /var/wwwroot/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /var/wwwroot/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
c7a66 10046 someuser - 2016-02-01T23:10:49+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Felamimail_Exception_IMAPServiceUnavailable -&gt; cannot enable TLS
c7a66 10046 someuser - 2016-02-01T23:10:49+00:00 ERR (3): Tinebase_Exception::log::104 Felamimail_Exception_IMAPServiceUnavailable -&gt; cannot enable TLS

With SSL enabled on port 993, I do not get too many errors:
236e0 17e4c someuser - 2016-02-01T23:21:07+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Felamimail_Exception_IMAPServiceUnavailable -&gt; cannot connect to host : 0 :
236e0 17e4c someuser - 2016-02-01T23:21:07+00:00 ERR (3): Tinebase_Exception::log::104 Felamimail_Exception_IMAPServiceUnavailable -&gt; cannot connect to host : 0 :

So should we actually allow to bypass certificate checks with imap connect flags, ie
http://php.net/manual/en/function.imap-open.php : /novalidate-cert

Cheers,
Ingo

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 4 Feb 2016 00:18**

Note: PHP 5.6 introduces SSL certificate verification
http://php.net/manual/en/migration56.openssl.php

Since 5.6, SSL verification became default. Means that it does not work with self-signed certificates any more.

Solution would be to change
/Felamimail/Protocol/Imap.php line 129 from

$this-&gt;_socket = @fsockopen($host, $port, $errno, $errstr, self::TIMEOUT_CONNECTION);

to

$this-&gt;_socket = stream_socket_client($host.&#039;:&#039;.$port, $errno, $errstr, self::TIMEOUT_CONNECTION, STREAM_CLIENT_CONNECT, stream_context_create(
                array(
                        &#039;ssl&#039; =&gt; array(
                        &#039;verify_peer&#039; =&gt; false,
                        &#039;verify_peer_name&#039; =&gt; false,
                        &#039;allow_self_signed&#039; =&gt; true
                        )
                )
        ));

This would restore the default pre 5.6 behaviour. So we could now make this a user configuration.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Feb 2016 08:20**

hi Ingo,
thanks for mentioning. i think we should solve this for the upcoming 2016.03 Egon release.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 8 Feb 2016 09:24**

BTW, my little patch above works magic for SSL but not for TLS connections. It loses connection somewhere down the track. Just saying...

**Comment by Gloirin** [comment]
**Comment posted by daymien on 18 Aug 2016 19:54**

Same issue on my setup. Thx

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Aug 2016 12:27**

@Ingo: please check if this helps for your setup -&gt; https://gerrit.tine20.org/tine20/3384
