### ISSUE TITLE
0009694:
Cannot delete calender

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4863]
**Reported by frlan on 21 Feb 2014 18:35**

**Version:** Collin (2013.10.5)

I&#039;ve got issues to delete a calender on commen calender section. It&#039;s just popping up a message, that there might a missconfiguration or server under load. Inside logfile I saw this: 

d8ed6 7266c -- none -- - 2014-02-21T18:31:54+00:00 WARN (4): Tinebase_Core::setupStreamWrapper::756 Filesdir config value not set. tine20:// streamwrapper not registered, virtual filesystem not available.
df586 a7f98 -- none -- - 2014-02-21T18:31:59+00:00 WARN (4): Tinebase_Core::setupStreamWrapper::756 Filesdir config value not set. tine20:// streamwrapper not registered, virtual filesystem not available.
df586 a7f98 frank@lanitz.info - 2014-02-21T18:31:59+00:00 ERR (3): Tinebase_Controller_Record_Abstract::delete::1256 No base path (filesdir) configured or path not writeable
df586 a7f98 frank@lanitz.info - 2014-02-21T18:31:59+00:00 WARN (4): Tinebase_Server_Json::_handleException::264 Tinebase_Exception_Backend -&gt; No base path (filesdir) configured or path not writeable
df586 a7f98 frank@lanitz.info - 2014-02-21T18:31:59+00:00 WARN (4): Tinebase_Exception::log::103 Tinebase_Exception_Backend -&gt; No base path (filesdir) configured or path not writeable
df586 a7f98 frank@lanitz.info - 2014-02-21T18:31:59+00:00 NOTICE (5): Tinebase_Exception::log::119 #0 .../Tinebase/FileSystem.php(83): Tinebase_FileSystem-&gt;__construct()
#1 .../Tinebase/FileSystem/RecordAttachments.php(40): Tinebase_FileSystem::getInstance()
#2 .../Tinebase/FileSystem/RecordAttachments.php(51): Tinebase_FileSystem_RecordAttachments-&gt;__construct()
#3 .../Tinebase/Controller/Record/Abstract.php(1411): Tinebase_FileSystem_RecordAttachments::getInstance()
#4 .../Tinebase/Controller/Record/Abstract.php(1364): Tinebase_Controller_Record_Abstract-&gt;_deleteLinkedObjects(Object(Calendar_Model_Event))
#5 .../Tinebase/Controller/Record/Abstract.php(1242): Tinebase_Controller_Record_Abstract-&gt;_deleteRecord(Object(Calendar_Model_Event))
#6 .../Calendar/Controller/Event.php(719): Tinebase_Controller_Record_Abstract-&gt;delete(Object(Calendar_Model_Event))
#7 .../Tinebase/Controller/Record/Abstract.php(1281): Calendar_Controller_Event-&gt;delete(Array)
#8 .../Tinebase/Container.php(931): Tinebase_Controller_Record_Abstract-&gt;deleteByFilter(Object(Calendar_Model_EventFilter))
#9 .../Tinebase/Container.php(872): Tinebase_Container-&gt;deleteContainerContents(Object(Tinebase_Model_Container))
#10 .../Tinebase/Frontend/Json/Container.php(118): Tinebase_Container-&gt;deleteContainer(22)
#11 [internal function]: Tinebase_Frontend_Json_Container-&gt;deleteContainer(22)
#12 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 .../Tinebase/Server/Json.php(237): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 .../Tinebase/Server/Json.php(108): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#17 .../Tinebase/Core.php(251): Tinebase_Server_Json-&gt;handle()
#18 .../index.php(19): Tinebase_Core::dispatchRequest()
#19 {main}

**Comment by Gloirin** [comment]
**Comment posted by frlan on 24 Feb 2014 08:37**

This also happens on trying to delete an task list entry. 

I&#039;m running tine on postgrSQL and did also check thee server logs. There seems to be nothing critical.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Feb 2014 16:37**

thanks for the bugreport. this should be easy to fix.

if you need a workaround: please add a filesdir in the setup.php gui. this is required if you like to add attachments to records or use the Filemanager.
