### ISSUE TITLE
0009796:
owncloud sync doesn't work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4904]
**Reported by exma on 24 Mar 2014 08:37**

**Version:** Collin (2013.10.5)

using filemanger with the owncloud client i got the error &quot;Problem: Could not read response body: connection was closed by server&quot;

i see in the /var/log/apache2/error.log
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;child: 21 not found!&#039; in /usr/share/tine20/Tinebase/Tree/Node.php:125\nStack trace:\n#0 /usr/share/tine20/Tinebase/FileSystem.php(749): Tinebase_Tree_Node-&gt;getChild(Object(Tinebase_Model_Tree_Node), &#039;21&#039;)\n#1 /usr/share/tine20/Tinebase/Frontend/WebDAV/Container.php(210): Tinebase_FileSystem-&gt;stat(&#039;/6ac5fff190fefb...&#039;)\n#2 /usr/share/tine20/Tinebase/WebDav/Collection/Abstract.php(272): Tinebase_Frontend_WebDAV_Container-&gt;getETag()\n#3 /usr/share/tine20/Tinebase/WebDav/Collection/Abstract.php(272): Tinebase_WebDav_Collection_Abstract-&gt;getETag()\n#4 /usr/share/tine20/Tinebase/WebDav/Collection/Abstract.php(272): Tinebase_WebDav_Collection_Abstract-&gt;getETag()\n#5 /usr/share/tine20/Tinebase/WebDav/Collection/Abstract.php(405): Tinebase_WebDav_Collection_Abstract-&gt;getETag()\n#6 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1524): Tinebase_WebDav_Collection_Abstract-&gt;getProperties(Array)\n#7 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.ph in /usr/share/tine20/Tinebase/Tree/Node.php on line 125

it seems, that the owncloud client is looking for a version of the file, which dosen&#039;t exists anymore.
i&#039;m using the owncloud client on 2 machines.

**Comment by Gloirin** [comment]
**Comment posted by exma on 26 Mar 2014 13:26**

i have marked the entry with the id 21 in tine20_container as deleted.

**Comment by Gloirin** [comment]
**Comment posted by prego on 26 Mar 2014 17:39**

possible duplicate of https://forge.tine20.org/mantisbt/view.php?id=9208  ??

**Comment by Gloirin** [comment]
**Comment posted by prego on 15 Jun 2014 12:59**

the problem is fixed with the last official owncloud-client

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 7 Jul 2014 19:17**

Hi prego,

thanks for this news, can somebody else confirm this?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Jan 2017 08:14**

should already been fixed a while ago.
