### ISSUE TITLE
0009964:
Multiple problems with VTIMEZONE in CalDAV

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#4982]
**Reported by pij on 4 Jun 2014 19:25**

**Version:** Collin (2013.10.7)

Vorgeschichte: Ich nutze tine20 auf einem Debian Testing mit php5 5.5.12+dfsg-2
Seit ungefähr Anfang April liefert DateTimeZone:getTransitions für CET false zurück anstatt einen Array. Das ergibt im Log:
e4754 admin - 2014-05-19T18:17:17+00:00 WARN (4): Tinebase_Core::errorHandler::494 array_shift() expects parameter 1 to be array, boolean given in /usr/share/tine20
/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php::127 (2)
e4754 admin - 2014-05-19T18:17:17+00:00 WARN (4): Tinebase_Core::errorHandler::495 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;array_shift() e...&#039;, &#039;/us
r/share/tine...&#039;, 127, Array)
#1 /usr/share/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php(127): array_shift(false)
#2 /usr/share/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/VTimeZone.php(67): TimeZoneConvert_Transition::getTransitions(Object(DateTimeZone), Object(
DateTime), NULL)
#3 /usr/share/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert.php(69): TimeZoneConvert_VTimeZone-&gt;getVTimezone(&#039;CET&#039;, NULL, NULL)
#4 /usr/share/tine20/library/Sabre/VObject/Component/VTimezone.php(56): TimeZoneConvert::toVTimeZone(Object(DateTimeZone))
#5 /usr/share/tine20/vendor/sabre/vobject/lib/Sabre/VObject/Component.php(284): Sabre_VObject_Component_VTimezone-&gt;serialize()
#6 /usr/share/tine20/Calendar/Frontend/WebDAV/Event.php(504): Sabre\VObject\Component-&gt;serialize()
#7 /usr/share/tine20/Calendar/Frontend/WebDAV/Event.php(332): Calendar_Frontend_WebDAV_Event-&gt;_getVEvent()
#8 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1553): Calendar_Frontend_WebDAV_Event-&gt;getSize()
#9 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1368): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;calendars/9a84a...&#039;, Array, 0)
#10 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1421): Sabre\DAV\Server-&gt;getProperties(&#039;calendars/9a84a...&#039;, Array)
#11 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(544): Sabre\DAV\Server-&gt;getHTTPHeaders(&#039;calendars/9a84a...&#039;)
#12 [internal function]: Sabre\DAV\Server-&gt;httpGet(&#039;calendars/9a84a...&#039;)
#13 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;calendars/9a84a...&#039;)
#14 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;GET&#039;, &#039;calendars/9a84a...&#039;)
#15 /usr/share/tine20/Tinebase/Server/WebDAV.php(119): Sabre\DAV\Server-&gt;exec()
#16 /usr/share/tine20/Tinebase/Core.php(251): Tinebase_Server_WebDAV-&gt;handle()
#17 /usr/share/tine20/index.php(19): Tinebase_Core::dispatchRequest()
#18 {main}
e4754 admin - 2014-05-19T18:17:17+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::122 &gt;&gt;&gt; *DAV response:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//tine20.com//Tine 2.0 Calendar V8.2//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:CET
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20140409T181720Z
...

Gemäss RFC5545 muss VTIMEZONE aber mindestens einen standardc oder daylightc enthalten, so dass z.B. python-caldav einen Fehler wirft. Thunderbird/Lightning ist zum Glück toleranter.

Das betrifft nur CET, Ids wie posix/CET, Europe/Berlin funktionieren, man kann das mit einem kleinen PHP-Skript überprüfen

&lt;?php
$tzid = &quot;CET&quot;;
$timezone = new DateTimeZone($tzid);
$transitions = $timezone-&gt;getTransitions(date_create(&#039;now&#039;, new DateTimeZone(&#039;UTC&#039;))-&gt;getTimestamp());
print &quot;transitions is array: &quot;.(is_array($transitions)?&quot;ok&quot;:&quot;nok&quot;).&quot; \n&quot;
?&gt;

Leider normalisiert python-caldav alle funktionierenden TZIDs auf CET, so dass ich mit python kein Events mehr in Tine reinkriege die ich wieder auslesen könnte.

Jetzt zu den Problemen:
- Irgendwie müsste eine bessere Fehlerbehandlung erfolgen. Leider habe ich keine brauchbare Idee, ausser z.B. die Zeit in UTC umzuwandeln.
- UTC geht derzeit auch nicht, weil Tine für UTC unnötigerweise eine VTIMEZONE erstellt, die natürlich mangels Rules auch illegal ist
2bcd8 admin - 2014-05-25T21:42:57+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::122 &gt;&gt;&gt; *DAV response:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//tine20.com//Tine 2.0 Calendar V8.2//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:UTC
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20140525T214212Z

Vermutlich sollte man verhindern, dass UTC in die VTIMEZONE hineinkommt.

**Steps to reproduce:** 1. CET-Probleme: Man braucht eine PHP-Installation, die für CET keine Transitions zurückliefert, dann ein Event mit Zeitzone CET erzeugen und mit einem generischen Client auslesen z.B. mit python

import caldav
calurl=...
client = caldav.DAVClient(calurl)
principal = caldav.Principal(client, calurl)
calendars = principal.calendars()
if len(calendars) &gt; 0:
  calendar = calendars[0]
  for event in calendar.events():
    event.load()

Den Fehler sollte man wie oben im Log sehen.

UTC-Problem: ein Event mit Zeitzone UTC erzeugen (z.B. auch mit python-caldav) und wieder auslesen. Auf Tine-Seite gibt es zwar keinen Fehler, aber man sollte die illegale VTIMEZONE sehen.

**Comment by Gloirin** [comment]
**Comment posted by pij on 9 Jun 2014 15:42**

Folgender Patch behebt das Problem mit der illegalen VTIMEZONE für UTC

--- /usr/share/tine20/Calendar/Convert/Event/VCalendar/Abstract.php.bak	2014-05-23 12:50:41.000000000 +0200
+++ /usr/share/tine20/Calendar/Convert/Event/VCalendar/Abstract.php	2014-06-09 17:31:59.000000000 +0200
@@ -79,8 +79,10 @@
             throw new Tinebase_Exception_Record_Validation(&#039;originator_tz needed for conversion to Sabre\VObject\Component&#039;);
         }
         
-        $vcalendar-&gt;add(new Sabre_VObject_Component_VTimezone($originatorTz));
-        
+        if (strcasecmp($originatorTz,&#039;UTC&#039;)!=0) {
+          $vcalendar-&gt;add(new Sabre_VObject_Component_VTimezone($originatorTz));
+        }
+       
         foreach ($_records as $_record) {
             $this-&gt;_convertCalendarModelEvent($vcalendar, $_record);
 
Der strcasecmp ist vielleicht Overkill, vielleicht reicht ein !=&quot;UTC&quot; aus, ich wollte aber auf Nummer sicher gehen.

Ich vermute, bei Calendar - ExportICS taucht die Kalamität auch auf.
