### ISSUE TITLE
Fatal error on update from 2018.02.2 -> 2018.02.3

### ISSUE THREAD

**Issue by tvannahl** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#51]
I just tried to update a tine20 instance from 2018.02.2 to 2018.02.3 which crashed with the following output:

```shell
[root@gloin tine20]# sudo -u apache php setup.php --update
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'state' in 'field list' in /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `tine20_...', Array)
#4 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `tine20_...', Array)
#5 /opt/tine/2018.02.3/tine20/Tinebase in /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'state' in 'field list' in /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `tine20_...', Array)
#4 /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `tine20_...', Array)
#5 /opt/tine/2018.02.3/tine20/Tinebase in /opt/tine/2018.02.3/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
```

Previously I ran a `composer install --prefer-source --no-interaction` on the 2018.02.3 tag nothing more.

**Comment by pschuele** [comment]
i can reproduce the problem.

just run the update (for example with CLI command "php setup.php --update") again and it should work.

**Comment by pschuele** [comment]
here is the full stacktrace:

```
b3424 setupuser - 2018-05-03T13:57:12+00:00 ERR (3): Setup_Controller::updateApplication::599 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'state' in 'field list', query was: UPDATE `master_applications` SET `name` = ?, `version` = ?, `status` = ?, `order` = ?, `state` = ?, `id` = ? WHERE (`id` = '72f8a5338b9bdf85ae3c2e4809b57b9f945a6dcd')
b3424 setupuser - 2018-05-03T13:57:12+00:00 ERR (3): Setup_Controller::updateApplication::600 #0 /tine/tine20/vendor_2017.11-develop/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /tine/tine20/vendor_2017.11-develop/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /tine/tine20/vendor_2017.11-develop/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `master_...', Array)
#3 /tine/tine20/vendor_2017.11-develop/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `master_...', Array)
#4 /tine/tine20/Tinebase/Backend/Sql/Abstract.php(1313): Zend_Db_Adapter_Abstract->update('master_applicat...', Array, '(`id` = '72f8a5...')
#5 /tine/tine20/Tinebase/Application.php(556): Tinebase_Backend_Sql_Abstract->update(Object(Tinebase_Model_Application))
#6 /tine/tine20/Setup/Update/Abstract.php(98): Tinebase_Application->updateApplication(Object(Tinebase_Model_Application))
#7 /tine/tine20/Tinebase/Setup/Update/Release11.php(502): Setup_Update_Abstract->setApplicationVersion('Tinebase', '11.24')
#8 /tine/tine20/Setup/Controller.php(593): Tinebase_Setup_Update_Release11->update_23()
#9 /tine/tine20/Setup/Controller.php(476): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
#10 /tine/tine20/Setup/Frontend/Cli.php(509): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
#11 /tine/tine20/Setup/Frontend/Cli.php(465): Setup_Frontend_Cli->_updateApplications()
#12 /tine/tine20/Setup/Frontend/Cli.php(71): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#13 /tine/tine20/Setup/Server/Cli.php(127): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#14 /tine/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#15 /tine/tine20/setup.php(14): Setup_Core::dispatchRequest()
#16 {main}
```

**Comment by pschuele** [comment]
problem is, that the state column still exists in the table schema cache and the cache is not invalidated correctly.

@paulmhh could you have a look
