### ISSUE TITLE
0010363:
Nach update kein Login beim Webaccess

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5167]
**Reported by koelschejung on 16 Oct 2014 19:04**

**Version:** Koriander (2014.09.2)

Hallo,

ich habe heute das Update eingerichtet und im setup die Anwendungen aktualisiert. Seitdem kann ich mich im Browser nicht mehr anmelden.

Ich habe tine aus den Repository Ubuntu 14.04 installiert.

Wenn ich mich einloggen möchte kommt folgende Meldung im Browser:

&quot;Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.&quot;

Über Thunderbird habe ich folgende Mail bekommen:

Tine 2.0 can&#039;t setup the configured logger! The Server responded: exception &#039;Zend_Db_Adapter_Exception&#039; with message &#039;SQLSTATE[HY000] [2002] Can&#039;t connect to local MySQL server through socket &#039;/var/run/mysqld/mysqld.sock&#039; (2)&#039; in /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php:144
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract-&gt;_connect()
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(832): Zend_Db_Adapter_Pdo_Mysql-&gt;_connect()
#2 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(902): Zend_Db_Adapter_Abstract-&gt;quote(&#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;)
#3 /usr/share/tine20/Tinebase/Backend/Sql/Filter/GroupSelect.php(103): Zend_Db_Adapter_Abstract-&gt;quoteInto(&#039;`config`.`appli...&#039;, &#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;)
#4 /usr/share/tine20/Tinebase/Backend/Sql/Filter/GroupSelect.php(71): Tinebase_Backend_Sql_Filter_GroupSelect-&gt;_where(&#039;`config`.`appli...&#039;, &#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;, true)
#5 /usr/share/tine20/Tinebase/Model/Filter/Id.php(76): Tinebase_Backend_Sql_Filter_GroupSelect-&gt;where(&#039;`config`.`appli...&#039;, &#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;)
#6 /usr/share/tine20/Tinebase/Backend/Sql/Filter/FilterGroup.php(46): Tinebase_Model_Filter_Id-&gt;appendFilterSql(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Tinebase_Backend_Sql))
#7 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(546): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Zend_Db_Select), Object(Tinebase_Model_ConfigFilter), Object(Tinebase_Backend_Sql))
#8 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(500): Tinebase_Backend_Sql_Abstract-&gt;_addFilter(Object(Zend_Db_Select), Object(Tinebase_Model_ConfigFilter))
#9 /usr/share/tine20/Tinebase/Config/Abstract.php(346): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Tinebase_Model_ConfigFilter))
#10 /usr/share/tine20/Tinebase/Config/Abstract.php(302): Tinebase_Config_Abstract-&gt;_loadAllAppConfigsInCache()
#11 /usr/share/tine20/Tinebase/Config/Abstract.php(154): Tinebase_Config_Abstract-&gt;_loadConfig(&#039;Tinebase_Authen...&#039;)
#12 /usr/share/tine20/Tinebase/Config/Abstract.php(253): Tinebase_Config_Abstract-&gt;get(&#039;Tinebase_Authen...&#039;, &#039;###NOTSET###&#039;)
#13 /usr/share/tine20/Tinebase/Log/Formatter.php(157): Tinebase_Config_Abstract-&gt;__isset(&#039;Tinebase_Authen...&#039;)
#14 /usr/share/tine20/Tinebase/Log.php(41): Tinebase_Log_Formatter-&gt;setReplacements()
#15 /usr/share/tine20/Tinebase/Core.php(585): Tinebase_Log-&gt;addWriterByConfig(Object(Tinebase_Config_Struct))
#16 /usr/share/tine20/Tinebase/Core.php(1471): Tinebase_Core::setupLogger()
#17 /usr/share/tine20/Tinebase/Core.php(655): Tinebase_Core::getLogger()
#18 /usr/share/tine20/Tinebase/Core.php(427): Tinebase_Core::setupCache()
#19 /usr/share/tine20/Tinebase/Server/Cli.php(83): Tinebase_Core::initFramework()
#20 /usr/share/tine20/Tinebase/Core.php(257): Tinebase_Server_Cli-&gt;handle()
#21 /usr/share/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#22 {main}
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Adapter_Exception&#039; with message &#039;SQLSTATE[HY000] [2002] Can&#039;t connect to local MySQL server through socket &#039;/var/run/mysqld/mysqld.sock&#039; (2)&#039; in /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php:144
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract-&gt;_connect()
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(832): Zend_Db_Adapter_Pdo_Mysql-&gt;_connect()
#2 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(902): Zend_Db_Adapter_Abstract-&gt;quote(&#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;)
#3 /usr/share/tine20/Tinebase/Backend/Sql/Filter/GroupSelect.php(103): Zend_Db_Adapter_Abstract-&gt;quoteInto(&#039;`config`.`appli...&#039;, &#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;)
#4 /usr/share/tine20/Tinebase/Backend/Sql/Filter/GroupSelect.php(71): Tinebase_Backend_Sql_Filter_GroupSelect-&gt;_where(&#039;`config`.`appli...&#039;, &#039;f4b4cea98b934fa...&#039;, &#039;varchar&#039;, true)
#5 /usr/share/tine20/Tinebase/Model/Filter/Id.php(76): Tinebase_Backend_Sql_Filter_GroupSelect-&gt;wh in /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php on line 144&quot;

Was kann ich tun?

Viele grüße
Uli

**Comment by Gloirin** [comment]
**Comment posted by koelschejung on 16 Oct 2014 19:11**

Im Apache Log steht folgendes:
PHP Fatal error:  Call to undefined function convertCacheId() in /usr/share/tine20/SimpleFAQ/Controller.php

**Comment by Gloirin** [comment]
**Comment posted by koelschejung on 16 Oct 2014 19:37**

Habe den Debug-Level auf 7 gestellt. Das tine log findet Ihr anbei.

ich hoffe, Ihr könnt mir helfen.

Viele grüße
Uli

**Comment by Gloirin** [comment]
**Comment posted by koelschejung on 16 Oct 2014 19:55**

Wieder eine Info. Nachdem ich im setup das SimpleFAQ deinstalliert habe, konnte ich mich einloggen.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 16 Oct 2014 20:12**

Du hast wohl noch eine alte Version von SimpleFAQ installiert gehabt.

Kann das sein?

**Comment by Gloirin** [comment]
**Comment posted by koelschejung on 16 Oct 2014 20:25**

Hi,

dann fehlt das aber in den Repositories. Habe heute einfach ein apt-get update &amp;&amp; apt-get upgrade durchgeführt.

Könntest Du bitte mal schauen, ob es komplett ist?

Viele Grüße
Uli
