### ISSUE TITLE
0010367:
error in tine20.log after update to 2014.09.2

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5169]
**Reported by exma on 17 Oct 2014 12:33**

**Version:** Koriander (2014.09.2)

e5435 54dd2 -- none -- - 2014-10-17T12:01:45+00:00 WARN (4): Tinebase_Core::errorHandler::530 realpath(): open_basedir restriction in effect. File(/usr/share) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/us
r/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/Tinebase/Helper.php::87 (2)
e5435 54dd2 -- none -- - 2014-10-17T12:01:45+00:00 WARN (4): Tinebase_Core::errorHandler::531 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;realpath(): ope...&#039;, &#039;/usr/share/tine...&#039;, 87, Array)
#1 /usr/share/tine20/Tinebase/Helper.php(87): realpath(&#039;/usr/share&#039;)
#2 /usr/share/tine20/Tinebase/Core.php(488): Tinebase_Helper::getDevelopmentRevision()
#3 /usr/share/tine20/Tinebase/Core.php(424): Tinebase_Core::setupBuildConstants()
#4 /usr/share/tine20/Tinebase/Server/Json.php(65): Tinebase_Core::initFramework()
#5 /usr/share/tine20/Tinebase/Core.php(252): Tinebase_Server_Json-&gt;handle()
#6 /usr/share/tine20/index.php(19): Tinebase_Core::dispatchRequest()
#7 {main}
06fb5 -- none -- - 2014-10-17T12:01:46+00:00 WARN (4): Tinebase_Core::errorHandler::530 realpath(): open_basedir restriction in effect. File(/usr/share) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/shar
e/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/Tinebase/Helper.php::87 (2)
06fb5 -- none -- - 2014-10-17T12:01:46+00:00 WARN (4): Tinebase_Core::errorHandler::531 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;realpath(): ope...&#039;, &#039;/usr/share/tine...&#039;, 87, Array)
#1 /usr/share/tine20/Tinebase/Helper.php(87): realpath(&#039;/usr/share&#039;)
#2 /usr/share/tine20/Tinebase/Core.php(488): Tinebase_Helper::getDevelopmentRevision()
#3 /usr/share/tine20/Tinebase/Core.php(424): Tinebase_Core::setupBuildConstants()
#4 /usr/share/tine20/Tinebase/Server/WebDAV.php(45): Tinebase_Core::initFramework()
#5 /usr/share/tine20/Tinebase/Core.php(252): Tinebase_Server_WebDAV-&gt;handle()
#6 /usr/share/tine20/index.php(19): Tinebase_Core::dispatchRequest()
#7 {main}

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 17 Oct 2014 12:43**

You probably would like to add /usr/share to your allowed paths in your php.ini

**Comment by Gloirin** [comment]
**Comment posted by weberho on 17 Oct 2014 12:47**

Or better /usr/share/tine20

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Oct 2014 15:47**

this problem occurred in our build scripts, they are already fixed.

I&#039;ll attach a patched version (of Tinebase/Core.php) with the correct TINE20_CODENAME to this ticket.

sorry for the inconvenience.
