### ISSUE TITLE
0010385:
Error during scheduled ical import

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5176]
**Reported by Canny on 20 Oct 2014 17:39**

**Version:** Koriander (2014.09.2)

Oct 20 19:35:01 pilu Tine 2.0[7305]: Tinebase_Core::errorHandler::530 mb_detect_encoding() expects parameter 1 to be string, array given in /usr/share/tine20/Tinebase/Helper.php::179 (2)
Oct 20 19:35:01 pilu Tine 2.0[7305]: Tinebase_Core::errorHandler::531 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;mb_detect_encod...&#039;, &#039;/usr/share/tine...&#039;, 179, Array)#012#1 /usr/share/tine20/Tinebase/Helper.php(179): 
mb_detect_encoding(Array, Array)#012#2 /usr/share/tine20/Tinebase/Core.php(1514): Tinebase_Helper::mbConvertTo(Array)#012#3 /usr/share/tine20/Tinebase/Convert/VCalendar/Abstract.php(61): Tinebase_Core::filterInputForDatabase(Array)
#012#4 /usr/share/tine20/Calendar/Convert/Event/VCalendar/Abstract.php(520): Tinebase_Convert_VCalendar_Abstract::getVObject(Array)#012#5 /usr/share/tine20/Calendar/Import/Ical.php(115): Calendar_Convert_Event_VCalendar_Abstract-&gt;t
oTine20RecordSet(Array)#012#6 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(191): Calendar_Import_Ical-&gt;import(Array)#012#7 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(67): Tinebase_Controller_ScheduledImport-&gt;_doScheduledImport(Object(Tinebase_Model_Import))#012#8 [internal function]: Tinebase_Controller_ScheduledImport-&gt;runNextScheduledImport()#012#9 /usr/share/tine20/Tinebase/Scheduler/Task.php(283): call_user_func_array(Array, Array)#012#10 /usr/share/tine20/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()#012#11 /usr/share/tine20/Tinebase/Frontend/Cli.php(121): Zend_Scheduler-&gt;run()#012#12 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))#012#13 /usr/share/tine20/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))#012#14 /usr/share/tine20/Tinebase/Server/Cli.php(94): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))#012#15 /usr/share/tine20/Tinebase/Core.php(252): Tinebase_Server_Cli-&gt;handle()#012#16 /usr/share/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()#012#17 {main}
Oct 20 19:35:01 pilu Tine 2.0[7305]: Tinebase_Exception::log::104 Sabre\VObject\EofException -&gt; End of document reached prematurely
Oct 20 19:35:01 pilu Tine 2.0 scheduler: 
Oct 20 19:35:01 pilu Tine 2.0 scheduler: Fatal error: Uncaught exception &#039;Calendar_Exception_IcalParser&#039; with message &#039;can not parse ical file =&gt; syntax errors ?&#039; in /usr/share/tine20/Calendar/Import/Ical.php:118
Oct 20 19:35:01 pilu Tine 2.0 scheduler: Stack trace:
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #0 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(191): Calendar_Import_Ical-&gt;import(Array)
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #1 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(67): Tinebase_Controller_ScheduledImport-&gt;_doScheduledImport(Object(Tinebase_Model_Import))
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #2 [internal function]: Tinebase_Controller_ScheduledImport-&gt;runNextScheduledImport()
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #3 /usr/share/tine20/Tinebase/Scheduler/Task.php(283): call_user_func_array(Array, Array)
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #4 /usr/share/tine20/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #5 /usr/share/tine20/Tinebase/Frontend/Cli.php(121): Zend_Scheduler-&gt;run()
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #6 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #7 /usr/share/tine20/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
Oct 20 19:35:01 pilu Tine 2.0 scheduler: #8 /usr/share/tine20/Tinebase/Server/Cli.php(94): Tinebase_Frontend_Cl in /usr/share/tine20/Calendar/Import/Ical.php on line 118

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 5 Feb 2015 18:49**

How does the ical file look alike?

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 9 Feb 2015 14:10**

Warten auf Feedback, habe Reporter per E-Mail kontaktiert.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 18 Feb 2015 11:34**

Closed. No response from reporter.
