### ISSUE TITLE
0010441:
redis read error during update

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5203]
**Reported by pschuele on 7 Nov 2014 21:45**

**Version:** Koriander (2014.09.2)

redis read error during update

maybe we should catch this error

**Additional information:** root@server:~/pschuele/scripts# /usr/bin/php -d include_path=/usr/share/tine20:/etc/tine20 -d memory_limit=512M /usr/share/tine20/setup.php --update
PHP Fatal error:  Uncaught exception &#039;RedisException&#039; with message &#039;read error on connection&#039; in /usr/share/tine20/Zend/Cache/Backend/Redis.php:250
Stack trace:
#0 /usr/share/tine20/Zend/Cache/Backend/Redis.php(250): Redis-&gt;flushDB()
#1 /usr/share/tine20/library/Zend/Cache/Core.php(430): Zend_Cache_Backend_Redis-&gt;clean(&#039;all&#039;, Array)
#2 /usr/share/tine20/Setup/Controller.php(574): Zend_Cache_Core-&gt;clean(&#039;all&#039;)
#3 /usr/share/tine20/Setup/Controller.php(427): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;8&#039;)
#4 /usr/share/tine20/Setup/Frontend/Cli.php(233): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#5 /usr/share/tine20/Setup/Frontend/Cli.php(196): Setup_Frontend_Cli-&gt;_updateApplications()
#6 /usr/share/tine20/Setup/Frontend/Cli.php(56): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#7 /usr/share/tine20/Setup/Server/Cli.php(92): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#8 /usr/share/tine20/Setup/Core.php(89): Setup_Server_Cli-&gt;handle()
#9 /usr/share in /usr/share/tine20/Zend/Cache/Backend/Redis.php on line 250

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Sep 2017 12:17**

could be solved by adding a redis proxy (like the imap proxy in Felamimail) that adds retry functionality to the redis cache backend.
