### ISSUE TITLE
0010447:
session cleanup scheduler job fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5206]
**Reported by pschuele on 10 Nov 2014 17:48**

**Version:** Koriander (2014.09.2)

STDERR: PHP Fatal error: Uncaught exception &#039;RuntimeException&#039; with message &#039;Directory name must not be empty.&#039; in .../tine/htdocs/Tinebase/Controller.php:496
Stack trace:
#0 .../tine/htdocs/Tinebase/Controller.php(496): DirectoryIterator-&gt;__construct(&#039;&#039;)
#1 [internal function]: Tinebase_Controller-&gt;cleanupSessions()
#2 .../tine/htdocs/Tinebase/Scheduler/Task.php(283): call_user_func_array(Array, Array)
#3 .../tine/htdocs/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
#4 .../tine/htdocs/Tinebase/Frontend/Cli.php(121): Zend_Scheduler-&gt;run()
#5 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#6 .../tine/htdocs/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#7 .../tine/htdocs/Tinebase/Server/Cli.php(93): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#8 .../tine/htdocs/Tine in .../tine/htdocs/Tinebase/Controller.php on line 496

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 12 Nov 2014 07:57**

I can&#039;t reproduce this problem on my development system. 

We have to do further research on the server generating the error.

**Comment by Gloirin** [comment]
**Comment posted by fmos on 4 Dec 2014 09:06**

I observe the following hourly error message, which seems related to the present issue:

&lt;pre&gt;ERR (3): Tinebase_Exception::log::104 UnexpectedValueException -&gt; DirectoryIterator::__construct(/var/lib/php5): failed to open dir: Permission denied&lt;/pre&gt;

The following patch seems to fix the problem:

&lt;pre&gt;
--- Tinebase/Controller.php.orig        2014-12-01 12:39:41.000000000 +0100
+++ Tinebase/Controller.php     2014-12-04 09:45:55.806698500 +0100
@@ -490,7 +490,7 @@
         
         if (strtolower($backendType) == &#039;file&#039;) {
             $maxLifeTime = ($config-&gt;session &amp;&amp; $config-&gt;session-&gt;lifetime) ? $config-&gt;session-&gt;lifetime : 86400;
-            $path = ini_get(&#039;session.save_path&#039;);
+            $path = ($config-&gt;session &amp;&amp; $config-&gt;session-&gt;path) ? $config-&gt;session-&gt;path : ini_get(&#039;session.save_path&#039;);
             
             $unlinked = 0;
             try {
&lt;/pre&gt;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Dec 2014 11:19**

hi fmos,

thanks for the patch. we&#039;ll test it and include it if it works as expected :)

**Comment by Gloirin** [comment]
**Comment posted by fmos on 5 Dec 2014 14:16**

I&#039;m using the above patch in production (2 users) myself. Today I observed the below error messages for the first time, which may be related to session data and therefore relevant in connection with the present issue:

&lt;pre&gt;
cf783 05914 XXXXXX - 2014-12-05T13:12:23+00:00 CRIT (2): Felamimail_Model_Account::resolveCredentials::432 Something went wrong with the CredentialsCache
cf783 05914 XXXXXX - 2014-12-05T13:12:23+00:00 WARN (4): Tinebase_Server_Json::_handleException::326 Felamimail_Exception_IMAPInvalidCredentials -&gt; Need at least user in params.
cf783 05914 XXXXXX - 2014-12-05T13:12:23+00:00 ERR (3): Tinebase_Exception::log::104 Felamimail_Exception_IMAPInvalidCredentials -&gt; Need at least user in params.
&lt;/pre&gt;

The messages occured when I was using the web interface several times over a long duration (serveral hours) and did not log out in between.
The web interface asked for IMAP login credentials, but providing them didn&#039;t help. Logout &amp; re-login did help. 

My suspicion is that the session data gets cleaned on the server although the browser session doesn&#039;t expire (or at least the browser doesn&#039;t notice).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Mar 2016 08:35**

the patch is already included in Elena (code moved to Tinebase_Session_Abstract::getSessionDir). closing this ticket...
