### ISSUE TITLE
0010462:
E-Mail sync stopped to work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5214]
**Reported by pschuele on 13 Nov 2014 13:03**

**Version:** Koriander (2014.09.3)

E-Mail sync stopped to work

... because sessions have been disabled in ActiveSync

**Additional information:** a45f5 kekstod - 2014-11-13T12:20:07+00:00 CRIT (2): Syncroton_Server::_handlePost::162 unexpected exception occured: Felamimail_Exception_IMAPInvalidCredentials
a45f5 kekstod - 2014-11-13T12:20:07+00:00 CRIT (2): Syncroton_Server::_handlePost::164 exception message: Need at least user in params.
a45f5 kekstod - 2014-11-13T12:20:07+00:00 CRIT (2): Syncroton_Server::_handlePost::166 #0 /var/www/virtual/kekstod/tine_2014_09_3/Felamimail/Backend/ImapFactory.php(48): Felamimail_Backend_ImapProxy-&gt;__construct(Array)
#1 /var/www/virtual/kekstod/tine_2014_09_3/Felamimail/Controller/Cache/Message.php(263): Felamimail_Backend_ImapFactory::factory(&#039;8727653414ef756...&#039;)
#2 /var/www/virtual/kekstod/tine_2014_09_3/Felamimail/Frontend/ActiveSync.php(683): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;ef4b8cc83a4cb1e...&#039;, 10)
#3 /var/www/virtual/kekstod/tine_2014_09_3/ActiveSync/Frontend/Abstract.php(669): Felamimail_Frontend_ActiveSync-&gt;_inspectGetCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#4 /var/www/virtual/kekstod/tine_2014_09_3/ActiveSync/Frontend/Abstract.php(687): ActiveSync_Frontend_Abstract-&gt;getCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#5 /var/www/virtual/kekstod/tine_2014_09_3/vendor/syncroton/syncroton/lib/Syncroton/Command/Sync.php(575): ActiveSync_Frontend_Abstract-&gt;hasChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#6 /var/www/virtual/kekstod/tine_2014_09_3/vendor/syncroton/syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_Sync-&gt;getResponse()
#7 /var/www/virtual/kekstod/tine_2014_09_3/vendor/syncroton/syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#8 /var/www/virtual/kekstod/tine_2014_09_3/ActiveSync/Server/Http.php(75): Syncroton_Server-&gt;handle()
#9 /var/www/virtual/kekstod/tine_2014_09_3/Tinebase/Core.php(200): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#10 /var/www/virtual/kekstod/tine_2014_09_3/index.php(19): Tinebase_Core::dispatchRequest()
#11 {main}
a45f5 kekstod - 2014-11-13T12:20:07+00:00 INFO (6): index.php (27) METHOD: ActiveSync_Server_Http::POST / TIME: 278ms /  Memory usage: 14.25 MB /  Real patch cache size: 16318

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Nov 2014 14:02**

and this happens during initial folder sync:

bbf6d golem01 - 2014-11-13T12:36:09+00:00 CRIT (2): Syncroton_Command_FolderSync::getResponse::157 Syncing folder hierarchy failed: Session not started
bbf6d golem01 - 2014-11-13T12:36:09+00:00 DEBUG (7): Syncroton_Command_FolderSync::getResponse::159 Syncing folder hierarchy failed: #0 /opt/local/tine/2014.09.2pl57/htdocs/Felamim
ail/Controller/Account.php(514): Tinebase_Session_Abstract::getSessionNamespace()
#1 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Backend/ImapFactory.php(49): Felamimail_Controller_Account-&gt;updateCapabilities(Object(Felamimail_Model_Account), Object(Felamimai
l_Backend_ImapProxy))
#2 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Controller/Cache/Folder.php(138): Felamimail_Backend_ImapFactory::factory(Object(Felamimail_Model_Account))
#3 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Controller/Cache/Folder.php(122): Felamimail_Controller_Cache_Folder-&gt;_getRootFolders(Object(Felamimail_Model_Account))
#4 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Controller/Cache/Folder.php(94): Felamimail_Controller_Cache_Folder-&gt;_getFoldersFromIMAP(Object(Felamimail_Model_Account), &#039;&#039;)
#5 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Frontend/ActiveSync.php(849): Felamimail_Controller_Cache_Folder-&gt;update(Object(Felamimail_Model_Account))
#6 /opt/local/tine/2014.09.2pl57/htdocs/Felamimail/Frontend/ActiveSync.php(801): Felamimail_Frontend_ActiveSync-&gt;_updateFolderCache()
#7 /opt/local/tine/2014.09.2pl57/htdocs/vendor/syncroton/syncroton/lib/Syncroton/Command/FolderSync.php(140): Felamimail_Frontend_ActiveSync-&gt;getAllFolders()
#8 /opt/local/tine/2014.09.2pl57/htdocs/vendor/syncroton/syncroton/lib/Syncroton/Server.php(145): Syncroton_Command_FolderSync-&gt;getResponse()
#9 /opt/local/tine/2014.09.2pl57/htdocs/vendor/syncroton/syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#10 /opt/local/tine/2014.09.2pl57/htdocs/ActiveSync/Server/Http.php(75): Syncroton_Server-&gt;handle()
#11 /opt/local/tine/2014.09.2pl57/htdocs/Tinebase/Core.php(200): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 /opt/local/tine/2014.09.2pl57/htdocs/index.php(19): Tinebase_Core::dispatchRequest()
#13 {main}
bbf6d golem01 - 2014-11-13T12:36:09+00:00 DEBUG (7): Syncroton_Server::_handlePost::175 xml response(0):
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot; xmlns:Syncroton=&quot;uri:Syncroton&quot;&gt;
  &lt;Status&gt;11&lt;/Status&gt;
&lt;/FolderSync&gt;

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 14 Nov 2014 07:32**

The second one should be fixed by this change https://gerrit.tine20.org/tine20/#/c/2961/1

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Nov 2014 08:23**

just added a hotfixed ActiveSync/Server/Http.php
