### ISSUE TITLE
0010470:
CalDAV is broken

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5218]
**Reported by e_li on 14 Nov 2014 11:07**

**Version:** Koriander (2014.09.3)

With update from 2014.09.2 to 2014.09.3 CalDAV sync to Android stopped working and emClient is displaying a mix of calendars and tasks.
The update was done with the Debian package on Nov 13.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Nov 2014 11:52**

hi e_li,

could you please add some more information? do you see any errors in the tine20 / webserver error logs?

**Comment by Gloirin** [comment]
**Comment posted by e_li on 14 Nov 2014 12:02**

Don&#039;t know if it is related to the problem. In /var/log/tine20/tine20.log I see hourly:

29042 cronuser - 2014-11-14T10:00:02+00:00 NOTICE (5): Tinebase_Core::errorHandler::561 Undefined variable: e in /usr/share/tine20/Tinebase/Controller.php::499 (8)
29042 cronuser - 2014-11-14T10:00:02+00:00 NOTICE (5): Tinebase_Core::errorHandler::562 #0 /usr/share/tine20/Tinebase/Controller.php(499): Tinebase_Core::errorHandler(8, &#039;Undefined varia...&#039;, &#039;/usr/share/tine...&#039;, 499, Array)
#1 [internal function]: Tinebase_Controller-&gt;cleanupSessions()
#2 /usr/share/tine20/Tinebase/Scheduler/Task.php(283): call_user_func_array(Array, Array)
#3 /usr/share/tine20/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
#4 /usr/share/tine20/Tinebase/Frontend/Cli.php(121): Zend_Scheduler-&gt;run()
#5 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#6 /usr/share/tine20/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#7 /usr/share/tine20/Tinebase/Server/Cli.php(93): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#8 /usr/share/tine20/Tinebase/Core.php(200): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#9 /usr/share/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#10 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Nov 2014 12:06**

this is not related as this only happens during the async job. but we&#039;ll have a look at this error, too.

**Comment by Gloirin** [comment]
**Comment posted by e_li on 14 Nov 2014 12:30**

I tried to create an account in CalDAV-Sync on my mobile. There are no errors in /var/log/tine20/tine20.log.
CalDAV-Sync reports errors with PropFind, but I&#039;m not sure what it looks for.

**Comment by Gloirin** [comment]
**Comment posted by e_li on 14 Nov 2014 12:37**

I found this in the apache log:

[Fri Nov 14 06:29:04 2014] [error] [client yy.yy.yy.yy] PHP Fatal error:  Uncaught exception &#039;Zend\\Http\\Exception\\InvalidArgumentException&#039; with message &#039;Invalid HTTP method passed&#039; in /usr/share/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php:141\nStack trace:\n#0 /usr/share/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(240): Zend\\Http\\Request-&gt;setMethod(&#039;REPORT&#039;)\n#1 /usr/share/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(82): Zend\\Http\\PhpEnvironment\\Request-&gt;setServer(Object(Zend\\Stdlib\\Parameters))\n#2 /usr/share/tine20/Tinebase/Core.php(188): Zend\\Http\\PhpEnvironment\\Request-&gt;__construct()\n#3 /usr/share/tine20/index.php(19): Tinebase_Core::dispatchRequest()\n#4 {main}\n  thrown in /usr/share/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php on line 141

[Fri Nov 14 13:23:59 2014] [error] [client xx.xx.xx.xx] script &#039;/var/www/groupdav.php&#039; not found or unable to stat
[Fri Nov 14 13:24:00 2014] [error] [client xx.xx.xx.xx] script &#039;/var/www/remote.php&#039; not found or unable to stat

I guess the last two can be ignored. Seems to be some kind of auto discovery. Tine is not installed in /var/www.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Nov 2014 12:40**

could you please have a look, if this fixes the problem:

http://git.tine20.org/git?p=tine20;a=blobdiff;f=tine20/Tinebase/Auth.php;h=0cd01b9b76ee6d9f14a6c07340a77a0792984811;hp=c38885a769ade0f6b03d1f16b11740bb6c6b3ebb;hb=00c205a90f344f04251510c7061afb0262021a43;hpb=ee02d4b95a791deb2e8a627d3c89d4083adb4d50

you could just replace your Tinebase/Auth.php with this file: http://git.tine20.org/git?p=tine20;a=blob_plain;f=tine20/Tinebase/Auth.php;hb=00c205a90f344f04251510c7061afb0262021a43

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 17 Nov 2014 01:50**

Maybe related:
My caldav does not work any more either with the latest GIT, neither in Thunderbird Lightning, nor in Apple iPhone:

Access log:
210.48.113.22 - ingo [17/Nov/2014:14:37:34 +1300] &quot;PROPFIND /calendars/c21349a5775f4dd6e603214dc0ad83ffc37729b6/9/ HTTP/1.1&quot; 207 6736 &quot;-&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.2.0 Lightning/3.3.1&quot;
210.48.113.22 - ingo [17/Nov/2014:14:37:39 +1300] &quot;REPORT /calendars/c21349a5775f4dd6e603214dc0ad83ffc37729b6/9/ HTTP/1.1&quot; 500 408 &quot;-&quot; &quot;Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.2.0 Lightning/3.3.1&quot;

Error Log:
[Mon Nov 17 14:36:43.487085 2014] [:error] [pid 4035] [client 210.48.113.22:7565] PHP Fatal error:  Uncaught exception &#039;Zend\\Http\\Exception\\InvalidArgumentException&#039; with message &#039;Invalid HTTP method passed&#039; in /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php:141\nStack trace:\n#0 /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(240): Zend\\Http\\Request-&gt;setMethod(&#039;REPORT&#039;)\n#1 /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(82): Zend\\Http\\PhpEnvironment\\Request-&gt;setServer(Object(Zend\\Stdlib\\Parameters))\n#2 /var/wwwroot/tine20-gerrit/tine20/Tinebase/Core.php(188): Zend\\Http\\PhpEnvironment\\Request-&gt;__construct()\n#3 /var/wwwroot/tine20-gerrit/tine20/index.php(19): Tinebase_Core::dispatchRequest()\n#4 {main}\n  thrown in /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php on line 141
[Mon Nov 17 14:37:39.666375 2014] [:error] [pid 14677] [client 210.48.113.22:7590] PHP Fatal error:  Uncaught exception &#039;Zend\\Http\\Exception\\InvalidArgumentException&#039; with message &#039;Invalid HTTP method passed&#039; in /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php:141\nStack trace:\n#0 /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(240): Zend\\Http\\Request-&gt;setMethod(&#039;REPORT&#039;)\n#1 /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/PhpEnvironment/Request.php(82): Zend\\Http\\PhpEnvironment\\Request-&gt;setServer(Object(Zend\\Stdlib\\Parameters))\n#2 /var/wwwroot/tine20-gerrit/tine20/Tinebase/Core.php(188): Zend\\Http\\PhpEnvironment\\Request-&gt;__construct()\n#3 /var/wwwroot/tine20-gerrit/tine20/index.php(19): Tinebase_Core::dispatchRequest()\n#4 {main}\n  thrown in /var/wwwroot/tine20-gerrit/tine20/vendor/zendframework/zend-http/Zend/Http/Request.php on line 141

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2014 10:59**

@Ingo: please run &quot;composer install&quot;. the zend-http lib has been updated.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 19 Nov 2014 17:51**

I am pretty sure I did that... Okay, will do again and see.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 20 Nov 2014 08:30**

Works after today&#039;s update.
