### ISSUE TITLE
0010502:
startup not working because DB is not initialized yet (redis)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5234]
**Reported by pschuele on 19 Nov 2014 09:06**

**Version:** Koriander (2014.09.4)

startup not working because DB is not initialized yet (redis)

* session + cache backends

**Steps to reproduce:** php-fpm + redis

**Additional information:** PHP message: PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.SQL_TABLE_PREFIXapplications&#039; doesn&#039;t exist&#039; in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /usr/share/tine20/Tinebase/Application.php(197): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /usr/share/tine20/Tinebase/Session/Abstract.php(246): Tinebase_Application-&gt;getApplicationByName(&#039;Tinebase&#039;)
#5 /usr/share/tine20/Setup/Core.php(65): Tinebase_Session_Abstract::setSessionBackend()
#6 /usr/share/tine20/Setup/Server/Http.php(30): Setup_Core::startSetupSession()

2014/11/19 09:44:52 [error] 7671#0: *35624 FastCGI sent in stderr: &quot;PHP message: Tinebase_Core::errorHandler::564 Use of undefined constant SQL_TABLE_PREFIX - assumed &#039;SQL_TABLE_PREFIX&#039; in /usr/share/tine20/Tinebase/Application.php::70 (8)
PHP message: Tinebase_Core::errorHandler::565 #0 /usr/share/tine20/Tinebase/Application.php(70): Tinebase_Core::errorHandler(8, &#039;Use of undefine...&#039;, &#039;/usr/share/tine...&#039;, 70, Array)
#1 /usr/share/tine20/Tinebase/Application.php(102): Tinebase_Application-&gt;__construct()
#2 /usr/share/tine20/Tinebase/Session/Abstract.php(246): Tinebase_Application::getInstance()
#3 /usr/share/tine20/Setup/Core.php(65): Tinebase_Session_Abstract::setSessionBackend()
#4 /usr/share/tine20/Setup/Server/Http.php(30): Setup_Core::startSetupSession()
#5 /usr/share/tine20/Setup/Core.php(104): Setup_Server_Http-&gt;handle()
#6 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2014 09:35**

fixed problem in redis session setup.

**Comment by Gloirin** [comment]
**Comment posted by jtremesay_menta on 21 Nov 2014 14:07**

I have the same error:
9a77a 1456c -- none -- - 2014-11-21T14:02:41+00:00 NOTICE (5): Tinebase_Core::errorHandler::561 Use of undefined constant SQL_TABLE_PREFIX - assumed &#039;SQL_TABLE_PREFIX&#039; in /srv/http/tine/2014.09.4/Tinebase/Application.php::70 (8)
9a77a 1456c -- none -- - 2014-11-21T14:02:41+00:00 NOTICE (5): Tinebase_Core::errorHandler::562 #0 /srv/http/tine/2014.09.4/Tinebase/Application.php(70): Tinebase_Core::errorHandler(8, &#039;Use of undefine...&#039;, &#039;/srv/http/tine/...&#039;, 70, Array)
#1 /srv/http/tine/2014.09.4/Tinebase/Application.php(102): Tinebase_Application-&gt;__construct()
#2 /srv/http/tine/2014.09.4/Setup/Controller.php(1786): Tinebase_Application::getInstance()
#3 /srv/http/tine/2014.09.4/Tinebase/User.php(247): Setup_Controller-&gt;isInstalled(&#039;Tinebase&#039;)
#4 /srv/http/tine/2014.09.4/Tinebase/User.php(156): Tinebase_User::getConfiguredBackend()
#5 /srv/http/tine/2014.09.4/Tinebase/Session/Validator/AccountStatus.php(40): Tinebase_User::getInstance()
#6 /srv/http/tine/2014.09.4/library/Zend/Session.php(779): Tinebase_Session_Validator_AccountStatus-&gt;validate()
#7 /srv/http/tine/2014.09.4/library/Zend/Session.php(506): Zend_Session::_processValidators()
#8 /srv/http/tine/2014.09.4/Tinebase/Core.php(483): Zend_Session::start()
#9 /srv/http/tine/2014.09.4/Tinebase/Server/Json.php(118): Tinebase_Core::startCoreSession()
#10 /srv/http/tine/2014.09.4/Tinebase/Core.php(200): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#11 /srv/http/tine/2014.09.1/index.php(19): Tinebase_Core::dispatchRequest()
#12 {main}


I have Tine 2014.09.4 patched with commit 447c79be52610ae17215c3f3a3cd09f51c35db76 (http://git.tine20.org/git?p=tine20;a=commit;h=447c79be52610ae17215c3f3a3cd09f51c35db76).
My webserver is nginx with PHP-fpm 5.4, my database is MySQL and I use Redis for cache and sessions.
