### ISSUE TITLE
0010508:
Session_Validator_AccountStatus causes problems

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5237]
**Reported by pschuele on 19 Nov 2014 14:52**

**Version:** Koriander (2014.09.4)

Session_Validator_AccountStatus causes problems

because of the new bootstrap flow

**Additional information:** a8d75 ffd63 -- none -- - 2014-11-19T14:42:32+00:00 CRIT (2): Tinebase_User_Sql::getUserByProperty::187 User sql plugin failure: exception &#039;Zend_Db_Adapter_Exception&#039; with message &#039;SQLSTATE[42000] [1044] Access denied for user &#039;xxxx&#039; to database &#039;aaaa&#039;&#039; in /usr/share/tine20.com/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php:144Stack trace:
#0 /usr/share/tine20.com/tine20/library/Zend/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract-&gt;_connect()
#1 /usr/share/tine20.com/tine20/Tinebase/Backend/Sql/Adapter/Pdo/Mysql.php(32): Zend_Db_Adapter_Pdo_Mysql-&gt;_connect()
#2 /usr/share/tine20.com/tine20/library/Zend/Db/Adapter/Abstract.php(832): Tinebase_Backend_Sql_Adapter_Pdo_Mysql-&gt;_connect()
#3 /usr/share/tine20.com/tine20/library/Zend/Db/Adapter/Abstract.php(902): Zend_Db_Adapter_Abstract-&gt;quote(&#039;metaways.de&#039;, NULL)
#4 /usr/share/tine20.com/tine20/Zend/Db/Select.php(930): Zend_Db_Adapter_Abstract-&gt;quoteInto(&#039;`dovecot_users`...&#039;, &#039;****&#039;, NULL)
#5 /usr/share/tine20.com/tine20/Zend/Db/Select.php(463): Zend_Db_Select-&gt;_where(&#039;`dovecot_users`...&#039;, &#039;***&#039;, NULL, true)
#6 /usr/share/tine20.com/tine20/Tinebase/EmailUser/Imap/Dovecot.php(296): Zend_Db_Select-&gt;where(&#039;`dovecot_users`...&#039;, &#039;****&#039;)
#7 /usr/share/tine20.com/tine20/Tinebase/EmailUser/Sql.php(176): Tinebase_EmailUser_Imap_Dovecot-&gt;_getSelect()
#8 /usr/share/tine20.com/tine20/Tinebase/User/Sql.php(183): Tinebase_EmailUser_Sql-&gt;inspectGetUserByProperty(Object(Tinebase_Model_FullUser))
#9 /usr/share/tine20.com/tine20/Tinebase/User/Abstract.php(566): Tinebase_User_Sql-&gt;getUserByProperty(&#039;accountId&#039;, &#039;3271&#039;, &#039;Tinebase_Model_...&#039;)
#10 /usr/share/tine20.com/tine20/Tinebase/User/Sql.php(291): Tinebase_User_Abstract-&gt;getUserById(&#039;3271&#039;, &#039;Tinebase_Model_...&#039;)
#11 /usr/share/tine20.com/tine20/Tinebase/Session/Validator/AccountStatus.php(40): Tinebase_User_Sql-&gt;getFullUserById(&#039;3271&#039;)
#12 /usr/share/tine20.com/tine20/library/Zend/Session.php(779): Tinebase_Session_Validator_AccountStatus-&gt;validate()
#13 /usr/share/tine20.com/tine20/library/Zend/Session.php(506): Zend_Session::_processValidators()
#14 /usr/share/tine20.com/tine20/Tinebase/Core.php(483): Zend_Session::start()
#15 /usr/share/tine20.com/tine20/Tinebase/Server/Json.php(118): Tinebase_Core::startCoreSession()
#16 /usr/share/tine20.com/tine20/Tinebase/Core.php(200): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2014 15:29**

it looks like the validator sometimes tries to access the DB before it has been initialized.

-&gt; i deactivated the validator for the moment.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2014 15:30**

https://gerrit.tine20.org/tine20/#/c/2975/
