### ISSUE TITLE
0010536:
Update von Version: Collin (2013.10.7) auf Koriander schlägt fehl. SQLSTATE[42S21]: Column already exists: 1060 Duplicate column

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5251]
**Reported by jhh on 26 Nov 2014 18:39**

**Version:** Koriander (2014.09.4)

php-cli setup.php --update
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name &#039;user_agent&#039;&#039; in /library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /Setup/Backend/Abstract.php(217): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /Setup/Backend/Mysql.php(214): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5  in /library/Zend/Db/Statement/Pdo.php on line 238

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name &#039;user_agent&#039;&#039; in /library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /Setup/Backend/Abstract.php(217): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /Setup/Backend/Mysql.php(214): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5  in /library/Zend/Db/Statement/Pdo.php on line 238

**Steps to reproduce:** setup.php --update

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Nov 2014 11:32**

I wrote a fix for this problem.
