### ISSUE TITLE
0010546:
Gnome 3 ActiveSync does not work

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5256]
**Reported by mspahn on 28 Nov 2014 22:49**

**Version:** Koriander (2014.09.4)

Gnome3 offers a service to add sync for activesync / exchange accounts.

But this does not work with Tine 2.0.

**Additional information:** 6b7c8 -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Auth::authenticate::206 Trying to authenticate ?T??@`?

6b7c8 -- none -- - 2014-11-28T22:42:47+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Auth_Adapter_Exception -&gt; A credential value was not provided prior to authentication with Zend_Auth_Adapter_DbTable.
6b7c8 -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): index.php (27) METHOD: ActiveSync_Server_Http::POST / TIME: 520ms /  Memory usage: 6.75 MB /  Real patch cache size: 16353
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::setupLogger::659 Logger initialized
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::getDispatchServer::213 POST https://tine.spahn.me/Microsoft-Server-ActiveSync/autodiscover/autodiscover.xml?frontend=activesync HTTP/1.1
X-Forwarded-For: 92.210.16.106
X-Ssl-Cipher: DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
X-Forwarded-Port: 443
X-Forwarded-Https: on
Content-Type: text/xml; charset=utf-8
Content-Length: 328
Connection: close
User-Agent: libews/0.1
Host: tine.spahn.me
Authorization: Basic a2Vrc3RvZDpmdHdoYnc4NjcwJA==

&lt;Autodiscover xmlns=&quot;http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006&quot;&gt;
  &lt;Request&gt;
    &lt;EMailAddress&gt;michael@spahn.me&lt;/EMailAddress&gt;
    &lt;AcceptableResponseSchema&gt;http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a&lt;/AcceptableResponseSchema&gt;
  &lt;/Request&gt;
&lt;/Autodiscover&gt;
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): ActiveSync_Server_Http::handle::42 is ActiveSync request.
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::setupCache::742 cache of backend type &#039;File&#039; enabled
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::createAndConfigureDbAdapter::882 Creating Pdo_Mysql DB adapter
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::341 Loading all configs for app Tinebase
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::348 Found 22 configs.
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1055 given localeString &#039;auto&#039;
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1082 Try to detect the locale of the user (browser, environment, default)
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::217 given localeString &#039;auto&#039;
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::229 &#039;en&#039; is not supported, checking fallback
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::255 selected locale: &#039;en&#039;
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::setupUserLocale::1099 Setting user locale: en
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1111 Setting CTYPE locale from &quot;C&quot; to &quot;en_US.UTF8&quot;.
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::1181 setting execution life time to: 0
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::341 Loading all configs for app ActiveSync
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::348 Found 0 configs.
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Auth::setBackend::277 authentication backend: Sql
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Auth::authenticate::206 Trying to authenticate kekstod
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_User::setBackendType::272 Setting backend type to Sql
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_User::getInstance::160 accounts backend: Sql
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_User::factory::233 Created user backend of type Sql
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Controller::login::92 Login with username kekstod from 92.210.16.106 succeeded.
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::208 Got 1 search results
7aa0a -- none -- - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::set::1276 Setting user kekstod
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1055 given localeString &#039;auto&#039;
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1082 Try to detect the locale of the user (browser, environment, default)
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::217 given localeString &#039;auto&#039;
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::229 &#039;en&#039; is not supported, checking fallback
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::255 selected locale: &#039;en&#039;
7aa0a kekstod - 2014-11-28T22:42:47+00:00 INFO (6): Tinebase_Core::setupUserLocale::1099 Setting user locale: en
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValueForUser::287 Get value for locale of account id 5aae3f1a712dad5d1522c3f9b0f9a16c325cf9e4 / user
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Group::getInstance::75 groups backend: Sql
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValueForUser::287 Get value for timezone of account id 5aae3f1a712dad5d1522c3f9b0f9a16c325cf9e4 / user
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::102 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::341 Loading all configs for app ActiveSync
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::348 Found 0 configs.
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Syncroton_Server::handle::61 REQUEST METHOD: POST
7aa0a kekstod - 2014-11-28T22:42:47+00:00 NOTICE (5): Tinebase_Core::errorHandler::561 Undefined offset: 186 in /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php::314 (8)
7aa0a kekstod - 2014-11-28T22:42:47+00:00 NOTICE (5): Tinebase_Core::errorHandler::562 #0 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(314): Tinebase_Core::errorHandler(8, &#039;Undefined offse...&#039;, &#039;/var/www/virtua...&#039;, 314, Array)
#1 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(100): Syncroton_Server-&gt;_getRequestParameters(Object(Zend_Controller_Request_Http))
#2 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#3 /var/www/virtual/kekstod/tine_2014_09_4/ActiveSync/Server/Http.php(75): Syncroton_Server-&gt;handle()
#4 /var/www/virtual/kekstod/tine_2014_09_4/Tinebase/Core.php(200): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#5 /var/www/virtual/kekstod/tine_2014_09_4/index.php(19): Tinebase_Core::dispatchRequest()
#6 {main}
7aa0a kekstod - 2014-11-28T22:42:47+00:00 WARN (4): Tinebase_Core::errorHandler::548 unpack(): Type H: not enough input, need 233, have 8 in /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php::322 (2)
7aa0a kekstod - 2014-11-28T22:42:47+00:00 WARN (4): Tinebase_Core::errorHandler::549 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;unpack(): Type ...&#039;, &#039;/var/www/virtua...&#039;, 322, Array)
#1 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(322): unpack(&#039;H466string&#039;, &#039;\xDDi\xCBb\xBD\xEB2\x9D&#039;)
#2 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(100): Syncroton_Server-&gt;_getRequestParameters(Object(Zend_Controller_Request_Http))
#3 /var/www/virtual/kekstod/tine_2014_09_4/vendor/syncroton/syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#4 /var/www/virtual/kekstod/tine_2014_09_4/ActiveSync/Server/Http.php(75): Syncroton_Server-&gt;handle()
#5 /var/www/virtual/kekstod/tine_2014_09_4/Tinebase/Core.php(200): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#6 /var/www/virtual/kekstod/tine_2014_09_4/index.php(19): Tinebase_Core::dispatchRequest()
#7 {main}
7aa0a kekstod - 2014-11-28T22:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::103 REQUEST Array
(
    [protocolVersion] =&gt; 12.6
    [command] =&gt; 
    [deviceId] =&gt; 
    [deviceType] =&gt; 
    [policyKey] =&gt; 
    [saveInSent] =&gt; 
    [collectionId] =&gt; 
    [itemId] =&gt; 
    [attachmentName] =&gt; 
    [acceptMultipart] =&gt; 
    [userAgent] =&gt; libews/0.1
    [contentType] =&gt; text/xml; charset=utf-8
)

7aa0a kekstod - 2014-11-28T22:42:47+00:00 CRIT (2): Syncroton_Server::_handlePost::109 command not supported: 
7aa0a kekstod - 2014-11-28T22:42:48+00:00 INFO (6): index.php (27) METHOD: ActiveSync_Server_Http::POST / TIME: 290ms /  Memory usage: 11.75 MB /  Real patch cache size: 16353

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 28 Nov 2014 23:35**

Error in unpack of base64 encoded string, similar to windows phone 8.1 and my surface 3 windows 8.1 mail sync issue.
Related to #0010518?

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 29 Nov 2014 15:49**

Ingo, did you see, that #101518 is solved now.

I guess that Gnome is not speaking ActiveSync but EWS. That&#039;s something different. It&#039;s SOAP and can not be compared to ActiveSync.
