### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by tvannahl** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#53]
Currently I am running backups by simply running dumps on mariadb, but somewhere in the forum I stumbled oppon something like a backup and restore function which seems to be recommended by at least one of your developers.

But as a relatively conservative administrator I would love to write my internal documentation and setup according to something I can rely on and that doesn't break in some forseable future. So if the internal backup and restore function is the recommended way to go it should be addressed in the wiki.

In the Upgrade section of the wiki this is currently mentioned but not written.

**Comment by msphn** [comment]
Cheers, feel free to add it. The function is described if you run `php setup.php`

**Comment by pschuele** [comment]
here is the section in the old wiki (which will shut down soon):

https://wiki.tine20.org/Backup_and_Restore

**Comment by msphn** [comment]
Wiki will shut off at 25.5.

**Comment by tvannahl** [comment]
Now that I had the time to look into this backup/restore function I stumbled accross the following:

```
130 root@crash-test-dummy:/opt/tine20/tine20 [HEAD] # php setup.php --backup --config=1 db=1 files=1 backupDir=/srv/tine_bak noTimestmap=1
PHP Fatal error:  Uncaught Setup_Exception_NotFound: Expressomail/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php. in /opt/tine20/tine20/Setup/Controller.php:512
Stack trace:
#0 /opt/tine20/tine20/Setup/Controller.php(2426): Setup_Controller->getSetupXml('Expressomail')
#1 /opt/tine20/tine20/Setup/Controller.php(2393): Setup_Controller->getBackupStructureOnlyTables()
#2 /opt/tine20/tine20/Setup/Frontend/Cli.php(1070): Setup_Controller->backup(Array)
#3 /opt/tine20/tine20/Setup/Frontend/Cli.php(99): Setup_Frontend_Cli->_backup(Object(Zend_Console_Getopt))
#4 /opt/tine20/tine20/Setup/Server/Cli.php(132): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#5 /opt/tine20/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#6 /opt/tine20/tine20/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}
  thrown in /opt/tine20/tine20/Setup/Controller.php on line 512

Fatal error: Uncaught Setup_Exception_NotFound: Expressomail/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php. in /opt/tine20/tine20/Setup/Controller.php:512
Stack trace:
#0 /opt/tine20/tine20/Setup/Controller.php(2426): Setup_Controller->getSetupXml('Expressomail')
#1 /opt/tine20/tine20/Setup/Controller.php(2393): Setup_Controller->getBackupStructureOnlyTables()
#2 /opt/tine20/tine20/Setup/Frontend/Cli.php(1070): Setup_Controller->backup(Array)
#3 /opt/tine20/tine20/Setup/Frontend/Cli.php(99): Setup_Frontend_Cli->_backup(Object(Zend_Console_Getopt))
#4 /opt/tine20/tine20/Setup/Server/Cli.php(132): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#5 /opt/tine20/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#6 /opt/tine20/tine20/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}
  thrown in /opt/tine20/tine20/Setup/Controller.php on line 512
```

Further more the settings are not really self explanitory, at least to me.

What are `--config=1` and `noTimestmap=1` exactly for?

**Comment by pschuele** [comment]
> PHP Fatal error:  Uncaught Setup_Exception_NotFound: Expressomail/Setup/setup.xml not found

could you please create a separate issue for this? you also might add it to this issue: https://github.com/tine20/tine20/issues/6515

> What are --config=1 and noTimestmap=1 exactly for?

config=1 will also backup the config.inc.php file.
noTimestmap=1 does not create a subdir with the current timestamp for the backup files.
