### ISSUE TITLE
0010890:
Sales module can not be successfully updated from 2013.10.7 to 2014.09.8

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5390]
**Reported by weberho on 5 Mar 2015 09:59**

**Version:** Koriander (2014.09.8)

The update fails giving a message related to a former (already disabled) user. However, the update operation is done by tine20setup user and not by the user &quot;Old, User&quot; which tine20 referres to.

d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::set::1245 Setting user &#039;tine20setup&#039;
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::setupCache::770 cache disabled
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::setupUserLocale::1071 Setting user locale: de
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.updateApplications
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::setExecutionLifeTime::1146 setting execution life time to: 0
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Setup_Controller::updateApplication::508 Executing updates for Sales (starting at 8.3)
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Setup_Controller::updateApplication::532 Updating Sales - update_3
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_User::setBackendType::281 Setting backend type to Sql
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_User::factory::242 Created user backend of type Sql
d62b8 -- none -- - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::set::1245 Setting user Old, User
d62b8 Old, User - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::setupUserLocale::1071 Setting user locale: de
d62b8 Old, User - 2015-03-05T09:49:08+00:00 INFO (6): Tinebase_Core::getApplicationInstance::433 User Old Usern/100cf679c8621cd2a5218cd0b14bb2e0df5ed67d has no right to access Sales
d62b8 Old, User - 2015-03-05T09:49:08+00:00 ERR (3): Setup_Controller::updateApplication::542 No right to access application Sales
d62b8 Old, User - 2015-03-05T09:49:08+00:00 ERR (3): Setup_Controller::updateApplication::543 #0 /usr/share/tine20/Tinebase/Container.php(306): Tinebase_Core::getApplicationInstance(&#039;Sales&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(402): Tinebase_Container-&gt;_resolveRecordClassArgument(&#039;Sales&#039;)
#2 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(513): Tinebase_Container-&gt;getContainerByACL(Object(Tinebase_Model_User), &#039;Sales&#039;, &#039;readGrant&#039;, true)
#3 /usr/share/tine20/Sales/Setup/Update/Release8.php(184): Tinebase_Controller_Record_Abstract-&gt;getMultiple(Array)
#4 /usr/share/tine20/Sales/Setup/Update/Release8.php(258): Sales_Setup_Update_Release8-&gt;_updateContractsFields()
#5 /usr/share/tine20/Setup/Controller.php(536): Sales_Setup_Update_Release8-&gt;update_3()
#6 /usr/share/tine20/Setup/Controller.php(435): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;8&#039;)
#7 /usr/share/tine20/Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#8 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#9 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /usr/share/tine20/Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#13 /usr/share/tine20/Setup/Core.php(108): Setup_Server_Json-&gt;handle()
#14 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#15 {main}
d62b8 Old, User - 2015-03-05T09:49:08+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_AccessDenied -&gt; No right to access application Sales
d62b8 Old, User - 2015-03-05T09:49:08+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; No right to access application Sales

**Comment by Gloirin** [comment]
Related to #5269

**Comment by Gloirin** [comment]
Related to #5386

**Comment by Gloirin** [comment]
**Comment posted by weberho on 5 Mar 2015 10:24**

After uninstalling/installing the sales module the system is running again, but I can&#039;t log in; in Apache&#039;s error log I see the following messages upon each login:

[Thu Mar 05 11:09:29 2015] [error] [client 85.124.132.100] PHP Fatal error:  Can&#039;t inherit abstract function Sales_Model_Accountable_Interface::clearBillables() (previously declared abstract in Sales_Model_Accountable_Abstract) in /usr/share/tine20/Sales/Model/Accountable/Abstract.php on line 19, referer: https://tine.DOMAIN.com/

Removing the &quot;abstract public function clearBillables/loadBillables/isBillable&quot; methods from /usr/share/tine20/Sales/Model/Accountable/Abstract.php makes me beeing able to log in and work with tine20.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 5 Mar 2015 10:40**

You use an older php version, don&#039;t you?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 5 Mar 2015 10:54**

On this server it&#039;s 5.3.5, so not the latest version, yes.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 5 Mar 2015 11:19**

PHP Bug seems to be fixed with 5.3.9, see http://php.net/ChangeLog-5.php#5.3.9 and https://bugs.php.net/bug.php?id=43200 

So documentation/software checks should be updated to reflect this or the code should be written compatible ;-)

However, the update problem still exists and seems not to be related to this issue.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Jun 2015 08:29**

thanks for the infos.

we&#039;ll update the required php version soon.

and I&#039;ll have a look at the broken Sales update, too.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jun 2016 10:56**

the problem here is that an admin user is required for the update and there is no check if the user has the required right for the Sales app. fixing that...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jun 2016 11:05**

http://gerrit.tine20.com/customers/3228
