### ISSUE TITLE
0010900:
.eml attachments can't be opened

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5395]
**Reported by jan on 11 Mar 2015 17:18**

**Version:** Koriander (2014.09.8)

If you try to open an email attached to an email the error message &quot;Nachricht nicht verfügbar&quot; appears.

**Steps to reproduce:** Forward yourself an email as attachment (.eml).
Try to open the attachment in Tine2.0.

**Additional information:** 267ef f0cb8 jan - 2015-03-11T17:11:42+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::545 Updating capabilities for account:
267ef f0cb8 jan - 2015-03-11T17:11:42+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_NotFound -&gt; $_id can not be empty
267ef f0cb8 jan - 2015-03-11T17:11:42+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::331 Looking for defaults config.inc.php at /usr/share/tine20/Tinebase/config.inc.php
267ef f0cb8 jan - 2015-03-11T17:11:42+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; $_id can not be empty

**Comment by Gloirin** [comment]
**Comment posted by jan on 6 Apr 2015 16:35**

Here is the stack trace:
------------------------

12c63 69b29 jan - 2015-04-06T16:04:25+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_NotFound -&gt; $_id can not be empty
12c63 69b29 jan - 2015-04-06T16:04:25+00:00 WARN (4): Tinebase_Server_Json::_handleException::326 Tinebase_Exception_NotFound -&gt; exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;$_id can not be empty&#039; in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:211
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(1252): Tinebase_Backend_Sql_Abstract-&gt;get(NULL, true)
#1 /usr/share/tine20/Felamimail/Controller/Account.php(546): Tinebase_Backend_Sql_Abstract-&gt;update(Object(Felamimail_Model_Account))
#2 /usr/share/tine20/Felamimail/Backend/ImapFactory.php(49): Felamimail_Controller_Account-&gt;updateCapabilities(Object(Felamimail_Model_Account), Object(Felamimail_Backend_ImapProxy))
#3 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(1312): Felamimail_Backend_ImapFactory::factory(NULL)
#4 /usr/share/tine20/Felamimail/Model/Message.php(200): Felamimail_Controller_Cache_Message-&gt;getMessageSummary(&#039;8329&#039;, NULL, &#039;fe110b4129eb274...&#039;)
#5 /usr/share/tine20/Felamimail/Model/Message.php(178): Felamimail_Model_Message-&gt;_fetchStructure()
#6 /usr/share/tine20/Felamimail/Model/Message.php(363): Felamimail_Model_Message-&gt;__get(&#039;structure&#039;)
#7 /usr/share/tine20/Felamimail/Controller/Message.php(237): Felamimail_Model_Message-&gt;parseStructure(Array)
#8 /usr/share/tine20/Felamimail/Controller/Message.php(163): Felamimail_Controller_Message-&gt;_getCompleteMessageContent(Object(Felamimail_Model_Message), Object(Felamimail_Model_Account), &#039;2&#039;)
#9 /usr/share/tine20/Felamimail/Frontend/Json.php(198): Felamimail_Controller_Message-&gt;getCompleteMessage(&#039;6692c5af35512e3...&#039;, &#039;2&#039;, false)
#10 [internal function]: Felamimail_Frontend_Json-&gt;getMessage(&#039;6692c5af35512e3...&#039;)
#11 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /usr/share/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 /usr/share/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#16 /usr/share/tine20/Tinebase/Core.php(207): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#17 /usr/share/tine20/index.php(19): Tinebase_Core::dispatchRequest()
#18 {main}
12c63 69b29 jan - 2015-04-06T16:04:25+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; $_id can not be empty

**Comment by Gloirin** [comment]
**Comment posted by jan on 6 Apr 2015 16:38**

tine20_felamimail_eml_attachment.patch fixes the problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Apr 2015 14:41**

fix is in the repo: http://git.tine20.org/git?p=tine20;a=commit;h=501ef916c023eec22d28ff0044958ebc995f3795
