### ISSUE TITLE
0010908:
Sending Mail: Fehler: 502 5.5.1 Error: command not implemented

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5398]
**Reported by kobusch on 16 Mar 2015 14:58**

**Version:** git master

Sending Mails in Felamimail produces the following error:

a4586 2bb9b riffraff - 2015-03-16T14:53:16+00:00 WARN (4): Felamimail_Controller_Message_Send::sendMessage::81 Could not send message: exception &#039;Zend_Mail_Protocol_Exception&#039; with message &#039;502 5.5.1 Error: command not implemented
&#039; in /mnt/system/www/htdocs/tine/********_repos/********/Zend/Mail/Protocol/Abstract.php:389
Stack trace:
#0 /mnt/system/www/htdocs/tine/********_repos/********/library/Zend/Mail/Protocol/Smtp.php(205): Zend_Mail_Protocol_Abstract-&gt;_expect(220, 180)
#1 /mnt/system/www/htdocs/tine/********_repos/********/library/Zend/Mail/Transport/Smtp.php(196): Zend_Mail_Protocol_Smtp-&gt;helo(&#039;localhost&#039;)
#2 /mnt/system/www/htdocs/tine/********_repos/********/library/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp-&gt;_sendMail()
#3 /mnt/system/www/htdocs/tine/********_repos/********/library/Zend/Mail.php(973): Zend_Mail_Transport_Abstract-&gt;send(Object(Tinebase_Mail))
#4 /mnt/system/www/htdocs/tine/********_repos/********/Tinebase/Smtp.php(145): Zend_Mail-&gt;send(Object(Felamimail_Transport))
#5 /mnt/system/www/htdocs/tine/********_repos/********/Felamimail/Controller/Message/Send.php(235): Tinebase_Smtp-&gt;sendMessage(Object(Tinebase_Mail), Object(Felamimail_Transport))
#6 /mnt/system/www/htdocs/tine/********_repos/********/Felamimail/Controller/Message/Send.php(79): Felamimail_Controller_Message_Send-&gt;_sendMailViaTransport(Object(Tinebase_Mail), Object(Felamimail_Model_Account), Object(Felamimail_Model_Message), true, Array)
#7 /mnt/system/www/htdocs/tine/********_repos/********/Felamimail/Frontend/Json.php(238): Felamimail_Controller_Message_Send-&gt;sendMessage(Object(Felamimail_Model_Message))
#8 [internal function]: Felamimail_Frontend_Json-&gt;saveMessage(Array)
#9 /mnt/system/www/htdocs/tine/********_repos/********/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /mnt/system/www/htdocs/tine/********_repos/********/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /mnt/system/www/htdocs/tine/********_repos/********/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /mnt/system/www/htdocs/tine/********_repos/********/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /mnt/system/www/htdocs/tine/********_repos/********/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /mnt/system/www/htdocs/tine/********_repos/********/Tinebase/Core.php(207): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /mnt/system/www/htdocs/tine/********_repos/********/index.php(19): Tinebase_Core::dispatchRequest()
#16 {main}
a4586 2bb9b riffraff - 2015-03-16T14:53:16+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_SystemGeneric -&gt; Fehler: 502 5.5.1 Error: command not implemented

a4586 2bb9b riffraff - 2015-03-16T14:53:16+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_SystemGeneric -&gt; Fehler: 502 5.5.1 Error: command not implemented

**Steps to reproduce:** New Mail
Put in Address
Put Send Button

**Comment by Gloirin** [comment]
**Comment posted by kobusch on 25 Mar 2015 10:00**

Problem war auf Seiten postfix
