### ISSUE TITLE
0010922:
Openoffice export not working: execption

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5405]
**Reported by mokraemer on 25 Mar 2015 09:39**

**Version:** Koriander (2014.09.8)

tried to export an invoice as openoffice document

**Additional information:** 4a89f user - 2015-03-24T23:39:26+00:00 INFO (6): Tinebase_Export_Spreadsheet_Ods::generate::128 Creating export for Sales_Model_Invoice . Data
4a89f user - 2015-03-24T23:39:26+00:00 WARN (4): Tinebase_Core::errorHandler::558 SimpleXMLElement::addChild(): Attribute requires prefix for namespace in /home/www/www/tine/vendor/metaways/opendocument/lib/OpenDocument/SpreadSheet/Table.php::105 (2)
4a89f user - 2015-03-24T23:39:26+00:00 WARN (4): Tinebase_Core::errorHandler::559 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;SimpleXMLElemen...&#039;, &#039;/home/www...&#039;, 105, Array)
#1 /home/www/www/tine/vendor/metaways/opendocument/lib/OpenDocument/SpreadSheet/Table.php(105): SimpleXMLElement-&gt;addChild(&#039;table&#039;, NULL, &#039;urn:oasis:names...&#039;)
#2 /home/www/www/tine/vendor/metaways/opendocument/lib/OpenDocument/SpreadSheet.php(367): OpenDocument_SpreadSheet_Table::createTable(Object(SimpleXMLElement), &#039;Data&#039;, NULL)
#3 /home/www/www/tine/Tinebase/Export/Spreadsheet/Ods.php(137): OpenDocument_SpreadSheet-&gt;appendTable(&#039;Data&#039;)
#4 /home/www/www/tine/Tinebase/Frontend/Http/Abstract.php(72): Tinebase_Export_Spreadsheet_Ods-&gt;generate()
#5 /home/www/www/tine/Sales/Frontend/Http.php(68): Tinebase_Frontend_Http_Abstract-&gt;_export(Object(Sales_Model_InvoiceFilter), Array, Object(Sales_Controller_Invoice))
#6 [internal function]: Sales_Frontend_Http-&gt;exportInvoices(&#039;[{&quot;field&quot;:&quot;id&quot;,...&#039;, &#039;{&quot;format&quot;:&quot;ods&quot;...&#039;)
#7 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Sales_Frontend_Http), Array)
#8 /home/www/www/tine/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#9 /home/www/www/tine/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#10 /home/www/www/tine/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Sales_Frontend_Http), Array)
#11 /home/www/www/tine/Tinebase/Server/Http.php(93): Tinebase_Http_Server-&gt;handle(Array)
#12 /home/www/www/tine/Tinebase/Core.php(207): Tinebase_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#13 /home/www/www/tine/index.php(19): Tinebase_Core::dispatchRequest()
#14 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Apr 2015 07:32**

hi,

I could not reproduce this with 2014.09.9.

did you customize anything (export definition, odt files, php code)?

or maybe there is something strange with your invoice.

another possibility: your OpenDocument library is not up to date. did you update that as well?

**Comment by Gloirin** [comment]
**Comment posted by mokraemer on 30 Apr 2015 09:54**

this report was against 2014.09.8 hadn&#039;t had the time to update.

This was a plain install from tarball, nothing is configured - just wanted to test the feature.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2015 08:32**

ok, then please test again with current 2014.09.10 and tell us the php version that your server is running.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jun 2016 11:10**

closing this as we were not able to reproduce the problem.
