### ISSUE TITLE
0010928:
iconv use is deprecated

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5408]
**Reported by mspahn on 26 Mar 2015 11:40**

**Version:** Koriander (2014.09.9)

Use of iconv.internal_encoding is deprecated

**Additional information:** 2015-03-26T11:39:21+00:00 NOTICE (5): Tinebase_Core::errorHandler::567 iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Validate/Hostname.php::438 (8192)
85549 89af7 kekstod - 2015-03-26T11:39:21+00:00 NOTICE (5): Tinebase_Core::errorHandler::568 #0 [internal function]: Tinebase_Core::errorHandler(8192, &#039;iconv_set_encod...&#039;, &#039;/var/www/virtua...&#039;, 438, Array)
#1 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Validate/Hostname.php(438): iconv_set_encoding(&#039;internal_encodi...&#039;, &#039;UTF-8&#039;)
#2 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Validate.php(98): Zend_Validate_Hostname-&gt;isValid(&#039;vega.uberspace....&#039;)
#3 /var/www/virtual/kekstod/tine_2014_09_9/Zend/Mail/Protocol/Abstract.php(137): Zend_Validate-&gt;isValid(&#039;vega.uberspace....&#039;)
#4 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Mail/Protocol/Smtp.php(156): Zend_Mail_Protocol_Abstract-&gt;__construct(&#039;vega.uberspace....&#039;, &#039;587&#039;)
#5 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Mail/Protocol/Smtp/Auth/Login.php(76): Zend_Mail_Protocol_Smtp-&gt;__construct(&#039;vega.uberspace....&#039;, &#039;587&#039;, Array)
#6 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Mail/Transport/Smtp.php(194): Zend_Mail_Protocol_Smtp_Auth_Login-&gt;__construct(&#039;vega.uberspace....&#039;, &#039;587&#039;, Array)
#7 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp-&gt;_sendMail()
#8 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Mail.php(973): Zend_Mail_Transport_Abstract-&gt;send(Object(Tinebase_Mail))
#9 /var/www/virtual/kekstod/tine_2014_09_9/Tinebase/Smtp.php(145): Zend_Mail-&gt;send(Object(Felamimail_Transport))
#10 /var/www/virtual/kekstod/tine_2014_09_9/Felamimail/Controller/Message/Send.php(235): Tinebase_Smtp-&gt;sendMessage(Object(Tinebase_Mail), Object(Felamimail_Transport))
#11 /var/www/virtual/kekstod/tine_2014_09_9/Felamimail/Controller/Message/Send.php(79): Felamimail_Controller_Message_Send-&gt;_sendMailViaTransport(Object(Tinebase_Mail), Object(Felamimail_Model_Account), Object(Felamimail_Model_Message), true, Array)
#12 /var/www/virtual/kekstod/tine_2014_09_9/Felamimail/Frontend/Json.php(238): Felamimail_Controller_Message_Send-&gt;sendMessage(Object(Felamimail_Model_Message))
#13 [internal function]: Felamimail_Frontend_Json-&gt;saveMessage(Array)
#14 /var/www/virtual/kekstod/tine_2014_09_9/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#15 /var/www/virtual/kekstod/tine_2014_09_9/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#16 /var/www/virtual/kekstod/tine_2014_09_9/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#17 /var/www/virtual/kekstod/tine_2014_09_9/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#18 /var/www/virtual/kekstod/tine_2014_09_9/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#19 /var/www/virtual/kekstod/tine_2014_09_9/Tinebase/Core.php(207): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#20 /var/www/virtual/kekstod/tine_2014_09_9/index.php(19): Tinebase_Core::dispatchRequest()
#21 {main}

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 26 Mar 2015 13:26**

PHP 5.6.1

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 27 Apr 2015 09:51**

This is actually a bug in Zend 1.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 27 Apr 2015 09:53**

http://gerrit.tine20.com/customers/1884

That fixes it at least for our bootstrap.php

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 30 Apr 2015 08:55**

Latest versions of ZF1 has this problem solved.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 24 Feb 2017 08:31**

Resolved with ZF1 Update
