### ISSUE TITLE
0010940:
Dovecot MySQL SSHA512 password too long

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5414]
**Reported by TallStranger on 30 Mar 2015 19:44**

**Version:** Koriander (2014.09.9)

Auf einem nach dieser Anleitung (https://wiki.tine20.org/Admins/Mailserver_integration) installierten System schlägt das Anlegen eines neues Benutzers fehl, wenn als &quot;Password Scheme&quot; im Dovecot MySQL Backend SSHA512 ausgewählt ist. Mit SSHA256 funktioniert es. Schaltet man den Profiler für die DB an, dann taucht im Log das hier auf (gesamter Auszug aus dem Log siehe Feld Additional Information):
d2b2f 5a318 admin - 2015-03-27T18:20:07+00:00 ERR (3): Tinebase_EmailUser_Sql::_addUser::335 Error while creating email user: exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;password&#039; at row 1&#039; in /var/www/html/tine20-ts/library/Zend/Db/Statement/Pdo.php:238

Es sieht so aus, dass das Feld in der Datenbank nicht lang genug für den Hash ist.

**Steps to reproduce:** Erneut versuchen einen Benutzer anzulegen

**Additional information:** d2b2f 5a318 admin - 2015-03-27T18:20:07+00:00 ERR (3): Tinebase_EmailUser_Sql::_addUser::335 Error while creating email user: exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;password&#039; at row 1&#039; in /var/www/html/tine20-ts/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/html/tine20-ts/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/html/tine20-ts/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/html/tine20-ts/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `do...&#039;, Array)
#3 /var/www/html/tine20-ts/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `do...&#039;, Array)
#4 /var/www/html/tine20-ts/Tinebase/EmailUser/Sql.php(325): Zend_Db_Adapter_Abstract-&gt;insert(&#039;dovecot_users&#039;, Array)
#5 /var/www/html/tine20-ts/Tinebase/User/Plugin/Abstract.php(64): Tinebase_EmailUser_Sql-&gt;_addUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#6 /var/www/html/tine20-ts/Tinebase/User/Plugin/Abstract.php(45): Tinebase_User_Plugin_Abstract-&gt;inspectUpdateUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#7 /var/www/html/tine20-ts/Tinebase/User/Sql.php(860): Tinebase_User_Plugin_Abstract-&gt;inspectAddUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#8 /var/www/html/tine20-ts/Tinebase/User/Sql.php(846): Tinebase_User_Sql-&gt;addPluginUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#9 /var/www/html/tine20-ts/Admin/Controller/User.php(277): Tinebase_User_Sql-&gt;addUser(Object(Tinebase_Model_FullUser))
#10 /var/www/html/tine20-ts/Admin/Frontend/Json.php(372): Admin_Controller_User-&gt;create(Object(Tinebase_Model_FullUser), &#039;$gut5schrift%&#039;, &#039;$gut5schrift%&#039;)
#11 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#12 /var/www/html/tine20-ts/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 /var/www/html/tine20-ts/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 /var/www/html/tine20-ts/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 /var/www/html/tine20-ts/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 /var/www/html/tine20-ts/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#17 /var/www/html/tine20-ts/Tinebase/Core.php(207): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#18 /var/www/html/tine20-ts/index.php(19): Tinebase_Core::dispatchRequest()
#19 {main}
d2b2f 5a318 admin - 2015-03-27T18:20:07+00:00 ERR (3): Admin_Controller_User::create::287 SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20ts`.`tine20_group_members`, CONSTRAINT `tine20_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine20_accounts` (`id`))
d2b2f 5a318 admin - 2015-03-27T18:20:07+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Zend_Db_Statement_Exception -&gt; SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20ts`.`tine20_group_members`, CONSTRAINT `tine20_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine20_accounts` (`id`))
d2b2f 5a318 admin - 2015-03-27T18:20:07+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20ts`.`tine20_group_members`, CONSTRAINT `tine20_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine20_accounts` (`id`))

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 May 2015 19:44**

just increase the password field length. i would suppose varchar(256).

I updated the create table in the comment (Tinebase/EmailUser/Imap/Dovecot.php)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 May 2015 15:46**

i increased the size of the password fields on the wiki page, too.
