### ISSUE TITLE
0010980:
DavDROID can't save tasks

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5434]
**Reported by mspahn on 25 Apr 2015 13:58**

**Version:** Koriander (2014.09.9)

DAVDROID is an unknown client therefor it&#039;s not allowed to create and edit.

**Additional information:** 1e0d4 kekstod - 2015-04-25T13:18:41+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::145 &gt;&gt;&gt; *DAV response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\Forbidden&lt;/s:exception&gt;
  &lt;s:message&gt;Update denied for unknow client&lt;/s:message&gt;
  &lt;s:sabredav-version&gt;1.8.10&lt;/s:sabredav-version&gt;
&lt;/d:error&gt;

D/HttpClient(26980): Connection released: [id: 28][route: HttpRoute[{s}-&gt;https://tine.spahn.me:443]][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 3]
E/davdroid.DavSyncAdapter(26980): Hard HTTP error 403
E/davdroid.DavSyncAdapter(26980): at.bitfire.davdroid.webdav.HttpException: 403 Forbidden
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:419)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:393)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.webdav.WebDavResource.put(WebDavResource.java:370)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.resource.RemoteCollection.update(RemoteCollection.java:184)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.syncadapter.SyncManager.pushDirty(SyncManager.java:169)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:50)
E/davdroid.DavSyncAdapter(26980): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:146)
E/davdroid.DavSyncAdapter(26980): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 25 Apr 2015 14:27**

Tine supports davdroid now :)

https://gerrit.tine20.org/tine20/#/c/3075/

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 26 Apr 2015 08:56**

I verified my change today, every field matches correctly.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 27 Apr 2015 09:22**

Hi, happy to re-check, however about 6 months ago, davdroid had timezone issues and synced every entry to the incorrect time. Might be working good in your timezone, did not for me in UTC+13. From my experience, all works great in UTC to UTC+11, UTC+12 and more throws up quite a lot of software... ;-)
See #10778

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 27 Apr 2015 09:35**

If that&#039;s a bug I will contact upstream and aim to resolve that. Don&#039;t worry. I won&#039;t drop it. :&gt;

**Comment by Gloirin** [comment]
**Comment posted by Hennige-IT on 1 May 2016 16:50**

Hey Guys,
sorry for reopen, but this error is the same while syncing tasks.
I think the solution should be the same with a new converter.

Thanks for all the great work you all done already.
Tine 2.0 is amazing over many years.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 2 May 2016 11:34**

I take this, give me at least to the next monday :P.

**Comment by Gloirin** [comment]
**Comment posted by Hennige-IT on 13 Jul 2016 15:24**

Maybe the following report from the davdroid error message could help you:

SYNCHRONIZATION INFO
Synchronization phase: 4
Account name: info@xxx.de
Authority: org.dmfs.tasks

HTTP REQUEST:
PUT /calendars/shared/37/b6ec1853-cbfd-430d-a4e7-b6e393bddcc9
Content-Length: 404
Content-Type: text/calendar;charset=utf-8
If-Match: &quot;d42ccb6bc66e64f273e39b97cf488cb412a2a444&quot;

BEGIN:VCALENDAR[CR][LF]
VERSION:2.0[CR][LF]
PRODID:+//IDN bitfire.at//DAVdroid/1.2 ical4android ical4j/2.x[CR][LF]
BEGIN:VTODO[CR][LF]
DTSTAMP:20160713T152040Z[CR][LF]
UID:b6ec1853-cbfd-430d-a4e7-b6e393bddcc9[CR][LF]
SEQUENCE:2[CR][LF]
CREATED:20160711T195600Z[CR][LF]
LAST-MODIFIED:20160713T151833Z[CR][LF]
SUMMARY:test[CR][LF]
ORGANIZER:mailto:info@xxx.de[CR][LF]
CLASS:PUBLIC[CR][LF]
STATUS:COMPLETED[CR][LF]
COMPLETED:20160713T151833Z[CR][LF]
PERCENT-COMPLETE:100[CR][LF]
END:VTODO[CR][LF]
END:VCALENDAR[CR][LF]


HTTP RESPONSE:
http/1.1 403 Forbidden
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8
Date: Wed, 13 Jul 2016 15:20:41 GMT
Keep-Alive: timeout=5, max=99
Server: Apache/2.4.10 (Debian)
Transfer-Encoding: chunked
X-API: http://www.tine20.org/apidocs/tine20/

&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;[LF]
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;[LF]
  &lt;s:exception&gt;Sabre\DAV\Exception\Forbidden&lt;/s:exception&gt;[LF]
  &lt;s:message&gt;Update denied for unknow client&lt;/s:message&gt;[LF]
  &lt;s:sabredav-version&gt;1.8.12&lt;/s:sabredav-version&gt;[LF]
&lt;/d:error&gt;[LF]


EXCEPTION:
at.bitfire.dav4android.exception.HttpException: 403 Forbidden
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:316)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:289)
	at at.bitfire.dav4android.DavResource.put(DavResource.java:200)
	at at.bitfire.davdroid.syncadapter.SyncManager.uploadDirty(SyncManager.java:319)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.java:148)
	at at.bitfire.davdroid.syncadapter.TasksSyncAdapterService$SyncAdapter.onPerformSync(TasksSyncAdapterService.java:78)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

SOFTWARE INFORMATION
DAVdroid version: 1.2 (109) Sun Jul 03 15:15:13 MESZ 2016
Installed from: org.fdroid.fdroid
JB Workaround installed: no

CONFIGURATION
System-wide synchronization: automatically
Account: info@xxx.de
  Address book sync. interval: 240 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: 240 min
  Preemptive auth: true
  WiFi only: false
  [CardDAV] Contact group method: CATEGORIES
            RFC 6868 encoding: true
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Jul 2016 19:43**

Hmm, checked it right now and all works for me. Do you have an old version? Anything that did not upgrade?
Anyway, works for under current GIT like a treat. BTW, I also added Task support and will add that in the next few days.

Check yours against those ones:
https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/tree/master/tine20/Addressbook/Convert/Contact/VCard

**Comment by Gloirin** [comment]
**Comment posted by Hennige-IT on 13 Jul 2016 19:52**

The Problem exists only when syncing Tasks(!)
I have Version: Egon (2016.03.2)

maybe here...
https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/tree/master/tine20/Tasks/Convert/Task/VCalendar
...is missing a converter like here...
https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/tree/master/tine20/Calendar/Convert/Event/VCalendar


I could fix it amateurish:

comment out in /htdocs/Tasks/Frontend/WebDAV/Task.php (356-360) 

    public function put($cardData)
    {
//        if (get_class($this-&gt;_converter) == &#039;Tasks_Convert_Task_VCalendar_Generic&#039;) {
//            if (Tinebase_Core::isLogLevel(Zend_Log::WARN))
//                Tinebase_Core::getLogger()-&gt;warn(__METHOD__ . &#039;::&#039; . __LINE__ . &quot; update by generic client not allowed. See Tasks_Convert_Task_VCalendar_Factory for supported clients.&quot;);
//            throw new Sabre\DAV\Exception\Forbidden(&#039;Update denied for unknow client&#039;);
//        }

        if (is_resource($cardData)) {

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Jul 2016 20:08**

Hahha, contRacts... I read CONTACTS... OOps. Okay.
As per my last line above:

&quot;BTW, I also added Task support and will add that in the next few days.&quot;
This issue is known.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Jul 2016 20:14**

Changed CardDAV -&gt; Tasks and contacts -&gt; Tasks.
Contacts and calendar are fully supported, Tasks has been fixed and will be pushed in the next few days.

**Comment by Gloirin** [comment]
**Comment posted by Hennige-IT on 16 Jan 2017 18:21**

Problem is even existing, fix is even working.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 16 Jan 2017 23:37**

Fix is available, just not committed. I&#039;ll see what I can do. Have been testing for long enough I&#039;d say... ;-)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Jan 2017 09:40**

@Ingo would be great if you could commit the fix :)

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 9 Feb 2017 11:10**

https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/pull/19

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Feb 2017 09:02**

i just merged the pull request. thanks for that!
