### ISSUE TITLE
0010998:
Frequent messages because autoloader can not load LICENSE/Config.php and PRIVACY/Config.php

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5443]
**Reported by weberho on 30 Apr 2015 20:19**

**Version:** Koriander (2014.09.10)

I see many of these warnings in the logs, eg. when activcesync is used. Both messages occur together.

d41d0 343f7 -- none -- - 2015-04-30T19:40:02+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20//LICENSE/Config.php) is not within the allowed path(s): (/var/lib/tine20:/usr/share/tine20:/usr/share/php5/PEAR) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)
d41d0 343f7 -- none -- - 2015-04-30T19:40:02+00:00 WARN (4): Tinebase_Core::errorHandler::510 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;file_exists(): ...&#039;, &#039;/usr/share/tine...&#039;, 393, Array)
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(393): file_exists(&#039;/usr/share/tine...&#039;)
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(329): Composer\Autoload\ClassLoader-&gt;findFileWithExtension(&#039;LICENSE_Config&#039;, &#039;.php&#039;)
#3 /usr/share/tine20/vendor/composer/ClassLoader.php(300): Composer\Autoload\ClassLoader-&gt;findFile(&#039;LICENSE_Config&#039;)
#4 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;LICENSE_Config&#039;)
#5 [internal function]: spl_autoload_call(&#039;LICENSE_Config&#039;)
#6 /usr/share/tine20/Tinebase/Core.php(1573): class_exists(&#039;LICENSE_Config&#039;)
#7 /usr/share/tine20/Tinebase/Core.php(1608): Tinebase_Core::_searchServerPlugins()
#8 /usr/share/tine20/Tinebase/Core.php(242): Tinebase_Core::_getServerPlugins()
#9 /usr/share/tine20/Tinebase/Core.php(219): Tinebase_Core::getDispatchServer(Object(Zend\Http\PhpEnvironment\Request))
#10 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#11 {main}
d41d0 343f7 -- none -- - 2015-04-30T19:40:02+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20//PRIVACY/Config.php) is not within the allowed path(s): (/var/lib/tine20:/usr/share/tine20:/usr/share/php5/PEAR) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)
d41d0 343f7 -- none -- - 2015-04-30T19:40:02+00:00 WARN (4): Tinebase_Core::errorHandler::510 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;file_exists(): ...&#039;, &#039;/usr/share/tine...&#039;, 393, Array)
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(393): file_exists(&#039;/usr/share/tine...&#039;)
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(329): Composer\Autoload\ClassLoader-&gt;findFileWithExtension(&#039;PRIVACY_Config&#039;, &#039;.php&#039;)
#3 /usr/share/tine20/vendor/composer/ClassLoader.php(300): Composer\Autoload\ClassLoader-&gt;findFile(&#039;PRIVACY_Config&#039;)
#4 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;PRIVACY_Config&#039;)
#5 [internal function]: spl_autoload_call(&#039;PRIVACY_Config&#039;)
#6 /usr/share/tine20/Tinebase/Core.php(1573): class_exists(&#039;PRIVACY_Config&#039;)
#7 /usr/share/tine20/Tinebase/Core.php(1608): Tinebase_Core::_searchServerPlugins()
#8 /usr/share/tine20/Tinebase/Core.php(242): Tinebase_Core::_getServerPlugins()
#9 /usr/share/tine20/Tinebase/Core.php(219): Tinebase_Core::getDispatchServer(Object(Zend\Http\PhpEnvironment\Request))
#10 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
**Comment posted by weberho on 30 Apr 2015 20:57**

Found a solution: removing PRIVACY and LICENSE file removes the messages. 

Seems that the source of the problem is in the new function _searchServerPlugins() which should not add files to the list of filters.

line 1559 of Tinebase/Core.php must be:
if (ctype_upper($entry[0]) &amp;&amp; is_dir($entry)) {

instead of:
if (ctype_upper($entry[0]) {

**Comment by Gloirin** [comment]
**Comment posted by weberho on 1 May 2015 06:55**

https://gerrit.tine20.org/tine20/#/c/3096/

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2015 07:59**

Hi, thanks for the patch. I&#039;ll move it to the 2014.09 branch.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2015 08:05**

I moved the change: https://gerrit.tine20.org/tine20/3100
