### ISSUE TITLE
0011000:
Cannot accept invitation to meeting when organiser email is too long

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5444]
**Reported by ingoratsdorf on 1 May 2015 01:17**

**Version:** Koriander (2014.09.10)

When I try to accept an invitation to a meeting in my case in Lightning, the action fails due to a too long organiser email address:

exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;email string too long&#039;

However, while the email address may be slightly longer than one would normally expect, it&#039;s not overly long really...

Think the email field length should be increased. From what I can see a users email address can be max 64 chars, the one supplied in the bug trace below is 68... ;-)

Maybe 80 might be good?

**Additional information:** 1f7bb user - 2015-05-01T01:00:02+00:00 ERR (3): Calendar_Frontend_WebDAV_Event::create::127 exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;email string too long&#039; in /var/wwwroot/tine20/Calendar/Model/Attender.php:519
Stack trace:
#0 /var/wwwroot/tine20/Calendar/Model/Attender.php(450): Calendar_Model_Attender::_sanitizeEmail(&#039;productspec.net...&#039;)
#1 /var/wwwroot/tine20/Calendar/Convert/Event/VCalendar/Abstract.php(819): Calendar_Model_Attender::resolveEmailToContact(Array)
#2 /var/wwwroot/tine20/Calendar/Convert/Event/VCalendar/Abstract.php(411): Calendar_Convert_Event_VCalendar_Abstract-&gt;_convertVevent(Object(Sabre\VObject\Component\VEvent), Object(Calendar_Model_Event), Array)
#3 /var/wwwroot/tine20/Calendar/Frontend/WebDAV/Event.php(125): Calendar_Convert_Event_VCalendar_Abstract-&gt;toTine20Model(&#039;BEGIN:VCALENDAR...&#039;)
#4 /var/wwwroot/tine20/Tinebase/WebDav/Container/Abstract.php(66): Calendar_Frontend_WebDAV_Event::create(Object(Tinebase_Model_Container), &#039;mb81g4u50s1guc0...&#039;, Resource id #3)
#5 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;mb81g4u50s1guc0...&#039;, Resource id #3)
#6 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server-&gt;createFile(&#039;calendars/c2134...&#039;, Resource id #3, NULL)
#7 [internal function]: Sabre\DAV\Server-&gt;httpPut(&#039;calendars/c2134...&#039;)
#8 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;calendars/c2134...&#039;)
#9 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;calendars/c2134...&#039;)
#10 /var/wwwroot/tine20/Tinebase/Server/WebDAV.php(142): Sabre\DAV\Server-&gt;exec()
#11 /var/wwwroot/tine20/Tinebase/Core.php(221): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 /var/wwwroot/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#13 {main}
1f7bb user - 2015-05-01T01:00:02+00:00 ERR (3): Calendar_Frontend_WebDAV_Event::create::128 BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20141130T223034Z
LAST-MODIFIED:20150501T010048Z
DTSTAMP:20150501T010048Z
UID:mb81g4u50s1guc0m63v6k3d40o@google.com
SUMMARY:Paradigm Shift AKL
STATUS:CONFIRMED
ORGANIZER;CN=PS &amp; SS Events;SCHEDULE-AGENT=CLIENT:mailto:productspec.net_7
 59fok1fkb7f46rb4h0b9gqcnc@group.calendar.google.com
ATTENDEE;RSVP=TRUE;CN=user@envirology.co.nz;PARTSTAT=ACCEPTED;CUTYPE=INDIV
 IDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:user@envirology.co.nz
DTSTART:20150505T043000Z
DTEND:20150505T083000Z
DESCRIPTION:Thank you for registering for Paradigm Shift 2015! It&#039;s going
 to be a fantastic evening full of product displays\, drinks and canapés\,
  networking\, amazing prizes\, and of course an inspiring presentation fro
 m london-based Usman Haque! \n\nExclusive to Paradigm Shift in Auckland\,
 Ludo Campbell-Reid (Auckland Design Champion\, GM of Auckland Design Offic
 e) will be doing a live Q+A session with Usman following the keynote prese
 ntation.\n\nEvent Schedule:\n\n4:30pm  Arrival + registration\n4:45pm  Bro
 wse stands\n5:15pm  Exhibitor&#039;s rapid-fire presentations\n6:15pm  Browse s
 tands\n6:45pm  Keynote presentation\n7:45pm  Live Q+A with Ludo\n8:00pm  P
 rize draws\n\nTransport: The nearest parking is at the Auckland transport
 Downtown Carpark? ?on 31 Customs Street West. Alternatively\, there is
  plenty of public transport in central Auckland\, and taxis will come righ
 t to the front door of Shed 10.\n\nYour colleagues are welcome to register
  and and join you at the event - http://www.paradigm-shift.co.nz/\n\nWe lo
 ok forward to seeing you there!\nView your event at https://www.google.com
 /calendar/event?action=VIEW&amp;eid=bWI4MWc0dTUwczFndWMwbTYzdjZrM2Q0MG8gaW5nb0
 BlbnZpcm9sb2d5LmNvLm56&amp;tok=NjgjcHJvZHVjdHNwZWMubmV0Xzc1OWZvazFma2I3ZjQ2cmI
 0aDBiOWdxY25jQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20yM2I4NjQxOTEwNmUwY2RiNjEwZ
 GQ0ODNiNTAwMWI1YTgxOGM4ZTlk&amp;ctz=Pacific/Auckland&amp;hl=en.
LOCATION:Shed 10 - Cruise Ship Terminal\, 89 Quay Street\, Queens Wharf\,
 Auckland CBD\, Auckland 1010\, New Zealand
SEQUENCE:1
TRANSP:TRANSPARENT
X-MOZ-RECEIVED-SEQUENCE:1
X-MOZ-RECEIVED-DTSTAMP:20150430T232650Z
END:VEVENT
END:VCALENDAR

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2015 07:49**

hi Ingo,

I agree, we should increase the email fields.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 May 2015 11:43**

https://gerrit.tine20.org/tine20/3105
