### ISSUE TITLE
0011028:
Open_basedir error

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5458]
**Reported by Gurney on 11 May 2015 05:21**

**Version:** Koriander (2014.09.10)

Hello,

Using the Utopic package on the Velvet version of Ubuntu (not sure if related) I have many errors of this type in the logs :

9b14b f14b1 -- none -- - 2015-05-11T05:06:01+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20/../tests/setup/LICENSE/Config.php) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)

Stacktrace below.

I&#039;m currently investigating an issue, since I upgraded to Velvet, with this error :
108f2 2e9d8 equesselai - 2015-05-11T04:30:10+00:00 WARN (4): Felamimail_Controller_Message_Send::sendMessage::81 Could not send message: exception &#039;Zend_Mail_Protocol_Exception&#039; with message &#039;Unable to connect via TLS&#039; in /usr/share/tine20/library/Zend/Mail/Protocol/Smtp.php:211

I think it may be caused by the previous error.

**Additional information:** 9b14b f14b1 -- none -- - 2015-05-11T05:06:01+00:00 WARN (4): Tinebase_Core::errorHandler::510 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;file_exists(): ...&#039;, &#039;/usr/share/tine...&#039;, 393, Array)
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(393): file_exists(&#039;/usr/share/tine...&#039;)
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(329): Composer\Autoload\ClassLoader-&gt;findFileWithExtension(&#039;LICENSE_Config&#039;, &#039;.php&#039;)
#3 /usr/share/tine20/vendor/composer/ClassLoader.php(300): Composer\Autoload\ClassLoader-&gt;findFile(&#039;LICENSE_Config&#039;)
#4 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;LICENSE_Config&#039;)
#5 [internal function]: spl_autoload_call(&#039;LICENSE_Config&#039;)
#6 /usr/share/tine20/Tinebase/Core.php(1573): class_exists(&#039;LICENSE_Config&#039;)
#7 /usr/share/tine20/Tinebase/Core.php(1608): Tinebase_Core::_searchServerPlugins()
#8 /usr/share/tine20/Tinebase/Core.php(242): Tinebase_Core::_getServerPlugins()
#9 /usr/share/tine20/Tinebase/Core.php(219): Tinebase_Core::getDispatchServer(Object(Zend\Http\PhpEnvironment\Request))
#10 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#11 {main}

**Comment by Gloirin** [comment]
Related to #5443

**Comment by Gloirin** [comment]
**Comment posted by weberho on 11 May 2015 06:29**

The solution from #10998 should fix that problem. To the developers: In openSUSEs RPM packages I have additionally used the attached patch to disable searching in the test-libraries. Don&#039;t know if this wouldn&#039;t be useful for all the distribution packages.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 11 May 2015 20:47**

Thanks, I tried your patch but I still get these errors:

b00ce 5db43 -- none -- - 2015-05-11T20:43:33+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20/CREDITS/Config.php) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)

0d190 c6eb6 -- none -- - 2015-05-11T20:54:01+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20/PRIVACY/Config.php) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)

0d190 c6eb6 -- none -- - 2015-05-11T20:54:01+00:00 WARN (4): Tinebase_Core::errorHandler::509 file_exists(): open_basedir restriction in effect. File(/usr/share/tine20/LICENSE/Config.php) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)

**Comment by Gloirin** [comment]
**Comment posted by weberho on 11 May 2015 22:10**

Did you also change the line as explained in #0010998 ? This should fix the reason for the message, the patch attached is something additional.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 12 May 2015 04:28**

Yep, thanks, indeed I missed that, that made the trick.

Cheers!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 May 2015 16:15**

hi,

&gt; To the developers: In openSUSEs RPM packages I have additionally used the 
&gt; attached patch to disable searching in the test-libraries. Don&#039;t know if this 
&gt; wouldn&#039;t be useful for all the distribution packages.

I&#039;ll have a look. thanks!

**Comment by Gloirin** [comment]
**Comment posted by Ying on 2 Jun 2015 08:23**

I got the following error, using the patch attached by weberho fixed it.
Version: 2014.09.12 (Ubuntu)

[Tue Jun 02 10:10:56.406125 2015] [:error] [pid 32051] [client 192.168.0.29:50194] Tinebase_Core::errorHandler::513 is_file(): open_basedir restriction in effect. File(/usr/share/tine20/../tests/setup/Timetracker/Config.php) is not within the allowed path(s): (/usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20) in /usr/share/tine20/vendor/composer/ClassLoader.php::393 (2)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Jun 2015 14:08**

i think, we need to update the composer.json file before the build to make sure we have the correct autoloader setup. I&#039;ll discuss this with the team and we&#039;ll fix this for the next release.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Jun 2015 11:37**

we discussed this and plan to solve this in the following way:

- remove the test paths from the autoloader config in composer.json
- add the test paths only when needed (in the tests bootstrap)
