### ISSUE TITLE
0011030:
Ldap plugin error: no user object found

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5459]
**Reported by Gurney on 11 May 2015 20:44**

**Version:** Koriander (2014.09.10)

Hello,

I have many errors of this type, related to LDAP (stack trace below):
c0a44 equesselai - 2015-05-11T19:15:08+00:00 WARN (4): Tinebase_Core::errorHandler::509 Creating default object from empty value in /usr/share/tine20/Tinebase/User/Plugin/LdapAbstract.php::106 (2)

I think it may be caused by something like this:
http://stackoverflow.com/questions/8900701/creating-default-object-from-empty-value-in-php

**Additional information:** c0a44 equesselai - 2015-05-11T19:15:08+00:00 WARN (4): Tinebase_Core::errorHandler::510 #0 /usr/share/tine20/Tinebase/User/Plugin/LdapAbstract.php(106): Tinebase_Core::errorHandler(2, &#039;Creating defaul...&#039;, &#039;/usr/share/tine...&#039;, 106, Array)
#1 /usr/share/tine20/Tinebase/User/Ldap.php(334): Tinebase_User_Plugin_LdapAbstract-&gt;inspectGetUserByProperty(Object(Tinebase_Model_FullUser), Array)
#2 /usr/share/tine20/Tinebase/User/Sql.php(226): Tinebase_User_Ldap-&gt;getUserByPropertyFromSyncBackend(&#039;accountId&#039;, Object(Tinebase_Model_FullUser), &#039;Tinebase_Model_...&#039;)
#3 /usr/share/tine20/Tinebase/User/Abstract.php(563): Tinebase_User_Sql-&gt;getUserByProperty(&#039;accountId&#039;, &#039;1000&#039;, &#039;Tinebase_Model_...&#039;)
#4 /usr/share/tine20/Tinebase/User/Sql.php(325): Tinebase_User_Abstract-&gt;getUserById(&#039;1000&#039;, &#039;Tinebase_Model_...&#039;)
#5 /usr/share/tine20/Felamimail/Controller/Account.php(966): Tinebase_User_Sql-&gt;getFullUserById(&#039;1000&#039;)
#6 /usr/share/tine20/Felamimail/Controller/Account.php(943): Felamimail_Controller_Account-&gt;_addConfigValuesToAccount(Object(Felamimail_Model_Account), &#039;sieve&#039;, Array, Array)
#7 /usr/share/tine20/Felamimail/Controller/Account.php(166): Felamimail_Controller_Account-&gt;_addSystemAccountConfigValues(Object(Felamimail_Model_Account))
#8 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(1278): Felamimail_Controller_Account-&gt;get(&#039;f6cb565c5b5e0b5...&#039;)
#9 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(284): Felamimail_Controller_Cache_Message-&gt;_updateFolderQuota(Object(Felamimail_Model_Folder), Object(Felamimail_Backend_ImapProxy))
#10 /usr/share/tine20/Felamimail/Frontend/ActiveSync.php(674): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;c6733739db37273...&#039;, 10)
#11 /usr/share/tine20/ActiveSync/Frontend/Abstract.php(669): Felamimail_Frontend_ActiveSync-&gt;_inspectGetCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#12 /usr/share/tine20/ActiveSync/Frontend/Abstract.php(687): ActiveSync_Frontend_Abstract-&gt;getCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#13 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Command/Ping.php(167): ActiveSync_Frontend_Abstract-&gt;hasChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#14 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(143): Syncroton_Command_Ping-&gt;handle()
#15 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()
#16 /usr/share/tine20/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#17 /usr/share/tine20/Tinebase/Core.php(221): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#18 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#19 {main}

**Comment by Gloirin** [comment]
Related to #5481

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 12 May 2015 04:44**

Adding :

$user = new stdClass();

before line 106
$user-&gt;emailUsername = $this-&gt;_getEmailUserName($_user);

solved the issue.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 May 2015 19:13**

hi,

thanks for the bugreport and the hint for solving this. i just committed a fix to our gerrit review system.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2015 07:39**

there still seems to be a problem with this. see #11076

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2015 17:27**

i hope, this is fixed, too. if not, please reopen.
