### ISSUE TITLE
0011054:
Problems with ScheduledImport of external ics calendars

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5470]
**Reported by hedo on 21 May 2015 07:19**

**Version:** Koriander (2014.09.10)

I want to use the scheduled import from remote ics files in Tine20. I found some problems here:

1) The import of some calendars dont work. For example:
http://mozorg.cdn.mozilla.net/media/caldata/DutchHolidays.ics
When I place this ics file on my own webserver: http://courtz.nl/tine20/DutchHolidays.ics
it works OK. When I download the file to my computer, and I do a manual import it works OK too in Tine20.

Debug info:
57edd cronuser - 2015-05-21T06:30:03+00:00 WARN (4): Tinebase_Core::errorHandler::509 gzinflate(): data error in /usr/share/tine20/library/Zend/Http/Response.php::609 (2)
57edd cronuser - 2015-05-21T06:30:03+00:00 WARN (4): Tinebase_Core::errorHandler::510 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;gzinflate(): da...&#039;, &#039;/usr/share/tine...&#039;, 609, Array)
#1 /usr/share/tine20/library/Zend/Http/Response.php(609): gzinflate(&#039;DutchHolidays.i...&#039;)
#2 /usr/share/tine20/library/Zend/Http/Response.php(275): Zend_Http_Response::decodeGzip(&#039;??????????Dutch...&#039;)
#3 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(157): Zend_Http_Response-&gt;getBody()
#4 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(184): Tinebase_Controller_ScheduledImport-&gt;_getFileToImport(&#039;http://mozorg.c...&#039;)
#5 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(68): Tinebase_Controller_ScheduledImport-&gt;_doScheduledImport(Object(Tinebase_Model_Import))
#6 [internal function]: Tinebase_Controller_ScheduledImport-&gt;runNextScheduledImport()
#7 /usr/share/tine20/Tinebase/Scheduler/Task.php(283): call_user_func_array(Array, Array)
#8 /usr/share/tine20/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
#9 /usr/share/tine20/Tinebase/Frontend/Cli.php(121): Zend_Scheduler-&gt;run()
#10 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#11 /usr/share/tine20/Tinebase/Frontend/Cli.php(85): call_user_func(Array, Object(Zend_Console_Getopt))
#12 /usr/share/tine20/Tinebase/Server/Cli.php(94): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#13 /usr/share/tine20/Tinebase/Core.php(221): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#14 /usr/sbin/tine20-cli(75): Tinebase_Core::dispatchRequest()
#15 {main}
57edd cronuser - 2015-05-21T06:30:03+00:00 INFO (6): Tinebase_Controller_ScheduledImport::_doScheduledImport 220 The source could not be loaded: http://mozorg.cdn.mozilla.net/media/caldata/DutchHolidays.ics

2) Existing events which are modified in the remote calendar are never updated in Tine20. The following line is reported in the log: Calendar_Import_Ical::import 208  totalcount: 0 / duplicates: 50 / fails: 0 When I manual set forceUpdateExisting=TRUE I get Permission denied errors, and Container id is NULL or something. Solved this problem by deleting events in a calendar before do the import in Calendar\Import\Ical.php, but seems not best practice to me?

3) Only one calendar is updating every minute instead of all calendars weekly. After research it seems to me that there is a little glitch in the database query filter. 

In &quot; \Tinebase\Controller\ScheduledImport.php&quot; is the following filter defined:
Line 96:
$filter = new Tinebase_Model_ImportFilter(array(), &#039;OR&#039;);
Blahblah  extra filters added, then line 129:
$record = $this-&gt;search($filter, $pagination)-&gt;getFirstRecord();

Somewhere else in Tine20 a extra item is added to the WHERE clause: WHERE import.isdeleted=0 OR .. and here after the results of the filter above. Because import.isdeleted=0 OR have always a result, regardless of the timestamp column, the task is running every minute. I changed the filter a little, and now it is working fine for me:
$filter = new Tinebase_Model_ImportFilter(array(), &#039;OR&#039;); &lt; not changed

$filter4 = new Tinebase_Model_ImportFilter(array(), &#039;AND&#039;); &lt; extra above line 129
	$filter4-&gt;addFilterGroup($filter);

$record = $this-&gt;search($filter4, $pagination)-&gt;getFirstRecord();
So the query is changed: WHERE import.isdeleted=0 AND (here the timestamp filter things)

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 4 Nov 2016 11:28**

Thanks for the report.

#1 fix: http://gerrit.tine20.com/customers/3730
#2 already fixed
#3 already fixed

in future, please have one issue with expressive summary per problem.
