### ISSUE TITLE
0011060:
Erstinstallation: Fehler durch cronjob tine20-cli: "tine20.tine20_accounts' doesn't exist"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5473]
**Reported by tomm on 22 May 2015 12:55**

**Version:** Koriander (2014.09.10)

Nach einer Erstinstallation von Tine aus dem Ubuntu Repository &quot;deb https://packages.tine20.org/ubuntu utopic stable&quot; erszeugt der angelegte Cron-Job 
&quot;... /usr/sbin/tine20-cli --method=Tinebase.triggerAsyncEvents | logger -p daemon.notice -t &quot;Tine 2.0 scheduler&quot; 

im Sekundentakt Mails mit dem Inhalt:
&quot;PHP Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_accounts&#039; doesn&#039;t exist&#039; in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /usr/share/tine20/Zend/Db/Select.php(674): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /usr/share/tine20/Tinebase/User/Sql.php(280): Zend_Db_Select-&gt;query()
#5 /usr/share/tine20/Tinebase/User/Sql.php(210): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountLoginNam...&#039;, NULL, &#039;Tinebase_Model_...&#039;)
#6 /usr/share/tine20/Tinebase/User/Abstract.php(549): Tinebase_User_Sql-&gt;getUserByProperty(&#039;accountLoginNam...&#039;, NULL, &#039;Tinebase_Model_.. in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php on line 238&quot;

Sonst ist auf den ersten Blick alles funktionsfähig. Die Tabelle existiert, ist mit den angelegten Benutzern gefüllt und diese können sich auch anmelden.

**Steps to reproduce:** Per apt-get installieren + Benutzer anlegen.
Kurz auf den Cronjob warten und dann root-Mails abrufen. 

**Additional information:** Webserver: nginx

**Comment by Gloirin** [comment]
**Comment posted by tomm on 25 May 2015 04:08**

Das Problem ist gelöst. Mit dem Ubuntu-Paket wird automatisch eine Datenbank/User &quot;tine20&quot; angelegt. Das wird aber nicht ausgegeben. Die Daten dazu werden unter /etc/tin20/config.inc.php gespeichert. Das nicht wissen habe ich m anschließenden Setup-Dialog von Tine eine eigene DB und USER angegeben. Und abgespeichert. Die dort erfassten Daten wurden in $webroot/tine20/config.inc.php gespeichert. Die Tine-GUI zieht sich nun Daten aus $webroot/tine20/config.inc.php und funktioniert problemlos.

Das cli nimmt aber die Daten aus /etc/tin20/config.inc.php. Die erstellte &quot;tine20&quot; Datenbank wurde aber nie mit Tabellen gefüllt, dort hatte ich bereits meine eigene angegeben. Und schon sind wir bei der Fehlermeldung :-)
