### ISSUE TITLE
0011074:
Active Directory as User Backend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5480]
**Reported by konus on 29 May 2015 12:10**

**Version:** Koriander (2014.09.10)

I try to use Active Directory of Windows Server 2008R2 as (readonly) user backend.
After the first sync of accounts from Active Directory to SQL Database, login to tine20 fails with the following error:

Tinebase_Controller::_getLoginUser::128 Failed to sync user data for: tineadmin reason: DateTime::__construct(): Failed to parse time string (@1431981744.1237094000) at position 19 (0): Unexpected character

I found an older entry with the same error message but in an other context: https://forge.tine20.org/view.php?id=4460 - I don&#039;t think they are related.

**Additional information:** Forum Discussion: https://www.tine20.org/forum/viewtopic.php?p=54806#p54806

Logfile Exerpt:

DEBUG (7): Tinebase_User::getInstance::169 accounts backend: ActiveDirectory
INFO (6): Tinebase_User::factory::242 Created user backend of type ActiveDirectory
INFO (6): Tinebase_User::syncUser::442  sync user data for: tineadmin
DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::632 filter (&amp;(objectclass=user)(samaccountname=tineadmin))
CRIT (2): Tinebase_Controller::_getLoginUser::128 Failed to sync user data for: tineadmin reason: DateTime::__construct(): Failed to parse time string (@1431981744.1237094000) at position 19 (0): Unexpected character
ERR (3): Tinebase_Exception::log::104 Exception -&gt; DateTime::__construct(): Failed to parse time string (@1431981744.1237094000) at position 19 (0): Unexpected character

**Comment by Gloirin** [comment]
**Comment posted by konus on 29 May 2015 12:15**

Schemaversion: Windows Server 2008 R2 mit allen Service Packs = 47

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Jun 2015 08:50**

hi,

could you please extract the ldif of the tineadmin user object?

it looks like that we need to convert this date string (&quot;@1431981744.1237094000&quot;) to a format that is understood by tine20.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Jun 2015 08:51**

maybe we could skip the attribute in the first place to allow the sync to continue.

a full stacktrace would be helpful, too.

**Comment by Gloirin** [comment]
**Comment posted by konus on 24 Jun 2015 10:08**

The extracted ldif of tineadmin is attached as file.

The stacktrace looks like this:
[18-Jun-2015 09:38:07 UTC] PHP Fatal error:  Uncaught exception &#039;Exception&#039; with message &#039;DateTime::__construct(): Failed to parse time string (@1391776840.7434058000) at position 19 (0): Unexpected character&#039; in C:\xampp\htdocs\tine20\Tinebase\DateTime.php:108
Stack trace:
#0 C:\xampp\htdocs\tine20\Tinebase\DateTime.php(108): DateTime-&gt;__construct(&#039;@1391776840.743...&#039;)
#1 C:\xampp\htdocs\tine20\Tinebase\User\ActiveDirectory.php(451): Tinebase_DateTime-&gt;__construct(&#039;1391776840.7434...&#039;)
#2 C:\xampp\htdocs\tine20\Tinebase\User\Ldap.php(330): Tinebase_User_ActiveDirectory-&gt;_ldap2User(Array, &#039;Tinebase_Model_...&#039;)
#3 C:\xampp\htdocs\tine20\Tinebase\User\Sql.php(226): Tinebase_User_Ldap-&gt;getUserByPropertyFromSyncBackend(&#039;accountId&#039;, Object(Tinebase_Model_FullUser), &#039;Tinebase_Model_...&#039;)
#4 C:\xampp\htdocs\tine20\Tinebase\User\Abstract.php(549): Tinebase_User_Sql-&gt;getUserByProperty(&#039;accountLoginNam...&#039;, &#039;kbau&#039;, &#039;Tinebase_Model_...&#039;)
#5 C:\xampp\htdocs\tine20\Tinebase\User\Abstract.php(292): Tinebase_User_Abstract-&gt;getUserByLoginName(&#039;kbau&#039;, &#039;Tinebase_Model_.. in C:\xampp\htdocs\tine20\Tinebase\DateTime.php on line 108

(Disclaimer: I am not 100% sure about the stacktrace, because I changed my config back to mysql-auth.)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Jun 2015 10:15**

thanks! I&#039;ll have a look. this should be easy to fix.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jun 2015 12:34**

i found the problem. somehow the converted timestamp (windows timestamp -&gt; unix timestamp) is no integer but a float number:
1391776840.7434058000

when we create a datetime object, this fails. so i added a small patch for converting the float to an integer:

--- tine20/Tinebase/DateTime.php	(revision c96b13728793449585afc532d83d5872cb1da006)
+++ tine20/Tinebase/DateTime.php	(revision )
@@ -95,7 +95,7 @@
             
             $time = $_time-&gt;format(&quot;Y-m-d H:i:s&quot;);
         } else {
-            $time = (is_numeric($_time)) ? &quot;@&quot; . $_time : $_time;
+            $time = (is_numeric($_time)) ? &quot;@&quot; . floor($_time) : $_time;
         }
         
         if ($_timezone) {
