### ISSUE TITLE
0011156:
big files can't be uploaded

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5521]
**Reported by pschuele on 16 Jul 2015 11:39**

**Version:** Collin (2013.10.8)

files bigger than ~3 GB throw an error on upload. the size field in the tempfile record is negative :(

**Additional information:** 3e86f 087e2 vagrant - 2015-07-09T08:55:29+00:00 WARN (4): 
Tinebase_Server_Json::_handleException::325 Zend_Db_Statement_Exception -&gt; 
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for 
column &#039;size&#039; at row 1
3e86f 087e2 vagrant - 2015-07-09T08:55:29+00:00 ERR (3): 
Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[22003]: 
Numeric value out of range: 1264 Out of range value for column &#039;size&#039; at row 
1
3e86f 087e2 vagrant - 2015-07-09T08:55:29+00:00 ERR (3): 
Tinebase_Exception::log::121 #0 .../library/Zend/Db/Statement.php(284): 
Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-
&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): 
Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 .../library/Zend/Db/Adapter/Abstract.php(546): 
Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 .../Tinebase/Backend/Sql/Abstract.php(945): Zend_Db_Adapter_Abstract-
&gt;insert(&#039;tine20_temp_fil...&#039;, Array)
#5 .../Tinebase/TempFile.php(222): Tinebase_Backend_Sql_Abstract-
&gt;create(Object(Tinebase_Model_TempFile))
#6 .../Tinebase/TempFile.php(253): Tinebase_TempFile-
&gt;createTempFile(&#039;/tmp/tine_tempf...&#039;, &#039;IE11.Win7.For.L...&#039;, 
&#039;application/zip&#039;)
#7 .../Tinebase/Frontend/Json.php(1189): Tinebase_TempFile-
&gt;joinTempFiles(Object(Tinebase_Record_RecordSet))
#8 [internal function]: Tinebase_Frontend_Json-&gt;joinTempFiles(Array)
#9 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array,

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Jul 2015 14:39**

seems to be a problem on 32bit systems only (see PHP_INT_SIZE)
