### ISSUE TITLE
0011174:
Can not create user when visibility is set to "do not show in address-book"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5529]
**Reported by weberho on 24 Jul 2015 12:51**

**Version:** Elena (2015.07.1)

After saving a the user I get a error message and the following log-entries:

972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Model_Filter_Abstract::_getQuotedFieldName::317 Using tablename: config
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_fetch::739 SELECT `config`.* FROM `tine20_config` AS `config` WHERE ((`config`.`application_id` = &#039;33a59a194184c5d477ed59d7b1ae52233dcd84d8&#039;))
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::522 Found 0 configs.
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::523 Array
(
)

972b4 69fd7 web - 2015-07-24T12:43:49+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::298 Using application name is deprecated. Please use the classname of the model or the class itself.
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::337 Params: application: Addressbook / model: 
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::357 Extracted appName: Addressbook modelName: 
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::366 controllerName: Addressbook_Controller
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::390 Getting instance of Addressbook_Controller
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::783 *
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 TRACE (8): Tinebase_TransactionManager::rollBack::136  rollBack request, rollBack all transactionables
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 ERR (3): Admin_Controller_User::create::287 Container Internal Contacts not found.
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 DEBUG (7): Admin_Controller_User::create::288 #0 /usr/share/tine20/Addressbook/Setup/Initialize.php(261): Tinebase_Container-&gt;getContainerByName(&#039;Addressbook&#039;, &#039;Internal Contac...&#039;, &#039;shared&#039;)
#1 /usr/share/tine20/Admin/Controller/User.php(420): Addressbook_Setup_Initialize::setDefaultInternalAddressbook()
#2 /usr/share/tine20/Admin/Controller/User.php(440): Admin_Controller_User-&gt;getDefaultInternalAddressbook()
#3 /usr/share/tine20/Admin/Controller/User.php(271): Admin_Controller_User-&gt;createOrUpdateContact(Object(Tinebase_Model_FullUser))
#4 /usr/share/tine20/Admin/Frontend/Json.php(372): Admin_Controller_User-&gt;create(Object(Tinebase_Model_FullUser), &#039;asd&#039;, &#039;asd&#039;)
#5 [internal function]: Admin_Frontend_Json-&gt;saveUser(Array)
#6 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 /usr/share/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 /usr/share/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#11 /usr/share/tine20/Tinebase/Core.php(221): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#13 {main}
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_NotFound -&gt; Container Internal Contacts not found.
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; Container Internal Contacts not found.
972b4 69fd7 web - 2015-07-24T12:43:49+00:00 INFO (6): index.php (25) METHOD: Tinebase_Server_Json::Admin.saveUser / TIME: 187ms /  Memory usage: 13.25 MB /  Real patch cache size: 0 / PID: 8586

**Comment by Gloirin** [comment]
Related to #6312

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Jul 2015 09:26**

hi,

I could not reproduce the problem on a fresh installation. there might be a problem with your default &quot;Internal Contacts&quot;-addressbook container.

I&#039;ll try to fix this by adding a new default container on the fly as suggested in the TODO for function Addressbook_Setup_Initialize::setDefaultInternalAddressbook
