### ISSUE TITLE
0011204:
After upgrade to 2015.07.2: Exception in Pdo.php

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5544]
**Reported by TwizzyDizzy on 7 Aug 2015 14:39**

**Version:** Elena (2015.07.2)

Hi folks,

after upgrading to 2015.07.2 (from 2015.07.1) I see these errors in my logfile:

-------------------------------
[Fri Aug 07 16:20:25.986109 2015] [:error] [pid 6656] [client 91.65.208.152:37511] PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;cal_events.base_event_id&#039; in &#039;where clause&#039;&#039; in /path/to/tine20/library/Zend/Db/Statement/Pdo.php:238\nStack trace:\n#0 /path/to/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)\n#1 /path/to/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)\n#2 /path/to/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)\n#3 /path/to/tine20/Calendar/Backend/Sql.php(227): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))\n#4 /path/to/tine20/Tinebase/Controller/Record/Abstract.php(208): Calendar_Backend_Sql-&gt;search(Object(Calendar_Model_EventFilter), NULL, false)\n#5 /path/to/tine20/Calendar/Controller/Event.php(4 in /path/to/tine20/library/Zend/Db/Statement/Pdo.php on line 238, referer: https://my.domain/office/webdav/Calendar/[...]
-------------------------------

Any clues as to what might be the reason? To me it seems like some SQL migration may have failed?

Cheers
Thomas

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 7 Aug 2015 14:40**

One addition: this leads to failing CalDAV.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Aug 2015 16:36**

yup, the column should have been added in a migration script.

I uploaded the missing/patched files:
Calendar/Setup/Update/Release9.php
Calendar/Setup/setup.xml

please put the files in place and run the update scripts again. as this could be a major blocker in many installations, expect a new service release soon ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Aug 2015 16:46**

for the gerrit guys: https://gerrit.tine20.org/tine20/3182

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 7 Aug 2015 16:48**

Hi Philipp,

thanks for your feedback - especially your speed.

I just put the files in place and ran

  php setup.php --update

Feedback was

  &quot;Updated 1 application(s).&quot;

CalDAV is now working again, no further errors in the logfile. So this seems to have done the trick :)

Thanks!

Cheers
Thomas

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Aug 2015 17:22**

hi Thomas,

thanks for reporting and testing :)

cheers!
