### ISSUE TITLE
0011216:
Calendar events disappear from device (CalDAV)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5550]
**Reported by adrian on 10 Aug 2015 10:01**

Alright, back to the original problem :)

After creating an event via CalDAV (f.e. from Android device), the Event disappears after next sync.

**Steps to reproduce:** Create an event on a CalDAV device, sync to server.
Event is seen in WebUI on server.
Resync device, Event is gone in CalDAV.
Sync in ActiveSync - Event is there, but others are missing...

Another way I just found out:
Create an event from WebUI that is repeating, then try to delete the whole thing :)

**Additional information:** Following error I am getting from adb logcat:
W/System.err(29578): org.dmfs.m.d: no calendar data returned for https://tineserver/calendars/08c8b81aa82fa50a13e9903d7f33791ff36ddc68/11/19638670-15c8-4f8f-86cd-fa9e0cddd476
W/System.err(29578):    at org.dmfs.g.e.j(Unknown Source)
W/System.err(29578):    at org.dmfs.g.e.i(Unknown Source)
W/System.err(29578):    at org.dmfs.b.f.a(Unknown Source)
W/System.err(29578):    at org.dmfs.b.f.&lt;init&gt;(Unknown Source)
W/System.err(29578):    at org.dmfs.b.l.d(Unknown Source)
W/System.err(29578):    at org.dmfs.m.g.c(Unknown Source)
W/System.err(29578):    at org.dmfs.m.g.c(Unknown Source)
W/System.err(29578):    at org.dmfs.m.g.a(Unknown Source)
W/System.err(29578):    at org.dmfs.caldav.syncadapter.a.a(Unknown Source)
W/System.err(29578):    at org.dmfs.n.a.onPerformSync(Unknown Source)
W/System.err(29578):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

Following error happens on server when I try to sync:
[Mon Aug 10 11:43:31.123418 2015] [:error] [pid 6615] [client 127.0.0.1:64591] PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;cal_events.base_event_id&#039; in &#039;where clause&#039;&#039; in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /usr/share/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/share/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/share/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /usr/share/tine20/Calendar/Backend/Sql.php(227): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(208): Calendar_Backend_Sql-&gt;search(Object(Calendar_Model_EventFilter), NULL, false)
#5 /usr/share/tine20/Calendar/Controller/Event.php(413): Tinebase_Controller_Record_Abstract-&gt;search(Object(Calendar_Model_EventFilter), NULL, false, false, &#039;sync&#039;)
#6 /usr/share/tine20/Calendar/Controller/ in /usr/share/tine20/library/Zend/Db/Statement/Pdo.php on line 238

I also created DEBUG Logfiles, but they don&#039;t seem to contain anything interesting...

But when I try to delete a repeating event, I get the following:
SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;cal_events.base_event_id&#039; in &#039;where clause&#039;
.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../Calendar/Backend/Sql.php(227): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Calendar/Controller/Event.php(1236): Calendar_Backend_Sql-&gt;search()
.../Calendar/Controller/Event.php(1312): Calendar_Controller_Event-&gt;getRecurExceptions()
.../Calendar/Controller/Event.php(1383): Calendar_Controller_Event-&gt;adoptAlarmTime()
.../Tinebase/Controller/Record/Abstract.php(1759): Calendar_Controller_Event-&gt;_inspectAlarmSet()
.../Tinebase/Controller/Record/Abstract.php(1041): Tinebase_Controller_Record_Abstract-&gt;_saveAlarms()
.../Tinebase/Controller/Record/Abstract.php(906): Tinebase_Controller_Record_Abstract-&gt;_setRelatedData()
.../Calendar/Controller/Event.php(530): Tinebase_Controller_Record_Abstract-&gt;update()
.../Calendar/Controller/Event.php(864): Calendar_Controller_Event-&gt;update()
.../Calendar/Frontend/Json.php(429): Calendar_Controller_Event-&gt;updateRecurSeries()
[internal function]: Calendar_Frontend_Json-&gt;updateRecurSeries()
.../library/Zend/Server/Abstract.php(232): call_user_func_array()
.../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle()
.../Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle()
.../Tinebase/Core.php(221): Tinebase_Server_Json-&gt;handle()
.../index.php(18): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
Related to #5544

**Comment by Gloirin** [comment]
**Comment posted by adrian on 10 Aug 2015 10:03**

Ah damn I just am seeing, it has to do with 11204...

Yeah is the same problem - but I am investigating further why one event is still missing in ActiveSync - that seems to be something else, so please wait before closing!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Aug 2015 10:13**

&gt; Ah damn I just am seeing, it has to do with 11204...

yup, that&#039;s the missing update script. i think, the ActiveSync problem is the same thing.

i&#039;ll delete the log.zip.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 10 Aug 2015 10:24**

Okay, the missing recurring events seem to be an Outlook problem as I was able to sync all events with an Android device.

I won&#039;t blame you for the mess of Microsoft :) That is not your fault.

After deleting and recreating the account in Outlook, the missing events were there again. FU Microsoft.

(It&#039;s more funny afterwards I guess ...) :)

Thanks for your support! I will highly recommend Tine!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Nov 2015 12:07**

closing this issue.
