### ISSUE TITLE
0011246:
Can not modify some time-accounts and time-sheets

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5565]
**Reported by weberho on 19 Aug 2015 12:37**

**Version:** Elena (2015.07.3)

Upon saving of some modified time-accounts, I see the following warning in the browser: &quot;Ihre Eingabedaten sind ungültig. Bitte tragen Sie korrekte Daten ein.
Server-Nachricht: Some fields modification_time have invalid content&quot;

The same message appears when I try to update a just created time-sheet.

**Additional information:** fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Timemachine_ModificationLog::writeModLog::567 CurRecord: Array
(
    [id] =&gt; d215bc52ef111417ebee7e50feb38b617f0141ac
    [container_id] =&gt; 11
    [title] =&gt; Servicearbeiten (Regiestunden)
    [number] =&gt; FSW-Service
    [description] =&gt; 
    [budget] =&gt; 
    [budget_unit] =&gt; hours
    [price] =&gt; 95
    [price_unit] =&gt; Stunden
    [is_open] =&gt; 1
    [is_billable] =&gt; 1
    [billed_in] =&gt; 
    [status] =&gt; not yet billed
    [created_by] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [creation_time] =&gt; 2009-12-22 19:44:04
    [last_modified_by] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [last_modified_time] =&gt; 2010-01-03 08:44:10
    [is_deleted] =&gt; 0
    [deleted_by] =&gt; 
    [deleted_time] =&gt; 
    [deadline] =&gt; 
    [seq] =&gt; 1
    [cleared_at] =&gt; 
    [invoice_id] =&gt; 
    [grants] =&gt; Array
        (
        )

    [tags] =&gt; Array
        (
        )

    [relations] =&gt; Array
        (
        )

    [attachments] =&gt; Array
        (
        )

    [notes] =&gt; Array
        (
        )

)
fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Timemachine_ModificationLog::writeModLog::569 NewRecord: Array
(
    [id] =&gt; d215bc52ef111417ebee7e50feb38b617f0141ac
    [container_id] =&gt; 11
    [title] =&gt; Servicearbeiten (Regiestunden)
    [number] =&gt; FSW-Service
    [description] =&gt; 
    [budget] =&gt; 0
    [budget_unit] =&gt; hours
    [price] =&gt; 95
    [price_unit] =&gt; Stunden
    [is_open] =&gt; 1
    [is_billable] =&gt; 1
    [billed_in] =&gt; 
    [status] =&gt; not yet billed
    [created_by] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [creation_time] =&gt; 2009-12-22 19:44:04
    [last_modified_by] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [last_modified_time] =&gt; 2015-08-19 12:31:00
    [is_deleted] =&gt; 0
    [deleted_by] =&gt; 
    [deleted_time] =&gt; 
    [deadline] =&gt; none
    [seq] =&gt; 2
    [cleared_at] =&gt; 
    [invoice_id] =&gt; 
    [grants] =&gt; Array
        (
        )

    [tags] =&gt; Array
        (
        )

    [attachments] =&gt; Array
        (
        )

    [relations] =&gt; Array
        (
        )

)
fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Timemachine_ModificationLog::writeModLog::571 Common modlog: Array
(
    [application_id] =&gt; 099b2096c86573305067a1fb755cd265ad1c501d
    [record_id] =&gt; d215bc52ef111417ebee7e50feb38b617f0141ac
    [record_type] =&gt; Timetracker_Model_Timeaccount
    [record_backend] =&gt; Sql
    [modification_time] =&gt; 2015-08-19 12:31:00
    [modification_account] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [seq] =&gt; 2
)

fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Timemachine_ModificationLog::_loopModifications::643 Field &#039;deadline&#039; changed.
fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Timemachine_ModificationLog::_loopModifications::645 Change: from &#039;&#039; to &#039;none&#039;
fa50d 19850 web - 2015-08-19T12:31:00+00:00 ERR (3): Tinebase_Record_Abstract::isValid::557 Some fields modification_time have invalid contentArray
(
    [0] =&gt; Array
        (
            [id] =&gt; modification_time
            [msg] =&gt; Array
                (
                    [notEmptyInvalid] =&gt; Invalid type given, value should be float, string, or integer
                )

        )

)

fa50d 19850 web - 2015-08-19T12:31:00+00:00 DEBUG (7): Tinebase_Record_Abstract::isValid::560 Record: Array
(
    [application_id] =&gt; 099b2096c86573305067a1fb755cd265ad1c501d
    [record_id] =&gt; d215bc52ef111417ebee7e50feb38b617f0141ac
    [record_type] =&gt; Timetracker_Model_Timeaccount
    [record_backend] =&gt; Sql
    [modification_time] =&gt; 2015-08-19 12:31:00
    [modification_account] =&gt; 3d40322c70b1ca136246a61890ae1fee616a027d
    [seq] =&gt; 2
    [modified_attribute] =&gt; deadline
    [old_value] =&gt; 
    [new_value] =&gt; none
)
fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_TransactionManager::rollBack::136  rollBack request, rollBack all transactionables
fa50d 19850 web - 2015-08-19T12:31:00+00:00 INFO (6): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::638 Some fields modification_time have invalid content
fa50d 19850 web - 2015-08-19T12:31:00+00:00 TRACE (8): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::639 #0 /usr/share/tine20/Tinebase/Timemachine/ModificationLog.php(258): Tinebase_Record_Abstract-&gt;isValid(true)
#1 /usr/share/tine20/Tinebase/Timemachine/ModificationLog.php(652): Tinebase_Timemachine_ModificationLog-&gt;setModification(Object(Tinebase_Model_ModificationLog))
#2 /usr/share/tine20/Tinebase/Timemachine/ModificationLog.php(575): Tinebase_Timemachine_ModificationLog-&gt;_loopModifications(Array, Object(Tinebase_Model_ModificationLog), Object(Tinebase_Record_RecordSet), Array, Array)
#3 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(1012): Tinebase_Timemachine_ModificationLog-&gt;writeModLog(Object(Timetracker_Model_Timeaccount), Object(Timetracker_Model_Timeaccount), &#039;Timetracker_Mod...&#039;, &#039;Sql&#039;, &#039;d215bc52ef11141...&#039;)
#4 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(910): Tinebase_Controller_Record_Abstract-&gt;_writeModLog(Object(Timetracker_Model_Timeaccount), Object(Timetracker_Model_Timeaccount))
#5 /usr/share/tine20/Timetracker/Controller/Timeaccount.php(153): Tinebase_Controller_Record_Abstract-&gt;update(Object(Timetracker_Model_Timeaccount), true)
#6 [internal function]: Timetracker_Controller_Timeaccount-&gt;update(Object(Timetracker_Model_Timeaccount))
#7 /usr/share/tine20/Tinebase/Frontend/Json/Abstract.php(250): call_user_func_array(Array, Array)
#8 /usr/share/tine20/Timetracker/Frontend/Json.php(303): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Timetracker_Controller_Timeaccount), &#039;Timeaccount&#039;)
#9 [internal function]: Timetracker_Frontend_Json-&gt;saveTimeaccount(Array)
#10 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 /usr/share/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#14 /usr/share/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#15 /usr/share/tine20/Tinebase/Core.php(221): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#16 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#17 {main}
fa50d 19850 web - 2015-08-19T12:31:00+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_Record_Validation -&gt; Some fields modification_time have invalid content
fa50d 19850 web - 2015-08-19T12:31:00+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_Record_Validation -&gt; Some fields modification_time have invalid content
fa50d 19850 web - 2015-08-19T12:31:00+00:00 INFO (6): index.php (25) METHOD: Tinebase_Server_Json::Timetracker.saveTimeaccount / TIME: 196ms /  Memory usage: 15.5 MB /  Real patch cache size: 0 / PID: 24127

**Comment by Gloirin** [comment]
Related to #5566

**Comment by Gloirin** [comment]
Related to #5523

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Aug 2015 15:06**

there seems to be a problem with the &#039;allowEmpty&#039; validation of datetime fields. this might be related to the Zend Framework update (#11160). I&#039;ll try to reporduce this error.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 24 Aug 2015 17:50**

Philip, you are right; I had an older version installed here, but some parts of ZF have been updated with the latest tine update.

Bringing the ZF to the same version as distributed with tine version solved the problems for me.

Thank you for finding that.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Aug 2015 16:08**

ok.

i just had a similar error which could be solved by adding the new zf1ext path to the include path in my apache config:

php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/library/zf1ext:/etc/tine20
