### ISSUE TITLE
0011258:
Accepting (some, likely external) calendar events results in database error when using Postgres

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5571]
**Reported by a3li on 21 Aug 2015 15:46**

**Version:** Elena (2015.07.3)

Tine crashes when changing the acceptance status of some events, possibly related to invitations from external addresses.

Log:

8a268 e8555 user.name - 2015-08-21T14:08:48+00:00 DEBUG (7): Calendar_Controller_Event::update::548 Rolling back because: exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block&#039; in /path/to/tine/htdocs/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /path/to/tine/htdocs/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /path/to/tine/htdocs/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /path/to/tine/htdocs/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;/*getContainerB...&#039;, Array)
#3 /path/to/tine/htdocs/Tinebase/Container.php(544): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;/*getContainerB...&#039;)
#4 /path/to/tine/htdocs/Calendar/Controller.php(107): Tinebase_Container-&gt;getContainerByName(&#039;Calendar&#039;, &#039;$name_of_external_contact..&#039;, &#039;shared&#039;)
#5 /path/to/tine/htdocs/Calendar/Controller/Event.php(1479): Calendar_Controller-&gt;getInvitationContainer(Object(Addressbook_Model_Contact))
#6 /path/to/tine/htdocs/Calendar/Controller/Event.php(515): Calendar_Controller_Event-&gt;_inspectEvent(Object(Calendar_Model_Event))
#7 [internal function]: Calendar_Controller_Event-&gt;update(Object(Calendar_Model_Event), 1, &#039;THIS&#039;)
#8 /path/to/tine/htdocs/Tinebase/Frontend/Json/Abstract.php(250): call_user_func_array(Array, Array)
#9 /path/to/tine/htdocs/Calendar/Frontend/Json.php(378): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Calendar_Controller_Event), &#039;Event&#039;, &#039;id&#039;, Array)
#10 [internal function]: Calendar_Frontend_Json-&gt;saveEvent(Array, 1, &#039;THIS&#039;)
#11 /path/to/tine/htdocs/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#12 /path/to/tine/htdocs/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /path/to/tine/htdocs/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /path/to/tine/htdocs/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#15 /path/to/tine/htdocs/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#16 /path/to/tine/htdocs/Tinebase/Core.php(221): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#17 /path/to/tine/htdocs/index.php(18): Tinebase_Core::dispatchRequest()
#18 {main}

Error message not really useful, Postgres gives more info about the failed query:
ERROR:  bind message supplies 0 parameters, but prepared statement &quot;pdo_stmt_00000075&quot; requires 1

I pasted the full query below. Note the ...WHERE (&quot;addressbook&quot;.&quot;is_deleted&quot; = 0) AND (&quot;accounts&quot;.&quot;id&quot; = $1)... part that seems to be indeed lacking a parameter.
Just before this query, another very very similar query is executed, but this one works as it is asking for an addressbook directly.

I&#039;ll also post the log messages just before the error happens, maybe this can give an indication where this happens.

**Steps to reproduce:** Try to accept/decline an event, Tine sometimes goes boom.

**Additional information:** SQL query:
SELECT &quot;addressbook&quot;.&quot;id&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_countryname&quot;) AS &quot;adr_one_countryname&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_locality&quot;) AS &quot;adr_one_locality&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_postalcode&quot;) AS &quot;adr_one_postalcode&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_region&quot;) AS &quot;adr_one_region&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_street&quot;) AS &quot;adr_one_street&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_street2&quot;) AS &quot;adr_one_street2&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_lon&quot;) AS &quot;adr_one_lon&quot;, MIN(&quot;addressbook&quot;.&quot;adr_one_lat&quot;) AS &quot;adr_one_lat&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_countryname&quot;) AS &quot;adr_two_countryname&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_locality&quot;) AS &quot;adr_two_locality&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_postalcode&quot;) AS &quot;adr_two_postalcode&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_region&quot;) AS &quot;adr_two_region&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_street&quot;) AS &quot;adr_two_street&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_street2&quot;) AS &quot;adr_two_street2&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_lon&quot;) AS &quot;adr_two_lon&quot;, MIN(&quot;addressbook&quot;.&quot;adr_two_lat&quot;) AS &quot;adr_two_lat&quot;, MIN(&quot;addressbook&quot;.&quot;cat_id&quot;) AS &quot;cat_id&quot;, MIN(&quot;addressbook&quot;.&quot;assistent&quot;) AS &quot;assistent&quot;, MIN(&quot;addressbook&quot;.&quot;bday&quot;) AS &quot;bday&quot;, MIN(&quot;addressbook&quot;.&quot;calendar_uri&quot;) AS &quot;calendar_uri&quot;, MIN(&quot;addressbook&quot;.&quot;email&quot;) AS &quot;email&quot;, MIN(&quot;addressbook&quot;.&quot;email_home&quot;) AS &quot;email_home&quot;, MIN(&quot;addressbook&quot;.&quot;freebusy_uri&quot;) AS &quot;freebusy_uri&quot;, MIN(&quot;addressbook&quot;.&quot;geo&quot;) AS &quot;geo&quot;, MIN(&quot;addressbook&quot;.&quot;label&quot;) AS &quot;label&quot;, MIN(&quot;addressbook&quot;.&quot;note&quot;) AS &quot;note&quot;, MIN(&quot;addressbook&quot;.&quot;container_id&quot;) AS &quot;container_id&quot;, MIN(&quot;addressbook&quot;.&quot;private&quot;) AS &quot;private&quot;, MIN(&quot;addressbook&quot;.&quot;pubkey&quot;) AS &quot;pubkey&quot;, MIN(&quot;addressbook&quot;.&quot;role&quot;) AS &quot;role&quot;, MIN(&quot;addressbook&quot;.&quot;room&quot;) AS &quot;room&quot;, MIN(&quot;addressbook&quot;.&quot;tid&quot;) AS &quot;tid&quot;, MIN(&quot;addressbook&quot;.&quot;salutation&quot;) AS &quot;salutation&quot;, MIN(&quot;addressbook&quot;.&quot;title&quot;) AS &quot;title&quot;, MIN(&quot;addressbook&quot;.&quot;tz&quot;) AS &quot;tz&quot;, MIN(&quot;addressbook&quot;.&quot;url&quot;) AS &quot;url&quot;, MIN(&quot;addressbook&quot;.&quot;url_home&quot;) AS &quot;url_home&quot;, MIN(&quot;addressbook&quot;.&quot;n_family&quot;) AS &quot;n_family&quot;, MIN(&quot;addressbook&quot;.&quot;n_fileas&quot;) AS &quot;n_fileas&quot;, MIN(&quot;addressbook&quot;.&quot;n_fn&quot;) AS &quot;n_fn&quot;, MIN(&quot;addressbook&quot;.&quot;n_given&quot;) AS &quot;n_given&quot;, MIN(&quot;addressbook&quot;.&quot;n_middle&quot;) AS &quot;n_middle&quot;, MIN(&quot;addressbook&quot;.&quot;n_prefix&quot;) AS &quot;n_prefix&quot;, MIN(&quot;addressbook&quot;.&quot;n_suffix&quot;) AS &quot;n_suffix&quot;, MIN(&quot;addressbook&quot;.&quot;org_name&quot;) AS &quot;org_name&quot;, MIN(&quot;addressbook&quot;.&quot;org_unit&quot;) AS &quot;org_unit&quot;, MIN(&quot;addressbook&quot;.&quot;tel_assistent&quot;) AS &quot;tel_assistent&quot;, MIN(&quot;addressbook&quot;.&quot;tel_car&quot;) AS &quot;tel_car&quot;, MIN(&quot;addressbook&quot;.&quot;tel_cell&quot;) AS &quot;tel_cell&quot;, MIN(&quot;addressbook&quot;.&quot;tel_cell_private&quot;) AS &quot;tel_cell_private&quot;, MIN(&quot;addressbook&quot;.&quot;tel_fax&quot;) AS &quot;tel_fax&quot;, MIN(&quot;addressbook&quot;.&quot;tel_fax_home&quot;) AS &quot;tel_fax_home&quot;, MIN(&quot;addressbook&quot;.&quot;tel_home&quot;) AS &quot;tel_home&quot;, MIN(&quot;addressbook&quot;.&quot;tel_other&quot;) AS &quot;tel_other&quot;, MIN(&quot;addressbook&quot;.&quot;tel_pager&quot;) AS &quot;tel_pager&quot;, MIN(&quot;addressbook&quot;.&quot;tel_prefer&quot;) AS &quot;tel_prefer&quot;, MIN(&quot;addressbook&quot;.&quot;tel_work&quot;) AS &quot;tel_work&quot;, MIN(&quot;addressbook&quot;.&quot;created_by&quot;) AS &quot;created_by&quot;, MIN(&quot;addressbook&quot;.&quot;creation_time&quot;) AS &quot;creation_time&quot;, MIN(&quot;addressbook&quot;.&quot;last_modified_by&quot;) AS &quot;last_modified_by&quot;, MIN(&quot;addressbook&quot;.&quot;last_modified_time&quot;) AS &quot;last_modified_time&quot;, MIN(&quot;addressbook&quot;.&quot;is_deleted&quot;) AS &quot;is_deleted&quot;, MIN(&quot;addressbook&quot;.&quot;deleted_by&quot;) AS &quot;deleted_by&quot;, MIN(&quot;addressbook&quot;.&quot;deleted_time&quot;) AS &quot;deleted_time&quot;, MIN(&quot;addressbook&quot;.&quot;seq&quot;) AS &quot;seq&quot;, MIN(&quot;addressbook&quot;.&quot;type&quot;) AS &quot;type&quot;, MIN((CASE WHEN &quot;addressbook_image&quot;.&quot;contact_id&quot; IS NULL THEN 0 ELSE 1 END)) AS &quot;jpegphoto&quot;, MIN(&quot;accounts&quot;.&quot;id&quot;) AS &quot;account_id&quot; FROM &quot;tine20_addressbook&quot; AS &quot;addressbook&quot;
         LEFT JOIN &quot;tine20_addressbook_image&quot; AS &quot;addressbook_image&quot; ON &quot;addressbook&quot;.&quot;id&quot; = &quot;addressbook_image&quot;.&quot;contact_id&quot;
         LEFT JOIN &quot;tine20_accounts&quot; AS &quot;accounts&quot; ON &quot;addressbook&quot;.&quot;id&quot; = &quot;accounts&quot;.&quot;contact_id&quot; WHERE (&quot;addressbook&quot;.&quot;is_deleted&quot; = 0) AND (&quot;accounts&quot;.&quot;id&quot; = $1) GROUP BY &quot;addressbook&quot;.&quot;id&quot; LIMIT 1

Other Log messages before the error:
8a268 e8555  - 2015-08-21T14:08:48+00:00 INFO (6): Calendar_Controller_Event::update::511 updating event: 1b0efb4d1cba1345d405a7a15c7eb3b9e7da0ce8 (range: THIS)
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;user_type&#039; of &#039;Calendar_Model_Attender&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::783 *
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_addForeignTableJoins::816 foreign column: jpegphoto
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_addForeignTableJoins::816 foreign column: account_id
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::783 *
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::783 *
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_addForeignTableJoins::816 foreign column: jpegphoto
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_addForeignTableJoins::816 foreign column: account_id
8a268 e8555  - 2015-08-21T14:08:48+00:00 DEBUG (7): Calendar_Model_Event::assertAttendee::283 not adding attendee as container is not personal.
8a268 e8555  - 2015-08-21T14:08:48+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::298 Using application name is deprecated. Please use the classname of the model or the class itself.
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::337 Params: application: Calendar / model: 
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::357 Extracted appName: Calendar modelName: 
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::366 controllerName: Calendar_Controller
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Core::getApplicationInstance::390 Getting instance of Calendar_Controller
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Record_RecordSet::_getMatchingRecords::562 Filtering field &#039;name&#039; of &#039;Tinebase_Model_Application&#039; without indices, expecting slow results
8a268 e8555  - 2015-08-21T14:08:48+00:00 TRACE (8): Tinebase_Backend_Sql_Abstract::_getSelect::783 *

**Comment by Gloirin** [comment]
**Comment posted by cdr68 on 31 Aug 2015 20:15**

Yes, I can confirm that matter too. Where to go for a further investigation: Addressbook/Backend/Sql.php -&gt; public function getByUserId($_userId) ???

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Sep 2015 08:15**

hi,

i added an additional check in Addressbook_Controller_Contact. could you please try again with the following change (i can add the patched file here, if you like):

--- a/tine20/Addressbook/Controller/Contact.php
+++ b/tine20/Addressbook/Controller/Contact.php
@@ -132,6 +132,10 @@ class Addressbook_Controller_Contact extends Tinebase_Controller_Record_Abstract
      */
     public function getContactByUserId($_userId, $_ignoreACL = FALSE)
     {
+        if (empty($_userId)) {
+            throw new Tinebase_Exception_InvalidArgument(&#039;Empty user id&#039;);
+        }
+        
         $contact = $this-&gt;_backend-&gt;getByUserId($_userId);
         
         if ($_ignoreACL === FALSE) {

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Sep 2015 08:17**

added a patched Addressbook/Controller/Contact.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Sep 2015 08:23**

https://gerrit.tine20.org/tine20/3205

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Sep 2015 08:18**

should be resolved in upcoming 2015.07.4 release. please report, if there are still problems with this.
