### ISSUE TITLE
0011330:
problems in expressodriver

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5607]
**Reported by pschuele on 17 Sep 2015 10:29**

**Version:** Elena (2015.07.4)

we found some minor problems in expressodriver application:

* Undefined index problems
* it seems that webdav backend is readonly, we could not upload any new files

**Additional information:** 38db9 80a15 user - 2015-09-17T10:19:13+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::102 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontentlength in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::744 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(744): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 744, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontenttype in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::747 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(747): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 747, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontentlength in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::744 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(744): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 744, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/shared&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontenttype in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::747 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(747): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 747, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/shared&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontentlength in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::744 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(744): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 744, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontenttype in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::747 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(747): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 747, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontentlength in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::744 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(744): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 744, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontenttype in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::747 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(747): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 747, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontentlength in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::744 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(744): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 744, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::530 Undefined index: {DAV:}getcontenttype in /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php::747 (8)
38db9 80a15 user - 2015-09-17T10:19:26+00:00 NOTICE (5): Tinebase_Core::errorHandler::531 #0 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(747): Tinebase_Core::errorHandler(8, &#039;Undefined index...&#039;, &#039;/********/tine20...&#039;, 747, Array)
#1 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(725): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;rawDataToNode(&#039;/Name...&#039;, Array)
#2 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(695): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromBackend(false)
#3 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(674): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodesFromCache(false, &#039;&quot;fb088ce6d58799...&#039;)
#4 /********/tine20.git/tine20/Expressodriver/Backend/Storage/Adapter/Webdav.php(379): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;getNodes(&#039;/&#039;)
#5 /********/tine20.git/tine20/Expressodriver/Controller/Node.php(194): Expressodriver_Backend_Storage_Adapter_Webdav-&gt;search(&#039;&#039;, &#039;/&#039;)
#6 /********/tine20.git/tine20/Tinebase/Frontend/Json/Abstract.php(190): Expressodriver_Controller_Node-&gt;search(Object(Expressodriver_Model_NodeFilter), Object(Tinebase_Model_Pagination), false)
#7 /********/tine20.git/tine20/Expressodriver/Frontend/Json.php(43): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, Array, Object(Expressodriver_Controller_Node), &#039;Expressodriver_...&#039;)
#8 [internal function]: Expressodriver_Frontend_Json-&gt;searchNodes(Array, Array)
#9 /********/tine20.git/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /********/tine20.git/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /********/tine20.git/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /********/tine20.git/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#13 /********/tine20.git/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#14 /********/tine20.git/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}

**Comment by Gloirin** [comment]
Related to #5592

**Comment by Gloirin** [comment]
**Comment posted by fgsl on 21 Sep 2015 11:50**

Philipp, could you inform which version of WebDAV server was used?


It can be possible that DAV server is returning {DAV:}size insteaf of 
{DAV:}getcontentlength, as reported by Tinebase_Core::errorHandler.


Could you tell which keys DAV server is returning where is expected {DAV:}getcontentlength  and {DAV:}getcontenttype?

Thank you!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Oct 2015 09:40**

hi Flávio,

we were connecting against another Tine 2.0 instance. we&#039;ll try again and check the keys that are returned.

@Steffi: could you please collect the required information?
