### ISSUE TITLE
0011338:
First Configuration fails after Installation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5611]
**Reported by jens_gau on 22 Sep 2015 11:16**

**Version:** Elena (2015.07.4)

After Installation on Ubuntu 14.04.3 can&#039;t start Configuration. Tested on three several platforms.

**Steps to reproduce:** - Ubuntu 14.04.3 (!) Installation without additional Software
- Tine 2.0 Installation
  - echo &quot;deb https://packages.tine20.org/ubuntu $(lsb_release -sc) stable&quot; &gt; /etc/apt/sources.list.d/tine20org.list
  - sudo apt-key adv --recv-keys --keyserver keys.gnupg.net 7F6F6895
  - sudo apt-get update
  - sudo apt-get install tine20
- Test with Firefox / Opera
- Go to &quot;https://&lt;domain&gt;/tine20/setup.php&quot;

- Error:

Dienst nicht verfügbar
Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.

**Additional information:** /var/log/tine20/tine20.log

35143 -- none -- - 2015-09-21T22:40:01+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
35143 -- none -- - 2015-09-21T22:40:01+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
13538 -- none -- - 2015-09-21T22:40:54+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
13538 -- none -- - 2015-09-21T22:40:54+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
13538 -- none -- - 2015-09-21T22:40:54+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
13538 -- none -- - 2015-09-21T22:40:54+00:00 ERR (3): Tinebase_Exception::log::121 #0 .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 .../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 .../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(745): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(527): Tinebase_Backend_Sql_Abstract-&gt;_fetch(Object(Zend_Db_Select), &#039;fetch_all&#039;)
#5 .../Tinebase/Application.php(177): Tinebase_Backend_Sql_Abstract-&gt;search(NULL, NULL)
#6 .../Tinebase/Application.php(200): Tinebase_Application-&gt;getApplications()
#7 .../Tinebase/Frontend/Http.php(204): Tinebase_Application-&gt;getApplicationsByState(&#039;enabled&#039;)
#8 [internal function]: Tinebase_Frontend_Http-&gt;login()
#9 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 .../library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#11 .../Tinebase/Http/Server.php(147): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#12 .../Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#13 .../Tinebase/Server/Http.php(93): Tinebase_Http_Server-&gt;handle(Array)
#14 .../Tinebase/Core.php(228): Tinebase_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 .../index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
b2786 -- none -- - 2015-09-21T22:41:01+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
b2786 -- none -- - 2015-09-21T22:41:01+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20.tine20_applications&#039; doesn&#039;t exist
bf4ad -- none -- - 2015-09-21T22:41:01+00:00 ERR (3):

**Comment by Gloirin** [comment]
Related to #5582

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2015 15:37**

there is also a forum post about this: https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=17644

I&#039;ll have a look at this now.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2015 15:51**

i uploaded patched versions of

Tinebase/Application.php
Tinebase/Config/Abstract.php

please replace your local files with those and try again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2015 15:59**

http://gerrit.tine20.com/customers/2267

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Oct 2015 07:24**

seems to be fixed with the patched files (see https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=17644&amp;sid=ca4150c634025b5965ed7a71412fdf6e&amp;p=62920#p62920).

**Comment by Gloirin** [comment]
**Comment posted by dre on 12 Oct 2015 12:28**

there is another error after first install related to bug #0011280.

admin login can&#039;t be created on debian jessie / apache2.4 php 5.6

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Oct 2015 13:07**

i&#039;ll close this one again as the initial problem seems to be fixed. added a relation to #11280

**Comment by Gloirin** [comment]
**Comment posted by jens_gau on 27 Oct 2015 15:17**

Danke.
