### ISSUE TITLE
0011402:
Update8.4 fails on MySQL < 5.5

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5641]
**Reported by pschuele on 26 Oct 2015 08:44**

**Version:** Elena (2015.07.5)

... because of General error: 1193 Unknown system variable &#039;innodb_version&#039;

https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=17678

**Steps to reproduce:** update Fmail 8.4 -&gt; 8.5 with older MySQL

**Additional information:** Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1193 Unknown system variable &#039;innodb_version&#039;&#039; in /var/www/tine/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/tine/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/tine/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/tine/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;select @@innodb...&#039;, Array)
#3 /var/www/tine/Felamimail/Setup/Update/Release8.php(170): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;select @@innodb...&#039;)
#4 /var/www/tine/Felamimail/Setup/Update/Release9.php(21): Felamimail_Setup_Update_Release8-&gt;update_4()
#5 /var/www/tine/Setup/Controller.php(529): Felamimail_Setup_Update_Release9-&gt;update_0()
#6 /var/www/tine/Setup/Controller.php(428): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;9&#039;)
#7 /var/www/tine/Setup/Frontend/Cli.php(241): Setup_Controller-&gt;updateA in /var/www/tine/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Oct 2015 08:46**

attached a patched Felamimail/Setup/Update/Release8.php

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Oct 2015 08:48**

http://gerrit.tine20.com/customers/#/c/2313/
