### ISSUE TITLE
0011426:
CLI: fails to purge deleted records du to constraint violation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5653]
**Reported by ingoratsdorf on 8 Nov 2015 23:26**

**Version:** git master

Running &quot;php tine20.php --username tine20admin --method Tinebase.purgeDeletedRecords&quot;
throws a few errors which mainly are realated to not having sales installed in my instance, however it also complains about

Failed to purge deleted records for table tags. SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`tine20db`.`tine20_tags_acl`, CONSTRAINT `tine20_tags_acl::tag_id--tags::id` FOREIGN KEY (`tag_id`) REFERENCES `tine20_tags` (`id`))

There should probably also be exception handling be added for uninstalled applications, like sales:
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20db.tine20_sales_cost_centers&#039; doesn&#039;t exist&#039; in /var/wwwroot/tine20/library/Zend/Db/Statement/Pdo.php:238

**Additional information:** Removing all deleted entries ...
Failed to purge deleted records for table tags. SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`tine20db`.`tine20_tags_acl`, CONSTRAINT `tine20_tags_acl::tag_id--tags::id` FOREIGN KEY (`tag_id`) REFERENCES `tine20_tags` (`id`))
Cleaning relations...PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20db.tine20_sales_cost_centers&#039; doesn&#039;t exist&#039; in /var/wwwroot/tine20/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/wwwroot/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/wwwroot/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/wwwroot/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;DESCRIBE `tine2...&#039;, Array)
#3 /var/wwwroot/tine20/library/Zend/Db/Adapter/Pdo/Mysql.php(156): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;DESCRIBE `tine2...&#039;)
#4 /var/wwwroot/tine20/Tinebase/Db/Table.php(125): Zend_Db_Adapter_Pdo_Mysql-&gt;describeTable(&#039;tine20_sales_co...&#039;)
#5 /var/wwwroot/tine20/Tinebase/Backend/Sql/Abstract.php(198): Tinebase_Db_Table::getTableDescriptionFromCache(&#039;tine20_sales_co...&#039;, Object(Tinebase_Backend_Sql_Adapter_Pdo_Mysql))
#6 /var/wwwroot/tine20/Tineb in /var/wwwroot/tine20/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
Related to #5115

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Nov 2015 17:27**

hi Ingo,

i fixed the problem with the constraints (see #10249).

but i can&#039;t reproduce the second problem (&quot;Base table or view not found&quot;) when relations are cleaned. do you have a full stacktrace of this? i would like to see, where this comes from.
