### ISSUE TITLE
0011482:
WebDAV Integrity constraint violation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5681]
**Reported by it-mvz on 11 Dec 2015 10:37**

**Version:** Elena Community Edition (2015.07.7)

Appointments with reminder in multiple calendars shown in Lightning, cause Tine to try to insert duplicate entries into the database, what fails

6e5b2 Benutzer - 2015-12-11T10:06:34+00:00 ERR (3): Calendar_Frontend_WebDAV_Event::update::517 exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;e7dbf0bfa953e17b0
123d69b8a786710ea282048-a981d716-9b38-41b9-9117&#039; for key &#039;unique-fields&#039;&#039; in /srv/www/htdocs/domain.tld/library/Zend/Db/Statement/Pdo.php:238

**Steps to reproduce:** Preconditions:
- You have a personal calendar
- You have write permissions in a public calendar
- You have hooked up both calenders in Thunderbird/Lightning

Steps to reproduce:
- Create an appointment in the future in the public calendar and set an reminder 15 mins before. You are automatically attendee in this appointment.
- 15 mins before, lightning pops up with an message (see attached screenshot), that this item has been changed on the server and the error is logged.

**Additional information:** I have created a dump of the tine database and searched it for the string (e7dbf0bfa953e17b0123d69b8a786710ea282048-a981d716-9b38-41b9-9117) appearing in the error message. It doesn&#039;t exist in the whole database, so I don&#039;t understand why it should be duplicated.

This problem only exists for users accessing the Tine calendar via WebDAV.

We discovered this error the first time, after we updated to 2015.07.6, that also introduced some other WebDAV problems.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Dec 2015 17:17**

there is a problem with the sequence here:

6e5b2 Benutzer - 2015-12-11T10:06:34+00:00 ERR (3): Calendar_Frontend_WebDAV_Event::update::517 exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;e7dbf0bfa953e17b0
123d69b8a786710ea282048-a981d716-9b38-41b9-9117&#039; for key &#039;unique-fields&#039;&#039; in /srv/www/htdocs/domain.tld/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /srv/www/htdocs/domain.tld/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /srv/www/htdocs/domain.tld/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /srv/www/htdocs/domain.tld/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /srv/www/htdocs/domain.tld/library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /srv/www/htdocs/domain.tld/Zend/Db/Table/Abstract.php(1055): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_timemach...&#039;, Array)
#5 /srv/www/htdocs/domain.tld/Tinebase/Timemachine/ModificationLog.php(362): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /srv/www/htdocs/domain.tld/Tinebase/Timemachine/ModificationLog.php(744): Tinebase_Timemachine_ModificationLog-&gt;setModification(Object(Tinebase_Model_ModificationLog))
#7 /srv/www/htdocs/domain.tld/Tinebase/Timemachine/ModificationLog.php(667): Tinebase_Timemachine_ModificationLog-&gt;_loopModifications(Array, Object(Tinebase_Model_ModificationLog), Object(Tinebase_Record_RecordSet)
, Array, Array)
#8 /srv/www/htdocs/domain.tld/Tinebase/Controller/Record/Abstract.php(1012): Tinebase_Timemachine_ModificationLog-&gt;writeModLog(Object(Calendar_Model_Event), Object(Calendar_Model_Event), &#039;Calendar_Model_...&#039;, &#039;Sql&#039;
, &#039;a981d716-9b38-4...&#039;)

we will try to reproduce this.
