### ISSUE TITLE
0011530:
Anschrift von Kontakten lässt sich nicht ändern

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5705]
**Reported by e_li on 6 Jan 2016 13:02**

**Version:** Elena Community Edition (2015.07.7)

Die Anschrift von Kontakten lässt sich über die Weboberfläche nicht mehr ändern.
Nach &quot;Ok&quot; erhalte ich ein Programmabruchfenster (Tine 2.0 - Dialog).

Im Log steht zur gleichen Zeit folgendes:

c79eb f6ca0 oooo - 2016-01-06T12:55:51+00:00 WARN (4): Admin_Frontend_Json::searchSambaMachines::692 No samba settings defined in config.
d2b63 c5e6e oooo - 2016-01-06T12:56:19+00:00 WARN (4): Tinebase_Core::errorHandler::517 require_once(Zend/Service/Nominatim/Result.php): failed to open stream: No such file or directory in /usr/share/tine20/library/zf1ext/Zend/Service/Nominatim/ResultSet.php::28 (2)
d2b63 c5e6e oooo - 2016-01-06T12:56:19+00:00 WARN (4): Tinebase_Core::errorHandler::518 #0 /usr/share/tine20/library/zf1ext/Zend/Service/Nominatim/ResultSet.php(28): Tinebase_Core::errorHandler(2, &#039;require_once(Ze...&#039;, &#039;/usr/share/tine...&#039;, 28, Array)
#1 /usr/share/tine20/library/zf1ext/Zend/Service/Nominatim/ResultSet.php(28): require_once()
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(412): include(&#039;/usr/share/tine...&#039;)
#3 /usr/share/tine20/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile(&#039;/usr/share/tine...&#039;)
#4 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;Zend_Service_No...&#039;)
#5 /usr/share/tine20/library/zf1ext/Zend/Service/Nominatim.php(157): spl_autoload_call(&#039;Zend_Service_No...&#039;)
#6 /usr/share/tine20/Addressbook/Controller/Contact.php(390): Zend_Service_Nominatim-&gt;search()
#7 /usr/share/tine20/Addressbook/Controller/Contact.php(503): Addressbook_Controller_Contact-&gt;_setGeoDataForAddress(&#039;adr_one_&#039;, Object(Addressbook_Model_Contact))
#8 /usr/share/tine20/Addressbook/Controller/Contact.php(328): Addressbook_Controller_Contact-&gt;_setGeoData(Object(Addressbook_Model_Contact))
#9 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(894): Addressbook_Controller_Contact-&gt;_inspectBeforeUpdate(Object(Addressbook_Model_Contact), Object(Addressbook_Model_Contact))
#10 [internal function]: Tinebase_Controller_Record_Abstract-&gt;update(Object(Addressbook_Model_Contact), true)
#11 /usr/share/tine20/Tinebase/Frontend/Json/Abstract.php(257): call_user_func_array(Array, Array)
#12 /usr/share/tine20/Addressbook/Frontend/Json.php(211): Tinebase_Frontend_Json_Abstract-&gt;_save(Array, Object(Addressbook_Controller_Contact), &#039;Contact&#039;, &#039;id&#039;, Array)
#13 [internal function]: Addressbook_Frontend_Json-&gt;saveContact(Array, true)
#14 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#15 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#16 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#17 /usr/share/tine20/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#18 /usr/share/tine20/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#19 /usr/share/tine20/Tinebase/Core.php(228): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#20 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#21 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Jan 2016 16:10**

es sieht so aus, als wäre der php include_path nicht richtig gesetzt.

es muss der Pfad 
&quot;/usr/share/tine20/library/zf1ext&quot; enthalten sein, da dort die datei Zend/Service/Nominatim/ResultSet.php enthalten ist.

**Comment by Gloirin** [comment]
**Comment posted by e_li on 7 Jan 2016 17:47**

Ok. Und wo wird der Pfad festgelegt? Tine2.0 läuft bei mir unter Debian, falls das von Belang ist.

**Comment by Gloirin** [comment]
**Comment posted by e_li on 7 Jan 2016 20:42**

Ich habe es in der Apache-Konfiguration eingetragen. Der Fehler tritt jetzt nicht mehr auf.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Jan 2016 13:46**

&gt; Ich habe es in der Apache-Konfiguration eingetragen. Der Fehler tritt jetzt nicht 
&gt; mehr auf.

ja, da muss es hin.

wenn du die deb-pakete aus unserem repo installierst, wird das auch entsprechend eingetragen.

ich schliesse den bugreport.
