### ISSUE TITLE
0011572:
Unable to update Calendar 9.3 -> 9.4

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5726]
**Reported by ingoratsdorf on 21 Jan 2016 18:30**

**Version:** git master

Did fail with a dialog along the lines &quot;Update failed. The data could not be found. Somebody may have already deleted the data. Refresh view&quot;. or similar... ;-)

**Steps to reproduce:** Updated from GIT today and was to update applications in setup.php as usual

**Additional information:** user@server:/var/wwwroot/tine20-git/tine20$ php setup.php --update
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;User with accountLoginName = 20f7b095bf97c62b655b3011f8c7c818d970d0bd not found.&#039; in /var/wwwroot/tine20-git/tine20/Tinebase/User/Sql.php:286
Stack trace:
#0 /var/wwwroot/tine20-git/tine20/ActiveSync/Controller.php(69): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountLoginNam...&#039;, &#039;20f7b095bf97c62...&#039;)
#1 /var/wwwroot/tine20-git/tine20/Calendar/Setup/Update/Release8.php(512): ActiveSync_Controller-&gt;resetSyncForUser(&#039;20f7b095bf97c62...&#039;, &#039;Calendar&#039;)
#2 /var/wwwroot/tine20-git/tine20/Calendar/Setup/Update/Release9.php(60): Calendar_Setup_Update_Release8-&gt;update_11()
#3 /var/wwwroot/tine20-git/tine20/Setup/Controller.php(529): Calendar_Setup_Update_Release9-&gt;update_3()
#4 /var/wwwroot/tine20-git/tine20/Setup/Controller.php(428): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;9&#039;)
#5 /var/wwwroot/tine20-git/tine20/Setup/Frontend/Cli.php(241): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#6 in /var/wwwroot/tine20-git/tine20/Tinebase/User/Sql.php on line 286

Fatal error: Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;User with accountLoginName = 20f7b095bf97c62b655b3011f8c7c818d970d0bd not found.&#039; in /var/wwwroot/tine20-git/tine20/Tinebase/User/Sql.php:286
Stack trace:
#0 /var/wwwroot/tine20-git/tine20/ActiveSync/Controller.php(69): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountLoginNam...&#039;, &#039;20f7b095bf97c62...&#039;)
#1 /var/wwwroot/tine20-git/tine20/Calendar/Setup/Update/Release8.php(512): ActiveSync_Controller-&gt;resetSyncForUser(&#039;20f7b095bf97c62...&#039;, &#039;Calendar&#039;)
#2 /var/wwwroot/tine20-git/tine20/Calendar/Setup/Update/Release9.php(60): Calendar_Setup_Update_Release8-&gt;update_11()
#3 /var/wwwroot/tine20-git/tine20/Setup/Controller.php(529): Calendar_Setup_Update_Release9-&gt;update_3()
#4 /var/wwwroot/tine20-git/tine20/Setup/Controller.php(428): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;9&#039;)
#5 /var/wwwroot/tine20-git/tine20/Setup/Frontend/Cli.php(241): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#6 in /var/wwwroot/tine20-git/tine20/Tinebase/User/Sql.php on line 286

Well, there is no USER with &quot;20f7b095bf97c62b655b3011f8c7c818d970d0bd&quot;, but I found that id in the activesync device id table as id for windowsmail.

Devided to delete the activesync app in tine20 setup as I don&#039;t really use it that much.

That lead to the following error when clicking on &quot;update Applications&quot; in setup:

SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;tine20svndb.tine20_acsync_device&#039; doesn&#039;t exist
.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../Tinebase/Backend/Sql/Abstract.php(756): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Tinebase/Backend/Sql/Abstract.php(532): Tinebase_Backend_Sql_Abstract-&gt;_fetch()
.../Calendar/Setup/Update/Release8.php(508): Tinebase_Backend_Sql_Abstract-&gt;search()
.../Calendar/Setup/Update/Release9.php(60): Calendar_Setup_Update_Release8-&gt;update_11()
.../Setup/Controller.php(529): Calendar_Setup_Update_Release9-&gt;update_3()
.../Setup/Controller.php(428): Setup_Controller-&gt;updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications()
[internal function]: Setup_Frontend_Json-&gt;updateApplications()
.../library/Zend/Server/Abstract.php(232): call_user_func_array()
.../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle()
.../Setup/Core.php(109): Setup_Server_Json-&gt;handle()
.../setup.php(14): Setup_Core::dispatchRequest()

Soooo... activesync is now required for calendar?

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 21 Jan 2016 18:32**

After I installed the activesync app again, the update process was able to update calendar. Now all working again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jan 2016 08:38**

yup, that update script was broken. we need to check if ActiveSync is currently installed ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jan 2016 09:06**

http://gerrit.tine20.com/customers/2611
