### ISSUE TITLE
0011700:
setup.php wird nicht geladen: PHP-Pfad falsch?

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5789]
**Reported by e_li on 18 Mar 2016 12:39**

**Version:** Egon Community Edition (2016.03.1)

Ich habe meine Installation gerade mittels des Debian-Pakets auf &quot;Egon&quot; upgedatet.
setup.php kann nicht geladen werden (Status 500). Im Apache-Log sehr ich gehäuft folgende Meldung:

PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Exception.php&#039; (include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20:/usr/share/tine20/library/zf1ext&#039;) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php on line 146,

Vermutlich ist der PHP-Include-Pfad falsch. 

Wie wäre es denn richtig?
Und wohin hat das Update-Kit den richtigen Pfad hingeschrieben?

**Comment by Gloirin** [comment]
**Comment posted by e_li on 18 Mar 2016 12:59**

Ich habe jetzt mal geraten und &quot;/usr/share/tine20/vendor/zendframework/zendframework1/library&quot; an den include_path angehängt.

Jetzt wird die Seite geladen. Ich erhalte aber fortlaufend die Meldung, dass meine Sitzung abgelaufen ist, ohne jedoch Anmeldedaten eingeben zu können.

Im Tine20-Log steht folgendes:

d5a6a -- none -- - 2016-03-18T12:51:07+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_AccessDenied -&gt; Not Authorised
d5a6a -- none -- - 2016-03-18T12:51:07+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; Not Authorised
12d68 -- none -- - 2016-03-18T12:54:49+00:00 WARN (4): Setup_Server_Json::handle::81 Fatal: got wrong json key! (3eab1d83df24168e803e11e6a1e8a80a50089f31) Possible CSRF attempt! affected account: tine20setup request: Array
(
    [transactionid] =&gt; 86cdf2637f7474c09dbb4e22f6b08e8200fb462a
)

12d68 -- none -- - 2016-03-18T12:54:49+00:00 WARN (4): Tinebase_Server_Json::_handleException::325 Tinebase_Exception_AccessDenied -&gt; Not Authorised
12d68 -- none -- - 2016-03-18T12:54:49+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; Not Authorised

**Comment by Gloirin** [comment]
**Comment posted by e_li on 18 Mar 2016 13:49**

In einem zweiten Browser konnte ich mich an setup.php anmelden und die Anwendung aktualisieren. Jetzt funktioniert auch die normale (Nutzer-)Anmeldung wieder.

Allerdings erhalte ich immer noch den Hinweis, dass ich auf &quot;Egon&quot; updaten sollte.

**Comment by Gloirin** [comment]
**Comment posted by exma on 18 Mar 2016 18:20**

Bei mir hat ein &quot;/etc/init.d/apache2 restart&quot; geholfen.
Zudem musste ich mich aus- und wieder einloggen.
Die Update Meldung bleibt aber.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Mar 2016 18:49**

debian/ sollten eigentlich automatisch den richtigen pfad in die apache condig schreiben. ich guck mal, ob wir den apache restart/reload noch ins update script packen können.

update check sollte jetzt passen.

**Comment by Gloirin** [comment]
**Comment posted by e_li on 18 Mar 2016 20:37**

Bei mir wurde der Pfad in der Apache-Config vom Debian-Update-Paket nicht geändert. War bei einem der letzten Updates auch schon so.
Gibt es denn eine Beschreibung, was man manuell eintragen muss?

Der Neustart des Apache brachte keinen Unterschied. 

Die Anmelde-Endlos-Schleife trat nur in Chrome (mit dem ich vorher auch die normale Tine-Umgebung genutzt hatte) auf. Mit MSIE (den ich praktisch nie benutze) konnte ich mich in setup.php (nach der Korrektur des PHP-Pfades) anmelden. Jetzt geht es auch wieder mit Chrome.

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 22 Mar 2016 22:45**

Auch ich habe massive Probleme mit dem aktuellen update (ausgeführt  am 22.3.26 gegen 22:00)

Log-auszug:
[Tue Mar 22 23:39:55.320094 2016] [:error] [pid 10488] [client 95.118.164.50:53668] Tinebase_Core::errorHandler::547 require_once(Zend/Exception.php): failed to open stream: No such file or directory in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php::146 (2)
[Tue Mar 22 23:39:55.320129 2016] [:error] [pid 10488] [client 95.118.164.50:53668] Tinebase_Core::errorHandler::548 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Tinebase_Core::errorHandler(2, &#039;require_once(Ze...&#039;, &#039;/usr/share/tine...&#039;, 146, Array)\n#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Zend_Registry-&gt;get()\n#2 /usr/share/tine20/Tinebase/Core.php(1216): Zend_Registry::get(&#039;cache&#039;)\n#3 /usr/share/tine20/Tinebase/Core.php(1341): Tinebase_Core::get(&#039;cache&#039;)\n#4 /usr/share/tine20/Tinebase/Core.php(1579): Tinebase_Core::getCache()\n#5 /usr/share/tine20/Tinebase/Core.php(1646): Tinebase_Core::_searchServerPlugins()\n#6 /usr/share/tine20/Tinebase/Core.php(246): Tinebase_Core::_getServerPlugins()\n#7 /usr/share/tine20/Tinebase/Core.php(227): Tinebase_Core::getDispatchServer(Object(Zend\\Http\\PhpEnvironment\\Request))\n#8 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()\n#9 {main}
[Tue Mar 22 23:39:55.320163 2016] [:error] [pid 10488] [client 95.118.164.50:53668] PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Exception.php&#039; (include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20&#039;) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php on line 146
[Tue Mar 22 23:39:57.543691 2016] [:error] [pid 10488] [client 95.118.164.50:53669] Tinebase_Core::errorHandler::547 require_once(Zend/Session.php): failed to open stream: No such file or directory in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php::27 (2)
[Tue Mar 22 23:39:57.543724 2016] [:error] [pid 10488] [client 95.118.164.50:53669] Tinebase_Core::errorHandler::548 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php(27): Tinebase_Core::errorHandler(2, &#039;require_once(Ze...&#039;, &#039;/usr/share/tine...&#039;, 27, Array)\n#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php(27): require_once()\n#2 /usr/share/tine20/vendor/composer/ClassLoader.php(412): include(&#039;/usr/share/tine...&#039;)\n#3 /usr/share/tine20/vendor/composer/ClassLoader.php(301): Composer\\Autoload\\includeFile(&#039;/usr/share/tine...&#039;)\n#4 [internal function]: Composer\\Autoload\\ClassLoader-&gt;loadClass(&#039;Zend_Session_Na...&#039;)\n#5 /usr/share/tine20/Tinebase/Session/Abstract.php(20): spl_autoload_call(&#039;Zend_Session_Na...&#039;)\n#6 /usr/share/tine20/vendor/composer/ClassLoader.php(412): include(&#039;/usr/share/tine...&#039;)\n#7 /usr/share/tine20/vendor/composer/ClassLoader.php(301): Composer\\Autoload\\includeFile(&#039;/usr/share/tine...&#039;)\n#8 [internal function]: Composer\\Autoload\\ClassLoader-&gt;loadClass(&#039;Tinebase_Sessio...&#039;)\n#9 /usr/share/tine20/Setup/Server/Http.php(27): spl_autoload_call(&#039;Tinebase_Sessio...&#039;)\n#10 /usr/share/tine20/Setup/Core.php(109): Setup_Server_Http-&gt;handle()\n#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()\n#12 {main}
[Tue Mar 22 23:39:57.543752 2016] [:error] [pid 10488] [client 95.118.164.50:53669] PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Session.php&#039; (include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20&#039;) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php on line 27

egal welcher Browser, tine läuft garnicht. (error 500) auch eine Neuinstallation über die Debian Pakete (apt-get remove... ...apt-get install) brachte keinerlei Besserung

**Comment by Gloirin** [comment]
**Comment posted by indubioproreo on 1 Apr 2016 07:16**

Hi, ich habe in der apache.conf von Tine20 den Pfad ergänzt, natürlich auch schon wie vorgeschlagen in der php*.ini und dann lief es bei mir wieder :-)

/etc/apache2/conf.d/tine20.conf 

ist bei mir ein softlink auf:

tine20.conf -&gt; ../../tine20/apache.conf

Darin habe ich den Pfad ergänzt:

/usr/share/tine20/vendor/zendframework/zendframework1/library

sieht dann so aus:

------schnipp---------------

 &lt;IfModule mod_php5.c&gt;
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20:/usr/share/tine20/vendor/zendframework/zendframework1/library

----------schnapp----------

natürlich 

# service apache2 restart 

nicht vergessen

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 1 Apr 2016 12:17**

------schnipp------
&lt;IfModule mod_php5.c&gt;
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20:/usr/share/tine20/vendor/zendframework/zendframework1/library
------schnapp------

so sieht der entsprechende Abschnitt in meine &quot;/etc/apache2/config-enabled/tine20.conf&quot; aus. Kein Unterschied.

Auffallend ist aber, wenn ich die Dateien von Elena wieder über Egon drüberwegschiebe funzt tine20 wieder (na klar, diesmal wieder als Elena). Eine Fehlkonfiguration meinerseits würde ich deshalb mal ausschließen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Apr 2016 17:32**

@Matze0811:

&gt; include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20&#039;

das steht in deiner fehlermeldung. da ist der richtige include path nicht drin.

die config sieht aber soweit gut aus. sicher, dass der apache neu gestartet wurde und die config geladen wird?

**Comment by Gloirin** [comment]
**Comment posted by indubioproreo on 1 Apr 2016 17:56**

[PATH=/usr/share/tine20]
max_input_time          = 120
include_path            = &quot;.:/usr/share/tine20/vendor/zendframework/zendframework1/library:/usr/share/tine20/library&quot;
open_basedir            = /usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
session.gc_maxlifetime  = 86400
memory_limit            = 256M
upload_max_filesize     = 20M
post_max_size           = 20M
safe_mode               = off
display_errors          = on
log_errors              = on
magic_quotes_gpc        = off
magic_quotes_runtime    = off
register_globals        = off
zlib.output_compression = on
max_execution_time      = 90

so sieht meine 

/etc/tine20/php5.ini 


aus

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 2 Apr 2016 03:59**

Also ich hatte noch nie dies in meinem Pfad stehen:
&quot;vendor/zendframework/zendframework1/library&quot;
Trotzdem hat Tine20 immer funktioniert. Bis vor kurzen, nach dem letzten Upgrade. Ich vermute, das hat mit euren zf1 Aenderungen zu tun.
Is kein grosses Problem, sollte nur dokumentiert werden.

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 2 Apr 2016 07:52**

@pschuele: ist auch schon etwas älter, das log.

Momentan sieht es so aus, wobei die configs die von tine20 angelegten Standard configs sind:
/etc/tine20/apache.conf:
-----schnipp------
&lt;IfModule mod_php5.c&gt;
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/vendor/zendframework/zendframework1/library:/etc/tine20
        php_admin_value open_basedir            /usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
------schnapp-------

/etc/tine20/php5.ini:
------schnipp------
include_path            = .:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/vendor/zendframework/zendframework1/library:/etc/tine20
open_basedir            = /usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
------schnapp------

/var/log/tine20/apache2-error.log
------schnipp------
[Sat Apr 02 09:30:52.254721 2016] [:error] [pid 11187] [client 89.182.204.89:38037] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:30:52.419773 2016] [:error] [pid 11141] [client 89.182.204.89:38672] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:30:52.460971 2016] [:error] [pid 11182] [client 89.182.204.89:39983] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:30:52.477564 2016] [:error] [pid 11364] [client 89.182.204.89:45028] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:30:52.491722 2016] [:error] [pid 11143] [client 89.182.204.89:37615] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:30:52.901206 2016] [:error] [pid 11187] [client 89.182.204.89:39307] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
[Sat Apr 02 09:32:03.325499 2016] [:error] [pid 11526] [client 95.90.208.34:17259] PHP Fatal error:  Cannot redeclare class Zend_Session_Namespace in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php on line 44
[Sat Apr 02 09:33:04.344243 2016] [:error] [pid 11522] [client 95.90.208.34:17237] PHP Fatal error:  Cannot redeclare class Zend_Session_Namespace in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php on line 44
[Sat Apr 02 09:36:25.918988 2016] [:error] [pid 11746] [client 95.90.208.34:17266] PHP Fatal error:  Cannot redeclare class Zend_Session_Namespace in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php on line 44
[Sat Apr 02 09:37:06.757187 2016] [:error] [pid 11746] [client 52.34.158.207:58127] PHP Fatal error:  Cannot redeclare class Zend_Session in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session.php on line 50
------schnapp------

der o.g. Fehler wiederholt sich dabei dann sofort dutzende male.

Nach jeder Änderung wird bei mir rundsätzlich der apache per &quot;service apache2 restart&quot; neugestartet.
Die configs von Egon vertragen sich übrigens sehr gut mit den Files von Elena ;)
Ich muss leider hin und herspringen, da ich eine absolut Funktionstüchtige Umgebung brauche (ist ein kleines Produktiv-System für ein kleines Handwerksunternehmen (3 Mitarbeiter))

**Comment by Gloirin** [comment]
**Comment posted by xp_user on 18 Apr 2016 07:57**

Hi. Ich habe gestern das upgrade auf Egon gemacht und bin leider zu dem selben Fehler gekommen. Endlosschleife bei der setup.php mit ständigem neuladen des Fensters und dem Hinweis: &quot;Sitzung abgelaufen bitte melden sie sich erneut an.&quot; Das trat allerdings erst nach dem Upgrade auf. D.h. ich konnte mich nach einspielen der neuen Daten erst ganz normal auf der setup.php anmelden, habe dann die Pakete aktualisiert und ab dann kam der Fehler.
Ich habe das Problem durch löschen der Cookies im (Client-)Browser lösen können. Evtl. hilft das weiter?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jun 2016 09:46**

hi, ich denke, ich schliesse das hier mal.

die pfade stehen ja mittlerweile richtig in den configs.

es muss halt nach einem update auf alle fälle der webserver reloaded werden. das jetzt so pauschal ins paket einzubauen, ist wohl auch nicht ganz richtig bzw. muss dann auch gescheit gemacht werden (nginx/apache berücksichtigen, nur bei änderungen in den configs, ...).
