### ISSUE TITLE
0011704:
PHP 7 can't decode empty JSON-strings

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5791]
**Reported by lab-at-nohl on 20 Mar 2016 18:10**

**Version:** Egon Community Edition (2016.03.1)

As already mentioned in Forum PHP 7 struggles with JSON. 

No favorites are shown. 

Following an example for Admin: 

d7243 405f7 admin - 2016-03-20T16:52:31+00:00 WARN (4): Felamimail_Frontend_Json::getRegistryData::571 Could not get accounts: Decoding fail
ed: Syntax error
d7243 405f7 admin - 2016-03-20T16:52:31+00:00 DEBUG (7): Felamimail_Frontend_Json::getRegistryData::572 #0 /var/www/tine/www/Tinebase/Frontend/Json/Abstract.php(192): Zend_Json::decode(&#039;&#039;)
#1 /var/www/tine/www/Felamimail/Frontend/Json.php(414): Tinebase_Frontend_Json_Abstract-&gt;_search(&#039;&#039;, &#039;&#039;, Object(Felamimail_Controller_Account), &#039;Felamimail_Mode...&#039;)
#2 /var/www/tine/www/Felamimail/Frontend/Json.php(569): Felamimail_Frontend_Json-&gt;searchAccounts(&#039;&#039;)
#3 /var/www/tine/www/Tinebase/Frontend/Json.php(852): Felamimail_Frontend_Json-&gt;getRegistryData()
#4 /var/www/tine/www/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Tinebase_Frontend_Json-&gt;getAllRegistryData()
#5 /var/www/tine/www/Zend/Json/Server.php(589): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#6 /var/www/tine/www/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#7 /var/www/tine/www/Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#8 /var/www/tine/www/Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#9 /var/www/tine/www/Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle(Object(Zend_Json_Server_Request))
#10 /var/www/tine/www/index.php(18): Tinebase_Core::dispatchRequest()
#11 {main}

UI Bug Report:
Decoding failed: Syntax error

.../Tinebase/Frontend/Json/Abstract.php(192): Zend_Json::decode()
.../Felamimail/Frontend/Json.php(36): Tinebase_Frontend_Json_Abstract-&gt;_search()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json-&gt;searchFolders()
.../Zend/Json/Server.php(589): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Tinebase/Server/Json.php(293): Zend_Json_Server-&gt;handle()
.../Tinebase/Server/Json.php(166): Tinebase_Server_Json-&gt;_handle()
.../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle()
.../index.php(18): Tinebase_Core::dispatchRequest()

**Steps to reproduce:** Use PHP 7 and login. Wait for some seconds. 

**Additional information:** Old bug report (php 5.6): https://bugs.php.net/bug.php?id=68938 - wont fix in php7?

Forum: https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=17926&amp;p=64030

Log: ERR (3): Tinebase_Exception::log::104 Zend_Json_Exception -&gt; Decoding failed: Syntax error

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Mar 2016 08:36**

here&#039;s the pull request: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/pull/11

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Mar 2016 10:10**

pull request merged: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/c4371df20ea247cef202f650812f256f495dc007

I&#039;ll write a test for this in the next days to make this complete.

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 4 Apr 2016 10:01**

More possible code fragements came up to fix (all extend Tinebase_Frontend_Json_Abstract). 

tine20/Calendar/Frontend/Json.php
tine20/Expressomail/Frontend/Json.php

Also I&#039;m unsure about HTTP- and CLI-Frontends as well as JSON coming from database (which might be NULL oder empty). 

Since I ever wanted to look into Expressomail I will fix this next weekend, or should I wait for a patch from Flavio?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Apr 2016 15:04**

&gt; Also I&#039;m unsure about HTTP- and CLI-Frontends as well as JSON coming from 
&gt; database (which might be NULL oder empty).

i think, we can ignore those for the moment. the empty json param case is a specific problem of the json-frontend. maybe it is correct to throw an error if tine20 receives an empty string as json-type param in most cases.

&gt; Since I ever wanted to look into Expressomail I will fix this next weekend, or 
&gt; should I wait for a patch from Flavio?

please go ahead and fix it. or ask Flávio in the Slack channel about it ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Apr 2016 10:17**

we now have a php7 test job in our jenkins: http://ci.tine20.org/job/tine20-php7-cloud

some more tests have been failing (to be fixed in Calendar/Frontend/Json.php):


1) Calendar_JsonTests::testExdateDeleteAll
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1001

2) Calendar_JsonTests::testExdateDeleteThis
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1039

3) Calendar_JsonTests::testExdateDeleteThisAndFuture
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1054

4) Calendar_JsonTests::testExdateUpdateAllSummary
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1162

5) Calendar_JsonTests::testExdateUpdateAllDtStart
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1184

6) Calendar_JsonTests::testExdateUpdateThis
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1206

7) Calendar_JsonTests::testExdateUpdateThisAndFuture
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1230

8) Calendar_JsonTests::testExdateUpdateThisAndFutureRemoveAttendee
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1277

9) Calendar_JsonTests::testExdateUpdateAllAddAttendee
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1302

10) Calendar_JsonTests::testExdateUpdateThisAndFutureChangeDtstart
Zend_Json_Exception: Decoding failed: Syntax error

/usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Json.php:97
/usr/local/share/tine20.git/tine20/Calendar/Frontend/Json.php:292
/usr/local/share/tine20.git/tests/tine20/Calendar/JsonTests.php:1322

FAILURES!
Tests: 1813, Assertions: 10432, Errors: 10, Incomplete: 15, Skipped: 159.

see http://ci.tine20.org/job/tine20-php7-cloud/2/

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 9 Apr 2016 20:41**

This are not errors. Calendar_JsonTests invoke Calendar&#039;s Json search interface wrongful by NULL - UI always uses proper parameters (at least I couldn&#039;t reproduce any other situation). Even so, a pull request is on github. 

Can&#039;t say anything about Expressomail. Couldn&#039;t make it work. Even logging didn&#039;t work.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Apr 2016 11:45**

hi Johannes,

I merged the pull request and pushed your commit into our gerrit as well: https://gerrit.tine20.org/tine20/3332

for Expressomail, we should open a separate bug report.
