### ISSUE TITLE
0011716:
Apparent crash during Calendar_Controller_Event::setConstraintsExdates

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5797]
**Reported by fmos on 25 Mar 2016 06:05**

**Version:** Egon Community Edition (2016.03.1)

Every midnight since the upgrade I have the following error message in my cron logs:

[code]PHP Fatal error:  __clone method called on non-object in /usr/share/tine20/Calendar/Controller/Event.php on line 482[/code]

In preparation of this report I have turned on debug logging yesterday evening. However there is only one message that seems related (because it has the same timestamp). Here is the message plus one previous message:

[code]3be29 cronuser - 2016-03-25T00:00:09+00:00 DEBUG (7): Tinebase_CustomField::getCustomFieldsForApplication::205 Got 0 uncached custom fields for app id 8acb6d5dd190fda903adb6f0cf69c45e2023c71b (cacheid: getCustomFieldsForApplication8acb6d5dd190fda903adb6f0cf69c45e2023c71bAddressbook_Model_ContactreadGrantaecf88fd26a62ce04e5c4cda07d1761c5b468c3d)  
3be29 cronuser - 2016-03-25T00:00:10+00:00 DEBUG (7): Calendar_Controller_Event::setConstraintsExdates::476 event has rrule constrains, calculating exdates[/code]

Hope this help. Regards!

**Steps to reproduce:** Wait for cron to run at midnight:
[code]/usr/sbin/tine20-cli --method=Tinebase.triggerAsyncEvents | logger -p daemon.notice -t &quot;Tine 2.0 scheduler&quot;[/code]

**Comment by Gloirin** [comment]
**Comment posted by fmos on 29 Mar 2016 10:02**

Jetzt bekomme ich auch einen Stack Trace in den Logs:

Mar 29 01:00:01 stanke Tine 2.0 scheduler: Tine 2.0 scheduler run (Tinebase_Alarm,Tinebase_cleanupSessions,Tinebase_Controller_ScheduledImport) complete.
Mar 29 02:00:22 stanke Tine 2.0 scheduler:
Mar 29 02:00:22 stanke Tine 2.0 scheduler: Fatal error: Uncaught Error: __clone method called on non-object in /usr/share/tine20/Calendar/Controller/Event.php:482
Mar 29 02:00:22 stanke Tine 2.0 scheduler: Stack trace:
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #0 /usr/share/tine20/Calendar/Controller/Event.php(511): Calendar_Controller_Event-&gt;setConstraintsExdates(Object(Calendar_Model_Event))
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #1 /usr/share/tine20/Tinebase/Scheduler/Task.php(283): Calendar_Controller_Event-&gt;updateConstraintsExdates()
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #2 /usr/share/tine20/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #3 /usr/share/tine20/Tinebase/Frontend/Cli.php(316): Zend_Scheduler-&gt;run()
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #4 /usr/share/tine20/Tinebase/Frontend/Cli.php(272): Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #5 /usr/share/tine20/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #6 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #7 /usr/sbin/tine20-cli(75): Tinebase_Core::dispatchRequest()
Mar 29 02:00:22 stanke Tine 2.0 scheduler: #8 {main}
Mar 29 02:00:22 stanke Tine 2.0 scheduler:   thrown in /usr/share/tine20/Calendar/Controller/Event.php on line 482
Mar 29 03:00:01 stanke Tine 2.0 scheduler: Tine 2.0 scheduler run (Tinebase_Alarm,Tinebase_cleanupSessions,Tinebase_Controller_ScheduledImport) complete.

Bitte um Info, falls ich noch etwas tun kann um hiermit zu helfen.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 31 Mar 2016 02:58**

I have exactly the same error in my cron jobs. But only every so often.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Mar 2016 08:31**

hi,

this is duplicate of #11702.

i&#039;ll merge the fix today into the git repo... :)
