### ISSUE TITLE
0011722:
Setup.php nach upgrade Egon läuft nicht.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5800]
**Reported by dl6mra on 29 Mar 2016 07:22**

**Version:** Egon Community Edition (2016.03.1)

[Mon Mar 28 23:04:04.168132 2016] [:error] [pid 27058] [client 109.42.1.195:32309] PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Exception.php&#039; (include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/library/zf1ext:/etc/tine20:/tine20/vendor/zendframework/zendframework1/library&#039;) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php on line 146
[Mon Mar 28 23:04:34.116913 2016] [:error] [pid 27056] [client 217.230.137.145:57685] Tinebase_Core::errorHandler::547 require_once(Zend/Session.php): failed to open stream: No such file or directory in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php::27 (2)

Setup nach upgrade Egon läuft nicht.

**Comment by Gloirin** [comment]
**Comment posted by exma on 29 Mar 2016 07:30**

Wie hast du installiert?
Starte mal deinen Webserver neu.
https://forge.tine20.org/view.php?id=11700

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 29 Mar 2016 07:40**

Über apt-get. Apache2 neu gestartet. Habe beim 2. Versuch aber nur neue Dateien ins /tine20 kopiert. Nun sind wieder die alten Dateien dort und es läuft die alte Version. Der Include_path müsste drin sein, Zeigt mir auch das Apache-error.log

   &lt;IfModule mod_php5.c&gt;
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/library/zf1ext:/etc/tine20:/tine20/vendor/zendframework/zendframework1/library
        php_admin_value open_basedir            /usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
        php_admin_value session.gc_maxlifetime  86400
        php_admin_value memory_limit            128M
        php_admin_value upload_max_filesize     20M
        php_admin_value post_max_size           20M
        
        php_admin_value safe_mode               off
        php_admin_flag  display_errors          off
        php_admin_flag  log_errors              on
        php_admin_flag  magic_quotes_gpc        off
        php_admin_flag  magic_quotes_runtime    off
        php_admin_flag  register_globals        off
        php_admin_flag  zlib.output_compression on
        
        php_value       max_execution_time      90

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 29 Mar 2016 08:47**

Looks like a similar problem here, however from GIT after
&quot;git pull upstream&quot; and &quot;composer install&quot;:

[Tue Mar 29 21:45:38.263935 2016] [:error] [pid 6517] [client 125.239.83.84:57309] Tinebase_Core::errorHandler::547 require_once(Zend/Exception.php): failed to open stream: No such file or directory in /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php::146 (2)
[Tue Mar 29 21:45:38.264574 2016] [:error] [pid 6517] [client 125.239.83.84:57309] Tinebase_Core::errorHandler::548 #0 /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Tinebase_Core::errorHandler(2, &#039;require_once(Ze...&#039;, &#039;/var/wwwroot/ti...&#039;, 146, Array)\n#1 /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Zend_Registry-&gt;get()\n#2 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(1216): Zend_Registry::get(&#039;cache&#039;)\n#3 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(1341): Tinebase_Core::get(&#039;cache&#039;)\n#4 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(1579): Tinebase_Core::getCache()\n#5 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(1646): Tinebase_Core::_searchServerPlugins()\n#6 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(246): Tinebase_Core::_getServerPlugins()\n#7 /var/wwwroot/tine20-git/tine20/Tinebase/Core.php(227): Tinebase_Core::getDispatchServer(Object(Zend\\Http\\PhpEnvironment\\Request))\n#8 /var/wwwroot/tine20-git/tine20/index.php(18): Tinebase_Core::dispatchRequest()\n#9 {main}
[Tue Mar 29 21:45:38.264613 2016] [:error] [pid 6517] [client 125.239.83.84:57309] PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Exception.php&#039; (include_path=&#039;.:/var/wwwroot/tine20-git/tine20:/var/wwwroot/tine20-git/tine20/library&#039;) in /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php on line 146

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 29 Mar 2016 09:07**

All that was needed was to add the zendframework1 path to the php includde path, in my case:
php_admin_value include_path            .:/var/wwwroot/tine20-git/tine20:/var/wwwroot/tine20-git/tine20/library:/var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library

just wondering whether this should actually be included in the tine20 loader somewhere rather than in a server config.... ;-)

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 29 Mar 2016 20:59**

Gelöst: hatte statt &quot;/usr/share/tine20/../..&quot; nur &quot;/Tine20/../..&quot; im Pfad..., Danke Mny tnx

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 29 Mar 2016 21:00**

War nicht der komplette Pfad nach Zend eingetragen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Apr 2016 17:37**

@Ingo:

&gt; just wondering whether this should actually be included in the tine20 loader 
&gt; somewhere rather than in a server config.... ;-)

yep, I agree. we are currently discussing if setting the include path as &quot;php_admin_value&quot; is a good idea. we did this for security reasons but it is a pain in the ass... if you set the tine config and tine20 root path as &quot;php_value include_path&quot;, there are no problems as the autoloader takes care of the include_path...

**Comment by Gloirin** [comment]
**Comment posted by schoebelh on 5 Jun 2016 07:43**

Ich habe eben das Update durchgeführt (zusammen mit einem php-Update), Ubuntu Wily).

Jetzt sieht es bei mir - trotz korrektem include-Pfad in der tine20-Apache-ini) so aus:

[Sun Jun 05 09:40:55.081429 2016] [:error] [pid 23120] [client 79.208.209.107:58240] Tinebase_Core::errorHandler::547 require_once(Zend/Exception.php): failed to open stream: No such file or directory in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php::146 (2)
[Sun Jun 05 09:40:55.081467 2016] [:error] [pid 23120] [client 79.208.209.107:58240] Tinebase_Core::errorHandler::548 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Tinebase_Core::errorHandler(2, &#039;require_once(Ze...&#039;, &#039;/usr/share/tine...&#039;, 146, Array)\n#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php(146): Zend_Registry-&gt;get()\n#2 /usr/share/tine20/Tinebase/Core.php(1216): Zend_Registry::get(&#039;cache&#039;)\n#3 /usr/share/tine20/Tinebase/Core.php(1341): Tinebase_Core::get(&#039;cache&#039;)\n#4 /usr/share/tine20/Tinebase/Core.php(1579): Tinebase_Core::getCache()\n#5 /usr/share/tine20/Tinebase/Core.php(1646): Tinebase_Core::_searchServerPlugins()\n#6 /usr/share/tine20/Tinebase/Core.php(246): Tinebase_Core::_getServerPlugins()\n#7 /usr/share/tine20/Tinebase/Core.php(227): Tinebase_Core::getDispatchServer(Object(Zend\\Http\\PhpEnvironment\\Request))\n#8 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()\n#9 {main}
[Sun Jun 05 09:40:55.081487 2016] [:error] [pid 23120] [client 79.208.209.107:58240] PHP Fatal error:  require_once(): Failed opening required &#039;Zend/Exception.php&#039; (include_path=&#039;.:/usr/share/tine20:/usr/share/tine20/library:/etc/tine20&#039;) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Registry.php on line 146

Sowohl setup.php als auch die Startseite sind nicht aufrufbar...

ini:
    &lt;IfModule mod_php5.c&gt;
        php_admin_value max_input_time          120
        php_admin_value include_path            .:/usr/share/tine20:/usr/share/tine20/library:/usr/share/tine20/vendor/zendframework/zendframework1/library
        php_admin_value open_basedir            /usr/share/tine20:/var/lib/tine20:/tmp:/usr/share/php:/etc/tine20:/var/log/tine20
        php_admin_value session.gc_maxlifetime  86400
        php_admin_value memory_limit            128M
        php_admin_value upload_max_filesize     20M
        php_admin_value post_max_size           20M

        php_admin_value safe_mode               off
        php_admin_flag  display_errors          off
        php_admin_flag  log_errors              on
        php_admin_flag  magic_quotes_gpc        off
        php_admin_flag  magic_quotes_runtime    off
        php_admin_flag  register_globals        off
        php_admin_flag  zlib.output_compression on

        php_value       max_execution_time      90
    &lt;/IfModule&gt;


???

**Comment by Gloirin** [comment]
**Comment posted by schoebelh on 5 Jun 2016 17:01**

Found the problem. Apache used tine20.conf in /etc/apache2/conf-enabled/. This was on my system not the expected symbolic link to the correct version in /etc/apache2/conf.d/tine20.conf...

After deleting the file and creating a link all is running fine.

Please close.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Jul 2016 09:20**

ok, thanks for the update. closing this ...
