### ISSUE TITLE
0011726:
External invite handled by Outlook (2016) ends in HTTP POST 500 loop while ActiveSync the event.

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5802]
**Reported by daymien on 29 Mar 2016 09:53**

**Version:** Egon Community Edition (2016.03.1)

If an external user sends an invite and I accept that invite. Outlook (2016) creates the event in my (Tine ActiveSync) calendar but remains in sync mode.

In the tine.log I see that the sync is in an error loop with following exception.

-----------------------

75157 user - 2016-03-29T09:19:24+00:00 CRIT (2): Syncroton_Server::_handlePost::163 unexpected exception occured: Tinebase_Exception_NotFound
75157 user - 2016-03-29T09:19:24+00:00 CRIT (2): Syncroton_Server::_handlePost::165 exception message: Calendar_Model_Event record with id 0313f8f92c5f415be268d67b7eb0c87a66e46a22 not found!
75157 user - 2016-03-29T09:19:24+00:00 CRIT (2): Syncroton_Server::_handlePost::167 #0 /srv/********/Tinebase/Backend/Sql/Abstract.php(225): Calendar_Backend_Sql-&gt;getByProperty(&#039;0313f8f92
c5f415...&#039;, &#039;id&#039;, false)
#1 /srv/********/Tinebase/Controller/Record/Abstract.php(463): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;0313f8f92c5f415...&#039;, false)
#2 /srv/********/Calendar/Controller/Event.php(1319): Tinebase_Controller_Record_Abstract-&gt;get(&#039;0313f8f92c5f415...&#039;, NULL, true, false)
#3 /srv/********/Calendar/Controller/MSEventFacade.php(126): Calendar_Controller_Event-&gt;get(&#039;0313f8f92c5f415...&#039;)
#4 /srv/********/Calendar/Frontend/ActiveSync.php(224): Calendar_Controller_MSEventFacade-&gt;get(&#039;0313f8f92c5f415...&#039;)
#5 /srv/********/vendor/syncroton/syncroton/lib/Syncroton/Command/MeetingResponse.php(38): Calendar_Frontend_ActiveSync-&gt;setAttendeeStatus(Object(Syncroton_Model_MeetingResponse))
#6 /srv/********/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_MeetingResponse-&gt;handle()
#7 /srv/********/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#8 /srv/********/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#9 /srv/********/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#10 /srv/********/index.php(18): Tinebase_Core::dispatchRequest()
#11 {main}

-----------------------

I have to stop Outlook to make calendar sync work again. The invite events remain only local an won&#039;t be synced via ActiveSync to Tine.

Best regards

Reimund 

**Steps to reproduce:** 1) Get an invite from external contact
2) Accept the invite
3) Calendar Sync isn&#039;t working anymore. 

**Additional information:** Outlook 2016 (16.0.6701.1013) via Active Sync

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Mar 2016 08:39**

hi,

could you please provide the (ActiveSync) request log for the event invitation?
it is found in the tine20 log file in DEBUG log level. most valuable is the xml part of the request sent by outlook.

**Comment by Gloirin** [comment]
**Comment posted by daymien on 31 Mar 2016 15:13**

Hi,

Thanks for your fast response.

Are this the lines you are looking for?

--------------------------------------
&lt;code&gt;
9e93d user - 2016-03-31T14:37:01+00:00 DEBUG (7): Syncroton_Server::_handlePost::127 xml request:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;MeetingResponse xmlns=&quot;uri:MeetingResponse&quot;&gt;
  &lt;Request&gt;
    &lt;CollectionId&gt;4793841256eb72b190dd526624624cacebe5a4fc&lt;/CollectionId&gt;
    &lt;UserResponse&gt;1&lt;/UserResponse&gt;
    &lt;RequestId&gt;02670c34b47d3c8dd8ee75ed6b3e34ef8797d13f&lt;/RequestId&gt;
  &lt;/Request&gt;
&lt;/MeetingResponse&gt;
&lt;/code&gt;
--------------------------------------

I also attached a filtered tine.log with one request.


&lt;del&gt;It looks like Outlook isn&#039;t creating the associated event in the calendar.&lt;/del&gt;

Outlook creates only a lokal event and that event isn&#039;t synced to Tine. 

Kind regards
