### ISSUE TITLE
0011908:
Crash on Outlook-Sync (SendMail Command)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5892]
**Reported by mokraemer on 7 Jun 2016 15:31**

**Version:** Egon Community Edition (2016.03.2)

Relevant Trace
cad34 x - 2016-06-07T15:28:13+00:00 DEBUG (7): Syncroton_Server::_handlePost::104 REQUEST Array
(
    [protocolVersion] =&gt; 14.0
    [command] =&gt; SendMail
    [deviceId] =&gt; D6408B60C71D40478FEDFF898C634FE6
    [deviceType] =&gt; WindowsOutlook15
    [policyKey] =&gt; 
    [saveInSent] =&gt; 
    [collectionId] =&gt; 
    [itemId] =&gt; 
    [attachmentName] =&gt; 
    [acceptMultipart] =&gt; 
    [userAgent] =&gt; Outlook/15.0 (15.0.4823.1000; C2R; x86)
    [contentType] =&gt; application/vnd.ms-sync.wbxml
)

cad34 x - 2016-06-07T15:28:13+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2016-06-07 15:28:13
cad34 x - 2016-06-07T15:28:13+00:00 WARN (4): Tinebase_Core::errorHandler::544 simplexml_import_dom() expects parameter 1 to be object, null given in /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/SendMail.php::46 (2)
cad34 x - 2016-06-07T15:28:13+00:00 WARN (4): Tinebase_Core::errorHandler::545 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;simplexml_impor...&#039;, &#039;/mnt/www/...&#039;, 46, Array)
#1 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/SendMail.php(46): simplexml_import_dom(NULL)
#2 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_SendMail-&gt;handle()
#3 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#4 /mnt/www/tine/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#5 /mnt/www/tine/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#6 /mnt/www/tine/index.php(18): Tinebase_Core::dispatchRequest()
#7 {main}
cad34 x - 2016-06-07T15:28:13+00:00 NOTICE (5): Tinebase_Core::errorHandler::557 Trying to get property of non-object in /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/SendMail.php::48 (8)
cad34 x - 2016-06-07T15:28:13+00:00 NOTICE (5): Tinebase_Core::errorHandler::558 #0 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/SendMail.php(48): Tinebase_Core::errorHandler(8, &#039;Trying to get p...&#039;, &#039;/mnt/www/...&#039;, 48, Array)
#1 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_SendMail-&gt;handle()
#2 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#3 /mnt/www/tine/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#4 /mnt/www/tine/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#5 /mnt/www/tine/index.php(18): Tinebase_Core::dispatchRequest()
#6 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jun 2016 15:48**

hi,

it looks like the request body of the SendMail command sent by outlook is empty. did you send an email with outlook? does this happen for every email that is sent?

**Comment by Gloirin** [comment]
**Comment posted by mokraemer on 9 Jun 2016 16:05**

yes, this happend for every mail sent by outlook, but only after updating from 2016.03.1 to 2016.03.2 .
After downgrading to 2016.03.1 this issue disappeared.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jun 2016 16:51**

that&#039;s strange. i can&#039;t see any changes in ActiveSync or Syncroton that might cause the issue.

could you please create a log for a SendMail with 2016.03.1 to see if there are any differences?

**Comment by Gloirin** [comment]
**Comment posted by mokraemer on 9 Jun 2016 17:00**

Ok, on tuesday, I don&#039;t have access to outlook any further ;-)
