### ISSUE TITLE
0011916:
It is not possible to create new roles or modify existing roles

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5896]
**Reported by Notaufnahme on 9 Jun 2016 09:07**

**Version:** Egon Community Edition (2016.03.2)

illegal json data in response

Fatal error: Uncaught exception &#039;ErrorException&#039; with message &#039;Method Zend_Json_Server_Response_Http::__toString() must return a string value&#039; in ../Tinebase/Server/Json.php:174 Stack trace: #0 ../Tinebase/Server/Json.php(174): Tinebase_Core::errorHandler(4096, &#039;Method Zend_Jso...&#039;, &#039;/usr/www/users/...&#039;, 174, Array) #1 ../Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request)) #2 ../index.php(18): Tinebase_Core::dispatchRequest() #3 {main} thrown in ../Tinebase/Server/Json.php on line 174

**Additional information:** https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=18064

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jun 2016 15:19**

hi,

i can&#039;t reproduce the error.

could you please attach a complete (loglevel DEBUG / 7) tine log of the save/createRole request?

thanks!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 May 2017 08:00**

is this still a problem for you?
