### ISSUE TITLE
0011966:
create dialogs from model config

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5921]
**Reported by pschuele on 23 Jun 2016 13:30**

create dialogs from model config

... it should be possible to create apps without any javascript / jsb2 files
... it should only be necessary to add EditDialog.j, GridPanel.js and others if some special design/layout/functionality is needed

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Jun 2016 07:16**

currently this fails with this error:

47977 vagrant - 2016-06-28T15:40:44+00:00 WARN (4): Tinebase_Core::errorHandler::555 file_get_contents(/********/tine20.git/tine20/SoftwareEngineering/SoftwareEngineering.jsb2): failed to open stream: N
o such file or directory in /********/tine20.git/tine20/library/jsb2tk/jsb2tk.php::162 (2)
47977 vagrant - 2016-06-28T15:40:44+00:00 WARN (4): Tinebase_Core::errorHandler::556 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;file_get_conten...&#039;, &#039;/********/tine20...&#039;, 162, Array)
#1 /********/tine20.git/tine20/library/jsb2tk/jsb2tk.php(162): file_get_contents(&#039;/********/tine20...&#039;)
#2 /********/tine20.git/tine20/library/jsb2tk/jsb2tk.php(310): jsb2tk::getDefinition(&#039;/********/tine20...&#039;)
#3 /********/tine20.git/tine20/Tinebase/Frontend/Http.php(262): jsb2tk-&gt;register(&#039;/********/tine20...&#039;, &#039;SoftwareEnginee...&#039;)
#4 /********/tine20.git/tine20/Tinebase/Frontend/Http.php(416): Tinebase_Frontend_Http-&gt;_renderMainScreen()
#5 [internal function]: Tinebase_Frontend_Http-&gt;mainScreen()
#6 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#7 /********/tine20.git/tine20/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#8 /********/tine20.git/tine20/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#9 /********/tine20.git/tine20/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 /********/tine20.git/tine20/Tinebase/Server/Http.php(93): Tinebase_Http_Server-&gt;handle(Array)
#11 /********/tine20.git/tine20/Tinebase/Core.php(229): Tinebase_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 /********/tine20.git/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jul 2016 11:07**

http://gerrit.tine20.com/customers/#/c/3294/
