### ISSUE TITLE
0012066:
Existing Event cannot be modified when it exists in a deleted container and got reimported

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5971]
**Reported by ingoratsdorf on 22 Jul 2016 07:22**

**Version:** 2015.11.15 Elena (Business Edition)

When I delete a container, all subsequent events stay in the database and do NOT get marked as deleted, only the calendar container.
When I import the existing events into a newly created calendar, all events get recreated with identical UID.
As a result, there will be 2x events with the same UID in the database.
If you sync one of them, the old one in the deleted container may get returned with an invalid deleted container ID.

**Steps to reproduce:** [Fri Jul 22 18:40:05.347297 2016] [:error] [pid 24786] [client 122.60.254.164:2283] PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Tinebase_Model_Container record with id = 9 not found!&#039; in /var/wwwroot/tine20/Tinebase/Backend/Sql/Abstract.php:272
Stack trace:
#0 /var/wwwroot/tine20/Tinebase/Backend/Sql/Abstract.php(225): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(9, &#039;id&#039;, false)
#1 /var/wwwroot/tine20/Tinebase/Container.php(482): Tinebase_Backend_Sql_Abstract-&gt;get(9, false)
#2 /var/wwwroot/tine20/Calendar/Frontend/WebDAV/Event.php(465): Tinebase_Container-&gt;getContainerById(&#039;9&#039;)
#3 /var/wwwroot/tine20/Calendar/Frontend/WebDAV/Event.php(226): Calendar_Frontend_WebDAV_Event-&gt;put(&#039;BEGIN:VCALENDAR...&#039;)
#4 /var/wwwroot/tine20/Tinebase/WebDav/Container/Abstract.php(66): Calendar_Frontend_WebDAV_Event::create(Object(Tinebase_Model_Container), &#039;0cd9adc2-e5f8-4...&#039;, Resource id #3)
#5 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;0cd9adc2-e5f8-4...&#039;, Resource id #3)
#6 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sab in /var/wwwroot/tine20/Tinebase/Backend/Sql/Abstract.php on line 272

**Additional information:** container ID 9 is the old deleted container.

Scenario 1: If we mark all container events as deleted too, they still exist and the check for exiting events ignored whether it is deleted anyway, so no option.
Scenario 2: When we import events, we could check against exiting UID&#039;s. However the caldav spec allows for duplicate ID&#039;s, as long as they are in separate calendars (containers). So no option.

Scenario 3: Maybe we could filter for the container in which we want to save the event, rather than JUST the UID or ID? Guess than container moves will not be detected.

So what is the solution?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Nov 2016 08:51**

Hi Ingo, 

#3 is the way to go, and I thought it&#039;s already implemented like this.

Please look at Calendar_Controller_MSEventFacade::assertEventFacadeParams and it&#039;s usages in Calendar_Frontend_WebDAV_Event

Are you talking about CalDAV or are you using (scheduled) ics imports?
In ics imports the Calendar_Controller_MSEventFacade::assertEventFacadeParams seems to be forgotten, I&#039;ll add it there

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Nov 2016 08:55**

http://gerrit.tine20.com/customers/3739
