### ISSUE TITLE
0012082:
deactivate failing scheduled imports

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#5979]
**Reported by pschuele on 4 Aug 2016 16:14**

deactivate failing scheduled imports

* if remote url or file is not found
* if target container is deleted / readonly
* ...

**Additional information:** b375b user - 2016-08-04T13:25:02+00:00 WARN (4): Tinebase_Core::errorHandler::551 file_get_contents(event.ics): failed to open stream: No such file or directory in /usr/share/tine20/Tinebase/Controller/ScheduledImport.php::162 (2)
b375b user - 2016-08-04T13:25:02+00:00 WARN (4): Tinebase_Core::errorHandler::552 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;file_get_conten...&#039;, &#039;/usr/share/tine...&#039;, 162, Array)
#1 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(162): file_get_contents(&#039;event.ics&#039;)
#2 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(187): Tinebase_Controller_ScheduledImport-&gt;_getFileToImport(&#039;event.ics&#039;)
#3 /usr/share/tine20/Tinebase/Controller/ScheduledImport.php(68): Tinebase_Controller_ScheduledImport-&gt;_doScheduledImport(Object(Tinebase_Model_Import))
#4 [internal function]: Tinebase_Controller_ScheduledImport-&gt;runNextScheduledImport()
#5 /usr/share/tine20/Tinebase/Scheduler/Task.php(292): call_user_func_array(Array, Array)
#6 /usr/share/tine20/library/zf1ext/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
#7 /usr/share/tine20/Tinebase/Frontend/Cli.php(316): Zend_Scheduler-&gt;run()
#8 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#9 /usr/share/tine20/Tinebase/Frontend/Cli.php(272): call_user_func(Array, Object(Zend_Console_Getopt))
#10 /usr/share/tine20/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#11 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 /usr/sbin/tine20-cli(75): Tinebase_Core::dispatchRequest()
#13 {main}
b375b user - 2016-08-04T13:25:02+00:00 NOTICE (5): Tinebase_Controller_ScheduledImport::_doScheduledImport 230 The source could not be loaded: &quot;event.ics&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Sep 2016 15:52**

http://gerrit.tine20.com/customers/#/c/3423
