### ISSUE TITLE
0012216:
Caldav Directory calendars not found

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6044]
**Reported by forrest on 20 Sep 2016 09:18**

**Version:** 2016.09.1 (Community Edition)

Hallo,

nach dem Update auf Community Edition (2016.09.01) funktioniert der Aufruf der CalDav URL (https://servername/tine20/calendars) nicht mehr. Es wird folgender Fehler ausgegeben (Username durch ##user## ersetzt:

&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\NotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Directory calendars/##user## not found&lt;/s:message&gt;
  &lt;s:file&gt;/usr/share/tine20/Tinebase/WebDav/Collection/AbstractContainerTree.php&lt;/s:file&gt;
  &lt;s:line&gt;146&lt;/s:line&gt;
  &lt;s:code&gt;0&lt;/s:code&gt;
  &lt;s:stacktrace&gt;#0 /usr/share/tine20/Calendar/Frontend/WebDAV.php(68): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChild(&#039;##user##&#039;)
#1 /usr/share/tine20/Tinebase/WebDav/Collection/AbstractContainerTree.php(284): Calendar_Frontend_WebDAV-&gt;getChild(&#039;##user##&#039;)
#2 /usr/share/tine20/Calendar/Frontend/WebDAV.php(77): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChildren()
#3 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(117): Calendar_Frontend_WebDAV-&gt;getChildren()
#4 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1478): Sabre\DAV\ObjectTree-&gt;getChildren(&#039;calendars&#039;)
#5 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(252): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;calendars&#039;, Array, 1)
#6 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(137): Sabre\DAV\Browser\Plugin-&gt;generateDirectoryIndex(&#039;calendars&#039;)
#7 [internal function]: Sabre\DAV\Browser\Plugin-&gt;httpGetInterceptor(&#039;GET&#039;, &#039;calendars&#039;)
#8 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#9 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(455): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeMethod&#039;, Array)
#10 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;GET&#039;, &#039;calendars&#039;)
#11 /usr/share/tine20/Tinebase/Server/WebDAV.php(147): Sabre\DAV\Server-&gt;exec()
#12 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#13 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#14 {main}&lt;/s:stacktrace&gt;
  &lt;s:sabredav-version&gt;1.8.12&lt;/s:sabredav-version&gt;
&lt;/d:error&gt;

Eine Logdatei kann ich gerne noch nachliefern. Auch der Aufruf einer speziellen CalDAV URL endet im gleichen Fehler. Ist dies ein bekannter Fehler, oder tritt es nur in meiner Umgebung auf?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Sep 2016 08:22**

hi,

ich kann den reproduzieren. werde mal schauen, was da los ist.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Sep 2016 08:33**

fehler kommt wohl durch #12204 und tritt nur auf, wenn tine in einem subdir auf dem server liegt.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Sep 2016 08:53**

found the bug. I&#039;ll post a patch in the next days ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Sep 2016 08:54**

http://gerrit.tine20.com/customers/#/c/3609/

**Comment by Gloirin** [comment]
**Comment posted by forrest on 20 Oct 2016 17:54**

Hallo,

vorerst, vielen Dank für die Bemühungen um den Fehler zu beseitigen.
Aber leider wurde mit dem Patch aus dem Git bei mir der Fehler nicht behoben und auch das heutige Update auf die Community Edition (2016.09.02) behebt es nicht.
Das Fehlerbild sieht jetzt ein wenig anders aus. (Log im Anhang)
Ich habe es auch einmal ohne subdir auf dem Server probiert, aber da geht es leider auch nicht.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 20 Oct 2016 18:07**

On my Community Edition (2016.09.02) I can not reproduce this bug any more. But I have no subdirectory.

**Comment by Gloirin** [comment]
**Comment posted by forrest on 21 Oct 2016 04:57**

Ich habe es noch einmal in einer neuen Installation getestet, und da funktioniert es auch.
In der betreffenden Installation funktionierte es auch nur bei einem User nicht richtig. Bei allen anderen User klappt es gut.
Ich habe als workaround einen neuen User angelegt und alle Daten auf diesen verschoben. Damit ist das Problem vorerst bei mir behoben.
Danke für die schnelle Unterstützung.
