### ISSUE TITLE
0012258:
Tinebase/Mail.php::convertFromTextToHTML exhausts memory

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6065]
**Reported by fmos on 14 Oct 2016 19:36**

**Version:** 2016.09.1 (Community Edition)

I&#039;ve been using Tine20 for several years now without an issue. I have not changed any PHP settings at least in the last six months. Starting yesterday, the following error messages started appearing in my php7.0-fpm.log file:

[14-Oct-2016 19:21:13] WARNING: [pool mail] child 4370 said into stderr: &quot;NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 135168 bytes) in /usr/share/tine20/Tinebase/Mail.php on line 601&quot;  
[14-Oct-2016 19:24:21] WARNING: [pool mail] child 1357 said into stderr: &quot;NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 135168 bytes) in /usr/share/tine20/Tinebase/Mail.php on line 601&quot;  
[14-Oct-2016 20:28:59] WARNING: [pool mail] child 7165 said into stderr: &quot;NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /usr/share/tine20/Tinebase/Mail.php on line 588&quot;  
[14-Oct-2016 20:29:26] WARNING: [pool mail] child 8753 said into stderr: &quot;NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /usr/share/tine20/Tinebase/Mail.php on line 575&quot;

The corresponding lines in Mail.php are all within the convertFromTextToHTML function.

The tine20.log file is filled with error messages like the following:

1f6b1 user - 2016-10-13T18:53:48+00:00 ERR (3): Syncroton_Server::_handlePost::192 Could not encode output: Syncroton_Wbxml_Exception: XML error: No memory at line 154287 in /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Wbxml/Encoder.php:171
Stack trace:
#0 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(189): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#2 /usr/share/tine20/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#3 /usr/share/tine20/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle(Object(Zend_Controller_Request_Http))
#4 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#5 {main}
1f6b1 user - 2016-10-13T18:53:48+00:00 WARN (4): Syncroton_Server::_handlePost::193 xml response(0):

with xml response(1) through (11) following that message with huge amounts of what appears to be an XML message in between. The tine20.log file takes over 300 MB already.

Please let me know if I can contribute any specific additional information.

**Comment by Gloirin** [comment]
Related to #4106

**Comment by Gloirin** [comment]
Related to #6022

**Comment by Gloirin** [comment]
Related to #6025

**Comment by Gloirin** [comment]
**Comment posted by fmos on 14 Oct 2016 19:54**

Apparently a message with 34121669 bytes was the problem. After deleting that message (the actual file in the maildir), Tine20 works again. 

It still seems a bug that one email can effectively DoS any ActiveSync access to an account.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Oct 2016 08:04**

yup, the message should be skipped (or shown as empty, maybe with a hint for the user), if memory is exhausted.e

**Comment by Gloirin** [comment]
**Comment posted by balticer on 30 Oct 2016 19:52**

Hi,

after upgrade to latest community edition, i got same error as above. After this i change PHP config to allow up to 2048M memory.

Now i get this error:
 
2016-10-30T19:46:41+00:00 ERR (3): Syncroton_Server::_handlePost::192 Could not encode output: Syncroton_Wbxml_Exception: XML error: No memory at line 241729 in /htdocs/vendor/syncroton/syncroton/lib/Syncroton/Wbxml/Encoder.php:171
Stack trace:
#0 /htdocs/vendor/syncroton/syncroton/lib/Syncroton/Server.php(189): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))
#1 /htdocs/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#2 /htdocs/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#3 /htdocs/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle(Object(Zend_Controller_Request_Http))
#4 /htdocs/index.php(18): Tinebase_Core::dispatchRequest()
#5 {main}

regards
Kai

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Oct 2016 06:56**

if anybody could send us a problematic mail, this would be easier to debug. if you don&#039;t want to make it public, you can send the mail to p.schuele AT metaways.de

**Comment by Gloirin** [comment]
**Comment posted by fmos on 31 Oct 2016 11:14**

I just sent you an example.

This file is directly from my maildir directory (and packed). Thus the header may need to be adapted according to your test setup.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Oct 2016 16:13**

hi guys,

I just uploaded an older version of tine20/vendor/syncroton/syncroton/lib/Syncroton/Wbxml/Encoder.php

could you please try again with this file? the memory problems should be resolved with this.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Oct 2016 16:18**

https://gerrit.tine20.org/syncroton/301

should be backported to 1.2: https://gerrit.tine20.org/syncroton/#/c/300/

**Comment by Gloirin** [comment]
**Comment posted by balticer on 31 Oct 2016 16:30**

hello,

works for me.

regards
Kai

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Nov 2016 07:43**

ok, thanks for testing. this will be fixed in the upcoming service releases.
