### ISSUE TITLE
0012314:
Thunderbird sync

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6093]
**Reported by gueni222 on 11 Nov 2016 10:33**

**Version:** 2016.09.4 Community Edition

Nach Update auf Tine 2016.09.04 ist der CALDAV Kalender in Thunderbird nicht mehr verfügbar.

**Comment by Gloirin** [comment]
Related to #5854

**Comment by Gloirin** [comment]
Related to #5654

**Comment by Gloirin** [comment]
Related to #5884

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Nov 2016 08:42**

hallo,

steht denn was im logfile? wie äussert sich das problem?

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 14 Nov 2016 09:18**

Guten Morgen,

das Problem äußert sich das neben dem Kalender ein Ausrufezeichen erscheint 
mit der Bemerkung das der Kalender nicht verfügbar ist.

Im Fehlerlog steht Auszugsweise diese Fehlermeldung welche ich auch gerne komplett senden kann


                            cal.ERROR(&quot;[calCachedCalendar] replay action failed: &quot; +
                                      (op ? op.id : &quot;&lt;unknown&gt;&quot;)+&quot;, uri=&quot; +
                                      this_.uri.spec + &quot;, result=&quot; +
                                      result + &quot;, op=&quot; + op);
                        }
                        cal.LOG(&quot;[calCachedCalendar] replayChangesOn finished.&quot;);
                        emptyQueue(status);
                    }
                }
            };
            this.mPendingSync = this.mUncachedCalendar.replayChangesOn(opListener);
            return this.mPendingSync;
        }

        cal.LOG(&quot;[calCachedCalendar] Doing full sync for calendar &quot; + this.uri.spec);
        let completeListener = {
            QueryInterface: XPCOMUtils.generateQI([Components.interfaces.calIOperationListener]),
            modifiedTimes: {},
            hasRenewedCalendar: false,
            getsCompleted: 0,
            getsReceived: 0,
            opCompleted: false,

            onGetResult: function cCC_oOC_cL_onGetResult(aCalendar,
                                                         aStatus,
                                                         aItemType,
                                                         aDetail,
                                                         aCount,
                                                         aItems) {
                if (Components.isSuccessCode(aStatus)) {
                    if (!this.hasRenewedCalendar) {
                        // TODO instead of deleting the calendar and creating a new
                        // one, maybe we want to do a &quot;real&quot; sync between the
                        // existing local calendar and the remote calendar.
                        this_.setupCachedCalendar();
                        this.hasRenewedCalendar = true;
                    }

                    this.getsReceived++;
                    cal.forEach(aItems, function(item) {
                        // Adding items recd from the Memory Calendar
                        // These may be different than what the cache has
                        completeListener.modifiedTimes[item.id] = item.lastModifiedTime;
                        this_.mCachedCalendar.addItem(item, null);
                    }, function completed() {
                        completeListener.getsCompleted++;
                        if (completeListener.opCompleted) {
                            // onOperationComplete was called, but we were not ready yet. call it now.
                            completeListener.onOperationComplete.apply(completeListener, completeListener.opCompleted);
                            completeListener.opCompleted = false;

Gruß Günter

**Comment by Gloirin** [comment]
**Comment posted by weberho on 14 Nov 2016 10:12**

I have the same issue after upgrading from 2016.03.2 to 2016.03.4

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 14 Nov 2016 10:47**

In the version 2016.03.3 everything works perfectly.

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 16 Nov 2016 11:45**

Hello

Is the error still going on?
It would be a pity if the calendar sync would not continue to work.
Do you need more information to solve the problem?

Greetings Guenter.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 16 Nov 2016 20:34**

See https://forge.tine20.org/view.php?id=11832

**Comment by Gloirin** [comment]
**Comment posted by weberho on 17 Nov 2016 08:55**

I tested a wrong instance before. I have this issue with 2016.03.4.

This is what I see in the log-files:

DEBUG (7): Tinebase_Server_WebDAV::handle::151 &gt;&gt;&gt; *DAV response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\ReportNotSupported&lt;/s:exception&gt;
  &lt;s:message/&gt;
  &lt;s:file&gt;/usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php&lt;/s:file&gt;
  &lt;s:line&gt;1069&lt;/s:line&gt;
  &lt;s:code&gt;0&lt;/s:code&gt;
  &lt;s:stacktrace&gt;#0 [internal function]: Sabre\DAV\Server-&gt;httpReport(&#039;calendars/2/44&#039;)
#1 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;calendars/2/44&#039;)
#2 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;REPORT&#039;, &#039;calendars/2/44&#039;)
#3 /usr/share/tine20/Tinebase/Server/WebDAV.php(148): Sabre\DAV\Server-&gt;exec()
#4 /usr/share/tine20/Tinebase/Core.php(230): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#5 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#6 {main}&lt;/s:stacktrace&gt;
  &lt;s:sabredav-version&gt;1.8.12&lt;/s:sabredav-version&gt;
  &lt;d:supported-report/&gt;
&lt;/d:error&gt;

**Comment by Gloirin** [comment]
**Comment posted by weberho on 17 Nov 2016 09:01**

I also see several of those messages when I try to synchronize my calendars (I don&#039;t have the sales module installed (I had it installed some time ago)):

Tinebase_Application::getApplicationByName::131 Application not found. Name: Sales

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 17 Nov 2016 20:06**

The sales stuff is annoying but harmless. It also pops up on cron jobs for me.

The &quot;ReportNotSupported&quot; error pops up when you have disabled the SyncToken plugin but have not disabled it completely in all files.

I will try to post a list of places where it will need to be commented out. It&#039;s NOT just a matter of commenting out the plugin being loaded into Sabre, the Tine20 responses are hardcoded in a few places and rely on the SyncToken plugin to be there.
I went through this procedure some time ago.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2016 08:23**

maybe we should add a feature switch for the synctoken as long as there are still problems with it.

I&#039;ll try to reproduce the problems with TB again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Nov 2016 11:14**

hi,

i just tested Thunderbird sync with the current 2016.09 and master branches and could not detect any problems.

could you please attach a complete sync request log if the problem persists in the upcoming 2016.09.5 release?

@Ingo: maybe you could add a feature toggle for the sync token support to fix the problems for you while no longer having to touch the code (see https://wiki.tine20.org/Developers/Concepts/Configuration#Feature_Toggles)

**Comment by Gloirin** [comment]
**Comment posted by weberho on 25 Nov 2016 10:49**

With version 2016.09.5 the synchronisation works for me again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Nov 2016 11:26**

thanks for the update.

@gueni222: does it work for you, too?

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 25 Nov 2016 11:53**

Hello,

sorry i can Tested not before Monday.
I work not at Home at the Time.
I&#039;ll log on Monday when i&#039;ve tested it.

Wishes a Nice Weekend 
Greetings Günter

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 29 Nov 2016 09:39**

Hello,
For me does not work. The calendar is not available.
I have uploaded the log file from Thunderbird.
Many greetings Guenter

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 14 Dec 2016 11:02**

Hello everybody,
Do you need more information to solve the problem?

**Comment by Gloirin** [comment]
**Comment posted by gueni222 on 14 Dec 2016 12:07**

Good afternoon,

After I have the permission for the files &quot;tmp&quot; and &quot;files&quot; changed everything worked fine.

Thanks Greeting Guenter
