### ISSUE TITLE
0012324:
Since upgrading from 2016.09.2 to 2016.09.4 the "tine20.php --method Tinebase.triggerAsyncEvents" fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6098]
**Reported by weberho on 16 Nov 2016 00:31**

**Version:** 2016.09.4 Community Edition

PHP Fatal error:  Uncaught exception &#039;PDOException&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;cronuser&#039; for key &#039;login_name&#039;&#039; in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#5 /usr/share/tine20/vendor/zendframework/z in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

**Comment by Gloirin** [comment]
**Comment posted by weberho on 17 Nov 2016 08:59**

After deleting the conuser it will automatically be created again. After that, the service fails agin. This is from the logs:

bd90b -- none --  INFO (6): Tinebase_Core::set::1247 Setting user cronuser
bd90b cronuser  DEBUG (7): Tinebase_Scheduler_Task::run::267 Fetching requests .... 
bd90b cronuser  INFO (6): Tinebase_Scheduler_Task::run::271 Running request: Tinebase_Alarm::sendPendingAlarms
bd90b cronuser  INFO (6): Tinebase_AsyncJob::_createNewJob::158 Creating new Job Tinebase_Event_Async_Minutely
bd90b cronuser  DEBUG (7): Tinebase_Alarm::sendPendingAlarms::93 No Tinebase_Event_Async_Minutely is running. Starting new one.
bd90b cronuser  DEBUG (7): Tinebase_Alarm::sendPendingAlarms::117 Sending 2 alarms (limit: 100).
bd90b cronuser  DEBUG (7): Tinebase_Group::getInstance::75 groups backend: Sql
bd90b cronuser  INFO (6): Calendar_Controller_MSEventFacade::getCurrentUserContactId::107 Creating user contact for cronuser on 
the fly ...
bd90b cronuser  DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::505 Loading all configs for app Admin
bd90b cronuser  DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::518 Found 0 configs.
bd90b cronuser  DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::298 Using application name is deprecated. Please use
 the classname of the model or the class itself.
bd90b cronuser  DEBUG (7): Tinebase_AsyncJob::finishJob::209 Finishing job Tinebase_Event_Async_Minutely with status failure
bd90b cronuser  INFO (6): Tinebase_AsyncJob::_purgeOldJobs::184 Purging old Jobs before sequence: 155585
bd90b cronuser  WARN (4): Tinebase_Alarm::sendPendingAlarms::152 Job failed: Container Internal Contacts not found.
bd90b cronuser  DEBUG (7): Tinebase_Alarm::sendPendingAlarms::153 #0 /usr/share/tine20/Addressbook/Setup/Initialize.php(238): Ti
nebase_Container-&gt;getContainerByName(&#039;Addressbook&#039;, &#039;Internal Contac...&#039;, &#039;shared&#039;)
#1 /usr/share/tine20/Admin/Controller/User.php(415): Addressbook_Setup_Initialize::setDefaultInternalAddressbook()
#2 /usr/share/tine20/Admin/Controller/User.php(435): Admin_Controller_User-&gt;getDefaultInternalAddressbook()
#3 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(109): Admin_Controller_User-&gt;createOrUpdateContact(Object(Tinebase_Model_FullUser))
#4 /usr/share/tine20/Calendar/Controller/Event.php(99): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#5 /usr/share/tine20/Calendar/Controller/Event.php(119): Calendar_Controller_Event-&gt;__construct()
#6 [internal function]: Calendar_Controller_Event::getInstance()
#7 /usr/share/tine20/Tinebase/Core.php(406): call_user_func(Array)
#8 /usr/share/tine20/Tinebase/Alarm.php(123): Tinebase_Core::getApplicationInstance(&#039;Calendar&#039;, &#039;Event&#039;)
#9 [internal function]: Tinebase_Alarm-&gt;sendPendingAlarms(&#039;Tinebase_Event_...&#039;)
#10 /usr/share/tine20/Tinebase/Scheduler/Task.php(292): call_user_func_array(Array, Array)
#11 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Scheduler.php(288): Tinebase_Scheduler_Task-&gt;run()
#12 /usr/share/tine20/Tinebase/Frontend/Cli.php(316): Zend_Scheduler-&gt;run()
#13 [internal function]: Tinebase_Frontend_Cli-&gt;triggerAsyncEvents(Object(Zend_Console_Getopt))
#14 /usr/share/tine20/Tinebase/Frontend/Cli.php(272): call_user_func(Array, Object(Zend_Console_Getopt))
#15 /usr/share/tine20/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#16 /usr/share/tine20/Tinebase/Core.php(230): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#17 /usr/share/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#18 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2016 08:11**

I&#039;ll have a look.

could you check if your cronuser is in the correct group/role to have access to &quot;Internal Contacts&quot;?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Nov 2016 08:55**

The user is deactivated and is member of &quot;Administrators&quot; and the &quot;admin role&quot; is assigned. That&#039;s how it is created automatically. With the older version everything worked without any issue.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2016 11:01**

hi,

i just tested this with a fresh installation and an older one and had no problems (in the current 2016.09 branch). i think, this will be resolved with 2016.09.5 (coming next week).

please reopen the issue if the problem persists.
