### ISSUE TITLE
0012336:
php-redis prevents installation of Inventory

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6104]
**Reported by pschuele on 18 Nov 2016 10:30**

php-redis prevents installation of Inventory

somehow related to Doctrine trying to use redis server.

**Additional information:** #0 /usr/share/tine20/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php(47): Redis-&gt;setOption(1, 2)
#1 /usr/share/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(140): Doctrine\Common\Cache\RedisCache-&gt;setRedis(Object(Redis))
#2 /usr/share/tine20/Setup/SchemaTool.php(61): Doctrine\ORM\Tools\Setup::createConfiguration()
#3 /usr/share/tine20/Setup/SchemaTool.php(72): Setup_SchemaTool::getConfig(Object(SimpleXMLElement), Array)
#4 /usr/share/tine20/Setup/SchemaTool.php(94): Setup_SchemaTool::getEntityManager(Object(SimpleXMLElement), Array)
#5 /usr/share/tine20/Setup/Controller.php(1475): Setup_SchemaTool::createSchema(Object(SimpleXMLElement), Array)
#6 /usr/share/tine20/Setup/Controller.php(1391): Setup_Controller-&gt;_installApplication(Object(SimpleXMLElement), Array)
#7 /usr/share/tine20/Setup/Frontend/Cli.php(121): Setup_Controller-&gt;install in /usr/share/tine20/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php on line 47

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Nov 2016 10:52**

http://gerrit.tine20.com/customers/3836
