### ISSUE TITLE
0012346:
Allow api requests from origin file://

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6109]
**Reported by mspahn on 22 Nov 2016 17:14**

**Version:** 2016.09.4 Community Edition

If there&#039;s no origin because you make a call from an ionic app which uses file:// in production mode, tine crashes with an exception.

**Additional information:** Fatal error: Uncaught exception &#039;Zend\Http\Header\Exception\InvalidArgumentException&#039; with message &#039;Invalid header value for Origin key: &quot;Origin&quot;&#039; in /srv/tine20/vendor/zendframework/zend-http/src/Header/Origin.php:36 Stack trace: #0 /srv/tine20/vendor/zendframework/zend-http/src/Headers.php(448): Zend\Http\Header\Origin::fromString(&#039;Origin: file://&#039;) #1 /srv/tine20/vendor/zendframework/zend-http/src/Headers.php(287): Zend\Http\Headers-&gt;lazyLoadHeader(4) #2 /srv/tine20/vendor/zendframework/zend-http/src/Request.php(380): Zend\Http\Headers-&gt;get(&#039;ORIGIN&#039;) #3 /srv/tine20/Tinebase/Server/Json.php(79): Zend\Http\Request-&gt;getHeaders(&#039;ORIGIN&#039;) #4 /srv/tine20/Tinebase/Core.php(229): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request)) #5 /srv/tine20/index.php(18): Tinebase_Core::dispatchRequest() #6 {main} thrown in /srv/tine20/vendor/zendframework/zend-http/src/Header/Origin.php on line 36

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 22 Nov 2016 17:46**

https://gerrit.tine20.org/tine20/#/c/3414/

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 22 Nov 2016 17:49**

Dear beloved Phil,

This patch is more a workaround but saves a lot of time and is efficient.
Zend 1 Request stuff can&#039;t deal with file:// in Origin which throws a nice exception. I don&#039;t want to change how it works in general so I put a try around it. This allows to work with CORS if it&#039;s possible and if an exception is caused it just skips it.

Solved my problem and Tine 2.0 is still working great. :)

Now have fun building ionic apps for Tine 2.0 without struggling with stupid CORS! :)

Regards

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 Nov 2016 14:48**

hi Micha, I&#039;ll talk to Conny about this. maybe we can detect those &quot;file&quot; requests without triggering the CORS-handling...

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 29 Nov 2016 12:22**

Yeah of course! Was just a quick solution :o.
