### ISSUE TITLE
0012478:
Email: update cache error repeating when folder is missing

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6174]
**Reported by pschuele on 29 Dec 2016 15:03**

Email: update cache error repeating when folder is missing

**Additional information:** Tinebase_Exception::log::121 #0 .../Felamimail/Backend/Imap.php(974): Felamimail_Backend_Imap-&gt;selectFolder(&#039;INBOX/Backup&#039;)
#1 .../Felamimail/Backend/ImapProxy.php(85): Felamimail_Backend_Imap-&gt;expunge(&#039;INBOX/Backup&#039;)
#2 .../Felamimail/Controller/Cache/Message.php(322): Felamimail_Backend_ImapProxy-&gt;__call(&#039;expunge&#039;, Array)
#3 .../Felamimail/Controller/Cache/Message.php(268): Felamimail_Controller_Cache_Message-&gt;_expungeCacheFolder(Object(Felamimail_Model_Folder), Object(Felamimail_Backend_ImapProxy))
#4 .../Felamimail/Frontend/ActiveSync.php(691): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;78e7fb29a3b9f67...&#039;, 10)
#5 .../ActiveSync/Frontend/Abstract.php(671): Felamimail_Frontend_ActiveSync-&gt;_inspectGetCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#6 .../ActiveSync/Frontend/Abstract.php(689): ActiveSync_Frontend_Abstract-&gt;getCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#7 .../vendor/syncroton/syncroton/lib/Syncroton/Command/Ping.php(180): ActiveSync_Frontend_Abstract-&gt;hasChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#8 .../vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_Ping-&gt;handle()
#9 .../vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#10 .../ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#11 .../Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle(Object(Zend_Controller_Request_Http))
#12 .../index.php(21): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Feb 2017 09:37**

http://gerrit.tine20.com/customers/#/c/4025/
