### ISSUE TITLE
0012538:
fix displaycontainer calendar update script broken

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6204]
**Reported by pschuele on 19 Jan 2017 17:17**

fix displaycontainer calendar update script broken

**Additional information:** 41643 -- none -- - 2017-01-19T18:01:09+00:00 NOTICE (5): Tinebase_Core::errorHandler::557 Undefined property: Calendar_Setup_Update_Release9::$getApplicationVersion in /********/tine20.git/tine20/Calendar/Setup/Update/Release9.php::140 (8)
41643 -- none -- - 2017-01-19T18:01:09+00:00 NOTICE (5): Tinebase_Core::errorHandler::558 #0 /********/tine20.git/tine20/Calendar/Setup/Update/Release9.php(140): Tinebase_Core::errorHandler(8, &#039;Undefined prope...&#039;, &#039;/********/tine20...&#039;, 140, Array)
#1 /********/tine20.git/tine20/Setup/Controller.php(529): Calendar_Setup_Update_Release9-&gt;update_4()
#2 /********/tine20.git/tine20/Setup/Controller.php(428): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;9&#039;)
#3 /********/tine20.git/tine20/Setup/Frontend/Cli.php(241): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#4 /********/tine20.git/tine20/Setup/Frontend/Cli.php(204): Setup_Frontend_Cli-&gt;_updateApplications()
#5 /********/tine20.git/tine20/Setup/Frontend/Cli.php(56): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#6 /********/tine20.git/tine20/Setup/Server/Cli.php(106): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#7 /********/tine20.git/tine20/Setup/Core.php(109): Setup_Server_Cli-&gt;handle()
#8 /********/tine20.git/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Jan 2017 18:02**

http://gerrit.tine20.com/customers/#/c/4117/
