### ISSUE TITLE
0012540:
upgrade to PHP 7.1.x (Tinebase_DateTime)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6205]
**Reported by fvisic on 20 Jan 2017 00:16**

**Version:** 2015.11.19 Elena (Business Edition)

In Zend Tinebase_DateTime::setTime need to add one more arguments $microseconds

...
Tinebase_Core::errorHandler::610 Declaration of Tinebase_DateTime::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) in ...tine20\Tinebase\DateTime.php::776 (2)
afdf9 ee773 -- none -- - 2017-01-19T15:39:19+00:00 WARN (4): Tinebase_Core::errorHandler::611 #0 ...tine20\vendor\composer\ClassLoader.php(412): Tinebase_Core::errorHandler(2, &#039;Declaration of ...&#039;, &#039;...&#039;, 776, Array)
#1 ...tine20\vendor\composer\ClassLoader.php(412): include()
#2 ...tine20\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile(&#039;C:\\nginx\\WWW\\De...&#039;)
#3 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass(&#039;Tinebase_DateTi...&#039;)
#4 ...tine20\Tinebase\Session\Abstract.php(235): spl_autoload_call(&#039;Tinebase_DateTi...&#039;)
#5 ...tine20\Tinebase\Core.php(509): Tinebase_Session_Abstract::setSessionBackend()
#6 ...tine20\Tinebase\Server\Json.php(121): Tinebase_Core::startCoreSession()
#7 ...tine20\Tinebase\Core.php(272): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#8 ...tine20\index.php(42): Tinebase_Core::dispatchRequest()
#9 {main}

**Additional information:** before
    /**
     * (non-PHPdoc)
     * @see DateTime::setTime()
     * @note PHP 5.3.0 changed the return value on success from NULL to DateTime.
     */
    public function setTime($hour, $minute, $second = 0)
    {
        parent::setTime($hour, $minute, $second);
        return $this;
    }

after

    /**
     * (non-PHPdoc)
     * @see DateTime::setTime()
     * @note PHP 5.3.0 changed the return value on success from NULL to DateTime.
     */
    public function setTime($hour, $minute, $second = 0, $microseconds = NULL)
    {
        parent::setTime($hour, $minute, $second);
        return $this;
    }

**Comment by Gloirin** [comment]
Related to #6206

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Jan 2017 14:49**

http://gerrit.tine20.com/customers/#/c/4155/
