### ISSUE TITLE
0012542:
upgrade to PHP 7.1.x (Zend_Translate)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6206]
**Reported by fvisic on 20 Jan 2017 00:21**

problme in translate

in .... zendframework1\library\Zend\Translate\Adapter\GettextPo.php

&lt;br /&gt;
&lt;b&gt;Fatal error&lt;/b&gt;:  Uncaught Error: [] operator not supported for strings in tine20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter\GettextPo.php:128
Stack trace:
#0 tine20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter.php(469): Zend_Translate_Adapter_GettextPo-&gt;_loadTranslationData(...&#039;, &#039;hr_HR&#039;, Array)
#1 tine20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter.php(212): Zend_Translate_Adapter-&gt;_addTranslationData(...&#039;, &#039;hr_HR&#039;, Array)
#2 tine20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter.php(117): Zend_Translate_Adapter-&gt;addTranslation(...&#039;, &#039;hr_HR&#039;, Array)
#3 tine20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter\GettextPo.php(50): Zend_Translate_Adapter-&gt;__construct(...&#039;, &#039;hr_HR&#039;, Array)
#4 tine20\vendor\zendframework\zendframework1\l in &lt;b&gt;C:\nginx\WWW\Default\cpm20\vendor\zendframework\zendframework1\library\Zend\Translate\Adapter\GettextPo.php&lt;/b&gt; on line &lt;b&gt;128&lt;/b&gt;&lt;br /&gt;

**Additional information:** in method

protected function _loadTranslationData($filename, $locale, array $options = array())
    {
...
before
....
            if(strpos($line, &#039;msgstr[&#039;)!== FALSE){
                $line = str_replace(&quot;\r\n&quot;, &quot;\n&quot;, $line);    
                $str = substr($line, 11, -2);
                $line = fgets($this-&gt;_file);
                while (strpos($line, &#039;&quot;&#039;)=== 0){
                    $str = $str . substr($line, 1, -2);
                    $line = fgets($this-&gt;_file);
                }

                $this-&gt;_data[$locale][$id][] = $str;
                fseek($this-&gt;_file, - strlen($line), SEEK_CUR);
            }
...
after 
....
            if(strpos($line, &#039;msgstr[&#039;)!== FALSE){
                $line = str_replace(&quot;\r\n&quot;, &quot;\n&quot;, $line);    
                $str = substr($line, 11, -2);
                $line = fgets($this-&gt;_file);
                while (strpos($line, &#039;&quot;&#039;)=== 0){
                    $str = $str . substr($line, 1, -2);
                    $line = fgets($this-&gt;_file);
                }
                if (empty($this-&gt;_data[$locale][$id])) {
                    unset($this-&gt;_data[$locale][$id]);
                }
                $this-&gt;_data[$locale][$id][] = $str;
                fseek($this-&gt;_file, - strlen($line), SEEK_CUR);
            }
....

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jan 2017 08:39**

hi Filip,

thanks for the bugreport. I&#039;ll update our ZF...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jan 2017 11:13**

https://gerrit.tine20.org/tine20/3430

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Feb 2017 12:49**

http://gerrit.tine20.com/customers/#/c/4160/
