### ISSUE TITLE
0012556:
2016.09.7 Exception during cron purgeDeletedRecords

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6213]
**Reported by ravermeister on 23 Jan 2017 15:33**

**Version:** 2016.09.7 Community Edition

I have a Cron job which was already working in the earlier Versions:

Cron &lt;raver@indus&gt; php /var/www/virtual/raver/mail.rimkus.it/tine20.php --method Tinebase.purgeDeletedRecords --username &quot;tine20_cronuser&quot; --password &quot;tine20_cron_password&quot;  -- date=$(date -d -30days +%Y-%m-%d) &gt; /dev/null

after the Upgrade Cron job shows Exceptions (even when executing the Command in Terminal):

Cleaning modlog...PHP Fatal error:  Uncaught exception &#039;Exception&#039; with message &#039;search for model: Tinebase_Model_Container returned not an array!&#039; in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php:199
Stack trace:
#0 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(153): Tinebase_Timemachine_ModificationLog-&gt;clean()
#1 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(546): Tinebase_Frontend_Cli-&gt;cleanModlog()
#2 [internal function]: Tinebase_Frontend_Cli-&gt;purgeDeletedRecords(Object(Zend_Console_Getopt))
#3 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(313): call_user_func(Array, Object(Zend_Console_Getopt))
#4 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#5 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Core.php(230): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#6 /var/www/virtual/raver/mail.rimkus.it.cur/tine20.php(73): Tinebase_Core:: in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php on line 199

Fatal error: Uncaught exception &#039;Exception&#039; with message &#039;search for model: Tinebase_Model_Container returned not an array!&#039; in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php:199
Stack trace:
#0 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(153): Tinebase_Timemachine_ModificationLog-&gt;clean()
#1 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(546): Tinebase_Frontend_Cli-&gt;cleanModlog()
#2 [internal function]: Tinebase_Frontend_Cli-&gt;purgeDeletedRecords(Object(Zend_Console_Getopt))
#3 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(313): call_user_func(Array, Object(Zend_Console_Getopt))
#4 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#5 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Core.php(230): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#6 /var/www/virtual/raver/mail.rimkus.it.cur/tine20.php(73): Tinebase_Core:: in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php on line 199

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 24 Jan 2017 12:57**

fyi: the Installation where Error occurs is very old (about 2 Years)
since then tine was always Upgraded to the recent Version.
Maybe there are old historical Data wich can&#039;t be removed?

If you need any additional information please let me know

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 21 Feb 2017 10:02**

The Error is still present in the current Version 2017.02.1

PHP Fatal error: Uncaught Exception: search for model: Tinebase_Model_Container returned not an array! in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php:199
Stack trace:
#0 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(153): Tinebase_Timemachine_ModificationLog-&gt;clean()
#1 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(551): Tinebase_Frontend_Cli-&gt;cleanModlog()
#2 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Frontend/Cli.php(313): Tinebase_Frontend_Cli-&gt;purgeDeletedRecords(Object(Zend_Console_Getopt))
#3 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Server/Cli.php(99): Tinebase_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#4 /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Core.php(230): Tinebase_Server_Cli-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#5 /var/www/virtual/raver/mail.rimkus.it.cur/tine20.php(73): Tinebase_Core::dispatchRequest()
#6 {main}
thrown in /var/www/virtual/raver/mail.rimkus.it.cur/Tinebase/Timemachine/ModificationLog.php on line 199

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 24 May 2017 07:01**

moved to new php Version PHP 7.1.0
and tine is now up to date at 2017.02.3
the problem is now not reproducable anymore

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 24 May 2017 08:53**

thanks for the update.
