### ISSUE TITLE
0012664:
For some users, CalDAV replies with "Folder not found"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6267]
**Reported by marosh on 16 Feb 2017 11:19**

**Version:** 2016.09.7 Community Edition

Calling &quot;&lt;domain&gt;/calendars&quot; in the browser (and possibly other clients) replies with &quot;Folder not found&quot; error for some users and others not.

FIX:
Change function call in
Tinebase/WebDav/Collection/AbstractContainerTree.php
near line 765/767 to

$contact = Addressbook_Controller_Contact::getInstance()-&gt;get($_id, NULL, false);

**Additional information:** 18cc0 mfe - 2017-02-16T11:06:31+00:00 ERR (3): Tinebase_Exception_NotFound: No Application Controller found (checked class Projects_Controller_Project)! in /var/www/example.com/mail/Tinebase/Core.php:394
Stack trace:
#0 /var/www/example.com/mail/Tinebase/Relations.php(590): Tinebase_Core::getApplicationInstance(&#039;Projects_Model_...&#039;)
#1 /var/www/example.com/mail/Tinebase/Relations.php(404): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#2 /var/www/example.com/mail/Tinebase/Controller/Record/Abstract.php(509): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, &#039;767ff98a4ff711e...&#039;)
#3 /var/www/example.com/mail/Tinebase/Controller/Record/Abstract.php(464): Tinebase_Controller_Record_Abstract-&gt;_getRelatedData(Object(Addressbook_Model_Contact))
#4 /var/www/example.com/mail/Tinebase/WebDav/Collection/AbstractContainerTree.php(766): Tinebase_Controller_Record_Abstract-&gt;get(&#039;767ff98a4ff711e...&#039;)
#5 /var/www/example.com/mail/Tinebase/WebDav/Collection/AbstractContainerTree.php(141): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;_getUser(&#039;767ff98a4ff711e...&#039;)
#6 /var/www/example.com/mail/Calendar/Frontend/WebDAV.php(68): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChild(&#039;767ff98a4ff711e...&#039;)
#7 /var/www/example.com/mail/Tinebase/WebDav/Collection/AbstractContainerTree.php(295): Calendar_Frontend_WebDAV-&gt;getChild(&#039;767ff98a4ff711e...&#039;)
#8 /var/www/example.com/mail/Calendar/Frontend/WebDAV.php(77): Tinebase_WebDav_Collection_AbstractContainerTree-&gt;getChildren()
#9 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(117): Calendar_Frontend_WebDAV-&gt;getChildren()
#10 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1478): Sabre\DAV\ObjectTree-&gt;getChildren(&#039;calendars&#039;)
#11 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(252): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;calendars&#039;, Array, 1)
#12 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(137): Sabre\DAV\Browser\Plugin-&gt;generateDirectoryIndex(&#039;calendars&#039;)
#13 [internal function]: Sabre\DAV\Browser\Plugin-&gt;httpGetInterceptor(&#039;GET&#039;, &#039;calendars&#039;)
#14 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#15 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Server.php(455): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeMethod&#039;, Array)
#16 /var/www/example.com/mail/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;GET&#039;, &#039;calendars&#039;)
#17 /var/www/example.com/mail/Tinebase/Server/WebDAV.php(156): Sabre\DAV\Server-&gt;exec()
#18 /var/www/example.com/mail/Tinebase/Core.php(230): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#19 /var/www/example.com/mail/index.php(18): Tinebase_Core::dispatchRequest()
#20 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Feb 2017 14:22**

problem was an old projects relation while the projects app is no longer available. this should be fixed in Tinebase_Relations.
