### ISSUE TITLE
0012852:
Syncroton_Command_Ping No entry is registered for key 'tasks_data_class'

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6360]
**Reported by Realterminator on 24 Mar 2017 11:18**

**Version:** 2017.02.1 Community Edition

a90a8 XXXXX - 2017-03-24T11:14:23+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;
3efab XXXXX - 2017-03-24T11:14:31+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;
8c6b1 XXXXX - 2017-03-24T11:14:38+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;
bb5c6 XXXXX - 2017-03-24T11:14:39+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;
a90a8 XXXXX - 2017-03-24T11:15:23+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;
3efab XXXXX - 2017-03-24T11:15:31+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;

**Additional information:** Please request witch logs are necessary

**Comment by Gloirin** [comment]
**Comment posted by Realterminator on 24 Mar 2017 15:07**

some more logs

65ccd xxxxxx - 2017-03-24T15:03:46+00:00 CRIT (2): Syncroton_Server::_handlePost::164 unexpected exception occured: Zend_Exception
65ccd xxxxxx - 2017-03-24T15:03:46+00:00 CRIT (2): Syncroton_Server::_handlePost::166 exception message: No entry is registered for key &#039;tasks_data_class&#039;
65ccd xxxxxx - 2017-03-24T15:03:46+00:00 CRIT (2): Syncroton_Server::_handlePost::168 #0 /var/www/mysides/yyyyyy.me/htdocs/tine20/vendor/syncroton/syncroton/lib/Syncroton/Data/Factory.php(59): Syncroton_Registry::get(&#039;tasks_data_clas...&#039;)
#1 /var/www/mysides/yyyyyy.me/htdocs/tine20/vendor/syncroton/syncroton/lib/Syncroton/Command/Sync.php(250): Syncroton_Data_Factory::factory(&#039;Tasks&#039;, Object(Syncroton_Model_Device), Object(DateTime))
#2 /var/www/mysides/yyyyyy.me/htdocs/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_Sync-&gt;handle()
#3 /var/www/mysides/yyyyyy.me/htdocs/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server-&gt;_handlePost()
#4 /var/www/mysides/yyyyyy.me/htdocs/tine20/ActiveSync/Server/Http.php(74): Syncroton_Server-&gt;handle()
#5 /var/www/mysides/yyyyyy.me/htdocs/tine20/Tinebase/Core.php(230): ActiveSync_Server_Http-&gt;handle(Object(Zend_Controller_Request_Http))
#6 /var/www/mysides/yyyyyy.me/htdocs/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#7 {main}
67af4 xxxxxx - 2017-03-24T15:03:53+00:00 ERR (3): Syncroton_Command_Ping::handle::179 No entry is registered for key &#039;tasks_data_class&#039;

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 9 Sep 2017 09:15**

I got the same issue:
2017-09-07T10:18:50+00:00 ERR (3): Syncroton_Command_Ping::handle::204 No entry is registered for key &#039;tasks_data_class&#039;
 On my site, it&#039;s only affecting a single user who is using an iphone. Maybe it&#039;s related to this?

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 9 Sep 2017 09:17**

Sorry, forgotten... I&#039;ve got tine20 (2017.08.3)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Sep 2017 07:07**

do you have the &quot;Tasks&quot; application enabled in Tine 2.0?

**Comment by Gloirin** [comment]
**Comment posted by Matze0811 on 11 Sep 2017 18:41**

Tasks Module is enabled but the message occurs wit deinstalled Tasks too. But i have cleared the issue by deleting the active-sync device in tine20-admin module (in this case the iphone) in hope it connects again without any error- and it does!
