### ISSUE TITLE
0012956:
Build fails on translation

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6412]
**Reported by ingoratsdorf on 13 Apr 2017 10:30**

**Version:** git master

trying phing on git master results in fatal as cache cannot be created.

**Steps to reproduce:** pull latest tine20
composer install
./vendor/bin/phing

looks like it cannot create any cache and cannot get backend of it since null

**Additional information:** ingo@server:/var/wwwroot/tine20-git/tine20$ ./vendor/bin/phing build
Buildfile: /var/wwwroot/tine20-git/tine20/build.xml

tine20 &gt; prepare:

     [echo] basedir: /var/wwwroot/tine20-git/tine20
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
      [php] Evaluating PHP expression: Tinebase_Helper::getDevelopmentRevision();
     [echo] $buildRevision: master: 60faa9a95cf0e15070534d34876c625baf7cdcb8 (2017-04-05 06:00:56)
      [php] Evaluating PHP expression: date_create(&#039;now&#039;, new DateTimeZone(&#039;UTC&#039;))-&gt;format(&#039;Y-m-d H:i:s&#039;);
     [echo] $buildDate: 2017-04-13 10:19:40
     [echo] Making build directory

tine20 &gt; build:

tine20 &gt; prepared-build-module:

     [echo] Building Voipmanager
     [echo] Replace buildstuff...
[reflexive] Applying reflexive processing to 0 files.
     [echo] Apply debug mode for debug files...
[reflexive] Applying reflexive processing to 0 files.
     [echo] [Translations] Checking js dir /var/wwwroot/tine20-git/tine20/Voipmanager/js ...
     [echo] [Translations] Building translations...
PHP Fatal error:  Uncaught Error: Call to a member function getBackend() on null in /var/wwwroot/tine20-git/tine20/Tinebase/Translation.php:72
Stack trace:
#0 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/tasks/system/AdhocTask.php(80) : eval()&#039;d code(11): Tinebase_Translation::getAvailableTranslations()
#1 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/UnknownElement.php(100): translationTask-&gt;main()
#2 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement-&gt;main()
#3 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/tasks/system/SequentialTask.php(58): Task-&gt;perform()
#4 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/tasks/system/IfTask.php(172): SequentialTask-&gt;main()
#5 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/TaskAdapter.php(61): IfTask-&gt;main(Object(Project))
#6 /var/wwwroot/tine20-git/tine20/vendor/phing/phing/classes/phing/UnknownElement.php(100): TaskAdapter-&gt;main()
#7 /var/wwwroot/tine20-git/ in /var/wwwroot/tine20-git/tine20/Tinebase/Translation.php on line 72

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 23 Apr 2017 19:46**

Not sure how exactly the build process works, however it would appear to me that the config file is not being parsed at all, as I am not getting any logs and I can write whatever I want into the config file (config.inc.php).
If it&#039;s not to do with the config file, then I do not know where values for logger and cache would come from.

**Comment by Gloirin** [comment]
**Comment posted by SOWIWAS on 28 Apr 2017 10:53**

On my development machine (without config.inc.php)the build process worked fine. But I have not been able to find the reason for this error. But I didn&#039;t had much time to investigate either. A message on why/what went wrong (more precise reason) woud be great in this case.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 15:38**

it looks like there is a problem with the cache. you don&#039;t need the cache for the build.

please try this (git diff format):

diff --git a/tine20/Tinebase/Translation.php b/tine20/Tinebase/Translation.php
index bb53c51..f92b0eb 100644
--- a/tine20/Tinebase/Translation.php
+++ b/tine20/Tinebase/Translation.php
@@ -70,7 +70,7 @@ class Tinebase_Translation
                 &#039;master_files&#039; =&gt; $filesToWatch
             ));
             $tineCache = Tinebase_Core::get(Tinebase_Core::CACHE);
-            if ($tineCache) {
+            if ($cache &amp;&amp; $tineCache) {
                 $cache-&gt;setBackend($tineCache-&gt;getBackend());
             } else {
                 $cache = null;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 17:33**

i think, the problem should be already fixed since yesterdays release (also in master). the fix above should not be necessary. could you please verify that?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2017 07:53**

closing this.

please reopen if the problem still exists.
