### ISSUE TITLE
0012970:
Crash on execution of phing

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6419]
**Reported by SOWIWAS on 21 Apr 2017 16:34**

**Version:** 2017.02.2 Community Edition

When I try to build the js files using phing I get the following uncaught exception:

tine20 &gt; prepared-build-module:

     [echo] Building ActiveSync
     [echo] Replace buildstuff...
[reflexive] Applying reflexive processing to 6 files.
     [echo] Apply debug mode for debug files...
[reflexive] Applying reflexive processing to 3 files.
     [echo] [Translations] Checking js dir /opt/tine/2017.02.2/tine20/ActiveSync/js ...
     [echo] [Translations] Building translations...
PHP Fatal error:  Uncaught Error: Call to a member function getBackend() on null in /opt/tine/2017.02.2/tine20/Tinebase/Translation.php:72
Stack trace:
#0 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/tasks/system/AdhocTask.php(80) : eval()&#039;d code(11): Tinebase_Translation::getAvailableTranslations()
#1 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/UnknownElement.php(100): translationTask-&gt;main()
#2 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement-&gt;main()
#3 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/tasks/system/SequentialTask.php(58): Task-&gt;perform()
#4 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/tasks/system/IfTask.php(172): SequentialTask-&gt;main()
#5 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/TaskAdapter.php(61): IfTask-&gt;main(Object(Project))
#6 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/phing/UnknownElement.php(100): TaskAdapter-&gt;main()
#7 /opt/tine/2017.02.2/tine20/vendor/phing/phing/classes/ph in /opt/tine/2017.02.2/tine20/Tinebase/Translation.php on line 72

The attached patch did work for me as a workaround but clearly does not fix the cause.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 25 Apr 2017 23:30**

Hmm, yes, the workaround works but I wonder whether there&#039;s a whole lot of thinks broken within.... If I edit a calendar event by double-clicking, I get 4x modal windows on top of each other, even though I set it to application windows.
Emails similar, 3x modal windows on top of each other. Almost looks like it is ignoring any settings that have done.
Is it only MY installation? Is my local GIT buggered?

**Comment by Gloirin** [comment]
**Comment posted by SOWIWAS on 28 Apr 2017 10:57**

I do have a massive internal Buglist since the 2017.02 release from my users. I try to report what I can but various bugs I cannot reliably reproduce or report in a accurate way. But I does seem that not only your git is bugged.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 15:42**

@SOWIWAS: please try the fix suggested in https://forge.tine20.org/view.php?id=12956#c19968

&gt; I do have a massive internal Buglist since the 2017.02 release from my users.

we are sorry for the current instability. we are creating new features at a rapid pace right now and we&#039;ll try to fix major bugs quickly so keep them bugreports coming :)

**Comment by Gloirin** [comment]
**Comment posted by SOWIWAS on 4 May 2017 16:33**

I indeed had a problem with the cache. After an upgrade to php70 the php70u-pecl-redis (CentOS 7) was missing. After that had been installed redis has been working as well.

Since the patch of #12956 is similar to the patch attached to this report I am confident that it will work but maybe a warning would be helpful for other administrators/developers. I will check 2017.02.3 tomorrow with configured redis but missing pecl-redis just to be sure.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 4 May 2017 23:27**

Works for me in the latest version, closing.
