### ISSUE TITLE
0012988:
CredentialCache password convertion doesn't work after update

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6428]
**Reported by mspahn on 27 Apr 2017 13:13**

**Version:** 2017.02.3 Community Edition

Changing password doesn&#039;t work.

I have a 22 character long alphanumerical password without any special character.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 27 Apr 2017 13:13**

9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::117 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 INFO (6): Tinebase_Auth_CredentialCache::_decrypt::308 lets try to decode it with the old algorithm, if successful, persist again if this is a persistent cache
9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 ERR (3): Tinebase_Helper::jsonDecode::357 Could not json decode: &#039;r???K8P{?Z~Ksk???Lp#g?a???A*???????8?c??T???u?&quot;B?=??p??;NYPg?vS???m[?:µUc?zC:q??J
?s?E?????W??L??k&lt;I???????&#039; . &quot;\0&quot; . &#039;???N??
                                           ?&gt;0N?&gt;#?EL ?????Kl???v*?-;?n??A??\&#039;??Q??^6??F,T?c?&#039; - assuming empty array.
9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 ERR (3): Tinebase_Exception::log::104 Zend_Json_Exception -&gt; Decoding failed
9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 ERR (3): Tinebase_Exception::log::121 #0 .../Tinebase/Helper.php(355): Zend_Json::decode(&#039;\x0Fr\xD0\xCE\xB7\xB0K8P{\xAAZ7\x08~...&#039;)
#1 .../Tinebase/Auth/CredentialCache.php(325): Tinebase_Helper::jsonDecode(&#039;\x0Fr\xD0\xCE\xB7\xB0K8P{\xAAZ7\x08~...&#039;)
#2 .../Tinebase/Auth/CredentialCache.php(212): Tinebase_Auth_CredentialCache-&gt;_decrypt(Object(Tinebase_Model_CredentialCache))
#3 .../Felamimail/Controller/Account.php(384): Tinebase_Auth_CredentialCache-&gt;getCachedCredentials(Object(Tinebase_Model_CredentialCache))
#4 .../Felamimail/Controller/Account.php(347): Felamimail_Controller_Account-&gt;_beforeUpdateStandardAccountCredentials(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#5 .../Felamimail/Controller/Account.php(296): Felamimail_Controller_Account-&gt;_beforeUpdateStandardAccount(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#6 .../Tinebase/Controller/Record/Abstract.php(956): Felamimail_Controller_Account-&gt;_inspectBeforeUpdate(Object(Felamimail_Model_Account), Object(Felamimail_Model_Account))
#7 .../Felamimail/Controller/Account.php(491): Tinebase_Controller_Record_Abstract-&gt;update(Object(Felamimail_Model_Account))
#8 .../Felamimail/Frontend/Json.php(483): Felamimail_Controller_Account-&gt;changeCredentials(&#039;563b49187aec4c5...&#039;, &#039;michael@spahn.m...&#039;, &#039;ywUr5WyZceqyIJj...&#039;)
#9 [internal function]: Felamimail_Frontend_Json-&gt;changeCredentials(&#039;563b49187aec4c5...&#039;, &#039;michael@spahn.m...&#039;, &#039;ywUr5WyZceqyIJj...&#039;)
#10 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#11 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#13 .../Tinebase/Server/Json.php(336): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Server/Json.php(171): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Core.php(237): Tinebase_Server_Json-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#16 .../index.php(18): Tinebase_Core::dispatchRequest()
#17 {main}
9a08e f4292 kekstod - 2017-04-27T13:09:46+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; could not find valid credential cache
