### ISSUE TITLE
0012990:
Tinebase Update from 10.9 to 10.20 not working, Tine 2.0 completely offline

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6429]
**Reported by adrian on 27 Apr 2017 20:19**

**Version:** 2017.02.3 Community Edition

I cannot update my Tinebase from within GUI and CLI.
CLI outputs following error:

root@tine:/usr/share/tine20# php /usr/share/tine20/setup.php -c /etc/tine20/config.inc.php --update
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;User with accountId = setupuser not found.&#039; in /usr/share/tine20/Tinebase/User/Sql.php:322
Stack trace:
#0 /usr/share/tine20/Tinebase/Container.php(736): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountId&#039;, &#039;setupuser&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(419): Tinebase_Container-&gt;getDefaultContainer(&#039;Addressbook&#039;, &#039;setupuser&#039;)
#2 /usr/share/tine20/Tinebase/Model/Filter/Container.php(292): Tinebase_Container-&gt;getContainerByACL(&#039;setupuser&#039;, &#039;Addressbook&#039;, Array, true, false)
#3 /usr/share/tine20/Tinebase/Model/Filter/Container.php(271): Tinebase_Model_Filter_Container-&gt;_resolveContainerNode(&#039;all&#039;)
#4 /usr/share/tine20/Tinebase/Model/Filter/Container.php(238): Tinebase_Model_Filter_Container-&gt;_resolvePath(&#039;/&#039;)
#5 /usr/share/tine20/Tinebase/Model/Filter/Container.php(149): Tinebase_Model_Filter_Container-&gt;_resolve()
#6 /usr/share/tine20/Tinebase/Backend/Sql/Filter/FilterGroup.php(46): Tinebase_Model_Filter_Container-&gt;appendFilterSq in /usr/share/tine20/Tinebase/User/Sql.php on line 322

**Steps to reproduce:** php /usr/share/tine20/setup.php -c /etc/tine20/config.inc.php --update

**Additional information:** Having LDAP Backend.
Updated several times during last years.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 06:52**

hi, could you please send a longer stacktrace? we need the numbers #7-10 (at least). this should be found in the tine20.log file.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 28 Apr 2017 07:06**

Did some other tries, so the error is a little bit different this time, but I got the log:

bdeed -- none -- - 2017-04-28T07:04:04+00:00 ERR (3): Setup_Controller::updateApplication::566 User with accountId = admin not found.
bdeed -- none -- - 2017-04-28T07:04:04+00:00 ERR (3): Setup_Controller::updateApplication::567 #0 /usr/share/tine20/Tinebase/Container.php(736): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountId&#039;, &#039;admin&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(419): Tinebase_Container-&gt;getDefaultContainer(&#039;Addressbook&#039;, &#039;admin&#039;)
#2 /usr/share/tine20/Tinebase/Model/Filter/Container.php(292): Tinebase_Container-&gt;getContainerByACL(&#039;admin&#039;, &#039;Addressbook&#039;, Array, true, false)
#3 /usr/share/tine20/Tinebase/Model/Filter/Container.php(271): Tinebase_Model_Filter_Container-&gt;_resolveContainerNode(&#039;all&#039;)
#4 /usr/share/tine20/Tinebase/Model/Filter/Container.php(238): Tinebase_Model_Filter_Container-&gt;_resolvePath(&#039;/&#039;)
#5 /usr/share/tine20/Tinebase/Model/Filter/Container.php(149): Tinebase_Model_Filter_Container-&gt;_resolve()
#6 /usr/share/tine20/Tinebase/Backend/Sql/Filter/FilterGroup.php(46): Tinebase_Model_Filter_Container-&gt;appendFilterSql(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Addressbook_Backend_Sql))
#7 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(574): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Zend_Db_Select), Object(Addressbook_Model_ContactFilter), Object(Addressbook_Backend_Sql))
#8 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(526): Tinebase_Backend_Sql_Abstract-&gt;_addFilter(Object(Zend_Db_Select), Object(Addressbook_Model_ContactFilter))
#9 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(212): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), true)
#10 /usr/share/tine20/Tinebase/Record/Iterator.php(178): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), false, true, &#039;get&#039;)
#11 /usr/share/tine20/Tinebase/Record/Iterator.php(142): Tinebase_Record_Iterator-&gt;_getRecords()
#12 /usr/share/tine20/Tinebase/Controller.php(808): Tinebase_Record_Iterator-&gt;iterate()
#13 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(426): Tinebase_Controller-&gt;rebuildPaths()
#14 /usr/share/tine20/Setup/Controller.php(560): Tinebase_Setup_Update_Release10-&gt;update_9()
#15 /usr/share/tine20/Setup/Controller.php(446): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#16 /usr/share/tine20/Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#17 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#18 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#19 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#20 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#21 /usr/share/tine20/Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#22 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Json-&gt;handle()
#23 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#24 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 08:12**

thanks! we&#039;ll provide a fix soon.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 10:25**

please remove / comment out line 426 of Tinebase/Setup/Update/Release10.php:

// Tinebase_Controller::getInstance()-&gt;rebuildPaths();

the update should now continue as expected.

we&#039;ll work on a better solution, but this should fix it for the moment.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 28 Apr 2017 12:08**

Now we have this one - I don&#039;t know if something was damaged before because of the bug and my tries to fix it or if it is something else:

fffdf setupuser - 2017-04-28T12:08:08+00:00 ERR (3): Setup_Controller::updateApplication::566 No right to access application Tinebase
fffdf setupuser - 2017-04-28T12:08:08+00:00 ERR (3): Setup_Controller::updateApplication::567 #0 /usr/share/tine20/Tinebase/Container.php(1117): Tinebase_Core::getApplicationInstance(&#039;Tinebase_Model_...&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(1066): Tinebase_Container-&gt;deleteContainerContents(Object(Tinebase_Model_Container), true)
#2 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(857): Tinebase_Container-&gt;deleteContainer(Object(Tinebase_Model_Container), true)
#3 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(810): Tinebase_Setup_Update_Release10-&gt;_moveAclFromContainersToNodes(Object(Tinebase_Record_RecordSet))
#4 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(770): Tinebase_Setup_Update_Release10-&gt;_migrateAclForApplication(Object(Tinebase_Model_Application), &#039;shared&#039;)
#5 /usr/share/tine20/Setup/Controller.php(560): Tinebase_Setup_Update_Release10-&gt;update_16()
#6 /usr/share/tine20/Setup/Controller.php(446): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#7 /usr/share/tine20/Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#8 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#9 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /usr/share/tine20/Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#13 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Json-&gt;handle()
#14 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#15 {main}
fffdf setupuser - 2017-04-28T12:08:08+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; No right to access application Tinebase

**Comment by Gloirin** [comment]
**Comment posted by gho on 28 Apr 2017 13:27**

I tried it and used the Setup.php Application. It works for me.
thanxs gho

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 15:21**

@adrian: i see. there is still a problem with acl. this should fix it (git diff format):

diff --git a/tine20/Tinebase/Container.php b/tine20/Tinebase/Container.php
index b14fe9d..4e077c4 100644
--- a/tine20/Tinebase/Container.php
+++ b/tine20/Tinebase/Container.php
@@ -1131,7 +1131,7 @@ class Tinebase_Container extends Tinebase_Backend_Sql_Abstract implements Tineba
             return;
         }
 
-        $controller = Tinebase_Core::getApplicationInstance($model);
+        $controller = Tinebase_Core::getApplicationInstance($model, /* $_modelName */ &#039;&#039;, $_ignoreACL);
 
         if ($controller) {
             if ($_ignoreAcl === TRUE &amp;&amp; method_exists($controller, &#039;doContainerACLChecks&#039;)) {

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 15:22**

i can send the whole file, if you like.

**Comment by Gloirin** [comment]
**Comment posted by adrian on 28 Apr 2017 15:58**

Did not work, but when I set $_ignoreACL to TRUE, it did.
Before, it was NULL.

cae5d setupuser - 2017-04-28T15:54:03+00:00 ERR (3): Setup_Controller::updateApplication::566 No right to access application Tinebase
cae5d setupuser - 2017-04-28T15:54:03+00:00 ERR (3): Setup_Controller::updateApplication::567 #0 /usr/share/tine20/Tinebase/Container.php(1117): Tinebase_Core::getApplicationInstance(&#039;Tinebase_Model_...&#039;, &#039;&#039;, NULL)
#1 /usr/share/tine20/Tinebase/Container.php(1066): Tinebase_Container-&gt;deleteContainerContents(Object(Tinebase_Model_Container), true)
#2 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(857): Tinebase_Container-&gt;deleteContainer(Object(Tinebase_Model_Container), true)
#3 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(810): Tinebase_Setup_Update_Release10-&gt;_moveAclFromContainersToNodes(Object(Tinebase_Record_RecordSet))
#4 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(770): Tinebase_Setup_Update_Release10-&gt;_migrateAclForApplication(Object(Tinebase_Model_Application), &#039;shared&#039;)
#5 /usr/share/tine20/Setup/Controller.php(560): Tinebase_Setup_Update_Release10-&gt;update_16()
#6 /usr/share/tine20/Setup/Controller.php(446): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#7 /usr/share/tine20/Setup/Frontend/Cli.php(245): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#8 /usr/share/tine20/Setup/Frontend/Cli.php(208): Setup_Frontend_Cli-&gt;_updateApplications()
#9 /usr/share/tine20/Setup/Frontend/Cli.php(56): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#10 /usr/share/tine20/Setup/Server/Cli.php(114): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#11 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Cli-&gt;handle()
#12 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#13 {main}

Now the Update completed with manually TRUE.

Somehow that is strange...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 17:27**

ah I managed to add a typo to the variable name ... it is $_ignoreAcl!

I&#039;ll push the fix soon.

thanks for your help!

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 12 May 2017 12:00**

https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/0f90b2f736247ab1221ba645c05ca958e3b33d67
