### ISSUE TITLE
0012992:
Tinebase not updateable

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6430]
**Reported by gho on 28 Apr 2017 07:40**

**Version:** 2017.02.3 Community Edition

When I try to update Tinebase from 10.9 to 10.20 I get:
Ihre Anfrage konnte aufgrund von fehlenden Daten nicht beantwortet werden. In den meisten Fällen wurden diese Daten von einem anderen Benutzer gelöscht. Bitte aktualisieren Sie Ihre momentane Ansicht.
All other Updates are OK. (e.g. calendar)

**Steps to reproduce:** Just update from repo:
https://packages.tine20.org/ubuntu/ xenial stable
and try to do the Tine20-setup.php Application-update

**Comment by Gloirin** [comment]
**Comment posted by gho on 28 Apr 2017 07:50**

from root-shell: php /usr/share/tine20/setup.php -c /etc/tine20/config.inc.php --update
gives:

PHP Fatal error:  Uncaught Tinebase_Exception_NotFound: User with accountId = setupuser not found. in /usr/share/tine20/Tinebase/User/Sql.php:322
Stack trace:
#0 /usr/share/tine20/Tinebase/Container.php(736): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountId&#039;, &#039;setupuser&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(419): Tinebase_Container-&gt;getDefaultContainer(&#039;Projects&#039;, &#039;setupuser&#039;)
#2 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(506): Tinebase_Container-&gt;getContainerByACL(&#039;setupuser&#039;, &#039;Projects&#039;, &#039;readGrant&#039;, true)
#3 /usr/share/tine20/Tinebase/Relations.php(603): Tinebase_Controller_Record_Abstract-&gt;getMultiple(Array, false)
#4 /usr/share/tine20/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#5 /usr/share/tine20/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#6 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelati in /usr/share/tine20/Tinebase/User/Sql.php on line 322

Fatal error: Uncaught Tinebase_Exception_NotFound: User with accountId = setupuser not found. in /usr/share/tine20/Tinebase/User/Sql.php:322
Stack trace:
#0 /usr/share/tine20/Tinebase/Container.php(736): Tinebase_User_Sql-&gt;getUserByPropertyFromSqlBackend(&#039;accountId&#039;, &#039;setupuser&#039;)
#1 /usr/share/tine20/Tinebase/Container.php(419): Tinebase_Container-&gt;getDefaultContainer(&#039;Projects&#039;, &#039;setupuser&#039;)
#2 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(506): Tinebase_Container-&gt;getContainerByACL(&#039;setupuser&#039;, &#039;Projects&#039;, &#039;readGrant&#039;, true)
#3 /usr/share/tine20/Tinebase/Relations.php(603): Tinebase_Controller_Record_Abstract-&gt;getMultiple(Array, false)
#4 /usr/share/tine20/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#5 /usr/share/tine20/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#6 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelati in /usr/share/tine20/Tinebase/User/Sql.php on line 322

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Apr 2017 10:25**

for a hotfix, see https://forge.tine20.org/view.php?id=12990#c19952
