### ISSUE TITLE
0013002:
can't save file over webdav

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6435]
**Reported by exma on 3 May 2017 11:48**

saving files over webdav crash since the 2017.02.3 release.

**Additional information:** 0471d ex - 2017-05-03T11:41:27+00:00 NOTICE (5): Tinebase_Core::errorHandler::581 Object of class Tinebase_Model_Tree_Node could not be converted to int in /usr/share/tine20/Tinebase/Model/Container.php::164 (8)
0471d ex - 2017-05-03T11:41:27+00:00 NOTICE (5): Tinebase_Core::errorHandler::582 #0 /usr/share/tine20/Tinebase/Model/Container.php(164): Tinebase_Core::errorHandler(8, &#039;Object of class...&#039;, &#039;/usr/share/tine...&#039;, 164, Array)
#1 /usr/share/tine20/Tinebase/Container.php(1261): Tinebase_Model_Container::convertContainerIdToInt(Object(Tinebase_Model_Tree_Node))
#2 /usr/share/tine20/Tinebase/WebDav/Container/Abstract.php(205): Tinebase_Container-&gt;getGrantsOfContainer(Object(Tinebase_Model_Tree_Node), true)
#3 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(487): Tinebase_WebDav_Container_Abstract-&gt;getACL()
#4 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(516): Sabre\DAVACL\Plugin-&gt;getACL(Object(Filemanager_Frontend_WebDAV_Container))
#5 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(192): Sabre\DAVACL\Plugin-&gt;getCurrentUserPrivilegeSet(&#039;webdav/Filemana...&#039;)
#6 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(783): Sabre\DAVACL\Plugin-&gt;checkPrivileges(&#039;webdav/Filemana...&#039;, &#039;{DAV:}unbind&#039;, 3)
#7 [internal function]: Sabre\DAVACL\Plugin-&gt;beforeUnbind(&#039;webdav/Filemana...&#039;)
#8 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#9 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(690): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeUnbind&#039;, Array)
#10 [internal function]: Sabre\DAV\Server-&gt;httpDelete(&#039;webdav/Filemana...&#039;)
#11 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;webdav/Filemana...&#039;)
#12 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;DELETE&#039;, &#039;webdav/Filemana...&#039;)
#13 /usr/share/tine20/Tinebase/Server/WebDAV.php(156): Sabre\DAV\Server-&gt;exec()
#14 /usr/share/tine20/Tinebase/Core.php(237): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#15 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#16 {main}
26b4f ex - 2017-05-03T11:41:27+00:00 NOTICE (5): Tinebase_Core::errorHandler::581 Object of class Tinebase_Model_Tree_Node could not be converted to int in /usr/share/tine20/Tinebase/Model/Container.php::164 (8)
26b4f ex - 2017-05-03T11:41:27+00:00 NOTICE (5): Tinebase_Core::errorHandler::582 #0 /usr/share/tine20/Tinebase/Model/Container.php(164): Tinebase_Core::errorHandler(8, &#039;Object of class...&#039;, &#039;/usr/share/tine...&#039;, 164, Array)
#1 /usr/share/tine20/Tinebase/Container.php(1261): Tinebase_Model_Container::convertContainerIdToInt(Object(Tinebase_Model_Tree_Node))
#2 /usr/share/tine20/Tinebase/WebDav/Container/Abstract.php(205): Tinebase_Container-&gt;getGrantsOfContainer(Object(Tinebase_Model_Tree_Node), true)
#3 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(487): Tinebase_WebDav_Container_Abstract-&gt;getACL()
#4 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(516): Sabre\DAVACL\Plugin-&gt;getACL(Object(Filemanager_Frontend_WebDAV_Container))
#5 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(192): Sabre\DAVACL\Plugin-&gt;getCurrentUserPrivilegeSet(&#039;webdav/Filemana...&#039;)
#6 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(767): Sabre\DAVACL\Plugin-&gt;checkPrivileges(&#039;webdav/Filemana...&#039;, &#039;{DAV:}bind&#039;)
#7 [internal function]: Sabre\DAVACL\Plugin-&gt;beforeBind(&#039;webdav/Filemana...&#039;)
#8 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#9 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1638): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeBind&#039;, Array)
#10 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server-&gt;createFile(&#039;webdav/Filemana...&#039;, Resource id #3, NULL)
#11 [internal function]: Sabre\DAV\Server-&gt;httpPut(&#039;webdav/Filemana...&#039;)
#12 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;webdav/Filemana...&#039;)
#13 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;webdav/Filemana...&#039;)
#14 /usr/share/tine20/Tinebase/Server/WebDAV.php(156): Sabre\DAV\Server-&gt;exec()
#15 /usr/share/tine20/Tinebase/Core.php(237): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#16 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#17 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2017 12:35**

i can reproduce the problem and will work on a fix.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2017 12:48**

http://gerrit.tine20.com/customers/4615

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 May 2017 14:59**

attached a patch for this problem.
