### ISSUE TITLE
0013064:
Tinebase Update from 10.9 to 10.20 not working, Tine 2.0 completely offline, even after applying patch 0012990

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6466]
**Reported by bluesilisk on 13 May 2017 09:02**

**Version:** 2017.02.3 Community Edition

I had the problem described i ticket 0012990. After applying these changes, I get a different error and cannot update Tinebase.

**Steps to reproduce:** root@tine20:~# php /usr/share/tine20/setup.php -c /etc/tine20/config.inc.php --update

or

use &quot;Update application&quot; after login in the tine20/setup.php page using tine20setup account

**Additional information:** output of the php command line call mentioned above:

root@tine20:~# php /usr/share/tine20/setup.php -c /etc/tine20/config.inc.php --update
PHP Fatal error:  Uncaught Tinebase_Exception_NotFound: No Application Controller found (checked class Projects_Controller_Project)! in /usr/share/tine20/Tinebase/Core.php:391
Stack trace:
#0 /usr/share/tine20/Tinebase/Relations.php(601): Tinebase_Core::getApplicationInstance(&#039;Projects_Model_...&#039;)
#1 /usr/share/tine20/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#2 /usr/share/tine20/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#3 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#4 /usr/share/tine20/Tinebase/Record/Iterator.php(196): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), NULL)
#5 /usr/share/tine20/Tinebase/Record/Iterator.php(142): Tinebase_Record_Iterator-&gt;_getRecords()
#6 /usr/share/tine20 in /usr/share/tine20/Tinebase/Core.php on line 391

Fatal error: Uncaught Tinebase_Exception_NotFound: No Application Controller found (checked class Projects_Controller_Project)! in /usr/share/tine20/Tinebase/Core.php:391
Stack trace:
#0 /usr/share/tine20/Tinebase/Relations.php(601): Tinebase_Core::getApplicationInstance(&#039;Projects_Model_...&#039;)
#1 /usr/share/tine20/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#2 /usr/share/tine20/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#3 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#4 /usr/share/tine20/Tinebase/Record/Iterator.php(196): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), NULL)
#5 /usr/share/tine20/Tinebase/Record/Iterator.php(142): Tinebase_Record_Iterator-&gt;_getRecords()
#6 /usr/share/tine20 in /usr/share/tine20/Tinebase/Core.php on line 391

contents of /var/tine20/tine20.log after trying to update Tinebase using web-login at tine20/setup.php

8490b setupuser - 2017-05-13T08:43:41+00:00 ERR (3): Setup_Controller::updateApplication::566 No Application Controller found (checked class Projects_Controller_Project)!
8490b setupuser - 2017-05-13T08:43:41+00:00 ERR (3): Setup_Controller::updateApplication::567 #0 /usr/share/tine20/Tinebase/Relations.php(601): Tinebase_Core::getApplicationInstance(&#039;Projects_Model_...&#039;)
#1 /usr/share/tine20/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false)
#2 /usr/share/tine20/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#3 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL)
#4 /usr/share/tine20/Tinebase/Record/Iterator.php(196): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), NULL)
#5 /usr/share/tine20/Tinebase/Record/Iterator.php(142): Tinebase_Record_Iterator-&gt;_getRecords()
#6 /usr/share/tine20/Tinebase/Controller.php(808): Tinebase_Record_Iterator-&gt;iterate()
#7 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(430): Tinebase_Controller-&gt;rebuildPaths()
#8 /usr/share/tine20/Setup/Controller.php(560): Tinebase_Setup_Update_Release10-&gt;update_9()
#9 /usr/share/tine20/Setup/Controller.php(446): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#10 /usr/share/tine20/Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#11 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json-&gt;updateApplications(Array)
#12 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#14 /usr/share/tine20/Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#15 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Json-&gt;handle()
#16 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#17 {main}
8490b setupuser - 2017-05-13T08:43:41+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; No Application Controller found (checked class Projects_Controller_Project)!

installed packages

root@tine20:~# dpkg -l|grep tine20
ii  tine20                             2017.02.3-1.1604                           all          webbased groupware and crm - metapackage
ii  tine20-activesync                  2017.02.3-1.1604                           all          webbased groupware and crm - activesync module
ii  tine20-allapps                     2017.02.3-1.1604                           all          All Tine 2.0 applications
ii  tine20-calendar                    2017.02.3-1.1604                           all          webbased groupware and crm - calendar module
ii  tine20-crm                         2017.02.3-1.1604                           all          webbased groupware and crm - crm module
ii  tine20-events                      2017.02.3-1.1604                           all          webbased groupware and crm - events module
ii  tine20-felamimail                  2017.02.3-1.1604                           all          webbased groupware and crm - email module
ii  tine20-filemanager                 2017.02.3-1.1604                           all          webbased groupware and crm - filemanager module
ii  tine20-humanresources              2017.02.3-1.1604                           all          webbased groupware and crm - humanresources module
ii  tine20-inventory                   2017.02.3-1.1604                           all          webbased groupware and crm - inventory module
ii  tine20-libraries                   2017.02.3-1.1604                           all          Additional libraries needed by Tine 2.0
ii  tine20-mailfiler                   2017.02.3-1.1604                           all          webbased groupware and crm - mailfiler module
ii  tine20-sales                       2017.02.3-1.1604                           all          webbased groupware and crm - sales module
ii  tine20-tasks                       2017.02.3-1.1604                           all          webbased groupware and crm - tasks module
ii  tine20-timetracker                 2017.02.3-1.1604                           all          webbased groupware and crm - timetracker module
ii  tine20-tinebase                    2017.02.3-1.1604                           all          webbased groupware and crm - core + addressbook module
ii  tine20-webstack                    2017.02.3-1.1604                           all          Tine 2.0 webserver integration package

php version:

root@tine20:~# php --version
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Gloirin** [comment]
Related to #6429

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 17 May 2017 08:20**

http://gerrit.tine20.com/customers/#/c/4684/

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 17 May 2017 10:43**

Hello,

thank you for reporting this issue.

It seems that your installation has relations to models of the application &quot;projects&quot;. But that application seems not to be installed or not to be present. We improved application uninstallment in 2016.09 Can you recall if you uninstalled your &quot;projects&quot; application after upgrading to 2016.09 or before? Or did you maybe just delete the source code folder &quot;Projects&quot;?

Your problem should go away if you call
tine20-cli --method=Tinebase.cleanRelations

it should output
Deleted N relations in total

with N &gt; 0

after that you should be able to update.

In addition find attached a patch that will handle your data inconsistency more gracefully (though I recommend to clean your relations anyway). Please go to the directory containing your tine20 installation directory (maybe /usr/share/ if it is installed in /usr/share/tine20) and apply the path with
&quot;git apply /path/to/patch&quot;

best regards
Paul Mehrer
