### ISSUE TITLE
0013106:
Update Tinebase from 10.16 to 10.24 fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6486]
**Reported by ingoratsdorf on 20 May 2017 00:03**

Tinebase introduced a filesystem preview in 10.23, however during upgrade from 10.16 to 10.17 there is a call for filesystem.stat that will fail as Tinebase tries a DB JOIN LEFT with the preview field and subsequently fails (as preview db field will only be added in 10.23.
The stat() call in enclosed in try..catch but only catches ExceptionNotFound, not DB exceptions, hence the upgrade fails with an uncaught exception.

**Steps to reproduce:** Tinabase/Setup/Update/Release10.php, line 803:
    protected function _migrateAclForApplication($application, $type)
    {
        $path = Tinebase_FileSystem::getInstance()-&gt;getApplicationBasePath(
            $application-&gt;name,
            $type
        );
        try {
            $parentNode = Tinebase_FileSystem::getInstance()-&gt;stat($path);
        } catch (Exception $tenf) {
            // changed from Exception_NotFound to Exception as there can be other exceptions happening like db fields not found etc
            return;
        }

**Additional information:** 51b87 setupuser - 2017-05-19T23:51:25+00:00 ERR (3): Setup_Controller::updateApplication::572 SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;tree_filerevisions.preview_count&#039; in &#039;field list&#039;, query was: SELECT `tree_nodes`.*, `tree_fileobjects`.`type`, `tree_fileobjects`.`created_by`, `tree_fileobjects`.`creation_time`, `tree_fileobjects`.`last_modified_by`, `tree_fileobjects`.`last_modified_time`, `tree_fileobjects`.`revision`, `tree_fileobjects`.`contenttype`, `tree_fileobjects`.`revision_size`, `tree_fileobjects`.`indexed_hash`, `tree_fileobjects`.`description`, `tree_filerevisions`.`hash`, `tree_filerevisions`.`size`, `tree_filerevisions`.`preview_count`, GROUP_CONCAT( DISTINCT `tree_filerevisions2`.`revision`) AS `available_revisions` FROM `tine20_tree_nodes` AS `tree_nodes`
 LEFT JOIN `tine20_tree_fileobjects` AS `tree_fileobjects` ON `tree_nodes`.`object_id` = `tree_fileobjects`.`id`
 LEFT JOIN `tine20_tree_filerevisions` AS `tree_filerevisions` ON `tree_fileobjects`.`id` = `tree_filerevisions`.`id` AND `tree_filerevisions`.`revision` = `tree_fileobjects`.`revision`
 LEFT JOIN `tine20_tree_filerevisions` AS `tree_filerevisions2` ON `tree_fileobjects`.`id` = `tree_filerevisions2`.`id` WHERE ((`tree_nodes`.`parent_id`  IS NULL)) AND ((`tree_nodes`.`name`  LIKE (&#039;0bec96ebadb4a70730f692d8210d25e64c40e22d&#039;))) GROUP BY `tree_nodes`.`object_id`
51b87 setupuser - 2017-05-19T23:51:25+00:00 ERR (3): Setup_Controller::updateApplication::573 #0 /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#2 /var/wwwroot/tine20-git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;SELECT `tree_no...&#039;, Array)
#3 /var/wwwroot/tine20-git/tine20/Tinebase/Backend/Sql/Abstract.php(762): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /var/wwwroot/tine20-git/tine20/Tinebase/Backend/Sql/Abstract.php(542): Tinebase_Backend_Sql_Abstract-&gt;_fetch(Object(Zend_Db_Select), &#039;fetch_all&#039;)
#5 /var/wwwroot/tine20-git/tine20/Tinebase/Tree/Node.php(258): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Tinebase_Model_Tree_Node_Filter))
#6 /var/wwwroot/tine20-git/tine20/Tinebase/FileSystem.php(1239): Tinebase_Tree_Node-&gt;getChild(NULL, &#039;0bec96ebadb4a70...&#039;)
#7 /var/wwwroot/tine20-git/tine20/Tinebase/Setup/Update/Release10.php(810): Tinebase_FileSystem-&gt;stat(&#039;/0bec96ebadb4a7...&#039;)
#8 /var/wwwroot/tine20-git/tine20/Tinebase/Setup/Update/Release10.php(792): Tinebase_Setup_Update_Release10-&gt;_migrateAclForApplication(Object(Tinebase_Model_Application), &#039;personal&#039;)
#9 /var/wwwroot/tine20-git/tine20/Setup/Controller.php(566): Tinebase_Setup_Update_Release10-&gt;update_16()

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 May 2017 15:42**

http://gerrit.tine20.com/customers/#/c/4712/

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 May 2017 15:45**

problem should now be fixed in the master, too.

see https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/2767f35bc867ff5b8b7b9efe82b5e45c4b7b1e72
