### ISSUE TITLE
0013288:
Calendar update fails with "no permission"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6575]
**Reported by pschuele on 3 Jul 2017 09:04**

Calendar update fails with &quot;no permission&quot;

**Additional information:** 940fb setupuser - 2017-07-03T08:16:10+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; No Permission.
940fb setupuser - 2017-07-03T08:16:10+00:00 ERR (3): Setup_Controller::updateApplication::574 No Permission.
940fb setupuser - 2017-07-03T08:16:10+00:00 ERR (3): Setup_Controller::updateApplication::575 #0 /usr/share/tine20/Calendar/Controller/Resource.php(185): Tinebase_Controller_Record_Abstract-&gt;_checkGrant(Object(Calendar_Model_Resource), &#039;get&#039;, true, &#039;No Permission.&#039;, NULL)
#1 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(425): Calendar_Controller_Resource-&gt;_checkGrant(Object(Calendar_Model_Resource), &#039;get&#039;)
#2 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(946): Tinebase_Controller_Record_Abstract-&gt;get(&#039;7c7dfbe276c2f5d...&#039;)
#3 /usr/share/tine20/Calendar/Controller/Resource.php(178): Tinebase_Controller_Record_Abstract-&gt;update(Object(Calendar_Model_Resource))
#4 /usr/share/tine20/Calendar/Setup/Update/Release10.php(68): Calendar_Controller_Resource-&gt;update(Object(Calendar_Model_Resource))
#5 /usr/share/tine20/Setup/Controller.php(568): Calendar_Setup_Update_Release10-&gt;update_2()
#6 /usr/share/tine20/Setup/Controller.php(462): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#7 /usr/share/tine20/Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#8 [internal function]: Setup_Frontend_Json-&gt;updateApplications(Array)
#9 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#10 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#11 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#12 /usr/share/tine20/Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request_Http))
#13 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Json-&gt;handle()
#14 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#15 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2017 09:12**

http://gerrit.tine20.com/customers/4990

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2017 09:13**

uploaded a fixed version of Calendar/Setup/Update/Release10.php
