### ISSUE TITLE
0013298:
"Setup Admin undefined" when updating Tinebase 10.9 ? 10.28

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6580]
**Reported by marosh on 3 Jul 2017 16:01**

**Version:** 2017.02.5 Community Edition

When trying to update Tinebase from Version 10.9 to 10.28, an error occurs with title&quot;Setup admin undefined&quot;. Tried after fresh install of 2017.02.5 Community Version.

**Steps to reproduce:** 1. Unzip new allinone tarball to folder
2. Log into setup.php
3. Try to update

**Additional information:** Crash dump (manually formatted for better readability):
illegal json data in response

Fatal error: Uncaught Error: Call to a member function getIndexById() on null in /var/www/&lt;domain&gt;/mail/Tinebase/Relations.php:636

Stack trace: 
#0 /var/www/marian-felder.de/mail/Tinebase/Relations.php(411): Tinebase_Relations-&gt;resolveAppRecords(Object(Tinebase_Record_RecordSet), false) 
#1 /var/www/marian-felder.de/mail/Tinebase/Relations.php(437): Tinebase_Relations-&gt;getRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL) 
#2 /var/www/marian-felder.de/mail/Tinebase/Controller/Record/Abstract.php(224): Tinebase_Relations-&gt;getMultipleRelations(&#039;Addressbook_Mod...&#039;, &#039;Sql&#039;, Array, NULL, Array, false, NULL) 
#3 /var/www/marian-felder.de/mail/Tinebase/Record/Iterator.php(196): Tinebase_Controller_Record_Abstract-&gt;search(Object(Addressbook_Model_ContactFilter), Object(Tinebase_Model_Pagination), NULL) 
#4 /var/www/marian-felder.de/mail/Tinebase/Record/Iterator.php(142): Tinebase_Record_Iterator-&gt;_getRecords() 
#5 /var/www/marian-felder.de/mail/Tinebase/Controller.php(808): Tinebase_Record_Iterator-&gt;iterate in /var/www/&lt;domain&gt;/mail/Tinebase/Relations.php on line 636

**Comment by Gloirin** [comment]
**Comment posted by marosh on 3 Jul 2017 16:06**

Update: This also affects the updates of Felamimail and Timetracker.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2017 19:20**

http://gerrit.tine20.com/customers/5001

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Jul 2017 19:21**

that is a strange error ... could you please try again with the attached Tinebase/Relations.php ?

**Comment by Gloirin** [comment]
**Comment posted by marosh on 4 Jul 2017 08:38**

Thank you pschuele, the new file does the trick. Can I leave it in place or should I substitute it back with the old one?

**Comment by Gloirin** [comment]
**Comment posted by marosh on 4 Jul 2017 08:39**

Provided &quot;Tinebase/Relations.php&quot; solves the issue.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jul 2017 07:48**

&gt; Thank you pschuele, the new file does the trick. Can I leave it in place or should I substitute it back with the old one?

you can leave it there.

glad that it helps :)
