### ISSUE TITLE
0013322:
Update from 10.16 -> 10.28 fails

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6591]
**Reported by mspahn on 10 Jul 2017 08:14**

62d76 setupuser - 2017-07-08T17:02:49+00:00 WARN (4): Tinebase_Server_Json::_handleException::368 Tinebase_Exception_NotFound -&gt; No Application Controller found (checked class Tinebase_Node)!
62d76 setupuser - 2017-07-08T17:02:49+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; No Application Controller found (checked class Tinebase_Node)!
7b5b7 setupuser - 2017-07-08T17:07:34+00:00 ERR (3): Setup_Controller::updateApplication::574 No Application Controller found (checked class Tinebase_Node)!
7b5b7 setupuser - 2017-07-08T17:07:34+00:00 ERR (3): Setup_Controller::updateApplication::575 #0 /usr/share/tine20/Tinebase/Container.php(1146): Tinebase_Core::getApplicationInstance(&#039;Tinebase_Model_...&#039;, &#039;&#039;, true)
#1 /usr/share/tine20/Tinebase/Container.php(1095): Tinebase_Container-&gt;deleteContainerContents(Object(Tinebase_Model_Container), true)
#2 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(882): Tinebase_Container-&gt;deleteContainer(Object(Tinebase_Model_Container), true)
#3 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(831): Tinebase_Setup_Update_Release10-&gt;_moveAclFromContainersToNodes(Object(Tinebase_Record_RecordSet))
#4 /usr/share/tine20/Tinebase/Setup/Update/Release10.php(794): Tinebase_Setup_Update_Release10-&gt;_migrateAclForApplication(Object(Tinebase_Model_Application), &#039;personal&#039;)
#5 /usr/share/tine20/Setup/Controller.php(568): Tinebase_Setup_Update_Release10-&gt;update_16()
#6 /usr/share/tine20/Setup/Controller.php(454): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;10&#039;)
#7 /usr/share/tine20/Setup/Frontend/Cli.php(257): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#8 /usr/share/tine20/Setup/Frontend/Cli.php(220): Setup_Frontend_Cli-&gt;_updateApplications()
#9 /usr/share/tine20/Setup/Frontend/Cli.php(56): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#10 /usr/share/tine20/Setup/Server/Cli.php(114): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#11 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Cli-&gt;handle()
#12 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()

**Additional information:** https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=18484

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 7 Aug 2017 13:16**

Hello,

this looks like as there would be entries in the table tine20_container with the column &#039;model&#039; set to &#039;Tinebase_Model_Node&#039;

Can you please send the result of this query
SELECT distinct model FROM tine20_container;

If this would be true. it can be resolved by executing this query:
UPDATE tine20_container SET model = &#039;Tinebase_Model_Tree_Node&#039; WHERE model = &#039;Tinebase_Model_Node&#039;;

If this does not work, the logs at least on INFO, better on DEBUG would be nice (after the update was executed)

best regards
Paul

**Comment by Gloirin** [comment]
**Comment posted by admin4 on 20 Aug 2017 19:25**

The above SQL Statementhas solved the problem. Thx

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 1 Sep 2017 07:36**

http://gerrit.tine20.com/customers/5579
