### ISSUE TITLE
0013406:
Crash when  trying to upgrade database from 2017.02.05 to 2017.08.03

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6632]
**Reported by csvarer on 29 Aug 2017 21:08**

**Version:** 2017.08.3 Community Edition

Hi
I have just tried to upgrade between the two versions mentioned above. Unfortunately, the upgrade of the database doesn&#039;t succeed but crashes in the middle of the update process with a message like:

neuro:/home/srv/www/vhosts/tine # php setup.php --update
PHP Fatal error:  Uncaught exception &#039;PDOException&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20db`.`#sql-230e_4`, CONSTRAINT `tine20_container_content::container_id--container::id` FOREIGN KEY (`container_id`) REFERENCES `tine20_container` (`id`) ON DELETE CASCADE)&#039; in /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039; in /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught exception &#039;PDOException&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20db`.`#sql-230e_4`, CONSTRAINT `tine20_container_content::container_id--container::id` FOREIGN KEY (`container_id`) REFERENCES `tine20_container` (`id`) ON DELETE CASCADE)&#039; in /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039; in /home/srv/www/vhosts/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

do you have an idea of how to correct for that?

Best regards
Claus

**Comment by Gloirin** [comment]
**Comment posted by csvarer on 11 Sep 2017 07:49**

I got the idea that it perhpas helped deleting the files in the cache, session and tmp files before trying the update and it did. I don&#039;t know if it was because I did run the &quot;php setup.php --update&quot; as root where the apache server that normally uses these files is runned as the apache user &quot;wwwrun&quot;, but it helped and vers 2017.08.3 is running åerfectly well

**Comment by Gloirin** [comment]
**Comment posted by csvarer on 11 Sep 2017 07:51**

As described in note, solution was to delete the files in cache, session and tmp directories before running the database update script

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Sep 2017 12:13**

ok, thanks for the update. we&#039;ll think about adding the clearing if cache/session/tmp to the update process, too.
