### ISSUE TITLE
0013472:
Apple-Kalender synchronisiert über CalDAV nicht wenn Tabellenprefix nicht tine20_ ist

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6664]
**Reported by torran on 21 Sep 2017 23:30**

**Version:** 2017.08.5 Community Edition

Der Apple-Kalender liefert die Fehlermeldung (CalDAVAccountRefreshQueueableOperation) bei einem Sync mit CalDAV wenn für die Tine20-Installation ein anderer Tabellenprefix als &quot;tine20_&quot; konfiguriert ist.

FIX:
in /Calendar/Frontend/CalDAV/SpeedUpPropfindPlugin.php muss im SQL-Statement ab Zeile 173 der Tabellenprefix aus der Konfiguration eingesetzt werden. Hier ist tine20 hardgecodet.

**Additional information:** [21-Sep-2017 23:06:02 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;db.tine20_cal_events&#039; doesn&#039;t exist in /vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;SELECT ev.id, e...&#039;, Array)
#4/Calendar/Frontend/CalDAV/SpeedUpPropfindPlugin.php(175): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;SELE in/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Sep 2017 06:50**

danke für den hinweis, werden wir fixen!
