### ISSUE TITLE
0013476:
Update Error 2017.08.3 -> 2017.08.5

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6666]
**Reported by dl6mra on 22 Sep 2017 13:17**

**Version:** 2017.08.5 Community Edition

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name &#039;xprops&#039; in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/html/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#5 /var/www/html/Setup/Backend/Mysql.php(212): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#6 /var/www/html/Tinebase/Setup/Update/Release10.php(2058) in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name &#039;xprops&#039; in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
#1 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#2 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
#3 /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/html/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#5 /var/www/html/Setup/Backend/Mysql.php(212): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#6 /var/www/html/Tinebase/Setup/Update/Release10.php(2058) in /var/www/html/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

**Additional information:** Update Error 2017.08.3 -&gt; 2017.08.5 Tinebase

**Comment by Gloirin** [comment]
**Comment posted by dl6mra on 22 Sep 2017 17:57**

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name &#039;xprops&#039;, query was: ALTER TABLE `tine20_accounts` ADD COLUMN `xprops` text(65535)

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Setup/Backend/Mysql.php(212): Setup_Backend_Abstract-&gt;execQueryVoid()
.../Tinebase/Setup/Update/Release10.php(2058): Setup_Backend_Mysql-&gt;addCol()
.../Tinebase/Setup/Update/Release11.php(21): Tinebase_Setup_Update_Release10-&gt;update_42()
.../Setup/Controller.php(576): Tinebase_Setup_Update_Release11-&gt;update_0()
.../Setup/Controller.php(461): Setup_Controller-&gt;updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller-&gt;updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json-&gt;updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract-&gt;_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server-&gt;handle()
.../Setup/Core.php(115): Setup_Server_Json-&gt;handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 25 Sep 2017 10:45**

https://gerrit.tine20.com/customers/#/c/5821/

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 25 Sep 2017 10:47**

Thank you for reporting this issue.

You can fix it by replacing the function update_42 with the one posted below in the file Tinebase/Setup/Update/Release10.php line 2049ff

public function update_42()
    {
        if ($this-&gt;_backend-&gt;columnExists(&#039;configuration&#039;, &#039;accounts&#039;)) {
            $this-&gt;_backend-&gt;dropCol(&#039;accounts&#039;, &#039;configuration&#039;);
        }
        if (!$this-&gt;_backend-&gt;columnExists(&#039;xprops&#039;, &#039;accounts&#039;)) {
            $this-&gt;_backend-&gt;addCol(&#039;accounts&#039;, new Setup_Backend_Schema_Field_Xml(&#039;&lt;field&gt;
                    &lt;name&gt;xprops&lt;/name&gt;
                    &lt;type&gt;text&lt;/type&gt;
                    &lt;length&gt;65535&lt;/length&gt;
                &lt;/field&gt;&#039;));
        }
        if ($this-&gt;getTableVersion(&#039;accounts&#039;) &lt; 14) {
            $this-&gt;setTableVersion(&#039;accounts&#039;, 14);
        }

        $this-&gt;setApplicationVersion(&#039;Tinebase&#039;, &#039;10.43&#039;);
    }
