### ISSUE TITLE
0013478:
Update from 2017.08.3 to 5 fails (action queue problem)

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6667]
**Reported by mspahn on 23 Sep 2017 22:53**

**Version:** 2017.08.5 Community Edition

Update from a clean 8.3 install fails to 8.5 update. This is not supposed to happen.

**Additional information:** root@vulcan ~www/tine.****.me/tine20_20170805 # php setup.php --update

PHP Fatal error:  Uncaught Tinebase_Exception: waited for Action Queue to become empty for more than 300 sec in /var/www/tine.****.me/tine20_20170805/Setup/Controller.php:677
Stack trace:
#0 /var/www/tine.****.me/tine20_20170805/Setup/Controller.php(559): Setup_Controller-&gt;_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /var/www/tine.****.me/tine20_20170805/Setup/Controller.php(461): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;11&#039;)
#2 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(302): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#3 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(258): Setup_Frontend_Cli-&gt;_updateApplications()
#4 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(66): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#5 /var/www/tine.****.me/tine20_20170805/Setup/Server/Cli.php(119): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#6 /var/www/tine.****.me/tine20_20170805/Setup/Core.php(115):  in /var/www/tine.****.me/tine20_20170805/Setup/Controller.php on line 677

Fatal error: Uncaught Tinebase_Exception: waited for Action Queue to become empty for more than 300 sec in /var/www/tine.****.me/tine20_20170805/Setup/Controller.php:677
Stack trace:
#0 /var/www/tine.****.me/tine20_20170805/Setup/Controller.php(559): Setup_Controller-&gt;_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /var/www/tine.****.me/tine20_20170805/Setup/Controller.php(461): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;11&#039;)
#2 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(302): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#3 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(258): Setup_Frontend_Cli-&gt;_updateApplications()
#4 /var/www/tine.****.me/tine20_20170805/Setup/Frontend/Cli.php(66): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#5 /var/www/tine.****.me/tine20_20170805/Setup/Server/Cli.php(119): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#6 /var/www/tine.****.me/tine20_20170805/Setup/Core.php(115):  in /var/www/tine.****.me/tine20_20170805/Setup/Controller.php on line 677
php setup.php --update  5.02s user 6.84s system 3% cpu 4:59.89 total
root has logged on pts/1 from 77.20.148.145.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Sep 2017 09:16**

- do you use the action queue?
- is it configured properly?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Oct 2017 14:29**

works as expected - queue setup should be documented.
