### ISSUE TITLE
0013570:
Getting "service unavailable" window on login screen after upgrade from version 2017.02.5 to 2017.08.7

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6712]
**Reported by ainiesta on 19 Oct 2017 22:27**

**Version:** 2017.08.7 Community Edition

Hi all. I recently upgraded to the latest version 2017.08.7 (from 2017.02.5) after getting the message &quot;critical update available&quot;. The issue I am facing is that after I successfully upgraded to the new version, I am log in to the application with any user name and password and the &quot;service unavailable&quot; message window appears, not allowing me to log in. I have never experienced this issue before, and I am following the normal steps for updating the application as usual. I can&#039;t find any message related to this problem in the log file either. I am afraid it might be something related to the configuration or the database but I have no clue which is the root cause. Thanks in advance for your help.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Oct 2017 07:05**

hi,

there should be some clue about the error in either the tine20.log or your webserver error.log. please have a look and post the error here.

**Comment by Gloirin** [comment]
**Comment posted by ainiesta on 20 Oct 2017 15:25**

Hi, and thanks for you quick answer. First of all, I don&#039;t see anything written in the tine20.log since September 25th. After I checked error.log file of Apache, it turns out there is something wrong with the tine 20 logger. This is the error I am getting and repeating for all the clients every a few minutes:

[Tue Oct 17 23:47:49.681070 2017] [:error] [pid 1433] [client 192.168.42.26:54678] Tine 2.0 can&#039;t setup the configured logger! The Server responded: exception &#039;Zend_Log_Exception&#039; with message &#039;&quot;/var/log/tine20/tine20.log&quot; cannot be opened with mode &quot;a&quot;&#039; in /srv/www/tine20/vendor/zendframework/zendframework1/library/Zend/Log/Writer/Stream.php:81\nStack trace:\n#0 /srv/www/tine20/Tinebase/Log.php(122): Zend_Log_Writer_Stream-&gt;__construct(&#039;/var/log/tine20...&#039;)\n#1 /srv/www/tine20/Tinebase/Core.php(647): Tinebase_Log-&gt;addWriterByConfig(Object(Tinebase_Config_Struct))\n#2 /srv/www/tine20/Tinebase/Core.php(1350): Tinebase_Core::setupLogger()\n#3 /srv/www/tine20/Tinebase/Exception.php(100): Tinebase_Core::getLogger()\n#4 /srv/www/tine20/Tinebase/Core.php(807): Tinebase_Exception::log(Object(Zend_Cache_Exception))\n#5 /srv/www/tine20/Tinebase/Core.php(1365): Tinebase_Core::setupCache()\n#6 /srv/www/tine20/Tinebase/Core.php(1656): Tinebase_Core::getCache()\n#7 /srv/www/tine20/Tinebase/Core.php(1724): Tinebase_Core::_searchServerPlugins()\n#8 /srv/www/tine20/Tinebase/Core.php(255): Tinebase_Core::_getServerPlugins()\n#9 /srv/www/tine20/Tinebase/Core.php(235): Tinebase_Core::getDispatchServer(Object(Zend\\Http\\PhpEnvironment\\Request))\n#10 /srv/www/tine20/index.php(18): Tinebase_Core::dispatchRequest()\n#11 {main}, referer: http://leopard.cats/tine20/

**Comment by Gloirin** [comment]
**Comment posted by ainiesta on 20 Oct 2017 19:13**

No worries at all. I figured it out. The /var/lib/tine20 and /var/log/tine20 had the wrong ownerships (root), once I changed it to www-data (apache&#039;s user) all is good. Anyways, thanks for the guidance/assistance. :)

**Comment by Gloirin** [comment]
**Comment posted by ainiesta on 20 Oct 2017 19:32**

The /var/lib/tine20 and /var/log/tine20 folders had the wrong ownerships (root) for some reason, and once I changed it to &quot;www-data&quot; (apache&#039;s user) all was fine, and I was able to log in to the newest version 2017.08.8.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Nov 2017 09:32**

ok, thanks for the update on this :)
