### ISSUE TITLE
0013576:
support PHP 7.2

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6715]
**Reported by ingoratsdorf on 22 Oct 2017 01:18**

**Version:** git master

PHP7.2: The each() function is deprecated.

Tinebase_Core::errorHandler::579 The each() function is deprecated. This message will be suppressed on further calls in /var/wwwroot/tine20/vendor/zendframework/zendframework1/library/Zend/Cache/Backend.php::79 (8192)
Tinebase_Core::errorHandler::580 #0 [internal function]: Tinebase_Core::errorHandler(8192, &#039;The each() func...&#039;, &#039;/var/wwwroot/ti...&#039;, 79, Array)
#1 /var/wwwroot/tine20/vendor/zendframework/zendframework1/library/Zend/Cache/Backend.php(79): each(Array)
#2 /var/wwwroot/tine20/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php(363): Zend_Cache_Backend-&gt;setDirectives(Array)
#3 /var/wwwroot/tine20/vendor/zendframework/zendframework1/library/Zend/Cache/Core.php(183): Zend_Cache_Backend_Redis-&gt;setDirectives(Array)
#4 /var/wwwroot/tine20/vendor/zendframework/zendframework1/library/Zend/Cache.php(111): Zend_Cache_Core-&gt;setBackend(Object(Zend_Cache_Backend_Redis))
#5 /var/wwwroot/tine20/Tinebase/Core.php(802): Zend_Cache::factory(&#039;Core&#039;, &#039;Redis&#039;, Array, Array)
#6 /var/wwwroot/tine20/Tinebase/Core.php(1363): Tinebase_Core::setupCache()
#7 /var/wwwroot/tine20/Tinebase/Core.php(1676): Tinebase_Core::getCache()
#8 /var/wwwroot/tine20/Tinebase/Core.php(1744): Tinebase_Core::_searchServerPlugins()
#9 /var/wwwroot/tine20/Tinebase/Core.php(255): Tinebase_Core::_getServerPlugins()
#10 /var/wwwroot/tine20/Tinebase/Core.php(235): Tinebase_Core::getDispatchServer(Object(Zend\Http\PhpEnvironment\Request))
#11 /var/wwwroot/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#12 {main}

**Steps to reproduce:** Update from PHP7.1 to 7.2

**Additional information:** This will fix it:

    public function setDirectives($directives)
    {
        if (!is_array($directives)) Zend_Cache::throwException(&#039;Directives parameter must be an array&#039;);
        foreach ($directives as $name =&gt; $value) {
//        while (list($name, $value) = each($directives)) {
            if (!is_string($name)) {
                Zend_Cache::throwException(&quot;Incorrect option name : $name&quot;);
            }
            $name = strtolower($name);
            if (array_key_exists($name, $this-&gt;_directives)) {
                $this-&gt;_directives[$name] = $value;
            }

        }

        $this-&gt;_loggerSanity();
    }

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 22 Oct 2017 22:46**

Found some more, created https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/pull/29

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Nov 2017 09:33**

thanks for the PR. I&#039;ll merge that after a short review.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Nov 2017 10:45**

https://gerrit.tine20.com/customers/6203

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Dec 2017 07:54**

postponed this. there is lot&#039;s of stuff to be changed for php 7.2 :(

**Comment by Gloirin** [comment]
**Comment posted by frozn on 14 Feb 2018 20:23**

after fixing the following functions (interface errors) it works fine under php 7.2 so far:

\tine\Tasks\Controller\Task.php -&gt; create/update
\tine\Tinebase\Acl\Roles.php -&gt; getMultiple
\tine\Tinebase\PersistentFilter.php -&gt; create
\tine\Calendar\Controller\Resource.php -&gt; create

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Feb 2018 13:38**

ok, great.

i think, i&#039;ll finish the change until the next release (2018.02.2).
