### ISSUE TITLE
0013668:
Update Error when Container "Internal Contacts" has been renamed

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6760]
**Reported by weberho on 20 Dec 2017 08:10**

**Version:** 2017.08.10 Community Edition

Updating from 2017.08.9 to 2017.08.10 fails when the Container &quot;Internal Contacts&quot; has been renamed to &quot;Interne Kontakte&quot;. Don&#039;t know when/how this renaming happened but it must have been a long time ago. After going back to an old verion, renaming the container and upgrading again everything works nicely.

The stack-trace is:
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Container Internal Contacts not found.&#039; in /usr/share/tine20/Tinebase/Container.php:619
Stack trace:
#0 /usr/share/tine20/Addressbook/Setup/Initialize.php(246): Tinebase_Container-&gt;getContainerByName(&#039;Addressbook&#039;, &#039;Internal Contac...&#039;, &#039;shared&#039;)
#1 /usr/share/tine20/Admin/Controller/User.php(453): Addressbook_Setup_Initialize::setDefaultInternalAddressbook()
#2 /usr/share/tine20/Admin/Controller/User.php(474): Admin_Controller_User-&gt;getDefaultInternalAddressbook()
#3 /usr/share/tine20/Tinebase/User.php(1055): Admin_Controller_User-&gt;createOrUpdateContact(Object(Tinebase_Model_FullUser), false)
#4 /usr/share/tine20/Tinebase/Setup/Update/Release11.php(233): Tinebase_User::createSystemUser(&#039;anonymoususer&#039;, Object(Tinebase_Model_Group))
#5 /usr/share/tine20/Setup/Controller.php(577): Tinebase_Setup_Update_Release11-&gt;update_13()
#6 /usr/share/tine20/Setup/Controller.php(462): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;11&#039;) in /usr/share/tine20/Tinebase/Container.php on line 619

**Comment by Gloirin** [comment]
Related to #5529

**Comment by Gloirin** [comment]
Related to #6312

**Comment by Gloirin** [comment]
**Comment posted by weberho on 20 Dec 2017 08:16**

Might be related to #11174. The problem occured in the same instance.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Feb 2018 13:59**

we will fix this issue. it should be possible to rename this addressbook!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Feb 2018 14:00**

will be fixed by #0012756
