### ISSUE TITLE
0013690:
Migration fails due to "Integrity constraint violation"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6771]
**Reported by shochdoerfer on 4 Jan 2018 12:26**

**Version:** 2017.08.9 Community Edition

Trying to upgrade 2017.08.3 to 2017.08.9 produced the following error when executing php setup.php --upgrade:

PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;000000-2016-04-12 06:13:25&#039; for key &#039;inventory_id&#039; in /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO-&gt;query(&#039;CREATE UNIQUE I...&#039;)
#1 /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection-&gt;query(&#039;CREATE UNIQUE I...&#039;)
#2 /tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection-&gt;executeQuery(&#039;CREATE UNIQUE I...&#039;)
#3 /tine20/Setup/SchemaTool.php(129): Doctrine\ORM\Tools\SchemaTool-&gt;updateSchema(Array, true)
#4 /tine20/Setup/Update/Abstract.php(508): Setup_SchemaTool::updateSchema(&#039;Inventory&#039;, Array)
#5 /tine20/Inventory/Setup/Update/Release11.php(20): Setup_Update_Abstract-&gt;updateSchema(&#039;Inventory&#039;, Array)
#6 /tine20/Setup/Controller.php(577): Inventory_Setup_Up in /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 66

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;000000-2016-04-12 06:13:25&#039; for key &#039;inventory_id&#039; in /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO-&gt;query(&#039;CREATE UNIQUE I...&#039;)
#1 /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection-&gt;query(&#039;CREATE UNIQUE I...&#039;)
#2 /tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection-&gt;executeQuery(&#039;CREATE UNIQUE I...&#039;)
#3 /tine20/Setup/SchemaTool.php(129): Doctrine\ORM\Tools\SchemaTool-&gt;updateSchema(Array, true)
#4 /tine20/Setup/Update/Abstract.php(508): Setup_SchemaTool::updateSchema(&#039;Inventory&#039;, Array)
#5 /tine20/Inventory/Setup/Update/Release11.php(20): Setup_Update_Abstract-&gt;updateSchema(&#039;Inventory&#039;, Array)
#6 /tine20/Setup/Controller.php(577): Inventory_Setup_Up in /tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 66

Look like we have quite a few entries in the inventory table with the same deletion_time. I would assume others can potentially have similar problems. Will fix our records manually for now.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Feb 2018 15:59**

hm, this is very strange ... how did you get this data? I assume that this is not a common problem and would like to close this issue. do you agree, @shochdoerfer ?

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 22 Feb 2018 16:14**

I don&#039;t really know. I assume - have not tested it - that the batch deletion in Tine 2.0 might be the problem.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Mar 2018 16:32**

this has been introduced with https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/69a39cca739b4d5e2d0a424a050e5fe6590e3e11

@pmehrer: why did we add the deleted time here? inventory_id != id - maybe this constraint should be removed here.

**Comment by Gloirin** [comment]
**Comment posted by pmehrer on 1 Apr 2018 16:02**

issue needs discussion and most probably fixing the update script
