### ISSUE TITLE
0013694:
permanent Fatal errors caused by Scheduler.php

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6773]
**Reported by apvit on 11 Jan 2018 09:32**

**Version:** 2017.08.8 Community Edition

Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: Fatal error: Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »t20_scheduler_task« existiert nicht
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: LINE 1: ...T &quot;scheduler_task&quot;.*, NOW() AS &quot;server_time&quot; FROM &quot;t20_sched...
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler:                                                                                                               ^ in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: Stack trace:
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;execute(Array)
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: #1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo-&gt;_execute(Array)
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: #2 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement-&gt;execute(Array)
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: #3 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;SELECT &quot;schedul...&#039;, Array)
Jan 11 10:15:01 APVLX09 Tine 2.0 scheduler: #4 /usr/share/tine20/Tinebase/Backend/Scheduler.php(104): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

**Additional information:** probably a db problem when using PostgreSQL
caused by usage of double quotes  for table name around &quot;t20_scheduler_task&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Mar 2018 16:32**

pgsql support will be dropped soon.
