### ISSUE TITLE
0013806:
CalDAV Server responds with 404

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6828]
**Reported by shochdoerfer on 22 Mar 2018 16:09**

**Version:** 2018.02.1 Community Edition

Sometimes the CalDAV Server responds with 404 reponse which some clients happily ignore, iCal on iOS presents this error to the user by showing an alert box. This is what I have found out so far:

This is the request that returns a 404 in our Tine 2.0 instance (I assume it is a problem with &quot;wrong&quot; data in our database, but I might be wrong):

c8baa johndoe - 2018-03-22T12:34:46+00:00 INFO (6): Tinebase_Server_WebDAV::handle::106 Starting to handle WebDAV request ( requestUri:/principals/users/986691f61f9daa5f97f37634fb83ca4e34b41365/ PID: 34)

The CalDAV client sends this request to the server:
c8baa johndoe - 2018-03-22T12:34:46+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::127 &lt;&lt;&lt; *DAV request
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;A:expand-property xmlns:A=&quot;DAV:&quot;&gt;
  &lt;A:property name=&quot;calendar-proxy-read-for&quot; namespace=&quot;http://calendarserver.org/ns/&quot;&gt;
    &lt;A:property name=&quot;calendar-user-address-set&quot; namespace=&quot;urn:ietf:params:xml:ns:caldav&quot;/&gt;
    &lt;A:property name=&quot;email-address-set&quot; namespace=&quot;http://calendarserver.org/ns/&quot;/&gt;
    &lt;A:property name=&quot;displayname&quot; namespace=&quot;DAV:&quot;/&gt;
  &lt;/A:property&gt;
  &lt;A:property name=&quot;calendar-proxy-write-for&quot; namespace=&quot;http://calendarserver.org/ns/&quot;&gt;
    &lt;A:property name=&quot;calendar-user-address-set&quot; namespace=&quot;urn:ietf:params:xml:ns:caldav&quot;/&gt;
    &lt;A:property name=&quot;email-address-set&quot; namespace=&quot;http://calendarserver.org/ns/&quot;/&gt;
    &lt;A:property name=&quot;displayname&quot; namespace=&quot;DAV:&quot;/&gt;
  &lt;/A:property&gt;
&lt;/A:expand-property&gt;

This leads to to couple of notices stating that &quot;Group/list principal does not exist&quot; like this (for this specific request I got about 15 of those messages):

c8baa johndoe - 2018-03-22T12:34:46+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: 645585e475809352e11c589e47f5dd25676a7712
c8baa johndoe - 2018-03-22T12:34:46+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: 98d2c501897d8312bfadb8bcacd9d0b6cfc8c6ab

What seems to kill the request in the end is this SabreDAV exception for the last notice:
c8baa johndoe - 2018-03-22T12:34:46+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: 6af35127394a0af1467b250c4fe9f1b96f2b3dca
c8baa johndoe - 2018-03-22T12:34:46+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::202 &gt;&gt;&gt; *DAV response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\NotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Principal with name 6af35127394a0af1467b250c4fe9f1b96f2b3dca not found&lt;/s:message&gt;
  &lt;s:file&gt;/var/www/html/vendor/sabre/dav/lib/Sabre/DAVACL/AbstractPrincipalCollection.php&lt;/s:file&gt;
  &lt;s:line&gt;116&lt;/s:line&gt;
  &lt;s:code&gt;0&lt;/s:code&gt;
  &lt;s:stacktrace&gt;#0 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Sabre\DAVACL\AbstractPrincipalCollection-&gt;getChild(&#039;6af35127394a0af...&#039;)
#1 /var/www/html/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(380): Sabre\DAV\ObjectTree-&gt;getNodeForPath(&#039;principals/grou...&#039;)
#2 [internal function]: Sabre\CalDAV\Plugin-&gt;beforeGetProperties(&#039;principals/user...&#039;, Object(Tinebase_WebDav_Principal), Array, Array)
#3 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1519): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeGetProper...&#039;, Array)
#5 /var/www/html/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(1204): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;principals/user...&#039;, Array, 0)
#6 /var/www/html/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(1132): Sabre\DAVACL\Plugin-&gt;expandProperties(&#039;principals/user...&#039;, Array, 0)
#7 /var/www/html/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(1007): Sabre\DAVACL\Plugin-&gt;expandPropertyReport(Object(DOMDocument))
#8 [internal function]: Sabre\DAVACL\Plugin-&gt;report(&#039;{DAV:}expand-pr...&#039;, Object(DOMDocument), &#039;principals/user...&#039;)
#9 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1066): Sabre\DAV\Server-&gt;broadcastEvent(&#039;report&#039;, Array)
#11 [internal function]: Sabre\DAV\Server-&gt;httpReport(&#039;principals/user...&#039;)
#12 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;principals/user...&#039;)
#13 /var/www/html/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;REPORT&#039;, &#039;principals/user...&#039;)
#14 /var/www/html/Tinebase/Server/WebDAV.php(199): Sabre\DAV\Server-&gt;exec()
#15 /var/www/html/Tinebase/Core.php(260): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#16 /var/www/html/index.php(24): Tinebase_Core::dispatchRequest()
#17 {main}&lt;/s:stacktrace&gt;
&lt;/d:error&gt;

Given I am not so deep involved in CalDAV and the implementation in Tine 2.0, I am wondering why those Group/list principal are read, especially since those are mostly internal groups from our LDAP instance that get synched into Tine 2.0. They are not related at all to certain events.

The ids mentioned above seem to be entries of the  tine20_addressbook_lists table, those entries do still exist, and those lists have vaild members in the tine20_addressbook_list_members table. I did a quick check and could not find orphaned references in there. Not sure where the error is coming from or how to fix it.

**Additional information:** This issue is based on a &quot;bug report&quot; in the Tine 2.0 forum, see here https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=18756&amp;p=68388

We recently moved from a very old 2016.* instance of Tine 2.0 to the 2018.02.1 version. All db migrations went fine. I kind of think that some checks within Tine 2.0 were hardened and maybe some references cannot be found any more. But not sure what and which.

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 22 Mar 2018 22:54**

Looks like a Duplikate of #0013708 to me. Can you confirm that?

Reproduce: Set all groups your user belongs to to Show in Addressbook. 404-error gone away? 

If so please set this bug as duplicate of in relations.

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 23 Mar 2018 07:52**

Can confirm that this is an issue of 0013708.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 14:31**

this should be fixed in 2018.02.3. can you confirm that this is no longer an issue? or better: reopen this if it still is ... ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 14:32**

https://gerrit.tine20.com/customers/#/c/8455/

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 21 Apr 2018 09:17**

Goods good to me. Cannot reproduce the problem any more.
