### ISSUE TITLE
0013826:
Update auf 2018.02.3 Community Edition crasht mit Verweis auf Redis im Stacktrace

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#6837]
**Reported by bammes on 14 Apr 2018 18:48**

**Version:** 2018.02.3 Community Edition

Hallo,

gerade habe ich versucht, das Update von 2018.02.2 auf 2018.02.3 zu fahren.
Dieses schlägt mit folgender Ausgabe fehl:

[www@www-1 /usr/local/www/calendar.postadigitale.de.new]$ php ./setup.php  --update All
PHP Fatal error:  Uncaught Error: Undefined class constant &#039;Redis::SERIALIZER_IGBINARY&#039; in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php:115
Stack trace:
#0 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_Redis-&gt;__construct(Array)
#1 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend(&#039;Redis&#039;, Array, false, false)
#2 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(932): Zend_Cache::factory(&#039;Core&#039;, &#039;Redis&#039;, Array, Array)
#3 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(1502): Tinebase_Core::setupCache()
#4 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(985): Tinebase_Core::getCache()
#5 /usr/local/www/calendar.postadigitale.de.new/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection()
#6 /usr/local/www/calendar.postadigitale.de.new/Setup/Core. in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php on line 115

Fatal error: Uncaught Error: Undefined class constant &#039;Redis::SERIALIZER_IGBINARY&#039; in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php:115
Stack trace:
#0 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_Redis-&gt;__construct(Array)
#1 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend(&#039;Redis&#039;, Array, false, false)
#2 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(932): Zend_Cache::factory(&#039;Core&#039;, &#039;Redis&#039;, Array, Array)
#3 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(1502): Tinebase_Core::setupCache()
#4 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(985): Tinebase_Core::getCache()
#5 /usr/local/www/calendar.postadigitale.de.new/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection()
#6 /usr/local/www/calendar.postadigitale.de.new/Setup/Core. in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php on line 115

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2018 08:40**

fixed in the next release

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2018 13:28**

you can now download the fixed zf1 version here: https://github.com/tine20/zendframework1/releases/tag/1.12.20pl25

just unzip into tine20/vendor/zendframework/zendframework1

**Comment by Gloirin** [comment]
**Comment posted by bammes on 19 Apr 2018 13:35**

I am sorry, same behaviour as before:

[www@www-1 /usr/local/www/calendar.postadigitale.de.new]$ php setup.php --update All
PHP Fatal error:  Uncaught Error: Undefined class constant &#039;Redis::SERIALIZER_IGBINARY&#039; in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php:115
Stack trace:
#0 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_Redis-&gt;__construct(Array)
#1 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend(&#039;Redis&#039;, Array, false, false)
#2 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(932): Zend_Cache::factory(&#039;Core&#039;, &#039;Redis&#039;, Array, Array)
#3 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(1502): Tinebase_Core::setupCache()
#4 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(985): Tinebase_Core::getCache()
#5 /usr/local/www/calendar.postadigitale.de.new/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection()
#6 /usr/local/www/calendar.postadigitale.de.new/Setup/Core. in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php on line 115

Fatal error: Uncaught Error: Undefined class constant &#039;Redis::SERIALIZER_IGBINARY&#039; in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php:115
Stack trace:
#0 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_Redis-&gt;__construct(Array)
#1 /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend(&#039;Redis&#039;, Array, false, false)
#2 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(932): Zend_Cache::factory(&#039;Core&#039;, &#039;Redis&#039;, Array, Array)
#3 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(1502): Tinebase_Core::setupCache()
#4 /usr/local/www/calendar.postadigitale.de.new/Tinebase/Core.php(985): Tinebase_Core::getCache()
#5 /usr/local/www/calendar.postadigitale.de.new/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection()
#6 /usr/local/www/calendar.postadigitale.de.new/Setup/Core. in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php on line 115

short diff between old and new dir-content:

[www@www-1 /usr/local/www]$ diff -r calendar.diff/vendor/zendframework/zendframework1/ calendar.postadigitale.de.new/vendor/zendframework/zendframework1/
Only in calendar.postadigitale.de.new/vendor/zendframework/zendframework1/: .gitignore
diff -r calendar.diff/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php
269c269,290
&lt;                     return $this-&gt;_redis-&gt;flushDB();
---
&gt;                     $iterator = null;
&gt;                     $success = true;
&gt;                     $prefix = $this-&gt;_redis-&gt;getOption(Redis::OPT_PREFIX);
&gt;                     if (!is_string($prefix) || strlen($prefix) === 0) {
&gt;                         $prefix = null;
&gt;                         $pattern = null;
&gt;                     } else {
&gt;                         $this-&gt;_redis-&gt;setOption(Redis::OPT_PREFIX, &#039;&#039;);
&gt;                         $pattern = $prefix . &#039;*&#039;;
&gt;                     }
&gt;                     try {
&gt;                         while (is_array($keys = $this-&gt;_redis-&gt;scan($iterator, $pattern, 100))) {
&gt;                             // don&#039;t &amp;&amp; the other way! we still want to delete as much as possible, even if it failes once
&gt;                             $success = $this-&gt;_redis-&gt;del($keys) &amp;&amp; $success;
&gt;                         }
&gt;                     } finally {
&gt;                         if (null !== $prefix) {
&gt;                             $this-&gt;_redis-&gt;setOption(Redis::OPT_PREFIX, $prefix);
&gt;                         }
&gt;                     }
&gt;                     return $success;
&gt;                     //return $this-&gt;_redis-&gt;flushDB();
325c346,354
&lt;                         $allTags = array_unique(array_merge($tags, $values[$i][3]));
---
&gt;                         // if the record also has some other tags attached, remove record from these tag lists too
&gt;                         // $values[$i] can be null if id was not found by getMultiple
&gt;                         if (is_array($values[$i]) &amp;&amp; is_array($values[$i][3])) {
&gt;                             $allTags = array_unique(array_merge((array) $tags, $values[$i][3]));
&gt;                             // otherwise just remove from the tag lists provided
&gt;                         } else {
&gt;                             $allTags = (array) $tags;
&gt;                         }
&gt; 
diff -r calendar.diff/vendor/zendframework/zendframework1/library/Zend/RedisProxy.php calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/RedisProxy.php
79a80,102
&gt;     public function scan(&amp;$iterator, $pattern = null, $count = 0)
&gt;     {
&gt;         $tries = 0;
&gt;         while (true) {
&gt;             try {
&gt;                 return $this-&gt;_redis-&gt;scan($iterator, $pattern, $count);
&gt;             } catch (RedisException $re) {
&gt;                 if (true === $this-&gt;_inMulti || ++$tries &gt; 5) {
&gt;                     throw $re;
&gt;                 }
&gt; 
&gt;                 // give Redis 100ms and try again
&gt;                 usleep(100000);
&gt; 
&gt;                 try {
&gt;                     $this-&gt;_redis-&gt;ping();
&gt;                 } catch (RedisException $re) {
&gt;                     $this-&gt;_reconnect();
&gt;                 }
&gt;             }
&gt;         }
&gt;     }
&gt;     
110a134,138
&gt;             case &#039;flushDB&#039;:
&gt;             case &#039;flushAll&#039;:
&gt;                 throw new RedisException($_name . &#039; is forbidden, it well may be a shared redis, don\&#039;t do it ever!&#039;);
&gt;                 break;
&gt;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 15:05**

hi bammes,

i attached a patched version of the redis backend (vendor/zendframework/zendframework1/library/Zend/Cache/Backend/Redis.php). could you please try it and tell us if this works?

thanks!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 15:06**

redis backend without mandatory SERIALIZER_IGBINARY

**Comment by Gloirin** [comment]
**Comment posted by bammes on 19 Apr 2018 15:09**

Looks, like RedisProxy.php has to be changed as well:

[www@www-1 /usr/local/www/calendar.postadigitale.de.new]$ php setup.php --update All
PHP Fatal error:  Cannot declare class Zend_Cache_Backend_Redis, because the name is already in use in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/RedisProxy.php on line 31

Fatal error: Cannot declare class Zend_Cache_Backend_Redis, because the name is already in use in /usr/local/www/calendar.postadigitale.de.new/vendor/zendframework/zendframework1/library/Zend/RedisProxy.php on line 31

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 15:14**

see https://github.com/tine20/zendframework1/commit/cf11dc28ca6b565cf4d409a204dd5f73e3abc06d

**Comment by Gloirin** [comment]
**Comment posted by bammes on 19 Apr 2018 15:23**

Looks good now with your new Redis.php, replaced the wrong file...

[www@www-1 /usr/local/www/calendar.postadigitale.de.new]$ php setup.php --update All
Updated 4 application(s).

**Comment by Gloirin** [comment]
**Comment posted by bammes on 19 Apr 2018 15:31**

Just found out, that freebsds default package switched ignbinary off.
If I compile php71-pecl-redis WITH ignbinary support myself, it works.
It could be also a possible solution to include a hint in the Changelog, that from 2018.02.3 on IGNBINARY support is needed.
I don&#039;t know, what the Debian/Ubuntu/Redhat default is, which should cover most of the cases...

Your &quot;redis backend without mandatory SERIALIZER_IGBINARY&quot; made me check, if there where any non-default build-options in php71-pecl-redis in freebsd.

**Comment by Gloirin** [comment]
**Comment posted by AdrianSt on 19 Apr 2018 18:28**

Bammes, thanks for the hint. 
2018.02.3 works unpatched after reinstalling/activating redis with igbinary support and igbinary through PECL.
Ubuntu doesn&#039;t come with Redis for PHP 7.1/7.2 out of the box so you have to use PECL.
And &quot;no&quot; is the default when being asked for igbinary support.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Apr 2018 08:27**

ok, thanks for the updates :)

closing this issue. 2018.02.4 will have the fixed Redis cache backend that works with or without IGBINARY.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Apr 2018 08:33**

http://gerrit.tine20.com/customers/8965
