### ISSUE TITLE
0001240:
SVN

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#707]
**Reported by Olodin on 14 Jul 2009 07:38**

**Version:** Leonie (2009-07) Beta 2

Tested with SVN 9405

Tried to create a new ActiveSync Partnership. User in Tine20 was created just before, server configration on Windows Mobile 6 device was also new. Sync does not start, debug log shows this:

2009-07-13T18:40:46+00:00 DEBUG (7): authentication of Olodin succeeded
2009-07-13T18:40:46+00:00 DEBUG (7): Tinebase_User::getInstance::54 accounts backend: Sql
2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::82 Agent: MSFT-PPC/0.0.0  PolicyKey: 0 ASVersion: 2.5 Command: FolderSync
2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::94 class name: ActiveSync_Command_FolderSync
2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::95 decoded wbxml content: &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot;&gt;&lt;SyncKey&gt;0&lt;/SyncKey&gt;&lt;/FolderSync&gt;

2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::101 sync timestamp: 2009-07-13 18:40:46
2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Command_FolderSync::handle::101 synckey is 0
2009-07-13T18:40:46+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Contacts
2009-07-13T18:40:46+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Tasks
2009-07-13T18:40:46+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Calendar
2009-07-13T18:40:46+00:00 DEBUG (7): ActiveSync_Command_FolderSync::getResponse::173 Contacts
2009-07-13T18:40:46+00:00 DEBUG (7): Tinebase_Record_Abstract:
Array
(
    [0] =&gt; Array
        (
            [id] =&gt; lastfiltertype
            [msg] =&gt; Array
                (
                    [0] =&gt; Field &#039;lastfiltertype&#039; is required by rule &#039;lastfiltertype&#039;, but the field is missing
                )

        )

)
exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;some fields lastfiltertype have invalid content&#039; in /usr/local/www/data/tine20/Tinebase/Record/Abstract.php:425
Stack trace:
#0 /usr/local/www/data/tine20/Tinebase/Record/Abstract.php(287): Tinebase_Record_Abstract-&gt;isValid(true)
#1 /usr/local/www/data/tine20/Tinebase/Record/Abstract.php(167): Tinebase_Record_Abstract-&gt;setFromArray(Array)
#2 /usr/local/www/data/tine20/ActiveSync/Command/FolderSync.php(214): Tinebase_Record_Abstract-&gt;__construct(Array)
#3 /usr/local/www/data/tine20/ActiveSync/Command/FolderSync.php(181): ActiveSync_Command_FolderSync-&gt;_addFolderState(&#039;Contacts&#039;, &#039;addressbook-roo...&#039;)
#4 /usr/local/www/data/tine20/ActiveSync/Frontend/Http.php(101): ActiveSync_Command_FolderSync-&gt;getResponse()
#5 /usr/local/www/data/tine20/ActiveSync/Server/Http.php(81): ActiveSync_Frontend_Http-&gt;handlePost(&#039;bjoern&#039;, &#039;29CA3BE90BCCA94...&#039;, &#039;PocketPC&#039;, &#039;FolderSync&#039;)
#6 /usr/local/www/data/tine20/Tinebase/Core.php(161): ActiveSync_Server_Http-&gt;handle()
#7 /usr/local/www/data/tine20/index.php(50): Tinebase_Core::dispatchRequest()
#8 {main}

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 14 Jul 2009 07:40**

Sorry, missed to add a correct summary:
First ActiveSync attempt fails
