### ISSUE TITLE
0001288:
task syncing fails with database exception

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#731]
**Reported by Olodin on 15 Jul 2009 19:40**

**Version:** Leonie (2009-07) Beta 2

Syncing of tasks fails with an exception for each task, the client gives an error but the sync of all other items (calendar and contacts) passes through. Below is the error from one task

**Additional information:** 2009-07-15T19:13:58+00:00 INFO (6): ActiveSync_Command_Sync::handle::172 entry not found. adding as new
2009-07-15T19:13:58+00:00 DEBUG (7): ActiveSync_Controller_Abstract::add::247 add entry
2009-07-15T19:13:58+00:00 DEBUG (7): ActiveSync_Controller_Tasks::_toTineModel::173 taskData Array
(
    [percent] =&gt; 0
    [completed] =&gt; 
    [due] =&gt; 2009-07-11 22:00:00
    [geo] =&gt; 
    [priority] =&gt; 2
    [status_id] =&gt; 3
    [summary] =&gt; Backup
)

2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::84  startTransaction request
2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::86  new transactionable. Starting transaction on this resource
2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::99  queued transaction with id 27dfc8ec82c5fa44cc17ce377ca08078233ed734
2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_TransactionManager::rollBack::141  rollBack request, rollBack all transactionables
2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::create::258 SQLSTATE[01000]: Warning: 1265 Data truncated for column &#039;created_by&#039; at row 1
2009-07-15T19:13:58+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::create::259 #0 /usr/local/www/data/tine20/library/Zend/Db/Statement.php(283): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /usr/local/www/data/tine20/library/Zend/Db/Adapter/Abstract.php(430): Zend_Db_Statement-&gt;execute(Array)
#2 /usr/local/www/data/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(220): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /usr/local/www/data/tine20/library/Zend/Db/Adapter/Abstract.php(508): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /usr/local/www/data/tine20/Tinebase/Backend/Sql/Abstract.php(329): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_tasks&#039;, Array)
#5 /usr/local/www/data/tine20/Tasks/Backend/Sql.php(83): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Tasks_Model_Task))
#6 /usr/local/www/data/tine20/Tinebase/Controller/Record/Abstract.php(228): Tasks_Backend_Sql-&gt;create(Object(Tasks_Model_Task))
#7 /usr/local/www/data/tine20/Tasks/Controller/Task.php(88): Tinebase_Controller_Record_Abstract-&gt;create(Object(Tasks_Model_Task))
#8 /usr/local/www/data/tine20/ActiveSync/Controller/Abstract.php(256): Tasks_Controller_Task-&gt;create(Object(Tasks_Model_Task))
#9 /usr/local/www/data/tine20/ActiveSync/Command/Sync.php(173): ActiveSync_Controller_Abstract-&gt;add(&#039;tasks-root&#039;, Object(SimpleXMLElement))
#10 /usr/local/www/data/tine20/ActiveSync/Frontend/Http.php(97): ActiveSync_Command_Sync-&gt;handle()
#11 /usr/local/www/data/tine20/ActiveSync/Server/Http.php(81): ActiveSync_Frontend_Http-&gt;handlePost(&#039;bjoern&#039;, &#039;29CA3BE90BCCA94...&#039;, &#039;PocketPC&#039;, &#039;Sync&#039;)
#12 /usr/local/www/data/tine20/Tinebase/Core.php(161): ActiveSync_Server_Http-&gt;handle()
#13 /usr/local/www/data/tine20/index.php(50): Tinebase_Core::dispatchRequest()
#14 {main}
2009-07-15T19:13:58+00:00 WARN (4): ActiveSync_Command_Sync::handle::183 failed to add entry exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[01000]: Warning: 1265 Data truncated for column &#039;created_by&#039; at row 1&#039; in /usr/local/www/data/tine20/library/Zend/Db/Statement/Pdo.php:238

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 19 Jul 2009 10:51**

I can&#039;t reproduce this problem.

Can you please make sure that you have updated the tasks application to it&#039;s latest version(0.2).

If Tasks is already at version 0.2, please try to get the mysql statement creating the problem. You can get the statement from the mysql query log. You can also send me the bug report from error reporting window. This will send the full sql query too.

Also attach the output of the mysql command:
show create table tine20_tasks;

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 19 Jul 2009 20:07**

I&#039;ve added the mysql query log of one of the tasks, which fail. What struggled me, when I saw the query: those tasks are already in the user account of tine20. There need to be just some updates made (eg some have been completed).

Uploaded the logs you requested.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 20 Jul 2009 12:10**

CREATE TABLE `tine20_tasks` (
  `id` varchar(40) NOT NULL,
  `container_id` int(11) unsigned DEFAULT NULL,
  `created_by` int(11) unsigned DEFAULT NULL,,
....

created_by has the wrong datatype. It should be varchar(40)  instead of int(11) unsigned.

The field type get changed during the update of tasks from version 0.1 to 0.2.

Is tasks already at version 0.2 in setup?

If tasks is already at version 0.2, try to set the version back 0.1 in tine20_applications and try to apply the update again.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jul 2009 13:22**

closing this task, seems to be an update problem
