### ISSUE TITLE
0001332:
pdf export from contact in edit view produces empty pdf

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#753]
**Reported by Olodin on 21 Jul 2009 15:07**

**Version:** Leonie (2009-07) Beta 3

PDF export of a contact does not work properly and produces a nearly empty pdf file. 
It just has
* default contact picture top left
* export date low left
* created by tine20 in low right

Exporting the same contact in the adressbook list view when the row is selected the PDF is filled with all the details.

Debug logs for both are identical I would say, nothing in httpd-error log:

Export from overview:

2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Core::setupLogger::308 logger initialized
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Core::setupCache::347 cache disabled
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id 9aa24383ebda3ffc0e50fce3331fa4f20d26c55a
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::509 given localeString &#039;auto&#039;
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;en&#039;
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;en&#039;
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-21T14:58:21+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-21T14:58:22+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::139 Contact has no image.
2009-07-21T14:58:22+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-21T14:58:22+00:00 DEBUG (7): index.php (63) TIME: 0.804343938828 seconds 4.5 MBytes

Export from detail view

2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Core::setupLogger::308 logger initialized
2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Core::setupCache::347 cache disabled
2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id 9aa24383ebda3ffc0e50fce3331fa4f20d26c55a
2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::509 given localeString &#039;auto&#039;
2009-07-21T14:58:37+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;en&#039;
2009-07-21T14:58:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;en&#039;
2009-07-21T14:58:38+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-21T14:58:38+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-21T14:58:38+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-21T14:58:38+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::139 Contact has no image.
2009-07-21T14:58:38+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-21T14:58:38+00:00 DEBUG (7): index.php (63) TIME: 0.692403078079 seconds 4.25 MBytes

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jul 2009 11:53**

could not reproduce: i just tested this on two different systems and it works on both of them.

could you try again and send me a screenshot of the &#039;almost empty&#039; pdf?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 22 Jul 2009 12:09**

uploaded both PDFs. contact-6_working.pdf is the export from the addressbook overview.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Jul 2009 09:17**

do you get an error in the apache error.log?
do you always get this almost empty pdf for all your contacts? could it be connected to charset problems?

i&#039;m sorry, but i can&#039;t reproduce this misbehaviour ... :-/

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 23 Jul 2009 11:08**

Just tested again with SVN 9632 and a fresh database, no errors in http error log, but debug output is slightly different:

Export from overview, this works:

2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Core::setupLogger::308 logger initialized
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Core::setupCache::347 cache disabled
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id c7b51a688f0e3e7e9ad36c22e5257c1cb0508e79
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::509 given localeString &#039;auto&#039;
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::522 session value &#039;en&#039;
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;en&#039;
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;en&#039;
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-23T11:05:10+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::138 exception &#039;Addressbook_Exception_NotFound&#039; with message &#039;Contact has no image.&#039; in /usr/local/www/data/tine20-svn/Addressbook/Controller.php:135
Stack trace:
#0 /usr/local/www/data/tine20-svn/Addressbook/Export/Pdf.php(129): Addressbook_Controller-&gt;getImage(&#039;3&#039;)
#1 /usr/local/www/data/tine20-svn/Addressbook/Frontend/Http.php(55): Addressbook_Export_Pdf-&gt;generateContactPdf(Object(Addressbook_Model_Contact))
#2 [internal function]: Addressbook_Frontend_Http-&gt;exportContacts(&#039;[{&quot;field&quot;:&quot;id&quot;,...&#039;, &#039;pdf&#039;)
#3 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#4 /usr/local/www/data/tine20-svn/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#5 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#6 /usr/local/www/data/tine20-svn/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#7 /usr/local/www/data/tine20-svn/Tinebase/Server/Http.php(61): Tinebase_Http_Server-&gt;handle(Array)
#8 /usr/local/www/data/tine20-svn/Tinebase/Core.php(161): Tinebase_Server_Http-&gt;handle()
#9 /usr/local/www/data/tine20-svn/index.php(50): Tinebase_Core::dispatchRequest()
#10 {main}
2009-07-23T11:05:10+00:00 WARN (4): Addressbook_Export_Pdf::generateContactPdf::139 Contact has no image.
2009-07-23T11:05:10+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-23T11:05:10+00:00 DEBUG (7): index.php (62) TIME: 0.779725074768 seconds 4.5 MBytes



Export from detail contact view, this does not work:
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Core::setupLogger::308 logger initialized
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Core::setupCache::347 cache disabled
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id c7b51a688f0e3e7e9ad36c22e5257c1cb0508e79
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::509 given localeString &#039;auto&#039;
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::522 session value &#039;en&#039;
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;en&#039;
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;en&#039;
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-23T11:06:22+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-23T11:06:23+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-23T11:06:23+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::138 exception &#039;Addressbook_Exception_NotFound&#039; with message &#039;Contact has no image.&#039; in /usr/local/www/data/tine20-svn/Addressbook/Controller.php:135
Stack trace:
#0 /usr/local/www/data/tine20-svn/Addressbook/Export/Pdf.php(129): Addressbook_Controller-&gt;getImage(NULL)
#1 /usr/local/www/data/tine20-svn/Addressbook/Frontend/Http.php(55): Addressbook_Export_Pdf-&gt;generateContactPdf(Object(Addressbook_Model_Contact))
#2 [internal function]: Addressbook_Frontend_Http-&gt;exportContacts(&#039;&quot;3&quot;&#039;, &#039;pdf&#039;)
#3 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#4 /usr/local/www/data/tine20-svn/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#5 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#6 /usr/local/www/data/tine20-svn/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#7 /usr/local/www/data/tine20-svn/Tinebase/Server/Http.php(61): Tinebase_Http_Server-&gt;handle(Array)
#8 /usr/local/www/data/tine20-svn/Tinebase/Core.php(161): Tinebase_Server_Http-&gt;handle()
#9 /usr/local/www/data/tine20-svn/index.php(50): Tinebase_Core::dispatchRequest()
#10 {main}
2009-07-23T11:06:23+00:00 WARN (4): Addressbook_Export_Pdf::generateContactPdf::139 Contact has no image.
2009-07-23T11:06:23+00:00 DEBUG (7): Tinebase_Translation::getTranslation::238 locale used: en
2009-07-23T11:06:23+00:00 DEBUG (7): index.php (62) TIME: 0.662828922272 seconds 4.25 MBytes

At least line #0 and and #2 differ in the stack trace output. Does this help?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jul 2009 10:59**

hi, could you please test again with the new rev 9690? i added some more debug output. it seems that somehow the contact id is lost.

which browser are you using? for me, it works with firefox 3.0, firefox 3.5 and ie8.

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 27 Jul 2009 17:50**

The initial test were on Windows XP with Firefox 3.5.1, the following was also with 3.5.1 on Ubuntu.

Updated to SVN 9698 before testing.

Export from overview, this works:
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Core::setupLogger::309 logger initialized
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Core::setupCache::348 cache disabled
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id c7b51a688f0e3e7e9ad36c22e5257c1cb0508e79
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::510 given localeString &#039;auto&#039;
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::523 session value &#039;en&#039;
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Translation::getLocale::175 given localeString &#039;en&#039;
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Translation::getLocale::210 selected locale: &#039;en&#039;
2009-07-27T17:45:11+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-27T17:45:12+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-27T17:45:12+00:00 DEBUG (7): Addressbook_Frontend_Http::exportContacts::54 Creating pdf for contact id 3
2009-07-27T17:45:12+00:00 DEBUG (7): Tinebase_CustomField::resolveRecordCustomFields::242 Resolved custom fields for record of class Addressbook_Model_Contact
2009-07-27T17:45:12+00:00 DEBUG (7): Tinebase_Translation::getTranslation::240 locale used: en
2009-07-27T17:45:13+00:00 DEBUG (7): Tinebase_CustomField::resolveRecordCustomFields::242 Resolved custom fields for record of class Addressbook_Model_Contact
2009-07-27T17:45:13+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::133 exception &#039;Addressbook_Exception_NotFound&#039; with message &#039;Contact has no image.&#039; in /usr/local/www/data/tine20-svn/Addressbook/Controller.php:135
Stack trace:
#0 /usr/local/www/data/tine20-svn/Addressbook/Export/Pdf.php(124): Addressbook_Controller-&gt;getImage(&#039;3&#039;)
#1 /usr/local/www/data/tine20-svn/Addressbook/Frontend/Http.php(56): Addressbook_Export_Pdf-&gt;generateContactPdf(Object(Addressbook_Model_Contact))
#2 [internal function]: Addressbook_Frontend_Http-&gt;exportContacts(&#039;[{&quot;field&quot;:&quot;id&quot;,...&#039;, &#039;pdf&#039;)
#3 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#4 /usr/local/www/data/tine20-svn/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#5 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#6 /usr/local/www/data/tine20-svn/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#7 /usr/local/www/data/tine20-svn/Tinebase/Server/Http.php(61): Tinebase_Http_Server-&gt;handle(Array)
#8 /usr/local/www/data/tine20-svn/Tinebase/Core.php(162): Tinebase_Server_Http-&gt;handle()
#9 /usr/local/www/data/tine20-svn/index.php(50): Tinebase_Core::dispatchRequest()
#10 {main}
2009-07-27T17:45:13+00:00 WARN (4): Addressbook_Export_Pdf::generateContactPdf::134 Contact has no image.
2009-07-27T17:45:13+00:00 DEBUG (7): Tinebase_Translation::getTranslation::240 locale used: en
2009-07-27T17:45:13+00:00 DEBUG (7): index.php (62) TIME: 2.29778003693 seconds 8 MBytes


Export from detail contact view, this does not work:
2009-07-27T17:45:34+00:00 DEBUG (7): Tinebase_Core::setupLogger::309 logger initialized
2009-07-27T17:45:34+00:00 DEBUG (7): Tinebase_Core::setupCache::348 cache disabled
2009-07-27T17:45:34+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id c7b51a688f0e3e7e9ad36c22e5257c1cb0508e79
2009-07-27T17:45:34+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::510 given localeString &#039;auto&#039;
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::523 session value &#039;en&#039;
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Translation::getLocale::175 given localeString &#039;en&#039;
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Translation::getLocale::210 selected locale: &#039;en&#039;
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Server_Http::handle::32 is http request. method: Addressbook.exportContacts
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Export_Pdf::__construct::141 use zend_pdf font: Helvetica
2009-07-27T17:45:35+00:00 DEBUG (7): Addressbook_Frontend_Http::exportContacts::54 Creating pdf for contact id 
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Translation::getTranslation::240 locale used: en
2009-07-27T17:45:35+00:00 DEBUG (7): Addressbook_Export_Pdf::generateContactPdf::133 exception &#039;Addressbook_Exception_NotFound&#039; with message &#039;Contact has no image.&#039; in /usr/local/www/data/tine20-svn/Addressbook/Controller.php:135
Stack trace:
#0 /usr/local/www/data/tine20-svn/Addressbook/Export/Pdf.php(124): Addressbook_Controller-&gt;getImage(NULL)
#1 /usr/local/www/data/tine20-svn/Addressbook/Frontend/Http.php(56): Addressbook_Export_Pdf-&gt;generateContactPdf(Object(Addressbook_Model_Contact))
#2 [internal function]: Addressbook_Frontend_Http-&gt;exportContacts(&#039;&quot;3&quot;&#039;, &#039;pdf&#039;)
#3 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#4 /usr/local/www/data/tine20-svn/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#5 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#6 /usr/local/www/data/tine20-svn/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Addressbook_Frontend_Http), Array)
#7 /usr/local/www/data/tine20-svn/Tinebase/Server/Http.php(61): Tinebase_Http_Server-&gt;handle(Array)
#8 /usr/local/www/data/tine20-svn/Tinebase/Core.php(162): Tinebase_Server_Http-&gt;handle()
#9 /usr/local/www/data/tine20-svn/index.php(50): Tinebase_Core::dispatchRequest()
#10 {main}
2009-07-27T17:45:35+00:00 WARN (4): Addressbook_Export_Pdf::generateContactPdf::134 Contact has no image.
2009-07-27T17:45:35+00:00 DEBUG (7): Tinebase_Translation::getTranslation::240 locale used: en
2009-07-27T17:45:35+00:00 DEBUG (7): index.php (62) TIME: 0.688829898834 seconds 4.5 MBytes

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jul 2009 22:32**

somehow the contact id is missing ... but i think it is send by the js client (please have a look at the request with firebug to make sure).

but i have another idea: are the magic_quotes_gpc = on on your server?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 28 Jul 2009 12:43**

Thats set on the server: magic_quotes_gpc = Off

With firebug I see that posted by the client:

contactId	3
jsonKey	5679c997d359e4b22bb44fc21f4a95babee06cf1
method	Addressbook.getContact
requestType	JSON

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Aug 2009 15:23**

could you please try it again (with rev 9839) and post the debug output if it doesn&#039;t work?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 10 Aug 2009 18:39**

Hm, with rev 9839 the exported pdf generated out of the edit view now is completely empty (not almost empty as before). The logs are attached as &quot;tine20svn_20090810.log&quot;.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Sep 2009 15:31**

could not be verified on another system. it seems to be a problem with quoting, for example by magic_quotes_gpc = On
