### ISSUE TITLE
0001386:
Nach Löschen eines Eintrages erscheint Fehlermeldung bei "alle Kalender" oder "Kalender anderer"

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#780]
**Reported by weberho on 30 Jul 2009 14:21**

**Version:** Leonie (2009-07) RC 1

Bei einem Klick auf alle Kalender oder Kalender anderer erhalte ich immer folgenden Fehlerdialog:

Nicht gefunden: &quot;Ihre Anfrage konnte aufgrund von fehlenden Daten nicht beantwortet werden. In den meisten Fällen wurden diese Daten von einem anderen Benutzer gelöscht. Bitte aktualisieren Sie Ihre momentane Ansicht.&quot;
Nach dem Schließen des Dialogs läuft die Aktualisierungssanduhr unendlich weiter.

Ein Benutzer hat mir mitgeteilt, dass dieser Fehler seit dem Löschen eines Eintrages aus dem Kalender auftritt.

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=956

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 4 Aug 2009 09:28**

ich kann den fehler nicht reproduzieren. 

kannst du bitte das debug-log einschalten und den entsprechenden schnipsel hier einfügen?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 4 Aug 2009 10:40**

2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupLogger::309 logger initialized
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupLogger::309 logger initialized
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupCache::348 cache disabled
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id 7c8ee8574b4b7e57ec7d5bee7354d2da8f7b08f2
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::510 given localeString &#039;auto&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::523 session value &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Server_Json::handle::39 is json request. method: Tinebase_Container.getContainer
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_User::getInstance::54 accounts backend: Sql
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupCache::348 cache disabled
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id 7c8ee8574b4b7e57ec7d5bee7354d2da8f7b08f2
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Sql
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::510 given localeString &#039;auto&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::523 session value &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;de&#039;
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Server_Json::handle::39 is json request. method: Calendar.searchEvents
2009-08-04T10:38:38+00:00 DEBUG (7): Tinebase_Server_Json::handle::117 got exception code404
2009-08-04T10:38:38+00:00 DEBUG (7): Zend_Json_Server:
exception &#039;Tinebase_Exception_NotFound&#039; with message &#039;Account must be in at least one group.&#039; in /srv/www/vhosts/main/tine20/Tinebase/Container.php:457
Stack trace:
#0 /srv/www/vhosts/main/tine20/Calendar/Model/EventAclFilter.php(104): Tinebase_Container-&gt;getPersonalContainer(&#039;9d2a94c93f202da...&#039;, &#039;Calendar&#039;, &#039;9d2a94c93f202da...&#039;, 0, true)
#1 /srv/www/vhosts/main/tine20/Calendar/Model/EventAclFilter.php(47): Calendar_Model_EventAclFilter-&gt;_resolve()
#2 /srv/www/vhosts/main/tine20/Tinebase/Backend/Sql/Filter/FilterGroup.php(46): Calendar_Model_EventAclFilter-&gt;appendFilterSql(Object(Tinebase_Backend_Sql_Filter_GroupSelect), Object(Calendar_Backend_Sql))
#3 /srv/www/vhosts/main/tine20/Tinebase/Backend/Sql/Abstract.php(624): Tinebase_Backend_Sql_Filter_FilterGroup::appendFilters(Object(Zend_Db_Select), Object(Calendar_Model_EventFilter), Object(Calendar_Backend_Sql))
#4 /srv/www/vhosts/main/tine20/Tinebase/Backend/Sql/Abstract.php(253): Tinebase_Backend_Sql_Abstract-&gt;_addFilter(Object(Zend_Db_Select), Object(Calendar_Model_EventFilter))
#5 /srv/www/vhosts/main/tine20/Tinebase/Controller/Record/Abstract.php(89): Tinebase_Backend_Sql_Abstract-&gt;search(Object(Calendar_Model_EventFilter), Object(Tinebase_Model_Pagination), false)
#6 /srv/www/vhosts/main/tine20/Tinebase/Frontend/Json/Abstract.php(100): Tinebase_Controller_Record_Abstract-&gt;search(Object(Calendar_Model_EventFilter), Object(Tinebase_Model_Pagination))
#7 /srv/www/vhosts/main/tine20/Calendar/Frontend/Json.php(111): Tinebase_Frontend_Json_Abstract-&gt;_search(&#039;[{&quot;field&quot;:&quot;cont...&#039;, &#039;{}&#039;, Object(Calendar_Controller_Event), &#039;Calendar_Model_...&#039;)
#8 [internal function]: Calendar_Frontend_Json-&gt;searchEvents(&#039;[{&quot;field&quot;:&quot;cont...&#039;, &#039;{}&#039;)
#9 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Calendar_Frontend_Json), Array)
#10 /srv/www/vhosts/main/tine20/library/Zend/Server/Reflection/Function/Abstract.php(371): call_user_func_array(Array, Array)
#11 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#12 /srv/www/vhosts/main/tine20/Zend/Json/Server.php(144): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Calendar_Frontend_Json), Array)
#13 /srv/www/vhosts/main/tine20/Tinebase/Server/Json.php(108): Zend_Json_Server-&gt;handle(Array)
#14 /srv/www/vhosts/main/tine20/Tinebase/Core.php(162): Tinebase_Server_Json-&gt;handle()
#15 /srv/www/vhosts/main/tine20/index.php(51): Tinebase_Core::dispatchRequest()
#16 {main}


Hoffe, es hilft
