### ISSUE TITLE
0001496:
exception during login with LDAP backend

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#835]
**Reported by czytom on 12 Aug 2009 08:18**

**Version:** Leonie (2009-07-1)

after adding configuration for LDAP:
&#039;authentication&#039; =&gt; array(
       &#039;backend&#039; =&gt; &#039;ldap&#039;,
       &#039;ldap&#039; =&gt; array(
         &#039;host&#039; =&gt; &#039;ldaphost&quot;&#039;,
         &#039;username&#039; =&gt; &quot;uid=ws,ou=Access,dc=p,dc=com&quot;,
         &#039;password&#039; =&gt; &#039;something&#039;,
         &#039;bindRequiresDn&#039; =&gt; true,
         &#039;baseDn&#039; =&gt; &quot;dc=p,dc=com&quot;,
         &#039;accountCanonicalForm&#039; =&gt; 2
       ),
   ),
   &#039;accounts&#039; =&gt; array(
       &#039;backend&#039; =&gt; &#039;ldap&#039;,
       &#039;ldap&#039; =&gt; array(
         &#039;host&#039; =&gt; &#039;ldaphost&#039;,
         &#039;username&#039; =&gt; &quot;uid=ws,ou=Access,dc=p,dc=com&quot;,
         &#039;password&#039; =&gt; &quot;something&quot;&#039;,
         &#039;bindRequiresDn&#039; =&gt; true,
         &#039;userDn&#039; =&gt; &quot;ou=People,dc=p,dc=com&quot;,
         &#039;groupsDn&#039; =&gt; &quot;ou=Groups,dc=p,dc=com&quot;,
        &#039;pwEncType&#039;      =&gt; &#039;MD5CRYPT&#039;,
        //&#039;useRfc2307bis&#039;  =&gt; true,
        &#039;minUserId&#039;      =&gt; 1000,
        &#039;maxUserId&#039;      =&gt; 29999,
        &#039;minGroupId&#039;     =&gt; 12000,
        &#039;maxGroupId&#039;     =&gt; 12099,
       ),

and try to login with ldap user credentials I&#039;m getting:

exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20/tine20_accounts`, CONSTRAINT `tine20_accounts::primary_group_id--groups::id` FOREIGN KEY (`primary_group_id`) REFERENCES `tine20_groups` (`id`))&#039; in /var/www/webim/tine/library/Zend/Db/Statement/Pdo.php:238

**Additional information:** 2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Core::setupLogger::309 logger initialized
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Core::setupCache::348 cache disabled
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValue::126 get user preference &quot;timezone&quot; for account id 0
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::510 given localeString &#039;auto&#039;
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::523 session value &#039;en&#039;
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Translation::getLocale::173 given localeString &#039;en&#039;
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Translation::getLocale::208 selected locale: &#039;en&#039;
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Server_Json::handle::39 is json request. method: Tinebase.login
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_Auth::__construct::110 authentication backend: Ldap
2009-08-12T07:58:44+00:00 DEBUG (7): trying to authenticate mylogin
2009-08-12T07:58:44+00:00 DEBUG (7): authentication of mylogin succeeded
2009-08-12T07:58:44+00:00 DEBUG (7): Tinebase_User::getInstance::54 accounts backend: Ldap
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_Group::getInstance::60 groups backend: Ldap
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::84  startTransaction request
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::86  new transactionable. Starting transaction on this resource
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::99  queued transaction with id 4fc3db5cd9f9120afe6966d6003bcdbfe6929980
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_TransactionManager::rollBack::141  rollBack request, rollBack all transactionables
2009-08-12T07:58:49+00:00 DEBUG (7): Tinebase_Server_Json::handle::117 got exception code0
2009-08-12T07:58:49+00:00 DEBUG (7): Zend_Json_Server:
exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20/tine20_accounts`, CONSTRAINT `tine20_accounts::primary_group_id--groups::id` FOREIGN KEY (`primary_group_id`) REFERENCES `tine20_groups` (`id`))&#039; in /var/www/webim/tine/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/webim/tine/library/Zend/Db/Statement.php(283): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/webim/tine/library/Zend/Db/Adapter/Abstract.php(430): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/webim/tine/library/Zend/Db/Adapter/Pdo/Abstract.php(220): Zend_Db_Adapter_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#3 /var/www/webim/tine/library/Zend/Db/Adapter/Abstract.php(508): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;INSERT INTO `ti...&#039;, Array)
#4 /var/www/webim/tine/library/Zend/Db/Table/Abstract.php(815): Zend_Db_Adapter_Abstract-&gt;insert(&#039;tine20_accounts&#039;, Array)
#5 /var/www/webim/tine/Tinebase/User/Sql.php(474): Zend_Db_Table_Abstract-&gt;insert(Array)
#6 /var/www/webim/tine/Tinebase/User/Ldap.php(188): Tinebase_User_Sql-&gt;addUser(Object(Tinebase_Model_FullUser))
#7 /var/www/webim/tine/Tinebase/User/Abstract.php(214): Tinebase_User_Ldap-&gt;getUserByLoginName(&#039;mylogin&#039;, &#039;Tinebase_Model_...&#039;)
#8 /var/www/webim/tine/Tinebase/Controller.php(73): Tinebase_User_Abstract-&gt;getFullUserByLoginName(&#039;mylogin&#039;)
#9 /var/www/webim/tine/Tinebase/Frontend/Json.php(271): Tinebase_Controller-&gt;login(&#039;mylogin&#039;, &#039;mypass&#039;, &#039;10.5.0.15&#039;)
#10 [internal function]: Tinebase_Frontend_Json-&gt;login(&#039;mylogin&#039;, &#039;mypass&#039;)
#11 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Json), Array)
#12 /var/www/webim/tine/library/Zend/Server/Reflection/Function/Abstract.php(371): call_user_func_array(Array, Array)
#13 [internal function]: Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#14 /var/www/webim/tine/Zend/Json/Server.php(144): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Json), Array)
#15 /var/www/webim/tine/Tinebase/Server/Json.php(108): Zend_Json_Server-&gt;handle(Array)
#16 /var/www/webim/tine/Tinebase/Core.php(162): Tinebase_Server_Json-&gt;handle()
#17 /var/www/webim/tine/index.php(51): Tinebase_Core::dispatchRequest()
#18 {main}

**Comment by Gloirin** [comment]
**Comment posted by unknown user on 14 Oct 2009 08:32**

Since r10973 it is possible to switch between accounts storage backend (Database/Ldap).

Note however, that switching from Database to Ldap will delete all existing accounts, groups, roles and rights and then get re-created/imported from Ldap. Of course, you have to confirm a warning message before this will happen.

Switching from Ldap to mySql simply disconnects from Ldap and continues working with the mirrored Database accounts/groups.
