### ISSUE TITLE
0001750:
problems with 'synckey' and 'lastfiltertype' : synchonization no longer possible

### ISSUE THREAD

**Issue by Gloirin** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#959]
**Reported by joebel on 7 Oct 2009 05:45**

**Version:** August (2009-11) Milestone 1

After uopgrading to Milestone 1, activesync is no longer working. An error message involving synckeys is shown in the tine20.log (shown under Additional Information in this report). Error kept repeating at each try.

After removing the synchronization account on the windows mobile phone, and later reentering the synchronization account, I get complains in the tine20 log concerning &#039;lastfiltertype&#039; data that is unavailable. This message is also included under Additional Information in this report. Error kept repeating at each try.

**Additional information:** 1. Error messages after upgrading to Milestone 1:

- tine20.log:
2009-10-04T15:12:41+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::101 sync timestamp: 2009-10-04 15:12:41
2009-10-04T15:12:41+00:00 INFO (6): ActiveSync_Command_GetItemEstimate::handle::87 synckey is 2 class: Contacts collectionid: addressbook-root filtertype: 0
2009-10-04T15:12:41+00:00 INFO (6): ActiveSync_Command_GetItemEstimate::handle::87 synckey is 73 class: Calendar collectionid: calendar-root filtertype: 5
2009-10-04T15:12:41+00:00 INFO (6): ActiveSync_Command_GetItemEstimate::handle::87 synckey is 35 class: Tasks collectionid: tasks-root filtertype: 0
2009-10-04T15:12:41+00:00 WARN (4): ActiveSync_Command_GetItemEstimate::handle::90 invalid synckey 35 provided

- Apache error log:
HP Fatal error: Uncaught exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;record object is not valid&#039; in /var/www/tine20/Tinebase/Backend/Sql/Abstract.php:393\nStack trace:\n#0 /var/www/tine20/ActiveSync/Command/GetItemEstimate.php(177): Tinebase_Backend_Sql_Abstract-&gt;update(Object(ActiveSync_Model_FolderState))\n#1 /var/www/tine20/ActiveSync/Frontend/Http.php(101): ActiveSync_Command_GetItemEstimate-&gt;getResponse()\n#2 /var/www/tine20/ActiveSync/Server/Http.php(88): ActiveSync_Frontend_Http-&gt;handlePost(&#039;rvromen&#039;, &#039;05AB2BCA989F84B...&#039;, &#039;PocketPC&#039;, &#039;GetItemEstimate&#039;)\n#3 /var/www/tine20/Tinebase/Core.php(180): ActiveSync_Server_Http-&gt;handle()\n#4 /var/www/tine20/index.php(51): Tinebase_Core::dispatchRequest()\n#5 {main}\n thrown in /var/www/tine20/Tinebase/Backend/Sql/Abstract.php on line 393

2. After removing an reentering  the synchronization account on WIndows Mobil:
- tine20.log:
2009-10-04T19:01:11+00:00 DEBUG (7): ActiveSync_Command_FolderSync::handle::101 synckey is 0
2009-10-04T19:01:11+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Contacts
2009-10-04T19:01:11+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Tasks
2009-10-04T19:01:11+00:00 INFO (6): ActiveSync_Command_FolderSync::getResponse::123 class: Calendar
2009-10-04T19:01:12+00:00 DEBUG (7): ActiveSync_Command_FolderSync::getResponse::173 Contacts
2009-10-04T19:01:12+00:00 DEBUG (7): Tinebase_Record_Abstract:
Array
(
    [0] =&gt; Array
        (
            [id] =&gt; lastfiltertype
            [msg] =&gt; Array
                (
                    [isEmpty] =&gt; You must give a non-empty value for field &#039;lastfiltertype&#039;
                )

        )

)
exception &#039;Tinebase_Exception_Record_Validation&#039; with message &#039;some fields lastfiltertype have invalid content&#039; in /var/www/tine20/Tinebase/Record/Abstract.php:441
Stack trace:
#0 /var/www/tine20/Tinebase/Record/Abstract.php(302): Tinebase_Record_Abstract-&gt;isValid(true)
#1 /var/www/tine20/Tinebase/Record/Abstract.php(174): Tinebase_Record_Abstract-&gt;setFromArray(Array)
#2 /var/www/tine20/ActiveSync/Command/FolderSync.php(215): Tinebase_Record_Abstract-&gt;__construct(Array)
#3 /var/www/tine20/ActiveSync/Command/FolderSync.php(181): ActiveSync_Command_FolderSync-&gt;_addFolderState(&#039;Contacts&#039;, &#039;addressbook-roo...&#039;)
#4 /var/www/tine20/ActiveSync/Frontend/Http.php(101): ActiveSync_Command_FolderSync-&gt;getResponse()
#5 /var/www/tine20/ActiveSync/Server/Http.php(88): ActiveSync_Frontend_Http-&gt;handlePost(&#039;username&#039;, &#039;05AB2BCA989F84B...&#039;, &#039;PocketPC&#039;, &#039;FolderSync&#039;)
#6 /var/www/tine20/Tinebase/Core.php(180): ActiveSync_Server_Http-&gt;handle()
#7 /var/www/tine20/index.php(51): Tinebase_Core::dispatchRequest()

**Comment by Gloirin** [comment]
**Comment posted by joebel on 7 Oct 2009 11:15**

just looked into the database:
- the mobile phone IS listed in  tine20_acsync_device;
- there are NO entries in tine20_acsync_folder (end therefore no lastfiltertype values) for the corresponding device-id

**Comment by Gloirin** [comment]
**Comment posted by joebel on 7 Oct 2009 12:40**

Removing the activesync app (therefore remving the tables), then enabling the activesync app (--&gt; fresh tables): same effect.

removing Zend-cache from /tmp: no effect

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 8 Oct 2009 05:55**

I fixed the problem in SVN. We will backport the fix the last milestone and will build new packages.

Thanks for the good bugreport!
